### ISSUE TITLE
X-Axis does not adjust itself when setting a ColumnSeries width 

### ISSUE THREAD

**Issue by MsXam** [syncfusion/flutter-examples#10]
As can be seen from the snapshot - when width is set for a column series, the x-axis fails to adjust properly. 

![image](https://user-images.githubusercontent.com/18722796/63033006-d2b25400-beae-11e9-9f08-1b374dba2e00.png)

**Comment by JayavigneshwaranG** [comment]
Hi MsXam,

Thanks for trying our Flutter widgets.
We have analyzed your query and we wish to let you know that, the width of the column value ranges from 0 to 1. If we specify higher than that, it will apply but it occupies the space of another column, thus the columns are overlapping. This is the behaviour of column spacing and width. So to avoid overlapping, we suggest you to specify a value between 0 and 1 to the column width property. By default, the column width value is 0.7.

Also, we have depicted the column spacing and width functionality in our SB. Please find the sample code from the below link. Width and spacing value can be changed by the options in the bottom sheet.
https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/column_series/column_width_and_spacing.dart

Please refer the below UG documentation link for more details.
https://help.syncfusion.com/flutter/chart/cartesian-chart-types#column-width-and-spacing

Thus I am closing this issue now.
If you still face any concerns, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update the responses there.

Thanks,
Jayavigneshwaran
