### ISSUE TITLE
Detect Panning Faster

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#101]
The plot seems to not register that you are panning until you have pressed the screen and moved a pretty far distance. I would like to decrease the distance you have to move while touching the screen for the plot to start panning. 

You can see this behavior in the video. It shows how far you have to drag for the panning to begin.
https://www.youtube.com/watch?v=_epXvLTAsi8&feature=youtu.be

I also noticed that it won't register panning at all if you move too slowly. I would also like to lower the threshold speed if possible.

I think this would make the plots feel more responsive and easier to use.

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed the reported scenario. We would like to let you know that, there is a performance lag in panning with the GestureDetector widget. We have reported this issue to the Flutter team. So, the reported scenario regarding the panning is not an issue with our chart widget. You can find the github issue below.

https://github.com/flutter/flutter/issues/54359 

Thanks,
Dharani.
