### ISSUE TITLE
Can't Remove Header from Trackball Tooltip

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#102]
When I upgraded syncfusion to ^18.1.36, the header in my trackball tooltip started appearing. I'm trying to show point.x and point.y on one row. Is this possible in 18.1.36?

This is the problem:
![image](https://user-images.githubusercontent.com/50309714/78461422-c0cc2e00-7696-11ea-8ea3-db8544b813d4.png)

This is what I want:
![image](https://user-images.githubusercontent.com/50309714/78461371-47344000-7696-11ea-91af-a5413a59014b.png)

Code:
```
trackballBehavior: TrackballBehavior(
                  enable: true,
                  shouldAlwaysShow: true,
                  tooltipAlignment: ChartAlignment.near,
                  tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
                  lineType: TrackballLineType.vertical,
                  lineColor: trackerLineColor,
                  lineWidth: trackerLineWidth,
                  activationMode: ActivationMode.singleTap,
                  tooltipSettings:
                      InteractiveTooltip(format: 'point.x  point.y', 
                                         borderWidth: 3, 
                                         borderColor: Colors.transparent, 
                                         color: tooltipBackgroundColor, 
                                         textStyle: ChartTextStyle(color: tooltipTextColor, fontSize: 20, fontWeight: FontWeight.w800))
)
```

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed your query. No, with v18.1.36 we didn’t provide an option for customizing the header. However, we have provided an option for customizing now which is under the testing phase. This will be included in our upcoming patch release which is expected to be rolled out on April 7, 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Thanks for being patience. Now you can customize the header of the trackball using the **onTrackballPositionChanging** event. Find the code below to hide the header of the trackball.

> 
     SfCartesianChart(
             onTrackballPositionChanging: (TrackballArgs args) {
                args.chartPointInfo.header = null;
            },
 )

To achieve this scenario, kindly upgrade your chart widget package from below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.44 

Thanks,
Dharani.
