### ISSUE TITLE
SingleChildScrollView and Row are superfluous

### ISSUE THREAD

**Issue by tenSunFree** [syncfusion/flutter-examples#104]
SingleChildScrollView and Row are superfluous
![2020-04-07_115806](https://user-images.githubusercontent.com/23090085/78628825-fa37b000-78c7-11ea-9162-cc9410324694.jpg)

Maybe you can change it like this
![2020-04-07_120155](https://user-images.githubusercontent.com/23090085/78628828-01f75480-78c8-11ea-866c-9dd1a3964b96.jpg)

**Comment by dharanidharandharmasivam** [comment]
Hi @tenSunFree ,

Greetings from Syncfusion. We have reviewed the given screenshots, and we would like to know that if you have faced any problems with our Flutter widgets. If it does, please include more detail about yours. This will be beneficial in presenting the solution sooner.

Thanks,
Dharani.
