### ISSUE TITLE
Axis Value Range Inconsistent

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#106]
Sometimes the Y-Axis range is not being set in a way that fits the data in the center of the plot.

I attached 2 images. They have the same chart configuration. The only difference is in the data provided in the series parameter of the X and Y axis.

The problem here is that Y-axis starts at 0. This causes the plotted line to be squeezed into the top of the plot.
![image](https://user-images.githubusercontent.com/50309714/78842686-b085bd00-79ce-11ea-8cd3-83b19436ffaa.png)

Somehow for this other data on the same plot, it knows to not start the Y-axis at 0, and it looks better.
![image](https://user-images.githubusercontent.com/50309714/78842705-c4312380-79ce-11ea-9960-f5d63e606c32.png)

**Comment by opalr** [comment]
I made an algorithm to determine the min and max y for the viewable axis range:

```
var valueRange = yValMax - yValMin;
var divideAmount = pow(10, valueRange.toString().length-1);

var yViewMin = ((yValMin / divideAmount).floor()).toDouble()*divideAmount;
var yViewMax = ((yValMax / divideAmount).ceil()).toDouble()*divideAmount;
```
After setting minimum and maximum to yViewMin and yViewMax in NumericAxis:
![image](https://user-images.githubusercontent.com/50309714/78853939-20f00680-79ee-11ea-9c0b-8a1587633e1f.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed the requirement with the provide screenshots. We would like to let you know that for line type series, the ranges will be calculated from zero and it also depends upon the data sources. If you wish to change this, you can either specify the ranges to **minimum**/**maximum** properties of the axis or you can use the **rangePadding** option. For more information on rangePadding, find the user guide below.

https://help.syncfusion.com/flutter/chart/axis-types#applying-padding-to-the-range 

We have prepared a sample based on this, which can be found below.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/rangepadding746100398

Code snippet:

> 
    SfCartesianChart(
                      primaryYAxis: NumericAxis(
                        rangePadding: ChartRangePadding.round
                      ),
                  )

Thanks,
Dharani.
