### ISSUE TITLE
Stacked Spline Series

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#108]
Is it possible to create a plot with 2 spline series? From the docs, it seems that it is only possible to stack line series.

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. No, as of now we haven’t provided support for stacked spline series. So, we have considered and logged your scenario as a new feature request. The requested feature will be available in any of our upcoming releases and you can track the status of the feature from our feedback portal below.
https://www.syncfusion.com/feedback/13359 

Thanks,
Dharani.
