### ISSUE TITLE
Box plot chart types

### ISSUE THREAD

**Issue by jfox454** [syncfusion/flutter-examples#109]
Can you please add support for box plot charts

https://en.wikipedia.org/wiki/Box_plot

**Comment by SriramKiranSenthilkumar** [comment]
Hi @jfox454 ,
   Yes, we have considered your requirement for box-plot support as a new feature request. We will include the requested feature in one of our upcoming releases yet to come. You can track the status of the feature below.

https://www.syncfusion.com/feedback/13379/a-new-box-plot-chart-type

Thanks,
Sriram Kiran
