### ISSUE TITLE
trying to transpose the axis and pan yields exception

### ISSUE THREAD

**Issue by MsXam** [syncfusion/flutter-examples#11]
In a Catersian Chart using a Column series, when we transpose and try to pan we get an exception : 

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
#1      ZoomPanBehavior._doubleTapZooming 
package:syncfusion_flutter_charts/…/user_interaction/zooming_panning.dart:203
#2      ZoomPanBehavior.onDoubleTap 
package:syncfusion_flutter_charts/…/user_interaction/zooming_panning.dart:594
#3      _ContainerArea._bindInteractionWidgets.<anonymous closure> 
package:syncfusion_flutter_charts/…/base/chart_base.dart:1775
#4      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
...
Handler: "onDoubleTap"
Recognizer: DoubleTapGestureRecognizer#31719
    debugOwner: GestureDetector
════════════════════════════════════════════════════════════════════════════════

**Comment by JayavigneshwaranG** [comment]
Hi @MsXam ,

We have tried to replicate the reported issues by rendering column chart, transposing it and by enabling double-tap zooming and panning. But the reported is not replicated at out end. Zooming and panning are working properly. Attached the screen recorded video in the below link for your reference.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/20190815_1211111419799435

Also attached the sample used for testing below for your reference.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/chart1152506987

As we didn’t know your exact scenario, we couldn’t replicate this. We request you to revert your sample code or revert the sample which we have attached, by modifying your scenario in it. This will be helpful for us to reproduce the issue and to resolve it ASAP.

Also please ensure whether you were using the latest version(1.0.0-beta.3) of our package in your example and latest Flutter SDK.

Thanks,
Jayavigneshwaran

**Comment by MsXam** [comment]
We are using latest SF plugin as well as Flutter 1.7.8 hotfix 4, dart 2.4.0

To reproduce : 

1. Ensure your chart has a legend
2. Go into zoom/panning mode on chart
3. Tap a legend item to hide a column
4. Now tap chart, try to pan - you will see exception thrown in Debug Console

**Comment by dharanidharandharmasivam** [comment]
Hi @MsXam ,

We have analyzed your query. On panning with the transposed chart throws the below exception. 

`I/flutter (15040): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15040): The following NoSuchMethodError was thrown while dispatching a pointer event:
I/flutter (15040): The method 'contains' was called on null.
I/flutter (15040): Receiver: null
I/flutter (15040): Tried calling: contains(Instance of 'Offset')
I/flutter (15040): When the exception was thrown, this was the stack:
I/flutter (15040): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
I/flutter (15040): #1      _ContainerArea._bindInteractionWidgets._findSeries 
package:syncfusion_flutter_charts/…/base/chart_base.dart:1438
I/flutter (15040): #2      _ContainerArea._bindInteractionWidgets.<anonymous closure> 
package:syncfusion_flutter_charts/…/base/chart_base.dart:1532
I/flutter (15040): #3      RenderPointerListener.handleEvent 
package:flutter/…/rendering/proxy_box.dart:2683
I/flutter (15040): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
I/flutter (15040): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent `

But we would like to confirm whether you are specifying the above issue? If this is the case, then we have logged bug report in our feedback portal and the status of the bug can be tracked from below feedback portal link.

https://www.syncfusion.com/feedback/8284 

We will fix the bug and include it in our upcoming release. Please let us know if you have any concerns.

Thanks,
Dharanidharan.

**Comment by dharanidharandharmasivam** [comment]
Hi @MsXam ,

Thanks for being patience. We have fixed the above issue, now on panning with the transposed chart, the exception will not be thrown. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Kindly revert us if you have any concerns.

Thanks,
Dharani.
