### ISSUE TITLE
Option to Set Trackball Position

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#111]
I have an idea for a new feature. It allows you to set the position of the trackball in SfCartesianChart using a variable.

For example, there could be a chart of Balance vs. Time on the top of the screen, and a list of transactions below that. As the user scrolls down the transactions list, the chart's trackball would be set to the x-axis location (time) of the transaction in the list currently visible to the user.

Edit: I figured out that I can achieve this by plotting another set of data on the same chart to show the position. This image shows a column plotted at the desired x-location, which can be updated dynamically.

![image](https://user-images.githubusercontent.com/50309714/79052217-edd29080-7c02-11ea-8c18-fd2f43531e6c.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @opalr ,

We have analyzed your scenario. As of now, you can achieve this scenario by using **PlotBand** feature in the chart in which you can provide the start and end value to achieve the required scenario. Also, we have provided a simple sample for the usage of **PlotBand** feature in the chart.

 **screenshot:**
![plotbandexample](https://user-images.githubusercontent.com/63577117/79113348-55711300-7d9e-11ea-9712-70dd5dc41dcc.png)

 The reference sample can be found below.
[plotband.zip](https://github.com/syncfusion/flutter-examples/files/4469103/plotband.zip)
 
Also for further reference check our user guide link provided below,
https://help.syncfusion.com/flutter/chart/axis-customization#plot-bands.

Thanks,
Sriram Kiran

**Comment by opalr** [comment]
I'm finding that redrawing the SfCartesianPlot every time the plot band needs to move causes performance issues / running at less than 60 Hz. My data consists of 12 points and I'm attempting to redraw the chart every ~0.1 seconds. This performance issue also exists when plot band is disabled while still attempting to redraw the chart every ~0.1 seconds.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @opalr ,
We have further analysed your scenario and we suspect that you need to show only the trackball line without tooltip.  You can use the onTrackballPositionChanging event in the chart for achieving the scenario. We have included some improvements with trackball in v18.1.44 and to use this kindly upgrade your package from below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.44

Please check the below code snippet.
```
 SfCartesianChart(
             onTrackballPositionChanging: (TrackballArgs args) {
                args.chartPointInfo.label = null;
                args.chartPointInfo.header = null;
            },
 )
```
The sample for reference can be found below.
[trackballevent.zip](https://github.com/syncfusion/flutter-examples/files/4476362/trackballevent.zip)

For further reference on `onTrackballPositionChanging`, please check our user guide below:
https://help.syncfusion.com/flutter/chart/events#ontrackballpositionchanging
 
You can also show the trackball dynamically using the public methods available. Please refer the below code snippet in which we have used the show method in the `onPressed` event of `FlatButton` to show the trackball.

```
FlatButton(
          child: Text('Show'),
          onPressed:() {
              trackball.show(DateTime(2019,1,3,15), 340);
           }
 ),

```
The sample for reference can be found below.
[trackballmethods.zip](https://github.com/syncfusion/flutter-examples/files/4476367/trackballmethods.zip)

For further reference on trackball's public methods, please check our user guide below:
https://help.syncfusion.com/flutter/chart/methods#methods-in-trackballbehavior


Thanks,
Sriram Kiran.

**Comment by opalr** [comment]
Showing the trackball with trackball.show() works well. It would be awesome if the TrackballBehavior had options for animation like duration and curve. It would also be nice to be able to make the trackball a marker with a shape option (I would make it a circle). My goal is to make this marker/trackball follow the plotted line and animate smoothly between positions when I use trackball.show().

To test the animation part of this idea, I created an animated container that overlays the SfCartesionChart and moves to certain positions as the plotband would. Now that I've seen how good animation looks, I won't be able to go back to non-animated things. I think adding animation to trackball would be a nice feature to have.

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

We have analyzed your scenario. Your requirement can be achieved as a workaround. Here, we have drawn the marker using the custom painter for the trackball and positioned the marker using the onTrackballPositionChanging event. And as of now we don’t have support for the duration and curve support for the trackball. Find the code snippet to accomplish this.

> 
     CustomTrackball customTrackball;
     Stack(children: <Widget>[
              SfCartesianChart(
                  onTrackballPositionChanging: (TrackballArgs args) {
                    xPos = args.chartPointInfo.markerXPos;
                    yPos = args.chartPointInfo.markerYPos;
                    customTrackballRepaintNotifier.value++;
                  },
                  trackballBehavior: customTrackball,
                  //Other configurations
              ),
              CustomPaint(
                  painter: DrawCircle(notifier: customTrackballRepaintNotifier))
            ])
            class DrawCircle extends CustomPainter {
               //Drawn the marker here
            }
            class CustomTrackball extends TrackballBehavior {
                //Other configurations
               @override
               void onTouchUp(double x, double y) {
                     //To hide the marker on touch up
                     xPos = yPos = null;
                     super.onTouchUp(x, y);
                }
        }

The sample for reference can be found below. 
[marker.zip](https://github.com/syncfusion/flutter-examples/files/4485556/marker.zip)

Thanks,
Dharani.
