### ISSUE TITLE
Custom increment and reset (using inches on an axes) 

### ISSUE THREAD

**Issue by simeon9696** [syncfusion/flutter-examples#118]
This isn't an issue more a question of approach so I avoid reinventing the wheel. 

I want to place a range of 0 to 3ft on an axes but have the interval increase in inches. Since 12 inches make 1 foot the markings would have to reset at 12

Ideally I'd like to blend feet and inches on the same axis so that is reads: 

0ft 1 2 3 4 5 6 7 8 9 10 11 1ft 1 2 3 4 5 6 7 8 9 10 11 2ft ...etc

Would I have to use a custom axis to do this or is there some other functionality built in?

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,
 
We have analyzed the customer approach scenario at our end, and we have created and attached a simple sample below for customizing the axis label for blending feet and inches on the same axis as requested using the onAxisLabelRender event available in the chart. Please refer the code snippet below.
``` SfCartesianChart(
            onAxisLabelRender: (AxisLabelRenderArgs args) {
              if (args.axisName == 'primaryYAxis') {
                  if(args.value == 0) {
                    args.text = '0ft';
                  } else {
                    if (args.value % 12 != 0) {
                      inchCount =inchCount +1;
                      args.text = '${inchCount}';
                    }
                    else {
                      inchCount = 0;
                      feetFlag = feetFlag+1;
                      args.text = '${feetFlag}'+'ft';
                    }
                  }
              }
            },
)
```

Screenshot:
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/63577117/80370072-f5ee2980-88ac-11ea-8857-5d91ec0a0aa4.png) 

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4539436/sample.zip)
 
For further reference on onAxisLabelRender event, please check the user guide link below.
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onaxislabelrender
 
Thanks,
Sriram Kiran.

**Comment by simeon9696** [comment]
Y'all are the best! Thank you!

**Comment by simeon9696** [comment]
Y'all are the best, thank you! Would this work on the radial gauges are well?

**Comment by DeviArunaMurugan** [comment]
Hi @simeon9696 ,

We have prepared a sample using radial gauge widget by customizing its axis labels to display feet and inches on the radial axis. This requirement is achieved by using the **onLabelCreated** event of the radial axis as shown in the below code example,

```
@override
Widget build(BuildContext context) {
 return Scaffold(
   body: Center(
     child: SfRadialGauge(
       axes: <RadialAxis>[
         RadialAxis(minimum: 0, maximum: 24, interval: 1,
             onLabelCreated: onAxisLabelCreated)
       ],
     ),
   ),
 );
}


void onAxisLabelCreated(AxisLabelCreatedArgs args) {
  if (args.text == '0') {
    args.text = '0ft';
  } else {
    double _value = double.parse(args.text);
    if (_value  % 12 != 0) {
      inchCount = inchCount + 1;
      args.text = '$inchCount';
    }
    else {
      inchCount = 0;
      feetFlag = feetFlag + 1;
      args.text = '$feetFlag' + 'ft';
    }
  }
}
```
Screenshot: 
![image](https://user-images.githubusercontent.com/55730024/80694509-3b4f6880-8af2-11ea-9207-22007f1734ee.png)


Please find the demo sample
[custom_labels.zip](https://github.com/syncfusion/flutter-examples/files/4557342/custom_labels.zip)

Regards,
Devi

**Comment by simeon9696** [comment]
Thank you!
