### ISSUE TITLE
DataLabelSettings and MarkerSettings image

### ISSUE THREAD

**Issue by B0yma** [syncfusion/flutter-examples#12]
Im trying to set custom marker with visible labels:
`

            //primaryXAxis: CategoryAxis(),
            // Chart title
            //title: ChartTitle(text: 'Half yearly sales analysis'),
            // Enable legend
            legend: Legend(isVisible: false),
            // Enable tooltip
            tooltipBehavior: TooltipBehavior(enable: true),
            zoomPanBehavior: ZoomPanBehavior(
                enablePinching: true,
                zoomMode: ZoomMode.x,
                enablePanning: true),
            series: <ChartSeries<DskPoint, num>>[
              LineSeries<DskPoint, num>(
                dataSource: <DskPoint>[
                  DskPoint(0, 35),
                  DskPoint(1, 28),
                  DskPoint(2, 34),
                  DskPoint(3, 32),
                  DskPoint(4, 40)
                ],
                xValueMapper: (DskPoint sales, _) => sales.x,
                yValueMapper: (DskPoint sales, _) => sales.y,
                dataLabelSettings: DataLabelSettings(isVisible: true),
                //markerSettings: MarkerSettings(isVisible: true, shape: DataMarkerType.rectangle),
                 markerSettings: MarkerSettings(
                    isVisible: true,
                    shape: DataMarkerType.image,
                    imageUrl: 'images/truck.png'),
                // Enable data label
              ),
              ScatterSeries<DskPoint, num>(
                  dataSource: <DskPoint>[
                    DskPoint(1, 10)
                  ],
                  xValueMapper: (DskPoint sales, _) => sales.x,
                  yValueMapper: (DskPoint sales, _) => sales.y,
                  //markerSettings: MarkerSettings(isVisible: true, shape: DataMarkerType.rectangle),
                  markerSettings: MarkerSettings(
                      isVisible: true,
                      shape: DataMarkerType.image,
                      imageUrl: 'images/truck.png'),
                  name: 'India'),
            ]),
      )),`
the values is dissapearing, but when we scroll chart labels comes to visible state,when stop scrolling they dissapear again..

**Comment by dharanidharandharmasivam** [comment]
Hi @B0yma ,

We have analyzed your scenario and we can replicate the reported issue. The data label text gets hidden on scrolling when we use the marker shape as an image. So, we have a logged bug report for this scenario at our end. 

We will fix the bug and include it in our upcoming update. We appreciate your patience until then.

Thanks,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @B0yma ,

Thanks for being patience. The reported issue has been fixed, now the data labels will be visible properly on scrolling. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Kindly let us know if you have any concerns.

Thanks,
Dharani.

**Comment by JayavigneshwaranG** [comment]
Hi @B0yma  ,

We are closing this issue now, as it is resolved.
If you still face any concerns, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update the responses there.

Thanks,
Jayavigneshwaran
