### ISSUE TITLE
cannot use arabic

### ISSUE THREAD

**Issue by Nismaiel** [syncfusion/flutter-examples#121]
i have problem with the font itself (failed to open the file)
can you give me any kind of guidance because this is the only plugin supports arabic and rtl

**Comment by Nismaiel** [comment]
i figured it out

**Comment by evangelme** [comment]
@Nismaiel can you tell me how could u figured it out to use shamsi or jalali date ? thank u

**Comment by Indumathi1195R** [comment]
Hi @evangelme, 

Based on the provide information, we have checked, and your requirement is “**Hijri/Jalali/Shamsi calendar support in SfDateRangePicker or SfCalendar**” and we have logged the feature request for the both controls. We will implement this feature in any of our upcoming releases. We appreciate your patience until then. 

You can track the current status of this report by the following link, 

**Feedback links:** 
https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar
https://www.syncfusion.com/feedback/16598/provide-a-support-for-hijri-jalali-calendar-in-date-range-picker-sfdaterangepicker

Also, we have provided the RTL support for both SfCalendar and sfDateRangePicker controls. Please find the UG and KB documentation links.

**UG links:**
https://help.syncfusion.com/flutter/calendar/right-to-left
https://help.syncfusion.com/flutter/daterangepicker/right-to-left

**KB links:**
https://www.syncfusion.com/kb/11442/how-to-change-the-working-directions-rtl-of-the-flutter-calendar-sfcalendar
https://www.syncfusion.com/kb/11758/how-to-change-the-working-direction-rtl-of-the-flutter-date-range-picker-sfdaterangepicker

Regards,
Indumathi R

**Comment by evangelme** [comment]
@Indumathi1195R  thank u i reallly looking forward to this features.
but this link https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar
is private feedback can you make it public so we can see updates and things thank u again for ur awsome project.

**Comment by Indumathi1195R** [comment]
Hi @evangelme,

Thank you for the update. We have changed the feedback to the public and you get future updates regarding this feature.

Regards,
Indumathi R

**Comment by shero1111** [comment]
Hello,

Any updates regarding Hijri Calendar? 

HijriDateRangePicker is awesome, but we need also an `SfHijriCalendar`.

Is this already implemented?

Yours sincerely,
