### ISSUE TITLE
[PDF] Crash "The character is not supported by the font."

### ISSUE THREAD

**Issue by kinex** [syncfusion/flutter-examples#122]
I get exception `ArgumentError (Invalid argument (The character is not supported by the font.): 8332)`

I have no idea what is the "invalid" character causing this crash. I am drawing normal text.

```
_StandardWidthTable._returnValue (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_font_metrics.dart:106)
_StandardWidthTable.[] (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_font_metrics.dart:103)
PdfStandardFont._getCharWidthInternal (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_standard_font.dart:65)
PdfStandardFont._getLineWidth (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_standard_font.dart:91)
_PdfStringLayouter._getLineWidth (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_string_layouter.dart:256)
_PdfStringLayouter._layoutLine (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_string_layouter.dart:106)
_PdfStringLayouter._doLayout (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_string_layouter.dart:48)
_PdfStringLayouter._layout (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\fonts\pdf_string_layouter.dart:36)
PdfGridCell._measureHeight (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid_cell.dart:226)
PdfGridCell.height (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid_cell.dart:50)
PdfGridRow._measureHeight (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid_row.dart:123)
PdfGridRow.height (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid_row.dart:51)
_PdfGridLayouter._drawRow (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\layouting\pdf_grid_layouter.dart:791)
_PdfGridLayouter._layoutOnPage (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\layouting\pdf_grid_layouter.dart:140)
_PdfGridLayouter._layoutInternal (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\layouting\pdf_grid_layouter.dart:1441)
PdfGrid._layout (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid.dart:536)
PdfLayoutElement.draw (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\graphics\figures\base\layout_element.dart:25)
PdfGrid.draw (c:\Users\me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-18.1.48-beta\lib\src\pdf\implementation\structured_elements\grid\pdf_grid.dart:502)

```

**Comment by AnandJayachithra** [comment]
Hi Kinex,

We found that you are using PDF standard font to draw the Unicode characters like euro symbol ("€"). The PDF standard fonts are not support to draw the Unicode characters, so we have suggest you to use the PdfTrueTypeFont API to preserve the Unicode characters properly.
 
Please refer the following documentation for more details about PdfTrueTypeFont.
https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-truetype-fonts

With Regards,
Anand

**Comment by kinex** [comment]
Yeah that was the issue. I was wondering because it worked earlier and then suddenly stopped working. Then I remembered that I had changed my device region/language from en-US to fi-FI which causes also currency symbol to change from $ to €.

I think this limitation with PDF standard fonts make them pretty useless. For example my app is translated to over 10 languages so there will be Unicode characters in PDF documents I want to create for sure. Using those TrueType fonts seems to require much more work but I guess it is the only option.

Thanks!

**Comment by kinex** [comment]
@AnandJayachithra Do you have any working code sample using `PdfTrueTypeFont` and drawing Unicode characters font in Flutter?
 
I am loading font as follows:
```dart
final fontData = await rootBundle.load('fonts/Roboto-Regular.ttf');
final font  = PdfTrueTypeFont(fontData.buffer.asUint8List(), 12);
```
It is this font: https://fonts.google.com/specimen/Roboto

It doesn't crash anymore but Unicode characters are still not drawn correctly (a crossed box is drawn instead of €). If I format a number as currency the whole text is corrupted.

**Comment by AnandJayachithra** [comment]
Hi Kinex,

The provided font has advanced typography tables, due to this, the text is not preserved as expected. We confirmed this to be a defect in our side and the fix for this issue will be available on our Volume 1 SP1 release. Which will be expected to available on 13th May 2020.

You can track the issue status in the below feedback.
https://www.syncfusion.com/feedback/14199/text-is-not-preserved-when-using-particular-ttf-font

The .ttf font without having the advanced typography glyphs is working now. So we suggest you use the fonts like Open Sans.
https://fonts.google.com/specimen/Open+Sans.

With Regards,
Anand

**Comment by kinex** [comment]
@AnandJayachithra Great to hear you found the reason for the issue. The issue link you provided does not work (even if I sign in). Anyway, I will use that other font as a workaround. Thanks!

**Comment by AnandJayachithra** [comment]
Hi Kinex,

We regret the inconvenience, now the feedback link is accessible.

With Regards,
Anand
