### ISSUE TITLE
[Question] License issue

### ISSUE THREAD

**Issue by scheung38** [syncfusion/flutter-examples#124]
Do we need to pay for license usable?

**Comment by zjl801** [comment]
same question

**Comment by PHPadawan** [comment]
"_To be qualified for the Syncfusion Community License Program you must have a gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization, and agree to be bound by Syncfusion’s terms and conditions._"

https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

**Comment by SriramKiranSenthilkumar** [comment]
Hi @scheung38 ,

Thanks for trying our Flutter widgets.
You can refer the Syncfusion licensing terms and conditions from the below link. The cost is $295 for Flutter (per developer).
https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

And you can get more details about our community license from the below link.
https://www.syncfusion.com/products/communitylicense

If you still have any queries, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update our response there.

Thanks,
Sriram Kiran.
