### ISSUE TITLE
Data Labels don't render on Radial Bar Series

### ISSUE THREAD

**Issue by Sockitos** [syncfusion/flutter-examples#126]
When both Data Label and Legend are toggled visible, the data labels don't render.

Don't know if it helps but:
1. If I have the chart on a PageView.builder and I change page and change back to the chart, he renders the data labels like intended. 
2. I went into your code to find the bug and he is only calling _drawLabel once with animatedOpacity = 0;

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sockitos ,

We have analyzed your scenario and tried to replicate it. Unfortunately, we were not able to replicate the reported scenario. However, we have created a simple sample using a radial bar series and PageView builder for testing the reported issue and attached below for your reference. Kindly try to replicate the reported issue using the attached sample and revert us, this will be helpful in providing the solution sooner. 
Sample:  [sample.zip](https://github.com/syncfusion/flutter-examples/files/4634397/sample.zip)
 
Regards, 
Sriram Kiran.

**Comment by Sockitos** [comment]
Took me a while but I think I got it.
It actually happens when the chart is inside a StreamBuilder. At first, it doesn't build because initialData = [], but when it gets the data and rebuilds, it doesn't render the data labels.
Not sure if it is intended or not but thanks for your help!
I also noticed when I changed orientation on my device he doesn't rerender with data labels.

Sample: [sample.zip](https://github.com/syncfusion/flutter-examples/files/4637369/sample.zip)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sockitos ,

We have analyzed your scenario and we have considered the reported scenario as a bug and we will include the fix for the reported issue in the upcoming patch release which will be rolled out on 26th May 2020. We will update you once the release is rolled out. We appreciate your patience until then.

Thanks,
Sriram Kiran.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sockitos ,

Thanks for your patience. The reported issue regarding the chart’s data labels not rendering when rendered using stream builder is fixed and rolled out. To overcome the reported issue, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.54

Regards,
Sriram Kiran.
