### ISSUE TITLE
Always show tooltip in SfCircularChart with DoughnutSeries

### ISSUE THREAD

**Issue by mithunadhikari40** [syncfusion/flutter-examples#127]
First of all, I want to thank you for this wonderful library. I am using this one extensively in my app. But, I encountered an issue, where I could not always show the tooltip text in the circular chart. However, it does show the tooltip when there are smaller sets of data, for say 4, but when these sets of data increase the tooltip is not always visible. The attached picture displays the issues.

![Screenshot_20200516-115730](https://user-images.githubusercontent.com/16093696/82112438-ad6bb280-976c-11ea-8008-2778b83ff185.png)
![Screenshot_20200516-115748](https://user-images.githubusercontent.com/16093696/82112440-ae9cdf80-976c-11ea-9d2e-9694ba889064.png)

As you can see in the first picture, the tooltip is not visible, but in the second one(Circular Chart), it is. And what I notice is that if I make try to render fewer sets of data, the tooltips are always visible.

Here is my implmentation:
`SfCircularChart(
      margin: EdgeInsets.all(0),
      title: ChartTitle(text: AppLocalizations.of(context).Channel_Sales),
      legend: Legend(
        isVisible: true,
        overflowMode: LegendItemOverflowMode.wrap,
      ),
      series: getChannelSalesTargetForDonut(),
      tooltipBehavior: TooltipBehavior(
        enable: true,
      ),
    );`

`  List<DoughnutSeries<ReportDataModel, String>>
      getChannelSalesTargetForDonut() {
    num totalQuantity = dashboardModel.channelsales?.fold(0, (a, b) {
      return a + b.sales;
    });
    final List<ReportDataModel> list = dashboardModel.channelsales?.map((m) {
      num thisQuantity = m.sales;
      return ReportDataModel(
        objectName: m.channel,
        value: (thisQuantity / totalQuantity) * 100,
      );
    })?.toList();
    return <DoughnutSeries<ReportDataModel, String>>[
      DoughnutSeries<ReportDataModel, String>(
          radius: '80%',
          explode: true,
          explodeOffset: '10%',
          enableTooltip: true,
          dataSource: list,
          enableSmartLabels: true,
          xValueMapper: (ReportDataModel data, _) => data.objectName,
          yValueMapper: (ReportDataModel data, _) => data.value.toPrecision(1),
//          dataLabelMapper: (ChartSampleData data, _) => data.text,
          dataLabelSettings: DataLabelSettings(
            isVisible: true,
          ))
    ];
  }
`

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mithunadhikari40 ,

Thanks for your interest in Syncfusion Flutter charts. We have analyzed your scenario and we found that the tooltip text you are referring to is actually the data labels of the chart. And we tried to replicate the reported issue with a simple sample, unfortunately, we weren’t able to replicate it. However, we have provided the sample used for testing below for your reference. Kindly try to replicate the reported issue with the attached sample or provide your sample with replication steps with your data.

Screenshot of our sample:
![image](https://user-images.githubusercontent.com/63577117/82216988-6382f800-9937-11ea-8815-3bde1e7a83bd.png)
The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4644269/sample.zip) 

Regards,
Sriram Kiran.
