### ISSUE TITLE
[PDF] PdfDocument.dispose crash

### ISSUE THREAD

**Issue by kinex** [syncfusion/flutter-examples#129]
If I draw an image to PDF and finally try to dispose the PdfDocument, the following crash happens:
```
I/flutter (18810): Unsupported operation: Cannot clear a fixed-length list
[38;5;244mI/flutter (18810): #0      FixedLengthListMixin.clear  (dart:_internal/list.dart:58:5)[39;49m
[38;5;248mI/flutter (18810): #1      _PdfStream.dispose[39;49m
[38;5;248mI/flutter (18810): #2      _PdfMainObjectCollection._dispose[39;49m
[38;5;248mI/flutter (18810): #3      _PdfCrossTable._dispose[39;49m
[38;5;248mI/flutter (18810): #4      PdfDocument.dispose[39;49m
```
Here is how I get the image:
```dart
  Future<Uint8List> _getPngScreenShotBytes() async {
    final boundary = _previewContainer.currentContext.findRenderObject()
        as RenderRepaintBoundary;
    final image = await boundary.toImage(pixelRatio: 1);
    final byteData = await image.toByteData(format: ImageByteFormat.png);
    final pngBytes = byteData.buffer.asUint8List();
    return pngBytes;
  }
```

And code for drawing the image:
```dart
  void drawImage(Uint8List imageData, Rect rect) {
    final PdfBitmap image = PdfBitmap(imageData);
    _currentPage.graphics.drawImage(image, rect);
  }
```
syncfusion_flutter_pdf: ^18.1.53-beta
Flutter 1.17.1

**Comment by AnandJayachithra** [comment]
Hi Kinex,

The reported issue “Dispose is not working while drawing screen shot image taken by flutter mobile application” is confirmed as defect. The fix for this issue will be available in next weekly patch release scheduled on 26th May 2020.

Feedback: https://www.syncfusion.com/feedback/14627/dispose-is-not-working-while-drawing-screen-shot-image-taken-by-flutter-mobile

With Regards,
Anand

**Comment by AnandJayachithra** [comment]
Hi Kinex,
 
The fix has been included in the latest weekly patch release with version 18.1.54-beta. Kindly try this in your end and let us know if you need any further assistance. 

With Regards,
Anand

**Comment by kinex** [comment]
Hi Anand,

Yes I can confirm it works now. Thanks!
