### ISSUE TITLE
Gradient is not supported

### ISSUE THREAD

**Issue by xSILENCEx** [syncfusion/flutter-examples#13]
I use gradient just like
```
SplineSeries<MyData, String>(
    //...................
   gradient: LinearGradient(
      colors: [
         Colors.black,
         Colors.red,
      ],
    //.................
)
```
but it doesn't work. Is it wrong to use?

**Comment by dharanidharandharmasivam** [comment]
Hi @xSILENCEx ,

Thanks for your interest in our Syncfusion Flutter chart widget. We have analyzed your scenario. For line type series like line, spline, step line, fast line series gradient support is not applicable. However, if you specify the gradient colors, the first color available in the list will be considered for the series. This is the actual behavior of our chart widget.

As of now, the gradient applicable series are listed below.
•	Column
•	Area
•	Bar
•	Bubble
•	Scatter

Thanks,
Dharani.

**Comment by xSILENCEx** [comment]
Thank U
