### ISSUE TITLE
RangeError (fractionDigits): Invalid value: Not in range 0..20, inclusive: 22

### ISSUE THREAD

**Issue by ydenizs** [syncfusion/flutter-examples#130]
Test data:

`SfCartesianChart(
                  // Initialize category axis
                  primaryXAxis: CategoryAxis(),
                  series: <ChartSeries>[
                    // Initialize line series
                    LineSeries<SalesData, DateTime>(dataSource: [
                      // Bind data source
                      SalesData(DateTime.parse('2020-05-21 00:00:00'), 0.00001468),
                      SalesData(DateTime.parse('2020-05-20 00:00:00'), 0.00001550),
                      SalesData(DateTime.parse('2020-05-19 00:00:00'), 0.00001508),
                      SalesData(DateTime.parse('2020-05-18 00:00:00'), 0.00001494),
                      SalesData(DateTime.parse('2020-05-17 00:00:00'), 0.00001499),
                      SalesData(DateTime.parse('2020-05-16 00:00:00'), 0.00001545),
                      SalesData(DateTime.parse('2020-05-15 00:00:00'), 0.00001555),
                      SalesData(DateTime.parse('2020-05-14 00:00:00'), 0.00001474),
                      SalesData(DateTime.parse('2020-05-13 00:00:00'), 0.00001541),
                      SalesData(DateTime.parse('2020-05-12 00:00:00'), 0.00001623),
                      SalesData(DateTime.parse('2020-05-11 00:00:00'), 0.00001653),
                      SalesData(DateTime.parse('2020-05-10 00:00:00'), 0.00001616),
                      SalesData(DateTime.parse('2020-05-09 00:00:00'), 0.00001479),
                      SalesData(DateTime.parse('2020-05-08 00:00:00'), 0.00001439),
                      SalesData(DateTime.parse('2020-05-07 00:00:00'), 0.00001411),
                      SalesData(DateTime.parse('2020-05-06 00:00:00'), 0.00001519),
                      SalesData(DateTime.parse('2020-05-05 00:00:00'), 0.00001564),
                      SalesData(DateTime.parse('2020-05-04 00:00:00'), 0.00001599),
                      SalesData(DateTime.parse('2020-05-03 00:00:00'), 0.00001601),
                      SalesData(DateTime.parse('2020-05-02 00:00:00'), 0.00001590),
                      SalesData(DateTime.parse('2020-05-01 00:00:00'), 0.00001616),
                      SalesData(DateTime.parse('2020-04-30 00:00:00'), 0.00001660),
                      SalesData(DateTime.parse('2020-04-29 00:00:00'), 0.00001639),
                      SalesData(DateTime.parse('2020-04-28 00:00:00'), 0.00001849),
                      SalesData(DateTime.parse('2020-04-27 00:00:00'), 0.00001841),
                      SalesData(DateTime.parse('2020-04-26 00:00:00'), 0.00001866),
                      SalesData(DateTime.parse('2020-04-25 00:00:00'), 0.00001902),
                      SalesData(DateTime.parse('2020-04-24 00:00:00'), 0.00001910),
                      SalesData(DateTime.parse('2020-04-23 00:00:00'), 0.00001921),
                      SalesData(DateTime.parse('2020-04-22 00:00:00'), 0.00002010),
                    ], xValueMapper: (SalesData sales, _) => sales.date, yValueMapper: (SalesData sales, _) => sales.sales)
 ]),`

`class SalesData {
  SalesData(this.date, this.sales);
  final DateTime date;
  final double sales;
}`

We are experiencing problems with small decimal numbers. 

![image](https://user-images.githubusercontent.com/62982726/82602398-b370f180-9bb9-11ea-8ac6-7528fa0f1c01.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ydenizs ,
 
We regret the inconvenience. We have analyzed your scenario and we are able to replicate it at our end. We have considered this issue as a bug and we will include the fix for the reported issue in the upcoming patch release which is expected to be rolled out on 2nd June 2020. We will update you once the release is rolled out and we appreciate your patience until then.
 
Regards,
Sriram Kiran.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ydenizs ,

Thanks for your patience. The reported issue regarding the chart throwing range error exception when using small decimal numbers as datapoints is fixed and rolled out. To overcome the reported issue, kindly upgrade to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.55

Regards,
Sriram Kiran.
