### ISSUE TITLE
Performing setState to a variable in onTrackballPositionChanging callback stops tooltip & trackball from rendering

### ISSUE THREAD

**Issue by Kinnear** [syncfusion/flutter-examples#132]
Setting setState() to a variable in this example stops the trackball and also the tooltip from rendering. Is this a bug?

`class UserGraphDataPoint {
  UserGraphDataPoint(this.age, this.income, this.expenses, this.liabilities,
      this.cashSavings, this.assets);
  final String age;
  final double income;
  final double expenses;
  final double liabilities;
  final double cashSavings;
  final double assets;
}

class GraphLayout extends StatefulWidget {
  @override
  _GraphLayoutState createState() => _GraphLayoutState();
}

class _GraphLayoutState extends State<GraphLayout> {
  **String stateTest = "";**

  List<UserGraphDataPoint> generateData(
    int clientAge,
    int retirementAge,
    ClientProfile client,
  ) {
    // business logic here
    return data;
  }

  @override
  Widget build(BuildContext context) {
    final userData = Provider.of<GlobalClass>(context);
    String previousChartValue;

    final graphData = generateData(
      userData.user.getAge(),
      userData.user.getRetirementAge(),
      userData.user.clientProfile,
    );

    return Column(
      children: <Widget>[
        Container(
          height: 100.0,
          child: Text(**stateTest**),
        ),
        SfCartesianChart(
          onTrackballPositionChanging: (TrackballArgs args) {
            dynamic testValue = args.chartPointInfo.chartDataPoint.xValue;

            if (testValue.toString() != previousChartValue) {
              previousChartValue = testValue.toString();
              **setState(() {
                stateTest = previousChartValue;
              });**
            }
          },
          legend: Legend(isVisible: true),
          tooltipBehavior: TooltipBehavior(enable: true),
          trackballBehavior: TrackballBehavior(
              enable: true,
              shouldAlwaysShow: true,
              activationMode: ActivationMode.singleTap,
              tooltipSettings: InteractiveTooltip(
                enable: true,
                color: Colors.red,
                format: r"Year point.x : $point.y",
              ),
              tooltipDisplayMode: TrackballDisplayMode.floatAllPoints),
          primaryXAxis: CategoryAxis(),
          series: <ChartSeries>[
            SplineAreaSeries<UserGraphDataPoint, String>(
              enableTooltip: true,
              dataSource: graphData,
              xValueMapper: (UserGraphDataPoint data, _) => data.age,
              yValueMapper: (UserGraphDataPoint data, _) => data.cashSavings,
              name: 'Cash Savings',
              markerSettings: MarkerSettings(isVisible: true, borderWidth: 1.0),
              color: Colors.blue[100],
            ),
            LineSeries<UserGraphDataPoint, String>(
              enableTooltip: true,
              dataSource: graphData,
              xValueMapper: (UserGraphDataPoint data, _) => data.age,
              yValueMapper: (UserGraphDataPoint data, _) => data.income,
              name: 'Income',
              color: Colors.green,
            ),
            LineSeries<UserGraphDataPoint, String>(
              enableTooltip: true,
              dataSource: graphData,
              xValueMapper: (UserGraphDataPoint data, _) => data.age,
              yValueMapper: (UserGraphDataPoint data, _) => data.expenses,
              name: 'Expenses',
              color: Colors.redAccent[50],
            ),
            LineSeries<UserGraphDataPoint, String>(
              enableTooltip: true,
              dataSource: graphData,
              xValueMapper: (UserGraphDataPoint data, _) => data.age,
              yValueMapper: (UserGraphDataPoint data, _) => data.liabilities,
              name: 'Liabilities',
              color: Colors.purple[200],
            ),
            ColumnSeries<UserGraphDataPoint, String>(
              enableTooltip: true,
              dataSource: graphData,
              xValueMapper: (UserGraphDataPoint data, _) => data.age,
              yValueMapper: (UserGraphDataPoint data, _) => data.assets,
              name: 'Assets',
              color: Colors.yellow[200],
              opacity: 0.5,
            ),
          ],
        ),
      ],
    );
  }
}
`

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Kinnear ,

We have analyzed your scenario and we found that you are trying to dynamically update the x-value of the Trackball's data point in the text widget. We were able to replicate the reported issue of trackball and tooltip stops working when `setState` is called in the callback event from the provided code snippet. However, we have created a workaround sample by modifying your provided code snippet and attached below, which will help you in achieving your scenario. In the workaround sample, we have created a separate stateful widget class for the text widget and by using its global key we can refresh this widget from the `onTrackballPositionChanging` event. 

For further reference, please refer the code snippet below.
```
final textWidgetKey = GlobalKey<TextWidgetState>(); // global key for the text widget state class

String stateTest = ''; //Globally declare the string that is to be updated dynamically.

// 1st class configuration for holding the chart and the text widget stateful class.
class GraphLayout extends StatefulWidget {
  GraphLayout({Key key}) : super(key: key);
  @override
  _GraphLayoutState createState() => _GraphLayoutState();
}

class _GraphLayoutState extends State {
  @override
  Widget build(BuildContext context) {
    String previousChartValue;

    return Column(
      children: <Widget>[
        Container(
          height: 100.0,
           // Creating instance for the stateful text widget class which returns the dynamically 
           // 
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4696645/sample.zip)
updating Text widget.
           child: TextWidget(key: textWidgetKey),
        ),
        SfCartesianChart(
          onTrackballPositionChanging: (TrackballArgs args) {
            dynamic testValue = args.chartPointInfo.chartDataPoint.xValue;
            if (testValue.toString() != previousChartValue) {
              previousChartValue = testValue.toString();
              stateTest = previousChartValue;
              // calling the refresh method of the text widget stateclass in order to dynamically update 
              // the x-values of the trackball's datapoint.
              textWidgetKey.currentState.refresh();
            }
          },
          //your configurations
        ),
      ],
    );
  }
}
// 2nd configuration that holds the dynamically updating Text widget.
class TextWidget extends StatefulWidget {
  TextWidget({Key key}) : super(key: key);
  @override
  TextWidgetState createState() => TextWidgetState();
}

class TextWidgetState extends State<TextWidget> {
  TextWidgetState({Key key});
  // Refresh method for calling the setstate of text widget for dynamic updation.
  void refresh() {
    setState(() {});
  }
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text(stateTest),// stateTest string is set to Text widget.
    );
  }
}

```
The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4696646/sample.zip)

Regards,
Sriram Kiran.

**Comment by Kinnear** [comment]
The GlobalKey method works! Thank you!!
