### ISSUE TITLE
怎么添加另一个Y轴How to add another Y-axis

### ISSUE THREAD

**Issue by LeungChunWai** [syncfusion/flutter-examples#138]
我希望把“个数”和“概率”放在同一个图表下，这导致了Y轴的单位出现问题。我现在希望左边Y轴的单位是"个数"，右边添加一个单位为"百分比"的Y轴，这可以实现吗？
I want to put "number" and "probability" in the same chart, which leads to the unit problem of Y axis. Now I want the left Y-axis unit to be "number" and the right to add a Y-axis unit to be "percentage". Can this be achieved？

My English is not good,wish you could understand me,thks

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LeungChunWai ,

Thanks for using your Syncfusion Flutter charts.  We have analyzed your scenario and we assume that you are in need of multiple axes feature available in the chart for your requirement. The multiple axes allows you to add n number of axis to the chart. An additional horizontal or vertical axis can be added to the chart using the axes property, and then you can associate it to a series by specifying the name of the axis to the xAxisName or yAxisName property in the series. For further reference on multiple axes feature, please refer the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#multiple-axes

We have also created and attached a simple chart sample (using multiple axes feature) below in which we have added two y-axes for comparing the day-wise temperatures between Washington and New York cities.

**Screenshot**
![image](https://user-images.githubusercontent.com/63577117/84655072-ee9ee000-af2d-11ea-99a9-b755ebd8fd9a.png)
The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4780033/sample.zip)

Regards,
Sriram Kiran

**Comment by LeungChunWai** [comment]
That's what i need, extremely helpful, thks a lot!!
