### ISSUE TITLE
Tick Lines appear outside of the graph

### ISSUE THREAD

**Issue by hnnngwdlch** [syncfusion/flutter-examples#139]
Hi,

in cases where vertical graph space is scarce the last majorTickLine appears outside of the graph. My example includes a simple BarSeries, but the same behavior appears for other graph types as well (e.g. LineSeries or ColumnSeries) if one sets the isTransposed property to true.

Screenshot:
![TickLines](https://user-images.githubusercontent.com/57846029/84564013-1dfff200-ad60-11ea-8fe6-9d028a8925e0.png)

Code:
```
class _TestGraphState extends State<TestGraph> {
  @override
  Widget build(BuildContext context) {
    final List<DisplayedData> columnSeriesData = [
      DisplayedData('1991', 1.000),
      DisplayedData('1992', 1.034),
      DisplayedData('1993', 1.034),
      DisplayedData('1994', 1.011),
      DisplayedData('1995', 1.000),
      DisplayedData('1996', 1.000),
      DisplayedData('1997', 0.969),
      DisplayedData('1998', 0.971),
      DisplayedData('1999', 0.982),
      DisplayedData('2000', 0.994),
      DisplayedData('2001', 1.000),
      DisplayedData('2002', 1.034),
      DisplayedData('2003', 1.034),
      DisplayedData('2004', 1.011),
      DisplayedData('2005', 1.000),
      DisplayedData('2006', 1.000),
      DisplayedData('2007', 0.969),
      DisplayedData('2008', 0.971),
      DisplayedData('2009', 0.982),
      DisplayedData('2010', 0.994),
      DisplayedData('2011', 1.000),
      DisplayedData('2012', 1.034),
      DisplayedData('2013', 1.034),
      DisplayedData('2014', 1.011),
      DisplayedData('2015', 1.000),
      DisplayedData('2016', 1.000),
      DisplayedData('2017', 0.969),
      DisplayedData('2018', 0.971),
      DisplayedData('2019', 0.982),
    ];
    return Scaffold(
      body: Padding(
        padding: EdgeInsets.symmetric(
          vertical: 20,
          horizontal: 10,
        ),
        child: Column(
          children: <Widget>[
            Text(
              'Graph title',
              style: TextStyle(
                fontSize: 20,
              ),
            ),
            SizedBox(
              height: 15,
            ),
            Container(
              height: 400,
              child: SfCartesianChart(
                primaryXAxis: CategoryAxis(
                  majorTickLines: MajorTickLines(
                    color: Colors.black,
                  ),
                ),
                series: <ChartSeries>[
                  BarSeries<DisplayedData, String>(
                    dataSource: columnSeriesData,
                    xValueMapper: (DisplayedData data, _) => data.xValueMapper,
                    yValueMapper: (DisplayedData data, _) => data.yValueMapper,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DisplayedData {
  final String xValueMapper;
  final num yValueMapper;

  DisplayedData(
    this.xValueMapper,
    this.yValueMapper,
  );
}
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hnnngwdlch  ,

Greetings from Syncfusion. We have analyzed your scenario and we were able to replicate the reported issue regarding the tick lines rendering outside of the chart. We will consider this issue as a bug and we will include the fix for the reported issue in our upcoming next weekly patch release which is expected to be rolled on 23rd June 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hnnngwdlch ,

The reported issue has been fixed and we will include the fix in our upcoming Vol 2 main release which is expected to be rolled out at the end of this month (June 2020). We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hnnngwdlch ,

Thanks for your patience. The reported issue regarding the tick lines appearing outside of the chart is fixed and rolled out in our Vol 2 Main release. To overcome the reported issue, kindly upgrade the Flutter chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.44

We have also created and attached a test sample below for your reference. This sample was used to test the reported issue with the latest chart widget version.
[ticklinesample.zip](https://github.com/syncfusion/flutter-examples/files/4885538/ticklinesample.zip)


Regards,
Sriram Kiran

**Comment by hnnngwdlch** [comment]
Hi Sriram,

great, thanks!

Best regards,
Henning
