### ISSUE TITLE
zoomPanBehavior in example dynamic updates

### ISSUE THREAD

**Issue by B0yma** [syncfusion/flutter-examples#14]
im trying to add this behavior in your example file add_remove_series.dart:
```
...
zoomPanBehavior: ZoomPanBehavior(
        enablePinching: true,
        zoomMode: ZoomMode.x,
        enablePanning: true
    ),
...
```
after adding or removing line series, zoom of lines stops working 
.. update...
it also stop working when we dont add or delete anything and start-stop zooming

**Comment by dharanidharandharmasivam** [comment]
Hi @B0yma ,

We have analyzed your scenario. We can replicate the reported issue the issue occurs while the series is added or removed when zooming is enabled. So, we have logged defect report at our end and the status of the bug can be tracked from below feedback portal link.

https://www.syncfusion.com/feedback/8284 

We will fix the bug and include it in our upcoming update. We appreciate your patience until then.

Thanks.
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @B0yma ,

Thanks for being patience. We have fixed the reported issue, now panning will work properly on adding or removing the chart series dynamically. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Kindly revert us if you have any concerns.

Thanks,
Dharani.

**Comment by JayavigneshwaranG** [comment]
Hi @B0yma ,

We are closing this issue now, as it is resolved.
If you still face any concerns, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update the responses there.

Thanks,
Jayavigneshwaran
