### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kratipandey57** [syncfusion/flutter-examples#140]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = 'HelloWorld.pdf' (OS Error: Read-only file system, errno = 30)

**Comment by AnandJayachithra** [comment]
Hi,

We can able to open the output PDF document in mobile device as instructed in https://help.syncfusion.com/flutter/pdf/getting-started#save-and-open-a-pdf-document-in-mobile. And also find the android studio sample project to create a PDF document with Syncfusion Flutter PDF library and open the output document in mobile device from https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app2279934.

And also find the KB link from https://www.syncfusion.com/kb/11330/how-to-create-a-pdf-file-in-flutter.

Please let us know if you need any further assistance.

With Regards,
Anand
