### ISSUE TITLE
Performance issue on large data sources

### ISSUE THREAD

**Issue by raminvakili-fs** [syncfusion/flutter-examples#141]
The chart becomes too slow when the data source has over 1000 items!
Running in profile mode on a real device. (Huawei Honor 6 - Android 6)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @raminvakili-fs ,

Greetings from Syncfusion. We have analyzed your query and we wish to tell you that we have already taken measures for improving the performance and memory leak issues of our chart widget package. These improvements regarding performance issues in the chart when rendering large data sources will be included in our upcoming Vol 2 main release which is expected to be rolled out at the end of this month(June 2020). We will update you once the release has been rolled out and we appreciate your patience until then.

We have also attached a screenshot of performance metrics for your reference below which depicts the before and after comparison on improvement in the rendering performance of the chart with a large number of data sources provided. 
![image](https://user-images.githubusercontent.com/63577117/85416484-24764100-b58c-11ea-8b8c-f27cd323815d.png)

If you have any more concerns, please revert us.

Regards,
Sriram Kiran

**Comment by raminvakili-fs** [comment]
Hello @SriramKiranSenthilkumar .Thanks a bunch!

**Comment by dharanidharandharmasivam** [comment]
Hi @raminvakili-fs ,

Most welcome. As stated earlier, we will update you once the release has been rolled out and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @raminvakili-fs ,

Thanks for your patience. The reported performance-related issues regarding the performance issues in the chart when rendering large data source is now improved and rolled out in our Vol 2 Main release. To overcome the reported performance-related issues, kindly upgrade the Flutter chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.44

Regards,
Sriram Kiran

**Comment by raminvakili-fs** [comment]
Hi @SriramKiranSenthilkumar, Thanks for notifying, I'll check out the latest version. 🙇‍♂️
