### ISSUE TITLE
The Drag n drop functionality in Calendar app?

### ISSUE THREAD

**Issue by Danteless** [syncfusion/flutter-examples#142]
hello 
so i am trying the syncfusion examples and i stumbled upon the calendar app
i wanna know how to lake the appointements draggable like in this Swift app

https://help.syncfusion.com/xamarin/scheduler/populatingappointments_images/draganddrop.gif?_ga=2.202555794.2027199944.1592318534-1217406968.1592318534

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, your requirement is “Drag and drop support in Flutter calendar” and we have already logged the feature request for the same. We will implement this feature in any of our upcoming releases and let you know once the feature is implemented. We appreciate your patience until then. Now you can track the current status of this feature request by using the following link. 

Link:
https://www.syncfusion.com/feedback/15102/providing-support-for-drag-and-drop-in-the-flutter-event-calendar-sfcalendar
