### ISSUE TITLE
AreaSeries line width

### ISSUE THREAD

**Issue by ydenizs** [syncfusion/flutter-examples#144]
Hello,

Is there any way to change line color of AreaSeries chart? We are trying to achieve this look:

![image](https://user-images.githubusercontent.com/62982726/85801058-c17ed880-b74a-11ea-9bfd-b0fd68111912.png)

So far;

![image](https://user-images.githubusercontent.com/62982726/85801174-fa1eb200-b74a-11ea-9fd2-523df3015dc0.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ydenizs ,

Greetings from Syncfusion. We have analyzed your scenario and to render area series with borderline you need to provide the corresponding values for the border properties such as **borderWidth**, **borderColor** available in the series. Also, you can provide the border draw value using the property borderDrawMode of a series. Please refer the code snippet below for reference.
```
SfCartesianChart(
            series: <ChartSeries<ChartData, DateTime>>[
              SplineAreaSeries<ChartData, DateTime>(
                  borderWidth: 4,
                  borderColor:  Colors.amber,
                  borderDrawMode: BorderDrawMode.top,
              )
            ]
) 
```

We have also created a simple chart sample similar to the provided screenshot and attached the below for your reference.

**Screenshot**
![image](https://user-images.githubusercontent.com/63577117/85860504-8927da80-b7dc-11ea-9498-9dc25ebd7aca.png)

The sample for reference can be found below,
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4837070/sample.zip)

Regards,
Sriram Kiran

**Comment by ydenizs** [comment]
Thanks for fast reply and detailed explanation.
