### ISSUE TITLE
Animation not working after pan/zoom

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#146]
Hi,
when I change the chart data an animation is applied to the transition, if I zoom or pan the graph before to change the chart data, the animation is not applied

![bad-impl-3](https://user-images.githubusercontent.com/5927329/85873267-2a109880-b7d1-11ea-8b76-c329ad9f80e5.gif)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,
 
Greetings from Syncfusion. We have analyzed your scenario and currently, there are only two types of animation available in our chart library. They are the initial rendering animation and the animation which occurs when the chart data is added or updated. So, the series animation does not occur when the chart is zoomed or panned, and this is the default behaviour.

We would also like to share information about the axis animation feature which supports in animating the axis elements like labels, gridlines, and ticks when the axis range is changed. We have also attached a gif below which illustrates how axis animation looks like for your understanding. 
 
![image](https://user-images.githubusercontent.com/63577117/86004951-a1446780-ba31-11ea-9459-eee31ff4afd8.png)

This feature will be included in Vol 2 main release which is expected to be rolled out in the mid of this week.
 
Regards,
Sriram Kiran.

**Comment by andrea689** [comment]
Sorry, I will not have explained myself well.

If I change/update the data, the graph is updated with animation.

If I change/update the data **after a pan/zoom**, the graph is not updated with animation.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

We have analyzed your scenario and we were able to replicate the reported issue regarding the dynamic animation not working after the live-updating chart is panned or zoomed. We will consider this issue as a bug and we will include the fix for the reported issue in our upcoming patch release which is expected to be rolled out by the mid of next week. We will update you once the release is rolled and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Thanks for your patience. The reported issue regarding the dynamic animation not working after the live-updating chart is panned or zoomed is fixed and rolled out in our Vol 2 Main release. To overcome the reported issue, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.44

Regards,
Sriram Kiran.

**Comment by andrea689** [comment]
Hi @SriramKiranSenthilkumar ,
it has fixed when I pan the chart, but if I zoom the chart the problem with animation persist.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

We have analyzed your scenario and we would like to share some information regarding the dynamic animation behaviour available in our chart widget. Currently, the chart does not animate on dynamic update when it is in a zoomed state. This is the default behaviour. However, we have considered this as an improvement and will include this in our upcoming Vol 2 SP1 release which is expected to be rolled out by the middle of August 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Thanks for your patience. The requested improvement regarding the dynamic update animation should also work in zoomed state is now included and rolled out in our Vol 2 SP1 release. To overcome the reported issue, kindly upgrade the chart widget package version to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.55

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran
