### ISSUE TITLE
Missing location of event calendar

### ISSUE THREAD

**Issue by tbm98** [syncfusion/flutter-examples#148]
![Screenshot_2020-06-27-10-36-44-148_com syncfusion flutter examples](https://user-images.githubusercontent.com/52562340/85913816-2a0ca900-b862-11ea-81c2-19b3fd9a57ae.png)

**Comment by tbm98** [comment]
It only show title

**Comment by tbm98** [comment]
Nó
![Screenshot_2020-06-27-10-41-00-699_com google android calendar](https://user-images.githubusercontent.com/52562340/85913870-bae38480-b862-11ea-9d65-7550f23a5260.png)
Location in google calendar

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information your requirement is ”Custom widget support for appointment in the Flutter Event Calendar”. We have already logged the feature request for the same. We will implement this feature in any of our upcoming releases and let you know once the feature is implemented. We appreciate your patience until then. Now you can track the current status of this feature request by using the below-mentioned link. 

As of now, you can achieve your requirement using the below code snippet. 

Code snippet:
appointments.add(Appointment(
  startTime: DateTime.now(),
  endTime: DateTime.now().add(const Duration(hours: 1)),
  subject: 'Customer Meeting\nVietNam',
  color: Colors.pink,
));


Feedback link:
https://www.syncfusion.com/feedback/14380/custom-widget-support-for-appointments-in-flutter-event-calendar-sfcalendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by tbm98** [comment]
Yes. I want to custom widget for appointments

**Comment by Indumathi1195R** [comment]
Hi Dani,

As we promised earlier, we will include the mentioned feature "**Custom widget support for appointment in the Flutter Event Calendar**" in any of our upcoming releases and let you know once release rollout. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by tbm98** [comment]
Yes. Thank you!
