### ISSUE TITLE
only ontTap event on  SfCalendar()

### ISSUE THREAD

**Issue by robertoltrocha** [syncfusion/flutter-examples#149]
I'm using SfCalendar () with a
 `monthViewSettings view: MonthViewSettings (showAgenda: true,)` 
and I would like to have an option to click on the calendar detail and call a function to open the details on another screen. Currently I only saw an option of onTap () to select the date, but there is no way to individually call up the agenda on the screen below the calendar.
Currently if I click on any cell in the calendar it is called function onTap() and show the details screen and I don't always want to open it, just see the schedules at the bottom of the calendar.

Some idea?
thanks

![WhatsApp Image 2020-06-27 at 13 27 02](https://user-images.githubusercontent.com/30963205/85927159-af03bc80-b87a-11ea-9f3b-5317a58b8c95.jpeg)
![WhatsApp Image 2020-06-27 at 13 28 27](https://user-images.githubusercontent.com/30963205/85927160-af9c5300-b87a-11ea-9d16-2eedd3ccb759.jpeg)

**Comment by Ahmadre** [comment]
> I'm using SfCalendar () with a
> `monthViewSettings view: MonthViewSettings (showAgenda: true,)`
> and I would like to have an option to click on the calendar detail and call a function to open the details on another screen. Currently I only saw an option of onTap () to select the date, but there is no way to individually call up the agenda on the screen below the calendar.
> Currently if I click on any cell in the calendar it is called function onTap() and show the details screen and I don't always want to open it, just see the schedules at the bottom of the calendar.
> 
> Some idea?
> thanks
> 
> ![WhatsApp Image 2020-06-27 at 13 27 02](https://user-images.githubusercontent.com/30963205/85927159-af03bc80-b87a-11ea-9f3b-5317a58b8c95.jpeg)
> ![WhatsApp Image 2020-06-27 at 13 28 27](https://user-images.githubusercontent.com/30963205/85927160-af9c5300-b87a-11ea-9d16-2eedd3ccb759.jpeg)

Just save a "isAgendaShown" bool and if you call onTap do this:

```dart
if (calendarView == CalendarView.month && isAgendaShown) {
      return;
}
```

This avoids opening your appointments and you can only select the day of the months.

**Comment by robertoltrocha** [comment]
Thanks for your response.
But I would like to open my appointments when I click on the bottom and each one so I can see the details. I didn't see how I can differentiate when I click on the day of the month or on each appointment in the agenda (below view).
I will always show true agenda.

That is the goal:
I select the day of the month, see my appointments in the bottom view and click on an appointment (bottom view) to be able to see the details.

**Comment by Indumathi1195R** [comment]
Hi Roberto,

Based on the provided information your requirement is “Getting the appointment details while tapping the agenda view appointments”.  Based on the `targetElement` of the calendar tapped details you can get the tapped element of the calendar and achieve your requirement. Please find the code snippet for the same.

**Code snippet:**
void calendarTapped(CalendarTapDetails details) {
    if (details.targetElement == CalendarElement.header) {
      //// Todo your requirement here.
    }
    else if (details.targetElement == CalendarElement.viewHeader) {
      //// Todo your requirement here.
    }
    else if (details.targetElement == CalendarElement.calendarCell) {
      //// Todo your requirement here.
    }
    else if (details.targetElement == CalendarElement.agenda) {
      //// Todo your requirement here.
    }

    }


Link: https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarElement-class.html

KB link: https://www.syncfusion.com/kb/10998/how-to-get-datetime-details-while-tapping-the-flutter-event-calendar-elements?_ga=2.125690634.1244006359.1593352046-911295489.1591688453

UG link: https://help.syncfusion.com/flutter/calendar/callbacks

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by robertoltrocha** [comment]
Hi,
Sorry I didn't see it in the documentation and I thought it was an issue.
Your answer answered many questions that I had and was very complete.
Thank you for your attention.
