### ISSUE TITLE
MarkerSettings image: No proposed image appears

### ISSUE THREAD

**Issue by gladson** [syncfusion/flutter-examples#15]
![error](https://i.imgur.com/jSyphTW.jpg)

```dart
class TendenciasData {
  TendenciasData(
    this.mes,
    this.vendas
  );

  final String mes;
  final double vendas;
}
```

```dart
ScatterSeries<TendenciasData, String>(
  dataSource: [
    TendenciasData('Jan', 12),
    TendenciasData('Fev', 25),
    TendenciasData('Mar', 9),
    TendenciasData('Abr', 36),
    TendenciasData('Mai', 15),
    TendenciasData('Jun', 42)
  ],
  xValueMapper: (TendenciasData tendencias, _) => tendencias.mes,
  yValueMapper: (TendenciasData tendencias, _) => tendencias.vendas,
  markerSettings: MarkerSettings(
    imageUrl: 'assets/images/ghost.png',
    isVisible: true,
    shape: DataMarkerType.image
  ),
  name: 'Scatter'
)
```

image_teste : ![ghost](https://image.flaticon.com/icons/png/128/1235/1235092.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @gladson ,

Thanks for trying the Syncfusion Flutter charts widget. 

As of now the image marker support to the scatter series is not provided. So, we have considered this as a bug and logged defect report at our end. We will fix this and include it in our upcoming update. We appreciate your patience until then.

Thanks,
Dharani.

**Comment by gladson** [comment]
> Hi @gladson ,
> 
> Thanks for trying the Syncfusion Flutter charts widget.
> 
> As of now the image marker support to the scatter series is not provided. So, we have considered this as a bug and logged defect report at our end. We will fix this and include it in our upcoming update. We appreciate your patience until then.
> 
> Thanks,
> Dharani.


Hi @dharanidharandharmasivam , thanks for the return.
👍

**Comment by dharanidharandharmasivam** [comment]
Hi @gladson ,

Thanks for being patience. We have fixed the reported issue, now the scatter series is rendering properly with image markers. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Kindly revert us if you have any concerns.

Thanks,
Dharani.

**Comment by gladson** [comment]
> Hi @gladson ,
> 
> Thanks for being patience. We have fixed the reported issue, now the scatter series is rendering properly with image markers. To resolve the issue, kindly upgrade your package and you can find the updated packages from the below link.
> 
> https://pub.dev/packages/syncfusion_flutter_charts
> 
> Kindly revert us if you have any concerns.
> 
> Thanks,
> Dharani.

Hi @dharanidharandharmasivam, thanks again for the effective feedback...
Everything went very well, but in the name: 'Scatter' it does not appear the first time, only after clicking and is cropping the image. 
As soon as possible I will send here the screen print using this same icon.

**Comment by dharanidharandharmasivam** [comment]
Hi @gladson ,

Sorry for the inconvenience. As of now, the scatter series can be rendered with image markers, but there is an issue with image shape for the legend. We have logged bug report for this legend issue. Fix for this issue will be included in our next update, we appreciate your patience until then. Also, we can keep this issue open until it gets resolved.

Thanks,
Dharani.

**Comment by gladson** [comment]
> Hi @gladson ,
> 
> Sorry for the inconvenience. As of now, the scatter series can be rendered with image markers, but there is an issue with image shape for the legend. We have logged bug report for this legend issue. Fix for this issue will be included in our next update, we appreciate your patience until then. Also, we can keep this issue open until it gets resolved.
> 
> Thanks,
> Dharani.

No need to apologize. 😄 
We are helping each other...
I have to thank you for your patience.
🥇

**Comment by JayavigneshwaranG** [comment]
Hi @gladson ,

Thanks for your patience.
Now we have fixed the reported issues and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5).](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). Now the Scatter and legend are working fine when an image is specified for the marker shape.

Thanks,
Jayavigneshwaran
