### ISSUE TITLE
[MISSING FEATURE] - AgendaView timeFormat hard coded

### ISSUE THREAD

**Issue by Ahmadre** [syncfusion/flutter-examples#150]
I wanted to localize the timeFormat for the AgendaView but "whoops" it's hard coded:

![image](https://user-images.githubusercontent.com/18512224/85956872-1019b600-b989-11ea-9581-ebea1fac5dcb.png)

I am developing for 24h-format customers and this blocks us from releasing our app. Please provide a parameter, that we can give the 24-timeFormat and not rely on the am/pm.

I need to give: `HH:mm` format.

Thanks

**Comment by Indumathi1195R** [comment]
Hi Rebar,

Based on the provided information your requirement is “**Time format support for agenda view appointments in Calendar**” and we have logged the feature request for the same. We will implement and include the support in our upcoming Weekly Nuget release package, which is expected to roll out by July 7, 2020, and let you know once release rollout. We appreciate your patience until then.

You can track the current status of this report by the following link,

**Feedback links:** https://www.syncfusion.com/feedback/15615/providing-a-time-format-support-for-agenda-view-in-flutter-calendar-sfcalendar

https://www.syncfusion.com/feedback/14380/custom-widget-support-for-appointments-in-flutter-event-calendar-sfcalendar

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
Thank you sooo much @Indumathi1195R :)

You rock from Syncfusion ❤️

**Comment by Indumathi1195R** [comment]
Hi Rebar,
 
Sorry for the inconvenience caused.
 
We are not including a new API in the Weekly Nuget package. We will include this in our upcoming 2020 Volume 2 SP1 release, which is expected to roll out by August month of 2020 and let you know once release rollout. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R Thank you so much for the information :)

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

We have included the feature “**Time format support for agenda and schedule view appointments in Calendar**” in our latest Week Nuget release package version 18.2.54. Kindly update to the latest version for this feature. Please find the changelog for the same.

**Changelog link**: https://pub.dev/packages/syncfusion_flutter_calendar/changelog

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R Thank you sooooooooooooooo much for the update! Help us a lot!
