### ISSUE TITLE
calendar is showing wrong month of date selected

### ISSUE THREAD

**Issue by robertoltrocha** [syncfusion/flutter-examples#151]
Hi,

It is still June and when I move on to the next week, the date selected is 29 June(Junho) and the month shown is July(Julho).
month Junho = June
month Julho = July
so for this calendar I don't know if I am on June 29th or July 29th

```
SfCalendar(
                      controller: _calendarController,
                      firstDayOfWeek: 1,
                      onTap: (value){
                        onTapCalendar(model, value);
                      },
                      headerStyle: CalendarHeaderStyle(
                        textStyle: TextStyle(color: Colors.blue, fontSize: 30),
                        textAlign: TextAlign.center,
                      ),
                      appointmentTextStyle: TextStyle(
                          fontSize: 14.0, fontWeight: FontWeight.bold),
                      view: CalendarView.week,
                      initialSelectedDate: DateTime.now(),
                      timeSlotViewSettings: TimeSlotViewSettings(
                        startHour: 6,
                        endHour: 19,
                      ),
                      dataSource: _getDataSource(),
                      // by default the month appointment display mode set as Indicator, we can
                      // change the display mode as appointment using the appointment display mode
                      // property
                      monthViewSettings: MonthViewSettings(
                          appointmentDisplayMode:
                              MonthAppointmentDisplayMode.appointment),
                    )
```
![WhatsApp Image 2020-06-29 at 00 38 28 (1)](https://user-images.githubusercontent.com/30963205/85970805-eae57180-b9a1-11ea-81aa-fa0cebb4ce47.jpeg)
![WhatsApp Image 2020-06-29 at 00 38 28](https://user-images.githubusercontent.com/30963205/85970807-eb7e0800-b9a1-11ea-941e-926a380db76b.jpeg)

**Comment by Indumathi1195R** [comment]
Hi Roberto,

Based on the provided information we can replicate the mentioned issue “**Calendar showing the wrong month of the date selected**”. We will fix the mentioned issue and include the issue fix in our upcoming Weekly Nuget release package, which is expected to roll out by July 7, 2020, and let you know once release rollout. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R Thank you very much for that, because I got the same issue when I programmatically change the `displayDate` or `selectedDate`

**Comment by Ahmadre** [comment]
I can confirm, that this is only happening on debug mode in Flutter. On release mode it works perfect!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18512224/86192134-20788f00-bb49-11ea-9e01-9a82ec55a312.gif)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Based on the provided information, we have checked the simple sample with the programmatic `**selectedDate**` and `**displayDate**` and it is working fine. We have prepared the simple sample for the same. Please find the sample from the following link.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_calendarversion-588689277.zip

If possible, can you please share your requirement in detail clearly with simple pictorial representation. If this is not your requirement, please modify the sample based on your scenario and revert us back with the more details, it would be helpful for us to analyze and provide you a solution at the earliest.


Regards,
Indumathi R
