### ISSUE TITLE
details.targetElement == CalendarElement.calendarCell is calling selected date when tap out of calendar

### ISSUE THREAD

**Issue by robertoltrocha** [syncfusion/flutter-examples#153]
Hello
when I touch the red area it is called a function ontTap()  as if it had touched the selected cell.
If there is no date selected, no function is performed in if (details.targetElement == CalendarElement.calendarCell) {do something}
I´m use S-10 Galaxy mobile
Selected date is 04/July

Please note that I use limited hours so the screen is not completely filled.
```
   timeSlotViewSettings: TimeSlotViewSettings (
                         startHour: 6,
                         endHour: 19,
                       ),
```

```
void calendarTapped(CalendarTapDetails details) {

if (details.targetElement == CalendarElement.calendarCell) {
     //call my function
    }
}

```

```
SfCalendar(
                      controller: _calendarController,
                      firstDayOfWeek: 1,
                      onTap: (value){
                        onTapCalendar(model, value);
                      },
                      headerStyle: CalendarHeaderStyle(
                        textStyle: TextStyle(color: Colors.blue, fontSize: 30),
                        textAlign: TextAlign.center,
                      ),

                      appointmentTextStyle: TextStyle(
                          fontSize: 14.0, fontWeight: FontWeight.bold),
                      view: CalendarView.week,
                      initialSelectedDate: DateTime.now().toLocal(),
                      timeSlotViewSettings: TimeSlotViewSettings(
                        startHour: 6,
                        endHour: 19,
                      ),
                      dataSource: _getDataSource(),
                      // by default the month appointment display mode set as Indicator, we can
                      // change the display mode as appointment using the appointment display mode
                      // property
                      monthViewSettings: MonthViewSettings(
                          appointmentDisplayMode:
                              MonthAppointmentDisplayMode.appointment),
                    )
```

![WhatsApp Image 2020-06-29 at 18 26 01](https://user-images.githubusercontent.com/30963205/86058039-9a6c2380-ba36-11ea-9f3d-0019c73ee00f.jpg)

**Comment by Indumathi1195R** [comment]
Hi Roberto,

We have already found and fixed the reported issue “**onTap callback of the SfCalendar calling when tapping out of the calendar**”. We will include the issue fix in our upcoming 2020 Volume 2 release which is expected to roll out at the end of this week and let you know once release rollout. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Roberto,

We are glad to announce that our 2020 Volume 2 Release v18.2.44 is rolled out with the mentioned issue fix for “**onTap callback of the SfCalendar calling when tapping out of the calendar**”. Please find the latest version from the following pub.dev link.

Link: https://pub.dev/packages/syncfusion_flutter_calendar/

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
