### ISSUE TITLE
[CALENDAR] - Jump to today's date doesn't work in week/workweek mode

### ISSUE THREAD

**Issue by Ahmadre** [syncfusion/flutter-examples#154]
I got a Button "Today" which leads the view to `DateTime.now()`.

I am setting:
- `selectedDate` and
- `displayDate`

to that value and it works on Day and Month View, but when I press that button on week or workweek mode, it does nothing.

Is that intended to be so, or is that a missing feature?

Thanks.

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

Based on the provided information, we have checked the mentioned issue “Unable to move current date while set the **displayDate** and **selectedDate** as today date” and it is working fine as expected. We have prepared the simple sample and video for the same. Please find the sample and video from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/283590/ze/flutter_calendarversion-1880675412.zip

**Video link:** https://www.syncfusion.com/downloads/support/directtrac/283590/ze/video-1720044104.zip

If this is not your requirement, please modify the sample based on your scenario and revert us back with the more details, it would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R I cannot access the video! I logged with with our Account (Amptech), but it said: access denied :(

**Comment by Ahmadre** [comment]
Here you can see what is exactly not working:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18512224/86385427-8de30780-bc90-11ea-803c-340ed58750ee.gif)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We have checked the mentioned issue on the web platform. **displayDate** and **selectedDate** are working fine as expected when moving to the current date. We have prepared a simple video for the same. We have attached the tested video for the same. Please find the video below.

[video.zip](https://github.com/syncfusion/flutter-examples/files/4868997/video.zip)

We would like to set up a web meeting to reproduce the issue at your end. Would you please get back to us on your availability for a web meeting?  

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R please invite me via: rebar.ahmad@gmail.com. We would prefer a google meet meetup.

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

Sorry for the inconvenience caused.

We usually update the meeting details in the incident. But the mentioned Email id  rebar.ahmad@gmail.com doesn’t have a Syncfusion account, so that we are unable to process for meeting. Can you create an incident under your account to proceed further?

https://www.syncfusion.com/support/directtrac/incidents/newincident

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@SyncfusionInstall I am the developer of our company. Please use this email for every now and further communication:

dev@amptech.store

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

We have created an incident. To get further updates please login the Syncfusion account with this mail id dev@amptech.store.
 
https://www.syncfusion.com/account/login

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

As per our meeting discussion, can you please share your code snippet. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R We will send you the whole reproducable code asap. We're a little bit busy now with other projects.

But thank you very much for tracking this ❤️ 

Best regards
Rebar

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

Thank you for the update. We will wait until further response to hear from you.

Regards,
Indumathi R
