### ISSUE TITLE
"It also supports programmatic selection." (of dates)

### ISSUE THREAD

**Issue by SogoGolf** [syncfusion/flutter-examples#155]
How can we programmatically select a range of dates ? Could you please provide an example to support this claim in the documentation ? Many thanks.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked your requirement “**Programmatic date selection in DateRangePicker**”and it can be achieved by using **DateRangePickerController**. Using this controller, you can select a date, multiple dates, range and multi-range of the dates. We have UG document for programmatic date selection. Please find the UG link for the same.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatic-date-selection

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
