### ISSUE TITLE
[CALENDAR] - headerHeight not working on native mobile browsers

### ISSUE THREAD

**Issue by Ahmadre** [syncfusion/flutter-examples#157]
I setup a customHeader like the official tutorial of Syncfusion to hide the actual header and setup my own header.

But on mobile web browsers the default header is appearing instead:

![Screenshot_20200704-211747~2.png](https://user-images.githubusercontent.com/18512224/86519588-56b15980-be3c-11ea-88e9-bf49d2bb0dbe.png)

How can I definetly hide the header?

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

Based on the provided information, we have checked the mentioned issue “**headerHeight is not working in SfCalendar**” in mobile and web platform. It is working fine as expected from our end. For hiding the default header, you need to set the **headerHeight value as 0**. We have prepared a simple sample for the custom header. Also, we have a KB document for the same. Please find the sample, UG, and KB from the following links.

**Tested version:**
18.1.59-beta

**Tested device:**
Mi A1

**Video:**
[video.zip](https://github.com/syncfusion/flutter-examples/files/4877263/video.zip)


**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_headerheight300225486.zip

**UG link:**
https://help.syncfusion.com/flutter/calendar/headers

**KB link:**
https://www.syncfusion.com/kb/10997/how-to-add-custom-header-and-view-header-in-flutter-event-calendar-sfcalendar-widget

If possible, can you please share the below details,
•	Tested version

If possible, can you please modify the sample based on your scenario and revert us back with the more details, it would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
Yes I have already set the headerHeight to 0 :)

**Comment by Ahmadre** [comment]
I tried your main.dart file, but on my Pixel 2 XL it is still visible. I saw that you explicitly used a Container with a height and I am also using a fixed height (kToolbarHeight), but It's the same. On landscape also. We can discuss that tomorrow.

**Comment by Ahmadre** [comment]
![image](https://user-images.githubusercontent.com/18512224/86599168-89736300-bf9e-11ea-9828-2592b55d96f0.png)

I saw that the implementation includes also the topPadding. But that can lead to misinterpretation on mobile browsers. On real apps it's working (because topPadding can be 0)

**Comment by Indumathi1195R** [comment]
Hi Ahmadre,

We have checked the mentioned issue “**Header height is not working in SfCalendar**” in our latest 2020 Volume 2 release version 18.2.44. We are unable to reproduce the mentioned issue and it is working fine as expected. Can you please check this issue in our latest release version and let us know if still you are facing the same issue? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
> **Tested version:**
> 18.1.59-beta
> 
> **Tested device:**
> Mi A1
> 
> **Video:**
> [video.zip](https://github.com/syncfusion/flutter-examples/files/4877263/video.zip)

@Indumathi1195R Thanks you response, but you're testing on a mobile __App__ and not in the mobile __browser__.

Problem already exists with the newest release version of syncfusion_flutter_calendar.

**Comment by Ahmadre** [comment]
@Indumathi1195R Thanks you soooo much ❤️ it's working now on mobile browsers :)))

You're the best!!!
