### ISSUE TITLE
[charts]Wondering when tapped,show a tooltip contains all series in point.x

### ISSUE THREAD

**Issue by LeungChunWai** [syncfusion/flutter-examples#158]
for example,there are 'price' and 'quantity' series in 'oranges' , I want when I tap area of 'orange',it shows a tooltip contains 'price' and 'quantity' , in the style of tooltip showing when tapping the column. How i customize such a tooltip?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LeungChunWai ,

Thanks for using Syncfusion Flutter charts. We have analyzed your scenario and we have created a simple sample in which we have customized the tooltip contents using the callback event called the `onTooltipRender` event available in the chart. We have attached the sample link below for your reference.
https://github.com/SyncfusionExamples/tooltip-customization-flutter-chart

We have also attached our Knowledge Base document on how to customize the tooltip contents using the callback events below for your reference,
https://www.syncfusion.com/kb/11507

For further reference on onTooltipRender event, please check the user guide below,
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#ontooltiprender

Regards,
Sriram Kiran
