### ISSUE TITLE
[FEATURE REQUEST] Data label tapped callback

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#160]
Hi,
is there a plan to add `onDataLabelTapped`? 

I also tried to use `GestureDetector` with custom data label (with use of `builder`), but not working.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Greetings from Syncfusion. We have analyzed your query and we have considered this as a feature request regarding adding **onDataLabelTapped** callback event for data labels in the charts and created feedback for it in our feedback portal. We will include this feature in one of our upcoming releases yet to come.
You can track the status of the feature request feedback from the link below.
https://www.syncfusion.com/feedback/15811

Regards,
Sriram Kiran
