### ISSUE TITLE
Charts not aligning properly when Arabic locale is chosen

### ISSUE THREAD

**Issue by mithunadhikari40** [syncfusion/flutter-examples#163]
This library works perfectly fine on other locales, but when I chose Arabic Locale, the charts move to the right end of the screen and do not appear properly. Only 10-20% of the part is visible. As you can see here. The first picture is when en Locales is chosen and the second one is when ar Locale is chosen.
![Screenshot_20200707-110321](https://user-images.githubusercontent.com/16093696/86718571-efb1c180-c042-11ea-8060-9918c9a6960d.png)
![Screenshot_20200707-111219](https://user-images.githubusercontent.com/16093696/86718574-f0e2ee80-c042-11ea-9302-56cb2350f9b8.png)

If I change the locale from ar to en on line 28 as `locale: Locale('en'),` it works fine but not on Arabic.  The version I am using is syncfusion_flutter_charts: ^18.1.59
 and the flutter version is  1.17.4 • channel stable and dart version is  Dart 2.8.4

The code I am using is
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(ChartApp());
}

class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chart Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('en'),
        Locale('es'),
        Locale('pt'),
        Locale('ar'),
      ],
      locale: Locale('ar'),
      home: ChartAppEg(),
    );
  }
}

class ChartAppEg extends StatefulWidget {
  ChartAppEg({Key key}) : super(key: key);

  @override
  _ChartAppEgState createState() => _ChartAppEgState();
}

class _ChartAppEgState extends State<ChartAppEg> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            // Chart title
            title: ChartTitle(text: 'Half yearly sales analysis'),
            // Enable legend
            legend: Legend(isVisible: true),
            // Enable tooltip
            tooltipBehavior: TooltipBehavior(enable: true),
            series: <ChartSeries<SalesData, String>>[
              LineSeries<SalesData, String>(
                  dataSource: <SalesData>[
                    SalesData('Jan', 35),
                    SalesData('Feb', 28),
                    SalesData('Mar', 34),
                    SalesData('Apr', 32),
                    SalesData('May', 40)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  // Enable data label
                  dataLabelSettings: DataLabelSettings(isVisible: true))
            ]));
  }
}

class SalesData {
  SalesData(this.year, this.sales);

  final String year;
  final double sales;
}
`

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ mithunadhikari40 ,

Greetings from Syncfusion. We have analyzed your scenario and currently, we have not provided localization support for our chart widget and it is not applicable for our widget type because our chart widget does not return any texts or words from the source. For example, a calendar widget needs to return some texts or words from its source and for these kinds of widgets only localization support is applicable and chart type widgets do not need any localization support.

And regarding the improper rendering of the chart when the locale is set to Arabic is because the language is of locale type RTL(Right-to-Left). Currently, in our chart widget, only tooltip and legend texts support RTL feature. 

Due to the lack of localization support, which is not applicable for our chart widgets, we have not implemented the RTL feature in our chart widget. We are sorry for our inconvenience.

Regards,
Sriram Kiran.

**Comment by mithunadhikari40** [comment]
Hi @SriramKiranSenthilkumar 
Thank you for your response. Fortunately, I was able to force the chart to align from left to right wrapping the chart widget with `Directionality `widget and setting up the text direction as `textDirection: TextDirection.ltr,`.  It does the work but does not look very nice. Do you guys have any plan to support other locales on charts as well?
