### ISSUE TITLE
Rotated labels cause wrong calculations for alignment and seriesColorBackground is not rotated

### ISSUE THREAD

**Issue by hnnngwdlch** [syncfusion/flutter-examples#170]
Hi,

I have noticed strange behavior if I apply an angle to my labels. In this example I used a column series and set the angle to 90 degrees.

- The background for the label (useSeriesColor = true) is not rotated together with the label, which makes setting an angle and using the series color as background together unfeasible.

- The Alignment does not work correctly when the label is rotated. In this example, I set the labelAlignment to ChartDataLabelAlignment.bottom and the label is partly cut off. I think what happens is the height of the label is calculated before the rotation instead of after the rotation. And therefore the positioning is not correctly applied.

I attached picture for both cases (one pic showing the chart with angle set to 90 and one without any angle).

Best regards,
Henning

Code:

```
class _TestGraphState extends State<TestGraph> {
  @override
  Widget build(BuildContext context) {
    final List<DisplayedData> columnSeriesData = [
      DisplayedData('1991', 1.000),
      DisplayedData('1992', 1.034),
      DisplayedData('1993', 1.034),
      DisplayedData('1994', 1.011),
      DisplayedData('1995', 1.000),
      DisplayedData('1996', 1.000),
    ];
    return Scaffold(
      body: Padding(
        padding: EdgeInsets.symmetric(
          vertical: 20,
          horizontal: 0,
        ),
        child: Column(
          children: <Widget>[
            Text(
              'Graph title',
              style: TextStyle(
                fontSize: 20,
              ),
            ),
            SizedBox(
              height: 15,
            ),
            Container(
              height: 400,
              child: SfCartesianChart(
                primaryXAxis: CategoryAxis(
                  majorTickLines: MajorTickLines(
                    color: Colors.black,
                  ),
                ),
                series: <ChartSeries>[
                  ColumnSeries<DisplayedData, String>(
                    dataSource: columnSeriesData,
                    xValueMapper: (DisplayedData data, _) => data.xValueMapper,
                    yValueMapper: (DisplayedData data, _) => data.yValueMapper,
                    dataLabelSettings: DataLabelSettings(
                      // useSeriesColor: true,
                      labelAlignment: ChartDataLabelAlignment.bottom,
                      // Renders the data label
                      isVisible: true,
                      angle: 90,
                    ),
                    dataLabelMapper: (DisplayedData data, _) =>
                        '${data.yValueMapper} (${data.xValueMapper})',
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DisplayedData {
  final String xValueMapper;
  final num yValueMapper;

  DisplayedData(
    this.xValueMapper,
    this.yValueMapper,
  );
}
```

![useSeriesColor_notRotated](https://user-images.githubusercontent.com/57846029/88153771-26bcd100-cc06-11ea-8b22-70353153fd98.png)
![useSeriesColor_rotatedBy90](https://user-images.githubusercontent.com/57846029/88153777-27556780-cc06-11ea-822e-180597fc1eb0.png)
![LabelAlignBottom_RotataedBy90](https://user-images.githubusercontent.com/57846029/88153793-2c1a1b80-cc06-11ea-9a4a-e66258b33495.png)
![labelAlignmentBottom_NotRotated](https://user-images.githubusercontent.com/57846029/88153794-2cb2b200-cc06-11ea-86ed-2b1c23d79dbb.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hnnngwdlch ,

We have analyzed your cenario and we are able to replicate the reported issues regarding the background of the label not rotating when label rotation is set and also the label alignment not working properly when the label is rotated. We will consider these as bugs and will include the fixes for the reported issues in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hnnngwdlch ,

Thanks for your patience. The reported issue regarding the background of the label not rotating when label rotation is set and also the label alignment not working properly when the label is rotated are fixed now and rolled out in our weekly patch release. To overcome the reported issue, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.47

Regards,
Sriram Kiran.

**Comment by hnnngwdlch** [comment]
Hi Sriram,

great! Thanks for the quick fix!

Best regards,
Henning
