### ISSUE TITLE
[CALENDAR] - Header not disappearing in Schedule View

### ISSUE THREAD

**Issue by Ahmadre** [syncfusion/flutter-examples#171]
Hello dear Syncfusion Team :),

at first: YOU ROCK! thank you for Updates!

But now I encountered, that the default header is also appearing in Schedule View:

![Screenshot_20200723-135823.png](https://user-images.githubusercontent.com/18512224/88284043-fac84b00-ccec-11ea-8cca-e110a2182ba6.png)

Would appreciate it, if you remove it there too.

Thanks :)

PS: I also encountered, that the header is switching while scrolling, how can I listen to that for my custom-header?

**Comment by Indumathi1195R** [comment]
Hi @Ahmadre,

**Regarding Query: The default header is not hidden issue**

We have checked the default header appearing issue in mobile web browser. It is working fine as expected from our end. Can you please check this issue in our latest release version and let us know if still you are facing the same issue? It would be helpful for us to analyze and provide you a solution at the earliest.

**Regarding Query:  That the header is switching while scrolling, how can I listen to that for my custom-header?**

Based on the provided information, we have checked, and your requirement is “**Custom header support for scheduleview in SfCalendar**”. We are logged the feature request for the same. We will implement this feature in our upcoming 2020 Volume 3 release, which is expected to roll out by September 2020 and let you know once the feature is implemented. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below mentioned link. 

**Feedback link:**
https://www.syncfusion.com/feedback/16400/custom-widget-support-scheduleview-header-and-week-header-in-flutter-event

Also, we have already logged the feature request for custom widget support for all calendar view appointments. Please find the feedback link,

**Feedback link:**
https://www.syncfusion.com/feedback/14380/custom-widget-support-for-appointments-in-flutter-event-calendar-sfcalendar

**Note:** viewChanged callback support provided when we switched from other calendar views to schedule view not while scheduleView scrolling.

Regards,
Indumathi R

**Comment by Ahmadre** [comment]
@Indumathi1195R BRILLIANT ❤️❤️❤️

IT WORKS :)))


I really love you guys! Really!
