### ISSUE TITLE
How to get or apply for community license ?

### ISSUE THREAD

**Issue by bizready** [syncfusion/flutter-examples#173]
Ref: https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

I am trying to see how to get a community version license. In the below link, I do not see any link for applying for a community license. Website https://www.syncfusion.com/downloads/flutter only talks about free-trial

Is there a process to get a community license?

**Comment by NiamhG** [comment]
You can get it from here
https://www.syncfusion.com/products/communitylicense

then follow these instructions
https://help.syncfusion.com/common/essential-studio/licensing/license-key
