### ISSUE TITLE
[CHART] - multiple errors with latest version

### ISSUE THREAD

**Issue by lukehold** [syncfusion/flutter-examples#175]
Lots of errors popping up with syncfusion_flutter_charts: ^18.2.47. Any advice?

``
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/barcodes_theme.dart:47:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfBarcodeThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/calendar_theme.dart:48:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfCalendarThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/charts_theme.dart:47:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfChartThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/datagrid_theme.dart:48:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfDataGridThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/daterangepicker_theme.dart:50:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfDateRangePickerThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/gauges_theme.dart:48:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfGaugeThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/maps_theme.dart:74:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfMapsThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/slider_theme.dart:80:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfSliderThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/theme_widget.dart:76:7: Error: Can't use 'Diagnosticable' as a mixin because it has constructors.
class SfThemeData with Diagnosticable {
      ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3053:9: Context: This constructor prevents using 'Diagnosticable' as a mixin.
  const Diagnosticable();
        ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/barcodes_theme.dart:47:7: Error: The non-abstract class 'SfBarcodeThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfBarcodeThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/calendar_theme.dart:48:7: Error: The non-abstract class 'SfCalendarThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfCalendarThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/charts_theme.dart:47:7: Error: The non-abstract class 'SfChartThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfChartThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/datagrid_theme.dart:48:7: Error: The non-abstract class 'SfDataGridThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfDataGridThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/daterangepicker_theme.dart:50:7: Error: The non-abstract class 'SfDateRangePickerThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfDateRangePickerThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/gauges_theme.dart:48:7: Error: The non-abstract class 'SfGaugeThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfGaugeThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/maps_theme.dart:74:7: Error: The non-abstract class 'SfMapsThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfMapsThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/slider_theme.dart:80:7: Error: The non-abstract class 'SfSliderThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfSliderThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/theme_widget.dart:76:7: Error: The non-abstract class 'SfThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfThemeData with Diagnosticable {
      ^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/range_slider_theme.dart:85:7: Error: The non-abstract class 'SfRangeSliderThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfRangeSliderThemeData extends SfSliderThemeData {
      ^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/range_selector_theme.dart:148:7: Error: The non-abstract class 'SfRangeSelectorThemeData' is missing implementations for these members:
 - DiagnosticableMixin.toDiagnosticsNode
 - DiagnosticableMixin.toStringShort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfRangeSelectorThemeData extends SfRangeSliderThemeData {
      ^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3110:19: Context: 'DiagnosticableMixin.toDiagnosticsNode' is defined here.
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
                  ^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3089:10: Context: 'DiagnosticableMixin.toStringShort' is defined here.
  String toStringShort() => describeIdentity(this);
         ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/barcodes_theme.dart:47:7: Error: The implementation of 'toString' in the non-abstract class 'SfBarcodeThemeData' does not conform to its interface.
class SfBarcodeThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/calendar_theme.dart:48:7: Error: The implementation of 'toString' in the non-abstract class 'SfCalendarThemeData' does not conform to its interface.
class SfCalendarThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/charts_theme.dart:47:7: Error: The implementation of 'toString' in the non-abstract class 'SfChartThemeData' does not conform to its interface.
class SfChartThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/datagrid_theme.dart:48:7: Error: The implementation of 'toString' in the non-abstract class 'SfDataGridThemeData' does not conform to its interface.
class SfDataGridThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/daterangepicker_theme.dart:50:7: Error: The implementation of 'toString' in the non-abstract class 'SfDateRangePickerThemeData' does not conform to its interface.
class SfDateRangePickerThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/gauges_theme.dart:48:7: Error: The implementation of 'toString' in the non-abstract class 'SfGaugeThemeData' does not conform to its interface.
class SfGaugeThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/maps_theme.dart:74:7: Error: The implementation of 'toString' in the non-abstract class 'SfMapsThemeData' does not conform to its interface.
class SfMapsThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/slider_theme.dart:80:7: Error: The implementation of 'toString' in the non-abstract class 'SfSliderThemeData' does not conform to its interface.
class SfSliderThemeData with Diagnosticable {
      ^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/theme_widget.dart:76:7: Error: The implementation of 'toString' in the non-abstract class 'SfThemeData' does not conform to its interface.
class SfThemeData with Diagnosticable {
      ^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/range_slider_theme.dart:85:7: Error: The implementation of 'toString' in the non-abstract class 'SfRangeSliderThemeData' does not conform to its interface.
class SfRangeSliderThemeData extends SfSliderThemeData {
      ^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/range_selector_theme.dart:148:7: Error: The implementation of 'toString' in the non-abstract class 'SfRangeSelectorThemeData' does not conform to its interface.
class SfRangeSelectorThemeData extends SfRangeSliderThemeData {
      ^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_internal/vm/lib/object_patch.dart:45:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'DiagnosticableMixin.toString'.
  String toString() native "Object_toString";
         ^
/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:3092:10: Context: This is the overridden method ('toString').
  String toString({ DiagnosticLevel minLevel = DiagnosticLevel.debug }) {
         ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/barcodes_theme.dart:146:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/calendar_theme.dart:440:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/charts_theme.dart:468:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/datagrid_theme.dart:243:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/daterangepicker_theme.dart:435:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/gauges_theme.dart:326:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/maps_theme.dart:434:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/slider_theme.dart:530:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-18.2.47/lib/src/theme/theme_widget.dart:293:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by SriramKiranSenthilkumar** [comment]
Hi @lukehold ,

Greetings from Syncfusion. We have analyzed your scenario with the provided information and we assume that you are using the outdated version of Flutter SDK and due to this only you are getting the compilation errors regarding the `Diagnosticable `when building. As the flutter team has removed the usage of `DiagnosticableMixin `in their latest beta and stable versions due to its duplicate implementation of `Diagnosticable`, we have also done the necessary changes in our chart source.

So, we kindly request you to upgrade your Flutter SDK version to the latest stable or beta channel in order to overcome the reported compilation errors by using any of the links below.

stable version: https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.5-stable.zip
Beta version: https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_1.20.0-7.2.pre-beta.zip

Please revert us if you still face problems after upgrading to the latest Flutter SDK version.

Regards,
Sriram Kiran

**Comment by lukehold** [comment]
Thanks, that was it. Much appreciated.
