### ISSUE TITLE
[Calendar] - how to handle navigation when CalendarView is schedule

### ISSUE THREAD

**Issue by angel1st** [syncfusion/flutter-examples#176]
Hi there,
Here is my case - when I switch between calendar different views, I can see `onViewChanged` is called every time. It is also called when I swipe to a new time period in the view, e.g. if I am in `CalendarView.month` if I swipe to prev / next month `onViewChanged` is called. So far so good.
However, when I switch to `CalendarView.schedule` if I scroll back / forth, `onViewChanged` is not called.
Is there a way, I can get info about scrolling when in the `schedule` view?
The reason I ask - I have a large number of appointments, which I store in DB. When I am in a specific view, I can get from `onViewChanged` callback `viewChangedDetails.visibleDates` and hence, request appointments for that specific date range. However, when I switch to the `schedule` view, I have got an `onViewChanged` called once, where `viewChangedDetails.visibleDates` holds the previously selected single date only. However, when I scroll it to prev / next dates, I am not able to load prev / next appointments, since I haven't been notified. 
Is there a way, I can make it work as I need?

**Comment by Indumathi1195R** [comment]
Hi @angel1st,

Based on the provided information, we have checked and now viewChanged callback support provided initially for the scheduleView not scrolling. So, we have logged the feature request for “onLoadMore callback for schedule view in the Flutter calendar”. We will implement this feature in any of our upcoming releases and let you know once release rolled out. We appreciate your patience until then.

You can track the current status of this report by the following link,

**Link:** https://www.syncfusion.com/feedback/16628/provide-a-support-for-onloadmore-callback-in-the-flutter-event-calendar-sfcalendar

Regards,
Indumathi R

**Comment by angel1st** [comment]
Thanks, @Indumathi1195R for your prompt response! I will watch the provided link!

**Comment by angel1st** [comment]
@JayavigneshwaranG - any updates on that?

**Comment by Indumathi1195R** [comment]
Hi @angel1st,

We will implement this feature “**onLoadMore callback for schedule view in the Flutter event calendar**” in our upcoming 2020 Volume 4 release, which is expected to roll out by month of December 2020 and let you know once release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @angel1st ,

We have included the following [features ](https://help.syncfusion.com/flutter/release-notes/v18.4.0.30?type=all)in our 2020 Volume 4 release feature. Due to this, we have postponed this feature “**Provide a support for onLoadMore callback in the Flutter event calendar (SfCalendar)**” to 2021 Volume 1 release, which is expected to roll out by the month of March 2021 and let you know once release rolled out. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below feedback link. 

**Link:** https://www.syncfusion.com/feedback/16628/provide-a-support-for-onloadmore-callback-in-the-flutter-event-calendar-sfcalendar

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi, 
 
We are glad to announce that our **2021 Volume 1 release (version 19.1.54)** is rolled out with the mentioned feature “**Provide a support for onLoadMore callback in the Flutter event calendar (SfCalendar)”**. Kindly update to the latest version for this feature. Please find the latest version, release notes and changelog from the following links.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

**Release notes link:**
 https://help.syncfusion.com/flutter/release-notes/v19.1.0.54?type=all#sfcalendar-features

**Changelog link:**
https://pub.dev/packages/syncfusion_flutter_calendar/changelog

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
