### ISSUE TITLE
[DateRangePicker] How to use with CoachMark

### ISSUE THREAD

**Issue by Adejair** [syncfusion/flutter-examples#177]
Hi,

Users of my app have much questions to use date range calendar, because of UX. I have ideia to implement coack mark in calendar to show road to use range calendar in my app. 

My question is, how to get `context` from single day(in calendar) to mark with coack mark. Coack Mark lib requires context from object to mark.

[Coack Mark package](https://pub.dev/packages/highlighter_coachmark)

**Comment by Indumathi1195R** [comment]
Hi @Adejair ,

Based on the provided information, we have checked your requirement “**Getting the context of the single day in SfDateRangePicker**”. As per the date picker implementation, we have drawn the picker views in the same view. So, the same context applied to all picker views. So, as per the current implementation, this is not possible.

Regards,
Indumathi R
