### ISSUE TITLE
[Calendar] - onTap callback not always returns properly cast calendarTapDetails.appointments collection

### ISSUE THREAD

**Issue by angel1st** [syncfusion/flutter-examples#179]
Hi there. I found out that `onTab` callback not always return `calendarTapDetails.appointments` collection which can be cast to original `UserAppointment` class. 
Here is the case:

```
class RecurrentActivity {
  final ScheduledActivity scheduledActivity;
  const RecurrentActivity({
    @required this.scheduledActivity,
  });
  DateTime get startDate => scheduledActivity.dueDate;
  DateTime get endDate =>
      scheduledActivity.dueDate.add(const Duration(minutes: 30));
  int get plantId => scheduledActivity.plantId;
  String get name => scheduledActivity.activityType.name;
  String get imagePath => scheduledActivity.activityType.imagePath;
  Color get color => scheduledActivity.activityType.color;
}

class RecurrentCalendarDataSource extends CalendarDataSource {
  RecurrentCalendarDataSource({@required List<RecurrentActivity> activities}) {
    appointments = activities;
  }
  @override
  DateTime getStartTime(int index) {
    final RecurrentActivity activity = appointments[index];
    return activity.startDate;
  }

  @override
  DateTime getEndTime(int index) {
    final RecurrentActivity activity = appointments[index];
    return activity.endDate;
  }

  @override
  String getSubject(int index) {
    final RecurrentActivity activity = appointments[index];
    return activity.scheduledActivity.activityType.name;
  }

  @override
  Color getColor(int index) {
    final RecurrentActivity activity = appointments[index];
    return activity.color;
  }

  @override
  bool isAllDay(int index) {
    return false;
  }

  @override
  String getRecurrenceRule(int index) {
    final RecurrentActivity activity = appointments[index];
    final String rule = 'FREQ=${activity.scheduledActivity.periodType.frequency};INTERVAL=${activity.scheduledActivity.count}';
    return rule;
  }
}

```
as you can see, there is a list of recurrent appointments, however, I use my own `RecurrentActivity` class, since I have additional data, I would like to carry.
This is how I process `onTab` callback:

```
                    onTap: (CalendarTapDetails calendarTapDetails) {
                      if (calendarTapDetails.targetElement ==
                          CalendarElement.calendarCell) {
                        Appointment app;
                        List<RecurrentActivity> activities = calendarTapDetails
                            .appointments
                            .map((a) => a as RecurrentActivity) // <- this is where I have got exception
                            .toList();
                        _recurrentCalendarBloc.add(
                          RecurrentCalendarEventSelectDate(
                            selectedDate: _calendarController.selectedDate,
                            activities: activities,
                          ),
                        );
                      }
                    },

```
What I found out, is that occasionally when I am in `CalendarView.agenda` mode, `activities` list returned in `onTab` callback holds `Appointment` items rather than `RecurrentActivity` ones. Usually, when I click 10 - 15 times on different cells, this happens. However, at that moment, when I have got `Appointment` item rather than `RecurrentActivity` one, I observe `Appointment._data` holds the correct `RecurrentActivity` value. So if I can obtain the value from there, I will be good.

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the provided information, we have checked the mentioned issue “**onTap callback doesn’t return proper casting appointment value sometimes**” with the latest calendar package version (18.2.48) and we are unable to replicate the mentioned issue and it is working fine as expected from our end. We have prepared a simple sample and video for the same. Please find the sample and video from the following links.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/288478/ze/flutter_dayweeksample-470504504.zip

**Video link:**
 https://www.syncfusion.com/downloads/support/directtrac/288478/ze/Video-1635095204.zip

Is possible, can you please replicate the mentioned issue in the attached sample. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by angel1st** [comment]
@Indumathi1195R - I am not able to download the zip file you have attached - this is the message, I have got:
 
![sync-files](https://user-images.githubusercontent.com/8547131/89547152-131c8780-d80e-11ea-9431-972b70788a6e.png)

I suspect the reason is that my syncfusion account is associated with angel.todorov@agilebs.com email address. I would appreciate if you resolve the issue, so I can download & try the example.

**Comment by Indumathi1195R** [comment]
Hi @angel1st,

Please check the attached sample and revert us back.
[flutter_dayweeksample.zip](https://github.com/syncfusion/flutter-examples/files/5036213/flutter_dayweeksample.zip)


Regards,
Indumathi R

**Comment by angel1st** [comment]
Hi @Indumathi1195R, the issue was caused by a bug in my own code. Thanks for your time and efforts. I am closing the issue since it has nothing to do with your package. Thanks one more time!
