### ISSUE TITLE
[Calendar] - is it possible to retrieve recurrent appointments for specific date without onTap interaction?

### ISSUE THREAD

**Issue by angel1st** [syncfusion/flutter-examples#181]
Hi there,
I have a calendar, populated with recurrent appointments. If I tap on a specific date, I can easily obtain all appointments for the date via `onTap` callback. So far so good.
However, at some point when I change the view and `onViewChanged` is activated, I would like to retrieve the recurrent appointments for a specific date e.g. for the selected date, which is available via `_calendarController.selectedDate`.
Why I need that? I have a custom agenda view and when I switch between daily view and agenda view, I would like to list all appointments, in case the date is selected.
How can I do that?

**Comment by Muniappan612** [comment]
Hi @angel1st ,

Based on the shared information, we have checked the query “**Retrieve recurrent appointments for specific date without onTap interaction**”. As of now, there is no support for getting appointments on a specific date and it can be achieved on a sample level using the **GetRecurrenceDateTimeCollection** method in SfCalendar.

 Please find the KB link for get appointments on specific date. 
https://www.syncfusion.com/kb/11570/how-to-update-the-custom-agenda-view-events-when-selected-date-changes-in-the-flutter

We hope that this helps you.

Regards,
Muniappan Subramanian.

**Comment by angel1st** [comment]
@Muniappan612 - thanks for the feedback. I must say, the example you referred to works, however, it has one caveat - `SfCalendar.getRecurrenceDateTimeCollection` does not return a list of dates in case either **rule pattern** misses `COUNT` parameter or both `specificStartDate` and `specificEndDate` are not present in the call.
Other than that, the suggestion allows me to retrieve the required appointments for the specific date. I am closing the issue.
