### ISSUE TITLE
onPointClick instead of onPointTapped

### ISSUE THREAD

**Issue by prabel** [syncfusion/flutter-examples#182]
Hey,
Thanks for the great package. I'm using few different Chart widgets and as I see there is only the option to get a callback from `onPointTapped`. Is it possible to handle click action instead of tap ? In some cases it is very annoying for users, we he/she is trying for example scroll page and my accident tap gesture is captured by chart and some actions occur (like opening new screen with details)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @prabel ,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some information about the **`OnPointTapped `** event available in the chart. This event will work fine in the web for click actions and in mobile platforms, this event fires when the user taps down on the screen. This is the current behaviour.

And for this query “In some cases, it is very annoying for users when he/she is trying for example scroll page and my accident tap gesture is captured by chart”. To avoid this issue regarding the triggering of this event (**OnPointTapped**) on the scroll, we have planned to change the gesture from **onTapDown** to **onTap** from our side. We will change and include this fix in our upcoming weekly patch release which is expected to be rolled out by 25th August 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by prabel** [comment]
Great, thank you for quick answer. I will looking forward for new version

**Comment by SriramKiranSenthilkumar** [comment]
Hi @prabel,

Thanks for your patience. The reported issue regarding the triggering of the event (OnPointTapped) on the scroll is fixed now and included in our weekly patch release which is already rolled. To overcome the reported issue, kindly upgrade the chart widget package version to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.55

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran
