### ISSUE TITLE
test with Syncfusion 

### ISSUE THREAD

**Issue by guti30** [syncfusion/flutter-examples#184]
hi, I try to do some test with flutter driver, and can't do with this dependency, the problem is that when the test tap in the view of the calendar, it can't found the letter of the days to tap, if you now how can prove this or if we need to use something else to do it,

thanks

**Comment by Indumathi1195R** [comment]
Hi @guti30,

Currently, we are validating this issue. We will validate and let you know the details on or before August 18, 2020. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @guti30 ,

We have analyzed the reported issue and our calendar control was implemented based on the custom painter. We have checked the mentioned issue and we have tried to find the element by using the below commands.

•	find.text('string') 
•	find.bySemanticsLabel('Label') 

and the element is not null, but the tapping doesn't occur. So, we have logged the issue report in GitHub. If we got any solution from the GitHub, we will update to you. Please find the GitHub link for the same.

**GitHub link:**
https://github.com/flutter/flutter/issues/64048

Regards,
Indumathi R

**Comment by guti30** [comment]
Thanks :)
