### ISSUE TITLE
DoughnutSeries groupMode label text problem

### ISSUE THREAD

**Issue by ydenizs** [syncfusion/flutter-examples#185]
Hi,

Is there any way to change "others" text in DoughnutSeries chart? Also, "others" group's percentage text is "others". Can we change it?

Thanks.

![image](https://user-images.githubusercontent.com/62982726/90289114-e3135b00-de83-11ea-8176-2ba0ff9ff7ca.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @ydenizs ,

We have analyzed your requirement and the data labels can be customized by using the onDataLabelRender event. Find the code snippet below to achieve this.

`
  SfCircularChart(          
    onDataLabelRender: (DataLabelRenderArgs args)          
        {             
          if(args.text == 'Others')              
               args.text ='%' + args.dataPoints[args.pointIndex].y.toString();          
          },          
         //other configurations       
 )`

You can modify this based on your scenario. We have attached the main.dart file for your reference which can be found below.


[main.dart.zip](https://github.com/syncfusion/flutter-examples/files/5084041/main.dart.zip)

For more information on the events, find the user guide below.

https://help.syncfusion.com/flutter/circular-charts/callbacks#ondatalabelrender

 

Thanks,

Dharani.
