### ISSUE TITLE
[syncfusion_flutter_charts] Label position and alignment does not change if we use the label builder

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#189]
This is my Column Series
```
ColumnSeries<CheckIn, String>(
            color: _getChartColor(),
            width: 0.125,
            borderRadius: BorderRadius.all(Radius.circular(2)),
            isTrackVisible: true,
            trackColor: _getTrackColor(),
            trackBorderWidth: 0,
            dataLabelSettings: DataLabelSettings(
              isVisible: true,
              builder: _buildLabel,
              labelPosition: ChartDataLabelPosition.outside,
              labelAlignment: ChartDataLabelAlignment.middle
            ),
            dataSource: ...,
            xValueMapper: ...,
            yValueMapper: ...,
```

This is my label builder
```
Widget _buildLabel(
    dynamic data,
    dynamic point,
    dynamic series,
    int pointIndex,
    int seriesIndex,
  ) {
    return Container(
      padding: const EdgeInsets.all(6),
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: _getDataLabelColor(),
      ),
      child: Text(
        point.y.toInt().toString(),
        style: TextStyle(
          fontFamily: AppTheme.fontFamilySF,
          fontWeight: FontWeight.w500,
          fontSize: 12,
          color: _getDataLabelTextColor(),
        ),
      ),
    );
  }
```

When I use `builder`, `labelPosition` and `labelAlignment` are ignored.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some information regarding the label position property available in the **`DataLabelSettings`**. The **`labelPosition`** property is only applicable for the pie, doughnut series types and it is not applicable for cartesian series types. For further reference, please check the API reference link below,
https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/labelPosition.html

For aligning the data label or the data label builder, the **`labelAlignment`** property available in the **`DataLabelSettings`** can be used in which you can set the values such as auto, top, bottom, middle or outer to align the cartesian chart type data labels. For further reference, please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#label-position

Also to mention that currently, we are working on a feature for adding new properties such as **`verticalPadding`** and **`horizontalPadding`** for the data label in the **`DataLabelSettings`** with which you can be able to move the data label/data label builder vertically or horizontally according to the provided pixel values. We are planned to include this feature in our Vol 3 main release which is expected to be rolled out by the end of next month (September 2020).

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran

**Comment by AndreHaueisen** [comment]
Hi @SriramKiranSenthilkumar 
Thanks for the clarification. Now it is clear the difference between `labelPosition` and `labelAlignment`.
That said, `labelAlignment` is still being ignored when we use the label builder. I still think there is a bug there.
Please, let me know what you think.

`verticalPadding` and `horizontalPadding` will help a lot. Thanks for letting me know.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen,

We are sorry that we have missed conveying to you on a piece of information about the data label builder. We have recently only provided alignment support for the data label builder in our chart source and using the same **`labelAlignment`** property itself now you can be able to align the data label builder in the cartesian chart. This support is already included and released in our weekly patch release which was released today (26th August 2020). So, to overcome the reported issue, kindly upgrade the chart widget package version to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.55

Regards,
Sriram Kiran

**Comment by AndreHaueisen** [comment]
Oh. Nice. It works now. Thank you @SriramKiranSenthilkumar

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen ,

Thanks for your patience. The requested feature regarding the addition of a property for the data label in the **DataLabelSettings** which will be helpful in moving the data labels/ data label builder in the chart horizontally or vertically according to the provided pixel values is now included and rolled out in our vol 3 main release. The property name is called as **`offset`** of the **`DataLabelSettings`** available in the chart. To use this property, kindly please upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.35

For further information in the **offset** property of the DataLabelSettings, please check the API reference link below.
https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/offset.html

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran

**Comment by AndreHaueisen** [comment]
Thank you!
