### ISSUE TITLE
SfCircularChart - tooltip is not always visible

### ISSUE THREAD

**Issue by prabel** [syncfusion/flutter-examples#192]
Hi,
In some cases, not all tooltips are visible when using **SfCircularChart**. What does it depend on ? Are we able to make it always visible? 

<img width="409" alt="Zrzut ekranu 2020-08-30 o 16 29 37" src="https://user-images.githubusercontent.com/3511381/91661796-7c767a00-eade-11ea-8226-c736f0313898.png">
<img width="412" alt="Zrzut ekranu 2020-08-30 o 16 29 52" src="https://user-images.githubusercontent.com/3511381/91661797-7e403d80-eade-11ea-91ef-dd9b8bfc5c7e.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @prabel ,

Thanks for using our chart widget. We have analyzed your scenario with the provided information and the tooltip which you have mentioned in your query is actually the data label of the pie data points and the query regarding not all tooltips (datalabels) are visible when using SfCircularChart, this hiding of data labels in the chart can be overcome by setting the **`labelIntersectAction`** property available in the **`DatalabelSettings`** to **LabelIntersectAction.none** along with **`labelPosition`** property set to **ChartDataLabelPosition.outside**. Please refer the code snippet below for further reference.
```
SfCircularChart(
    series: <CircularSeries>[
       PieSeries<ChartData, String>(
           dataSource: chartData,
           xValueMapper: (ChartData data, _) => data.x,
           yValueMapper: (ChartData data, _) => data.y,
           // Radius for each segment from data source
           pointRadiusMapper: (ChartData data, _) => data.size,
           dataLabelSettings: DataLabelSettings(
               isVisible: true,
               labelPosition: ChartDataLabelPosition.outside, // Places the data labels outside the pie area
               // By setting the below property to none value, does not hides the data label that are getting hidden due to intersection
               labelIntersectAction: LabelIntersectAction.none 
           )
       )
    ]
)
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/63577117/91729858-c89aea80-ebc2-11ea-9248-fe837ebd75ac.png)

The sample for reference can be found below.
[piesample.zip](https://github.com/syncfusion/flutter-examples/files/5150821/piesample.zip)

For further reference on data label positioning, please check the user guide below.
https://help.syncfusion.com/flutter/circular-charts/datalabel

Please check the attached sample and revert us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by prabel** [comment]
Great, thank you for your quick response.
I just checked and it works perfectly as I wish
