### ISSUE TITLE
[syncfusion_flutter_charts][Question] How can I change the initial chart scroll position?

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#193]
I have panning enabled - `zoomPanBehavior: ZoomPanBehavior(enablePanning: true` - and my X-axis is a `DateTimeAxis`.

When the chart is created, it shows the first date in ascending order like so. To see my last date, I need to scroll all the way to the right.
![Screenshot_1598962180](https://user-images.githubusercontent.com/13854934/91849731-e142e900-ec32-11ea-85a7-d5612a208688.png)

My question is: is there a way to make it show my last date on creation? Example:
![Screenshot_1598962234](https://user-images.githubusercontent.com/13854934/91849812-00da1180-ec33-11ea-8bdc-54909e9e5a0f.png)

I tried `isInversed` but it is not what I'm looking for.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AndreHaueisen,

Greetings from Syncfusion. We have analyzed your scenario with the provided information, and we would like to share some information on the **visibleMinimum** and **visibleMaximum** property of an axis available in the chart. With the help of these two properties, you can be able to change the visible range for the chart on initial render and then using the panning feature you can pan across the chart to view other points which are outside the visible range. We have created a simple sample like in the provided screenshot in which we have provided a visible range according to the requested scenario regarding the showing of last data points on the creation of the chart. Please refer the code snippet below for reference.
```
SfCartesianChart(
            primaryXAxis: DateTimeAxis(
                visibleMinimum: chartData.last.year.add(Duration(days: -15)), // Set the minimum value according to the last data point in the chart data source.
                visibleMaximum: chartData.last.year), // Set the maximum value as the last data point in the data source.
            primaryYAxis: NumericAxis(
                majorTickLines: MajorTickLines(width: 0),
                axisLine: AxisLine(width: 0),
                minimum: 0,
                maximum: 10,
                interval: 1,
                opposedPosition: true),
            series: <ChartSeries<SalesData, DateTime>>[
              ColumnSeries<SalesData, DateTime>(
                  // your configuration
                  dataSource: chartData,
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
              ) 
            ]
)
```
The sample for reference can be found below.
[193_sample.zip](https://github.com/syncfusion/flutter-examples/files/5162598/193_sample.zip)

Please check the attached sample and revert us if you still have concerns.

Regards,
Sriram Kiran

**Comment by AndreHaueisen** [comment]
@SriramKiranSenthilkumar 
Once again, thank you.

Cheers!
