### ISSUE TITLE
[Date Picker] - Chinese MonthHeaer Incorrect translation?

### ISSUE THREAD

**Issue by xieyezi** [syncfusion/flutter-examples#197]
Hi, Thank you for providing such a great project. 

## Phenomenon

 I have some problems：

When I seetting `Locale` : `zh`,like this:
```dart
  locale: Locale('zh'),
```
But the MonthHeaer belcome like this:

![image](https://user-images.githubusercontent.com/16821989/92061549-28fb7900-edc9-11ea-856b-9cb39c304ad3.png)

The MonthHeaer  red part circled，translation Incorrect.  The '周' mean 'week' , is not mean 'Monday, Tuesday, Wednesday
....' .

## Want Help

I guess the reason of this , because There Only shorthand, like 'M、T、W...'

Sincerely hope to get your help and reply !!!

**Comment by Indumathi1195R** [comment]
Hi @xieyezi ,

Based on the provided information, we have checked and we are able to reproduce the mentioned issue “**Incorrect locale translation in month header of the date range picker**”. We will include the issue fix in our upcoming Weekly Nuget package, which is expected to be rolled out by September 8, 2020 and let you know once release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by xieyezi** [comment]
@Indumathi1195R  

Thanks Sincerely !!😄

**Comment by Indumathi1195R** [comment]
Hi @xieyezi ,

We have included the mentioned issue fix “**Incorrect locale translation in month header of the date range picker**” in our latest Weekly Nuget package. Kindly update the Flutter calendar package to the latest version (**18.2.57-beta**) to resolve the issue. Also please find the changelog for the same.

**Link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog

Regards,
Indumathi R

**Comment by xieyezi** [comment]
@Indumathi1195R 
I have confirmed and solved this problem!
thank you again😄
