### ISSUE TITLE
Error: depends on intl

### ISSUE THREAD

**Issue by gladson** [syncfusion/flutter-examples#20]
This error occurred today when I went to update the flutter.

```shell
[erpmobile] flutter packages get
Running "flutter pub get" in erpmobile...                  
Because syncfusion_flutter_charts >=1.0.0-beta.4 depends on intl ^0.15.7 and erpmobis depends on intl ^0.16.0, syncfusion_flutter_charts >=1.0.0-beta.4 is forbidden.

So, because erpmobis depends on syncfusion_flutter_charts ^1.0.0-beta.4, version solving failed.
pub get failed (1)
exit code 1
```

Thank you guys

**Comment by dharanidharandharmasivam** [comment]
Hi @gladson ,

The reported scenario occurs at your end since our chart widget depends upon the intl dependency with version 0.15.7. We will upgrade the intl dependency to the current version in our upcoming update. We appreciate your patience until then. 

Thanks,
Dharani.

**Comment by gladson** [comment]
> Hi @gladson ,
> 
> The reported scenario occurs at your end since our chart widget depends upon the intl dependency with version 0.15.7. We will upgrade the intl dependency to the current version in our upcoming update. We appreciate your patience until then.
> 
> Thanks,
> Dharani.


Thank you, @dharanidharandharmasivam, for your quick return.

**Comment by JayavigneshwaranG** [comment]
Hi @gladson ,

Thanks for your patience.
Now we have referred the latest version intl library in the charts package and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). Thus your reported issue will be resolved.
We are closing this issue. You can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by diezep** [comment]
This is a problem now again
