### ISSUE TITLE
[Date Picker] - Month Custom View Header

### ISSUE THREAD

**Issue by JasonHezz** [syncfusion/flutter-examples#200]
![image](https://user-images.githubusercontent.com/15358765/92957507-34baff80-f49b-11ea-9956-51a61f52dd87.png)
I want custom month view header with different text style, a use case is weekends have different text color

**Comment by Indumathi1195R** [comment]
Hi @JasonHezz ,

Based on the provided information, we have checked and your requirement is “**Custom view header with different text colors for weekends**” and it can be achieved by hiding the header and view header of the date picker using the **headerHeight** and **viewHeaderHeight** property value as 0. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:**
[flutter_customviewheader.zip](https://github.com/syncfusion/flutter-examples/files/5216722/flutter_customviewheader.zip)

Please find the UG link for the same.

https://help.syncfusion.com/flutter/daterangepicker/headers
https://help.syncfusion.com/flutter/daterangepicker/headers#view-header

Also, we have a **KB document** for the date range picker header customization. Please find the KB from the following link,

https://www.syncfusion.com/kb/11897/how-to-customize-the-header-in-flutter-multi-date-range-picker-sfdaterangepicker

https://www.syncfusion.com/kb/11427/how-to-customize-the-header-view-of-the-flutter-date-range-picker

We hope that this helps you. Please let us know if you need further assistance.

**Note:**
In the custom header, we are unable to navigate the other views using header navigation.

Regards,
Indumathi R
