### ISSUE TITLE
[Chart] Big data zoom and move

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#202]
Hi
After adding a lot of candles, it slows down the movement and zooms

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi ,

Greetings from Syncfusion. We have analyzed your scenario at our end and we would like to share some information regarding the performance of the candle series available in the chart. We have measured the performance metrics of the candle series with the various number of data points and provided the metrics below for your reference. 
Candle with number of data sources | performance metrics(Time taken to render)
------------ | -------------
Candle Series 1k | 55 ms(0.055s)
Candle Series 10k | 300 ms(0.3s)
Candle Series 1lakh | 4000 ms(4s)
Candle Series 5 lakh | 34000(34s)


The above metrics show the current rendering performance of the candle series and we are also currently planning on improving the performance furthermore regarding the chart series rendering and zooming behaviour. We will include these improvements in any of our upcoming releases yet to come and we appreciate your patience until then.

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran
