### ISSUE TITLE
[Chart] add zoom and move animations

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#203]
Please add animation mode to move and zoom for users to enjoy

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi ,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some regarding the series animations and the axis animations available in our chart widget. The `series animation` in our chart is of two types, one occurs at the initial rendering animation of the chart and another is the dynamic animation which occurs when there is any data addition or data update in the chart and this animation also work when the chart is in zoomed state too. For further reference on the series animation, kindly please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/series-customization#animation 

The `axis animation` available in the chart can be enabled using the `enableAxisAnimation `property of the chart. By setting this property to true, the axis elements like grid lines, tick lines, and labels will be animated when the axis range is changed dynamically. For further reference on Axis animation, please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#axis-animation

Please get in touch with us if you require further assistance.

Regards,
Sriram Kiran
