### ISSUE TITLE
[Chart] big data 10k

### ISSUE THREAD

**Issue by m2faridi** [syncfusion/flutter-examples#204]
When we do not work on 10,000 pieces of information, it stops completely
Information that is not on the page should not be processed

**Comment by SriramKiranSenthilkumar** [comment]
Hi @m2faridi ,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some information regarding the lazy loading feature which will process only the data which is to be rendered in the chart and will not process the remaining data outside the range and on panning, another set of data will be loaded and processed. This feature will be useful for your case. We have already logged feedback regarding this feature in our feedback portal. We will implement and include this feature in any of our upcoming releases yet to come. You can also track the status of the feature using the below feedback link.
https://www.syncfusion.com/feedback/11947

Regards,
Sriram Kiran

**Comment by m2faridi** [comment]
I want to buy your chart but it does not work for me as long as this problem exists, please fix the problem
