### ISSUE TITLE
Create PDF from HTML

### ISSUE THREAD

**Issue by Sun3** [syncfusion/flutter-examples#207]
I would like to request a feature to add a way to created PDF files from HTML.

Thank you,

**Comment by chinnumuniyappan** [comment]
Hi @Sun3 ,

Greetings from Syncfusion. We have logged the feature request for "Add support for converting HTML to PDF in Flutter platform" in our feature request list. At present we do not have any immediate plan to implement this feature in our end. We will implement this feature any of our upcoming releases, you can track the current status of this feature request by using the below-mentioned link.

https://www.syncfusion.com/feedback/18068/add-support-for-converting-html-to-pdf-in-flutter-platform

Regards,
Chinnu M

**Comment by Sun3** [comment]
Thank you.
