### ISSUE TITLE
Suggestion : added the possibility to change the color of the curve, and of the area, depending on the value

### ISSUE THREAD

**Issue by pbouttier** [syncfusion/flutter-examples#208]
Hi,

For the clarity of the graphs, it can be interesting to have different colors on the line and the area.

For example, google_charts implements it, see example here : https://google.github.io/charts/flutter/example/line_charts/segments

I personally use it to differentiate groups of values, like here, each color represents a given date 

![image](https://user-images.githubusercontent.com/36472673/93769513-2ac39a00-fc1b-11ea-9c86-73ed4f7ce43e.png)

This plugin seems to go further on many points than google's one, but this feature is essential to me, could it be added in the future ? 

I have seen a similar comment https://github.com/syncfusion/flutter-examples/issues/119
The same thing on areaSeries and equivalent should be great :) 

Thanks,

**Comment by SriramKiranSenthilkumar** [comment]
Hi @pbouttier,

Greetings from Syncfusion. We have analyzed on your scenario and we are sorry that currently, we do not have support for segments in cartesian area series available in our chart widget. However, we have considered your suggestion as a feature request and created feedback for it in our feedback portal. We will plan and include the requested feature in any of our upcoming releases yet to come. You can also trackt the status of the feature using the below feedback link.
https://www.syncfusion.com/feedback/18202/

Please get in touch with us if your require further assistance.

Regards,
Sriram Kiran
