### ISSUE TITLE
[Chart] [Bug] SFCartesianChart Lines disappear on returning back to DetailView

### ISSUE THREAD

**Issue by devrajraut** [syncfusion/flutter-examples#209]
In my Code, I have a Master page and a DetailView Page. On the Master Page I tap on a Widget and get to the Detail Page which shows a SfCartesianChart. The Data comes from FireStore and all works fine.
But I go Back to Master and come back to the Same DetailView again and the lines on the chart reanimate and disappear. Although the Data Points remain on the chart and no error is thrown and everything works. Just that the lines disappear. 

Only when I Change BottomNavigationTab and come back to the Home Tab followed by DetailView then the Lines come back. 

This is my SFCartesianChart Code inside a Container: 

child: SfCartesianChart(
                      enableAxisAnimation: true,
                      tooltipBehavior: TooltipBehavior(
                          activationMode: ActivationMode.singleTap,
                          animationDuration: 1000,
                          enable: true,
                          shared: true,
                          elevation: 10,
                          tooltipPosition: TooltipPosition.auto,
                          shouldAlwaysShow: true),
                      legend: Legend(
                          isVisible: true,
                          isResponsive: true,
                          position: LegendPosition.bottom,
                          orientation: LegendItemOrientation.horizontal,
                          overflowMode: LegendItemOverflowMode.scroll),
                      selectionType: SelectionType.point,
                      selectionGesture: ActivationMode.singleTap,
                      zoomPanBehavior: ZoomPanBehavior(
                        enablePinching: true,
                        enablePanning: true,
                        zoomMode: ZoomMode.x,
                      ),
                      title: ChartTitle(
                        text: widget._chartlabel,
                        textStyle: Theme.of(context).textTheme.headline6,
                      ),
                      primaryXAxis: DateTimeAxis(
                          isVisible: true,
                          interactiveTooltip: InteractiveTooltip(
                              color: AppTheme.hexWhite, enable: true),
                          minimum: DateTime(2020, 01, 01),
                          visibleMinimum: DateTime(
                              DateTime.now().year, DateTime.now().month),
                          maximum: DateTime.now().add(Duration(days: 1)),
                          labelIntersectAction:
                              AxisLabelIntersectAction.multipleRows,
                          dateFormat: DateFormat('d MMM yy'),
                          intervalType: DateTimeIntervalType.auto,
                          enableAutoIntervalOnZooming: true,
                          labelAlignment: LabelAlignment.center,
                          labelStyle: Theme.of(context)
                              .textTheme
                              .caption
                              .copyWith(color: AppTheme.hexWhite),
                          associatedAxisName: 'Date',
                          placeLabelsNearAxisLine: false,
                          edgeLabelPlacement: EdgeLabelPlacement.shift),
                      primaryYAxis: NumericAxis(
                        isVisible: true,
                        anchorRangeToVisiblePoints: false,
                        labelStyle: Theme.of(context)
                            .textTheme
                            .bodyText2
                            .copyWith(color: AppTheme.hexWhite),
                        labelPosition: ChartDataLabelPosition.inside,
                        labelAlignment: LabelAlignment.end,
                        numberFormat: NumberFormat('###'),
                        associatedAxisName: 'Workload',
                        decimalPlaces: 0,
                        majorGridLines: MajorGridLines(width: 0),
                        majorTickLines: MajorTickLines(width: 0),
                        minorGridLines: MinorGridLines(width: 0),
                        minorTickLines: MinorTickLines(width: 0),
                      ),
                      series: [
                        if (_tertiaryWorkload != null)
                          SplineSeries<DataPoint<DateTime>, DateTime>(
                            dataSource: _tertiaryWorkload,
                            xValueMapper: (DataPoint workload, _) =>
                                workload.xAxis,
                            yValueMapper: (DataPoint workload, _) =>
                                workload.value,
                            enableTooltip: true,
                            xAxisName: 'Date',
                            yAxisName: 'Tertiary Workload',
                            name: _tertiaryLegend,
                            color: AppTheme.hexGreen,
                            markerSettings: MarkerSettings(
                                isVisible: true,
                                height: 10,
                                width: 10,
                                color: AppTheme.hexBlack,
                                shape: DataMarkerType.triangle),
                            splineType: SplineType.monotonic,
                            emptyPointSettings: EmptyPointSettings(
                                mode: EmptyPointMode.zero,
                                color: AppTheme.hexBlack,
                                borderColor: AppTheme.hexWhite,
                                borderWidth: 2),
                            isVisible: true,
                            isVisibleInLegend: true,
                            legendIconType: LegendIconType.triangle,
                          ),
                        if (_secondaryWorkload != null)
                          SplineSeries<DataPoint<DateTime>, DateTime>(
                            dataSource: _secondaryWorkload,
                            xValueMapper: (DataPoint workload, _) =>
                                workload.xAxis,
                            yValueMapper: (DataPoint workload, _) =>
                                workload.value,
                            enableTooltip: true,
                            xAxisName: 'Date',
                            yAxisName: 'Secondary Workload',
                            name: _secondaryLegend,
                            color: AppTheme.hexOrange,
                            markerSettings: MarkerSettings(
                                isVisible: true,
                                height: 10,
                                width: 10,
                                color: AppTheme.hexBlack,
                                shape: DataMarkerType.invertedTriangle),
                            splineType: SplineType.monotonic,
                            emptyPointSettings: EmptyPointSettings(
                                mode: EmptyPointMode.zero,
                                color: AppTheme.hexBlack,
                                borderColor: AppTheme.hexWhite,
                                borderWidth: 2),
                            isVisible: true,
                            isVisibleInLegend: true,
                            legendIconType: LegendIconType.invertedTriangle,
                          ),
                        SplineSeries<DataPoint<DateTime>, DateTime>(
                          dataSource: _primaryWorkload,
                          // dataLabelSettings: DataLabelSettings(
                          //   isVisible: true,
                          // ),
                          xValueMapper: (DataPoint workload, _) =>
                              workload.xAxis,
                          yValueMapper: (DataPoint workload, _) =>
                              workload.value,
                          enableTooltip: true,
                          xAxisName: 'Date',
                          yAxisName: 'Workload',
                          name: 'You',
                          color: MediaQueryConfig.isDarkMode
                              ? AppTheme.hexBlack
                              : AppTheme.hexWhite,
                          markerSettings: MarkerSettings(
                            isVisible: true,
                            color: !MediaQueryConfig.isDarkMode
                                ? AppTheme.hexBlack
                                : AppTheme.hexWhite,
                          ),
                          splineType: SplineType.monotonic,
                          emptyPointSettings: EmptyPointSettings(
                              mode: EmptyPointMode.zero,
                              color: AppTheme.hexBlack,
                              borderColor: AppTheme.hexWhite,
                              borderWidth: 2),
                          isVisible: true,
                          isVisibleInLegend: true,
                          legendIconType: LegendIconType.circle,
                        ),
                      ],
                    ),

Pls check out the small Screen Recording of the Issue.

<img width="310" alt="Screenshot 2020-09-23 at 1 51 22 PM" src="https://user-images.githubusercontent.com/10286865/93986445-fcbd9180-fda3-11ea-9fd6-4472214cb613.png">
<img width="310" alt="Screenshot 2020-09-23 at 1 51 32 PM" src="https://user-images.githubusercontent.com/10286865/93986451-fe875500-fda3-11ea-9f83-31f184382f73.png">

[SfCartesianChart.zip](https://github.com/syncfusion/flutter-examples/files/5266625/SfCartesianChart.zip)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @devrajraut,

Greetings from Syncfusion. We have analyzed on your scenario and we tried to replicate the reported issue by creating a simple sample in which we have created two pages one for the chart and another as main/master page and by tapping on the main page container, the application routes to the chart page according to your scenario and unfortunately, we are not able to replicate the reported issue at our end. So, we kindly request you to revert us with the below details so that it will be helpful in providing the solutions sooner.
- Share us with a simple replication sample or with the whole project of your as we are not exactly sure of the widget tree you have used in your project.

- Or, if possible, try to replicate the reported issue in the below attached test sample and revert us.

Test sample: 
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5275929/sample.zip)



Regards,
Sriram Kiran
