### ISSUE TITLE
[BUG] Legend class require width and height as String

### ISSUE THREAD

**Issue by gumbarros** [syncfusion/flutter-examples#214]

**Comment by SriramKiranSenthilkumar** [comment]
Hi @gumbarros,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some information regarding the **`height`** and **`width`** properties of the Legend available in the chart. These two properties can be set with string values suffixed with a percentage `%` symbol and it cannot be set with integer or double values. These properties take the percentage from the overall chart height and width. Please refer the code snippet below for reference.
```
Widget build(BuildContext context) {
   return Container(
       child: SfCartesianChart(
           legend: Legend(
              isVisible: true,
              height: '30%',
              width: '40%'
           )
       )
   );
}
```

For further reference **`height`** and **`width`** properties, please refer the API reference links below.
Legend's height: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/height.html
Legend's Width: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/width.html

Please get in touch with us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by gumbarros** [comment]
Thanks for the return.
To prevent a issue like this or error in the code, I suggest the creating of a Enum or Class to represent a percentage, that would be nice.
Cheers :)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @gumbarros ,

Thanks for your suggestion. Currently, we cannot change this behaviour as this would be a breaking change. However, we will consider your suggestion in future cases.

Regards,
Sriram Kiran
