### ISSUE TITLE
EventCalendar schedule view-add dots indicating events on each day

### ISSUE THREAD

**Issue by giaur500** [syncfusion/flutter-examples#217]
Schedule view is missing color dots to indicate there is a event planned that day when month view is expanded. That should look similar as agenda view, which includes color dots under day number. 

I think it's good idea to add dots markers  in schedule view when selecting day of month when month view is expanded expanded. Google Calendar displays them too.

**Comment by Indumathi1195R** [comment]
Hi @giaur500 ,

Based on the provided information, we are unable to understand your requirement clearly with [scheduleView](https://help.syncfusion.com/flutter/calendar/schedule-view). But we suspect your requirement is to show the appointment indicator in the [picker ](https://help.syncfusion.com/flutter/calendar/date-navigations#show-date-picker)dates of the calendar header.

If possible, can you please share your requirement clearly with pictorial representation? It will be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by giaur500** [comment]
Yes, it seems you understand correctly. I mean indicators on days. Pleae look at this, indicators are present on month agenda view:
![Screenshot_20201007-161940](https://user-images.githubusercontent.com/26817206/95343825-408ebb80-08b9-11eb-837e-d97fc5a27b6e.jpg)

However, they are missing on schedule view when month is expanded:

![Screenshot_20201007-161957](https://user-images.githubusercontent.com/26817206/95343768-31a80900-08b9-11eb-8b10-ac4bbd847d88.jpg)

Indicators should be present on days with events planned. Do you think you can add them?

**Comment by Indumathi1195R** [comment]
Hi @giaur500,

We have already considered and logged the feature request for the “**Custom builder support for month cells of the date picker**”. We will implement this feature in our upcoming 2020 Volume 4 release and based on this we will integrate the same in picker of the calendar header with appointment indicator and let you know once the release is rolled out. We appreciate your patience until then.

Now, you can track the current status of this feature request by using the following feedback link.

**Feedback link:**
https://www.syncfusion.com/feedback/18537/providing-a-custom-builder-support-for-month-cells-of-the-flutter-date-range

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @giaur500,

We are glad to announce that our Essential Studio 2020 Volume 4 release v18.4.30-beta is rolled with the mentioned feature “**Providing a custom builder support for cells of the Flutter Date range picker (SfDateRangePicker)**”. Kindly update to the latest version for this feature. Please find the latest version from the following pub link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_datepicker/versions

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/builders

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v18.4.0.30?type=all#date-range-picker

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,           
Indumathi R
