### ISSUE TITLE
Bar Series Tooltip Format Y Value

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#22]
### Description:

For bar series data, for some reason the tooltip does not honor `point.y`. For example, the following code:

```dart
tooltipBehavior: TooltipBehavior(
  enable: true,
  header: '',
  format: "point.x: point.y",
)
``` 

The value of `point.y` is not parsed and updated with true value - instead the return is an empty string.

### Issue Resolution: 

I noticed in the source code that that is completed through a search and replace. Just need to update this to get the actual value so it can be used in the tooltip label.

**Comment by JayavigneshwaranG** [comment]
Hi @walsha2 ,

We have analyzed this, but we could not replicate this at our end. Now we have made some general improvements and bug fixes and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). The point.y in tooltip format is replaced with appropriate value properly.

If you still face the same issue in this version, please revert back with your scenario. We will check and provide the exact solution ASAP.
We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran
