### ISSUE TITLE
How can I reproduce Range-selector Zooming example?

### ISSUE THREAD

**Issue by gireeshkbogu** [syncfusion/flutter-examples#220]
Hi, I am trying to run Range-selector, using the example from [here](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/sliders/range_selector/range_selector_with_zooming.dart). I see there are two packages imported locally, and probably because of this I am running into errors. How can I reproduce the Range-selector zoom example without having to import any local packages?

```
///Local import
import '../../../model/sample_view.dart';
import '../../../widgets/checkbox.dart';
```

thanks

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Gireeshkbogu,

Greetings from Syncfusion.

Those items were used for the purpose of our sample browser. For your application, you will only need the following packages in pubspec.yaml and import the following libraries.

**Packages required:** 
syncfusion_flutter_sliders: ^18.3.38-beta
syncfusion_flutter_charts: ^18.3.38

**Libraries required:**
import 'package:syncfusion_flutter_charts/charts.dart' hide LabelPlacement;
import 'package:syncfusion_flutter_core/core.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';

For zooming, you can create the instance of RangeController and set the same instance to both chart and range selector. Please find the below code snippet. 

**Code snippet:**

`class RangeSelectorZoomingPage extends StatefulWidget {
  @override
  _RangeSelectorZoomingPageState createState() =>
      _RangeSelectorZoomingPageState();
}

class _RangeSelectorZoomingPageState extends State<RangeSelectorZoomingPage>
    with SingleTickerProviderStateMixin {

  RangeController rangeController;

  @override
  void initState() {
    super.initState();
    rangeController = RangeController(
      start: DateTime.fromMillisecondsSinceEpoch(1498608000000),
      end: DateTime.fromMillisecondsSinceEpoch(1508112000000),
    );
  }

  @override 
  Widget build(BuildContext context) {
    return SfRangeSelector(
        controller: rangeController,
        ...
        ...
        child: SfCartesianChart(
           primaryXAxis: NumericAxis(
                rangeController: rangeController),
           primaryYAxis: NumericAxis(isVisible: true),
           ...
           ...
           ...
     ));
  }
}
`
We have attached the complete dart file here. 
**Dart file:** https://www.syncfusion.com/downloads/support/directtrac/297003/ze/range_selector_page1746619194.zip 

Also, please check the below UG link for more details.
**UG link:** https://help.syncfusion.com/flutter/range-selector/range-controller#zooming-with-sfchart  

Regards,
Lakshmi R.
