### ISSUE TITLE
samples project does not compile

### ISSUE THREAD

**Issue by SerggioC** [syncfusion/flutter-examples#222]
There are too many undefined and wrong imports. The project wont compile this way.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @SerggioC ,

Thanks for contacting Syncfusion Support. We have analyzed on your scenario and we have now resolved the imports related issue in the sample source and merged the changes. So, we kindly request you to take a pull from the latest master of the [flutter example repo](https://github.com/syncfusion/flutter-examples) to overcome the import-related compilation issues.

Regards,
Sriram Kiran
