### ISSUE TITLE
Bar Series Label Position When Transposed

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#23]
### Description:

Something happened from v3 to v4 that really messed up the data label positioning when the bar series is transposed - relevant snippets below:

```dart
SfCartesianChart(
    ...
    isTransposed: true,
    ...
    series: <BarSeries<ValueData, String>>[
    ...
      dataLabelSettings: DataLabelSettings(
        isVisible: true,
        position: CartesianLabelPosition.outer,
        labelPosition: LabelPosition.outside,
        alignment: ChartAlignment.center,
        textStyle: ChartTextStyle(
          fontSize: 8.5,
          fontWeight: FontWeight.bold,
        ),
          ),
    ...
    ],
)
```

The following is for the same exact code, just updating from v3 to v4 of package.

--------------------

Here is the output from v3:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64924706-31176e80-d79c-11e9-8fd5-c963ac463228.jpeg" width="400">
</p>

Here is the output from v4:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64924848-aafc2780-d79d-11e9-9cdb-820564d38442.jpeg" width="400">
</p>

### Issue Resolution: 

Fix data labels and add more robust testing/checks for when bar series enables `isTransposed: true`

**Comment by JayavigneshwaranG** [comment]
Hi @walsha2 ,

Sorry for the inconvenience. 
We are able to reproduce the reported issue at our end and we have fixed this now. Published the fix to pub. So please use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5).
Now the data labels are positioned properly when isTransposed is specified.

We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by walsha2** [comment]
@JayavigneshwaranG confirmed - this is now fixed with the latest release. Thanks!
