### ISSUE TITLE
[SfCircularChart] Is there a way to clear the selection from the selectionBehavior when I tap off the graph?

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-examples#234]
Hi!
### Is there a way to clear the selection from the selectionBehavior when I tap off the graph?

My idea was whenever I selected a portion of the graph the tooltip and the selected portion would appear, and when I touched outside the graph, I would clear the selection and disappear the tooltip.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LuisCampos97,

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we have achieved your requirements by using a simple workaround with help of the **`onPointTapped`** and **`onChartTouchInteractionUp`** callback events available in the `SfCircularchart`. In the sample, we have used the **`onPointTapped`** and **`onChartTouchInteractionUp`** events to check whether the user touches outside the chart or on the chart data point and based on that, we have deselected the selected point and also hiding the active tooltip of that point using the public methods of **`SelectionBehavior`** and **`TooltipBehavior`** available in the chart. We have also attached the workaround sample below for your reference. 

sample: [gh234_sample.zip](https://github.com/syncfusion/flutter-examples/files/5430654/gh234_sample.zip)

Please check with the above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by LuisCampos97** [comment]
Its works fine!.
Thanks for all Siriam, you are the greatest.

**Comment by LuisCampos97** [comment]
Hello again, and sorry for the inconvenience.
But with this new update on syncfusion_flutter_charts, your implementation will stop working. The selection does not disappear when you tap outside the graph, only the tooltip disappears.

**Can you please review through the sample you created above with the new update?**

Thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LuisCampos97,

We have analyzed your query and we are able to replicate the reported issue at our end. We will consider this as a bug and we will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by LuisCampos97** [comment]
Hi @SriramKiranSenthilkumar,
When will the fix for this problem come out?

Thank you!

**Comment by LuisCampos97** [comment]
Hi @SriramKiranSenthilkumar,
With this new update, most of the problems of this issue have been solved. 

But with that sample you made, when you click the second time on the same portion, it clears the selection and shouldn't be. 

Can you help me, please.
Thank you!

**Comment by dharanidharandharmasivam** [comment]
Hi @LuisCampos97 ,

Thanks for your revert. And we have analyzed on clearing selection when selecting the same portion on the second attempt. As of now, we don’t have support for not to deselect when selecting on the same portion, by default when the selected portion is tapped on the second attempt, it will get deselected. So, we have considered your request as a feature request and logged for the same. This feature will be available in any of our upcoming releases yet to come and you can track the status of the feature from below feedback portal.

https://www.syncfusion.com/feedback/19720 
 
Thanks,
Dharani.

**Comment by LuisCampos97** [comment]
Hi!
I'm using the version of 'syncfusion_flutter_charts' and this [sample](https://github.com/syncfusion/flutter-examples/issues/234#issuecomment-715443376) implementation stop working.

Tell me this error when I touch an area outside the graph: 

═══════ Exception caught by gesture library ═══════════════════════════════════
**Provided point index is not in the visible range. Provide point index which is in the visible range.**
'package:syncfusion_flutter_charts/src/common/user_interaction/selection_behavior.dart':
Failed assertion: line 249 pos 9: 'seriesRenderer._chartState is SfCartesianChartState &&
            _getVisibleDataPointIndex(pointIndex, seriesRenderer) != null'

Can you help me please?

Thank you.
Luís.
