### ISSUE TITLE
how can i get this tooltips

### ISSUE THREAD

**Issue by mzfff** [syncfusion/flutter-examples#236]
![image](https://user-images.githubusercontent.com/51697986/98649068-17f35900-2372-11eb-8783-900819096966.png)

**Comment by Arunsanthoshh** [comment]
Hi @mzfff,

Greetings from Syncfusion. 
 
Yes, we can get the tooltip as the provided image by using the trackball customization. You can initialize the **trackballBehavior** property under **SfCartesianChart** class, which allows you to customize the trackball and its tooltip appearance.  Using the **tooltipDisplayMode** property, we can change the tooltip display mode with multiple series, in your case we can use **groupAllpoints**. We have provided a simple sample and code snippet below, which meets your scenario and also find the UG link below to under more about trackball behavior.

**Code snippet -** 

`trackballBehavior: TrackballBehavior(
  enable: true,
  lineColor: Colors.white,
  tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
  shouldAlwaysShow: true,
  activationMode: ActivationMode.singleTap,
  tooltipSettings: InteractiveTooltip(
    enable: true,
    color: Colors.black,
    format: 'point.x: point.y \n',
  ),
),
`

**UG link -** https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html 
 
**Sample --** https://www.syncfusion.com/downloads/support/directtrac/general/ze/236-1336290291 
 
Please revert us back if you have any other concerns.
 
Thanks,
Arun.

**Comment by baliejun** [comment]
Hi, Arun.

Thanks for your replay, we have  initialized  the **trackballBehavior** property under **SfCartesianChart** class, which displays like this.
![image](https://user-images.githubusercontent.com/53867124/98902689-2a47d100-24f1-11eb-80ab-0871ba3025e7.png)

There are some other questions about it.
1.When we click it out the scope of the AreaLine , then the tooltips cannot display,which like this.
![image](https://user-images.githubusercontent.com/53867124/98903129-ec977800-24f1-11eb-8359-0152b685d165.png)

2.The format is "string" type of tooltipSettings,  how can we draw round frames before the text like this.
![image](https://user-images.githubusercontent.com/53867124/98903466-a0006c80-24f2-11eb-8303-82da3b5ad20e.png)

3.Can the title of primaryYAxis alignment like this?
![image](https://user-images.githubusercontent.com/53867124/98903644-fe2d4f80-24f2-11eb-8ed6-173566e08a0e.png)


Thanks,
Best Regards.

**Comment by dharanidharandharmasivam** [comment]
Hi @baliejun ,

Kindly find the response for your queries below.

**Query #1: When we click it out the scope of the AreaLine , then the tooltips cannot display,which like this.**
We would like to let to know that do you have customized the trackball in the onTrackballPositionChanging event. Can you please share the code snippet that you have used to render the chart widget as well share the data source? Else kindly try to replicate the reported scenario with the attached sample.

**Query #2: The format is "string" type of tooltipSettings, how can we draw round frames before the text like this.**
As of now, we don’t have marker support for the trackball tooltip. So, we have logged a feature request for the requirement and this will be available in any of our upcoming releases yet to come. You can track the status of the feature from below feedback portal.

https://www.syncfusion.com/feedback/19719

**Query #3: Can the title of primaryYAxis alignment like this?**
No, the primaryYaxis title aligned as shown in the attached screenshot. However, using the chart title, it can be positioned as you expected. But if you position the legend to the top of the chart, then chart title will be positioned above the legend. Find the code snippet below to accomplish this.

```
SfCartesianChart(
            title: ChartTitle(
              text: 'Chart Title',
              //Aligned the chart title
              alignment: ChartAlignment.near
            ),
)`
```

Screenshot:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/19346074/99074567-fb5b5900-25dd-11eb-9ec5-85dc2b7649e4.png)


Sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/5536848/sample.zip)

Thanks,
Dharani.
