### ISSUE TITLE
[SfCartesianChart] Change offset of bar selection

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-examples#237]
Hi!
At this moment when I click on the bar through the onSelectionChanged method the label changes to white. 

But I have a problem is that when I have the bar with y = 0 (as seen in the following image), I have no way to click on the bar to change the color of the label to white because the bar does not exist.
![imagem](https://user-images.githubusercontent.com/33434500/99385039-4ae4a200-28c8-11eb-9dc3-f145e489bfd1.png)

Is there any way to change the offset of the selection to the one that is selected in red, in case there is no bar in the selection?

Thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @LuisCampos97,

Greetings from Syncfusion. We have analyzed your scenario at our end we have created a simple workaround sample in which we have provided support for selecting the data points in the chart when tapped on its axis label with the help of the **`onAxisLabelTapped`** callback event and **`selectDataPoints`** public method of **`SelectionBehavior`**. So, using this workaround, you will be able to select the data whose y-value is zero by tapping on its axis label as there will be no bar available for selection. We have also attached the workaround sample below for further reference.
Sample: [sample.zip](https://github.com/syncfusion/flutter-examples/files/5563955/workaround_sample.zip) 

Please check with the above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by LuisCampos97** [comment]
It worked! 
Thank you very much @SriramKiranSenthilkumar .
