### ISSUE TITLE
Line Series Trackball Tooltip Format Series Name

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#24]
### Description:

In the following example for a line series chart (where x-axis is `DateTimeAxis` and y-axis is `NumericAxis`) the following does not work as expected:

```dart
tooltipSettings: InteractiveTooltip(
	textStyle: ChartTextStyle(color: Colors.black, fontSize: 11),
	format: 'series.name: point.y',
	borderWidth: 1,
	borderColor: Colors.black,
	color: Color.fromRGBO(255, 255, 255, 0.75),
)
```

The tooltip label correctly parses and replaces `point.y` but **does not** do the same for `series.name` it just keeps it as the string: `'series.name'` in the tool tip and does not update.

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64925177-b3eef800-d7a1-11e9-9289-de5e0bd41be4.jpeg" width="400" align="center">
</p>

### Issue Resolution: 

Digging through the code, the following seems to be the culprit - `series.name` is completely missing:

```
lib/src/chart/user_interaction/trackball_painter.dart
```

```dart
labelValue = chart
  .trackballBehavior.tooltipSettings.format
  .replaceAll('point.x', (x ?? xValue).toString())
  .replaceAll('point.y',
      _getLabelValue(yValue, cartesianSeries._yAxis))
  .replaceAll('{', '')
  .replaceAll('}', '');
```

Changing to this to the following (adding `series.name` replacement), solved the issue:

```dart
labelValue = chart
  .trackballBehavior.tooltipSettings.format
  .replaceAll('point.x', (x ?? xValue).toString())
  .replaceAll('point.y',
      _getLabelValue(yValue, cartesianSeries._yAxis))
  .replaceAll('{', '')
  .replaceAll('}', '')
  .replaceAll('series.name', cartesianSeries.name);
```

**Comment by JayavigneshwaranG** [comment]
Hi @walsha2 ,

Sorry for the inconvenience. 
We are able to reproduce the reported issue at our end and we have fixed this now. Published the fix to pub. So please use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5).
Now series.name will be replaced with the appropriate value in the tooltip.

We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by walsha2** [comment]
@JayavigneshwaranG confirmed - this is now fixed with the latest release. Thanks!
