### ISSUE TITLE
Last sunday of march in month view of calendar repeats the saturday date

### ISSUE THREAD

**Issue by fourman-alex** [syncfusion/flutter-examples#244]
See attached screenshot from the web demo. You can see March 27th repeats twice. 
This happens for every march of every year in this view.
![image](https://user-images.githubusercontent.com/5362998/102510369-3692f100-4090-11eb-9985-dbd362db2ae8.png)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Calendar repeats the date in March month of SfCalendar**” in Sample browser sample. We are unable to reproduce the issue from our end and it is working fine as expected. We have attached the tested image for the same. Please find the image from the following link.

**Link:**
[Image.zip](https://github.com/syncfusion/flutter-widgets/files/5715082/Image.zip)

If possible, can you please share the below details to reproduce the issue from our end? It would be helpful for us to analyze and provide you a solution at the earliest.

•	Time zone details
•	Issue reproducing scenario or video

Regards,
Indumathi R
