### ISSUE TITLE
How to shrinkWrap the date picker?

### ISSUE THREAD

**Issue by ajaygautam** [syncfusion/flutter-examples#247]
Hello

I am using `SfDateRangePicker` and want to "shrinkWrap" it... Similar to `ListView. shrinkWrap`.

Problem: See attached images. The `SfDateRangePicker` is in a complex widget hierarchy... and is placed in a ScrollView / IntrinsicHeight Column which causes the picker to get infinite height. This causes rendering errors:
```
flutter: 2020-12-25 15:22:55.591002: Utils WARNING: uploadToSentry: debugMode: true, caught message: Caught from Flutter onError, error: LayoutBuilder does not support returning intrinsic dimensions.
Calculating the intrinsic dimensions would require running the layout callback speculatively, which might mutate the live render object tree. - #0      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:390:9)
#1      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics (package:flutter/src/widgets/layout_builder.dart:397:6)
#2      _RenderLayoutBuilder.computeMaxIntrinsicHeight (package:flutter/src/widgets/layout_builder.dart:344:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1373:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:301:23)
#5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1371:<…>
flutter: 2020-12-25 15:22:55.594674: Utils WARNING: uploadToSentry: debugMode: true, caught message: Caught from Flutter onError, error: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1920 pos 12: 'hasSize': RenderBox was not laid out: RenderIntrinsicHeight#689f6 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE - #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1920:12)
#3      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:282:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#5      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:558:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/re<…>
```

I tried to wrap it in a SizedBox:
```dart
SizedBox(
                width: screenSize.width * 0.9,
                height: screenSize.height * 0.75,
                child: SfDateRangePicker(.......)
)
```
but this causes the stretching of the picker (see attached image below).

If I could specify a shrinkWrap type behavior... that would be great.

Thanks

![widget_tree](https://user-images.githubusercontent.com/60637/103141701-1c779500-46c6-11eb-8692-63a1d7249b21.jpg)

![datePicker](https://user-images.githubusercontent.com/60637/103141706-213c4900-46c6-11eb-887a-e7a029ea7962.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked your requirement “**Providing shrinkwrap option in the date range picker control similar to Listview**”. SfDateRangePicker control is implemented in the scroll panel, so shrinkWrap is not possible for date range picker. Kindly use the required widget with the required size for rendering the date range picker. 

We have prepared a simple sample for placing the date range picker in the card widget and attached the image for the same. Please find the sample and image from the following link,

**Sample and image link:**
https://www.syncfusion.com/downloads/support/directtrac/308637/ze/selection_radius385104920.zip

Also please find the example code snippets for the same.

**Code snippets:**

```
body: Card(margin: const EdgeInsets.fromLTRB(50, 150, 50, 150),
    child: SfDateRangePicker()),
```

```
body: Container(height: 300, width: 400,
    child: SfDateRangePicker()),
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
