### ISSUE TITLE
Bar Series with Negative Values - Bar Segment Painter Issue

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#25]
### Description:

Something happened from v3 to v4 that really messed up how a bar series deals with negative values. The painter completely fails to draw bar charts in the opposite direct - this was working just fine in v3.

The following is for the **same exact code**, just updating from v3 to v4 of package.

--------------------

Here is the output from v3:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64925280-f107ba00-d7a2-11e9-92ec-3b717f3bd3e2.jpeg" width="400">
</p>

Here is the output from v4:

NOTE: The data labels are messed up because of #23 in v4 - this issue is just focused on the bar segment painter issue as seen below.

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64925288-24e2df80-d7a3-11e9-9149-59f963005e67.jpeg" width="400">
</p>

### Issue Resolution: 

I tried to dig around, but could not find anything to identify what is causing the issue. @dharanidharandharmasivam @JayavigneshwaranG - please let me know if you have any thoughts on this.

**Comment by JayavigneshwaranG** [comment]
Hi @walsha2 ,

We have analyzed this, but we could not replicate this at our end. Now we have made some general improvements and bug fixes and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). The bar series with negative data points are rendering fine if it is transposed.

If you still face the same issue in this version, please revert back with your scenario. We will check and provide the exact solution ASAP.
We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by walsha2** [comment]
@JayavigneshwaranG confirmed - this is now fixed with the latest release. Thanks!
