### ISSUE TITLE
onTap of SfCalendar doesn't return any click event when clicked over CalendarView.Schedule events / appointments / meetings list

### ISSUE THREAD

**Issue by nakibHoxro** [syncfusion/flutter-examples#253]
![InkedScreenshot_1609228144_LI](https://user-images.githubusercontent.com/73923594/103268149-39210f00-49dd-11eb-8dd4-9108adfcee8a.jpg)

# I'm using this code
```
SfCalendar(
  onTap: (CalendarTapDetails details) {
  
    if (details.targetElement == CalendarElement.appointment) {
      print("pressed");
    }
    DateTime date = details.date;
    print(date);
    dynamic appointments = details.appointments;
    print(appointments);
    CalendarElement view = details.targetElement;
    print(view);
  },

  view: CalendarView.schedule,
  scheduleViewSettings: ScheduleViewSettings(
    appointmentItemHeight: 70,
  ),
  dataSource: MeetingDataSource(_getDataSource()),
  scheduleViewMonthHeaderBuilder: scheduleViewHeaderBuilder,
  //appointmentBuilder: appointmentShowDetailsBuilder,
  
),
```

this code prints some details when I click elsewhere. But it doesn't show anything no matter how much I click on the Event. (Green area)
# I also tried using 
`appointmentBuilder: appointmentShowDetailsBuilder,`

Here is the code of my `appointmentShowDetailsBuilder`

```
Widget appointmentShowDetailsBuilder(BuildContext buildContext,
    CalendarAppointmentDetails calendarAppointmentDetails) {
  final Appointment appointment = calendarAppointmentDetails.appointments.first;
  return GestureDetector(
    onTap: () {
      print("Pressed");
      //navigatorKey.currentState.pushNamed('/home');
    },
    child: Container(
      color: appointment.background,
      width: calendarAppointmentDetails.bounds.width,
      height: calendarAppointmentDetails.bounds.height,
      child: Column(
        children: [
          Text(appointment.eventName),
          RaisedButton(
            onPressed: () {
              print("Nakib");
            },
            child: Text("Nakib"),
          )
        ],
      ),
    ),
  );
}
```

In `appointmentShowDetailsBuilder`, the `RaisedButton` or the `GestureDetector` none of them works.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

We have already found and fixed the mentioned issue “**onTap callback not working in schedule view of the calendar**”. We will include the issue fix in our upcoming Weekly Nuget release package which is expected to be rolled out by December 30, 2020 and let you know once the release rolled out. We appreciate your patience until then. 
 
Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the mentioned issue fix for “**onTap callback not working in schedule view of the calendar**” in our latest Weekly NuGet package **version 18.4.32**. Kindly update the Flutter calendar package to this version for resolving this mentioned issue. Please find the latest version from the following link.

**Link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by nakibHoxro** [comment]
@Indumathi1195R  Thank you for resolving the issue.
Now I want to know, how to access the event / appointment details of specific event inside `onTap`?
```
onTap: (CalendarTapDetails details) {
    if (details.targetElement == CalendarElement.appointment) {
       // I want to access the appointment details like eventName, from, to, background, isAllDay etc. if I tap over an event
    }    
},
```

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: how to access the event / appointment details of specific event inside onTap?**

We have a KB document for access the appointment details inside **onTap** callback using **CalendarElement** and show the details in alert dialog window.  Please find the KB’s from the following links.

**KB links:**
https://www.syncfusion.com/kb/11529/how-to-add-a-custom-appointments-or-objects-in-the-flutter-event-calendar-sfcalendar
https://www.syncfusion.com/kb/10999/how-to-get-appointment-details-from-the-ontap-event-of-the-flutter-event-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by nakibHoxro** [comment]
Thank you @Indumathi1195R for your support. 
The urls you provided were really helpful.

I'm closing this issue for now. 
Thank you for your time and consideration. 
I hope to have further assistance in future from Syncfusion team.

**Comment by Ergi16** [comment]
I want to click events inside cell
![Screenshot_1621013412](https://user-images.githubusercontent.com/56676781/118330134-a0aca680-b507-11eb-967d-58bae0a88479.png)

**Comment by Edwinstr97** [comment]
<img width="1440" alt="Screenshot 2021-12-28 at 10 55 03 AM" src="https://user-images.githubusercontent.com/56911453/147531188-aa00cba8-f885-495f-9107-225f2090e546.png">
Hi,

Am not able to get the list of attendees in an event when I use the onTap callback .I first tried assigning the details to Event I was able to get the attendees but later for other events on my calendar it said that Appointment cannot be assigned to Event ,But on tap of appointments does not give me the list of atteendes or event ID it just gives me the reccurence rule , start , end date and other parameters.My use case is that when I tap on an event on my calendar I should be able to retrieve the attendees of a particular event


Thank you,
Edwin Raj
