### ISSUE TITLE
Variable "resources" is null after initializing DataSource

### ISSUE THREAD

**Issue by BenPoell** [syncfusion/flutter-examples#254]
When creating a DataSource with resources according the documentation, it somehow appears that the variable "resources" is reset to null after it is set in the constructor of the DataSource. You always have to set it manually after you initialized the DataSource.
```dart
class _AppointmentDataSource extends CalendarDataSource {
  _AppointmentDataSource(
      List<Appointment> source, List<CalendarResource> resourceColl) {
    appointments = source;
    resources = resourceColl;
  }
}
```

![image](https://user-images.githubusercontent.com/24900930/103409371-cd6aad80-4b66-11eb-9213-e3a291ddeeab.png)

I found some code snipped with extending **CalendarDataSourceResource** in `calendar_datasource.dart` but it doesn't allow me to do so.
```dart
  /// The collection of resource to be displayed in the timeline views of
  /// [SfCalendar].
  ///
  /// Defaults to `null`.
  ///
  /// ```dart
  ///
  /// class AppointmentDataSource extends CalendarDataSourceResource {
  ///    AppointmentDataSource(List<Appointment> appointments,
  ///                                 List<CalendarResource> resources) {
  ///    resources = resources;
  ///    appointments = appointments;
  ///  }
  /// }
  ///
  /// ```
  List<CalendarResource> resources;
```

Package version: syncfusion_flutter_calendar: ^18.4.31

flutter doctor output:
```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (6 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Ben\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Ben\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 87.0.664.60

• No issues found!
```

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**resources null after initializing DataSource in Flutter event calendar**” and it is working fine as expected from our end. resources denote the property name in CalendarDataSource class. In the shared code snippet, you have used the same property name for the parameter of the constructor. So that corresponding value was not set to resources property and the value was null, also calendar was rendering without resources. Kindly use different names in the parameter of the constructor. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/309186/ze/navigation_arrow-652392257.zip

Also please find the code snippet for the same.

```
class _AppointmentDataSource extends CalendarDataSource {
  _AppointmentDataSource(
      List<Appointment> source, List<CalendarResource> **resourceCollection**) {
    appointments = source;
    resources = **resourceCollection**;
  }
}

```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by BenPoell** [comment]
> [...] Kindly use different names in the parameter of the constructor. [...]

That's it, thank you! Sometimes solutions are that simple...

Thanks!
Benjamin
