### ISSUE TITLE
[SfCircularChart] Clear the selection from the selectionBehavior when I tap off the graph

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-examples#255]
Hi!
I'm using the version of 'syncfusion_flutter_charts' and this [sample](https://github.com/syncfusion/flutter-examples/issues/234#issuecomment-715443376) implementation stop working.

Tell me this error when I touch an area outside the graph: 

═══════ Exception caught by gesture library ═══════════════════════════════════
**Provided point index is not in the visible range. Provide point index which is in the visible range.**
'package:syncfusion_flutter_charts/src/common/user_interaction/selection_behavior.dart':
Failed assertion: line 249 pos 9: 'seriesRenderer._chartState is SfCartesianChartState &&
            _getVisibleDataPointIndex(pointIndex, seriesRenderer) != null'

According to my tests, this implementation stopped working in version 18.4.33, because in version 18.4.31 it worked.

Can you help me please?

Thank you.
Luís.

**Comment by Dharanipalani** [comment]
Hi @LuisCampos97 ,   

We regret the inconvenience. We can replicate your scenario at our end and we consider this as a bug and fix will be included in the upcoming patch release which is expected to be rolled out on January 12th, 2021. We appreciate your patience until then.   

Thanks,   
Dharanitharan. P

**Comment by LuisCampos97** [comment]
Thank you very much!

**Comment by dharanidharandharmasivam** [comment]
Hi @LuisCampos97 ,

Most welcome, we will update you once the weekly patch release has been rolled out and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by Dharanipalani** [comment]
Hi @LuisCampos97,

We are glad to inform you that reported issues have been resolved in our latest version **v18.4.34**.  Now, this  [https://github.com/syncfusion/flutter-examples/issues/234#issuecomment-715443376](Sample) will work correctly. So, kindly upgrade our charts to the latest version from the following link.

Latest version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.34](url)

Please revert us if you need any further assistance.


Thanks,
Dharanitharan. P

**Comment by LuisCampos97** [comment]
Thank you very much, it worked!
