### ISSUE TITLE
[Calendar] Finding the available time slots - resource view calendar 

### ISSUE THREAD

**Issue by A7medMaher** [syncfusion/flutter-examples#256]
Hi all.
If there are appointments at specific time slots, how to find the remaining free and not busy timeslots and returning them in a list?

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**## Finding the available time slots - resource view calendar.**

As of now, there is no direct support for getting free timeslots in the resource view. Timeslot may be in hours or minutes. In the meantime, we are preparing the sample. We will update you on or before January 12, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are preparing the sample. We will prepare and update you on the further details on or before January 15, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for your patience.

**## Finding the available time slots - resource view calendar.** 

We have prepared a simple sample for finding the available timeslots in the calendar. We have prepared the sample by adding the getAvailableTimeSlots method in the onViewChanged callback. Based on the resource, visible date, and appointment startTime (hour) and endTime(hour) we have finding the free slots.

**Code snippet:** getAvailableTimeSlots method in onViewChanged callback and pass the resource with a visible date to get the free timeslot for resource.
```
void viewChanged(ViewChangedDetails viewChangedDetails) {
  for(int j=0;j<viewChangedDetails.visibleDates.length;j++)
    {
      DateTime visibleDate = viewChangedDetails.visibleDates[j];
      for (int i = 0; i < _employeeCollection.length; i++) {
        CalendarResource _resourceColl1 = _employeeCollection[i];
        var availableTimeSlot= getAvailableTimeSlots(_resourceColl1, visibleDate);
      }
    }
}
```

**Code snippet:** If the appointment startTime(hour) and endTime(hour) not equals to the visible date hour adding those timeslots to the freeTimeSlots.
```
List<DateTime> getAvailableTimeSlots(
    CalendarResource resource, DateTime visibleDate) {
  var date = visibleDate;
  List<DateTime> freeTimeSlots = <DateTime>[];
  var numberOfTimeSlots = 24;

  for (int i = 0; i < numberOfTimeSlots; i++) {
    var dateTime = date.add(Duration(hours: i));
    if (!(hasAppointmentForResource(resource, dateTime)))
      freeTimeSlots.add(dateTime);
  }
  return freeTimeSlots;
}
```
**Code snippet:** Checks whether the appointment has resource and compare startTime and endTime with visible date.
```
bool hasAppointmentForResource(CalendarResource resource, DateTime date) {
  var count = 0;
  for (int j = 0; j < _events.appointments.length; j++) {
    Appointment app = _events.appointments[j];
    if (hasResource(app, resource)) {
        if(app.startTime.hour==date.hour ||app.endTime.hour==date.hour)
        count++;
    }
  }
  return count > 0 ? true : false;
}
```
**Code snippet:**  Checks whether resource has appointment.
```
bool hasResource(Appointment appointment, CalendarResource resource) {
  var count = 0;
  for (int j = 0; j < appointment.resourceIds.length; j++) {
    var resourceID = appointment.resourceIds[j];
    if (resourceID == resource.id) count++;
  }
  return count > 0 ? true : false;
}
```
We have attached the tested sample for your reference. You can download the same from the following link.

**Link:** https://www.syncfusion.com/downloads/support/directtrac/309919/ze/minimum_appointmentduration-462233031.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by 1rach** [comment]
The link doesn't work even I have a sync fusion account (community license).

How can I access the code example please?
