### ISSUE TITLE
[CALENDAR]  invalid member on null: 'hasClients'

### ISSUE THREAD

**Issue by diezep** [syncfusion/flutter-examples#258]
When i try to instance more than 4 SfCalendar instances in one screen, i get this error:
![image](https://user-images.githubusercontent.com/38699812/104112371-a96c4200-52b3-11eb-9d07-c11117bb402f.png)

I'm using flutter web.

**Comment by Indumathi1195R** [comment]
Hi ,

Based on the provided information, we have checked the mentioned issue “**Calendar shows an error when load more than 4 calendars in one screen**” and it is working fine as expected from our end. We have tested the following scenarios.

**Tested version:** 18.4.33

**Tested device:**
Chrome

**Tested scenarios:**
1.	Tested with the same controller for 4 calendars. 
2.	Tested with a different controller. for 4 calendars. 
3.	Tested with the controller with onTap callback 
4.	Load the calendars with the ListView widget 
5.	Load the calendars with the Column widget.

If possible, can you share the replication procedure to reproduce the mentioned error. It will be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
