### ISSUE TITLE
Line Series Y-Axis Title Alignment Issue

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#26]
### Description:

There is a minor issue introduced with the latest v4 version of the package. It seems that now `AxisTitle` alignment is measured as a function of the entire chart container height (possibly?) as opposed to just the y-axis (like it was before in v3). 

```dart
primaryYAxis: NumericAxis(
  isVisible: true,
  title: AxisTitle(
    alignment: ChartAlignment.center,
    text: "Rate of Return (%)",
  ),
)
```

The following is for the **same exact code**, just updating from v3 to v4 of package - note how `Rate of Return (%)` gets shifted down (no longer centered about the y-axis) in v4. 

--------------------

Here is the output from v3:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64928207-b9f8cf00-d7c9-11e9-83f2-110990771329.jpeg" width="400">
</p>

Here is the output from v4:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/64928206-b9f8cf00-d7c9-11e9-98c0-2a8d2aadc2a3.jpeg" width="400">
</p>

### Issue Resolution: 

I am not sure why anyone would want `AxisTitle` alignment relative to the entire rendered chart container and not just the chart axis. The axis title should measure its alignment relative to the axis height.

**Comment by JayavigneshwaranG** [comment]
Hi @walsha2 ,

We have analyzed this, but we could not replicate this at our end. Now we have made some general improvements and bug fixes and published to pub. So we request you to use the [latest version packages(1.0.0-beta.5).](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5) The Y-axis title text is aligned center to the axis.

If you still face the same issue in this version, please revert back with your scenario. We will check and provide the exact solution ASAP.
We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran

**Comment by walsha2** [comment]
@JayavigneshwaranG confirmed - this is now fixed with the latest release. Thanks!
