### ISSUE TITLE
[CALENDAR] Errors in test setup on beta channel

### ISSUE THREAD

**Issue by jhuckabee** [syncfusion/flutter-examples#260]
When attempting to test an app that contains a calendar widget in the current beta channel (1.25.0-8-2.pre), many errors are raised (see logs below). I do not see these errors when running on the stable channel. Any ideas on how we can test without these errors?

Steps to reproduce:

```
flutter create sf_cal_test
```

Update `lib/main.dart` as follows:

<details>
  <summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: SfCalendar(),
      ),
    );
  }
}
```
</details>

Update `test/widget_test.dart` as follows:

<details>
  <summary>test/widget_test.dart</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:sf_cal_test_stable/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
  });
}
```

</details>

Run `flutter test`

The errors that result can be found in [this gist](https://gist.github.com/jhuckabee/0c5733b8dccf1ce3840bdf23e383caea).

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.40.1)
[✓] Connected device (2 available)

• No issues found!
```
</details>

**Comment by Indumathi1195R** [comment]
Hi ,

Based on the provided information, we have checked the mentioned issue “**Calendar shows error on the latest beta channel in test setup**”. It is a framework level issue in the beta channel, and it is working fine in the stable version. We will try to fix the issue at the source level and update you with further details on or before January 18, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have included the mentioned issue fix for “**Calendar shows an error on the latest beta channel in test setup**” in our latest Weekly Nuget package. Kindly update the Flutter calendar package to the latest **version 18.4.35** for resolving this error. Please find the latest version from the following link.

**Link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

Regards,
Indumathi R
