### ISSUE TITLE
SfDateRangePicker -> HeaderStyle -> TextStyle -> NoSuchMethodError

### ISSUE THREAD

**Issue by Evyl1303** [syncfusion/flutter-examples#262]
The getter 'opacity' was called on null.
Receiver: null
Tried calling: opacity

```
headerStyle: DateRangePickerHeaderStyle(
          textAlign: TextAlign.center,
          textStyle: TextStyle(
            fontWeight: FontWeight.bold
          )
        )
```

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Error occurred when using the header text style in Flutter date range picker**". When using the text style for the date range picker header, kindly use the text style properties along with the color property for resolving this issue. Please find the code snippet for the same.

**Code snippet:**

```
child: SfDateRangePicker(
    view: DateRangePickerView.month,
    headerStyle: DateRangePickerHeaderStyle(
      textAlign: TextAlign.center,
      textStyle: TextStyle(
          fontWeight: FontWeight.bold,
          color: Colors.black),
    )),

```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
