### ISSUE TITLE
SfDateRangePicker - split header

### ISSUE THREAD

**Issue by Evyl1303** [syncfusion/flutter-examples#263]
Is it possible to split the header and show them like in the screenshot? I couldn't find a way

![Screenshot_1610567850](https://user-images.githubusercontent.com/18393918/104504629-07b26100-55e3-11eb-8585-c9cd177e1f51.png)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the attached image, your requirement is “**Showing a date picker in the vertical direction with header split**” and it can be achieved by using the **_navigationDirection_** as vertical and **_enableMultiView_** property as true. Also, we have attached the code snippet for the same. But there is no direct support to split the header and it can be achieved by sample using two pickers inside the Column widget. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:**

[Uploading navigationarrow_picker.zip…]()

**Code snippet for enabling multi picker with vertical direction:**
```
child: SfDateRangePicker(
  enableMultiView: true,
  navigationDirection: DateRangePickerNavigationDirection.vertical,
)),

```
We have a UG document for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/views#vertical-picker

Also, we have a KB document for the same. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12193/how-to-show-two-pickers-vertically-in-the-flutter-date-range-picker-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
