### ISSUE TITLE
_RenderRangeSelector does not meet its constraints.

### ISSUE THREAD

**Issue by chongbo2013** [syncfusion/flutter-examples#266]
Constraints: BoxConstraints(w=882.0, h=30.0)
Size: Size(882.0, 29.0)

If you are not writing your own RenderBox subclass, then this is not your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  _RangeSelectorRenderObjectWidget syncfusion_flutter_sliders/lib/src/range_selector.dart:1445:12
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2224:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2309:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:2001:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:2003:6)
#4      _RenderRangeSelector.performLayout (package:syncfusion_flutter_sliders/src/range_selector.dart:2803:5)

_RenderRangeSelector does not meet its constraints.
The relevant error-causing widget was: 
  _RangeSelectorRenderObjectWidget 
syncfusion_flutter_sliders/lib/src/range_selector.dart:1445:12

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Chongbo,   

Could you please check whether the below code snippet will resolve your issue? 

> 
class RangeSelectorPage extends StatelessWidget {
  SfRangeValues _values = SfRangeValues(30.0, 70.0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Range Selector')),
      body: Container(
        height: 100,
        alignment: Alignment.center,
        child: SfRangeSelector(
          min: 0.0,
          max: 100.0,
          interval: 10,
          initialValues: _values,
          showLabels: true,
          showTicks: true,
          child: Container(
            color: Colors.green,
          ),
        ),
      ),
    );
  }
}
> 

Regards,
Lakshmi R.

**Comment by chongbo2013** [comment]
Ok thank&nbsp;





------------------ Original ------------------

**Comment by chongbo2013** [comment]
`
class CpuMntPage {
  //cpu数据
  List<Perfdata> data = List();
  Widget root;


  double previousEnd,previousStart;
  bool enableDeferredUpdate = true;
  RangeController rangeController = RangeController(
    start: 0.0,
    end: 100.0,
  );

  SfCartesianChart splineChart;
  double chartsMin=0.0, chartsMax=1.0, chartsinterve=1.0;
  ChartSeriesController _yCpuController;

  CpuMntPage() {
    _create();
  }


  void addDataObj(Perfdata info) {
    //添加数据
    data.add(info);
    _refresh();

    if(_yCpuController==null||root==null){
      return;
    }
    _yCpuController.updateDataSource(
      addedDataIndexes: <int>[data.length - 1],
    );

  }
  void addDataObjs(Perfdata info) {
    //添加数据
    data.add(info);
    _refresh();

    if(_yCpuController==null||root==null){
      return;
    }
    _yCpuController.updateDataSource(
      addedDataIndexes: <int>[data.length - 1],
    );

  }
  void clear() {
    //添加数据
    data.clear();
    _refresh();

    if(_yCpuController==null||root==null){
      return;
    }
    _yCpuController.updateDataSource(
      addedDataIndexes: <int>[data.length - 1],
    );

  }

  void _create() {
    _refresh();

     splineChart = SfCartesianChart(
      title: ChartTitle(text: 'CPU Usage', alignment: ChartAlignment.center),
      plotAreaBorderWidth: 0,
      legend: Legend(isVisible: true, position: LegendPosition.right),
      trackballBehavior: TrackballBehavior(
        enable: true,
        markerSettings: TrackballMarkerSettings(
          markerVisibility: true
              ? TrackballVisibilityMode.visible
              : TrackballVisibilityMode.hidden,
          height: 0,
          color: Colors.black,
          width: 0,
          borderWidth: 1,
        ),
        hideDelay: 2.0 * 1000,
        activationMode: ActivationMode.singleTap,
        tooltipAlignment: ChartAlignment.center,
        tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
        tooltipSettings:
            InteractiveTooltip(enable: true),
        shouldAlwaysShow: true,
      ),
      primaryXAxis: NumericAxis(
          minimum: chartsMin,
          maximum: chartsMax,
          rangeController: rangeController,
          majorGridLines: MajorGridLines(width: 0),
          edgeLabelPlacement: EdgeLabelPlacement.shift),
      primaryYAxis: NumericAxis(
        interval: 25,
        axisLine: AxisLine(width: 0),
        majorTickLines: MajorTickLines(size: 0),
        labelFormat: '{value}%',
        labelPosition: ChartDataLabelPosition.outside,
        labelAlignment: LabelAlignment.center,
          plotBands: [
            PlotBand(
                // shouldRenderAboveSeries:true,
                isVisible: true,
                // provided the same y-value to start and end property in order to render the plotline for that y-value.
                start: 20.0,
                end: 20.0,
                borderWidth: 1,
                borderColor: Colors.blueAccent,
                // Label text for the reference plot line
                text: 'Ref CPU 20%',
                textStyle: TextStyle(color: Colors.blue),
                // provided dash array to render the line in dashed format.
                dashArray: <double>[8, 5])
          ]
      ),
      // zoomPanBehavior: _zoomingBehavior,
      series: <LineSeries<Perfdata, num>>[
        LineSeries<Perfdata, num>(
            name: 'Total',
            width: 1,
            dataSource: data,
            // color: const Color.fromRGBO(0, 193, 187, 1),
            animationDuration: 500,
            markerSettings: MarkerSettings(
              isVisible: false,
              width: 2,
              height: 2,
            ),
            xValueMapper: (Perfdata sales, _) => sales.timeSecond,
            yValueMapper: (Perfdata sales, _) => sales.cpuTotalUsage,
            onRendererCreated: (ChartSeriesController controller) {
              _yCpuController = controller;
            }
        ),
        LineSeries<Perfdata, num>(
            name: 'App',
            width: 1,
            dataSource: data,
            // color: const Color.fromRGBO(0, 193, 187, 1),
            animationDuration: 500,
            markerSettings: MarkerSettings(
              isVisible: false,
              width: 2,
              height: 2,
            ),
            xValueMapper: (Perfdata sales, _) => sales.timeSecond,
            yValueMapper: (Perfdata sales, _) => sales.cpuAppUsage,
            onRendererCreated: (ChartSeriesController controller) {
              _yCpuController = controller;
            }
        )
      ],
    );
  }

  void _refresh() {
    chartsMin = 0.0;
    chartsMax = max(data.length>0?data[data.length-1].timeSecond:0,1.0);
    chartsinterve =max( (chartsMax - chartsMin) / 12,1.0);
    if(previousStart==null||previousEnd==null){
      previousStart=0.0;
      previousEnd=1.0;
    }
    //应该比例，控制

    rangeController.start =chartsMax*previousStart;
    rangeController.end = chartsMax*previousEnd;

  }

  Widget getWidget() {

    return  Container(
      child: Column(
        children: <Widget>[
          Container(
              width: double.infinity,
              height: 200,
              child: splineChart),
         Container(child:SfRangeSelectorTheme(
             data: SfRangeSelectorThemeData(
                 activeLabelStyle:
                 TextStyle(fontSize: 10, color: Colors.black),
                 inactiveLabelStyle:
                 TextStyle(fontSize: 10, color: Colors.black),
                 activeTrackColor: Colors.black,
                 inactiveRegionColor: Colors.transparent,
                 thumbColor: Colors.white,
                 thumbStrokeColor:Colors.black,
                 thumbStrokeWidth: 2.0,
                 overlayRadius: 1,
                 overlayColor: Colors.white),
             child:  SfRangeSelector(
               min: chartsMin,
               max: chartsMax,
               interval: chartsinterve,
               enableDeferredUpdate: true,
               deferredUpdateDelay: 2000,
               labelPlacement: LabelPlacement.betweenTicks,
               controller: rangeController,
               showTicks: false,
               showLabels: false,
               dragMode: SliderDragMode.both,
               onChanged: (SfRangeValues values) {
                 previousStart=values.start;
                 previousEnd=values.end;
                 print('------------------');
               },
               child: Container(),
             )),
         )
        ],
      ),
    );
  }

  void dispose() {}

  //清理数据
  void clearData() {
   clear();
  }
}

`

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Chongho, 

We hope that the mentioned layout issue is resolved in your side. 

If you are facing any other issue, kindly provide details about the issue. We are always ready to help you. 

Regards, 
Lakshmi R.

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/107033949-fd097700-67f0-11eb-9fea-57d58b73428a.png)
Hello, I checked out the source code and I want to try to learn how to add some functions and submit it to you, but I found that the library chars used by the library cited a large number of files, which caused the android studio code to be prompted not to come out. Is there a good way to solve it?

**Comment by dharanidharandharmasivam** [comment]
Hi @chongbo2013 ,

We would like to let you know that, in our chart widget we have used part of and combined all the classes into a single chart library. This makes the android studio code to be promoted not to come out. We are already working on this and will be resolved soon. However, if you wish to submit your pull request to our source, then kindly use the below repository.

https://github.com/syncfusion/flutter-widgets/tree/master/packages 

Hope it helps you.

Thanks,
Dharani.

**Comment by bawa-ra** [comment]
This is still legit question
