### ISSUE TITLE
Unicode characters are not visible in openBookmarkView().

### ISSUE THREAD

**Issue by Shubham-Phatale** [syncfusion/flutter-examples#267]
I am working with syncfusion Flutter Pdf Viewer, I am having issue with bookmarks. my bookmark section is visible but in encoded format is there any way to first decode it and then view it.
![Screenshot_1611050617](https://user-images.githubusercontent.com/55837371/105020465-56417e80-5a6d-11eb-9aba-23cf7bf321d8.png)

**Comment by dillibabun** [comment]
Hi @Shubham-Phatale 

Greetings from Syncfusion.

We tried to reproduce the reported issue by creating a document with Unicode bookmarks, but the bookmark was shown properly with proper Unicode value. Please find the document which was used to reproduce the issue.
https://www.syncfusion.com/downloads/support/directtrac/general/pd/Bookmarks1177060065 

Kindly share us the issue reproducing document by creating a direct-trac incident using the following link.
https://www.syncfusion.com/support/directtrac/incidents/newincident 

Based the document, we will investigate further and provide you a prompt solution at the earliest.

Regards,
Dilli babu.
