### ISSUE TITLE
How to optimize, when there are 10,000 data on the interface, the interface is stuck and cannot be scrolled

### ISSUE THREAD

**Issue by chongbo2013** [syncfusion/flutter-examples#268]
![image](https://user-images.githubusercontent.com/3191545/105496532-8ea8bd00-5cf8-11eb-9b10-05cef64838f2.png)
How to optimize, when there are 10,000 data on the interface, the interface is stuck and cannot be scrolled, whether when the interface exceeds a certain number, you can omit the drawing partially overlapped to improve the speed

**Comment by dharanidharandharmasivam** [comment]
Hi @chongbo2013 , 

Greetings from Syncfusion. We have analyzed your scenario and unfortunately for the 10,000 data, there is no performance lag. We have ensured our current version of the chart widget (v18.4.35). Can you please revert chart widget version you are using and the sample in which you face the reported scenario, this will be helpful in further analysis in proving the solution sooner. And we also suggest using the fast line series in which there will not be any performance lag. 

To know more on fast line series, find the user guide below,
https://help.syncfusion.com/flutter/cartesian-charts/chart-types#fast-line-chart 

Thanks,
Dharani.

**Comment by chongbo2013** [comment]
Ok I will make demo thank u





------------------ Original ------------------

**Comment by dharanidharandharmasivam** [comment]
Hi @chongbo2013 ,

We will wait to hear from you.

Thanks,
Dharani.

**Comment by Doopin** [comment]
Hi @dharanidharandharmasivam 
Can you please tell me if its possible to plot 1000 additionals data point  each seconds to the chart which I get from a realtime system?
