### ISSUE TITLE
How to update blackoutDates when ViewChanged ?

### ISSUE THREAD

**Issue by ARTonu** [syncfusion/flutter-examples#269]
I want to update blackoutDates view when moved to next or previous month.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked, and your requirement is “**Update the blackout dates when viewChanged in Flutter calendar**”. We have prepared the sample for updating the **blackoutDates** using the **onViewChanged** callback. In this sample, we have updated the first 5 dates as blackout dates. Please find the sample from the following link. Also please find the code snippet for the same.

**Code snippet:**
```
child: SfCalendar(
  view: CalendarView.month,
  dataSource: _getCalendarDataSource(),
  allowedViews: [
    CalendarView.month,
    CalendarView.timelineMonth,
  ],
  blackoutDates: _blackoutDates,
  onViewChanged: viewChanged,
  blackoutDatesTextStyle: TextStyle(
      color: Colors.red, decoration: TextDecoration.lineThrough),
),

void viewChanged(ViewChangedDetails viewChangedDetails) {
  SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
    setState(() {
      _blackoutDates.add(viewChangedDetails.visibleDates[0]);
      _blackoutDates.add(viewChangedDetails.visibleDates[1]);
      _blackoutDates.add(viewChangedDetails.visibleDates[2]);
      _blackoutDates.add(viewChangedDetails.visibleDates[3]);
      _blackoutDates.add(viewChangedDetails.visibleDates[4]);
    });
  });
}

```

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/312116/ze/timeruler_calendar2019235038.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ARTonu** [comment]
it works. Thank You
