### ISSUE TITLE
StackedColumnSeries not stacking properly

### ISSUE THREAD

**Issue by Jayant2204** [syncfusion/flutter-examples#27]
I've two different series with DateTime and a double value. i'm trying to achieve Stacked Column chart stacking double value from two different series. ( This Part is done).

The issue is stacked value of second series isn't on the top and there's no option to force push them to top.  

[https://imgur.com/a/8TiJsQI](url)
```getBarSeries(List<PlotData> plotDay, List<PlotData> plotNight) {
    return <StackedColumnSeries<PlotData, DateTime>>[
      StackedColumnSeries<PlotData, DateTime>(
        dataSource: plotDay,
        name: "Day",
        color: Colors.blue[400],
        width: 0.4,
        yValueMapper: (PlotData data, _) => data.energy,
        xValueMapper: (PlotData data, _) => data.time,
       // borderRadius: BorderRadius.circular(5),
      ),
      StackedColumnSeries<PlotData, DateTime>(
        dataSource: plotNight,
        color: Colors.brown[400],
        width: 0.4,
         name: "Night",
        borderRadius: BorderRadius.circular(5),
        yValueMapper: (PlotData data, _) => data.energy,
        xValueMapper: (PlotData data, _) => data.time,
      ),
    ];
  }

**Comment by JayavigneshwaranG** [comment]
Hi @Jayant2204 ,

Sorry for the inconvenience.
We are able to reproduce the reported issue and we have fixed this now. Published the fix to pub. So please use the [latest version packages(1.0.0-beta.5)](https://pub.dev/packages/syncfusion_flutter_charts/versions/1.0.0-beta.5). 
Now both the series are stacked properly with the same configuration in the sample.

We are closing this issue. But you can reopen this if you face any concerns.

Thanks,
Jayavigneshwaran
