### ISSUE TITLE
I use CrosshairBehavior, how can I display the current value next to the vertical line

### ISSUE THREAD

**Issue by chongbo2013** [syncfusion/flutter-examples#271]
![image](https://user-images.githubusercontent.com/3191545/105994604-ca6dc900-60e2-11eb-8400-8f3d45993621.png)
I use CrosshairBehavior, how can I display the current value next to the vertical line

**Comment by Dharanipalani** [comment]
Hi @chongbo2013,  
 
We would like to inform you that you can use the **trackball** feature in our charts to know about the **current data-related information** of the clicked points. Using crosshair, you can only see the **current value of the axis**. The trackball feature will be useful for your requirement i.e to display the current value next to the vertical line.
 
To know more about trackball and crosshair, kindly refer to the below link,
[https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair ](url)
 
Sample: [https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/trackball/chart-with-trackball](url)

Thanks,
Dharanitharan. P
