### ISSUE TITLE
DragnDrop for Flutter Event Calendar

### ISSUE THREAD

**Issue by waketeck** [syncfusion/flutter-examples#272]
Hi syncfusion team,

I have implemented your flutter calendar widget: https://www.syncfusion.com/flutter-widgets/flutter-calendar. I am interested in an dragndrop event calendar functionality to make it easier to move an event to another date/time.

Could you please give me some information if and when it is scheduled?

Thx,

**Comment by Indumathi1195R** [comment]
Hi,

We have already logged the feature request for “**Providing a support for drag and drop and resizing support for appointments in the Flutter event calendar**”. We will implement this feature in any of our upcoming releases and let you know once the feature is implemented. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below-mentioned link.

**Feedback link:** https://www.syncfusion.com/feedback/15102/providing-support-for-drag-and-drop-and-resizing-the-appointment-duration-in-the

Regards,
Indumathi R
