### ISSUE TITLE
initialDateSelected is not working

### ISSUE THREAD

**Issue by pqtrong17** [syncfusion/flutter-examples#273]
I defined `initialSelectedDate` like this:
```
SfDateRangePicker(
              selectionMode: DateRangePickerSelectionMode.range,
              initialSelectedRange: pickerDateRangers,
              initialDisplayDate: DateTime(2021, 01, 14),
              initialSelectedDate:DateTime(2021, 01, 14) ,
              selectionColor: Colors.red,
              onSelectionChanged: (DateRangePickerSelectionChangedArgs args) {
                PickerDateRange range = args.value;
                setState(() {
                  pickerDateRangers = range;
                });
              },
            ),
```
But 14th Jan 2021 is not fill color? Why? How to fix it?

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**selectionColor not working for initialSelectedDate in Flutter date range picker**”.  In this shared code snippet, you have set the **selectionMode** as **range**, so **selectionColor** property value was not applied to picker. Kindly use **selectionColor** property for **single** and **multiple** selection modes, use **startRangeSelectionColor**, **endRangeSelectionColor**, **rangeSelectionColor** properties for **range** and **multi range** selection modes.

Please find the UG link for the same.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/customizations#selection-cell-customization 

Also, please find the KB links for the same.

**KB links:**
https://www.syncfusion.com/kb/11307/how-to-customize-the-month-cell-of-the-flutter-date-range-picker-sfdaterangepicker
https://www.syncfusion.com/kb/12148/how-to-customize-the-selected-range-cells-in-the-flutter-date-range-picker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by pqtrong17** [comment]
Thanks for response. I wanna always Range Mode but user can picked single date or range date. How to implement it?

**Comment by Indumathi1195R** [comment]
Hi,

**## I wanna always Range Mode but user can picked single date or range date. How to implement it?**

If your requirement as the color was applying for a first selected date, when set the selection mode as range, kindly use startRangeSelectionColor property. At the same time, if you select another date, it will look like a range selection and the corresponding range and end range selection color will be applied. We have attached the video for the same. Please find the video from the following link.

**Video link:** 
[video.zip](https://github.com/syncfusion/flutter-examples/files/5893738/video.zip)

If possible, can you please share more details of your requirement clearly or a Pictorial representation of your requirement? it would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by pqtrong17** [comment]
@Indumathi1195R My idea is If user selected date last time, when range dialog opening again, color of selected date is filling. Sorry because my english is not good. Hope you understand

**Comment by pqtrong17** [comment]
@Indumathi1195R Thank you very much for good support. I solved my proble by:
```
initialSelectedRange: PickerDateRange(DateTime(2021, 01, 31), null),
```

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We are glad to know that the issue resolved at your end. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
