### ISSUE TITLE
type '_PdfReferenceHolder' is not a subtype of type '_PdfArray' in type cast

### ISSUE THREAD

**Issue by lutang123** [syncfusion/flutter-examples#276]
Hello, 

I followed this tutorial: https://www.syncfusion.com/kb/11963/how-to-add-watermark-to-pdf-file-in-flutter

But it only works on this example, using exactly the same code, it doesn't work for other PDF, I keep getting this error: 

type '_PdfReferenceHolder' is not a subtype of type '_PdfArray' in type cast

Does anyone else have same problem?  Thank you!

**Comment by Anand3595** [comment]
Hi Lu Tang,

Thanks for contacting Syncfusion support.

We have tried reported issue with different test documents but we are not able to reproduce the reported “typecasting issue with adding bookmarks in PDF document” in our end. So, we request you to provide the below details,

1. Complete stack trace of the error
2. Input PDF document to reproduce the issue

It will help us to validate further and provide prompt solution from our end.

Regards,
Anand Panchamoorthi

**Comment by lutang123** [comment]
Hi, Anand, thank you for your quick response, here is the output:

**Comment by lutang123** [comment]
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:flutter/services.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<List<int>> _readDocumentData(String name) async {
    final ByteData data = await rootBundle.load('assets/$name');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

  Future<void> _addWatermarkToPDF() async {
    //Load the document
    PdfDocument document =
        PdfDocument(inputBytes: await _readDocumentData('sample.pdf'));
    //Get first page from document
    PdfPage page = document.pages[0];
    //Create PDF graphics for the page
    PdfGraphics graphics = page.graphics;
    //Save the graphics state for the watermark text
    graphics.save();
    //Set transparency level for the text
    graphics.setTransparency(0.25);
    //Rotate the text to -40 Degree
    graphics.rotateTransform(-40);
    //Draw the watermark text to the desired position over the PDF page with red color
    graphics.drawString(
        'Confidential', PdfStandardFont(PdfFontFamily.helvetica, 40),
        pen: PdfPen(PdfColor(255, 0, 0)),
        brush: PdfBrushes.red,
        bounds: Rect.fromLTWH(0, 300, 0, 0));
    //Restore the graphics
    graphics.restore();
    //Save the docuemnt
    List<int> bytes = document.save();
    //Dispose the document.
    document.dispose();

    //Get the external storage directory
    Directory directory = await getExternalStorageDirectory();
//Get the directory path
    String path = directory.path;
//Create an empty file to write the PDF data
    File file = File('$path/watermark.pdf');
//Write PDF data
    await file.writeAsBytes(bytes, flush: true);
//Open the PDF document in mobile
    OpenFile.open('$path/watermark.pdf');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              child: Text(
                'Add watermark',
                style: TextStyle(color: Colors.white),
              ),
              color: Colors.blue,
              onPressed: _addWatermarkToPDF,
            )
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by lutang123** [comment]
sorry the format of the code is not good, you can also try it yourself, download the code in the tutorial and change the pdf to the sample 2-page pdf, and see what error you get. I got sample pdf from here: http://www.africau.edu/images/default/sample.pdf

Tutorial is here: https://www.syncfusion.com/kb/11963/how-to-add-watermark-to-pdf-file-in-flutter

**Comment by Anand3595** [comment]
Hi Lu Tang,
 
Thanks for the details provided.
 
We can reproduce the reported typecasting issue in our end and it’s confirmed as a defect. We will include the fix in our upcoming weekly release which is planned on 9th Feb 2021.
 
The status of the bug can be track through below link: https://www.syncfusion.com/feedback/22116/exception-when-adding-watermark-to-the-pdf-document
 
Regards,
Anand Panchamoorthi

**Comment by lutang123** [comment]
Thank you!

**Comment by Anand3595** [comment]
Hi Lu Tang,

Due to some technical glitch, the fix is not included on the Feb 9th Weekly release. We will include the fix on the next weekly release which will be expected on 16th Feb 2021.

We regret for the inconvenienced.

Regards,
Anand Panchamoorthi

**Comment by Anand3595** [comment]
Hi Lu Tang,

Thanks for your patience.

We have included the fix for the typecasting issue and it has been available in our weekly release version [18.4.43-beta](https://pub.dev/packages/syncfusion_flutter_pdf/versions/18.4.43-beta). Please check this on your end and let us know if you need any further assistance in this.

Regards,
Anand Panchamoorthi

**Comment by VocsyJay** [comment]
its not working error shows that


type '_PdfStream' is not a subtype of type '_PdfArray?' in type cast
