### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by jasonjackson** [syncfusion/flutter-examples#277]
`% flutter run 
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                           1,257ms
Running Xcode build...                                                  
Xcode build done.                                           20.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    lib/sample_browser.dart:133:19: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
                      resizeToAvoidBottomPadding: true,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
      const Scaffold({
            ^^^^^^^^
    lib/sample_browser.dart:175:19: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
                      resizeToAvoidBottomPadding: true,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
      const Scaffold({
            ^^^^^^^^
    lib/samples/calendar/appointment_editor.dart:113:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
          resizeToAvoidBottomPadding: false,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
      const Scaffold({
            ^^^^^^^^
    lib/widgets/flutter_backdrop.dart:265:13: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
                resizeToAvoidBottomPadding: false,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
      const Scaffold({
            ^^^^^^^^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1111:7: Info: Struct 'ENUMLOGFONTEX' is empty.
    Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class ENUMLOGFONTEX extends Struct {
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2835:7: Info: Struct 'BLUETOOTH_PIN_INFO' is
    empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class BLUETOOTH_PIN_INFO extends Struct {
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2960:7: Info: Struct 'EXCEPINFO' is empty.
    Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class EXCEPINFO extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2966:7: Info: Struct 'PROPERTYKEY' is empty.
    Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class PROPERTYKEY extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2973:7: Info: Struct 'PROPVARIANT' is empty.
    Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class PROPVARIANT extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2978:7: Info: Struct 'SAFEARRAY' is empty.
    Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class SAFEARRAY extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2985:7: Info: Struct 'CLSID' is empty. Support
    for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class CLSID extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2992:7: Info: Struct 'STATSTG' is empty. Support
    for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class STATSTG extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2999:7: Info: Struct
    'NLM_SIMULATED_PROFILE_INFO' is empty. Support for empty structs is deprecated and will be removed in the next stable version of
    Dart. Use Opaque instead.
    class NLM_SIMULATED_PROFILE_INFO extends Struct {}
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:23:7: Info: Struct 'Utf8' is empty. Support for empty
    structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class Utf8 extends Struct {
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:16:7: Info: Struct 'Utf16' is empty. Support for empty
    structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
    class Utf16 extends Struct {
          ^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:47:33: Info: Support for using non-constant type
    arguments 'T' in this FFI API is deprecated and will be removed in the next stable version of Dart. Rewrite the code to ensure that
    type arguments are compile time constants referring to a valid native type.
      final int totalSize = count * sizeOf<T>();
                                    ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.`

**Comment by Dharanipalani** [comment]
Hi @jasonjackson, 
  
We have analyzed your scenario and we found that there are some breaking changes with the current Flutter version. So, we will resolve this in the upcoming weekly patch release will be expected to be rolled out on 16th February 2021 and we appreciate your patience. Until that, you can use the below Flutter version to avoid such compilation issues. 

[1.25.0-8.3.pre ](https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_1.25.0-8.3.pre-beta.zip)

Thanks, 
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @jasonjackson,

Thanks for being patience and we are glad to inform you that the reported issue has been resolved. So, kindly take an update of the [flutter-examples](https://github.com/syncfusion/flutter-examples) repository and run our samples, it will work now without any compilation failure.

Regards,
Dharanitharan. P
