### ISSUE TITLE
Is this package paid? If I use do I have to pay?

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#280]

**Comment by JayavigneshwaranG** [comment]
Hi @yasinakca ,

To use our package in your production app, it is mandatory to have a license. It can be either a Syncfusion community license or the Syncfusion commercial license.

To be qualified for the Syncfusion Community License Program you must have gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization and agree to be bound by Syncfusion’s terms and conditions. If you are not qualified for the community license, you can contact sales@syncfusion.com for commercial licensing options.

https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/LICENSE
https://www.syncfusion.com/sales/products
https://www.syncfusion.com/products/communitylicense

Please revert us if you have any questions.

Thanks,
Jayavigneshwaran
