### ISSUE TITLE
Is there a way to overlay text or images on top of a pdf?

### ISSUE THREAD

**Issue by jdeltoft** [syncfusion/flutter-examples#281]
I can use "stack" in flutter to draw over the pdf, but of course it won't align if I move around or zoom.  Is there some way to draw on the pdf itself?

**Comment by chinnumuniyappan** [comment]
Hi @jdeltoft ,

Thank you for contacting Syncfusion support.

We can draw text and images on the existing PDF document. We have created a sample to draw the text and image on a PDF document, you can check this sample on your end and let us know whether it is suitable for you.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/overlay_pdf708556961 

You can also refer our UG documentation for further details: 
https://help.syncfusion.com/flutter/pdf/working-with-text#drawing-text-in-an-existing-document 
https://help.syncfusion.com/flutter/pdf/working-with-images 

Regards,
Chinnu M
