### ISSUE TITLE
The method 'addAll' was called on null.

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#283]
When I'm receiving some data and put it in the pdf, I'm getting this error called "addAll was called on null". Any tips?

<img width="904" alt="Screen Shot 2021-02-16 at 17 33 34" src="https://user-images.githubusercontent.com/15368330/108077019-204be600-707d-11eb-8a6d-555b0f69325f.png">

**Comment by chinnumuniyappan** [comment]
Hi @yasinakca ,

Thank you for contacting Syncfusion support.

We have tried to reproduce the reported issue on our end but it was working fine on our end without any exception. So we request you to provide your code example and input document (if any) to reproduce the reported issue on our end. It will be more helpful for us to analyze further and provide you a prompt solution.

Regards,  
Chinnu M
