### ISSUE TITLE
type 'HijriDateTime' is not a subtype of type 'DateTime'

### ISSUE THREAD

**Issue by yasseralhendawy** [syncfusion/flutter-examples#285]
Hello,

While I am trying to use SfHijriDateRangePicker(),

it gave me this exception 

`type 'HijriDateTime' is not a subtype of type 'DateTime'

When the exception was thrown, this was the stack: 
#0      _IMonthView._getSemanticMonthLabel (package:syncfusion_flutter_datepicker/src/date_picker/month_view.dart:2029:39)
#1      _IMonthView._getSemanticsBuilder (package:syncfusion_flutter_datepicker/src/date_picker/month_view.dart:2012:20)
#2      _IMonthView.assembleSemanticsNode (package:syncfusion_flutter_datepicker/src/date_picker/month_view.dart:1884:52)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3721:13)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3713:16)
`

Thanks For your help & efforts

**Comment by Indumathi1195R** [comment]
Hi @yasseralhendawy,

We are able to reproduce the mentioned issue “**Type HijriDateTime is not a subtype of type DateTime, when accessibility enabled**”. We will fix the issue and include the issue fix in our upcoming Weekly NuGet package, which is expected to be rolled out by March 2, 2021, and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the issue for “**Type HijriDateTime is not a subtype of type DateTime, when accessibility enabled**” in our Weekly NuGet package version (**18.4.46-beta**). Kindly update the package to the latest version for resolving this issue. Please find the latest version from the following link.

**Link:** https://pub.dev/packages/syncfusion_flutter_datepicker/versions

Regards,
Indumathi R

**Comment by yasseralhendawy** [comment]
Hi @Indumathi1195R, I'm no longer see the issue, thanks
