### ISSUE TITLE
How to change the font family.

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#286]
It says font family doesn't support the character. How can I change the font family for that package?

**Comment by Dharanipalani** [comment]
Hi @yasinakca,

Greetings from Syncfusion. Can you please share the package name in which you are facing such an issue? This information will help us to solve your problem as early as possible.

Thanks,
Dharanitharan. P

**Comment by yasinakca** [comment]
I'm struggling with that issue with both syncfusion_flutter_pdf  and syncfusion_flutter_xlsio.
When I use some Turkish chracters like ı,ü etc. I'm getting this error below.
<img width="1145" alt="Screen Shot 2021-02-23 at 09 00 34" src="https://user-images.githubusercontent.com/15368330/108807506-b28c4680-75b5-11eb-9064-aea19a42ba42.png">

**Comment by chinnumuniyappan** [comment]
Hi @yasinakca,

We found that you are using `PdfStandardFont` to draw the Unicode characters. The PDF standard font is not supported to draw the Unicode characters. So we suggest you use the `PdfTrueTypeFont` API to draw the Unicode characters. Refer to the below code example and UG documentation for more details.

```dart
    //Create new PDF document
    PdfDocument document = PdfDocument();
    //Add a new page to the document
    PdfPage page = document.pages.add();
    //Create PdfTrueTypeFont.
    PdfFont font = PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
    //Draw the Unicode text.
    page.graphics.drawString('Selam Dünya! (ı,ü)', font,
        brush: PdfBrushes.black, bounds: Rect.fromLTWH(0, 0, 200, 20));
    //Save the docuemnt
    List<int> bytes = document.save();
    //Dispose the document.
    document.dispose();
```
```dart
  Future<List<int>> _readData(String name) async {
    final ByteData data = await rootBundle.load('assets/$name');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }
```
Please refer to the following documentation for more details about PdfTrueTypeFont.
https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-truetype-fonts

You can also draw the Unicode characters using the Google font package as follows.
https://www.syncfusion.com/kb/11976/how-to-draw-unicode-text-in-a-pdf-file-using-google-fonts-package 

Regards, 
Chinnu M

**Comment by yasinakca** [comment]
Can you give a spesific font example cause I tried both way and none of them are solved my problem.

**Comment by yasinakca** [comment]
Sir, can you please share an email. I would like to contact via mail. Best regards.

**Comment by chinnumuniyappan** [comment]
Hi @yasinakca ,

We have created a sample to draw Unicode characters and attached it for your reference below. 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1271342762 
Try the above sample on your end and let us know whether it is achieving your requirement.

You can share the details through the mail id support@syncfusion.com or contact our [Syncfusion support team](https://www.syncfusion.com/support/directtrac/incidents/newincident) or post them in our [community forums](https://www.syncfusion.com/forums). You can also submit a feature request or a bug alert through our [feedback portal](https://www.syncfusion.com/feedback/flutter).

Regards,  
Chinnu M

**Comment by yasinakca** [comment]
Thank you so much @chinnumuniyappan  it works now.

**Comment by Rabeeh96** [comment]
when create an list  cant change the font family?
 This information will help us to solve my problem as early as possible.

**Comment by yasinakca** [comment]
Edit: @chinnumuniyappan  still getting the same error. It should not be that much complicated. Can you help please?

**Comment by chinnumuniyappan** [comment]
Hi @Rabeeh96 ,

We can change the font family when creating a list to the PDF document. We have modified the sample and attached it for your reference below. 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-786569516 
Try the above sample on your end and let us know whether it is achieving your requirement. You can refer to [our documentation](https://help.syncfusion.com/flutter/pdf/working-with-lists) for more details.

Regards,  
Chinnu M

**Comment by chinnumuniyappan** [comment]
> when create an list cant change the font family?
> This information will help us to solve my problem as early as possible.
> @chinnumuniyappan

Hi @Rabeeh96 ,

We can change the font family when creating a list to the PDF document. We have modified the sample and attached it for your reference below. 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-786569516 
Try the above sample on your end and let us know whether it is achieving your requirement. You can refer to [our documentation](https://help.syncfusion.com/flutter/pdf/working-with-lists) for more details.

Regards,  
Chinnu M

**Comment by chinnumuniyappan** [comment]
> you help please?

Hi @yasinakca ,

Can you please share more details such as the code which you have used and font, it would more helpful for us and provide you a prompt solution.

Regards, 
Chinnu M

**Comment by chinnumuniyappan** [comment]
> Edit: @chinnumuniyappan still getting the same error. It should not be that much complicated. Can you help please?

Hi @yasinakca ,

Can you please share more details such as the code which you have used and font, it would more helpful for us and provide you a prompt solution.

Regards, 
Chinnu M

**Comment by yasinakca** [comment]
@chinnumuniyappan  if you share an email I can share my full code. I used the exact same project that you send but I'm still getting the "Invalid argument the character doesn't supported by font."

**Comment by yasinakca** [comment]
@chinnumuniyappan  And this is my code.

Future<void> generateInvoice() async {
    //Create a PDF document.
    final PdfDocument document = PdfDocument();
    //Add page to the PDF
    final PdfPage page = document.pages.add();
    //Get page client size
    final Size pageSize = page.getClientSize();
    //Draw rectangle
    page.graphics.drawRectangle(
      bounds: Rect.fromLTWH(0, 0, pageSize.width, pageSize.height),
      pen: PdfPen(
        PdfColor(142, 170, 219, 255),
      ),
    );
    //Generate PDF grid.
    final PdfGrid grid = await getGrid();
    //Draw the header section by creating text element
    final PdfLayoutResult result = await drawHeader(page, pageSize, grid);
    //Draw grid
    drawGrid(page, grid, result);
    //Add invoice footer
    drawFooter(page, pageSize);
    //Save and launch the document
    final List<int> bytes = document.save();
    //Dispose the document.
    document.dispose();
    //Get the storage folder location using path_provider package.
    final Directory directory =
        await path_provider.getApplicationDocumentsDirectory();
    final String path = directory.path;
    final File file = File('$path/output.pdf');
    await file.writeAsBytes(bytes);
    //Launch the file (used open_file package)
    await open_file.OpenFile.open('$path/output.pdf');
  }

  void drawFooter(PdfPage page, Size pageSize) async {
    final PdfPen linePen =
        PdfPen(PdfColor(142, 170, 219, 255), dashStyle: PdfDashStyle.custom);
    linePen.dashPattern = <double>[3, 3];
    //Draw line
    page.graphics.drawLine(linePen, Offset(0, pageSize.height - 100),
        Offset(pageSize.width, pageSize.height - 100));

    const String footerContent =
        '''800 Interchange Blvd.\r\n\r\nSuite 2501, Austin,
         TX 78721\r\n\r\nAny Questions? support@adventure-works.com''';

    PdfFont font =
        PdfTrueTypeFont(await _readData('OpenSans-SemiBold.ttf'), 12);
    //Added 30 as a margin for the layout
    page.graphics.drawString(footerContent, font,
        format: PdfStringFormat(alignment: PdfTextAlignment.right),
        bounds: Rect.fromLTWH(pageSize.width - 30, pageSize.height - 70, 0, 0));
  }

  void drawGrid(PdfPage page, PdfGrid grid, PdfLayoutResult result) {
    result = grid.draw(
      page: page,
      bounds: Rect.fromLTWH(0, result.bounds.bottom + 40, 0, 0),
    );
  }

  Future<PdfLayoutResult> drawHeader(
      PdfPage page, Size pageSize, PdfGrid grid) async {
    PdfFont font =
        PdfTrueTypeFont(await _readData('OpenSans-SemiBold.ttf'), 12);

    //Draw rectangle
    page.graphics.drawRectangle(
        brush: PdfSolidBrush(PdfColor(91, 126, 215, 255)),
        bounds: Rect.fromLTWH(0, 0, pageSize.width - 115, 90));
    //Draw string
    page.graphics.drawString(widget.raporBaslik.toUpperCase(), font,
        brush: PdfBrushes.white,
        bounds: Rect.fromLTWH(25, 0, pageSize.width - 115, 90),
        format: PdfStringFormat(lineAlignment: PdfVerticalAlignment.middle));

    page.graphics.drawRectangle(
        bounds: Rect.fromLTWH(400, 0, pageSize.width - 400, 90),
        brush: PdfSolidBrush(PdfColor(65, 104, 205)));

    //final PdfFont contentFont = PdfStandardFont(PdfFontFamily.helvetica, 9);
    //Draw string

    //Rapor kapak resminin geleceği yer
    page.graphics.drawString('Amount', font,
        brush: PdfBrushes.white,
        bounds: Rect.fromLTWH(400, 0, pageSize.width - 400, 33),
        format: PdfStringFormat(
            alignment: PdfTextAlignment.center,
            lineAlignment: PdfVerticalAlignment.bottom));

    //Create data foramt and convert it to text.
    final DateFormat format = DateFormat.yMMMMd('en_US');
    final String invoiceNumber =
        'Olusturan: ${widget.userName.toUpperCase()}\r\n\r\nTarih: ' +
            format.format(DateTime.now());
    final Size contentSize = font.measureString(invoiceNumber);
    String address = '''Konu: ${widget.konu}, 
        \r\n\r\nKatilimcilar ${widget.katilimcilar}''';

    PdfTextElement(text: invoiceNumber, font: font).draw(
        page: page,
        bounds: Rect.fromLTWH(pageSize.width - (contentSize.width + 30), 120,
            contentSize.width + 30, pageSize.height - 120));

    return PdfTextElement(text: address, font: font).draw(
        page: page,
        bounds: Rect.fromLTWH(30, 120,
            pageSize.width - (contentSize.width + 30), pageSize.height - 120));
  }

  Future<PdfGrid> getGrid() async {
    //Create a PDF grid
    final PdfGrid grid = PdfGrid();
    //Secify the columns count to the grid.
    grid.columns.add(count: 5);
    //Create the header row of the grid.
    final PdfGridRow headerRow = grid.headers.add(1)[0];
    //Set style
    headerRow.style.backgroundBrush = PdfSolidBrush(PdfColor(68, 114, 196));
    headerRow.style.textBrush = PdfBrushes.white;
    headerRow.cells[0].value = 'Bulgu gorsel';
    //headerRow.cells[0].stringFormat.alignment = PdfTextAlignment.center;
    headerRow.cells[1].value = 'Bulgu';
    headerRow.cells[2].value = 'Bolge';
    headerRow.cells[3].value = 'Yer';
    headerRow.cells[4].value = 'Mahal';
    //Add rows
    for (var item in widget.bulgular) {
      await addProducts(
          item.image, item.bulgu, item.bolge, item.yer, item.mahal, grid);
    }

    //Apply the table built-in style
    grid.applyBuiltInStyle(PdfGridBuiltInStyle.listTable4Accent5);
    //Set gird columns width
    grid.columns[1].width = 200;
    for (int i = 0; i < headerRow.cells.count; i++) {
      headerRow.cells[i].style.cellPadding =
          PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
    }
    for (int i = 0; i < grid.rows.count; i++) {
      final PdfGridRow row = grid.rows[i];
      for (int j = 0; j < row.cells.count; j++) {
        final PdfGridCell cell = row.cells[j];
        if (j == 0) {
          cell.stringFormat.alignment = PdfTextAlignment.center;
        }
        cell.style.cellPadding =
            PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
      }
    }
    return grid;
  }

  Future<void> addProducts(String imageUrl, String bulgu, String bolge,
      String mahal, String yer, PdfGrid grid) async {
    final PdfGridRow row = grid.rows.add();
    row.cells[0].value = PdfBitmap(await getImageFromNetWork(imageUrl));
    //set row height.
    row.height = 50;
    row.cells[1].value = bulgu;
    row.cells[2].value = bolge;
    row.cells[3].value = mahal;
    row.cells[4].value = yer;
  }

  Future<List<int>> getImageFromNetWork(String url) async {
    final response = await get(url);
    return response.bodyBytes;
  }

  Future<List<int>> _readData(String name) async {
    final ByteData data = await rootBundle.load('asset/fonts/$name');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

**Comment by chinnumuniyappan** [comment]
Hi @yasinakca ,

Thanks for the details.

Based on your code example, we found that you are not using Unicode font to draw the grid, so we have modified the code for your reference below.

```dart
    //Set font to the grid.
    grid.style.font =
        PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
```
The complete method as follows.
```dart
Future getGrid() async {
    //Create a PDF grid
    final PdfGrid grid = PdfGrid();
    //Set font to the grid.
    grid.style.font =
        PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
    //Secify the columns count to the grid.
    grid.columns.add(count: 5);
    //Create the header row of the grid.
    final PdfGridRow headerRow = grid.headers.add(1)[0];
    //Set style
    headerRow.style.backgroundBrush = PdfSolidBrush(PdfColor(68, 114, 196));
    headerRow.style.textBrush = PdfBrushes.white;
    headerRow.cells[0].value = 'Bulgu gorsel';
    //headerRow.cells[0].stringFormat.alignment = PdfTextAlignment.center;
    headerRow.cells[1].value = 'Bulgu';
    headerRow.cells[2].value = 'Bolge';
    headerRow.cells[3].value = 'Yer';
    headerRow.cells[4].value = 'Mahal';
    //Add rows
    for (var item in widget.bulgular) {
      await addProducts(
          item.image, item.bulgu, item.bolge, item.yer, item.mahal, grid);
    }

    //Apply the table built-in style
    grid.applyBuiltInStyle(PdfGridBuiltInStyle.listTable4Accent5);
    //Set gird columns width
    grid.columns[1].width = 200;
    for (int i = 0; i < headerRow.cells.count; i++) {
      headerRow.cells[i].style.cellPadding =
          PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
    }
    for (int i = 0; i < grid.rows.count; i++) {
      final PdfGridRow row = grid.rows[i];
      for (int j = 0; j < row.cells.count; j++) {
        final PdfGridCell cell = row.cells[j];
        if (j == 0) {
          cell.stringFormat.alignment = PdfTextAlignment.center;
        }
        cell.style.cellPadding =
            PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
      }
    }
    return grid;
  }
```

Try the above code on your end and let me know if you have any concerns.

Note: The default font for the PDF grid is standard font. 

Regards, 
Chinnu M

**Comment by yasinakca** [comment]
I used your advice, it's working know for the character error but now I'm getting this error.

<img width="1220" alt="Screen Shot 2021-02-26 at 14 34 45" src="https://user-images.githubusercontent.com/15368330/109295486-e37fac00-783f-11eb-8d66-03ebe4c7bafc.png">

**Comment by Rabeeh96** [comment]
@chinnumuniyappan 
 How Set a Total and Discount & total Tax at the end of the Table,
 if I set in Root Its Pop Over into table Design

**Comment by chinnumuniyappan** [comment]
> I used your advice, it's working know for the character error but now I'm getting this error.
> 
> <img alt="Screen Shot 2021-02-26 at 14 34 45" width="1220" src="https://user-images.githubusercontent.com/15368330/109295486-e37fac00-783f-11eb-8d66-03ebe4c7bafc.png">

Hi @yasinakca ,

We found that the PDF document is disposed of before draw the footer text, so we suggest you wait for all the asynchronous methods before disposing of the document. we have changed the code for your reference below.
```dart
    //Add invoice footer
    await drawFooter(page, pageSize);
```
Use the `await` keyword for drawFooter method.

Regards, 
Chinnu M

**Comment by chinnumuniyappan** [comment]
> @chinnumuniyappan
> How Set a Total and Discount & total Tax at the end of the Table,
> if I set in Root Its Pop Over into table Design

Hi @Rabeeh96 ,

We can draw the text next to the table by using `PdfLayoutResult` API as stated below.

```dart
PdfLayoutResult result = result = grid.draw(
        page: page, bounds: Rect.fromLTWH(0, result.bounds.bottom + 40, 0, 0));
//Draw grand total.
page.graphics.drawString('Grand Total',
    PdfStandardFont(PdfFontFamily.helvetica, 9, style: PdfFontStyle.bold),
    bounds: Rect.fromLTWH( 0,  result.bounds.bottom + 10, 150, 11));
```
Refer to the following sample for more details. 
https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/pdf/invoice.dart#L140 

Regards, 
Chinnu M

**Comment by Rabeeh96** [comment]
@chinnumuniyappan 
PdfLayoutResult result = result = grid.draw(
        page: page, bounds: Rect.fromLTWH(0, result.bounds.bottom + 40, 0, 0));
//Draw grand total.
page.graphics.drawString('Grand Total',
    PdfStandardFont(PdfFontFamily.helvetica, 9, style: PdfFontStyle.bold),
    bounds: Rect.fromLTWH( 0,  result.bounds.bottom + 10, 150, 11));
its not working?

**Comment by chinnumuniyappan** [comment]
Hi @Rabeeh96 ,

Can you please more details about your requirement like sample output document/screenshot and code example which you have used on your end? It would more helpful for us to analyze further and update you with a prompt solution.

Regards, 
Chinnu M

**Comment by yasinakca** [comment]
can I access the links again pls?
