### ISSUE TITLE
Unhandled Exception: Invalid argument (The character is not supported by the font.): 318

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#287]
How to avoid font family issues?

**Comment by Dharanipalani** [comment]
Hi @yasinakca,

Thanks for the interest in our Flutter widgets. We are unable to identify the issue with the given information. So, please share more information about the font issue you are facing and the package you are using. This will help us to provide you the solution sooner.

Thanks,
Dharanitharan. P
