### ISSUE TITLE
Datagrid GridWidgetColumn when sorting

### ISSUE THREAD

**Issue by BenPoell** [syncfusion/flutter-examples#289]
Hi,
I'm trying to implement the datagrid with a GridWidgetColumn.
Currently I'm facing the issue that the GridWidgetColumn is not sorted with all the other columns. Or at least I'm not able "get the actual data" from the sorted rows. Is there anything I'm missing or any how-to for that?

The issue basically is that I only receive `rowindex` in the cellBuilder and it seems that the datasource list is not sorted, when sorting the grid.
Can I somehow receive the actual row value or sort the datasource list?

In the example of the documentation the image would always stay the same although ID, name and salary change according to the sorting:
```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfDataGrid(
      source: _employeeDataSource,
      cellBuilder: (BuildContext context, GridColumn column, int rowindex) {
        return employees[rowIndex].image;
      },
      columns: [
        GridNumericColumn(mappingName: 'id', headerText: 'ID'),
        GridWidgetColumn(mappingName: 'image', headerText: 'Image'),
        GridTextColumn(mappingName: 'name', headerText: 'Name'),
        GridNumericColumn(mappingName: 'salary', headerText: 'Salary')
      ],
    ),
  );
}
```

Best regards,
Benjamin

**Comment by NeelakandanKannan** [comment]
Hi @BenPoell ,

Greetings from Syncfusion.

If you want to load an image based on the currently sorted order, you have to use the DataGridSource[index] indexer instead of the datasource collection which you set in dataSource property of DataGridSource. DataGrid provides the inner sorted list collection in the DataGridSource[index]indexer. Please find the below code snippet,

```dart
@override

  Widget build(BuildContext context) {

    return Scaffold(

        appBar: AppBar(title: Text('Syncfusion Flutter DataGrid')),

        body: SfDataGrid(

            allowSorting: true,

            source: _employeeDataSource,

            columnWidthMode: ColumnWidthMode.auto,

            cellBuilder:

                (BuildContext context, GridColumn column, int rowIndex) {

              return Container(

                padding: const EdgeInsets.all(3),

                child: _employeeDataSource[rowIndex].dealer,

              );

            },

            columns: _columns));

  }
```
