### ISSUE TITLE
Network image does not fit into calendar source circle

### ISSUE THREAD

**Issue by jehato47** [syncfusion/flutter-examples#290]
Calendar resources are part of weekview calendar. It comes with default circle image however when we try to add network image it exceed boundries of little circle. Is there any way to change image provider to normal image or directly widget?

![SmartSelect_20210302-235932.jpg](https://user-images.githubusercontent.com/45170719/109714366-5fb51f00-7bb3-11eb-8e80-b5bf12635809.jpg)

![SmartSelect_20210302-235851.jpg](https://user-images.githubusercontent.com/45170719/109714399-6b084a80-7bb3-11eb-909d-7498fc1b24d2.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Network image doesn’t fit to the circle of the resource in the Flutter calendar**” and it is working fine as expected from our end. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/317669/ze/minimum_appointmentduration-1588263967.zip

**Screenshot:**
![vidma_recorder_03032021_140726 1](https://user-images.githubusercontent.com/54974849/109789856-c3ccf700-7c36-11eb-99e8-1ccfafa9a01e.jpg)

If possible, can you please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us back with the following details.

•	Network image link
•	Replication procedure

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by jehato47** [comment]
Thank you for your reply

I could not see the sample because access denied. Can you provide a valid link?

![Screenshot_20210303-133106_Chrome.jpg](https://user-images.githubusercontent.com/45170719/109792704-d8a08f00-7c24-11eb-9ee2-3163cebc7ed1.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

Sorry for the inconvenience caused.

Can you please find the sample from the following link?

**Sample link:**
[minimum_appointmentduration.zip](https://github.com/syncfusion/flutter-examples/files/6075582/minimum_appointmentduration.zip)

Regards,
Indumathi R

**Comment by jehato47** [comment]
Both your sample and default samples work however there is still a problem with this.

Here is how i set calendar resources in provider:
![calendar_resources](https://user-images.githubusercontent.com/45170719/109805149-27095a00-7c34-11eb-94e9-ff7f09091164.png)

how i set appointments :
![appointments](https://user-images.githubusercontent.com/45170719/109805189-312b5880-7c34-11eb-98b0-9156a01978dd.PNG)

how i return it from provider
![data_source](https://user-images.githubusercontent.com/45170719/109805266-4902dc80-7c34-11eb-8b34-88749a00d8d8.PNG)

how i use it in actual screen:
![events](https://user-images.githubusercontent.com/45170719/109805363-6768d800-7c34-11eb-8562-a6b1de5ded2a.PNG)


here is default get_shift_scheduler function i use:
![get_shift_scheduler](https://user-images.githubusercontent.com/45170719/109805524-98490d00-7c34-11eb-8315-79b8d04de1b2.PNG)


When we use default and go on everything straightforward it works but when we use provider something doesn't complete.


And here is the result:
![Screenshot_1614774625](https://user-images.githubusercontent.com/45170719/109806219-80be5400-7c35-11eb-89b1-84993dbad54e.png)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We are able to reproduce the mentioned issue “**Network image doesn’t fit to the circle of the resource in the Flutter calendar**” and currently we are validating the issue at the source level. We will validate and update you the further details on or before March 8, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have fixed the mentioned issue “**Network image doesn’t fit to the circle of the resource in the Flutter calendar**” and include the issue fix in our upcoming 2021 Volume 1 release, which is expected to be rolled out by mid of March 2020 and we will let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the mentioned issue fix for “**Network image doesn’t fit to the circle of the resource in the Flutter calendar**” in our latest Weekly Nuget **version 18.4.48**. Kindly update Flutter calendar package to the mentioned version for resolving the issue. Also please find the changelog and release notes links from the following links.

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v18.4.0.48?type=all

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_calendar/changelog

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by jehato47** [comment]
Thank you for your interest. It works well now.

I respect your love of your job.
