### ISSUE TITLE
Migrate to Null safety

### ISSUE THREAD

**Issue by savs90** [syncfusion/flutter-examples#291]
Hello to everyone. I wanted to ask if there is some work progressing in this way , because we already officially flutter 2 with null safety in stable channel? All dependencies are already migrated to null safety i think.

**Comment by Dharanipalani** [comment]
Hi @savs90,

Greetings from Syncfusion. We are analyzing the timeline for providing null safety support for all our widgets. And thus, will update you on the status in two business days (9th March 2021), we appreciate your patience till then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @savs90,

Thanks for being patience and we are glad to inform you that we will provide null safety support to all our widgets in the upcoming volume1 main release itself which is expected to be rolled out at the end of March 2021. We appreciate your patience till then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @savs90,

Most welcome and thanks for the revert. Please revert us if you need any further assistance and we are always happy in assisting you.

Thanks,
Dharanitharan. P

**Comment by Dineshkumar-kovalan** [comment]
Hi @savs90,
 

Thanks for your patience. We are glad to inform you that we have migrated our widget packages to null safety and are rolled out in our vol 1 main release. To use the null safety version of our [flutter-widgets](https://github.com/syncfusion/flutter-widgets), kindly upgrade the package version to the latest version (19.1.54+1).

 

Please revert us if you still have further concerns.

 

Regards,
Dineshkumar K
