### ISSUE TITLE
any method to make a pdf from webview or html?

### ISSUE THREAD

**Issue by kechankrisna** [syncfusion/flutter-examples#294]
I would be so glade if your plugin can have support pdf from html or webview for all platform.

**Comment by Anand3595** [comment]
Hi @kechankrisna ,

Thanks for contacting Syncfusion support.

We have logged the feature request for “Add support to convert HTML to PDF in Flutter platform” in our feature request list. At present we do not have any immediate plan to implement this feature in our end. We will implement this feature any of our upcoming releases, you can tract the current status of this feature request by using the below mentioned link. 

https://www.syncfusion.com/feedback/18068/add-support-for-converting-html-to-pdf-in-flutter-platform 

Regards,
Anand Panchamoorthi
