### ISSUE TITLE
TimeSlotViewSettings not changing

### ISSUE THREAD

**Issue by dimitristaufer** [syncfusion/flutter-examples#295]
Hi, I am using syncfusion_flutter_calendar 18.4.46 in my flutter project.

I tried to use the **timeSlotViewSettings** with **syncfusion.TimeSlotViewSettings(timeFormat:'H')**, to get the 24-hour time format in the agenda view, however it still shows as "03:00 PM - 05:00 PM", instead of "15:00 - 17:00".

Thanks and regards
Dimitri

**Comment by Indumathi1195R** [comment]
Hi ,

Based on the provided information, we have checked, and your requirement is “**Changing the agenda appointment time format in the SfCalendar**” and your requirement can be achieved by using **appointmentTimeTextFormat** property of the calendar. We have UG and KB document for the same. Please find the UG and KB document from the following links,

**UG link:** https://help.syncfusion.com/flutter/calendar/appointments#appointment-time-format

**KB link:** https://www.syncfusion.com/kb/11989/how-to-format-the-appointment-time-in-the-flutter-event-calendar-sfcalendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by dimitristaufer** [comment]
Perfect! That's what I was looking for. Thank you.
