### ISSUE TITLE
Show image from base64

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#298]
Hi everyone,

I would like to show an image in my pdf file which is uploaded to sqflite as base64.

class Utility {
  static Image imageFromBase64String(String base64String) {
    return Image.memory(
      base64Decode(base64String),
      fit: BoxFit.fill,
    );
  }

  static Uint8List dataFromBase64String(String base64String) {
    return base64Decode(base64String);
  }

  static String base64String(Uint8List data) {
    return base64Encode(data);
  }
}

I'm using this class to save an show images with sqflite. How can I entegrate this to my grid so that I can show image. 
The below example is one of my image's url which come from sqflite. Can you help?

/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCAQAAdgDASIAAhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAECAwQFBv/EABgBAQEBAQEAAAAAAAAAAAAAAAABAgME/9oADAMBAAIQAxAAAAL58AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGj7vI+Ht9FfM+Ze7aPAe/MfPPo61889uteM9+MvBe/RfDe6s8J71TwnraV4s+5XLxJ9nfV+fe3ongR72R473GXhx7k14b2bR4kfQ8NeY6vWPAfQ0jwXuq8J7sx4L6LE8N7sV4UenfTyo9LM4p9ToPDn6XQ+WfVK334unLh26c6x876HOPBnsnLk5+rsjyrdm2nBPrcEVQ5ufS+W02wGs4RHZOFopj0YbvVCmZfn6OZOmmM26Usrm2rSuzzq0NvR5evK88umV71omU0jd6a8cGle2pzXr02bZaeeW2ruvXv4e+53vMHoaUz531OCmdd+uHRq4c3oedHPrXLE93nz7Ojya3zw6MenyTupj0Hn9saS8jfCTdXXKn
..... etc

**Comment by Anand3595** [comment]
Hi Yasin,

Thanks for contacting Syncfusion support.

We can draw image in grid cell by assigning [PdfImage](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfImage-class.html)/[PdfBitmap](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfBitmap-class.html) as a value of corresponding cell. We can load image data as a base64 string by using [PdfBitmap.fromBase64String(String imageData)](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfBitmap/PdfBitmap.fromBase64String.html) constructor.

Please find the code snippet below to load image from base64 string and draw it into PDF grid cell.

> //Create the PDF document
PdfDocument document = PdfDocument();
//Add a new page
PdfPage page = document.pages.add();
//Create a PdfGrid class
PdfGrid grid = PdfGrid();
//Add the columns to the grid
grid.columns.add(count: 3);
//Add header to the grid
grid.headers.add(1);
//Add the rows to the grid
PdfGridRow header = grid.headers[0];
header.cells[0].value = 'Employee ID';
header.cells[1].value = 'Employee Name';
header.cells[2].value = 'Employee Photo';
//Add rows to grid
PdfGridRow row = grid.rows.add();
row.cells[0].value = 'E01';
row.cells[1].value = 'Clay';
**//Load image from base64 string
PdfImage image = PdfBitmap.fromBase64String(imageData);
//Set image as a value of the grid cell
row.cells[2].value = image;**
grid.columns[2].width = 100;
grid.rows[0].height = 100;
//Draw the grid
grid.draw(page: page, bounds: const Rect.fromLTWH(0, 0, 0, 0));
//Save the docuemnt
List<int> bytes = document.save();
//Dispose the document.
document.dispose();

Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/grid_image_base64-220048352 and let us know if you need any further assistance in this.

Regards,
Anand Panchamoorthi

**Comment by yasinakca** [comment]
Thanks
