### ISSUE TITLE
I want to block to editing calendar not to edit by user.

### ISSUE THREAD

**Issue by osmaneser** [syncfusion/flutter-examples#299]
![image](https://user-images.githubusercontent.com/39035584/110619501-f469df00-81a8-11eb-9443-7e945510223d.png)

Ranges in the picture are date ranges loaded when the screen is first opened.
My goal is to prevent these values from being edited by the user.

User these dates should not be edited

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked and your requirement  “**Disallow the user to select the already selected ranges**” and your requirement can be achieved by adding the controller selected date ranges values in blackout dates also and adding the decoration for those dates. We have prepared the simple sample for the same. Please find the sample and screenshot from the following link.

**Sample link:**
[flutter_visibledates_calendar.zip](https://github.com/syncfusion/flutter-examples/files/6120938/flutter_visibledates_calendar.zip)

**Screenshot:**
![vidma_recorder_11032021_113045](https://user-images.githubusercontent.com/54974849/110747719-c2b64e00-8264-11eb-90ad-4aa78b44c1f8.jpg)


Also please find the UG link for blackoutDates and blackoutDates customization.

**UG links:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates
https://help.syncfusion.com/flutter/daterangepicker/customizations#month-cell-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
