### ISSUE TITLE
Be able to change the focus of the grid when the date changes by the controller

### ISSUE THREAD

**Issue by bernardoveras** [syncfusion/flutter-examples#300]
When I change the date through the controller it doesn't change the component's focus!

video:

https://user-images.githubusercontent.com/56937988/110720469-6106cd00-81ed-11eb-9ac8-13069a122862.mp4

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information and video, we are unable to understand your requirement clearly. If possible, please share the issue details clearly with the following details.

•	Exact issue details 
•	Replication procedure 
•	Code snippet 

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by bernardoveras** [comment]
Hi!
In the video it is explicit what I described.
The zoom focus does not change after changing the value by the controller.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Based on the shared video, we are unable to understand your requirement clearly and also we are not clear about component focus. Also, if possible can you please share the code snippet of the button clicked callbacks. It would be helpful for us to analyze and provide you a prompt solution on this.

Regards,
Indumathi R
