### ISSUE TITLE
TextField in custom header

### ISSUE THREAD

**Issue by pbeccegato** [syncfusion/flutter-examples#301]
I've implemented sfDataGrid into a Flutter Web project. In my project, datagrid has a custom header with a textfield. Before Flutter 2, everything works fine; after Flutter 2, the textfield appears as readonly and I can't use it. I tried to implement the same textfield into the example project, editing the file datagrid_custom_header.dart as follow:

Widget buildHeaderCell(GridColumn column) {
final themeData =
        SfDataGridThemeData(brightness: model.themeData.brightness);
    return Container(
        child: Row(
      children: [
        Flexible(child: TextField())
        // Flexible(
        //     child: Text(column.headerText,
        //         style: themeData.headerStyle.textStyle)),
        // Icon(
        //   Icons.keyboard_arrow_down,
        //   size: 25,
        //   color: Colors.grey,
        // )
      ],
    ));
  }

[datagrid_custom_header.dart.zip](https://github.com/syncfusion/flutter-examples/files/6137187/datagrid_custom_header.dart.zip)

Thanks in advance
Peter

**Comment by RenugaSadagoban98** [comment]
Hi Pbeccegato,
 
Thank you for contacting Syncfusion support.
 
Currently, we are analyzing your reported issue with “ TextField appears to be read only in Web”. We will validate and update you with the details in two business days i.e 17th March 2021. We appreciate your patience until then.

**Comment by RenugaSadagoban98** [comment]
Hi Pbeccegato, 
 
Thank you for your patience. 
 
We have analyzed your reported issue. This problem is occurred due to the focus issue of the TextField in Flutter 2.0. We have reported this issue to the framework. For further details, you can refer to the following link, 
 
https://github.com/flutter/flutter/issues/78413 

We will get back to you once we got the details from them.

**Comment by pbeccegato** [comment]
As suggested in [flutter/flutter#78413](https://github.com/flutter/flutter/issues/78413), I switched on MASTER channel and  now TextField is editable again.

Many thanks for you support.
