### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#303]
When I create a pdf or excel file in my grid cell, if I use a big text, the texts are getting complicated.
Like in the screenshot below. Can you guys please help me about this. I'm struggling same issue with pdf package too.

<img width="1124" alt="Screen Shot 2021-03-16 at 10 12 53" src="https://user-images.githubusercontent.com/15368330/111269867-2dd69a80-8640-11eb-908f-77992215f542.png">

**Comment by Anand3595** [comment]
Hi Yasin,

Thanks for contacting Syncfusion support.

Please find the response below for your queries,

Query  | Response 
------------- | ------------- 
When I create a pdf or excel file in my grid cell, if I use a big text, the texts are getting complicated. Like in the screenshot below. Can you guys please help me about this.  | We have checked the screenshot you have shared and found that column width differs for each column and also merged cells are applied in the worksheet. Please share us the code snippet you have used to create the Excel in your side which will be helpful for us to provide you the prompt solution at earliest.
I'm struggling same issue with pdf package too.  | We have text wrapping support to preserve long text or paragraphs in single PDF grid cell. If we applied the height of the row manually or applied column’s width with horizontal overflow property, then the text is preserved only in the layout area with the provided height and width values. So, remaining text are not drawn in corresponding grid cell. Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_pdf_file-828833015 to know more details. And also we can calculate and set the height of the grid row by using “measuring a string” support with the PDF font using in corresponding grid cell. Please let us know if you need any further assistance in this, and also please share us the code snippet you have used to create the PDF in your side which will be helpful for us to provide you the prompt solution at earliest.

With Regards,
Anand Panchamoorthi

**Comment by yasinakca** [comment]
Hi, the code below is the code that I'm using for creating excel page. I'll wait for your reply. @Anand3595 
Future<void> generateExcel() async {
    //Create a Excel document.

    //Creating a workbook.
    final Workbook workbook = Workbook();
    //Accessing via index
    final Worksheet sheet = workbook.worksheets[0];
    sheet.showGridlines = false;

    // Enable calculation for worksheet.
    sheet.enableSheetCalculations();

    //Set data in the worksheet.
    sheet.getRangeByName('A1').columnWidth = 4.82;
    sheet.getRangeByName('B1:C1').columnWidth = 13.82;
    sheet.getRangeByName('D1').columnWidth = 13.20;
    sheet.getRangeByName('E1').columnWidth = 7.50;
    sheet.getRangeByName('F1').columnWidth = 9.73;
    sheet.getRangeByName('G1').columnWidth = 8.82;
    sheet.getRangeByName('H1').columnWidth = 4.46;

    sheet.getRangeByName('A1:K1').cellStyle.backColor = '#333F4F';
    sheet.getRangeByName('A1:K1').merge();
    sheet.getRangeByName('B4:D6').merge();

    sheet
        .getRangeByName('B4')
        .setText(widget.duzenlenecekRapor.raporBaslik.toUpperCase());
    sheet.getRangeByName('B4').cellStyle.fontSize = 32;

    sheet.getRangeByName('B8').setText('Konu:');
    sheet.getRangeByName('B8').cellStyle.fontSize = 9;
    sheet.getRangeByName('B8').cellStyle.bold = true;

    sheet.getRangeByName('B9').setText(widget.duzenlenecekRapor.raporKonu);
    sheet.getRangeByName('B9').cellStyle.fontSize = 12;

    /* sheet
        .getRangeByName('B10')
        .setText('United States, California, San Mateo,');
    sheet.getRangeByName('B10').cellStyle.fontSize = 9; */
    sheet.getRangeByName('B10').setText('Katılımcılar:');
    sheet.getRangeByName('B10').cellStyle.fontSize = 9;
    sheet.getRangeByName('B10').cellStyle.bold = true;

    sheet
        .getRangeByName('B11')
        .setText(widget.duzenlenecekRapor.raporKatilimci);
    sheet.getRangeByName('B11').cellStyle.fontSize = 9;

    /* sheet.getRangeByName('B12').setNumber(9365550136);
    sheet.getRangeByName('B12').cellStyle.fontSize = 9;
    sheet.getRangeByName('B12').cellStyle.hAlign = HAlignType.left; */

    final Range range1 = sheet.getRangeByName('F8:G8');
    final Range range2 = sheet.getRangeByName('F9:G9');
    final Range range3 = sheet.getRangeByName('F10:G10');
    final Range range4 = sheet.getRangeByName('F11:G11');
    final Range range5 = sheet.getRangeByName('F12:G12');

    range1.merge();
    range2.merge();
    range3.merge();
    range4.merge();
    range5.merge();

    sheet.getRangeByName('K8').setText('Oluşturan');
    range1.cellStyle.fontSize = 8;
    range1.cellStyle.bold = false;
    range1.cellStyle.hAlign = HAlignType.right;

    sheet.getRangeByName('K9').setText('widget.userName');
    range2.cellStyle.fontSize = 9;
    range2.cellStyle.hAlign = HAlignType.right;

    sheet.getRangeByName('K10').setText('Tarih');
    range3.cellStyle.fontSize = 8;
    range3.cellStyle.bold = true;
    range3.cellStyle.hAlign = HAlignType.right;

    sheet.getRangeByName('K11').dateTime = DateTime(2020, 08, 31);
    sheet.getRangeByName('K11').numberFormat =
        '[\$-x-sysdate]dddd, mmmm dd, yyyy';
    range4.cellStyle.fontSize = 9;
    range4.cellStyle.hAlign = HAlignType.right;

    range5.cellStyle.fontSize = 8;
    range5.cellStyle.bold = true;
    range5.cellStyle.hAlign = HAlignType.right;

    final Range range6 = sheet.getRangeByName('B15:G15');
    range6.cellStyle.fontSize = 10;
    range6.cellStyle.bold = true;

    sheet.getRangeByIndex(15, 2).setText('Görsel');
    int a = 16;
    for (var item in widget.x) {
      final String image = base64.encode(await yapbisiler(item.bulguImage));
      final Picture picture = sheet.pictures.addBase64(a, 2, image);
      picture.height = 50;
      picture.width = 50;
      a += 2;
    }

    /* sheet.getRangeByIndex(16, 2).setText('CA-1098');
    sheet.getRangeByIndex(17, 2).setText('LJ-0192');
    sheet.getRangeByIndex(18, 2).setText('So-B909-M');
    sheet.getRangeByIndex(19, 2).setText('FK-5136');
    sheet.getRangeByIndex(20, 2).setText('HL-U509'); */

    sheet.getRangeByIndex(15, 4).setText('Bölge');

    int b = 16;
    for (var item in widget.x) {
      sheet.getRangeByIndex(b, 4).setText(item.bolge);
      b += 2;
    }

    /* sheet.getRangeByIndex(16, 3).setText('AWC Logo Cap');
    sheet.getRangeByIndex(17, 3).setText('Long-Sleeve Logo Jersey, M');
    sheet.getRangeByIndex(18, 3).setText('Mountain Bike Socks, M');
    sheet.getRangeByIndex(19, 3).setText('ML Fork');
    sheet.getRangeByIndex(20, 3).setText('Sports-100 Helmet, Black'); */

    /* sheet.getRangeByIndex(15, 3, 15, 4).merge();
    sheet.getRangeByIndex(16, 3, 16, 4).merge();
    sheet.getRangeByIndex(17, 3, 17, 4).merge();
    sheet.getRangeByIndex(18, 3, 18, 4).merge();
    sheet.getRangeByIndex(19, 3, 19, 4).merge();
    sheet.getRangeByIndex(20, 3, 20, 4).merge(); */

    sheet.getRangeByIndex(15, 5).setText('Bulgu');
    int c = 16;
    for (var item in widget.x) {
      sheet.getRangeByIndex(c, 5).setText(item.bulgu);
      c += 2;
    }

    /* sheet.getRangeByIndex(17, 5).setNumber(3);
    sheet.getRangeByIndex(18, 5).setNumber(2);
    sheet.getRangeByIndex(19, 5).setNumber(6);
    sheet.getRangeByIndex(20, 5).setNumber(1); */

    sheet.getRangeByIndex(15, 7).setText('Mahal');
    int d = 16;
    for (var item in widget.x) {
      sheet.getRangeByIndex(d, 8).setText(item.mahal);
      d += 2;
    }

    /* sheet.getRangeByIndex(17, 6).setNumber(49.99);
    sheet.getRangeByIndex(18, 6).setNumber(9.50);
    sheet.getRangeByIndex(19, 6).setNumber(175.49);
    sheet.getRangeByIndex(20, 6).setNumber(34.99); */

    sheet.getRangeByIndex(15, 10).setText('Yer');
    int e = 16;
    for (var item in widget.x) {
      sheet.getRangeByIndex(e, 10).setText(item.yer);
      e += 2;
    }
    /* sheet.getRangeByIndex(16, 7).setFormula('=E16*F16+(E16*F16)');
    sheet.getRangeByIndex(17, 7).setFormula('=E17*F17+(E17*F17)');
    sheet.getRangeByIndex(18, 7).setFormula('=E18*F18+(E18*F18)');
    sheet.getRangeByIndex(19, 7).setFormula('=E19*F19+(E19*F19)');
    sheet.getRangeByIndex(20, 7).setFormula('=E20*F20+(E20*F20)');
    sheet.getRangeByIndex(15, 6, 20, 7).numberFormat = '\$#,##0.00'; */

    sheet.getRangeByName('E15:G15').cellStyle.hAlign = HAlignType.right;
    sheet.getRangeByName('B15:G15').cellStyle.fontSize = 10;
    sheet.getRangeByName('B15:G15').cellStyle.bold = true;
    sheet.getRangeByName('B16:G20').cellStyle.fontSize = 9;

    sheet.getRangeByName('E22:G22').merge();
    sheet.getRangeByName('E22:G22').cellStyle.hAlign = HAlignType.right;
    sheet.getRangeByName('E23:G24').merge();

    /* final Range range7 = sheet.getRangeByName('E22');
    final Range range8 = sheet.getRangeByName('E23');
    range7.setText('TOTAL');
    range7.cellStyle.fontSize = 8;
    range8.setFormula('=SUM(G16:G20)');
    range8.numberFormat = '\$#,##0.00';
    range8.cellStyle.fontSize = 24;
    range8.cellStyle.hAlign = HAlignType.right;
    range8.cellStyle.bold = true; */

    /* sheet.getRangeByIndex(26, 1).text =
        '800 Interchange Blvd, Suite 2501, Austin, TX 78721 | support@adventure-works.com';
    sheet.getRangeByIndex(26, 1).cellStyle.fontSize = 8;

    final Range range9 = sheet.getRangeByName('A26:K27');
    range9.cellStyle.backColor = '#ACB9CA';
    range9.merge();
    range9.cellStyle.hAlign = HAlignType.center;
    range9.cellStyle.vAlign = VAlignType.center; */

    //Save and launch the excel.
    final List<int> bytes = workbook.saveAsStream();
    //Dispose the document.
    workbook.dispose();

    //Get the storage folder location using path_provider package.
    final Directory directory =
        await path_provider.getApplicationDocumentsDirectory();
    final String path = directory.path;
    final File file = File('$path/raporum.xlsx');
    await file.writeAsBytes(bytes);

    //Launch the file (used open_file package)
    await open_file.OpenFile.open('$path/raporum.xlsx');
  }

**Comment by Anand3595** [comment]
Hi yasinakca ,
 
We have checked the reported issue with your code snippet and we have found compilation issues when we are trying add your code snippets in the simple application. We suspect that you are using your own widget and fill the worksheet with that widget data. We have shared the application used in our side along with the output file we have generated by commenting the compilation issue lines.
 
The sample application will be downloaded from the following link
 
Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_excel-1526407925.zip
 
Please modify this sample application to reproduce the issue and share us along with the output file which will be helpful for us to provide you the prompt solution at earliest.
 
We also suspect that the text you are setting in worksheet is larger than the column width. For this case, you can use the wrap text option to view the cell text in one cell itself.

`sheet.getRangeByName('A1').cellStyle.wrapText = true;` 

Regards,
Anand Panchamoorthi

**Comment by yasinakca** [comment]
Hey,

Sir with all the respect this code doesn't work.
