### ISSUE TITLE
Add support to add custom widget to resource view calendar

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-examples#304]
Hi,

By using resource view type of calendar we are able to display avatar along with a name. like below
![existing one](https://user-images.githubusercontent.com/16321223/111280735-384b6100-864d-11eb-87f4-b1693ad8bdee.png)

So my question is there a way to customize this left panel?, so we show a custom widget in there instead of an avatar and name. and each widget will have a unique id. Something like this
![suggested one](https://user-images.githubusercontent.com/16321223/111280424-de4a9b80-864c-11eb-97c1-83b328c6ac5d.png)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information and image, your requirement is “**Providing custom widget support for resource view in the Flutter calendar**”. We have already logged the feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   

You can also communicate with us regarding the open features at any time using our Feature Report page.    

https://www.syncfusion.com/feedback/22810/custom-widget-support-for-resource-view-in-the-flutter-calendar-sfcalendar

If you have any more specifications/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
