### ISSUE TITLE
Problem with Scrollbar in Flutter Web

### ISSUE THREAD

**Issue by patricknicolosi** [syncfusion/flutter-examples#305]
Unable to scroll with Scrollbar in Flutter Web.
The same behavior is seen on
with week view https://flutter.syncfusion.com/#/event-calendar/getting-started.

![ezgif-4-417bc57aa4c8](https://user-images.githubusercontent.com/23001470/111283943-ec45ef80-863f-11eb-9d24-9fea850fa1b9.gif)

**Comment by Indumathi1195R** [comment]
Hi,

We are able to reproduce the mentioned issue “**Unable to scroll the calendar using Scrollbar in Flutter web platform**” and we have already found and fixed the mentioned issue. We will include the mentioned issue fix in our upcoming 2021 Volume 1 release, which is expected to be rolled out by end of March 2021, and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi, 
 
We are glad to announce that our **2021 Volume 1 release (version 19.1.54)** is rolled out with the mentioned issue fix “**Unable to scroll the calendar using Scrollbar in Flutter web platform**”. Kindly update to the latest version for resolving this issue. Please find the latest version from the following link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

Regards, 
Indumathi R
