### ISSUE TITLE
Please add headers to NetworkPdf (SfPdfViewer.network constructor)

### ISSUE THREAD

**Issue by idrats** [syncfusion/flutter-examples#306]
I need to pass authorization header to the request, but unfortunately there is no such opportunity

**Comment by dillibabun** [comment]
Hi @idrats ,

Greetings from Syncfusion.

We are analyzing the feasibility of providing "Headers support for NetworkPdf" and will update the validation details by 19 March 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @idrats ,


At present we do not have support for headers while accessing PDF from network URL. Based on our present commitments, this feature is expected to be implemented in our April 2021 first weekly package release which is estimated to be available by April 6, 2021 tentatively. We will let you know when this feature is implemented.


Regards,

Dilli babu.

**Comment by idrats** [comment]
Thank you! I'm waiting for this update with patience

**Comment by dillibabun** [comment]
Hi @idrats ,

We regret for the inconvenience.

We have implemented the requested support for headers while accessing PDF from network URL. But, we were unable to include it in the first weekly release. We have planned to include the changes in our next weekly release which is estimated to be available by 13 April 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @idrats ,

We have included the headers support in NetworkPdf in the latest package - https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.56-beta 

You can also refer to our [API documentation](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.network.html). Please let us know if you have any doubts.

Regards,
Dilli babu
