### ISSUE TITLE
Edit widget in header

### ISSUE THREAD

**Issue by patricknicolosi** [syncfusion/flutter-examples#307]
How can I change the widgets circled in red?

![Cattura](https://user-images.githubusercontent.com/23001470/111331610-5925ad80-8671-11eb-9727-d3955c577bbc.PNG)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Changing the allowed view label text, navigation arrows.**

Your requirement can be achieved by using the **textAlign** property of the **CalendarHeaderStyle**, you can change the position of the navigation arrows. Header text color was used for allowed views label text, so using the color property of the **TextStyle** you can customize the allowed views label text. We have UG and KB documents for header appearance customization. Please find the UG and KB from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/headers#header-appearance

**KB link:**
https://www.syncfusion.com/kb/12247/how-to-navigate-to-the-previous-or-next-views-using-navigation-arrows-in-the-flutter-event

**Regarding Query: No selected date text customization in agenda view** 

You can customize the no-selected date text by using styles. By using the localization extendibility, you can add the required strings for allowed view labels and custom strings. We have a KB document for the same. Please find the KB document from the following link.

**KB link:**
https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-event-calendar-sfcalendar

Also using appointment builder, you can customize the appointments in the agenda view. We have KB document for the same. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-event-calendar

We hope that the above helps you. If the provided information is not sufficient, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
