### ISSUE TITLE
Latest Versions

### ISSUE THREAD

**Issue by BugsOverBugs** [syncfusion/flutter-examples#308]
Please update path_provider version of your package pdf_viewer to the latest, because your latest version is incompatible with other latest versions in the pubspec.yaml.

**Comment by dillibabun** [comment]
Hi @BugsOverBugs ,

Syncfusion Flutter PdfViewer is supported till 2.10.5 Dart SDK Version so we are unable to refer to the latest package of path_provider (^2.0.1). From 2021 Volume 1 release onwards, Syncfusion flutter PdfViewer doesn’t require path_provider as a dependence. So, we request you to use an earlier/compatible version of the package until then.

2021 Volume 1 release is estimated to be rolled out on the last week of March 2021 tentatively. We will let you know once the release is rolled out. 

Regards.
Dilli babu.

**Comment by dillibabun** [comment]
Hi @BugsOverBugs , 
  
We are glad to announce that the path_provider dependency has been removed in our widget and the changes are available from Essential Studio 2021 Volume 1 release.  
  
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
  
Regards, 
Dilli babu.

**Comment by BugsOverBugs** [comment]
Thanks a lot. Your package is the best pdf viewer!
