### ISSUE TITLE
Bar Series with Negative Values - Bar Segment Painter Issue

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-examples#31]
### Description:

This is a re-open of #25 which was closed (I can't reopen issues because I am not a collaborator on the project), but this still is an issue. Here are more details and concrete example to reproduce:

<p align="center">
<img src="https://user-images.githubusercontent.com/53703092/65292848-a5e10480-db1e-11e9-886b-9cd6c443321c.png" width="400">
</p>

As you can see from above some of the negative bars are in the wrong direction. The issue only occurs for negative values that are greater than `-1` (`Data D` and `Data E`) - but values equals less than or equal to `-1` are in the right direction (`Data C`) 

### Code To Reproduce: 

Please run this simple `main.dart` to reproduce. All the code lives within it, attached below as `txt` file:

[main.txt](https://github.com/syncfusion/flutter-examples/files/3633847/main.txt)

**Comment by dharanidharandharmasivam** [comment]
Hi @walsha2 ,

We regret for the inconvenience. We can replicate the issue at our end, and we will include the fix for the reported issue in our upcoming update. We will let you know once we have published and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @walsha2 ,

Thanks for being patience. The reported issue has been fixed, now the negative bars will be rendered in the proper direction. To resolve the reported issue, kindly upgrade your packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts 

Thanks,
Dharani.
