### ISSUE TITLE
Hours not displayed correctly in Hebrew

### ISSUE THREAD

**Issue by ronytesler** [syncfusion/flutter-examples#311]
![image](https://user-images.githubusercontent.com/9344207/111878989-67950180-89b0-11eb-9660-579f09b40ff8.png)
The numbers should appear before the text. Like in Google Calendar:
![image](https://user-images.githubusercontent.com/9344207/111879411-81cedf80-89b0-11eb-80d9-9b3bfdfe3359.png)

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are analyzing the standard of the Hebrew language to display the time text. We will analyze and update you the further details on or before March 24, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
Thanks. Sometimes we also use 24 hours format with no text. Maybe it would be nice to have an option to choose between the different formats.
example:
![image](https://user-images.githubusercontent.com/9344207/111995374-8535a880-8b21-11eb-9dd2-31dddf8d27ad.png)

Thanks.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query:  It would be nice to have an option to choose between the different formats.**

By using the timeFormat property of the timeSlotViewSettings, you can change the time formats. We have a KB and UG document. Please find the KB and UG from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/timeslot-views#time-text-formatting

**KB link:** https://www.syncfusion.com/kb/11008/how-to-customize-the-time-label-in-the-flutter-event-calendar-sfcalendar

**Regarding Query: Hours not displayed correctly in Hebrew**

We have logged the framework issue in flutter for Hebrew language time text. If we got any solution from GitHub, we will update to you. We appreciate your patience until then. Please find the GitHub issue from the following link.

**Link:** https://github.com/flutter/flutter/issues/78864

Regards,
Indumathi R

**Comment by ronytesler** [comment]
Why was it closed? Any update?
