### ISSUE TITLE
CalendarView month onViewChanged sometimes show incorrect month start end day widget

### ISSUE THREAD

**Issue by sokolej79** [syncfusion/flutter-examples#312]
flluter version: 2.0.2
syncfusion_flutter_calendar version: 18.4.48
Calendar view type: month

When swipe previous/next month on calendar, sometimes shows wrong month widget with incorrect start/end day for selected month and does not show any data. 
Data from onViewChanged  start/end is correct but widget start/end date is not.
Whent widget start/end date are incorrect and swipe next or back again on same month then it shows correct sates in widgets.

**Comment by sokolej79** [comment]
On version   syncfusion_flutter_calendar: 18.2.4 works OK  on new version problems as described above.
Working version dependencies:
  syncfusion_localizations: 18.2.48
  syncfusion_flutter_core: 18.2.48

**Comment by Indumathi1195R** [comment]
Hi ,

Based on the provided information, we have checked the mentioned issue “**Calendar show incorrect start and end date in the widget using onViewChanged callback**” from our end and it is working fine as expected from our end. We have prepared the simple sample with monthCellBuilder and printing those start and end dates in the console window and working fine as expected. Please find the sample from the following link.

**Sample and video link:** https://www.syncfusion.com/downloads/support/directtrac/320383/ze/minimum_appointmentduration-1387406311.zip

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us back with the below details. 
  
•	Issue reproducing video (if possible)  
•	Replication procedure
•	Code snippet

It will be helpful for us to check on it and provide you the solution at the earliest.  

Regards,
Indumathi R
