### ISSUE TITLE
RRule recurrence doesn't work for daily

### ISSUE THREAD

**Issue by jackiepapers** [syncfusion/flutter-examples#313]
It seems the recurrence rrule for DAILY does not work and always sets the event for the current day. WEEKLY and MONTHLY recurrence are working as expected.
Also the appointment start and end times always show the current time instead of the appointment time.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Based on the provided information, we have checked the mentioned issue “**Recurrence rule doesn’t work properly for DAILY**”. We have checked with DAILY recurrence rule and the appointment is shown in the mentioned **startTime** and **endTime** with specified recurrenceRule property. We have prepared the simple sample and video for the same. Please find the sample and video from the following link. Also, we have attached the tested code snippet for the same.

**Code snippet:**
```
appointments.add(Appointment(
  startTime: DateTime(2021,03,21,11,0,0,),
  endTime: DateTime(2021,03,21,12,0,0,),
  subject: 'Meeting',
  color: Colors.cyan,
  recurrenceRule: 'FREQ=DAILY;INTERVAL=1'
));

```
**Sample and video link:** https://www.syncfusion.com/downloads/support/directtrac/321229/ze/timeruler_calendar-534395042.zip

If possible, can you please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with the following details.

•	Replication video
•	Code snippet

It will be helpful for us to check on it and provide you solution at the earliest. 

Regards,
Indumathi R

**Comment by jackiepapers** [comment]
I hard coded in the example you provided and the event was created on the current day (March 25) rather than the date provided (March 21).

`final event = EventModel(
      startDate: DateTime(2021, 03, 21, 11, 0, 0),
      endDate: DateTime(2021, 03, 21, 12, 0, 0),
      description: _descriptionController.text.trim(),
      recurrenceRule: 'FREQ=DAILY;INTERVAL=1;COUNT=1',
      isAllDay: false,
      subject: _subjectController.text.trim(),
    );
    await eventDBS.create(event.toMap());`

Start date in database is _March 21, 2021 at 11:00:00 AM UTC-7_ but event shows up on March 25 (the date it was created).

I am not seeing this issue with WEEKLY or MONTHLY recurrence.

**Comment by jackiepapers** [comment]
After further experimentation it seems all events are using the DateTime they were created at rather than the inputed startDate. Even if there is no rrule. So it seems to be a problem with the displaying of events rather than the rrule generation.

And the appointment start and end times in the agenda view are using the current time instead of the actual appointment time.

**Comment by jackiepapers** [comment]
Never mind, it was my fault. I used the names startDate and endDate instead of startTime and endTime in my model. I changed the names and all works as expected. Thanks, BTW, for this package. It really makes recurring events a breeze.
