### ISSUE TITLE
Real-time Charts memory leak/high ram usage

### ISSUE THREAD

**Issue by JasonMorris1** [syncfusion/flutter-examples#314]
The real-time charts on the screen causes memory usage to increase until phone runs out of memory and the charts keep freezing. 
![image](https://user-images.githubusercontent.com/22126616/112557149-0347b880-8d89-11eb-8d4f-f9f3ebdc2a64.png)

**Comment by JasonMorris1** [comment]
This issue occurs when you leave the real time charts running on screen for a couple of minutes.

**Comment by rokeshkarthikeyan** [comment]
Hi JasonMorris1

Thanks for your interest in our Flutter charts. We have analyzed your scenario and we are unable to replicate the reported issue at our end. We suspect for the live chart to re-render the chart with modified data points, you might have called setState(), this renders the chart from scratch. Thus, the app’s performance will be degraded on continuous updates. To overcome this problem, the updateDataSource method can be called by passing updated data points indexes. The chart will process only that point and skip various steps like bounds calculation, old data points processing, etc. Thus, this will improve the app’s performance. We have provided a simple sample below with a live update using the updateDataSource method for your reference.

Sample: -  [issues_314_sample.zip](https://github.com/syncfusion/flutter-examples/files/6211590/issues_314_sample.zip)


More information on updateDataSource can be found below,
https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource

We suggest using the updateDataSource method for live updates. Hope this resolves your concern, If the issue still gets reproduced please revert us with your sample.

Thanks,
Rokesh Karthikeyan.

**Comment by JasonMorris1** [comment]
The problem also occurs when using the app downloaded from the playstore without any modification to the code.

**Comment by Dharanipalani** [comment]
Hi @JasonMorris1,

We have analyzed the real-time chart [sample code](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/real_time_charts/live_update/real_time_spline_chart.dart) in our SB and found that we used the **setState** for this. So, only the app crashes by running after a couple of minutes. Moreover, we checked this by changing it into using the **updateDataSource** method then it worked without crashing the app. We will change this in our sb code in the future and we suggest you use the **updateDataSource** method for the live chart. Please revert us if you have further concerns on this.

Thanks,
Dharanitharan. P
