### ISSUE TITLE
BYSETPOS=-1 is crashing app

### ISSUE THREAD

**Issue by jackiepapers** [syncfusion/flutter-examples#315]
When trying to get last day of month or last Tuesday in month the calendar appointments are not displayed and eventually app crashes.
FREQ=MONTHLY;BYMONTHDAY=-1;INTERVAL=1
FREQ=MONTHLY;BYDAY=TU;BYSETPOS=-1;INTERVAL=1

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Calendar makes crash while use BYSETPOS=-1 in recurrence rule**”. In earlier, we don’t have support for -1 value in the calendar. Now we have provided support for negative values in the Flutter event calendar.  We have implemented and include this feature in our upcoming **2021 Volume 1 release**, which is expected to be rolled out by end of March 2021 and let you know once the release rolled out. We appreciate your patience until then.

Now you can track the current status of this feature request by using the following feedback link. 

**Link:** https://www.syncfusion.com/feedback/20548/provide-negative-values-support-for-bysetpos-property-of-recurrence-rule-in-the

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi, 

We are glad to announce that our 2021 Volume 1 release (version 19.1.54) is rolled out with the mentioned feature “Provided negative values support for BYSETPOS property of recurrence rule in the Flutter event calendar”. Kindly update to the latest version for resolving this issue. Please find the latest version, release notes and changelog from the following link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

**Release notes link:**
 https://help.syncfusion.com/flutter/release-notes/v19.1.0.54?type=all#sfcalendar-features

**Changelog link:**
https://pub.dev/packages/syncfusion_flutter_calendar/changelog

Regards, 
Indumathi R

**Comment by jackiepapers** [comment]
With the latest version this works: ` FREQ=MONTHLY;BYDAY=TU;BYSETPOS=-1;INTERVAL=1` and correctly returns the last Tuesday of every month.

But this: ` FREQ=MONTHLY;BYMONTHDAY=-1;INTERVAL=1` doesn't return the last day of each month.

Neither does this: `RRULE:FREQ=MONTHLY;BYMONTHDAY=31,30,29,28;BYSETPOS=-1;INTERVAL=1`

Am I missing something or it just doesn't work?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: RecurrenceRule (FREQ=MONTHLY;BYMONTHDAY=-1;INTERVAL=1) doesn’t return the last day of each month.**

In the Flutter calendar, we have provided the negative value support for **BYSETPOS** only and there is no negative value support for **BYMONTHDAY** property. Also, kindly use the single date for the **BYMONTHDAY** property of the monthly recurrence rule.

We hope that the above information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
