### ISSUE TITLE
AppointmentBuilder Countdown Widget Not Working for SfCalendar

### ISSUE THREAD

**Issue by FatihAydin52** [syncfusion/flutter-examples#320]
I add custom widgets using the appointmentBuilder. I have a countdown area in these widgets. My countdown widget is not working in calendar display. I use the plugin mentioned below for the countdown. Would you help me with this topic?

[flutter_countdown_timer](https://pub.dev/packages/flutter_countdown_timer)

![WhatsApp Video 2021-04-01 at 00 27 27](https://user-images.githubusercontent.com/14280894/113213694-30acce80-9281-11eb-856c-a1c5ff4d212a.gif)

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are validating the issue “**Countdown widget not working properly for appointmentBuilder in the Flutter calendar**”. We will validate and update you with further details on or before April 6, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have considered this is an issue “**Countdown widget not working properly for appointmentBuilder in the Flutter Event Calendar (SfCalendar)**” and logged the bug report for the same. We will fix and include the issue fix in our upcoming weekly nuget release package, which is expected to be rolled out by April 20,2021 and let you know once the release rolled out. We appreciate your patience until then.

You can track the current status of this report by the following link,

**Link:** https://www.syncfusion.com/feedback/23993/countdown-widget-not-working-properly-for-appointmentbuilder-in-the-flutter-event

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for your patience.

We have fixed the mentioned issue “**Countdown widget not working properly for appointmentBuilder in the Flutter Event Calendar (SfCalendar)**” and included the issue fix in our latest Weekly Nuget version 19.1.57. Kindly update to the latest version resolving this issue. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
