### ISSUE TITLE
How can I upload a pdf from Flutter Web to Firebase Storage?

### ISSUE THREAD

**Issue by patricknicolosi** [syncfusion/flutter-examples#324]
I use this function:
 https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/pdf/helper/save_file_web.dart 

to generate the pdf file from Flutter Web. How can I upload the file to firebase storage?

 To upload a file I use a function similar to this:
 https://stackoverflow.com/questions/59716944/flutter-web-upload-image-file-to-firebase-storage

But the file on Firebase Storage is not readable. 
Suggestions ?

**Comment by patricknicolosi** [comment]
I solved ! Thanks 😃

**Comment by aloRanking** [comment]
Hii.please can you tell me how you fixed it?

**Comment by gadearaujo** [comment]
Where is the solution??????????
