### ISSUE TITLE
How can i check if user signed on syncfusion_flutter_signaturepad?

### ISSUE THREAD

**Issue by amaajid001** [syncfusion/flutter-examples#325]
I didnt find any option by which i can check if user signed on pad or not.

**Comment by patricknicolosi** [comment]
You can use the onSign function to check.

bool isSigned = false;

SfSignaturePad(
    onSignStart: () {
      setState(() {
        isSigned = true;
      });
    },
    backgroundColor: Colors.white,
    strokeColor: Colors.black,
    minimumStrokeWidth: 10.0,
    maximumStrokeWidth: 6.0),

**Comment by amaajid001** [comment]
Hmm Yes this will work.
Thanks.
