### ISSUE TITLE
[Calendar]: Show events from Google/iOS calendar (question)

### ISSUE THREAD

**Issue by erperejildo** [syncfusion/flutter-examples#326]
I have seen some other calendar packages like this one displaying a calendar integrated within the UI working nicely but I was wondering if it's possible to display the events from Google/iOS without using other packages like this one: https://pub.dev/packages/add_2_calendar (this forces me to leave the app).

So basically I want to create events always in the phone's calendar directly. Is that possible using this package?

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the provided information, we have checked and your requirement is “**Show events from Google in the Flutter event calendar**”. We have a KB document for this requirement. Please find the KB from the following link.

**KB link:**

https://www.syncfusion.com/kb/12116/how-to-add-google-calendar-events-to-the-flutter-event-calendar-sfcalendar

We hope that this helps you. If this is not your requirement can you please share your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by erperejildo** [comment]
Thanks for the quick response (and for the package, it looks awesome btw).

Is it also available for iOS?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: Is it also available for iOS?**

As of now, we have prepared the KB for “**Show events from Google in the Flutter event calendar**” on the android platform. We will check and update you on the further details on or before April 8, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

Currently, we are checking your requirement “**Show events from Google in the Flutter event calendar**”, it takes some time to validate this requirement in iOS. We will validate and update you with the further details on or before April 13, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by erperejildo** [comment]
No rush at all. Take you time.
Thanks

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We are checking at a technical level. We will validate and update you on the further details on or before April 16, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by erperejildo** [comment]
BTW, do you know why I'm getting this issue?
https://stackoverflow.com/questions/67136720/the-package-name-and-fingerprint-pair-you-provided-is-already-used-by-an-android/67137262?noredirect=1#comment118677250_67137262

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is it also available for iOS?**

Yes, it is possible to load the calendar events in Flutter Calendar in iOS platform. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/add-google-event-calendar-to-flutter-event-calendar-main_(2)-24937156.zip

Also kindly follow the below steps for loading the google calendar events.

**STEP 1:** Create a project in Firebase using the following link.
https://console.firebase.google.com/

**STEP 2:** Kindly follow the steps provided by the above link and configure the Firebase with your application.

**STEP 3:** Then add the Firebase to your app by using the **iOS bundle ID** (Take a bundle ID from **project.pbxproj** file of the **Runner.xcodeproj** folder in iOS project) and register the app with firebase and download the GoogleService-Info.plist.
you can refer here for the set up: https://firebase.google.com/docs/flutter/setup 

**STEP 4:** Open the Runner folder **XCode** of your project and drag and drop the **GoogleService-Info.plist**
file into that folder. 

**STEP 5:** In the Project settings of the Firebase project add the Project name and Support email and **Enable** the Google Signin and add the Project name and support email and **Save** in Authentication tab.

**STEP 6:** Also **Enable** the Google Calendar API as in the following link https://console.cloud.google.com/

We hope that the above sample helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by erperejildo** [comment]
thanks for the help. I'll have a look ASAP
