### ISSUE TITLE
SfCircularChart - data in tooltip is not always visible

### ISSUE THREAD

**Issue by zjbennycn** [syncfusion/flutter-examples#328]
Hi,
In some cases, data in tooltips are not always visible when using SfCircularChart and no exception or error occurs in my console. What does it depend on ? Are we able to make it always visible?Please find the attachments as below,thanks!

![图片](https://user-images.githubusercontent.com/3417647/113863120-d9a47d80-97db-11eb-98ba-567a762273d0.png)
![图片](https://user-images.githubusercontent.com/3417647/113863138-e1642200-97db-11eb-86c0-d8e711d37f79.png)

**Comment by zjbennycn** [comment]
Below is my pie chart core codes,no matter I get data from Interface or hardcode the percentage data,the data (numbers in pie chart) will sometimes be disappeared when user refresh the page or trigger another Action in menu bar.I have been working on this problem for several days,I wonder if anyone can help.Thank you very much!

///Get the default circular series with legend
SfCircularChart _getLegendDefaultChart() {
  return SfCircularChart(
    series: _getLegendDefaultSeries(),
    tooltipBehavior: TooltipBehavior(enable: false),
    centerX: (MediaQuery.of(context).size.width * 0.3).toStringAsFixed(0),
  );
}

///Get the default circular series
List<DoughnutSeries<ChartSampleData, String>> _getLegendDefaultSeries() {
  if (chartSexData != null) {
    for (int i = chartSexData.length - 1; i >= 0; i--) {
      if (chartSexData[i].y.round() == 0) {
        chartSexData.removeAt(i);
      }
    }
  }
  return <DoughnutSeries<ChartSampleData, String>>[
    DoughnutSeries<ChartSampleData, String>(
      dataSource: chartSexData,
      innerRadius: '40%',
      pointColorMapper: (ChartSampleData data, _) => data.pointColor,
      xValueMapper: (ChartSampleData data, _) => data.x,
      yValueMapper: (ChartSampleData data, _) => data.y,
      startAngle: 0,
      endAngle: 0,
      radius: '100%',
      dataLabelSettings: DataLabelSettings(
          isVisible: true,
          labelPosition: ChartDataLabelPosition.inside,
          builder: (dynamic data, dynamic point, dynamic series,
              int pointIndex, int seriesIndex) {
            return Text(data.y.toString() + "%",
                style: TextStyle(
                  color: Color.fromARGB(255, 255, 255, 255),
                  fontSize: 22,
                ));
          },
          connectorLineSettings: ConnectorLineSettings(
            length: "20%",
            width: 3.5,
          )),
    ),
  ];
}

**Comment by Dharanipalani** [comment]
Hi @zjbennycn,

Greetings from Syncfusion. We have analyzed your query and we find some contradictions between your query and the given code snippet. 

**Query:** data in tooltips are not always visible

But in the given code snippet, you disable the tooltip. So, we suspect that you are facing issues in the data labels from the given screenshots and hence we run your code snippet but unfortunately we cannot replicate the issue. All data labels are rendered properly, so please share more information about the issue like the platform you are facing the issue, and in which cases you are facing this issue. This information will help us to investigate and give you the solution sooner.

Thanks,
Dharanitharan. P
