### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by yasinakca** [syncfusion/flutter-examples#329]
Hey, 

When add an image to my grid cell, even tough I gave credentials via image_picker like max width and max height my images comes to the pdf like quite annormaly. Can you guys please help? 

Here is the screenshot:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-07 at 21 49 29](https://user-images.githubusercontent.com/15368330/113919044-ce594e00-97eb-11eb-9117-665403fd5fb2.png)

Here is my code:

Future<void> generateInvoice() async {
    //Create a PDF document.
    PdfDocument document = PdfDocument();
    //Add page to the PDF
    PdfPage page = document.pages.add();
    //Get page client size
    Size pageSize = page.getClientSize();
    //Draw rectangle
    page.graphics.drawRectangle(
      bounds: Rect.fromLTWH(0, 0, pageSize.width, pageSize.height),
      pen: PdfPen(
        PdfColor(142, 170, 219, 255),
      ),
    );
    //Generate PDF grid.
    PdfGrid grid = await getGrid();
    //Draw the header section by creating text element
    PdfLayoutResult result = await drawHeader(page, pageSize, grid);
    //Draw grid
    await drawGrid(page, grid, result);
    //Add invoice footer
    await drawFooter(page, pageSize);
    //Save and launch the document
    List<int> bytes = document.save();
    //Dispose the document.
    document.dispose();
    //Get the storage folder location using path_provider package.
    Directory directory =
        await path_provider.getApplicationDocumentsDirectory();
    String path = directory.path;
    File file = File('$path/output.pdf');
    await file.writeAsBytes(bytes);
    //Launch the file (used open_file package)
    await open_file.OpenFile.open('$path/output.pdf');
  }

  //Draws the invoice header
  Future drawHeader(PdfPage page, Size pageSize, PdfGrid grid) async {
    PdfFont font = PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
    //Draw rectangle
    page.graphics.drawRectangle(
      brush: PdfSolidBrush(
        PdfColor(91, 126, 215, 255),
      ),
      bounds: Rect.fromLTWH(0, 0, pageSize.width - 115, 90),
    );
    //Draw string
    page.graphics.drawString(
      widget.duzenlenecekRapor.raporBaslik.toUpperCase(),
      font,
      brush: PdfBrushes.white,
      bounds: Rect.fromLTWH(25, 0, pageSize.width - 115, 90),
      format: PdfStringFormat(
        lineAlignment: PdfVerticalAlignment.middle,
      ),
    );

    page.graphics.drawRectangle(
      bounds: Rect.fromLTWH(400, 0, pageSize.width - 400, 90),
      brush: PdfSolidBrush(
        PdfColor(65, 104, 205),
      ),
    );

    /* page.graphics.drawString('\$' + getTotalAmount(grid).toString(),
        PdfStandardFont(PdfFontFamily.helvetica, 18),
        bounds: Rect.fromLTWH(400, 0, pageSize.width - 400, 100),
        brush: PdfBrushes.white,
        format: PdfStringFormat(
            alignment: PdfTextAlignment.center,
            lineAlignment: PdfVerticalAlignment.middle)); */

    //Draw string
    /* page.graphics.drawString(
      'Amount',
      font,
      brush: PdfBrushes.white,
      bounds: Rect.fromLTWH(400, 0, pageSize.width - 400, 33),
      format: PdfStringFormat(
        alignment: PdfTextAlignment.center,
        lineAlignment: PdfVerticalAlignment.bottom,
      ),
    ); */

    PdfImage image = PdfBitmap(
      await yapbisiler(widget.duzenlenecekRapor.raporImage),
    );
    page.graphics.drawImage(
      image,
      Rect.fromLTWH(400, 0, pageSize.width - 100, 90),
    );

    //Create data foramt and convert it to text.
    final DateFormat format = DateFormat.yMMMMd('en_US');
    String invoiceNumber =
        'Katılımcı ${widget.duzenlenecekRapor.raporKatilimci}\r\n\r\nTarih: ' +
            format.format(DateTime.now());
    final Size contentSize = font.measureString(invoiceNumber);
    String address =
        '''Rapor konu: ${widget.duzenlenecekRapor.raporBaslik.toUpperCase()}
        \r\n\r\nHazırlayan:  ${widget.duzenlenecekRapor.raporBaslik}''';

    PdfTextElement(text: invoiceNumber, font: font).draw(
      page: page,
      bounds: Rect.fromLTWH(
        pageSize.width - (contentSize.width + 30),
        120,
        contentSize.width + 30,
        pageSize.height - 120,
      ),
    );

    return PdfTextElement(text: address, font: font).draw(
      page: page,
      bounds: Rect.fromLTWH(
        30,
        120,
        pageSize.width - (contentSize.width + 30),
        pageSize.height - 120,
      ),
    );
  }

  //Draws the grid
  Future<void> drawGrid(
      PdfPage page, PdfGrid grid, PdfLayoutResult result) async {
    Rect totalPriceCellBounds;
    Rect quantityCellBounds;
    //Invoke the beginCellLayout event.
    grid.beginCellLayout = (Object sender, PdfGridBeginCellLayoutArgs args) {
      final PdfGrid grid = sender as PdfGrid;
      if (args.cellIndex == grid.columns.count - 1) {
        totalPriceCellBounds = args.bounds;
      } else if (args.cellIndex == grid.columns.count - 2) {
        quantityCellBounds = args.bounds;
      }
    };
    //Draw the PDF grid and get the result.
    result = grid.draw(
      page: page,
      bounds: Rect.fromLTWH(0, result.bounds.bottom + 40, 0, 0),
    );

    PdfFont font = PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
    //Draw grand total.
    /* page.graphics.drawString(
      'Grand Total',
      font,
      bounds: Rect.fromLTWH(
        quantityCellBounds.left,
        result.bounds.bottom + 10,
        quantityCellBounds.width,
        quantityCellBounds.height,
      ),
    ); */
    /* page.graphics.drawString(
      getTotalAmount(grid).toString(),
      PdfStandardFont(PdfFontFamily.helvetica, 9, style: PdfFontStyle.bold),
      bounds: Rect.fromLTWH(
        totalPriceCellBounds.left,
        result.bounds.bottom + 10,
        totalPriceCellBounds.width,
        totalPriceCellBounds.height,
      ),
    ); */
  }

  //Draw the invoice footer data.
  Future<void> drawFooter(PdfPage page, Size pageSize) async {
    PdfFont font = PdfTrueTypeFont(await _readData('NotoSans-Regular.ttf'), 12);
    final PdfPen linePen = PdfPen(
      PdfColor(142, 170, 219, 255),
      dashStyle: PdfDashStyle.custom,
    );
    linePen.dashPattern = <double>[3, 3];
    //Draw line
    page.graphics.drawLine(
      linePen,
      Offset(0, pageSize.height - 100),
      Offset(pageSize.width, pageSize.height - 100),
    );

    /* const String footerContent =
        '''800 Interchange Blvd.\r\n\r\nSuite 2501, Austin,
         TX 78721\r\n\r\nAny Questions? support@adventure-works.com'''; */

    //Added 30 as a margin for the layout
    /* page.graphics.drawString(
      footerContent,
      font,
      format: PdfStringFormat(alignment: PdfTextAlignment.right),
      bounds: Rect.fromLTWH(pageSize.width - 30, pageSize.height - 70, 0, 0),
    ); */
  }

  //Create PDF grid and return
  Future getGrid() async {
    //Create a PDF grid
    final PdfGrid grid = PdfGrid();
    //Secify the columns count to the grid.
    grid.columns.add(count: 5);
    //Create the header row of the grid.
    final PdfGridRow headerRow = grid.headers.add(1)[0];
    //Set style
    headerRow.style.backgroundBrush = PdfSolidBrush(PdfColor(68, 114, 196));
    headerRow.style.textBrush = PdfBrushes.white;
    headerRow.cells[0].value = 'Görsel';
    headerRow.cells[0].stringFormat.alignment = PdfTextAlignment.center;
    headerRow.cells[1].value = 'Bulgu';
    headerRow.cells[2].value = 'Bölge';
    headerRow.cells[3].value = 'Yer';
    headerRow.cells[4].value = 'Mahal';

    for (var item in widget.x) {
      await addProducts(
          item.bulguImage, item.bulgu, item.mahal, item.yer, item.bolge, grid);
    }
    //Add rows
    /* addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid);
    addProducts('CA-1098', 'AWC Logo Cap', '8.99', '2', '17.98', grid); */
    //Apply the table built-in style
    grid.applyBuiltInStyle(PdfGridBuiltInStyle.listTable4Accent5);
    //Set gird columns width
    grid.columns[1].width = 200;
    for (int i = 0; i < headerRow.cells.count; i++) {
      headerRow.cells[i].style.cellPadding =
          PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
    }
    for (int i = 0; i < grid.rows.count; i++) {
      final PdfGridRow row = grid.rows[i];
      for (int j = 0; j < row.cells.count; j++) {
        final PdfGridCell cell = row.cells[j];
        if (j == 0) {
          cell.stringFormat.alignment = PdfTextAlignment.center;
        }
        cell.style.cellPadding =
            PdfPaddings(bottom: 5, left: 5, right: 5, top: 5);
      }
    }
    return grid;
  }

  //Create and row for the grid.
  Future<void> addProducts(String productId, String productName, String price,
      String quantity, String total, PdfGrid grid) async {
    final PdfGridRow row = grid.rows.add();
    row.cells[0].value = PdfBitmap(await yapbisiler(productId));
    row.cells[1].value = productName;
    row.cells[2].value = price;
    row.cells[3].value = quantity;
    row.cells[4].value = total;
  }

  Future<List<int>> _readData(String name) async {
    final ByteData data = await rootBundle.load('asset/fonts/$name');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

  Future<List<int>> yapbisiler(String url) async {
    var response = Utility.dataFromBase64String(url);
    return response;
  }

**Comment by Anand3595** [comment]
Hi Yasin,
 
Thanks for contacting Syncfusion support.
 
By default, The largest height of the grid cells is takes as height of the corresponding grid row. But, the default width is sets as the average of grid’s width. So, the image in your sample is looks like abnormal.
 
We can set the height of the row by using _**PdfGridRow.height**_ property to draw the image properly. Or else we can use _**PdfGrid.beginCellLayout**_ callback to calculate the height of the image cell based on the width and height ratio of the image. Please find the sample code below,

> //Begin cell layout event to calculate and set image's height based on the cell width
> grid.beginCellLayout = (Object sender, PdfGridBeginCellLayoutArgs args) {
>   //Get grid instance
>   final PdfGrid grid = sender as PdfGrid;
>   if (args.cellIndex == 0) {
>     //Get grid row
>     PdfGridRow row = grid.rows[args.rowIndex];
>     //Get grid cell
>     PdfGridCell cell = row.cells[args.cellIndex];
>     //Get corresponding cell which is having image as a value
>     if (cell.value is PdfBitmap) {
>       //Get cell value as PdfBitmap instance
>       PdfBitmap value = cell.value as PdfBitmap;
>       //Get grid columns
>       PdfGridColumn column = grid.columns[args.cellIndex];
>       //Calculate new height based on the width changes
>       **row.height = (value.height / value.width) * column.width;**
>     }
>   }
> };

Please find the workable sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_pdf603758289.
 
With Regards,
Anand Panchamoorthi

**Comment by yasinakca** [comment]
Sir, it works just fine when I take a picture to fill the grid. But when I select an image gallery it still looks abnormal. Can you help with that issue? 
Like this.
![Screenshot_20210410-145432_Drive](https://user-images.githubusercontent.com/15368330/114268967-c9271980-9a0c-11eb-941c-715a22dab00f.jpg)

**Comment by Anand3595** [comment]
Hi Yasin,

We can calculate and set height for all the grid cells by using _PdfGrid.beginCellLayout_ callback. We suspect the height for the some of the cell is not applied. We can access all the cells in PdfGrid before layout by _isHeaderRow, cellIndex_ and _rowIndex_ properties in _PdfGridBeginCellLayoutArgs_ class and set height as we explained before. Please ensure to set height for all the cells which have images.

And also, we are requesting you to provide the simple sample to reproduce the reporting issue and to validate further in our side. It would more helpful for us to analyze further and provide you a prompt solution.

With Regards,
Anand Panchamoorthi
