### ISSUE TITLE
Half doughnut chart is occupying the entire circle space 

### ISSUE THREAD

**Issue by jasnicaa** [syncfusion/flutter-examples#331]
Hi, thanks for the library.

I've noticed something with the half doughnut chart. When I put it in the column above another widget I am not able to put something let's say 20px below because below itself it occupies as much space as above. You can see it in the image. Is this how it suppose to work? 

Thanks

![Screenshot_20210408-160114](https://user-images.githubusercontent.com/25682164/114041328-beda1380-9884-11eb-87f0-295ed41921af.jpg)

**Comment by Dharanipalani** [comment]
Hi @jasnicaa,

Greetings from Syncfsuion. We have analyzed your query and would like to tell you that we render the chart based on the width and height aspect ratio. By default, it renders by taking the minimum value by comparing the width and height, and moreover for you can draw any half-circle or quarter circle, the radius is calculated by taking the full width and height of the chart and it renders by scaling it. If you want to avoid the space, you can use the set the **radius** property as 100 and also use **centerY** property to position the doughnut and we attached the sample for your reference, kindly make use of it.

Sample: [half_doughnut.zip](https://github.com/syncfusion/flutter-examples/files/6284540/half_doughnut.zip)

Thanks,
Dharanitharan. P

**Comment by jasnicaa** [comment]
Thanks for the answer and example. However I am still not getting the result this is my code for the half chart and I've done everything that you've mentioned and still getting this offset at the bottom. I was trying to overcome that by setting negative padding on the listView above with transform but that is not the right solution for listView.

This is my code

`SfCircularChart(
          centerY: '150',
          margin: const EdgeInsets.fromLTRB(0, 0, 0, 0),
          annotations: <CircularChartAnnotation>[
            CircularChartAnnotation(
                widget: Padding(
                  padding: EdgeInsets.only(top: 20),
                  child: Container(
                    width: 150,
                    height: 150,
                    child: Column(
                      children: <Widget>[
                        Text(
                          state.balance.toStringAsFixed(2),
                          style: CustomTextStyles.fieldValueHighlightTopazLarge,
                        ),
                        const Text(
                          'CHF',
                          style: CustomTextStyles.greyInk,
                        )
                      ],
                    ),
                  ),
                ),
                angle: 90,
                horizontalAlignment: ChartAlignment.center,
                verticalAlignment: ChartAlignment.center),
          ],
          series: <CircularSeries>[
            DoughnutSeries<GaugeSegment, String>(
                dataSource: [
                  GaugeSegment('Owe me', state.oweMe, CustomColors.topaz),
                  GaugeSegment('Owing', state.iOwe, CustomColors.orangy),
                ],
                xValueMapper: (GaugeSegment data, _) => data.x,
                yValueMapper: (GaugeSegment data, _) => data.y,
                pointColorMapper: (GaugeSegment data, _) => data.color,
                startAngle: 270,
                radius: "100%",
                endAngle: 90,
                innerRadius: '70%')
          ],
        );`

**Comment by jasnicaa** [comment]
I decided not to handle with pie size so I laid out my widgets into Stack and handle sizes with Positioned widget. Thanks anyway
