### ISSUE TITLE
SfPdfViewer does not display pdfs

### ISSUE THREAD

**Issue by BugsOverBugs** [syncfusion/flutter-examples#332]
Hey Syncfusion,

I tested your `SfPdfViewer` by copying your example into a new Flutter project. There it works as expected.
But when I want to use it in my excisting project it's loading the pdf and after finishing the pdf is not displayed. I tried `.network()` and `.asset()`: the issue occures in both widgets. There is no console message.

I hope you can help me or fix it as soon as possible.

**Comment by amitsingh6391** [comment]
@BugsOverBugs The same issue in my case

**Comment by dillibabun** [comment]
Hi @BugsOverBugs / @amitsingh6391 

Greetings from Syncfusion.

We request you to share the following details to reproduce the reported issue from our side.
       1. flutter SDK version. - run flutter doctor command.
       2. SfPdfViewer pub version.
       3. Platform (android, ios, or web) in which issue is reproduced.
       4. Simple project in which issue is reproduced.  

This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by BugsOverBugs** [comment]
Of course @dillibabun:

1.) 
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.867], locale de-DE)
    • Flutter version 2.0.4 at D:\Tom\flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Pixel 3a (mobile) • 9AGAY1DFUJ • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
Process finished with exit code 0

2.) `syncfusion_flutter_pdfviewer: ^19.1.55-beta`

3.) Android

4.) 
Did I understand you right? - My mobile app should open the pdf as `.assest()` if the file is already downloaded. Otherwise Iít opens `SfPdfViewer.network()`.

If something is missing please ask for it.

**Comment by dillibabun** [comment]
Hi @BugsOverBugs ,

Thanks for the update. 

We tried to reproduce the reported issue with provided details but the sample is working fine at our end. Please find the sample link below [here](https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1546265260).

Kindly modify the sample to reproduce the issue and share us the same, which will be helpful for us to investigate further on this.

Regards,
Dilli babu.

**Comment by BugsOverBugs** [comment]
@dillibabun I spend so much to locate the issue. The following method disables the possiblity to show the pdfs:

`Future<void> _deleteCacheDir() async {
final cacheDir = await getTemporaryDirectory();
if (cacheDir.existsSync()) {
cacheDir.deleteSync(recursive: true);
}
}`

Thank you for spending time to solve the issue even I did it alone :-)
Maybe you can specifiy this in the README at pub.dev.

**Comment by dillibabun** [comment]
Hi @BugsOverBugs,

We glad to know that you have resolved the issue at your end. We need a few more clarifications on the mentioned codes. Kindly share us the purpose of using _deleteCacheDir method in your application. Please let us know what kind of information you are expecting us to update in readme file.

Regards,
Dilli babu.

Regards,
Dilli babu.

**Comment by BugsOverBugs** [comment]
I used the method to clear the cache after the app is opened (in `initState() `of `MaterialApp()` page like `MyApp()` of the Flutter demo app).
The usage is necessary because your pdf viewer saves everything in the cache. This causes a storage of hundreds of MBs which aren't used anymore. 
The usage of the method in `dispose()` does not work.

**Comment by dillibabun** [comment]
Hi @BugsOverBugs ,

As requested earlier, kindly let us know what kind of information you are expecting us to update in readme file.

Regards,
Dilli babu.

**Comment by BugsOverBugs** [comment]
Oh, I am sure you know what you could write. Maybe something like "The SfPdfViewer needs the app's cache. So never delete it before you want to display a pdf with it."

Is it possible for you to implement horizontal swipe and single page view? The SfPdfViewer has some difficulties with lager page sizes caused by scannned images...
