### ISSUE TITLE
Size between cells.

### ISSUE THREAD

**Issue by ViniciusCdeAlmeida** [syncfusion/flutter-examples#333]
Hi, it's possible to change the height between texts inside or change the size of the cells?

![image](https://user-images.githubusercontent.com/4376963/115442727-b967bc00-a1e8-11eb-9553-cf8078d18ef7.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: It's possible to change the height between texts inside or change the size of the cells?**

We regret to inform you that as per the current implementation Flutter calendar does not have support to change the height of the cells in month view.

Regards,  
Indumathi R

**Comment by jigarfumakiya** [comment]
Any update on this?
