### ISSUE TITLE
DatePicker blackout dates click event handle

### ISSUE THREAD

**Issue by egeysn** [syncfusion/flutter-examples#336]
In my app i want to show different bottom sheet when user clicks to blackout events so need to catch this click event.
I looked for a solution but i guess library not supporting this can you help me? [video link](https://streamable.com/h3bc03)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked, and your requirement is “**Show the bottom sheet for when blackout dates tap in the Flutter date range picker**”. Flutter date range picker doesn’t have touch interaction support for blackout dates. So, you are not allowed to interact with the blackout dates to show the bottom sheet. However, by using the special dates decoration, you can change UI appearance as blackout dates, and you can show the bottom sheet. We have prepared a simple sample and video for the same. Please find the sample and video from the following link.

**Sample and video link:**
[minimum_appointmentduration.zip](https://github.com/syncfusion/flutter-examples/files/6376796/minimum_appointmentduration.zip)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
