### ISSUE TITLE
remove issue with controller

### ISSUE THREAD

**Issue by rezaUniqe** [syncfusion/flutter-examples#337]
hi I try to remove a date from the selected date but when I select a new date  that removed date also  shows on calendar
![image](https://user-images.githubusercontent.com/47690060/115962633-95caab80-a531-11eb-9d7c-83411f7506ff.png)
in this image, I removed 3 dates but when I tried to a selected a new date that removed part automatically returns.

my remove function:
 _controller.selectedDates.removeAt(index);

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue **“Removed selected automatically added, when new date is selected from picker**”.  Flutter date range picker doesn’t support for remove() function. However you can achieve your requirement,  by cloning the selected dates list and remove from that list value and assign back it to the **selectedDates** of the **DateRangePickerController**. 

You can refer to the following code snippet.

```
final DateRangePickerController _controller = DateRangePickerController();
final List<DateTime> _selectedDates = <DateTime>[
  DateTime.now().add(Duration(days: 1)),
  DateTime.now().add(Duration(days: 2)),
  DateTime.now().add(Duration(days: 3)),
  DateTime.now().add(Duration(days: 4))
];

void initState() {
  _controller.selectedDates = _selectedDates;
  super.initState();
}

body: SafeArea(
    child: Column(
  children: [
    TextButton(
        onPressed: () {
          List<DateTime> newList = _controller.selectedDates!.sublist(0);
          newList.removeAt(3);
          _controller.selectedDates = newList;
        },
        child: Text('Remove')),
    SfDateRangePicker(
      controller: _controller,
      selectionMode: DateRangePickerSelectionMode.multiple,
    )
  ],
)),
```
**Video link:**
[video.zip](https://github.com/syncfusion/flutter-examples/files/6376222/video.zip)

Please let us know if you would require further assistance.

Regards,
Indumathi R
