### ISSUE TITLE
Timezone dependency incompatible

### ISSUE THREAD

**Issue by jackiepapers** [syncfusion/flutter-examples#338]
I get this error trying to install flutter_local_notifications:
`SLVR:   conflict: syncfusion_flutter_calendar 19.1.57 depends on timezone 0.7.0-nullsafety.0
SLVR:   ! not timezone 0.7.0-nullsafety.0 is satisfied by timezone ^0.7.0
SLVR:   ! which is caused by "flutter_local_notifications >=5.0.0+1 depends on timezone ^0.7.0"
SLVR:   ! thus: syncfusion_flutter_calendar 19.1.57 is incompatible with flutter_local_notifications >=5.0.0+1
SLVR:   ! flutter_local_notifications >=5.0.0+1 is satisfied by flutter_local_notifications 5.0.0+1`

Timezone ^0.7.0 is a stable null-safety version so i hope you can fix this in next release.

**Comment by Indumathi1195R** [comment]
Hi,

We have already fixed the mentioned issue “**Timezone dependency incompatible issue in the Flutter calendar**”. We will include the issue fix in our upcoming Weekly Nuget package, which is expected to be rolled out by May 4, 2021 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the issue fix for “**Timezone dependency incompatible issue in the Flutter calendar**” in our latest Weekly Nuget package **version 19.1.59** and kindly update to the latest version for this issue fix. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
