### ISSUE TITLE
In Invoice PDF when data goes to another page , How can I set total at the end of that new page ?

### ISSUE THREAD

**Issue by PriyankManiya** [syncfusion/flutter-examples#339]
**Hope you understand my point after watching this example..**

[Invoice.pdf](https://github.com/syncfusion/flutter-examples/files/6409018/Invoice.pdf)

**Comment by PriyankManiya** [comment]
[Invoice.pdf](https://github.com/syncfusion/flutter-examples/files/6409015/Invoice.pdf)

**Hope you understand my point after watching this example..**

**Comment by Anand3595** [comment]
Hi Priyank Maniya,

Thanks for contacting Syncfusion support.

Syncfusion PDF provides the rendered bounds for each and every element added through PdfLayoutResult objects. It also contains a page object with successive update of pagination while drawing the element. This can be used to add successive elements and prevent content overlap.

We can draw the summary and footer with a new page created in grid pagination by using PdfLayoutResult. Please find the more details in https://help.syncfusion.com/flutter/pdf/getting-started#creating-a-simple-pdf-document-with-basic-elements.

> //Draws the grid to the PDF page
> **PdfLayoutResult gridResult** = grid.draw(page: page, bounds: Rect.fromLTWH(0, result.bounds.bottom + 20, graphics.clientSize.width, graphics.clientSize.height - 100), format: layoutFormat)!;

> **gridResult.page**.graphics.drawString( 'Grand Total :                             \$386.91', subHeadingFont, brush: PdfSolidBrush(PdfColor(126, 155, 203)), bounds: Rect.fromLTWH(520, gridResult.bounds.bottom + 30, 0, 0));

> **gridResult.page**.graphics.drawString('Thank you for your business !', subHeadingFont, brush: PdfBrushes.black, bounds: Rect.fromLTWH(520, gridResult.bounds.bottom + 60, 0, 0));

And also find the simple sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_pdf_file-1671606185 to draw summary and footer based on the grid pagination.

Please let us know, if you need any further assistance in this.

Regards,
Anand Panchamoorthi
