### ISSUE TITLE
Selection zooming area

### ISSUE THREAD

**Issue by Azzeccagarbugli** [syncfusion/flutter-examples#341]
Hi everybody!

I'm trying to figure out how to customize some labels and lines that pop out **while the selection area is grabbed** but I can't understand if it's possibile first of all or I'm simply missing something in the documentation. 

Specifically I'm talking about these objects:

![Screenshot 2021-05-05 at 14 47 31](https://user-images.githubusercontent.com/16477661/117144236-fbc8f580-adb1-11eb-9697-ff8498f6a45a.png)

I started from this [example](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/user_interactions/zooming_and_panning/selection_zooming.dart)

Thank you in advance for the support 👋

**Comment by Dharanipalani** [comment]
Hi @Azzeccagarbugli,

Thanks for the interest in our Flutter charts. We have analyzed your query and the screenshot and like to share you the following code snippets and screen shot for customizing tooltip and selection zooming rectangle for your reference.

To customize the tooltip, use the [interactiveTooltip](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interactiveTooltip.html) property in the respective axis as like below,

` 
primaryXAxis: NumericAxis(interactiveTooltip: const InteractiveTooltip(color: Colors.red, borderColor: Colors.green, borderWidth: 2)),
`

To customize the selection zooming rectangle, use the [selectionRectColor](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/selectionRectColor.html), [selectionRectBorderColor](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/selectionRectBorderColor.html) and [selectionRectBorderWidth](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/selectionRectBorderWidth.html) properties in the [zoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/zoomPanBehavior.html) of the chart as like below,

`
ZoomPanBehavior(
 selectionRectColor: Colors.red,
 selectionRectBorderColor: Colors.green,
 selectionRectBorderWidth: 2,
 enableSelectionZooming: isSelectionZooming
);
`

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/117270559-f71a4500-ae76-11eb-843a-d3c560f991bb.png)

Thanks,
Dharanitharan. P

**Comment by Azzeccagarbugli** [comment]
Perfect, exactly what I was looking for 🚀

**Comment by Dharanipalani** [comment]
Hi @Azzeccagarbugli,

Most welcome and kindly revert us if you need further assistance on this and we are always happy on assisting you.

Thanks,
Dharanitharan. P
