### ISSUE TITLE
Problem with selection in SfCircularChart

### ISSUE THREAD

**Issue by jstnw10** [syncfusion/flutter-examples#343]
Hey there!

I would like to know when a section gets unselected in a PieChart. The onSelectionChanged works fine when a section gets selected but it wont trigger the callback if I unselect a section. I thought I could use onPointTapped as an alternative way to check if a previous selected section gets unselected but onPointTapped has a huge delay between tap and triggering the callback (why?) and it does not notice all kind of taps (I think it depends on the selection gesture but i can not use multiple gestures right now). My series has explode set to true and I can not find a way to trigger any callback the same way the explode features behaves. 

Can you add an unselected callback or a way to capture unselection in onSelectionChanged?

Thanks

**Comment by jstnw10** [comment]
also, is there a way to explode sections while using a SelectionBehaviour? `selectionBehaviour.selectDataPoints(index)` does not explode any section

**Comment by Dharanipalani** [comment]
Hi @jstnw10,

We've looked into the scenario and were able to reproduce the problem. We will include the fix in the next patch update, which is set to be released on May 18, 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by dharanidharandharmasivam** [comment]
Hi @jstnw10 ,

Thanks for being patience. We are glad to let you know that the reported issue got fixed and the release has been rolled out with the reported bug fix. To resolve the issue, kindly upgrade to the latest version of the chart package from below.

**Pub:** https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.64 

Thanks,
Dharani.
