### ISSUE TITLE
SfCalendar show date picker on tap.

### ISSUE THREAD

**Issue by sami79031** [syncfusion/flutter-examples#345]
Thanks for the great library.!

I recently started implementing the Calendar. I went through the documentation and the examples.
I'm trying to achieve a custom header and on tap to present the date picker.
Currently, I'm only able to use `showDatePickerButton: true`, but I'd love to be able to call it from a custom header as well. 
Could you please let me know if there is a way of achieving that?

Best,
Sami

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: I'd love to be able to call it from a custom header as well.
Could you please let me know if there is a way of achieving that?**

Based on the provided information, we have checked and your requirement is “**To show the date picker by tapping the custom header in the Flutter Calendar**” and your requirement can be achieved by using the alert dialog window for showing the SfDateRangePicker. We have prepared the simple sample and video for the same. Please find the sample from the following link.

**Sample and video link:** 
[header-customization-calendar-flutter-master (1).zip](https://github.com/syncfusion/flutter-examples/files/6472136/header-customization-calendar-flutter-master.1.zip)

We hope that this helps you. If possible, can you please share your requirement to show the picker while tapping custom header? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by sami79031** [comment]
This is exactly what I needed! Thanks a lot.
So, my requirement is to have the calendar date that behaves just as the default header, but I also need to add some extra filters to the same header. I'm attaching an image to better show you what exactly I mean by that.

<img width="550" alt="Screen Shot 2021-05-13 at 2 57 36 PM" src="https://user-images.githubusercontent.com/9218154/118122544-ad43d880-b3fb-11eb-946a-87a7e176a15b.png">

Best,
Sami

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Based on the shared information, we have changed UI as per the attached image and shown the date range picker via Filter by Facility text also. We have provided this UI with the default headers and you can add the required widgets above the default headers. Please find the sample from the following link.

**Sample link:**
[header-customization-calendar-flutter-master.zip](https://github.com/syncfusion/flutter-examples/files/6478425/header-customization-calendar-flutter-master.zip)

If possible, can you please share the below details,

•	Adding extra filter in default header (or) 
•	Adding extra filter in the custom header

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R

**Comment by sami79031** [comment]
Hi again,

Just didn't want to open a new issue, so I'll ask my question here.
Is there a way to remove the `todayIcon` from the header?
Check out the image below.

![Screenshot 2021-05-20 at 15 29 01](https://user-images.githubusercontent.com/9218154/118979449-2786d680-b981-11eb-96c3-20b0d7acdd0c.png)


Thanks a lot!
