### ISSUE TITLE
Flutter PDF Library (Decryption is Failing)

### ISSUE THREAD

**Issue by TheArchitect123** [syncfusion/flutter-examples#346]
I'm using the Syncfusion PDF Library for a recent flutter project.

I have a feature where a user imports a document from another app through an intent. The application then generates a new instance of PdfDocument class, and decrypts the file through the use of symmetric encryption. The key to decrypt is entered by the user.

According to the documentation: 

https://www.syncfusion.com/blogs/post/how-to-encrypt-and-decrypt-pdf-files-in-flutter.aspx

to decrypt the file I'm writing:

        PdfDocument pdfDocument = PdfDocument(
            inputBytes: File(documentFilePath).readAsBytesSync(),
            password: passcode);

I remove the passcode protection within the file, then I create a temporary file, which the app then uses. The problem is whenever I do this, I end up with this exception:

type '_ "GrowableList<" int>' is not a subtype of type 'Uint8List'

I've tried casting the Uint8List into a List<int> so that the types match exactly, however it all fails.

**Comment by chinnumuniyappan** [comment]
Hi @TheArchitect123 ,

We have tried to reproduce the reported issues on our end with test PDF documents. But we are not able to reproduce the reported issue on our end and we suspect the issue may depend on the specific PDF document. So we request you to provide the input PDF file along with the password and complete code example to reproduce the issue on our end. It would more helpful for us to analyze further and update you with a prompt solution.

We have attached the code which we tried on our end for your reference.

```dart 
Future<void> decryptPDF() async {
    //Load the PDF document with permission password.
    PdfDocument document = PdfDocument(
        inputBytes: await _readDocumentData('secured.pdf'),
        password: 'owner@123');
    //Get the document security.
    PdfSecurity security = document.security;
    //Set owner and user passwords are empty string.
    security.userPassword = '';
    security.ownerPassword = '';
    //Clear the security permissions.
    security.permissions.clear();
    //Save and dispose the document.
    List<int> bytes = document.save();
    document.dispose();
    //Get the external storage directory
    Directory directory = (await getExternalStorageDirectory())!;
    //Get the directory path
    String path = directory.path;
    //Create an empty file to write the PDF data
    File file = File('$path/output.pdf');
    //Write the PDF data
    await file.writeAsBytes(bytes, flush: true);
    //Open the PDF document in mobile
    OpenFile.open('$path/output.pdf');
  }
```

```dart
  Future<List<int>> _readDocumentData(String name) async {
    final ByteData data = await rootBundle.load('assets/$name');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }
```
Regards, 
Chinnu M

**Comment by dgerchcovich** [comment]
Hi @chinnumuniyappan,

I've solved the issue.
Thanks for getting back to me.
