### ISSUE TITLE
Week number in `SfCalendar`

### ISSUE THREAD

**Issue by essarn** [syncfusion/flutter-examples#347]
Is it possible to show the week number like in Google Calendar?

**Comment by Indumathi1195R** [comment]
Hi,

We have already considered and logged the feature request for “**Provide a support to show week number in the month view of the Flutter Calendar**”. We will implement this in our upcoming 2021 Volume 2 release, which is expected to be rolled out by end of June 2021, and let you know once the release rolled out. We appreciate your patience until then.

Now you can track the current status of this feature request by using the following feedback link. 

**Link:** https://www.syncfusion.com/feedback/25354/provide-a-support-to-show-week-number-in-the-month-view-of-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by essarn** [comment]
Thanks @Indumathi1195R for creating the feature request. 
I have implemented a temporary solution but looking forward to it being supported officially.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. We will update you once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We are glad to announce that our **2021 Volume 2 release version 19.2.44** is rolled out with the mentioned feature “**Provide a support to show week number in the month view of the Flutter Calendar**”. Kindly update to the latest version for this feature.

Please find the changelog and release notes from the following link.

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v19.2.0.44?type=all#sfcalendar-features

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_calendar/changelog

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
