### ISSUE TITLE
Syncfusion PDF Library - unicode font based drawString is resulting in kind of swapping

### ISSUE THREAD

**Issue by vshanthamoorthi** [syncfusion/flutter-examples#348]
I'm using the Syncfusion PDF Library for a recent flutter project.

i have followed the following documentation, https://help.syncfusion.com/flutter/pdf/working-with-text

i am trying to print the unicode text 'அலைபேசி எண்   : ' , but i am not seeing same text in PDF. refer to attached output.pdf file

Following are single char and it should be as below. they are getting swapped when its gets drawn.

லை
பே

Following two functions are used in my sample APP.

static Future<PdfFont> getFont(TextStyle style) async {
    //Get the external storage directory
    Directory directory = await getApplicationSupportDirectory();
    //Create an empty file to write the font data
    File file = File('${directory.path}/${style.fontFamily}.ttf');
    List<int> fontBytes;
    //Check if entity with the path exists
    if (file.existsSync()) {
      fontBytes = await file.readAsBytes();
    }
    if (fontBytes != null && fontBytes.isNotEmpty) {
      //Return the google font
      return PdfTrueTypeFont(fontBytes, 6);
    } else {
      //Return the default font
      return PdfStandardFont(PdfFontFamily.helvetica, 6);
    }
  }

  static Future<void> generatePdf() async {

    PdfDocument document = PdfDocument();
    final page = document.pages.add();

    PdfFont font = await getFont(GoogleFonts.kavivanar());

    page.graphics.drawString(
        'அலைபேசி எண்   : ' , font,
        brush: PdfBrushes.black, bounds: Rect.fromLTWH(70, 100, 150, 150));

    List<int> bytes = document.save();
    document.dispose();

    saveAndLaunchFile(bytes, 'Output.pdf');

}

[Output.pdf](https://github.com/syncfusion/flutter-examples/files/6489722/Output.pdf)

**Comment by chinnumuniyappan** [comment]
Hi @vshanthamoorthi 

Thank you for contacting Syncfusion support.

At present, we do not have support to draw complex script language texts such as Tamil, Hindi, and more. We have already logged the feature for “**Complex script text drawing support in Flutter PDF**” and added to our feature request list. We do not have any immediate plans to implement this feature. We usually have an interval of at least three months between releases and at the planning stage for every release cycle, we review all open features. We will consider this feature and update the details once it is implemented.       
 
You can track the feature status using the feedback from https://www.syncfusion.com/feedback/20541/complex-script-text-drawing-support-in-flutter-pdf  .

Regards, 
Chinnu M

**Comment by vshanthamoorthi** [comment]
Okay, thanks for quick response.

i tried to take a look at the https://pub.dev/packages/pdf

followed the TrueType font "Kavivanar-Regular" and seeing the same issue.

does Syncfusion PDF lib is based on https://pub.dev/packages/pdf or independent?

if it depends on this, then issue could be from this pdf package itself.

**Comment by chinnumuniyappan** [comment]
Hi @vshanthamoorthi ,

No, the [syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf) is not depend on the pdf package. The [syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf) library written natively in Dart for creating, reading, editing, and securing PDF files in the Flutter platform. It supports Flutter mobile, web, and desktop platforms. Please refer to the following FT and pub.dev link for more details.

FT: [https://www.syncfusion.com/flutter-widgets/pdf-library](https://www.syncfusion.com/flutter-widgets/pdf-library) 
UG: [https://help.syncfusion.com/flutter/pdf/overview ](https://help.syncfusion.com/flutter/pdf/overview )
pub.dev: [https://pub.dev/packages/syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf)  

As we said earlier, the complex script text is rendered properly once we provide the support. You can track the feature status using the feedback from https://www.syncfusion.com/feedback/20541/complex-script-text-drawing-support-in-flutter-pdf .

Regards,   
Chinnu M
