### ISSUE TITLE
How to disable localization support on sfcalendar

### ISSUE THREAD

**Issue by mnarsely** [syncfusion/flutter-examples#349]
Hey, I want to have only have English as a default to my calendar but I can't find to overcome it, can someone help me out.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: I want to have only have English as a default to my calendar but I can't find to overcome it.**

Based on the shared information, we have checked the reported query “To disable the other locale in the Flutter Calendar” from our end. We suggest you to kindly specify the English language only in the supported locales. Please find the attached code snippet for the same.

**Code snippet:**
```
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        SfGlobalLocalizations.delegate,
 
      ],
      **supportedLocales: [
        const Locale('en'), 
      ],**
      locale: const Locale('en'),
```
We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by mnarsely** [comment]
Hello, Thanks for your response, it works but I was referring on a situation where we store a language in a variable that switches whenever a user changes a language, how can you override the calendar to only display with english language (en_US)

localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        SfGlobalLocalizations.delegate,
 
      ],
      **supportedLocales: [
        const Locale('en'), 
        conat Locale('es),
      ],**
      locale: _locale,

**Comment by mnarsely** [comment]
Hello, I found a solution to this, It seems that there is a widget in flutter that helps overriding locale on other widgets.

Here is the solution 

`Localizations.override(
                    context: context,
                    locale: Locale('en'),
                          child: SfCalendar(..`
