### ISSUE TITLE
Some problem with android

### ISSUE THREAD

**Issue by Hopheylalal** [syncfusion/flutter-examples#350]
Hi. I run this code
if (fileExt == 'pdf') {
          try{
            final PdfDocument document =
            PdfDocument(inputBytes: await _readDocumentData(filePath));
            pdfPageCount = document.pages.count;
            print('pdf!!! - $pdfPageCount');
          }catch(e){
            print(e);
            return;
          }

        }
on IOS everything is good, but on android i have this error 

D/FilePickerDelegate(19277): File path:[com.mr.flutter.plugin.filepicker.FileInfo@c2b999a]
I/flutter (19277): Unable to load asset: /data/user/0/com.startforfireprint.startforfireprint/cache/file_picker/coding-with-flutter-layout-cheat-sheet-v1.0.pdf

**Comment by chinnumuniyappan** [comment]
Hi @Hopheylalal 

We have tried to reproduce the reported issue on our end. But the sample is working as expected. We request you to provide the following details. It would more helpful for us to analyze further and update you.

1. Flutter doctor -v command details.
2. Android SDK version.
3. Share the code for the _readDocumentData.
4. We have created a sample and attached it for your reference, Kindly try this on your end and modify the same to reproduce the issue.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample-1084705232 

Regards, 
Chinnu M

**Comment by Hopheylalal** [comment]
alexander@MacBook-Air-Alexander startforfireprint % flutter doctor -v command details.
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale ru-RU)
    • Flutter version 2.0.6 at /Users/alexander/documents/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/alexander/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Redmi 5 (mobile) • 3e2706b57cf5 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
____________________________
My code:

Future<List<int>> _readDocumentData(file) async {
    final ByteData data = await rootBundle.load('$file');
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

  Future pickFile() async {
    try {
      FilePickerResult result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: [...FileWidgetHelper().ext],
      );
      if (result != null) {
        File file = File(result.files.single.path);
        fileName = result.files.single.name;
        fileSize = result.files.single.size;
        fileExt = result.files.single.extension;
        filePath = result.files.single.path;

        if (fileExt == 'pdf') {
          try{
            final PdfDocument document =
            PdfDocument(inputBytes: await _readDocumentData(filePath));
            pdfPageCount = document.pages.count;
            print('pdf!!! - $pdfPageCount');
          }catch(e){
            print(e);
          }

        }
      }}}

**Comment by chinnumuniyappan** [comment]
Hi @Hopheylalal ,

Thanks for the details.

We found that you are trying to read the local file using [rootBundle ](https://api.flutter.dev/flutter/services/rootBundle.html). The rootBundle is only used to read the resource of the application. So we have modified the sample to read the local file. Kindly try the below code on your end and let us know whether it is suitable for your requirement.

**Solution 1:** The [file_picker](https://pub.dev/packages/file_picker) itself has a property to read the data for the local file. We can use it directly as stated as follows.

1. Enable the **widthData** argument.
```dart
FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom, allowedExtensions: ['pdf'], withData: true);
```

2. Read the bytes using **bytes** property.

```dart
PdfDocument document =
            PdfDocument(inputBytes: result.files.single.bytes);
```
The complete code is 

```dart
Future pickFile() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom, allowedExtensions: ['pdf'], withData: true);
    if (result != null) {
      String fileExt = result.files.single.extension!;

      if (fileExt == 'pdf') {
        PdfDocument document =
            PdfDocument(inputBytes: result.files.single.bytes);
        int pdfPageCount = document.pages.count;
        print('pdf!!! - $pdfPageCount');
      }
    }
  }
```

**Solution 2:** Or else we can use the **dart:io** to get the data from the file as follows.

1. Import the dart:io package.
```dart
import 'dart:io';
```
2. Add the following code read file from local.
```dart
Future pickFile() async {
    FilePickerResult? result = await FilePicker.platform
        .pickFiles(type: FileType.custom, allowedExtensions: ['pdf']);
    if (result != null) {
      String fileExt = result.files.single.extension!;

      if (fileExt == 'pdf') {
        PdfDocument document = PdfDocument(
            inputBytes: File(result.files.single.path!).readAsBytesSync());
        int pdfPageCount = document.pages.count;
        print('pdf!!! - $pdfPageCount');
      }
    }
  }
```

Regards, 
Chinnu M

**Comment by Hopheylalal** [comment]
Yes. It is work. Thank you very much.

**Comment by Hopheylalal** [comment]
Do you have some tools to convert docx files to pdf?

**Comment by chinnumuniyappan** [comment]
Hi @Hopheylalal ,

We glad to know the issue has been resolved. Currently, we do not have support to convert the docx files to PDF in Flutter.

Regards,  
Chinnu M
