### ISSUE TITLE
How change the range color with dynamically color.

### ISSUE THREAD

**Issue by egeysn** [syncfusion/flutter-examples#351]
I want customizing the my calendar. I'm using  to date picker with multiple range but i want multiple range with dynamic color and user cannot change the date picker. I'am not sure  can i use date picker or event calendar. Can you help me? This is all I want [link](https://ibb.co/F6gw7RL).

**Comment by Indumathi1195R** [comment]
Hi @egeysn,

Based on the shared information and image, we have checked the reported query “**Different colors for multiple range selection in the Flutter Date Range Picker**” from our end. We regret to inform you that as per the current implementation of the picker, does not have support to this feature.

We have different color options for Start, End and Range selection color. You can check the following UG documentation for your reference.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/customizations#selection-cell-customization

Regards,
Indumathi R

**Comment by sobhan15** [comment]
same issue
