### ISSUE TITLE
Classic chart inside the gauge annotation  

### ISSUE THREAD

**Issue by Azzeccagarbugli** [syncfusion/flutter-examples#353]
As I mentioned in the title of the issue I would like to place a classic chart inside the gauge annotation. 

However, unfortunately, I'm not able to do this properly even if I clip the annotation widget in a `ClipOval` to cut the extra overwhelming parts. 

Here I show you a little preview of what I mean:

Actual             |  Expected
:-------------------------:|:-------------------------:
<img width="242" alt="Screenshot 2021-05-21 at 11 26 37" src="https://user-images.githubusercontent.com/16477661/119115597-a2a2c800-ba27-11eb-8edb-aebef6dd69cc.png"> |  <img width="242" alt="Screenshot s2021-05-21 at 11 26 37" src="https://user-images.githubusercontent.com/16477661/119116644-ba2e8080-ba28-11eb-80df-cd4a31bd8907.png">

And this is the code for the annotation:

```dart
 annotations: <GaugeAnnotation>[
    GaugeAnnotation(
      angle: 180,
      widget: ClipOval(
        child: buildStepAreaChart(),
      ),
    ),
]
```

I really hope to find a solution as soon as possible!

Thanks a lot in advance 🙏🏻

**Comment by MeikandaNayanar** [comment]
Hi @Azzeccagarbugli,

We have checked your requirements and prepared a sample for you. We wrapped the chart widget as a child of a container widget and provided a required height and width. Please find the sample from the below link.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/gauge_annotation-1189164270.zip

Example Code Snippet :

annotations: <GaugeAnnotation>[ 
    GaugeAnnotation(
      widget: ClipOval(
        child: Container(
          width: 320,
          height: 320,
          child: buildStepAreaChart(),
        ),
      ),
    ),
]

Please let us know if you have any concerns about this.

Thanks
Meikandan

**Comment by Azzeccagarbugli** [comment]
Thanks @MeikandaNayanar for the answer.

```dart
annotations: [
  GaugeAnnotation(
    widget: ClipOval(
      child: Container(
      width: 320, // <--- Fixed size
      height: 320, // <--- Fixed size
      child: buildStepAreaChart(),
      ),
   ),
]
```
Simply using your solution will not update the UI properly because the size of the container is fixed and, as I said in my original post, some content will overlap the gauge itself.

There should be a possibility in the `GaugeAnnotation` that would let the user perfectly fit the center of the gauge without that any part goes outside the border.

Thanks again 🙏🏻

**Comment by MeikandaNayanar** [comment]
Hi @Azzeccagarbugli ,

Thank you for the details. 

As we do have any direct support to achieve this requirement, we have logged a feature request in our portal. For tracking this feature, please check the below feedback link,

Link: https://www.syncfusion.com/feedback/25858/

We will prioritize the features every release based on the demands and we do not have an immediate plan to implement this feature. So, this feature will be available for any of our upcoming releases. 

Please let us know if you need any further assistance in this.

Thanks,
Meikandan
