### ISSUE TITLE
How to Merge two pdf using file path.

### ISSUE THREAD

**Issue by Tapasm1212** [syncfusion/flutter-examples#354]
I want to merge two pdf files using the file paths in a flutter. How I can achieve that? 

I have found this link [https://help.syncfusion.com/file-formats/pdf/merge-documents?cs-save-lang=1&cs-lang=csharp](url) but there has no option for flutter.

Please suggest to me if you guys have any idea on this. 

Thanks in advance.

**Comment by chinnumuniyappan** [comment]
Hi @Tapasm1212 ,

Greetings from Syncfusion.

At present we do not have support to merge PDF documents in Flutter. We have added it to our feature request list and it will be implemented in any of our upcoming releases. 

**Feedback link:** https://www.syncfusion.com/feedback/25644/add-support-to-merge-pdf-documents 

However, we can create a new PDF document by creating an existing PDF page as a template. We have shared the code to create the existing PDF page as a template and draw to the new PDF page for your reference.

```dart
  //Load the PDF document.
  PdfDocument document =
      PdfDocument(inputBytes: File('pdf_succinctly.pdf').readAsBytesSync());
      //Create new PDF document.
  PdfDocument newDocument = PdfDocument();

  for (int i = 0; i < document.pages.count; i++) {
    //Get the existing PDF page.
    PdfPage page = document.pages[i];
    //Add section
    PdfSection section = newDocument.sections!.add();
    //Set margin and page size.
    section.pageSettings.margins.all = 0;
    section.pageSettings.size = page.size;
    //Create new PDF page.
    PdfPage newPage = section.pages.add();
    //Create exisitng page as template.
    PdfTemplate template = page.createTemplate();
    //Draw the template to new PDF page.
    newPage.graphics.drawPdfTemplate(template, Offset(0, 0));
  }

  //Save and dispose the documents.
  List<int> bytes = newDocument.save();
  document.dispose();
  newDocument.dispose();

  File('output.pdf').writeAsBytesSync(bytes);
```

Regards,  
Chinnu M
