### ISSUE TITLE
syncfusion_flutter_calendar web release

### ISSUE THREAD

**Issue by asenthilkumarr** [syncfusion/flutter-examples#355]
I am using syncfusion_flutter_calendar: ^18.4.49 appointment is showing, but I upgrade package to syncfusion_flutter_calendar 19.1.65 web debug mode can see but web release cannot show appointment
![calendar_error](https://user-images.githubusercontent.com/41473603/119438137-2963e780-bd3d-11eb-8f10-552da341c2e8.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “Unbale to see the appointments in the web with 19.1.65 version” and we are unable to reproduce the mentioned issue from our end and it is working fine as expected from our end. We have attached the tested image for the same.

**Screenshot:**
 
![Screenshot (151)](https://user-images.githubusercontent.com/54974849/119486663-1faaa600-bd76-11eb-9ff5-2e18138942f3.png)

If possible, can you please share the below details to us,

•	Replication procedure
•	Code snippets
 
It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by asenthilkumarr** [comment]
Hello,

I have attached my code, this code works in debug mode, but release to IIS
appointment cannot be seen.

Release command as below :
flutter build web --release --web-renderer html

Regards
Senthil

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We have checked the mentioned issue “**Appointment text is not shown SfCalendar in web renderer**”. The issue occurred while running the sample using an **HTML renderer** and it is not suitable for performance. So, we suggest you use the **CanvasKit** option for prioritizing the performance and pixel-perfect consistency. 

**Link:** 
https://flutter.dev/docs/development/tools/web-renderers 
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/staticcontent/mimemap 

Also, kindly mention the MIME type as text/xml and File name extension as .tzf while using release mode. Please find the screenshot for the same.

<img width="499" alt="Screenshot (157)" src="https://user-images.githubusercontent.com/54974849/120186878-b7eed200-c231-11eb-9082-fbec68bc4f99.png">

We hope that this helps you. Please let us know if you need further assistance. 

Regards,
Indumathi R
