### ISSUE TITLE
Date Picker on Scedule View doesn't work

### ISSUE THREAD

**Issue by johnstef99** [syncfusion/flutter-examples#356]
When picking a day from next week, the calendar jumps to today. That only happening in `CalendarView.schedule`. I tried the CalendarView.day with the same data, and it's working fine.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “**Picked date from date picker doesn’t work for schedule view**” and it is working fine as expected from our end. We have prepared the simple sample for the same. Please find the sample and video from the following link.

**Sample and video link:**
[Sample.zip](https://github.com/syncfusion/flutter-examples/files/6560885/Sample.zip)

We hope that this helps you. If possible, can you please modify the sample based on your scenario and revert us back with the following details.

•	Replication video
•	Replication procedure
•	Code snippet

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are validating the issue “**Picked date from date picker doesn’t work for schedule view**”. We will validate and update you on the further details on or before June 2, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have already found and fixed the mentioned issue “**Picked date from date picker doesn’t work for schedule view**” and we will include the issue fix in our upcoming Weekly Nuget release, which is expected to be rolled out on June 8, 2021 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have fixed the mentioned issue “**Picked date from date picker doesn’t work for schedule view**” and included the issue fix in our latest Weekly Nuget package **version 19.1.67**. Kindly update to the latest version for resolving this issue. Also please find the latest version from the following link,

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by johnstef99** [comment]
Nice I can confirm is working as expected! Thanks a lot 😄
