### ISSUE TITLE
Is pdfviewer support pdf with password?

### ISSUE THREAD

**Issue by zhouhao27** [syncfusion/flutter-examples#360]
I'm wondering if syncfusion pdfviewer supports pdf with password? Thanks.

**Comment by dillibabun** [comment]
Hi @zhouhao27 ,

At present we do not have support for “loading encrypted PDF document” in SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. 
Based on our present commitments and the above parameters, this feature is expected to be implemented on or before our 2021 Volume 4 main release. We will let you know when this feature is implemented. The status of this feature can be tracked using the following link. 
[https://www.syncfusion.com/feedback/25194/support-for-loading-encrypted-pdf-documents](https://www.syncfusion.com/feedback/25194/support-for-loading-encrypted-pdf-documents) 
Disclaimer: The date for the feature implementation is tentative and not a commitment on our part. 

Regards,
Dilli babu.

**Comment by deepika134** [comment]
Hi @zhouhao27 , 

We have included the requested feature “Loading encrypted PDF documents in SfPdfViewer” in our latest volume 4 release, so kindly upgrade to the latest version.    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.38-beta 

We are glad to announce that our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,  
Deepika Ravi
