### ISSUE TITLE
Syncfusion (Saving PDF Document) is extremely slow for large documents

### ISSUE THREAD

**Issue by TheArchitect123** [syncfusion/flutter-examples#363]
using the Syncfusion PDF Library, when encrypting a document, and running the save function is extremely slow.
Also, it's not a good idea to load a large array of bytes into memory. 
Are there any plans for adding a new method to simply pass in a url string resource, instead of the bytes.
This is how I'm doing it, and it lags for documents (greater than 5 pages) long.

```
  PdfDocument document = PdfDocument(inputBytes: fileData);  // fileData is the byte array from a different file
  String pdfName = "sample_filePath.pdf"
  await File(pdfName).writeAllBytes(document.save());  // when calling save(), application freezes.
```

**Comment by Anand3595** [comment]
Hi Dan Gerchcovich,

Thanks for contacting Syncfusion support.

We do not have direct support to load PDF from URL. We can load and read PDF data by using http package. We have created a sample to read the PDF data from webspace/website and load, encrypt and save it using the retrieved PDF data. Kindly try the following code example and sample in your side,

1-	Add http package in dependencies section of pubspec.yaml file

> dependencies:
>   http: ^0.13.3

2-	Import the following package in your dart file.
> import 'package:http/http.dart' show get;

3-	Get PDF data
> //Load PDF from website/webspace
> var url =
    "https://www.syncfusion.com/downloads/support/directtrac/general/pd/pdf_succinctly406491418";
> var response = await get(Uri.parse(url));
> var data = response.bodyBytes;

4-	Load PDF data, encrypt and save
> //Create a new PDF document
> PdfDocument document = PdfDocument(inputBytes: data);
> //Specifies encryption algorithm and key size
> document.security.algorithm = PdfEncryptionAlgorithm.aesx256Bit;
> //Set owner and user password
> document.security.ownerPassword = 'ownerPassword';
> document.security.userPassword = 'userPassword';
> //Save PDF document
> final List<int> bytes = document.save();
> //Dispose the document.
> document.dispose();

Sample : https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample2022734613

At the time of encryption, we are parsing all the document objects and encrypted it. So it will take some amount of time to parse all the objects and encrypt it. However, we are request the input PDF files to reproduce the reported issue, seems this to be document specific issue. it would more helpful for us to analyze further in our end.

With Regards,
Anand Panchamoorthi

**Comment by dgerchcovich** [comment]
Hi,

By closing this issue, I'm assuming that this was fixed. 
Because I was told by support, that the fixes for this issue will be released on the 22nd of June.

Please take a look at the issue here:
https://www.syncfusion.com/support/directtrac/incidents/330891

**Comment by dgerchcovich** [comment]
@JayavigneshwaranG
