### ISSUE TITLE
syncfusion_flutter_datepicker: ^19.1.66-beta

### ISSUE THREAD

**Issue by ylrs** [syncfusion/flutter-examples#365]
![image](https://user-images.githubusercontent.com/3962127/121015560-b8f1a780-c7cd-11eb-8eff-cac5e08a04b4.png)

![image](https://user-images.githubusercontent.com/3962127/121015817-ff470680-c7cd-11eb-8fc2-d019245aedbe.png)

 dayFormat: 'E',

为什么展示的是周一，而不是一呢

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Based on the shared images, we have checked the mentioned issue “Locale was not showing properly with dayFormat in SfDateRangePicker”. Based on the Flutter framework, we have implemented this for SfDateRangePicker control. Also, we have attached the code snippets for the Framework widget with localization and SfDateRangePicker. It shows the same output.

Code snippet:
```
supportedLocales: [
  const Locale('en'),
  const Locale('zh'),
  const Locale('he'),
  const Locale('ru'),
  const Locale('fr', 'BE'),
  const Locale('fr', 'CA'),
  const Locale('ja'),
  const Locale('de'),
  const Locale('hi'),
  const Locale('ar'),
],
locale: const Locale('zh'),

SfDateRangePicker(
  controller: _controller,
  view: DateRangePickerView.month,
  selectionMode: DateRangePickerSelectionMode.range,
  monthViewSettings: DateRangePickerMonthViewSettings(dayFormat: 'E', ),
)

```

```
child: Text( new DateFormat('E','zh').format(
 DateTime.now().add(Duration(days: -1))
),
```

**Screenshots:**
![vidma_recorder_08062021_151809 1](https://user-images.githubusercontent.com/54974849/121176205-92894600-c879-11eb-8194-f19696bff80a.jpg)

![vidma_recorder_08062021_151904 1](https://user-images.githubusercontent.com/54974849/121178491-29570200-c87c-11eb-895e-b60af97f0e6c.jpg)

![Screenshot (175)](https://user-images.githubusercontent.com/54974849/121178568-3e339580-c87c-11eb-8815-71b755cba7c5.png)

We hope that this helps you. Please let us know if you need further assistance on this.

Regards,
Indumathi R

**Comment by ylrs** [comment]
Thank you,  但是我怎么才能在日历头部 显示 ” 一 “  而不是  ”周一“ 呢  ？

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Kindly use the **dayFormat** property as the below code snippet. We have checked with the framework while using the dayFormat property as **EEEEE**, it shows **Mon**. We have attached the code snippet for the same.

Please find the code snippet for the same.

Code snippet:

```
SfDateRangePicker(
  controller: _controller,
  view: DateRangePickerView.month,
  selectionMode: DateRangePickerSelectionMode.range,
  monthViewSettings: DateRangePickerMonthViewSettings(dayFormat: 'EEEEE',),
)

```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
