### ISSUE TITLE
All example cannot run [A value of type 'dynamic' can't be assigned to a variable of type 'xxxxxx?'.]

### ISSUE THREAD

**Issue by WingCH** [syncfusion/flutter-examples#370]
For example:
![image](https://user-images.githubusercontent.com/19588517/121625592-5555cb80-caa6-11eb-965c-e96ffa14f39f.png)
![image](https://user-images.githubusercontent.com/19588517/121625674-7cac9880-caa6-11eb-9b1c-32d260cd49b6.png)

**Comment by Dharanipalani** [comment]
Hi @WingCH,

Thanks for the interest in our Flutter widgets. We have analyzed your query and would like to tell you that any user-defined type cannot be assigned as dynamic. We need to cast to its corresponding type to avoid the specified issue. For example, in the above specified calendar you can cast the tapped appointment details into **Appointment** will resolves the issue. Similarly, in the charts, the **xValueMapper** is of type **String** and so assigning dynamic will throws error and it can be resolved by casting into the type of **String**.

```
if (calendarTapDetails.appointments != null &&
  calendarTapDetails.targetElement == CalendarElement.appointment) {
  final dynamic appointment =calendarTapDetails.appointments![0];
  if(appointment is Appointment)
    {
    _selectedAppointment = appointment;
    }
  }
```

```
xValueMapper: (ChartSampleData data, _) => data.x as String,
yValueMapper: (ChartSampleData data, _) => data.y,

```

Similarly, for all other widgets casting to its appropriate type will resolve this issue.

Please revert us if you need any further assistance.

Thanks,
Dharanitharan. P
