### ISSUE TITLE
Add padding to rtl

### ISSUE THREAD

**Issue by ronytesler** [syncfusion/flutter-examples#371]
In ltr there's a small padding (see first cell in the image below).
Can you please add a similar padding for rtl?
![image](https://user-images.githubusercontent.com/9344207/121788234-6c92d700-cbd4-11eb-9ba4-9e846214c28b.png)

**Comment by Dharanipalani** [comment]
Hi @ronytesler,

Thank you for your interest in our Flutter charts. We have investigated your query and are not sure which widget you are having trouble with. Please share additional information about this issue so that we can give you a solution sooner.

Thanks,
Dharanitharan. P

**Comment by ronytesler** [comment]
Right, sorry. It's from the Calendar.

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the mentioned issue “**Padding issue occurred for appointment text while set text direction as RTL in SfCalendar**”. We will include the issue fix in our upcoming 2021 Volume 2 release, which is expected to be rolled out by end of June 2021, and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We are glad to announce that our **2021 Volume 2 release version 19.2.44** is rolled out with the mentioned issue fix “**Padding issue occurred for appointment text while set text direction as RTL in SfCalendar**”. Kindly update to the latest version for resolving this issue.

Please find the latest version from the following link.
**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
