### ISSUE TITLE
NOT WORKED (

### ISSUE THREAD

**Issue by Se7enstars** [syncfusion/flutter-examples#374]
Did all as instruction but 4K error!
did **flutter pub get**
same problem!
exculion not worked for me

**Comment by Dharanipalani** [comment]
Hi @Se7enstars,

Sorry for the inconvenience. We have now changed and merged the modifications, now please take a pull and check and it should no longer throw any errors or warnings. Please contact us if you require any additional assistance.

Thanks,
Dharanitharan. P

**Comment by anonymousprogrammers-1984** [comment]
@Se7enstars  Bruh same with me, I m also truing to add pdf to my app but not worth mine is showing 4k errors too. Tried Kinda like 10 different packages if you may find please inform here :)

**Comment by Dharanipalani** [comment]
Hi @anonymousprogrammers-1984,

We regret the inconvenience. Now, please take a pull and check and it should not throw any errors or warnings.

Thanks,
Dharanitharan. P

**Comment by Se7enstars** [comment]
> Hi @anonymousprogrammers-1984,
> 
> We regret the inconvenience. Now, please take a pull and check and it should not throw any errors or warnings.
> 
> Thanks,
> Dharanitharan. P

@Dharanitharani - Bro 99% fixed but some errors left! It say that some files not exist, try check it.
Screenshot attached >> 
![image](https://user-images.githubusercontent.com/20016371/122657520-a25c3080-d17d-11eb-8b12-a3b383a682fb.png)

**Comment by Se7enstars** [comment]
> @Se7enstars Bruh same with me, I m also trying to add pdf to my app but not worth mine is showing 4k errors too. Tried Kinda like 10 different packages if you may find please inform here :)

Worked for me after 
again git clone this repository
remove 2 files in pdf viewer
and comments those file at sample list
(look for screenshot)
![image](https://user-images.githubusercontent.com/20016371/122657915-fc122a00-d180-11eb-90ad-35e4f2b4e229.png)

**Comment by Dharanipalani** [comment]
Hi @Se7enstars / @anonymousprogrammers-1984,

Sorry for the inconvenience and now we have merged the modifications. Please take a pull and check and it should not throw any errors.

Thanks,
Dharanitharan. P

**Comment by Se7enstars** [comment]
it's good now it need work! because some files now also exist! 
Thanks for support.
