### ISSUE TITLE
Calendar - Months names appear in English.

### ISSUE THREAD

**Issue by ronytesler** [syncfusion/flutter-examples#378]
For small browser in desktop, the text on the images are in English:
![image](https://user-images.githubusercontent.com/9344207/122643588-4233a300-d119-11eb-8e72-e06539ddda47.png)

For mobile, one month is in Hebrew, one in English:
![image](https://user-images.githubusercontent.com/9344207/122643637-9179d380-d119-11eb-91cd-ca87c0a13055.png)

**Comment by ronytesler** [comment]
By the way, how do I remove from the "Schedule" view dates that don't have any events?
Also, how can I change the text "No events" to something else in Hebrew?

**Comment by Indumathi1195R** [comment]
Hi ronytesler,

**Regarding Query: the text on the images are in English**

Based on the shared information, we have checked mentioned issue “**The text on the images are in English**”. In the shared image you have used custom builder for month header of the schedule view. So, the specified text in the builder was applied. Kindly use that text with required localization for resolving this issue. Please find the code snippet for the same.

**Code snippet:**
```
Widget scheduleViewHeaderBuilder(
    BuildContext buildContext, ScheduleViewMonthHeaderDetails details) {
  final String monthName = _getMonthName(details.date.month);
  return Stack(
    children: [
      Image(
          image: ExactAssetImage('images/' + monthName + '.png'),
          fit: BoxFit.cover,
          width: details.bounds.width,
          height: details.bounds.height),
      Positioned(
        left: 55,
        right: 0,
        top: 20,
        bottom: 0,
        child: Text(
       DateFormat('MMMM yyyy', 'he').format(details.date).toString(),
          style: TextStyle(fontSize: 18),
        ),
      )
    ],
  );
}
```

**Screenshot:**

<img width="426" alt="localization" src="https://user-images.githubusercontent.com/54974849/122723707-e4c26200-d290-11eb-9c3b-eb52d2fac141.png">

**Regarding Query: how do I remove from the "Schedule" view dates that don't have any events?**

By using the hideEmptyScheduleWeek property of the scheduleViewSettings you can hide the weeks doesn’t have an appointment. Also please find the UG link for the same.

**UG link:**
https://help.syncfusion.com/flutter/calendar/schedule-view#hide-empty-weeks

**Regarding Query: how can I change the text "No events" to something else in Hebrew?**

By using the extendibility options, you can override the required keyword. We have a KB document for the same. Please find the KB from the following link.

**KB link:** https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
I tried to add scheduleViewSettings: ScheduleViewSettings(hideEmptyScheduleWeek: true) but I see no difference:
Why in large view I don't see empty weeks and I don't see images and in small view I see both?

![image](https://user-images.githubusercontent.com/9344207/122820443-48c24600-d2e4-11eb-860b-cfe40891720e.png)

![image](https://user-images.githubusercontent.com/9344207/122820516-5ed00680-d2e4-11eb-82e5-e9fac56ebbf8.png)

I see the scheduleViewHeaderBuilder, but how do I customize the appointments under it? I want to change the format of the appointment times:
![image](https://user-images.githubusercontent.com/9344207/122821055-08af9300-d2e5-11eb-8dc8-7ebc34604dcf.png)


Thanks.

**Comment by ronytesler** [comment]
I don't have a file called localization_extendibility.dart. I have global_localizations.dart, but it's part of the packages. It will be overwritten when I update the package.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Q1: Why in large view I don't see empty weeks and I don't see images and in small view I see both?**

As per the Schedule view implementation of the Flutter calendar, images will be displayed only when resizing the window and it is the expected behavior. Also, when resizing the window empty weeks are not shown with hideEmptyScheduleWeek property value as true and it is working fine as expected from our end. If possible, can you please check once with hideEmptyScheduleWeek value as true.

**Q2: how do I customize the appointments under it? I want to change the format of the appointment times**

In the Flutter Calendar you can change the appointment time format in schedule view by using the appointmentTimeTextFormat property of the calendar. Please find the UG document for the same.

**UG link:** https://help.syncfusion.com/flutter/calendar/appointments#appointment-time-format

**Q3: I don't have a file called localization_extendibility.dart. I have global_localizations.dart, but it's part of the package.** 

Can you please use the syncfusion_localization package for achieving your requirement? Also please find the pub document link for the same. Also we have attached the output screenshot also.

<img width="942" alt="locale" src="https://user-images.githubusercontent.com/54974849/122922597-6bef0300-d381-11eb-80b5-15599caab04d.png">
 
**Pub document link:**
https://pub.dev/packages/syncfusion_localizations/install

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
I had two SfCalendar in my code after copying from the example, and I added the settings to the wrong one. 
Everything looks great, except the Hebrew texts. For example, for the calendar view options:
![image](https://user-images.githubusercontent.com/9344207/122961905-88913800-d38d-11eb-816d-04c050ca3521.png)

In the middle word ther last letter is missing, and the Niqqud is also wrong, and usually unwanted, it's rarely used in systems. You can contact me if you want me to go over your texts.
But I'm not sure how I customize the Hebrew texts, is it by https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar or by using syncfusion_localization?

**Comment by ronytesler** [comment]
Also in Spanish for example, 'paginas' should be 'páginas'.

**Comment by Indumathi1195R** [comment]
Hi ,

Thank you for the update.

**Regarding Query: But I'm not sure how I customize the Hebrew texts, is it by https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar or by using syncfusion_localization?**

For localizing the custom string (No event) you can use the **syncfusion_localization** package and for customizing the Hebrew text you can use the extendibility option. Also please find the below KB link for adding the extendibility option in sample level.

**KB link:**
https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-a

We hope that this helps you. If possible, can you please share more details about your requirement clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
Sorry, I entered the kb (not sure what kb is), but I don't have a folder in my project called flutter_locale_extendibility. I'm not sure if I should have one, or it just the name of the project in the example...
These are some fixed texts, if you want to change on your side:
"ofDataPagerLabel" : "של",
"pdfScrollStatusOfLabel" : "של",
"pdfPaginationDialogCancelLabel" : "לבטל",
"allowedViewDayLabel" : "יום",
"allowedViewWeekLabel" : "שבוע",
"allowedViewMonthLabel" : "חודש",
"daySpanCountLabel" : "יום"

**Comment by ronytesler** [comment]
I also don't understand what it means to "Add the localization_extendibility.dart". I don't have such a file, I can create a new one, not sure what you refer by "the". I created a  Add the localization_extendibility.dart file in my lib folder, but it's empty, so the rest of the steps don't make sense, so I guess I should add "the" localization_extendibility.dart, but I have no idea what this file is...

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: but I don't have a folder in my project called flutter_locale_extendibility. I'm not sure if I should have one, or it just the name of the project in the example**

Localization_extendibility is a dart file name for adding the custom culture. Can you please refer the following custom culture support UG link?

**UG link:**
https://help.syncfusion.com/flutter/globalization#custom-culture-support

Can you please refer to the above UG link and override the required properties as per your requirement, and we hope that this helps you? Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
This one helped, thanks!!

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. Please get in touch with us if would require any further assistance.

Regards,
Indumathi R
