### ISSUE TITLE
[Feature Request] Rearranging PDF pages of a pdf document

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-examples#379]
Please add functionality for rearranging PDF pages in flutter using Syncfusion pdf plugin. Just like it is in other Syncfusion pdf libraries.

Thank you.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thanks for contacting Syncfusion support.

We have logged this requirement in feature-request. We will implement this feature in any of our upcoming releases.

You can track the status of this feature request from following feedback link,
https://www.syncfusion.com/feedback/26342/support-for-rearranging-pages-in-an-existing-pdf-document

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks I will keep a track on it.
