### ISSUE TITLE
Trackball still shows for a few seconds，after fingers move away from chart

### ISSUE THREAD

**Issue by Cyycl** [syncfusion/flutter-examples#38]
Now, If trackballBehavior is enabled, trackball disappear immediately after fingers move away from chart. 

I hope trackball still shows  for a few seconds after fingers move away from chart, in order to be able to take a screenshot.

Looking forward to your reply ~~

**Comment by dharanidharandharmasivam** [comment]
Hi @Cyycl ,

Thanks for your interest in our Syncfusion Flutter chart widget. As of now, the trackball disappears when the finger is moved away, and this is our current behavior. Your requirement for taking screenshots can be accomplished using **shouldAlwaysShow** of property. When shouldAlwaysShow property is set to true, the trackball will not get hidden. Find the code snippet below to achieve this.

> SfCartesianChart(
                  trackballBehavior: TrackballBehavior(
                        enable: true, 
                        shouldAlwaysShow: true
                  ),
                  //...
              )

And you can hide the trackball using the **hide** method. To know more about public methods, find the [user guide](https://help.syncfusion.com/flutter/chart/methods#hide-method-in-trackballbehavior).

We have also logged feature request in our feedback portal to provide, delay for trackball to disappear using an API. You can track the status of the feature using our feedback portal from below.

[Feedback link](https://www.syncfusion.com/feedback/9215 )

Hope this helps.

Thanks,
Dharani.
