### ISSUE TITLE
Calendar - Cannot display 5 weeks correctly in the Month view

### ISSUE THREAD

**Issue by xijun-j** [syncfusion/flutter-examples#381]
I like the library.!

I want to set the Month view to 5 rows and display the calendar from the beginning of the month.
It looks like this
![image](https://user-images.githubusercontent.com/3462059/122950232-4250ce80-d3b7-11eb-84d3-a2c022e482a1.png)

But I can't  get it. 

My source is 
```
MonthViewSettings(
          showTrailingAndLeadingDates: true,
          numberOfWeeksInView: 5,
          showAgenda: true,
        )
```

It became like this
![image](https://user-images.githubusercontent.com/3462059/122951940-a031e600-d3b8-11eb-8863-f83d736090a6.png)

Flutter 2.0.1
Dart 2.12.0
syncfusion_flutter_calendar: ^19.1.69

What should I do to solve it? 
Thank you

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: I want to set the Month view to 5 rows and display the calendar from the beginning of the month.**

Based on the shared information, we have checked and your requirement is “**Showing the calendar by beginning of the month**”. As per the calendar implementation, when set the **numberOfWeeksInView** property, weeks starts from the current date week. You can achieve your requirement by setting the **initialDisplayDate** property for the Calendar. 

You can refer the following documentation link for more information.
**UG link:** https://help.syncfusion.com/flutter/calendar/getting-started#initial-display-date

**Code snippet: initialDisplayDate defined.**
```
child: SfCalendar(
  view: CalendarView.month,
  initialDisplayDate: DateTime(DateTime.now().year,DateTime.now().month,1,9,0,0),
  monthViewSettings: MonthViewSettings(showAgenda: true,numberOfWeeksInView: 5),
),
```
**Screenshot:**

![vidma_recorder_23062021_111514](https://user-images.githubusercontent.com/54974849/123049367-1a945180-d41d-11eb-8084-c5cf7e706fea.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by xijun-j** [comment]
@Indumathi1195R 
Nice! Now it work fine.
Thanks a lot:)
