### ISSUE TITLE
[Issue] Can't remove pages from newly created document using existing document

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-examples#382]
Hello,
I have observed that I cannot remove pages from a document created using the pages as a template of an existing document.

To showcase the issue I'm providing this short sample code in which the first page should get removed from the newly created pdf:-

1. Replace main.dart code with this code below: (line 78 is trying to remove page)
```Dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late PlatformFile selectedFile;

  void onTapAction() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles();
    if (result != null) {
      selectedFile = result.files.first;

      PdfDocument document =
          PdfDocument(inputBytes: File(selectedFile.path!).readAsBytesSync());
      PdfDocument newDocument = PdfDocument();

      //function to create a new document using existing
      Future<PdfDocument> creatingNewPdfDocumentFromOld() async {
        List<PdfPage> pageList = [];
        List<PdfTemplate> pageTemplateList = [];
        //Get pages from existing document.
        for (var i = 0; i < document.pages.count; i++) {
          pageList.add(document.pages[i]);

          //Create the page as template and then add it to template list
          pageTemplateList.add(document.pages[i].createTemplate());
        }

        //Set page size and add page.
        for (var i = 0; i < document.pages.count; i++) {
          // pages of different size
          PdfSection section1 = newDocument.sections!.add();

          //changing section orientation if page height is less than width
          if (pageList[i].size.height < pageList[i].size.width) {
            section1.pageSettings.orientation = PdfPageOrientation.landscape;
          } else {
            section1.pageSettings.orientation = PdfPageOrientation.portrait;
          }
          section1.pageSettings.size = pageList[i].size;
          section1.pageSettings.margins.all = 0;
          PdfPage newPage = section1.pages.add();

          //Draw the template to the new document page.
          newPage.graphics.drawPdfTemplate(pageTemplateList[i], Offset(0, 0));
        }

        newDocument.pages.removeAt(0); //removing pages from newly created document here before returning it but it is causing no effect

        return newDocument;
      }

      late List<int> bytes;
      await creatingNewPdfDocumentFromOld().then((value) {
        document = value;
        bytes = value.save();
      });

      Future<void> saveAndLaunchFile(List<int> bytes, String fileName) async {
        final path = (await getExternalStorageDirectory())!.path;
        final file = File('$path/$fileName');
        await file.writeAsBytes(bytes, flush: true);
        OpenFile.open('$path/$fileName');
      }

      saveAndLaunchFile(bytes, 'Output.pdf');
    } else {
      // User canceled the picker
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: TextButton(
        onPressed: onTapAction,
        child: Text('Select File'),
      ),
    );
  }
}
```

2. Add these dependencies in pubspec.yaml :
```
  file_picker: ^3.0.3
  syncfusion_flutter_pdf: ^19.1.69-beta
  path_provider: ^2.0.2
  open_file: ^3.2.1
```

Thanks.

**Comment by Anand3595** [comment]
Hi @brightseagit,
 
Thanks for contacting Syncfusion support.
 
Currently we do not have support to remove PDF pages while creation. In your approach, you are trying to remove a page created in a new PDF document which have a content of an existing PDF page as template. So, the pages in newly created document is not removed.
 
We have two suggestions to remove the PDF page while creation. Please find the details below,
 
•	Instead of removing a page from a newly created PDF, we can ignore to create it. So that, the page is not added in new document and we can achieve the same as removing page.

> //Set page size and add page.
> for (int i = 0; i < document.pages.count; i++) {
>   **//Ignore to add a page, which is tried to remove**
>   **if (i == 0) {**
>     **continue;**
>   **}**
>   // pages of different size
>   final PdfSection section1 = newDocument.sections!.add();
>   //changing section orientation if page height is less than width
>   if (pageList[i].size.height < pageList[i].size.width) {
>     section1.pageSettings.orientation = PdfPageOrientation.landscape;
>   } else {
>     section1.pageSettings.orientation = PdfPageOrientation.portrait;
>   }
>   section1.pageSettings.size = pageList[i].size;
>   section1.pageSettings.margins.all = 0;
>   final PdfPage newPage = section1.pages.add();
>   //Draw the template to the new document page.
>   newPage.graphics.drawPdfTemplate(pageTemplateList[i], const Offset(0, 0));
> }
> return newDocument;

•	Instead of removing page from newly created PDF, we can save and load data to make it as loaded PDF. And then we can remove the pages by using removeAt(index) method as removed pages from an existing PDF document. 

> //Set page size and add page.
> for (int i = 0; i < document.pages.count; i++) {
>   // pages of different size
>   final PdfSection section1 = newDocument.sections!.add();
>   //changing section orientation if page height is less than width
>   if (pageList[i].size.height < pageList[i].size.width) {
>     section1.pageSettings.orientation = PdfPageOrientation.landscape;
>   } else {
>     section1.pageSettings.orientation = PdfPageOrientation.portrait;
>   }
>   section1.pageSettings.size = pageList[i].size;
>   section1.pageSettings.margins.all = 0;
>   final PdfPage newPage = section1.pages.add();
>   //Draw the template to the new document page.
>   newPage.graphics.drawPdfTemplate(pageTemplateList[i], const Offset(0, 0));
>   return newDocument;
> }
> **//Save newly created PDF and load saved data to make it as loaded PDF document**
> **PdfDocument ldocument = PdfDocument(inputBytes: newDocument.save());**
> **//removing pages from loaded PDF document**
> **ldocument.pages.removeAt(0);**

Please try the above approaches at your end and let us know if you need any further assistance in this.
 
With Regards,
Anand Panchamoorthi
