### ISSUE TITLE
PDFView multiple overview generation

### ISSUE THREAD

**Issue by giik0n** [syncfusion/flutter-examples#384]
There are some problems, when you select some text, at this moment opens Overlay menu, and you want to zoom in/out pdf view/ There are multiple copies of overlay creating.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-25 at 03 02 11](https://user-images.githubusercontent.com/26687349/123353576-19b90800-d562-11eb-8b3d-4b6fd0f59eb2.png)

**Comment by sarathkumar50** [comment]
Hi @giik0n ,
 
Greetings from syncfusion.
 
We are analysed about your issue with overlay and found the root cause what it might be.We are suspecting that you are using following codes in [onTextSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/onTextSelectionChanged.html) callback to show overlay
```
onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
if(details.selectedText != null) {
     _showOverlay(context, details);
   }
 },
```
Above codes will cause that issue with overlay to create again and again.We recommend you to use the following codes in [onTextSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/onTextSelectionChanged.html) callback to avoid overlay issue.
```
onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
  if (details.selectedText == null && _overlayEntry != null) {
    _overlayEntry!.remove();
    _overlayEntry = null;
  } else if (details.selectedText != null && _overlayEntry == null) {
    _showOverlay(context, details);
  }
},
```
You can follow the below website for more information about text selection
https://help.syncfusion.com/flutter/pdf-viewer/text-selection
 
Regards,
Sarath Kumar.

**Comment by giik0n** [comment]
> Hi @giik0n ,
> 
> Greetings from syncfusion.
> 
> We are analysed about your issue with overlay and found the root cause what it might be.We are suspecting that you are using following codes in [onTextSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/onTextSelectionChanged.html) callback to show overlay
> 
> ```
> onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
> if(details.selectedText != null) {
>      _showOverlay(context, details);
>    }
>  },
> ```
> 
> Above codes will cause that issue with overlay to create again and again.We recommend you to use the following codes in [onTextSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/onTextSelectionChanged.html) callback to avoid overlay issue.
> 
> ```
> onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
>   if (details.selectedText == null && _overlayEntry != null) {
>     _overlayEntry!.remove();
>     _overlayEntry = null;
>   } else if (details.selectedText != null && _overlayEntry == null) {
>     _showOverlay(context, details);
>   }
> },
> ```
> 
> You can follow the below website for more information about text selection
> https://help.syncfusion.com/flutter/pdf-viewer/text-selection
> 
> Regards,
> Sarath Kumar.

Hi, I'm actually using code from the example. The problem happening when you select some text, and trying to zoom PDF viewer. I think it's because of updating render. So text stays selected, and it's creates more overlay entries

**Comment by sarathkumar50** [comment]
Hi @giik0n ,
 
We tried to reproduce the reported issue with above shared codes but the context menu overlay where displayed properly. We have prepared a sample for your reference which can be downloaded in the following link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-699403576.zip
If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing sample which will be helpful for us to provide a prompt solution at the earliest.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar.
