### ISSUE TITLE
Vertical calendar can not show init selected date and edit background color

### ISSUE THREAD

**Issue by hautran90** [syncfusion/flutter-examples#386]
Hi @here! I use this package, but I can not show init selected date and edit background color initialDisplayDate and initialSelectedDates. Please help me, today is 06/25/2021 and initialSelectedDates 06/23/2021. Thanks
![image](https://user-images.githubusercontent.com/40556511/123436882-4d933c80-d5f9-11eb-9d1e-2087f4d9987d.png)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Vertical calendar can not show init selected date and edit background color**

Based on the provided information, we have checked and your requirement is “**Show the initial selected with color in Flutter Date Range Picker**”. In the shared code snippet, you have used **initialSelectedDates** property, it was applicable for **selectionMode** as **multiple**. Kindly use the **initialSelectedDate** property with **selectionColor** value and selectioMode as **single**. 

**Code snippet:**
```
child: SfDateRangePicker(
  selectionMode: DateRangePickerSelectionMode.single,
  enableMultiView: true,
  initialSelectedDate: DateTime(2021, 6, 25, 9, 0, 0),
  selectionColor: Colors.deepPurple,
  navigationDirection: DateRangePickerNavigationDirection.vertical,
),
```
**Screenshot:**
![vidma_recorder_28062021_110954 1](https://user-images.githubusercontent.com/54974849/123591971-45f6b200-d80a-11eb-8c1c-ccb45ddac30b.jpg)

Also please find the UG links for selection mode and selection cell customization in SfDateRangePicker,

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/selections
https://help.syncfusion.com/flutter/daterangepicker/customizations#selection-cell-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by hautran90** [comment]
Thanks @Indumathi1195R, How to add an icon stack a day.
![image](https://user-images.githubusercontent.com/40556511/125069355-d2de1d00-e0e0-11eb-820b-0e7acfda88d6.png)

**Comment by Indumathi1195R** [comment]
Hi @hautran90 ,

Thank you for the update.

Based on the shared image, we suspect your requirement is “**Adding an icon for particular date in the date range picker (SfDateRangePicker)**”. Your requirement can be achieved by using the **[cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html)** property of the picker, using this you can add icon for required dates. We have UG and document for adding custom widget in the date range picker.

Please find the UG and KB document from the following link.

UG link:
https://help.syncfusion.com/flutter/daterangepicker/builders

**KB link:**
https://www.syncfusion.com/kb/12208/how-to-customize-the-date-range-picker-cells-using-builder-in-the-flutter-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by hautran90** [comment]
Thanks @Indumathi1195R, How to edit selection date is circled. The current at it is square.
![image](https://user-images.githubusercontent.com/40556511/126057088-b7e45b48-32d1-4aa7-b1fd-f34b1f24fcf3.png)

**Comment by Indumathi1195R** [comment]
Hi hautran,

Thank you for the update.

**Regarding Query: How to edit selection date is circled. The current at it is square.**

Based on the shared code snippet, we have checked and your requirement is “**Changing the selection shape of the selected date in the SfDateRangePicker**”. You can customize the selection shape by using the **selectionShape** property of the picker.  Please find the UG documentation for the same.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/selections#selection-shape

Also, for custom builder, selection shape always in square selection. By using the below code snippet, you can change the selection shape for selected date. Please find the code snippet for the same.

**Code snippet:**
```
child: SfDateRangePicker(
  selectionColor: Colors.transparent,
  controller: _controller,
  view: DateRangePickerView.month,
  cellBuilder: cellBuilder,
),

Widget cellBuilder(BuildContext context, DateRangePickerCellDetails details)
{
  final bool isSelected = _controller.selectedDate != null &&
      details.date.year == _controller.selectedDate!.year &&
      details.date.month == _controller.selectedDate!.month &&
      details.date.day == _controller.selectedDate!.day;
  if (isSelected) {
    return Container(
      child: Text(
        details.date.day.toString(),
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.black87),
      ),
      decoration: BoxDecoration(shape: BoxShape.circle,color: Colors.red, ),
    );
  }
  else{
    return Container(child: Text( details.date.day.toString()),);
  }
}
```
We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
