### ISSUE TITLE
How to select month range (Date Range Picker)?

### ISSUE THREAD

**Issue by kizmiaz7** [syncfusion/flutter-examples#387]
Hello,

I'm sorry that this is more of a question than an issue.

Is it possible to select a month range using the Date Range Picker (Flutter)? 

For example: a selection from Jan 2020-April 2021 (disabling the date view). 

I assume I need to set allowViewNavigation to false, but I am unsure how to set the initial view to the yearly view (showing months instead of dates).

Any advice would be very much appreciated.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query:  Is it possible to select a month range using the Date Range Picker (Flutter)?** 

Yes, it is possible to select the month range in Flutter DateRangePicker by using the [allowViewnavigation ](https://help.syncfusion.com/flutter/daterangepicker/date-navigations#allow-view-navigation)value as false with [selectionMode ](https://help.syncfusion.com/flutter/daterangepicker/selections#range-selection)as range. We have attached the code snippet for the same. 

**Code snippet:**
```
    child: SfDateRangePicker(
  allowViewNavigation: false,
  view: DateRangePickerView.year,
  selectionMode: DateRangePickerSelectionMode.range,
)
```
**Screenshot:**
![Picture1](https://user-images.githubusercontent.com/54974849/123912013-22fb0800-d99a-11eb-8fbd-0d8847c96a6e.jpg)

Also, we have a KB document for selected range cell customization. Please find the document from the following link.

KB link:
https://www.syncfusion.com/kb/12148/how-to-customize-the-selected-range-cells-in-the-flutter-date-range-picker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
