### ISSUE TITLE
Hebrew text is not shown correctly

### ISSUE THREAD

**Issue by ronytesler** [syncfusion/flutter-examples#388]
![image](https://user-images.githubusercontent.com/9344207/123842992-0a4b0d80-d91a-11eb-9c99-bae2a0d54d5f.png)
I know it's a bug in Flutter, but the text is shown correctly after another build called, so I wanted to know if there's a way to know when the calendar is completely loaded so I can cause the build function to be run again.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “**Hebrew text is not shown correctly**”. On web the arabic text loaded after the text rendered on the view, it's a framework level issue. Overcome this issue, kindly use the custom font for fontFamily property of viewHeaderStyle.

**Code snippet:**
```
child: SfCalendar(
  view: CalendarView.month,
  viewHeaderStyle: ViewHeaderStyle(dayTextStyle: TextStyle(fontFamily: 'Heebo',color: Colors.red),),
  allowedViews: [CalendarView.week,CalendarView.day],
  dataSource: _getCalendarDataSource(),
),
```

**Screenshot:**
![Screenshot (16)](https://user-images.githubusercontent.com/54974849/124056794-ff8c9780-da43-11eb-985b-8ad38bdf7703.png)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
"On web the arabic text loaded after the text rendered on the view, it's a framework level issue." - Why does the arabic text affect the hebrew text?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: Why does the arabic text affect the hebrew text?**

Arabic, Persian, Hebrew, Pashto and Urdu are RTL related languages. So, we have mentioned Arabic text commonly for this issue. We have checked with other RTL languages also, the issue occurred for that languages also. Can you please use the custom fonts for resolving this issue?  Please find the RTL languages from the following UG document.

**UG link:** https://help.syncfusion.com/flutter/calendar/right-to-left#changing-the-locale-to-rtl-languages

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by ronytesler** [comment]
It works, thanks! Was just wondering about the Arabic.
Is there a simple way to do a similar solution for the text in the cells of the calendar?
Thanks.

**Comment by Indumathi1195R** [comment]
Hi ronytesler,

Thank you for the update.

**Regarding Query: Is there a simple way to do a similar solution for the text in the cells of the calendar?**

Yes, by using the custom font family for the textStyle, leadingDatesTextStyle, trailingDatesTextStyle of the MonthCellStyle you can overcome this issue for month cell texts. Please find the code snippet for the same.

**Code snippet:**
```
child: SfCalendar(
  view: CalendarView.month,
  viewHeaderStyle: ViewHeaderStyle(
    dayTextStyle: TextStyle(fontFamily: 'Heebo'),
  ),
  monthViewSettings: MonthViewSettings(
      monthCellStyle: MonthCellStyle(
          textStyle: TextStyle(
            fontFamily: 'Heebo',
          ),
          trailingDatesTextStyle: TextStyle(fontFamily: 'Heebo'),
          leadingDatesTextStyle: TextStyle(fontFamily: 'Heebo'))),
  allowedViews: [CalendarView.week, CalendarView.day],
  dataSource: _getCalendarDataSource(),
),
```
**Screenshot:**
![Screenshot (17)](https://user-images.githubusercontent.com/54974849/124551242-79ab8a80-de4f-11eb-928b-99a7818ebe7f.png)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
