### ISSUE TITLE
How can I combine multiple ranges with single dates?

### ISSUE THREAD

**Issue by Niko-by** [syncfusion/flutter-examples#389]
Hello. I really like your plugin **syncfusion_flutter_datepicker**. It is the only one that covers almost all needs. But there is one very important question. How to combine 2 modes in one? I need the user to be able to select both a date range and a single date. For example, how it is done in the web versions on the Google site. To select one date, you just need to double-click on it, and to select an interval, just click on different dates. And all this in one calendar.

If this is not possible, could you add?

**Comment by Niko-by** [comment]
A simple example. I need this so that the applicant can choose the dates to leave for temporary work. As several dates at once (date range) and single dates.

**Comment by Indumathi1195R** [comment]
Hi Niko-by,

Thank you for contacting Syncfusion support.

**Regarding Query: How can I combine multiple selection modes with single calendar.**

Based on the shared information, we have checked and your requirement is “**Combine the range selection with single selection in Flutter DateRangePicker**” and we regret to inform you that as per the current implementation of the picker, does not have support to use a single and range selection in one picker. Please let us know if you require any other assistance. We will be happy to assist you. 

Regards,
Indumathi R
