### ISSUE TITLE
How to disable edit  mode Only calendar ( initialEntryMode: DatePickerEntryMode.calendarOnly )

### ISSUE THREAD

**Issue by AhmedSayed2019** [syncfusion/flutter-examples#390]

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we are unbale to understand your requirement clearly. You can use **allowedViews** property of calendar for setting the particular calendar view. Also, by using the **allowViewnavigation** value as false you can restrict to day view navigation. Please find the UG and KB documentation for the same.

**UG links:**
https://help.syncfusion.com/flutter/calendar/date-navigations#allowed-views
https://help.syncfusion.com/flutter/calendar/date-navigations#allow-view-navigation

**KB link:**
https://www.syncfusion.com/kb/12019/how-to-do-date-navigations-easily-with-flutter-calendar

We hope that this helps you. If this is not your requirement, can you please share your requirement clearly? It would be helpful for analyze and provide you a solution. Can you please confirm your requirement is in SfCalendar or SfDateRangePicker control?

Regards,
Indumathi R

**Comment by rafildo** [comment]
If it's about SfDateRangePicker I would like to know how to disable the selection/edit mode. Enabling only view/navigation mode.

Thanks

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for the update.

**Regarding Query: I would like to know how to disable the selection/edit mode. Enabling only view/navigation mode.**

We regret to inform you that as per the current implementation of the picker, does not have support to completely disable the selection for the picker. But your requirement can be achieved by using setting the **selectionColor** value as **transparent** and setting the default property values for **selectionTextStyle**. We have attached the code snippet for the same. Please find the code snippet for the same.

**Code snippet:**
```
child: SfDateRangePicker(
  selectionColor: Colors.transparent,
  selectionTextStyle: const TextStyle(
      color: Colors.black87, fontSize: 13, fontFamily: 'Roboto') 
),
```
We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
