### ISSUE TITLE
SfDataGrid : The stylization of alternating lines is lost when sorting.

### ISSUE THREAD

**Issue by mikrul85** [syncfusion/flutter-examples#391]
I used your example for alternating line styling:

```
  DataGridRowAdapter? buildRow(DataGridRow row) {
    Color getRowBackgroundColor() {
      final int index = dataGridRows.indexOf(row);
      if (index % 2 != 0) {
        return Colors.lightGreen[300]!;
     }
      return Colors.transparent;
    }
    return DataGridRowAdapter(
        color: getRowBackgroundColor(),
        cells: row.getCells().map<Widget>((dataGridCell) {
          return Container(
              alignment: (dataGridCell.columnName == 'id' ||
                      dataGridCell.columnName == 'salary')
                  ? Alignment.centerRight
                  : Alignment.centerLeft,
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              child: Text(
                dataGridCell.value.toString(),
                overflow: TextOverflow.ellipsis,
              ));
        }).toList());
  }
```

When sorting, the stylization of rows ceases to work, since the rows in the list do not change places from sorting!

Before sorting:
<img width="698" alt="1_1" src="https://user-images.githubusercontent.com/49406463/124674981-6edf0d00-dec4-11eb-9202-f2321e23c118.png">

After sorting:
<img width="697" alt="1_2" src="https://user-images.githubusercontent.com/49406463/124675062-97670700-dec4-11eb-87b1-55a1bb304df0.png">

**Comment by mikrul85** [comment]
The second question: How do I get a modified list that has been sorted by a table?

**Comment by RenugaSadagoban98** [comment]
Hi @mikrul85 , 

Thanks for contacting Syncfusion support.  

 Currently, SfDataGrid does not have support to provide the sorted rows collection of DataGridRow. We have considered your request as an enhancement. This enhancement will be implement in our 2021 Volume 2 SP release, which is expected to be rolled out on mid of August 2021. You can follow up with the below feedback for further follow up,  
Feedback link: https://www.syncfusion.com/feedback/26797/provide-the-support-to-access-the-sorted-collection-of-datagridrow
 
Please let us know if you require any further assistance. 

Regards,
Renuga devi S

**Comment by mikrul85** [comment]
Hi @RenugaSadagoban98  ,

Thank you, but what do you say about the incorrect display of alternating rows when sorting?

**Comment by RenugaSadagoban98** [comment]
Hi @mikrul85 ,
 
Thanks for your update.
 
DataGrid is internally maintaining the collection when the sorting is applied. Due to this, the DataGridSource.rows gives the original order. That’s why the alternate row color is not applied properly when you sort the column. As we said earlier, we have planned to provide the sorted collection of DataGridRow. You can apply the color for the alternative row when you sort the column using that sorted rows collection like below,
 
   ```
 Color getRowBackgroundColor() {
      final int index = effectiveRows.indexOf(row); //The API may be changed. We will let you know about the API once we included in official release.
      if (index % 2 != 0) {
        return Colors.lightGreen[300]!;
     }
      return Colors.transparent;
```
Please let us know if you require any further assistance. 

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi @mikrul85,
 
We are glad to announce that your requested enhancement “**Provide sorted rows collection of DataGridRow**” was included our Essential Studio 2021 Volume 2 service pack Release v19.2.0.55 is rolled out and is available for download under the following link.
 
https://www.syncfusion.com/forums/168015/essential-studio-2021-volume-2-service-pack-release-v19-2-0-55-is-available-for-download

You can access the sorted collection of DataGridRow using the DataGridSource.effectiveRows property. Please refer the below code snippet,
```
@override
DataGridRowAdapter? buildRow(DataGridRow row) {
Color getRowBackgroundColor() {
final int index = effectiveRows.indexOf(row);
if (index % 2 != 0) {
return Colors.lightGreen[300]!;
}
return Colors.transparent;
}
return DataGridRowAdapter(
color: getRowBackgroundColor(),
cells: row.getCells().map<Widget>((dataGridCell) {
return Container(
alignment: (dataGridCell.columnName == 'id' ||
dataGridCell.columnName == 'salary')
? Alignment.centerRight
: Alignment.centerLeft,
padding: EdgeInsets.symmetric(horizontal: 16.0),
child: Text(
dataGridCell.value.toString(),
overflow: TextOverflow.ellipsis,
));
}).toList());
}

```

 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
 
Regards,
Renugadevi

**Comment by mikrul85** [comment]
@RenugaSadagoban98 
Thank you for the update, now rows are colored normally, but after installing version 19.2.55-beta, Multi-column sorting stopped working normally for me, could you check it?
And tell me how to get a sorted list?

**Comment by RenugaSadagoban98** [comment]
Hi @mikrul85  ,  
Thanks for your update. 
From the provided information, we have checked your reported scenario, but we could not reproduce your reported issue. We have tested a multi column sorting in the below sample with the following devices it's working fine.  
 
Devices:  
Moto G5S plus,  
Emulator-Nexus 5  
 
Please refer to the following sample for your reference,  
https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1804879325 


https://user-images.githubusercontent.com/77044081/129172770-032a492a-b2cd-4c2c-93af-8c5d6f206562.mp4


   
Please check the above sample and revert us if you still facing the same issue? If yes, please provide the following details,  
1.	Which is Flutter channel (Stable, beta or Master) are you using?  
2.	Provide the flutter version details? 
3.	Which platform you are using?

It will be helpful for us to check on it and provide you the solution at the earliest.    

Regards,
Renugadevi
