### ISSUE TITLE
Half SfRadialGauge Widget is occupying the entire view space 

### ISSUE THREAD

**Issue by ShineYang** [syncfusion/flutter-examples#395]
I have the same problem with #331 ,  is there a way to remove the extra bottom space?
![avatar](https://www.hualigs.cn/image/60eb17fa9ef47.jpg)

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,

You can remove the extra space below the half or quarter radial gauge using the canScaleToFit property of the RadialAxis. Please refer the below code snippet.

https://help.syncfusion.com/flutter/radial-gauge/axes 
https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/canScaleToFit.html 

**Code snippet:**

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            SfRadialGauge(
              axes: <RadialAxis>[
                RadialAxis(startAngle: 180, endAngle: 360, canScaleToFit: true,),
              ],
            ),
            Center(child: Text('Some text view')),
          ],
        ),
      ),
    );
  }
```

![image](https://user-images.githubusercontent.com/47354659/125277696-660c9200-e32f-11eb-992c-a4923efac93b.png)

Regards,
Lakshmi R.

**Comment by ShineYang** [comment]
@LakshmiRadhaKrishnan It solved my problem, Thx!
