### ISSUE TITLE
Rotating existing PDF document

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-examples#396]
Hello, 
I would like to know that is there any way to rotate an existing PDF document without converting its pages to templates?

Also, I have tried using the ```pdfDocument.pageSettings.rotate = PdfPageRotateAngle.rotateAngle180;``` but it didn't worked for existing documents. So, it would be great if the plugin clarifies somewhere in the documentation what features works and what doesn't with the existing document as whenever I use them I face no exception in the logs and it is very hard to trace why it doesn't work.
Thank you.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thanks for contacting Syncfusion support.

Currently we are not having support to get or set rotation to an existing PDF document page. We will consider it as a usability feature and include it in our upcoming weekly patch release which will be available on 27th July 2021.

You can track the status of this support implementation by https://www.syncfusion.com/feedback/26998/page-rotation-support-for-an-existing-pdf-document.

And we are using same API for creation and parsing support in flutter-pdf. we will update supported and unsupported feature details between PDF creation and parsing support in our help documentation.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks 👍 for letting me know about it. It would be amazing for me to have this feature.

**Comment by Anand3595** [comment]
Hi @brightseagit ,
 
We have included the support to get or set rotation to an existing PDF document page in our latest weekly patch release with version [19.2.49-beta](https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.2.49-beta). We can get or set page rotation by using ‘**PdfPage.rotation**’ property for an existing PDF document. Please find the code snippet below,

```
//Opens an existing PDF document
PdfDocument document =
    PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());

//Get first page
PdfPage page = document.pages[0];

//Get page rotation applied
PdfPageRotateAngle rotationAngle = page.rotation;

//Update rotation as 180 degree
page.rotation = PdfPageRotateAngle.rotateAngle180;

//Saves the document into a list of bytes
List<int> bytes = document.save();

//Saves the bytes to the file system
File('output.pdf').writeAsBytes(bytes);
```

Please let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks, I just checked and found that this feature is working great.
