### ISSUE TITLE
 Different fonts in one grid cell

### ISSUE THREAD

**Issue by metro636** [syncfusion/flutter-examples#397]
Is it possible to add text with different font styles in grid cell.Something like this
**Tittle**
_Description_

**Comment by RenugaSadagoban98** [comment]
Hi @metro636, 
Greetings from syncfusion.

Yes. We are getting the widgets directly from users. SfDataGrid provides support for load any type of widget in each column. So, you can set style in widget level itself. 

Refer following code snippet for setting font style to the grid cell,

```
@override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: EdgeInsets.all(8.0),
        child: Text(
          e.value.toString(),
          style: TextStyle(fontStyle: FontStyle.italic),
        ),
      );
    }).toList());
  }

```
![image](https://user-images.githubusercontent.com/77044081/125632248-44c06e46-a850-4c4b-9e57-b9ae5c8f7c1d.png)

Please let us know if you require any further assistance.

Regards, 
Renuga devi S

**Comment by metro636** [comment]
I had that doubt regarding pdf grid cell.

**Comment by Anand3595** [comment]
Hi @metro636 ,

We can set different fonts for each grid cells in PDF document by using _PdfGridCell.style.font_ property. Please find the code snippet below,

> //Create a PDF document
> PdfDocument document = PdfDocument();
> //Add a new page
> PdfPage page = document.pages.add();
> 
> //Create a PdfGrid
> PdfGrid grid = PdfGrid();
> 
> //Add columns to grid
> grid.columns.add(count: 3);
> 
> //Create header font with bold style
> PdfFont headerFont =
>     PdfStandardFont(PdfFontFamily.timesRoman, 17, style: PdfFontStyle.bold);
> 
> //Add headers to grid
> PdfGridRow header = grid.headers.add(1)[0];
> header.cells[0].value = 'Employee ID';
> header.cells[1].value = 'Employee Name';
> header.cells[2].value = 'Salary';
> ### //Set font for entire row
> ### header.style.font = headerFont;
> 
> PdfFont italicFont = PdfStandardFont(PdfFontFamily.timesRoman, 15,
>     style: PdfFontStyle.italic);
> PdfFont boldFont =
>     PdfStandardFont(PdfFontFamily.timesRoman, 15, style: PdfFontStyle.bold);
> PdfFont boldItalicFont = PdfStandardFont(PdfFontFamily.timesRoman, 15,
>     multiStyle: <PdfFontStyle>[PdfFontStyle.italic, PdfFontStyle.bold]);
> 
> //Add rows to grid
> PdfGridRow row1 = grid.rows.add();
> row1.cells[0].value = 'E01';
> ### //Set italic font for grid cell
> ### row1.cells[0].style.font = italicFont;
> row1.cells[1].value = 'Clay';
> ### //Set bold font for grid cell
> ### row1.cells[1].style.font = boldFont;
> row1.cells[2].value = '\$10,000';
> ### //Set italic and bold styled font for grid cell
> ### row1.cells[2].style.font = boldItalicFont;
> 
> //Draw the grid in PDF document page
> grid.draw(page: page, bounds: const Rect.fromLTWH(0, 0, 0, 0));
> 
> //Save the document
> List<int> bytes = document.save();
> //Dispose the document
> document.dispose();

Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_pdf_file1718064262.

Please find the documentation from https://help.syncfusion.com/flutter/pdf/working-with-tables#row-customization-in-pdfgrid and let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi
