### ISSUE TITLE
Uri does not exist 

### ISSUE THREAD

**Issue by itsdani121** [syncfusion/flutter-examples#398]
i added this pacakge which is  syncfusion_flutter_calendar: ^19.2.47.  after successfully get this pacakge when i import dart file which is  import 'package:syncfusion_flutter_calendar/calendar.dart'; which give me error as 
'target of URI doesn't exist: 'package:syncfusion_flutter_calendar/calendar.dart'. (Documentation)  Try creating the file referenced by the URI, or Try using a URI for a file that does exist.'  i dont know why it give me error i already pub get did also flutter clean and flutter pub get then run again but still same the issue i face

flutter doctor is 

         
[√] Connected device (3 available)
    [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter_windows_2.0.6-stable\flutter
    • Framework revision f4abaa0735 (13 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WasiSoft\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • JSN L22 (mobile) • GBT4C18913026549 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!

kindly look into this matter or i only face this issue

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the provided information, we have checked the mentioned issue “**Error occurred while adding the Syncfusion flutter calendar package**” and we are unable to reproduce the mentioned issue from our end. We have checked the latest version 19.2.47 with simple sample, pub get finished successfully and able to import the calendar package to sample. 

If possible, can you please share the below details,

•	Issue reproducing video
•	Issue reproducing sample

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
