### ISSUE TITLE
How to pass password dynamically.

### ISSUE THREAD

**Issue by raviganwal** [syncfusion/flutter-examples#399]
Hi want to to pass password into pdf at runtime so user don't know the password.

Thank you.

**Comment by Anand3595** [comment]
Hi @raviganwal ,

Thanks for contacting Syncfusion support.

We can protect the PDF document using encryption and set permission to the PDF document operations like printing, editing, copy content etc. using user password and owner password. Two types of encryption algorithms are available.
-	Rivest Cipher 4 (RC4)
-	Advanced Encryption Standard (AES)

And also we can use the user or owner password as a parameter of PdfDocument constructor to decrypt and load encrypted PDF document. Please find the constructors below,
-	PdfDocument({List<int> inputBytes, String password});
-	PdfDocument.fromBase64String(String base64String, {String? password})

Please find the more details about PDF security from https://help.syncfusion.com/flutter/pdf/working-with-security and also find the sample from https://www.syncfusion.com/kb/12265/how-to-secure-pdf-file-with-passwords-in-syncfusion-flutter-pdf-library.

Please let us know if you need any further assistance in this and also let us know more details about your requirement to provide prompt solution.

With Regards,
Anand Panchamoorthi
