### ISSUE TITLE
只有折线图, 有没有曲线图啊, 还有能不能加个阴影?

### ISSUE THREAD

**Issue by celiyawong** [syncfusion/flutter-examples#4]
同上

**Comment by JayavigneshwaranG** [comment]
Hi @celiyawong ,

Thanks for your interest in Syncfusion Flutter widgets.

There is no built-in support to render shadow for line chart. But you can achieve this in the sample level by following the below steps.
•	Extend new class named ‘CustomLineSeries’ from ‘LineSeries’ and ‘CustomLineSegment’ from ‘LineSegment’
•	Override the OnPaint method and add the code for rendering line shadow
•	Return the ‘CustomLineSegment’ in ‘createSegment’ method and assign it to the chart series.

We have attached the sample in the below link for your reference. Please refer main.dart file in lib folder.
[https://www.syncfusion.com/downloads/support/directtrac/general/ze/LINECH~1933419935.zip](https://www.syncfusion.com/downloads/support/directtrac/general/ze/LINECH~1933419935.zip)

Also, you can render curved lines using spline chart. Please refer the below sample code.
[https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/spline_series/default_spline_chart.dart](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/spline_series/default_spline_chart.dart)

Thus I am closing this issue. You can also contact us further through our [support forum](https://www.syncfusion.com/forums) or [Direct-Trac](https://www.syncfusion.com/support/directtrac/incidents). We are always happy to assist you! 

Note – I work for Syncfusion.

Thanks,
Jayavigneshwaran
