### ISSUE TITLE
Text extraction problem

### ISSUE THREAD

**Issue by ali321-hub** [syncfusion/flutter-examples#407]
Hi, I'm using version 19.2.49 of the plugin and it doesn't pick up spaces when extracting text in some pdf documents.

**Comment by chinnumuniyappan** [comment]
Hi @ali321-hub ,

Greetings from Syncfusion. We have tried to reproduce the reported issues on our end using our test documents. But the issue seems to the document-specific, we are not able to reproduce this. So we request you to share the input PDF document, which gives this issue. It would be more helpful for us to investigate further and update you with a prompt solution. 

Regards,  
Chinnu M

**Comment by ali321-hub** [comment]
Hİ @chinnumuniyappan 
Thanks for the feedback, you can find the pdf document that I had a problem with from the link.
https://drive.google.com/file/d/1Rk_QT4RAxeVBSRV9eh6gUW_SRERnyXc-/view?usp=sharing

**Comment by Anand3595** [comment]
Hi @ali321-hub ,

Currently we do not have support to add space in text extraction process based on the transformations applied between the words. We are processing text extraction based on the text drawing operators in page content. If the input text does not have any space character, we are not adding a space between two words and consider it as a single one. Please find more details from below screen shot,
![image](https://user-images.githubusercontent.com/72250552/128004672-057fec78-f26b-4fc3-b0f2-8a242bd0cec4.png)
 
We are logged a feature request for this support and we have no immediate plan to implement this feature. We will include this feature in any of our upcoming releases. You can track the status of this feature by https://www.syncfusion.com/feedback/27169/perform-the-text-extraction-by-considering-the-space-provided-by-transformations.

With Regards,
Anand Panchamoorthi

**Comment by ali321-hub** [comment]
Hi @Anand3595 Thank you, I will be waiting.

**Comment by maxbec** [comment]
What is the progress here? I would appreciate this feature. :)
