### ISSUE TITLE
Error when customise textStyle in headerStyle.

### ISSUE THREAD

**Issue by Vong3432** [syncfusion/flutter-examples#408]
### Reproduce error 

```
headerStyle: DateRangePickerHeaderStyle(
  textStyle: TextStyle(
      fontSize: 20
  ),
),
```
Setting textStyle without color will cause error.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/36991424/127672214-5fed3281-bbc2-4ac5-a5fd-42da884f15f8.png">

### This will not cause error

```
headerStyle: DateRangePickerHeaderStyle(
  textStyle: TextStyle(
      fontSize: 20,
      color: Colors.black <--- Adding color
  ),
),
```

### Full code (that cause error)
```
SfDateRangePicker(
  selectionColor: textColor,
  rangeSelectionColor: textColor,
  todayHighlightColor: textColor,
  minDate: DateTime.now(),
  headerStyle: DateRangePickerHeaderStyle(
    textStyle: TextStyle(
        fontSize: 20,
        fontStyle: FontStyle.normal,
    ),
  ),
  monthViewSettings: DateRangePickerMonthViewSettings(
    viewHeaderStyle: DateRangePickerViewHeaderStyle(
      textStyle: TextStyle(color: Colors.black),
    ),
  ),
  monthCellStyle: DateRangePickerMonthCellStyle(
    todayTextStyle: TextStyle(color: Colors.black),
    weekendTextStyle: TextStyle(color: Colors.black),
  ),
)
```

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

We have already found and fixed the mentioned issue “**Exception occurred while styling the headers of the picker using font size only**”. We will include the issue fix in out upcoming **2021 Volume 2 SP 1 release**, which is expected to be rolled out by mid of August 2021 and let you once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We are glad to announce that our Essential Studio 2021 Volume 2 service pack Release v19.2.55 is rolled out with the mentioned issue fix “**Exception occurred while styling the headers of the picker using font size only**”. Kindly update to the latest version for this feature. Please find the latest version from the following link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions/19.2.55

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
