### ISSUE TITLE
How to add Swipe Listener?

### ISSUE THREAD

**Issue by surajpunemaha** [syncfusion/flutter-examples#409]
I am using the` syncfusion_flutter_calendar: ^19.2.51` version.
I want to listen for swipe change when showing calendar in `view: CalendarView.month,` and retrieve the changed month and year.

I tried using `onSelectionChanged ` and` onViewChanged` but they doesn't fit in my requirement.
Please suggest.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked and we suspect your requirement is “Getting the month and year of the changed month in the Flutter Calendar”. In the Flutter Calendar you can get the current month,year details from the onViewChanged callback of the Flutter Calendar.

Please find the code snippet for the same. In the same way you can get the year and date details also.

**Code snippet:**
```
void viewChanged(ViewChangedDetails viewChangedDetails) {
  var currentMonth=viewChangedDetails.visibleDates[viewChangedDetails.visibleDates.length ~/2].month;
  var previousMonth=viewChangedDetails.visibleDates[0].month;
  var nextMonth=viewChangedDetails.visibleDates[viewChangedDetails.visibleDates.length-1].month;
}
```
Please find the UG link for onViewChanged callback.

**UG link:** https://help.syncfusion.com/flutter/calendar/callbacks#view-changed-callback

Please find the KB for getting visible date details using onViewChanged callback.

**KB link:**
https://www.syncfusion.com/kb/11026/how-to-get-visible-dates-details-from-the-flutter-calendar

We hope that this helps you. If this is not your requirement can you please share more details about your requirement clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Yes, you can use that approach, the **displayDate** property of the **CalendarController** will be updated whenever the current display date changed in the calendar. Please let us know if you need any further assistance.

Regards,
Indumathi R
