### ISSUE TITLE
Add Limit Line

### ISSUE THREAD

**Issue by Deain** [syncfusion/flutter-examples#41]
![chart-intro](https://user-images.githubusercontent.com/8544120/66377856-f7293900-e9e4-11e9-835e-947d525d4252.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @Deain ,

Thanks for using our Syncfusion Chart Flutter widget. The limit line can be rendered using the **plot band** feature. We have prepared a simple [sample ](https://www.syncfusion.com/downloads/support/directtrac/251038/ze/limit_line742457985 )and you can find the code snippet below to render the limit line and the text.

> 
      SfCartesianChart(
          
          // Render text (Limit line) using the annotation feature
            annotations: <CartesianChartAnnotation>[
               CartesianChartAnnotation(
                   widget: Container(
                   child: const Text('Limit Line', style: TextStyle(
                     fontSize: 24,
                     fontWeight: FontWeight.bold
                   ),)),
                   coordinateUnit: CoordinateUnit.point,
                   region: AnnotationRegion.plotArea,
                   x: 'X1',
                   y: 3100
                ),
            ],

            primaryYAxis: NumericAxis(
              
              // Render limit line
              plotBands: <PlotBand>[
                PlotBand(
                    isVisible: true,
                    start: 2980,
                    end: 3020,
                    shouldRenderAboveSeries: false,
                    color: const Color.fromRGBO(207, 85, 7, 1))
              ],
            ),
    )


To know more on the plot band, find the [user guide](https://help.syncfusion.com/flutter/chart/axis-customization#plot-bands).

Hope this helps.

Thanks,
Dharani.
