### ISSUE TITLE
[Syncfusion_flutter_pdf] Unable to load pdf from url 

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-examples#410]
I am working on an application that requires me to load pdf from url. The plugin I am using is syncfusion_flutter_pdf. I couldn't find a direct way to do the same so I tried downloading the file first and then use it. But the pdf is not displaying for some reason! There were nothing in the logs. Below is the screenshots of code for downloading and then using the file. 
P.S. I was trying this with the sample pdf url.

![image](https://user-images.githubusercontent.com/60787872/128191968-8f84622e-166a-4486-b20c-84a6d21d7856.png)
![image](https://user-images.githubusercontent.com/60787872/128192045-f92682ce-e1a2-4fc1-94e6-b3b62d3cbcfa.png)

**Comment by Anand3595** [comment]
Hi @ritz-ch ,

Thanks for contacting Syncfusion support.

We do not have direct support to load PDF from URL. We can load and read PDF data by using http package. We have created a sample to read the PDF data from webspace/website to load and save it using the retrieved PDF data. Kindly try the following code example and sample in your side,

1. Add http package in dependencies section of pubspec.yaml file
```
dependencies:
  http: ^0.13.3
```

2. Import the following package in your dart file.
```
//Read an PDF data from website/webspace
import 'package:http/http.dart' show get;
```

3. Get image data
```
//Read an PDF data from website/webspace
var url = "https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf";
var response = await get(Uri.parse(url));
var data = response.bodyBytes;
```

4. Load data into PDF document
```
//Create a new PDF document
PdfDocument document = PdfDocument(inputBytes: data);
//Save PDF document
final List<int> bytes = document.save();
//Dispose the document.
document.dispose();
```

Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample565926150.

Please let us know if your need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by ritz-ch** [comment]
Hi @Anand3595 
I tried the above code but the pdf is still not displaying on the mobile screen. When I am printing "response.bodyBytes" it's showing me list of integers. You can refer to the screenshot attached below. Can you guide me on this?
![image](https://user-images.githubusercontent.com/60787872/128673993-01d59fdd-1146-4022-a102-2537aadad6aa.png)

**Comment by Anand3595** [comment]
Hi ritz-ch,

We can save and open the PDF in mobile by using the following steps.

1.	Add dependency
```
path_provider: ^1.6.5
open_file: ^3.0.1
```

2.	Import package
```
import 'dart:io';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
```

3.	Include the following code snippet in readPdf() method to save and open PDF data in mobile
```
------------ PDF creation and manipulation code here ------------

//Get external storage directory
final directory = await getExternalStorageDirectory();

//Get directory path
final path = directory.path;

//Create an empty file to write PDF data
File file = File('$path/Output.pdf');

//Write PDF data
await file.writeAsBytes(bytes, flush: true);

//Open the PDF document in mobile
OpenFile.open('$path/Output.pdf');
```

Please find the sample to load PDF from URL / assets, save and open it in mobile from https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample565926150.

And also find the complete documentation from https://help.syncfusion.com/flutter/pdf/getting-started#save-and-open-a-pdf-document-in-mobile

With Regards,
Anand Panchamoorthi

**Comment by ritz-ch** [comment]
Hi @Anand3595 
I tried the above code but it is opening pdf in default pdfviewer and not in my application. Can you guide me further?
Thanks in advance!

**Comment by deepika134** [comment]
Hi ritz-ch,

SfPdfViewer have a support to load a PDF from URL. You can use the [SfPdfViewer.network]( https://help.syncfusion.com/flutter/pdf-viewer/getting-started#load-document-from-the-network) to load a PDF document from URL in your application. Please find the below documentation link to load a PDF from URL,
https://www.syncfusion.com/kb/12544/how-to-load-a-pdf-document-from-url-in-flutter-pdf-viewer-sfpdfviewer 

Regards,
Deepika R
