### ISSUE TITLE
[synfusion_flutter_calendar] Special region onTap detection

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#411]
Hi. Is there a way to differentiate between clicks on a `calendarCell` and a `specialRegion` on version 19.2.55?
The `onTap` callback gives us a `CalendarTapDetails`, but the result is the same whether the user clicks in a `calendarCell` that is not inside a `specialRegion` or in one that is.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Special region onTap detection**

We have considered this a feature “**Support to get the special time regions details using onTap callback of the Flutter Calendar**”. We will implement this feature in our upcoming 2021 Volume 4 release, which is expected to be rolled out by the month of December 2021.
 
At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
 
Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/27897/support-to-get-the-special-time-regions-details-using-ontap-callback-of-the
   
If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by AndreHaueisen** [comment]
Awesome! Thanks for the quick response.

**Comment by Indumathi1195R** [comment]
Hi Team,

We were unable to include this feature in our Volume 4 release. We have other high-priority tasks in the queue. So, we do not have any immediate plans to implement this feature. But we surely consider this in the future and implement it in any of our upcoming releases. We will inform you in the feedback portal once it is scheduled.

Regards,
Indumathi R
