### ISSUE TITLE
Not support local translation for allowedViews

### ISSUE THREAD

**Issue by MohammedMutasemHamed** [syncfusion/flutter-examples#412]
It seems that this version of the library did not support translating `allowedViews` while the rest of the items are localized.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Not support local translation for allowedViews.**

For localizing the **allowedViews** labels, you can use the **syncfusion_localizations** package. Kindly refer the package from the following link.

**Pub link:** https://pub.dev/packages/syncfusion_localizations/example

Also, we have KB document for adding the required localize word by using the extendibility option. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by MohammedMutasemHamed** [comment]
thanks!
Done.
But the names of the Arabic months are still not standard In the Levant and Iraq region Gregorian calendar months are not used
We use instead of 
يناير -> كانون الثاني 
And so on...
The question is how to modify the names of the months?.
