### ISSUE TITLE
Disable Input in DatePicker

### ISSUE THREAD

**Issue by sgarg15** [syncfusion/flutter-examples#414]
Hey,

I was wondering if its possible to disable the input/prevent the user from editing the date ranges in the [DatePicker Package.](https://pub.dev/packages/syncfusion_flutter_datepicker) Since I wanted the user to be able to look through the months but not be able to edit them/change the date ranges.

If you need more information let me know.
Thank you

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Disable Input in DatePicker**

Based on the shared information, we have checked and your requirement is “**Disable the user interaction for dates in the Flutter DateRangePicker**”. We have a KB document for disabling the user interaction for particular dates by using the blackoutDates property of the picker. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12075/how-to-add-active-dates-in-the-flutter-date-range-picker-sfdaterangepicker

Also please find the UG documentation for blackoutDates from the following link.

Also, we have a KB document for update the blackoutDates using onViewChanged callback.

**KB link:**
https://www.syncfusion.com/kb/12372/how-to-update-blackout-dates-using-onviewchanged-callback-in-the-flutter-date-range-picker

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by sgarg15** [comment]
Thank you for the quick reply. The blackouts date don't work however since the issue is that I want the calendar or datepicker to look like it normally does but only wanted to able to view the date ranges or dates not be able to edit them. The blackout dates you suggested crosses out those dates so they can't be selected. But what I wanted was to only view the calendar and the preselected dates not be able to edit any of the dates.

**Comment by Indumathi1195R** [comment]
Hi,

Sorry for the inconvenience caused.

As per the current implementation of the Flutter date range picker, there is no direct support for disabling the dates except the selected range dates. For achieving your requirement, we have prepared the simple sample based on the **blackoutDates** and **initialSelectedRange** property of the date range picker.

We have set all other dates except the selected range dates to the blackout dates collection and customized the blackout dates text style through the **blackoutDatesTextStyle** property of month cell style, to render the cells as a normal month cell, and updated the blackout dates on the 'onViewChanged`Callback.

To retain the same selection values, we have set the same selected range to the selected range property of the controller, on the **onSelectionChanged** callback, which selects the save value, even if any other cells are tapped.

Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/selection_without_blackoutdate_(2)-1876290866.zip

**Code snippet:**
```
child: SfDateRangePicker(
  controller: _controller,
  view: DateRangePickerView.month,
  selectionMode: DateRangePickerSelectionMode.range,
  initialSelectedRange:  PickerDateRange(_activeDates[0],_activeDates[5]),
  startRangeSelectionColor: Colors.purple,
  endRangeSelectionColor: Colors.purple,
  rangeSelectionColor: Colors.purpleAccent,
  onSelectionChanged: selectionChanged,
  monthViewSettings: DateRangePickerMonthViewSettings(
    blackoutDates: _blackoutDateCollection,
  ),
  monthCellStyle: DateRangePickerMonthCellStyle(
      blackoutDateTextStyle: TextStyle(color: Colors.black87,fontSize: 13,fontFamily: 'Roboto')),
  onViewChanged: viewChanged,
),

void viewChanged(DateRangePickerViewChangedArgs args) {
  DateTime date;
  DateTime startDate = args.visibleDateRange.startDate!;
  DateTime endDate = args.visibleDateRange.endDate!;
  List<DateTime> _blackDates = <DateTime>[];
  for (date = startDate;
  date.isBefore(endDate) || date == endDate;
  date = date.add(const Duration(days: 1))) {
    if (_activeDates.contains(date)) {
      continue;
    }
    _blackDates.add(date);
  }
  SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
    setState(() {
      _blackoutDateCollection = _blackDates;
    });
  });
}
void selectionChanged(DateRangePickerSelectionChangedArgs args)
{
  _controller.selectedRange=PickerDateRange(_activeDates[0],_activeDates[5]);
}
```
**Screenshot:**
![vidma_recorder_18082021_151127](https://user-images.githubusercontent.com/54974849/129878744-c8e43ad5-0c8d-4288-bdbe-adf098b80f13.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by sgarg15** [comment]
Ahh ok. Thanks again for replying quickly. If possible could you explain what you are doing here:
```dart
    List<DateTime> _blackDates = <DateTime>[];
    for (date = startDate;
        date.isBefore(endDate) || date == endDate;
        date = date.add(const Duration(days: 1))) {
      if (availabilityPharmacist.contains(date)) {
        continue;
      }
      _blackDates.add(date);
    }
    SchedulerBinding.instance?.addPostFrameCallback((timeStamp) {
      setState(() {
        _blackoutDateCollection = _blackDates;
      });
    });
```
And Also would this work if my activesDates were a list of pickerdate ranges rather then one pickerdaterange?
Thank you

**Comment by sgarg15** [comment]
Also this is sort of a different issue. but I have a list of PickerDateRanges:
`List<PickerDateRange> availabilityPharmacist`
and when I set that value in `initialSelectedRanges` it doesn't update the calendar, so it doesn't show anything in the calendar. I have checked the value of  `availabilityPharmacist` and its not null or empty, it has values stored in it. Do you know why this may be happening?
Thanks

**Comment by muthulakshmi-123** [comment]
Hi,

Sorry for the inconvenience caused.

Query1: Disable input for date picker and display the month as it is for multirange selection

Based on the provided information your requirement ‘Disable input for date picker and display the month as it is for multirange selection’, and we have modified the shared sample based on your requirement, by setting the selection mode as multirange.

And the mentioned code snippet is to disable the remaining dates other than the selected range dates, for the ‘onViewChangedCallback’ we get the visible date range and for every date in the visible date range, we have check and disabled date which doesn’t contain the selected range.

```
List<DateTime> _blackDates = <DateTime>[];
    for (date = startDate;
        date.isBefore(endDate) || date == endDate;
        date = date.add(const Duration(days: 1))) {
      if (availabilityPharmacist.contains(date)) {
        continue;
      }
      _blackDates.add(date);
    }
    SchedulerBinding.instance?.addPostFrameCallback((timeStamp) {
      setState(() {
        _blackoutDateCollection = _blackDates;
      });
    });

```
Kindly find the modified sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/selection_without_blackoutdate-378871811

Query 2: The `initialSelectedRanges` doesn’t update on the calendar.
We have tested the same and the issue doesn’t reproduce on our end, as per the date range picker implementation the initialSelectedRanges will be rendered only when the `selectionMode` is set as `DateRangePickerSelectionMode.multiRange`, kindly ensure the same in your sample.

Screenshot:
![image](https://user-images.githubusercontent.com/89257162/130252063-843b63ce-52c5-420d-b135-8d3db0b6831d.png)

Kindly refer to our UG document for the same by referring to the following link: 
https://help.syncfusion.com/flutter/daterangepicker/selections#multi-range-selection

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by sgarg15** [comment]
That works perfectly. Thank you so much!

**Comment by Ganesh-Shinde2002** [comment]
i want to disable editing of dates
