### ISSUE TITLE
[syncfusion_flutter_calendar] Day view initial scroll position

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#416]
Version 19.2.56
Hi. Is there a way to set the day view initial scroll position?
If a user reaches the view at 9 A.M, I would like the scroll position to reflect that.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we suspect your requirement is “**Showing the calendar day view with specified time**”. This can be achieved by using the **initialDisplayDate** property of the calendar, it displays the calendar based on the given time. Please find the UG documentation for the same.

**Code snippet:**
```
      child: SfCalendar(
          view: CalendarView.day,
          initialDisplayDate: DateTime(2019, 12, 20, 7, 0,0),
        ),
```
**Screenshot:**
![vidma_recorder_18082021_130027](https://user-images.githubusercontent.com/54974849/129858133-9383f594-05cf-42cb-82dd-dd0b28e2f267.jpg)

**UG link:**
https://help.syncfusion.com/flutter/calendar/getting-started#initial-display-date

We hope that this helps you. If this is not your requirement, can you please share more details about your requirement clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by AndreHaueisen** [comment]
Thank you! I will test it out.
