### ISSUE TITLE
[syncfusion_flutter_calendar] Today button does not change selectedDate

### ISSUE THREAD

**Issue by AndreHaueisen** [syncfusion/flutter-examples#418]
Version `19.2.56`
The today button present in the calendar's header only changes the `displayDate`:
```
onTap: () {
              if (!widget.enableInteraction) {
                return;
              }

              widget.removePicker();
              widget.controller.displayDate = DateTime.now();
            },
```

Can we modify it so it changes the `selectedDate` too?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Can we modify it so it changes the selectedDate too?**

As per the implementation, **Today** button intent only to move the calendar view to the today date, to update the selection dynamically you can use the [selectedDate](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController/selectedDate.html) property of the controller, also you can use the [displayDate](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController/displayDate.html) property of controller to programmatically navigate to particular date.

Please find the UG documentation for the same.

**UG links:** 
https://help.syncfusion.com/flutter/calendar/date-navigations#programmatic-date-selection
https://help.syncfusion.com/flutter/calendar/date-navigations#programmatic-date-navigation

**KB links:**
https://www.syncfusion.com/kb/12115/how-to-programmatically-select-the-dates-in-the-flutter-calendar
https://www.syncfusion.com/kb/12139/how-to-programmatically-navigate-to-the-date-in-the-flutter-event-calendar-sfcalendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by AndreHaueisen** [comment]
Thank you, but I do need to respond to that button click specifically.
Can I request that an optional "today button" callback gets implemented?

**Comment by muthulakshmi-123** [comment]
Hi AndreHaueisen,

Thank you for contacting Syncfusion support.

Based on provided information your requirement “Callback for today button in calendar”, as per calendar implementation, there is no callback for today button, but, you can achieve your requirement by adding custom header, in which you can design and set your own today button, we have prepared a simple sample for the same.

Kindly find the sample by referring the following link: 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/header-customization-today-button-1736306876

Please find the KB for adding custom header and view header in calendar
https://www.syncfusion.com/kb/10997/how-to-add-custom-header-and-view-header-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi

**Comment by AndreHaueisen** [comment]
Alright. I will test it out. Thanks for the help 👍🏻
