### ISSUE TITLE
[syncfusion_flutter_calendar] SfCalendar don't rebuild

### ISSUE THREAD

**Issue by lukiinhas1616** [syncfusion/flutter-examples#419]
I'm trying to switch view mode from a button, but SfCalendar doesn't rebuild.

`
child: Observer(
                  builder: (_) => SfCalendar(
                    view: store.isMonthView ? CalendarView.month : CalendarView.week,
                    dataSource: MeetingDataSource(_getDataSource()),
                    monthViewSettings: const MonthViewSettings(
                        appointmentDisplayMode:
                        MonthAppointmentDisplayMode.appointment),
                  ),
                )
`

Tried unsuccessfully using setState, also unsuccessfully tried using ternary in SFcalendar.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: I'm trying to switch view mode from a button, but SfCalendar doesn't rebuild.**

As per the current implementation of the calendar, view property of the calendar doesn’t switch the view dynamically. For achieving your requirement kindly use the view property of the CalendarController. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_dynamic_viewswitch33773121.zip

**Code snippet:**
```
child: Column(
  children: [
    TextButton(
        onPressed: () {
          if(_controller.view==CalendarView.day) {
            _controller.view = CalendarView.week;
          }
          else
            {
              _controller.view=CalendarView.day;
            }
        },
        child: Text("Switch view")),
    Expanded(
      child: SfCalendar(
        view: CalendarView.day,
        controller: _controller,
        dataSource: _getCalendarDataSource(),
      ),
    ),
  ],
),
```

Please find the KB documentation for the same.

KB link:
https://www.syncfusion.com/kb/12141/how-to-do-programmatic-navigation-using-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by lukiinhas1616** [comment]
Thank you very much, it worked!

**Comment by lukiinhas1616** [comment]
Thank you very much, it worked!
