### ISSUE TITLE
Calendar appointmentItemHeight set to automatic

### ISSUE THREAD

**Issue by Aaron-Linkforce** [syncfusion/flutter-examples#420]
Hi, I'm currently using Calendarview.schedule to display a list of appointments, with the option of clicking an appointment and having it expand using appointmentBuilder to display an ExpansionTile component inside a Card.

However I'm trying to find out how to set the appointmentItemHeight to automatic, so that it gets the height based on the size of the content. When it expands it should scale appropriately.

The kind of layout I'm using is as follows:

`SfCalendar(

      view: CalendarView.schedule,
      
      controller: _controller,
      
      scheduleViewSettings: ScheduleViewSettings(
      
        hideEmptyScheduleWeek: true,
        
        appointmentItemHeight: 130,
        
      ),
      
      appointmentBuilder: (BuildContext context,
      
          CalendarAppointmentDetails calendarAppointmentDetails) {
          
        return Card(
        
            elevation: 3,
            
            child: Container(
            
              child: ExpansionTile(
              
                initiallyExpanded: expanded,
                
                backgroundColor: Colors.blueGrey.withOpacity(0.15),
                
                title: Stack(children: [
                
                    // child items
                    
                  ]
                  
                    ),
                  )
                ],
              ),
            )
 );`
 
 In the above I've set the height to 130 just to see the content, but when I set it to the default -1 it overflows and doesn't work.
 
 Any help is appreciated!

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on provided information your requirement “how to set the appointmentItemHeight to automatic”. As of now, there is no direct support to set the appointmentItemHeight to automatic.

Kindly, share more details about your requirement. It will be helpful for us to analyze and resolve your requirement.

Please let us know if you need further assistance.  

Regards,
Muthulakshmi K

**Comment by Aaron-Linkforce** [comment]
> Kindly, share more details about your requirement. It will be helpful for us to analyze and resolve your requirement.

Thanks for the reply!
Basically my intention is that when you have a list of appointments, you can click one of them so that it expands and shows further information about that appointment (such as notes, contact phone numbers, etc), without having to navigate to a different page

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support. 

Based on provided information your requirement **“When clicking the appointment, that it expands and shows further information about that appointment”**. As of now there is no direct support to expands and shows the information about the appointment. But, you can get the tapped appointment details through the `onTap` callback of the calendar, by using this we suggest you to display the appointment details in a popup window.

Please let us know if you have any concerns. 

Regards,
Muthulakshmi K
