### ISSUE TITLE
How to change the text for startRangeSelection

### ISSUE THREAD

**Issue by chesongsong** [syncfusion/flutter-examples#425]
How to change the text for startRangeSelection,
startRangeSelection default text is some date,but i expective it is a string what i can customize eg:  string "start"

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support. 

Based on the shared information we have analyzed your requirement “How to customize the start range string”  as per date picker implementation, there is no direct support to customize the start range string, but you can achieve your requirement by using the  cellBuilder and set the cell text as you required, you can get the start date from the onSelectionChanged 

Kindly find the sample by referring the following link: 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/start-range-selection-customization762207620

Please refer the following UG link for customizing cell builder in date picker: 
https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder  

Please find the KB for customizing cell builder in date picker: 
https://www.syncfusion.com/kb/12208/how-to-customize-the-date-range-picker-cells-using-builder-in-the-flutter-sfdaterangepicker

We hope that this helps you, please let us know if you need further assistance. 

Regards,
Muthulakshmi K

**Comment by ziqq** [comment]
Can i change selection radius? SelectionRadius prop not working!
![image](https://user-images.githubusercontent.com/20646071/131670822-25b418cc-a0f6-4f71-b64b-935ed16227d6.png)

`SfDateRangePicker(
            controller: _controller,
            cellBuilder: (BuildContext context, cellDetails) {
              return ClipOval(
                child: Stack(
                  children: [
                    Container(
                      width: cellDetails.bounds.width,
                      height: cellDetails.bounds.height,
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30),
                        color: DateHelper.isSameDate(
                                cellDetails.date, DateTime.now())
                            ? Theme.of(context).primaryColor
                            : Colors.transparent,
                      ),
                      child: Text(
                        cellDetails.date.day.toString(),
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                              height: 1,
                              color: cellDetails.date.weekday == 6 ||
                                      cellDetails.date.weekday == 7
                                  ? Theme.of(context).errorColor
                                  : DateHelper.isSameDate(
                                          cellDetails.date, DateTime.now())
                                      ? Theme.of(context)
                                          .scaffoldBackgroundColor
                                      : Theme.of(context).primaryColor,
                            ),
                      ),
                    ),
                    if (widget.exposedDays
                        .where((e) =>
                            e ==
                            DateFormat('yyyy-MM-dd').format(cellDetails.date))
                        .isNotEmpty)
                      Positioned(
                        bottom: 6,
                        left: cellDetails.bounds.width / 2 - 3,
                        child: Container(
                          width: 6,
                          height: 6,
                          decoration: BoxDecoration(
                            color: kAccentColorDark,
                            borderRadius: BorderRadius.circular(30),
                          ),
                        ),
                      ),
                  ],
                ),
              );
            },

            selectionRadius: 30,
            // allowViewNavigation: false,
            // todayHighlightColor: Colors.white,

            enableMultiView: true,
            minDate: widget.minDate,
            maxDate: widget.maxDate,
            selectionMode: selectionMode,
            view: DateRangePickerView.month,
            navigationMode: DateRangePickerNavigationMode.scroll,
            navigationDirection: DateRangePickerNavigationDirection.vertical,
            onSelectionChanged: (DateRangePickerSelectionChangedArgs args) {
              setState(() {
                if (widget.single!) {
                  dateRanges = [PickerDateRange(args.value, args.value)];
                }
                if (widget.multiple!) {
                  List<PickerDateRange> value = [];
                  List.from(args.value).forEach((e) {
                    value.add(PickerDateRange(e, e));
                  });

                  value.sort((a, b) {
                    return a.startDate!.compareTo(b.startDate!);
                  });
                  dateRanges = value;
                }
                if (widget.multipleRange!) {
                  dateRanges = args.value;
                }
                if (widget.range!) {
                  dateRanges = [args.value];
                }
              });
            },
            initialSelectedDates: widget.multiple! ? multiple : null,
            initialSelectedRange:
                widget.range! ? widget.initialRanges.first : null,
            initialSelectedRanges:
                widget.multipleRange! ? widget.initialRanges : null,
            initialSelectedDate:
                widget.single! ? widget.initialRanges.first.startDate : null,
            headerStyle: DateRangePickerHeaderStyle(
              textStyle: Theme.of(context).textTheme.headline4,
            ),
            monthViewSettings: DateRangePickerMonthViewSettings(
              firstDayOfWeek: 1,
              enableSwipeSelection: false,
              specialDates: [DateTime.now()],
            ),
            backgroundColor: Theme.of(context).scaffoldBackgroundColor,
            selectionColor: Theme.of(context).accentColor,
            // selectionColor: Colors.transparent,
            // startRangeSelectionColor: Colors.transparent,
            // endRangeSelectionColor: Colors.transparent,
            // rangeSelectionColor: Colors.transparent,
            selectionTextStyle: Theme.of(context)
                .textTheme
                .bodyText1!
                .copyWith(color: Theme.of(context).scaffoldBackgroundColor),
            monthCellStyle: DateRangePickerMonthCellStyle(
              // specialDatesDecoration: BoxDecoration(
              //   color: Theme.of(context).errorColor,
              // ),
              textStyle: Theme.of(context).textTheme.bodyText2,
              cellDecoration: _MonthCellDecoration(
                // indicatorColor: Colors.red,
                // showIndicator: true,
                backgroundColor: Colors.transparent,
              ),
              // weekendTextStyle: Theme.of(context)
              //     .textTheme
              //     .bodyText2!
              //     .copyWith(color: Theme.of(context).errorColor),
              todayTextStyle: Theme.of(context)
                  .textTheme
                  .bodyText2!
                  .copyWith(color: Theme.of(context).primaryColor),
              // todayCellDecoration: _MonthCellDecoration(
              //   backgroundColor: Theme.of(context).disabledColor,
              // ),
            ),
          ),`

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on provided code snippet we have checked the mentioned issue "Selection radius not working properly", based on the current date range picker implementation that’s the behavior when the [cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html) used to render custom UI the selection radius will not work.  But you can achieve your requirement, by adding the selection UI through the [cellbuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html), we have prepared KB for the same.

Kindly find the KB for customizing the selection width cellbuilder in date range picker: 
https://www.syncfusion.com/kb/12474/how-to-create-timeline-date-picker-in-flutter

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by ziqq** [comment]
It's not rounded. 

![image](https://user-images.githubusercontent.com/20646071/131852944-7a7ec16e-d2e0-4688-8082-1f3b96eaf6ef.png)

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query1: What is Kb?**

Kb is Knowledge base documentation. It includes a working sample with details for frequently asked questions about our controls. We have included more samples for using a flutter date range picker. It can give customers the best chance of receiving information like code snippets, annotated images, video,  or any other media format. It’s easy for customers to find the information they need without having to reach out to your support team and wait on an answer.

**Regarding Query2: The selection is not rounded**

We have shared the KB for reference, indicating that your requirement can be achieved through the cellbuilder like in the KB, now, we have prepared a simple sample for the same by adding the selection UI through the [cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html), and render the selection shape as you required from the [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/onSelectionChanged.html). 
Kindly find the sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/rounded_selection_date_picker1043831129

We hope that this helps you. Please let us know if you need further assistance.

Regards, 
Muthulakshmi K

**Comment by ziqq** [comment]
OK. It's work for me. But i have still question. How can i create rouded selection interval? Plz get me new example. Thx.

![image](https://user-images.githubusercontent.com/20646071/132215514-5ac4f56b-9859-4ee2-8090-17955e657b98.png)

Like this

![image](https://user-images.githubusercontent.com/20646071/132215630-5306b514-e904-4b4a-ad5e-974411cb6f60.png)

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information your requirement **"How can I create rounded selection interval?"**, As per the date range picker implementation, when using the [cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html), the rounded range selection Interval will not work. But you can achieve your requirement by using Custom Painter, in which you can draw the rounded range selection for the start date, end date, and the between dates separately. We have prepared a simple sample for the same. 

Kindly find the sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Custom-rounded-range-selection-191298413

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by ziqq** [comment]
Ok. It's work. And the last question from me. How i can change color to white.
![image](https://user-images.githubusercontent.com/20646071/132504760-d59b58d0-fe1d-4201-a1ad-ee9620bd515b.png)

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on provided information your requirement **“How can I change white color for the selected date?”**, you can achieve your requirement by set the text color as white when the month cell is selected range start date or end date cell. We have modified the sample based on your requirement

Kindly find the modified sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Selection-cell-white-color-1397680664

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by ziqq** [comment]
Hi. Single mode not working.
![image](https://user-images.githubusercontent.com/20646071/133563568-1c8e302f-b47b-4303-865e-7c08f362f8a7.png)

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support. 

Based on the provided code snippet we have checked the mentioned issue **"Single selection mode is not working properly"**. As per your requirement, we have given the previous sample with [cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html) implementation for range selection to handle the start and end date of the range, also between the dates separately. In the given sample, we have not implemented the same for single selection in the given sample. 

As of now, based on your requirement, we have modified the given sample to work with the single selection with the cell builder. By referring the given sample, you can implement the same for all the selection modes as per your requirement.

Kindly find the modified sample by referring the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/single-selection-picker-2112814274

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K
