### ISSUE TITLE
onTouchUp callback

### ISSUE THREAD

**Issue by whenislunch** [syncfusion/flutter-examples#43]
I'd like to see to some sort of onTouchUp function for TrackballBehavior in particular, where a callback function gets activated when user stops touching the chart.

Thanks.

**Comment by dharanidharandharmasivam** [comment]
Hi @whenislunch ,

Thanks for suggesting the new feature. We have logged a feature request for your requirement, and you can track the status of the feature with our feedback portal from the below link.

https://www.syncfusion.com/feedback/9385 

The feature will be available in our volume 4 main release update which is expected to be in the middle of December 2019. We will notify you once the release is rolled out, and we appreciate your patience until then.

Thanks,
Dharani.
