### ISSUE TITLE
appointments are only updating on user intraction 

### ISSUE THREAD

**Issue by rawquesh** [syncfusion/flutter-examples#430]
I am listening to a firetore collection but when I update appointments on the `snapshot.listen` function the UI is not getting change but when i interact with UI or scroll the UI will change.

`         ....listen((res) {
            List<BookingModel> newb = res.docs.map((e) => BookingModel.fromSnapshot(e)).toList();
            dataSource.appointments.addAll(getAppointments(newb));
            dataSource.notifyListeners(CalendarDataSourceAction.add, getAppointments(newb));
          });`

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: appointments are only updating on user intraction**

Based on the shared information, we have prepared the simple sample and checked the mentioned issue “**Calendar UI is not updating while adding the appointments in Firestore database collection**” in our simple sample and it was working fine as expected from our end, also the appointments are reflected properly. Please find the KB documentation for performing CRUD operations using **Firestore** database.

Please find the KB from the following link.

**KB link:** https://www.syncfusion.com/kb/12661/how-to-perform-the-crud-operations-in-flutter-calendar-using-firestore-database

Also, we have a KB document for adding the appointment to the **Firestore** database.

**KB link:**
https://www.syncfusion.com/kb/12616/how-to-add-the-appointments-to-firestore-database-using-flutter-calendar

Please check the sample from above KB and let us know still if you are facing same issue? If not please modify the sample based on your scenario and revert us with more details. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by rawquesh** [comment]
i was not calling setState, its fine now, thanks btw :)
