### ISSUE TITLE
SfCalendar: all day events shown on two dates

### ISSUE THREAD

**Issue by brotkrume** [syncfusion/flutter-examples#432]
Hi,

my all-day-events are shown on two dates. Any ideas what i'm doing wrong? Example:
start date 2021-09-10 00:00:00, end date 2021-09-10 23:59:59 -> shown for 2021-09-10 and 2021-09-11 in month view.

Many thanks & Regards

**Comment by brotkrume** [comment]
Hi,

I've found the issue. Timezone will be considered 👎  I'm retrieving events from google. All events are in UTC except all day events. If I'm set them to UTC or convert them to local, then they are shown correctly.

Seems to be an issue in SfCalendar. All day events should not consider timezone.

Regards

**Comment by muthulakshmi-123** [comment]
Hi,

Based on provided information we have checked the mentioned issue **“All day events are shown on two dates”**. While retrieving events from google calendar they will return the all-day appointment as 24 hours hence we need to handle this in the sample to render the all-day appointment for a single day. We have a KB document for the same, kindly refer to the following KB document for more information. 

Please find the KB to load the google calendar events to the calendar in Android:
https://www.syncfusion.com/kb/12116/how-to-add-google-calendar-events-to-the-flutter-event-calendar-sfcalendar

Please find the KB to load the google calendar events to the calendar in iOS:
https://www.syncfusion.com/kb/12647/how-to-load-the-google-calendar-events-to-the-flutter-calendar-sfcalendar-in-ios 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K
