### ISSUE TITLE
SfCalendar: Scheduled view - hide empty day

### ISSUE THREAD

**Issue by brotkrume** [syncfusion/flutter-examples#434]
Hi,

in schedule view, I can hide empty weeks. But how can I hide the actual day, if there are no events?

Thanks & Regards

**Comment by muthulakshmi-123** [comment]
Hi,

Based on provided information we have analyzed your requirement **“How to hide the day if there is no event in schedule view”**. As per the current implementation of the calendar, the empty day will be hidden by default, and the initial display date alone will be displayed if there is no event in the schedule view and it’s a behavior of the calendar. Kindly, share more details about your exact requirement. It will be helpful for us to analyze and resolve your requirement.

Kindly find the following link to know more about schedule view in calendar
https://help.syncfusion.com/flutter/calendar/schedule-view

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by brotkrume** [comment]
Hi,

thanks for your response. Sorry that my request was not precise enough. I wrote "actual day": with actual day i mean the initial display date. How can I suppress the initial display date, if there is not event?

Regards

**Comment by muthulakshmi-123** [comment]
Hi,

Based on shared information we have analyzed your requirement **“How to hide the initial display date if there is no event in schedule view”**, and based on the current implementation of the calendar, there is no direct support to hide the initial display date if there is no event in schedule view and it’s a behavior of the calendar. 

But you can achieve your requirement by setting the initial display date to any of the event's dates, it will hide the empty day in schedule view, based on the data source moves to the nearest event date to the required display date. It will display the event date and the empty day slot will be hidden in schedule view. 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K
