### ISSUE TITLE
How to add custom icon as one of header property in SfCalendar

### ISSUE THREAD

**Issue by wahyu-handayani** [syncfusion/flutter-examples#435]
Hi, I am using syncfusion_flutter_calendar: ^19.2.57 and trying to add refresh icon beside calender icon. So whenever user press the refresh icon the calendar will be reload.
Here is the picture that I mean
![20210916_145123](https://user-images.githubusercontent.com/55479207/133572700-313c7908-c507-4706-9bef-307166d00da1.jpg)
I would like to ask, is there a property of ```SfCalendar``` to add custom icon beside calender icon?

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: How to add custom icon as one of header property in SfCalendar** 

By using the custom header, you can add the icon in the header view. By using the **headerHeight** value as 0, you can hide the default header. We have KB documentation for the same. Please find the documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/10997/how-to-add-custom-header-and-view-header-in-the-flutter-calendar

Also please find the UG link for **headerHeight** customization.

**UG link:**
https://help.syncfusion.com/flutter/calendar/headers#customize-header-height-in-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by wahyu-handayani** [comment]
Hi @Indumathi1195R thanks for your reply, I will try it later and let you know the result if I need another help

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R

**Comment by wahyu-handayani** [comment]
Hi @Indumathi1195R sure, I will let you know if I have another question, for now I will close my question. Thank you very much @Indumathi1195R
