### ISSUE TITLE
How to download agenda report in SfCalendar

### ISSUE THREAD

**Issue by wahyu-handayani** [syncfusion/flutter-examples#439]
Hi I am currently using syncfusion_flutter_calendar: ^19.2.57. Firstly, I would like to thank for all the team for making this plugin work nicely. This plugin is really good one to make multiple appointment. Actually I am here to ask a question, is there a menu or property or feature of ```SfCalendar``` to save all of the agenda that user create in form of pdf or docs or xls, so whenever user click a button there will be a kind of agenda report that user can download it

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Regarding Query: Export support in calendar

Based on the shared information, we have checked, and your requirement is “Export the calendar datasource details in an Excel document”. Based on current implementation we don’t have direct support to export the appointment from calendar, but you can achieve your requirement in sample level by using our Syncfusion xlsio  package. We have prepared the simple sample in web platform for exporting the calendar appointment to excel document. Kindly find the sample from the following link.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_appointmentchange_(3)768853850.zip

Also please find the UG documentation link for creating a n excel document in mobile, web and desktop platforms.

https://help.syncfusion.com/flutter/xlsio/getting-started#create-an-excel-document-in-mobile
https://help.syncfusion.com/flutter/xlsio/getting-started#create-an-excel-document-in-web
https://help.syncfusion.com/flutter/xlsio/getting-started#create-an-excel-document-in-desktop

We have attached the code snippet for the same. Please find the code snippet from below.

**Code snippet:**
```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text('Calendar Demo'),
      leading: IconButton(
        icon: Icon(Icons.import_export),
        onPressed: () async {
          final Workbook workbook = Workbook();
          final Worksheet sheet = workbook.worksheets[0];
          sheet.getRangeByIndex(1, 1).setText('Id');
          sheet.getRangeByIndex(1, 2).setText('Subject');
          sheet.getRangeByIndex(1, 3).setText('Start Time');
          sheet.getRangeByIndex(1, 4).setText('End Time');
          int row = 2;
          for(int i = 0;i<_dataSource.appointments!.length;i++){
            int column = 1;
            final Appointment appointment = _dataSource.appointments![i];
            sheet.getRangeByIndex(row, column).setValue(i+1);
            column++;
            sheet.getRangeByIndex(row, column).setText(appointment.subject);
            column++;
            sheet.getRangeByIndex(row, column).setDateTime(appointment.startTime);
            column++;
            sheet.getRangeByIndex(row, column).setDateTime(appointment.endTime);
            row++;
          }
          final List<int> bytes = workbook.saveAsStream();
          workbook.dispose();

/// Web platform
          AnchorElement(
              href:
              "data:application/octet-stream;charset=utf-16le;base64,${base64.encode(bytes)}")
            ..setAttribute("download", "output.xlsx")
            ..click();

/// Mobile platform

          // final directory = await getExternalStorageDirectory();
          //
          // final path = directory!.path;
          //
          // File file = File('$path/Output.xlsx');
          //
          // await file.writeAsBytes(bytes, flush: true);
          //
          // OpenFile.open('$path/Output.xlsx');
        },
      ),
    ),
    body: SfCalendar(
      dataSource: _dataSource,
    ),
  );
}
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by wahyu-handayani** [comment]
Hi @Indumathi1195R I have tried the code you gave to me and I will try to combine my project with the idea from yours. Thank you very much @Indumathi1195R. For now I will close my question, I will open it if I get another question in the middle of doing my project
