### ISSUE TITLE
Reanimate graph

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#44]
Hello is there any way for Reanimate graph without data change?

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

As of now the series will get animated on the initial rendering and when data is updated. We don’t have support for animate the series again or on calling the set state. So, we have a logged feature request in our feedback portal, and this will be available in any of our upcoming updates. Thanks for the request new feature, you can track the status of the feature using our feedback portal from below.
 
https://www.syncfusion.com/feedback/9415
 
Thanks,
Dharani.

**Comment by sujalBandhara** [comment]
Thanks for the reply, We are waiting for the new updates.
