### ISSUE TITLE
SfDataGrid can't continues editting from keyboard

### ISSUE THREAD

**Issue by huemulDeveloper** [syncfusion/flutter-examples#441]
Hi!, I tried to edit cells only moving with the keyboard, but it's not possible to start editting other row without mouse tap.

Thank you!

**Comment by RenugaSadagoban98** [comment]
Hi @huemul,
 
We suspect that you are using Web or Desktop platforms. If you want to move the cells into edit mode through the keyboard, you can press the F2 key. We have ensured at our end. It's working fine at our end. Can you check at your end by pressing the F2 key?
 
If we misunderstood your requirement, please provide some more information about your requirement.

Regards,  
Renugadevi

**Comment by huemulDeveloper** [comment]
Hi @RenugaSadagoban98, 

That's right, i'm using Web platform, but my application try to make an "excel" like editting experience, i mean, move from one cell to another and just edit the cell without press any "function" key, there is some option to set that behavior?, 

thank you again!.

**Comment by RenugaSadagoban98** [comment]
Hi @huemulDeveloper , 
Thanks for your update. 
You can achieve it by using programmatic editing with onCurrentCellActivated callback. onCurrentCellActivated callback will be called whenever the currentcell is moved via mouse tap or keyboard navigation. In the below sample, we have called the DataGridController.beginEdit method inside the onCurrentCellActivated callback. To avoid the calling of editing programmatically when you tap or double tap the cell, we have introduced the bool flag named isCellTappedorDoubleTapped. We have called the programmatic editing via onCurrentCellActivated callback only if that bool flag is disabled.

Refer to the following code snippet,
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: SfDataGrid(
        source: employeeDataSource,
        allowEditing: true,
        onCurrentCellActivated: (RowColumnIndex currentRowColumnIndex,
            RowColumnIndex previousRowColumnIndex) {
          if (!isAppliedEditing) {
            _dataGridController.beginEdit(currentRowColumnIndex);
          }
          {
            isAppliedEditing = false;
          }
        },
        onCellTap: (details) {
          isAppliedEditing = true;
        },
        onCellDoubleTap: (details) {
          isAppliedEditing = true;
        },
        selectionMode: SelectionMode.single,
        navigationMode: GridNavigationMode.cell,
        columnWidthMode: ColumnWidthMode.fill,
        controller: _dataGridController,
        columns: <GridColumn>[
          GridColumn(
            columnName: 'id',
            label: Container(
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.centerRight,
              child: Text(
                'ID',
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
          GridColumn(
            columnName: 'name',
            label: Container(
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.centerLeft,
              child: Text(
                'Name',
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
          GridColumn(
            columnName: 'designation',
            label: Container(
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.centerLeft,
              child: Text(
                'Designation',
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
          GridColumn(
            columnName: 'salary',
            label: Container(
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.centerRight,
              child: Text(
                'Salary',
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
        ],
      ),
    );

```

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main_(2)-1680370809

Please check the above sample and revert us if you need future assistance on this.

Regards,
Renugadevi
