### ISSUE TITLE
datePicker onSubmit Usage docs

### ISSUE THREAD

**Issue by Jefry-nolastname** [syncfusion/flutter-examples#443]
just gonna leave this here in case someone needed it since the docs don't mention this :

SfDateRangePicker(
  backgroundColor: Colors.white,
  view: DateRangePickerView.month,
  monthViewSettings: DateRangePickerMonthViewSettings(firstDayOfWeek: 1),
  showActionButtons: true,
  onCancel: (){
    Navigator.pop(context);
  },
  onSubmit: (Object args){
    DateRangePickerSelectionChangedArgs a = DateRangePickerSelectionChangedArgs(args);
    print([a.value.startDate,a.value.endDate]);
  },
  selectionMode: DateRangePickerSelectionMode.range,
)

**Comment by yogithesymbian** [comment]
u save my life , thankyou

**Comment by Jefry-nolastname** [comment]
u'r welcome~
