### ISSUE TITLE
Empty Signature Pad

### ISSUE THREAD

**Issue by Ddimitrako** [syncfusion/flutter-examples#444]
How i can see if the Signature pad is empty without any drawned signature inside it.
I would like to notify users that the pad is empty before they submit the signature.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Ddimitrako, 
 
Greetings from Syncfusion support. 
 
You can check whether signature pad is empty or not using the onDrawStart callback. Here we have checked by specifying one flag in the onDrawStart callback. This flag is true only when the pad is empty. 

```dart
class _MyHomePageState extends State<MyHomePage> {

  final GlobalKey<SfSignaturePadState> _signaturePadKey = GlobalKey();

  bool hasPadEmpty = true;

  

  @override

  Widget build(BuildContext context) {

    return Scaffold(

      body: Column(

        children: [

          Container(

            child: SfSignaturePad(

              key: _signaturePadKey,

              onDrawStart: () {

                if (hasPadEmpty) {

                  hasPadEmpty = false;

                  return true;

                } else {

                  return false;

                }

              },

            ),

            height: 300,

            width: 300,

            color: Colors.grey,

          ),

          const SizedBox(height: 30),

          ElevatedButton(

            onPressed: () async {

              hasPadEmpty = true;

              _signaturePadKey.currentState!.clear();

            },

            child: const Text('Clear sign'),

          ),

        ],

      ),

    );

  }

} 
```

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/empty_signature_pad675201596  
 
We hope that the above solution will fulfill your requirement. Kindly let us know if your requirement is different from this. 
 
Regards, 
Lakshmi R.

**Comment by Ddimitrako** [comment]
Thank you so much this is the solution I was looking for.
It's pretty easy.
Best regard,
Dimitrakopoulos Dimitris


Στις Δευ, 27 Σεπ 2021, 14:50 ο χρήστης LakshmiRadhaKrishnan <
***@***.***> έγραψε:
