### ISSUE TITLE
Start and end time not taken into account in CalendarView.timelineMonth

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-examples#446]
when view is set to **CalendarView.timelineMonth**, start and end time are ignored, therefore appointments are displayed from 00:00 to 23:59

In the screenshot, 'Development Meeting' is set to 2 days from 09AM to 10AM but displayed as if from 00:00 to 23:59

![image](https://user-images.githubusercontent.com/16321223/134979492-7e414d92-4bd0-4e74-8972-97bec3cbae23.png)

I wanna end up with something like this

![image](https://user-images.githubusercontent.com/16321223/134981024-1b091de7-8c8f-4424-ba88-b83448b2d8ca.png)

we need to take into account start and end time of an appointment.

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for contacting Syncfusion support. 

Based on provided information we have checked the mentioned issue "Appointments are not considered time in the timelineMonth view", The month view and timeline Month view is indented for handling dates hence we are not considered a time for those views, and we are displaying the event for the given date. Other than these month and timeline month views, timeslot views were implemented based on the time value, in those views the appointments will be rendered based on the given date and time. 

Please refer to the following UG link for more information.  
https://help.syncfusion.com/flutter/calendar/timeslot-views
https://help.syncfusion.com/flutter/calendar/month-view

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by bismarabia** [comment]
it's very unfortunate not to have this kind of flexibility while it's highly needed. and events can have start/end time not just start/end date.

Take **Google Calendar** as an example.


Anyways, I've managed to come up with a hack to do so. I hope it will be useful for future readers.

- define cell width in **timeSlotViewSettings** as **TimeSlotViewSettings(timeIntervalWidth: _cellWidth)**
- call appointmentBuilder param
- provide a custom appointment as Container
- and provide margin in the left and right side of the container as a factor of _cellWidth.

example: 
_cellWidth * 1/2 --> will place the appointment in the middle.

**Comment by muthulakshmi-123** [comment]
Hi,

We are glad to know that the issue resolved at your end. Please get in touch with us if you would require any further assistance.

Regards,
Muthulakshmi K
