### ISSUE TITLE
Auto highlight tooltip.

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#45]
Hello is there any way to highlight default tooltip with out tap or click on chart for any particular data point?

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

Greetings from Syncfusion. Your requirement for showing the tooltip without tapping the chart area can be achieved using the **show** method of the tooltip. Here you need to pass the x and y logical pixels. If the data point is available in the specified location, then the tooltip will be shown. For more information on this approach, find the [user guide](https://help.syncfusion.com/flutter/chart/methods#show-method-in-tooltipbehavior). 

For your convenience, we have prepared a [sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/tooltip-1028757938). Here when you click on the Show Tooltip button, the tooltip will be displayed in the specified location.

If this is not your exact requirement, kindly revert us with more information which will be helpful in further analysis and provide you the solution sooner. 

Thanks,
Dharani.

**Comment by sujalBandhara** [comment]
Ok thanks for the updates, Is there any way to get all data points position after graph line draw?

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

We regret the delay. As of now, you can get the location of points using the **onTooltipRender** event. With the below code snippet, we have printed the location of the first point. You can change this based on your scenario.

>  
     SfCartesianChart(
        onTooltipRender: (TooltipArgs args){
          final int pointIndex = 0;
          print(args.dataPoints[pointIndex].region);
       },
    )

Thanks,
Dharani.
