### ISSUE TITLE
Error while trying to load an asset: Failed to load asset at "assets/packages/timezone/data/2020a.tzf" (404)

### ISSUE THREAD

**Issue by Mr-System32** [syncfusion/flutter-examples#450]
" Error while trying to load an asset: Failed to load asset at "assets/packages/timezone/data/2020a.tzf" (404) "
this error showing to me with web release , when I used SfCalendar and all event didn't appear this issue only when I hosting my site on IIS but when hosting on other online hosting it's working fine
plz help me .

My greetings.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked the “**Error while trying to load an asset: Failed to load asset at "assets/packages/timezone/data/2020a.tzf**” issue with simple sample hosting to Internet Information Service (IIS). We have ensured this issue using the Flutter version 2.2.3 and Syncfusion Calendar version as 19.3.43 and there is no issue related to time zone package. If possible, can you please check your project once and let us know if the time zone package was installed or not. It would be helpful for us to analyze and provide you a solution at the earliest.

![Picture1](https://user-images.githubusercontent.com/54974849/135830627-d9a6768e-dc7c-42a6-9589-4dc66b83988b.png)

Regarding Query: when I used SfCalendar and all event didn't appear this issue only when I hosting my site on IIS but when hosting on other online hosting it's working fine.

Also, while running the sample using an HTML renderer and it is not suitable for performance. So, we suggest you use the CanvasKit option for prioritizing the performance and pixel-perfect consistency. Kinldy refer the following links more details.

**Link:** 
https://flutter.dev/docs/development/tools/web-renderers

Kindly specify the MIME type for appearing the appointments while hosting to IIS. Please refer the following link more details.

**Link:** https://docs.microsoft.com/en-us/iis/configuration/system.webserver/staticcontent/mimemap 

![Screenshot (68)](https://user-images.githubusercontent.com/54974849/135830769-5a1ee031-9854-47cb-865c-b3ff4739c319.png)

Regards,
Indumathi R

**Comment by Mr-System32** [comment]
Thank you very much, issue solved

**Comment by madhubansahani** [comment]
thankyou so much its working now for me
