### ISSUE TITLE
Data grid sorting not working properly

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-examples#451]
DataGrid columns are not sorted properly

In this SS, sorting asc/desc are not showing up properly.

![image](https://user-images.githubusercontent.com/16321223/135871666-be920c62-4044-4eb1-bff8-b03c3dfaa242.png)

can you please check?

**Comment by Sangeetha-Raju1** [comment]
Hi Bismarabia,

Thank you for contacting Syncfusion support.

From the provided information, we have checked sorting when paging is applied in DataGrid. But we are not able to reproduce your reported issue. Its working fine at our end. 

![image](https://user-images.githubusercontent.com/72553823/136011583-5690ffc8-591f-4f41-b280-c6542136e776.png)
![image](https://user-images.githubusercontent.com/72553823/136011597-4ca94d0a-f7e3-4051-84eb-7f95fa192629.png)
![image](https://user-images.githubusercontent.com/72553823/136011615-e698deb3-ab63-4bb6-99f5-fd5d1fe4df72.png)

We have prepared a sample for your reference.
Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main166980349 

Please check the above sample and revert us if you still facing the same issue? If yes, please provide the following details, 
1.	Which Flutter channel (Stable, beta or Master) are you using? 
2.	Syncfusion version.
3.	Your emulator version or physical device details. 

If we misunderstood anything, please modify the above sample based on your requirement. It will be helpful for us to check on it and provide you the solution at the earliest.    

Regards,
Sangeetha Raju.

**Comment by bismarabia** [comment]
after a couple of minutes of debugging, I've found out the issue which is a mismatch  between GridColumn.columnName and DataGridCell.columnName, they have to be the same, I somehow missed that.

thank you team!
