### ISSUE TITLE
Group view resources into groups...

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-examples#453]
as state in the below Screenshot, I want to be able to group view resources into groups.

![image](https://user-images.githubusercontent.com/16321223/135983447-0955dc87-c5f3-4ef3-afe1-40bfb76cb3f2.png)

This is one use-case, let's say we have 3 blocks and each block has 4 floors, each floor will have some events in the calendar.

How do I achieve such a thing? if not yet implemented can we have a plan for this?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

We have analyzed and considered your requirement of “**Provide multi-resource support in the Flutter Calendar**” and we have logged a feature request for the same. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
We are closing this incident now. You can also communicate with us regarding the open features any time using our Feature Report page. 
 
Feedback link: https://www.syncfusion.com/feedback/29198/provide-a-multi-resource-support-in-the-flutter-event-calendar-sfcalendar
 
If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by bismarabia** [comment]
any update on this @JayavigneshwaranG ?
