### ISSUE TITLE
Calendar : Is there any options to make 3 days week view?

### ISSUE THREAD

**Issue by olegzaim** [syncfusion/flutter-examples#459]
Work week not a solution for me, because there is only an option for const: this.nonWorkingDays = const <int>[DateTime.saturday, DateTime.sunday]. So, I can't make workaround for 3 days view, because it's requires const array. It would be grateful if you can add an option like in the google calendar 3 days view.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Is there any options to make 3 days week view?**

Based on the shared information, we have checked and already considered your requirement as a feature for “**Showing 3 days view in the Flutter Calendar (SfCalendar)**” and we have logged the feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features at any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/27376/support-for-3-days-view-like-google-calendar 

If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
