### ISSUE TITLE
Gradient for SplineSeries Line.

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#46]
Hello is there any way to Gradient for SplineSeries Line of graph.

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

Greetings from Syncfusion. We would like to let you know that currently, we don’t have gradient support for spline type series, however when the gradient colors are applied, then the first color in the list will be applied for spline type series. We have also considered your requirement as a feature request and logged feature report in our feedback portal. The feature will be available in any of our upcoming updates and you can track the status from below feedback portal link.

https://www.syncfusion.com/feedback/9411

Thanks,
Dharani.

**Comment by sujalBandhara** [comment]
Ok thanks for the reply, we are waiting for the next update.

**Comment by sujalBandhara** [comment]
Could you please give us time for next update so we can plan accordingly.Because we are waiting for it.

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

As we stated earlier, the requested feature will be available in any of our upcoming releases. We would like to let you know that, we have already laid a roadmap for our current release and we are in progress of those. So, we can’t provide a definite timeline on this. For every release, we consider the features based on the customer’s requirement. Thus, you can track the status using our feedback portal.

Thanks,
Dharani.

**Comment by vishaldhaduk9986** [comment]
@dharanidharandharmasivam Could you please share the demo code of Gradient for SplineSeries Line.
