### ISSUE TITLE
Unable to add emoji in PDF

### ISSUE THREAD

**Issue by Vinayak-Bhanushali** [syncfusion/flutter-examples#460]
When writing a text with emoji to pdf it only writes the text and ignores the emojis.

I tried with the following fonts
- NotoColorEmoji.ttf
- NotoEmoji-Regular.ttf
- OpenSans-Regular.ttf

```
Future _readFonts() async {
    final ByteData data =
        await rootBundle.load('assets/fonts/NotoColorEmoji.ttf');
    return PdfTrueTypeFont(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
      double.parse(30),
    );
  }
```

```
font = await  _readFonts();
layer.graphics.drawString(
      "Hello World! 😄",
      font,
      brush: PdfBrushes.black,
      bounds: Rect.zero,
    );
```

**Comment by Anand3595** [comment]
Hi @Vinayak-Bhanushali ,

Thanks for contacting Syncfusion support.

As of now, we don’t have support to draw the emoji characters on PDF document. However, we will analyze further details and update you the details on 20th October, 2021.

Regards,
Anand Panchamoorthi

**Comment by Vinayak-Bhanushali** [comment]
Hi @Anand3595 ,

Thanks for the quick update. I can see that emojis are getting rendered now. Just had one last query, will the support for color from fonts be added?
