### ISSUE TITLE
QR code yellow background

### ISSUE THREAD

**Issue by vishwajit76** [syncfusion/flutter-examples#461]
I tried multiple government pan card PDF and most of pdf QR code is showed with yellow background. Also some PDF not opened and generate exception with message "Null check operator used on a null value".

current version used:
syncfusion_flutter_pdf: ^19.3.46-beta

This pdf file not opened.
[15112000 INSTANT (1).pdf](https://github.com/syncfusion/flutter-examples/files/7375875/15112000.INSTANT.1.pdf)
password - 15112000

PDF show QR Code with yellow background.(We also tried remove password at the same time, may be issue occured from that)
[24071988_UTI_(1).pdf](https://github.com/syncfusion/flutter-examples/files/7375896/24071988_UTI_.1.pdf)
![WhatsApp Image 2021-10-19 at 11 57 23 PM](https://user-images.githubusercontent.com/25575802/137969612-cefae7ab-5901-4521-b756-de7dc7cae88c.jpeg)

**Comment by Anand3595** [comment]
Hi @vishwajit76 ,

Thanks for contacting Syncfusion support.

We can reproduce the reported issue with "**_Null check exception thrown while removing password from encrypted PDF document_**" in our end. We will validate and update further details on 22nd October 2021.

However, we are not able to reproduce the barcode preservation issue in our end with provided PDF documents. Please provide the below details to validate further in this.
-	Complete code snippet to reproduce the issue based on the PDF creation or manipulation process.
-	Details about the viewer used to view the output PDF document.

Regards,
Anand Panchamoorthi

**Comment by vishwajit76** [comment]
QR with yellow background not solved in latest release version.
Thank you.

**Comment by SF2381** [comment]
Hi @vishwajit76 ,

**Query:** Null check exception thrown while removing password from encrypted PDF document

> **Response:** We have included the fix for an issue with "**_Null check exception thrown while removing password from encrypted PDF document_**" into our weekly release with version '[19.3.48-beta](https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.3.48-beta)'. Please check and let us know if you need any further assistance in this.

**Query:** PDF QR code showed with yellow background

> **Response:** We have tried to reproduce the QR barcode image preservation issue with details provided and still not able to reproduce in our end. As per the issue reported, we have ensured the QR barcode image preservation after removed encryption. But, the reported issue is not reproduced with PDF documents provided. Based on the last video, looks like the issue came from input encrypted PDF document itself.
> 
> We can have a web meeting to directly look into the issue in your machine and reproduce the issue with proper files and provided the solution at the earliest. Please let us know your availability for a web meeting, we will make every effort to have this scheduled at a time of your convenience.

Regards,
Anand Panchamoorthi

**Comment by vishwajit76** [comment]
Please check below pdf

[01011994 -UTI.pdf](https://github.com/syncfusion/flutter-examples/files/8177507/01011994.-UTI.pdf)
pass - 01011994

[518079700006153_signed.pdf](https://github.com/syncfusion/flutter-examples/files/8177515/518079700006153_signed.pdf)
pass - 11092003

Yellow background on web & android both platform.

**Comment by vishwajit76** [comment]
Yellow background still showing on qr in both platform Android and Web. Can
we discuss this issue on Google Meet. My gmail account is
***@***.*** and contact number is +918238394252.

Thanks for your support
