### ISSUE TITLE
How create recurrence rule: monthly on the last of month

### ISSUE THREAD

**Issue by vuonghuynhvncoder** [syncfusion/flutter-examples#467]
FREQ=MONTHLY;BYMONTHDAY=28,29,30,31;BYSETPOS=-1
not working

**Comment by vuonghuynhvncoder** [comment]
Thanks you for your support.
Could you explain solution for recurrence monthly on the last day of month?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We have considered your requirement as feature request for “**Providing a support for monthly recurring appointments on the last day of every month in the Flutter Calendar**”. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
 
Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using this Feature Report page. 

**Feedback link:** https://www.syncfusion.com/feedback/30049/providing-a-support-for-monthly-recurring-appointments-on-the-last-day-of-every 
  
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
