### ISSUE TITLE
Drag and drop for sfcalendar

### ISSUE THREAD

**Issue by Maria-Donosova** [syncfusion/flutter-examples#468]
Hi,

Is there a way to drag and drop tasks from the custom task list into timeslots in the calendar (converting external to sfcalendar tasks into appointments)?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

We have considered your requirement as feature request for “**Providing a external drag and drop support for appointments in the Calendar (SfCalendar)**”. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
 
Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using this Feature Report page. 

**Feedback link:** https://www.syncfusion.com/feedback/30050/providing-a-external-drag-and-drop-support-for-appointments-in-the-calendar 
  
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
