### ISSUE TITLE
[Calendar] How to customize Meeting card on Schedule view?

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-examples#469]
I need to create another widget with more fields and in other positions for the meeting card

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: How to customize Meeting card on Schedule view?**

Based on the shared information, we have checked and your requirement is “**Customize the appointments in the schedule view of the Flutter Calendar**”. We have a support for appointmentbuilder, using this you can design the own custom UI for appointments. Please find the UG documentation for the same.

**UG link:**  https://help.syncfusion.com/flutter/calendar/builders#appointment-builder

Please find the KB documentations for the same.

**KB link:**
https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-calendar

Also we have KB documentation for adding additional attributes to events in the Flutter Calendar. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12209/how-to-add-additional-attributes-in-events-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
