### ISSUE TITLE
is it right for version

### ISSUE THREAD

**Issue by hanxu317317** [syncfusion/flutter-examples#47]
the latest version is '17.3.14'.  it's ok??

**Comment by dharanidharandharmasivam** [comment]
hi @hanxu317317 ,

Yes, it is correct. This is our updated version and hereafter our release version will be followed by this type. Kindly get back to us if you have any concerns. You can find our chart versions [here](https://pub.dev/packages/syncfusion_flutter_charts/versions).

Thanks,
Dharani.
