### ISSUE TITLE
How to insert a chat in a pdf.

### ISSUE THREAD

**Issue by M-A-D-A-R-A** [syncfusion/flutter-examples#470]
Dear Syncfusion team,

I was working with your SDK and i want to insert a charts in my pdf. Im using both `syncfusion_flutter_charts` and `syncfusion_flutter_pdf` for making charts and pdf. If there is some sample code it will be very helpful. 

Thanks

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @M-A-D-A-R-A,

Greetings from Syncfusion. We have analyzed your query and we have already implemented exporting chart as pdf. We have attached the sample and user guide for your reference below.

Sample: https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/export.dart 

User guide: https://help.syncfusion.com/flutter/cartesian-charts/export-cartesian-chart#export-pdf 

Regards,
Yuvaraj.
