### ISSUE TITLE
[Calendar] Is there a way to show Week view

### ISSUE THREAD

**Issue by wmfadel** [syncfusion/flutter-examples#471]
I'm trying to show a week view but i can't find any paramter to set view to week, `DateRangePickerView` doesn't have week option, I'm trying to make this widget
![Screenshot 2021-11-02 132522](https://user-images.githubusercontent.com/32733023/139837819-1343d302-24d8-4c34-bece-288a06ef4b52.png)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Is there a way to show Week view.**

Yes , you can show the required weeks in the picker by using the property of **[numberOfWeeksInview](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthViewSettings/numberOfWeeksInView.html)** in **[DateRangePickerMonthViewSettings](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthViewSettings-class.html)**. 

Please find the UG documentation for the same.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/views#week-view

Also we have KB documentation for the same. Please find the KB from the following link.

**KB link:** https://www.syncfusion.com/kb/12167/how-to-change-the-number-of-weeks-in-the-flutter-date-range-picker-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by wmfadel** [comment]
Thank you.
