### ISSUE TITLE
[Date Range Picker] Custom animation duration when changing the month

### ISSUE THREAD

**Issue by evetechsolutions** [syncfusion/flutter-examples#472]
Hello! Thank you for this amazing package.

I'd like to customise the animation duration (and possibly curve) when changing the month view, I think it's this one:

    _animationController.duration = const Duration(milliseconds: 500);
    _animationController
        .forward()
        .then<dynamic>((dynamic value) => _updateNextView());
        
Is it possible to add a property to do it? Or is it already possible but I'm missing how to?

Thank you in advance!

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Custom animation duration when changing the month**

We regret to inform the as per the current implementation of the Flutter date range picker doesn’t have support to custom animation and customize the animation duration. Please let us know if you require any other assistance. We will be happy to assist you. 

Regards,
Indumathi R
