### ISSUE TITLE
Calendar: mobile platform appointment resize

### ISSUE THREAD

**Issue by darialvznd** [syncfusion/flutter-examples#473]
Is there is a way to add mobile platform appointment resizing?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Is there is a way to add mobile platform appointment resizing?**

We regret to inform you that as per the current implementation of the calendar, does not have support to resizing the appointments on the mobile platform. Please let us know if you require any other assistance. We will be happy to assist you. 

Regards,
Indumathi R

**Comment by darialvznd** [comment]
Planning any work on that?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We will prioritize the features every release based on the demands and we do not have an immediate plan to implement this feature and we will implement this feature in any of our upcoming release. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

You can track the current status of this feature request by the following link,

**Link:**  https://www.syncfusion.com/feedback/30674/provide-a-support-for-appointment-resizing-in-mobile-platform-of-flutter-calendar  

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
