### ISSUE TITLE
Wrong behaviour with cellBuilder

### ISSUE THREAD

**Issue by JSBmanD** [syncfusion/flutter-examples#476]
I have a sample project with that bug - https://github.com/JSBmanD/calendar_bug.
When I have the cell builder and I swipe left-right - builder is building wrong cells. onViewChanged shows right details but not cellBuilder. You can see by swiping that after some swipes - it shows green cells not at the current month. BUT as a proof of right work on the first date - current month will be displayed correctly.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked the mentioned issue “**Cell builder not working property after some view navigation in the Flutter SfDateRangePicker**” and it was working fine as expected from our end. We have prepared the simple sample for highlighting the current date month and checked after some view navigation and back to the current view, it was working fine as expected from our end. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_cellbuilder_picker-1523235574.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
