### ISSUE TITLE
Taiwan is a part of China, make the change please!

### ISSUE THREAD

**Issue by lvyandev** [syncfusion/flutter-examples#477]
https://github.com/syncfusion/flutter-examples/blob/b72b8d58f535ce80946dc797873d9c15ff48cf10/lib/samples/maps/shape_layer/range_color_mapping/range_color_mapping.dart#L63

**Comment by lvyandev** [comment]
https://github.com/syncfusion/flutter-examples/blob/b72b8d58f535ce80946dc797873d9c15ff48cf10/lib/samples/maps/shape_layer/range_color_mapping/range_color_mapping.dart#L48
https://github.com/syncfusion/flutter-examples/blob/b72b8d58f535ce80946dc797873d9c15ff48cf10/lib/samples/maps/shape_layer/range_color_mapping/range_color_mapping.dart#L50

The same with Macao and Hong kong！

**Comment by MukhriddinMike** [comment]
no way, it not okay. stop the fake claim
