### ISSUE TITLE
Appointment order issue AGAIN

### ISSUE THREAD

**Issue by MukhriddinMike** [syncfusion/flutter-examples#479]
Appointments order different. The trailing date and monthly view are showing different views.
<img src="https://i.ibb.co/jM5HcVS/Screenshot-1637204727.png" alt="first" title="wrong order" />

Please check dates 11th month 01 day and 10th month 01 trailing date

<img src="https://i.ibb.co/wYShLt5/Screenshot-1637204717.png" alt="first" title="correct order" />

when onTap event is clicked order is correct . Only problem is view on monthly calendar

**Comment by MukhriddinMike** [comment]
appointments.sort((a, b) => a["name"].compareTo(b["name"])); 
This is the only way I guess , Hopefully I will close the issue tomorrow. is this error or just thing that I forgot ??? I don't know, however I resolved by sorting each appointment.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Appointment order issue.**

Based on the shared information, we have checked the mentioned issue “**Appointment order issue in the Flutter Event Calendar**” and we are unable to reproduce the mentioned issue from our end. We have prepared sample based on the shared image and checked the issue, it was working fine as expected.  Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_calendar_(1)1482691914.zip

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with more details or if possible share the replication video from your side, it will be helpful for us to check on it and provide you solution at the earliest. 

Regards,
Indumathi R
