### ISSUE TITLE
Please create a plugin to extract text from ms word files and save the ms word file

### ISSUE THREAD

**Issue by alihassan143** [syncfusion/flutter-examples#480]

**Comment by dharanidharandharmasivam** [comment]
Hi @alihassan143 ,

Greetings from Syncfusion. We have analyzed your query and we are clear with your query regarding creating a plugin to extract text from MS word files, but we are unclear about saving the MS word file. Kindly share more information on your requirements like do you wish to open the MS word file and then edit and save the text or share your exact requirement, this will be helpful in further analysis and considering the request.

Thanks,
Dharani.

**Comment by alihassan143** [comment]
actually i means that like your syncfusion pdf pluign where we can extract text from pdf and get result in string just like that create plugin to extract text from ms word file and in saving ms file option just like create pdf file from string or images just like that we pass string or images etc and plugin generate ms word file and save in mobile storage

**Comment by ManikandanRavichandranSync** [comment]
Hi @alihassan143,

Thank you for your update.

We have a plan to implement the Word library for the Flutter platform next year, but we are not able to provide any concrete timeline for this. We will inform you with more details once we implemented this feature.

Regards,
Manikandan Ravichandran
