### ISSUE TITLE
Visual bug when last week of the month is selected

### ISSUE THREAD

**Issue by benjdero** [syncfusion/flutter-examples#481]
I chose this library because I need the user of my app to pick a week, so far the API and UI are great, I can let the user click on any day of the week and programmatically select the week.

But there is an edge bug sometimes, when the last week of the month is selected, the last day of the week is not highlighted correctly.

This is how the date picker should behave:
![Screenshot_20211119-092243](https://user-images.githubusercontent.com/24305945/142598845-b42bf65e-1c71-4dbd-882a-ef02d370e108.png)

This is the edge bug when selecting last week of some months:
![Screenshot_20211119-092203](https://user-images.githubusercontent.com/24305945/142598871-4adefd82-2048-4729-9194-07611a8e50b9.png)

Also, while we are at it, why is there so much trailing days shown for September? It should only show days 1 to 3 from November, not the days 4 to 10.
![Screenshot_20211119-092300](https://user-images.githubusercontent.com/24305945/142598882-236affdf-969a-4328-a5bd-aba1b358bad0.png)

Sample app to easily reproduce the bug:
https://github.com/benjdero/flutter_calendar_bug

**Comment by benjdero** [comment]
Another bug I just noticed is if the user put his finger on the screen and then move is finger to the top without removing it from the screen, it keep changing the selected date.

This behavior don't happen when the user move is finger to the bottom of the screen for whatever reason.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked mentioned issue “**Week selection of the selected day in the Flutter DateRangePicker**” and it was working fine as expected from our end. Also, we have prepared the sample with leading and trailing dates and week selection working properly. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/week-selection-date-range-picker-flutter-master766797703.zip 

We have a KB document for the same. Please find the documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/11412/how-to-select-a-week-in-the-flutter-date-range-picker-sfdaterangepicker 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by benjdero** [comment]
I've tweaked the sample code you linked and found the issue, it seems to be an edge case that happen when the Time component of the DateTime is not 00:00:000.

For example, using the exact sample code you shared, under the following lines:
```dart
    DateTime dat1 = date1.add(Duration(days: (firstDayOfWeek - day1)));
    DateTime dat2 = date2.add(Duration(days: (endDayOfWeek - day2)));
```

Add this line:
```dart
    DateTime dat1 = date1.add(Duration(days: (firstDayOfWeek - day1)));
    DateTime dat2 = date2.add(Duration(days: (endDayOfWeek - day2)));
    dat2 = DateTime(
        dat2.year,
        dat2.month,
        dat2.day,
        12
    );
```

And now if you select the last week of a month, the end day highlight is not showing up:
![Screenshot_20211123-141426](https://user-images.githubusercontent.com/24305945/143030750-2d6a155b-b65d-4bc4-88ab-6cc5e41c06ea.png)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Based on the code snippet, we have checked and we are able to produce the mentioned issue. Also, SfDateRangePicker control was worked based on date value, not time value. As of now for resolving this, kindly use the date without the time. In the meantime, we will fix the issue and include the issue fix in our upcoming Weekly Nuget package, which is expected to be rolled out on November 30, 2021, and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have fixed the mentioned issue “**Week selection of the selected day in the Flutter DateRangePicker not working properly for last week of month**” but stability-related testing takes more time than expected. Due to this, we are not including this fix in our November 30, 2021, weekly nuget release. We will include the issue fix in our upcoming Weekly Nuget package, which is expected to be rolled out on December 7, 2021, and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the issue fix for “**Week selection of the selected day in the Flutter DateRangePicker not working properly for last week of month**” in our latest Weekly nuget package **version 19.3.57**. Kindly update to the latest version for resolving issue. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_datepicker/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by benjdero** [comment]
I confirm the latest version 19.3.57 fix the bug. Thank you for your assistance.
