### ISSUE TITLE
is it possible to add max date range in SfDateRangePicker?

### ISSUE THREAD

**Issue by parmarravi** [syncfusion/flutter-examples#482]
I have a requirement in which I don't want to add more than 7 or 14 days when the user selects a date range.
How to achieve this?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Could you support rrule of calendar format by http://jakubroztocil.github.io/rrule/?**

We didn’t support for RRule from the mentioned link. We have UG documentation for recurrence rule properties and purposes. Please find the UG documentation from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/appointments#recurrence-rule

Also, calendar supports the RRule from the following rule generator.

**Link:** https://www.textmagic.com/free-tools/rrule-generator 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: is it possible to add max date range in SfDateRangePicker?**

As per the current implementation of the picker, we didn’t have support for restricting particular range selection in SfDateRangePicker, but your requirement can be achieved by sample level using **enableSwipeSelection** value as **false** and **onSelectionChanged** callback. We prepared a simple sample for achieving your exact requirement. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_rangeselection62157223.zip 

We hope that this helps you. If this is not your requirement can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
