### ISSUE TITLE
Could you support rrule of calendar format by http://jakubroztocil.github.io/rrule/?

### ISSUE THREAD

**Issue by vuonghuynhvncoder** [syncfusion/flutter-examples#483]
Hi Team

We are using rrule format http://jakubroztocil.github.io/rrule/, that is more than complex you using
Could you update to support it?
Like that: https://pub.dev/packages/rrule

Thanks,
Optisigns Inc

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Could you support rrule of calendar format by http://jakubroztocil.github.io/rrule/?**

We didn’t support for RRule from the mentioned link. We have UG documentation for recurrence rule properties and purposes. Please find the UG documentation from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/appointments#recurrence-rule

Also, calendar supports the RRule from the following rule generator.

**Link:** https://www.textmagic.com/free-tools/rrule-generator 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
