### ISSUE TITLE
How do I modify the contents of a cell in the resource view

### ISSUE THREAD

**Issue by DioboKN** [syncfusion/flutter-examples#484]
How do I modify the contents of a cell in the resource view

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: How do I modify the contents of a cell in the resource view**

Based on the provided information, we have checked and your requirement is “**Modify the content inside the resource view of the Flutter Calendar**”. In Calendar control we have provided support for custom view for resources and using this you can create your own custom widget for resources. We have UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#resource-view-header-builder

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DioboKN** [comment]
![1a0dda09d79eef56527a011a1ca640d](https://user-images.githubusercontent.com/52503667/143410922-be1cd00d-85d8-40d3-951a-ab1a7c21cb25.jpg)
I don't want to change the header, I want to change the style of the appointment cell

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: I don't want to change the header, I want to change the style of the appointment cell**

By using the **appointmentTextStyle** property you can change the style of the appointment text. Also, by using the **appointmentBuilder** property you can create a custom view for the appointment and you can add the required customization for the appointment cell. We have UG and KB documentation for the same.

**UG link:**
https://help.syncfusion.com/flutter/calendar/appointments#appearance-customization
https://help.syncfusion.com/flutter/calendar/builders#appointment-builder

**KB link:**
https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DioboKN** [comment]
How to adjust the position of the appointment in the cell

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: How to adjust the position of the appointment in the cell**

As per the implementation of the calendar, appointments are rendered based on the start time value of the event. By using the drag and drop, appointment resizing features you can change the timing of the appointment. We have a UG document for the same. Please find the UG from the following link.

**UG links:**
https://help.syncfusion.com/flutter/calendar/drag-drop
https://help.syncfusion.com/flutter/calendar/appointment-resizing

If the above shared information doesn’t meet your requirement, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by DioboKN** [comment]
How do I change the size of a cell in a resource view

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for the update.

**Regarding Query: How do I change the size of a cell in a resource view**

By using the property of size in ResourceViewSettings, you can change the size of the resource panel. We have UG documentation for the same. Please find the UG from the following link.

UG link:
https://help.syncfusion.com/flutter/calendar/resource-view#resource-panel-size

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DioboKN** [comment]
Hi, I have solved this problem, I want to know how to set appointment unclickable in resource view

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: I want to know how to set appointment unclickable in resource view**

As per the current implementation of the calendar doesn’t support unclickable of the appointment. Also by using the [enablePointerInteraction](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeRegion/enablePointerInteraction.html) value as false in the [specialRegions](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/specialRegions.html) property we can disable the interaction of the cell. We have UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/timeslot-views#selection-restriction-in-timeslots

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
