### ISSUE TITLE
Base 64 string

### ISSUE THREAD

**Issue by Ankit0080** [syncfusion/flutter-examples#485]
1.  What i am  trying to do is whatever the signature user is typing i want to have a base 64 string of that image. And when i have  base 64 string i want to convert it into image and show it inside signature pad

2. If user takes a gap while signing the pad then it takes the previous input only which was typed before the  gap . The final output should be independent of gap

**Comment by PraveenGopalsamy** [comment]
Hi Ankit0080,

Query 1: What i am trying to do is whatever the signature user is typing i want to have a base 64 string of that image. And when i have base 64 string i want to convert it into image and show it inside signature pad

Yes. You can save the signature as base64 image and also you can convert it into an image. We have attached code snippet for your reference. 

```
GlobalKey<SfSignaturePadState> _signaturePadKey = GlobalKey();
String base64Image = "";

@override
Widget build(BuildContext context) {
  return SafeArea(
    child: Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(),
      body: Center(
        child: SizedBox(
          height: 400,
          width: 300,
          child: Column(
            children: [
              SfSignaturePad(
                key: _signaturePadKey,
                backgroundColor: Colors.grey,
                strokeColor: Colors.white,
                minimumStrokeWidth: 2.0,
                maximumStrokeWidth: 4.0,
              ),
              ElevatedButton(
                  child: Text("Save signature to base64 string"),
                  onPressed: () async {
                    ui.Image data = await _signaturePadKey.currentState
                        .toImage(pixelRatio: 2.0);
                    final ByteData byteData =
                        await data.toByteData(format: ui.ImageByteFormat.png);
                    final Uint8List imageBytes = byteData.buffer.asUint8List(
                        byteData.offsetInBytes, byteData.lengthInBytes);
                    base64Image = base64Encode(imageBytes);
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text("Saved Signature as base64 string."),
                      duration: Duration(seconds: 01),
                    ));
                  }),
              ElevatedButton(
                child: Text("Show base64 string to Image"),
                onPressed: () async {
                  Uint8List imageBytes = base64.decode(base64Image);
                  if (kIsWeb) {
                    AnchorElement(
                        href:
                            'data:application/octet-stream;charset=utf-16le;base64,${base64.encode(imageBytes)}')
                      ..setAttribute('download', 'Output.jpg')
                      ..click();
                  } else {
                    final String path =
                        (await getApplicationSupportDirectory()).path;
                    final String fileName = Platform.isWindows
                        ? '$path\\Output.png'
                        : '$path/Output.png';
                    final File file = File(fileName);
                    await file.writeAsBytes(imageBytes, flush: true);
                    OpenFile.open(fileName);
                  }
                },
              ),
            ],
          ),
        ),
      ),
    ),
  );
}
```

Query 2: If user takes a gap while signing the pad then it takes the previous input only which was typed before the gap . The final output should be independent of gap

You can handle the interaction gap using the [onDrawStart](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad/onDrawStart.html), [onDraw](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad/onDraw.html), and [onDrawEnd ](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad/onDrawEnd.html)callbacks. Please go through the below user guide documentation to know more about these callbacks.
* https://help.syncfusion.com/flutter/signaturepad/getting-started#handle-ondrawstart-ondraw-and-ondrawend-callbacks

Please let us know if you need any further assistance in this.
 
Regards,
Praveen G.
