### ISSUE TITLE
[Calendar] Locale for 'All Day' label missing

### ISSUE THREAD

**Issue by IngeAlejandro** [syncfusion/flutter-examples#487]
All day label on schedule view is not transalated

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: All day label on schedule view is not translated**

The Flutter Calendar, doesn’t contain the all-day label text in the schedule view of the calendar and which text in the calendar do you mean All Day? If possible, can you please share your issue details clearly or share the illustration image of the issue, it would be helpful for us to analyze and provide you a solution at the earliest?  

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: All day label on schedule view is not transalated**

We are able to reproduce the mentioned issue “**All day label was not localized in Flutter Calendar (SfCalendar)**” and we have logged the issue report for the same. We will fix the issue and include the issue fix in our upcoming Weekly nuget package, which is expected to be rolled out by December 7, 2021 and let you know once the release rolled out. We appreciate your patience until then.

You can track the current status of this issue report  by the following link,

**Link:** https://www.syncfusion.com/feedback/30679/localization-not-working-for-allday-label-in-schedule-view-of-the-flutter-calendar

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the issue fix “**Allday label not localized in schedule view of the Flutter Calendar**” in our latest Weekly nuget package version 19.3.57. Kindly update to the latest version for resolving the issue. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions 

Please find the release notes from the following link.

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v19.3.0.57?type=all#sfcalendar-bug-fixes 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
