### ISSUE TITLE
[Calendar] is there a way to resize allDay appointment line?

### ISSUE THREAD

**Issue by darialvznd** [syncfusion/flutter-examples#489]
Is there a way to resize allDay appointment line in week view? I want blue line to be thinner 
![image](https://user-images.githubusercontent.com/62381498/143423159-f4f61aa2-4cee-4eca-b6c9-306817193978.png)

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query:  is there a way to resize allDay appointment line?** 

Based on the provide information, we suspect your requirement is “**Need to reduce the all day appointment height in the Flutter Calendar**”. As per the current implementation of the Flutter calendar, we didn’t have support to resize the height of all-day appointments. By default, in the all-day panel, we can show 4 appointments in day view and 3 appointments in week view, if the appointment is more than the specified count, we can show more appointment UI. Please find the attached image for the same.

![Picture1](https://user-images.githubusercontent.com/54974849/143571292-35176856-a7b1-4da0-b578-36c3a8724d15.jpg)

We hope that this helps you. Please get in touch with us if you would require any further assistance on this.

Regards,
Indumathi R
