### ISSUE TITLE
App Exits while Live update example is running

### ISSUE THREAD

**Issue by DiazGopar** [syncfusion/flutter-examples#49]
Running App in emulator, simulator, real device on Android or IOS, the APP crash while executing Live Update Example. Some times its get 15K+ point updates, sometimes not.

**Comment by dharanidharandharmasivam** [comment]
Hi @DiazGopar ,

Thanks for using our Syncfusion Flutter chart widget. We can replicate the reported scenario with the live update sample, and we have already logged feedback in our portal to improve the performance of the chart. This will be available in any of our upcoming updates and you can track the status this feature from the below feedback portal.

https://www.syncfusion.com/feedback/8277

Kindly get back to us if you have any concerns.

Thanks,
Dharani.

**Comment by DiazGopar** [comment]
Thanks for your fast response.

Your widgets are amazing.

**Comment by dharanidharandharmasivam** [comment]
Hi @DiazGopar ,

Thanks for your feedback. Feel free to get back to us if you have any queries. We are always happy in assisting you.

Thanks,
Dharani.
