### ISSUE TITLE
Change color of PieChart during animation of syncfusion_flutter_charts in flutter

### ISSUE THREAD

**Issue by efazalk** [syncfusion/flutter-examples#491]
I am trying to change the color of the circular bar series in syncfusion_flutter_charts package to change color during loading animation from 0 to 20 while

0=>5(color = red) then 
6=>10(color = yellow) then 
11=>15(color = green) then 
16=>20(color = blue)...

SfCircularChart(
        annotations: [
            CircularChartAnnotation(
                widget: const PhysicalModel(
                    child: SizedBox(width: 170, height: 170),
                    shape: BoxShape.circle,
                    elevation: 4,
                    shadowColor: Colors.black,
                    color: Color.fromRGBO(230, 230, 230, 1)),
            ),
        ],
        legend: Legend(
            overflowMode: LegendItemOverflowMode.wrap),
        palette: [colorData(today)],
        series: [
            RadialBarSeries(
            dataSource: _chartData,
            xValueMapper: (GDPData data, _) =>
                data.continent,
            yValueMapper: (GDPData data, _) => data.gdp,
            trackColor: Colors.grey.shade200,
            radius: '50',
            animationDuration: 2000,
            animationDelay: 800,
            innerRadius: '85',
            maximumValue: 20)
        ],
    ),

![chart](https://user-images.githubusercontent.com/27408112/143468380-d4d1749d-d8fa-4301-bfe0-7249a18cc1d0.gif)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @efazalk,

Greetings from Syncfusion. We have analyzed your scenario at our end and we would like to let you know that currently, we do not have support in our circular chart widget to dynamically change the color of the radial bar segment while the animation is being performed. However, there only two possibilities to set the color for the radial bar series data points, you can either directly set the color for the points using the palette option or you can use the pointColorMapper to set different colors for each radial bar data points in the chart.

For further reference on the radial bar series, you can refer the use guide link below.
https://help.syncfusion.com/flutter/circular-charts/chart-types/radial-bar-chart

Regards,
Sriram Kiran
