### ISSUE TITLE
[SfDateRangePicker] need custom cancel, submit and today style

### ISSUE THREAD

**Issue by yogithesymbian** [syncfusion/flutter-examples#492]
anyone know how to custome cancel, submit and today style ( color ) 
```
showActionButtons: true,
toggleDaySelection: true,
cancelText: 'CANCEL', // **need to change color to red**
confirmText: 'SUBMIT',
```
or what function / programatically for **cancel** and **today** clicked ? 

https://www.syncfusion.com/kb/12546/how-to-confirm-or-cancel-the-selection-in-the-flutter-date-range-picker

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: need custom cancel, submit and today style**

Based on the shared information, we have checked and your requirement is “**Change the color of action buttons and today button in SfDateRangePicker**”. By using the todayHighLightColor property, you can change the action buttons color and today button color. We have attached the code snippet for the same. Please find the code snippet from the following link.

**Code snippet:**
```
child: SfDateRangePicker(
  view: DateRangePickerView.month,
  selectionMode: DateRangePickerSelectionMode.range,
  showActionButtons: true,
  cancelText: 'CANCEL',
  confirmText: 'OK',
  todayHighlightColor: Colors.greenAccent,
  showTodayButton: true,
  onCancel: () {
    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
      content: Text(
        'Selection Cancelled',
      ),
      duration: Duration(milliseconds: 500),
    ));
  },
  onSubmit: (Object value) {
    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
      content: Text(
        'Selection Confirmed',
      ),
      duration: Duration(milliseconds: 500),
    ));
  },
),
```

**Screenshot:**
![vidma_recorder_26112021_150721](https://user-images.githubusercontent.com/54974849/143560723-97a0ecef-52e6-486f-a17e-8f9a095853a2.jpg)

**Regarding Query: What function / programatically for cancel and today clicked ?**

When clicking the today button allows you to navigate to the today date easily and when clicking the cancel button it notifies the selection was canceled through this button and submit button notifies the selection confirmed. We have documentation for the same.

Please find the documentation from the following link.

https://help.syncfusion.com/flutter/daterangepicker/getting-started#action-buttons 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by yogithesymbian** [comment]
thanks for the answer

nice .. but its global color right ? 
that's mean i can't change _'cancel' to the red colour_ 
and _'ok' for green color_ 
and _'today' is black.shade 300 color ,_ 
```diff
+ 'ok'
- 'cancel'
'today'
```

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. As per the current implementation of the picker, we didn’t provide a separate color for action buttons. Please get in touch with us if you require any further assistance. We will be happy to assist you.

Regards,
Indumathi R
