### ISSUE TITLE
[Calendar] Provide Scroll Controller to calendar 

### ISSUE THREAD

**Issue by darialvznd** [syncfusion/flutter-examples#493]
Is there a way to provide scroll controller to calendar? I have a problem with week view calendar, when i want page be scrolled when calendar scrolled to end. Now i need to tap on other that calendar screen area to scroll page

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Provide Scroll Controller to calendar**

Based on the provided information, we have checked and your requirement is “Providing a Scroll controller support to Calendar”. As of now, the calendar doesn’t have support for Scroll Controller. Can you please share your exact requirement for using the scroll controller in the Calendar? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
