### ISSUE TITLE
How to change Week Index Text and  year-month format in chinese

### ISSUE THREAD

**Issue by Go-oG** [syncfusion/flutter-examples#494]

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: How to change Week Index Text and year-month format in Chinese**

Flutter Calendar and DateRangePicker have a support to localization. By using the Syncfusion_localizations package you can localize the **WEEK** text in the SfCalendar control based on the corresponding language. We have prepared the simple sample for the same. Please find the sample from the following link.

Sample link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/localization-date-range-picker-flutter-master_(1)-778565398.zip

We have a UG documentation for header date format. Please find the documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/headers#header-date-format

Also, if possible can you please share your requirement is in SfCalendar or SfDateRangePicker? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
