### ISSUE TITLE
how to select multi-cell 

### ISSUE THREAD

**Issue by AbdOoSaed** [syncfusion/flutter-examples#495]
## Like this

`SfCalendar`

https://user-images.githubusercontent.com/33700292/144071163-4731b0bc-746e-4f70-ac4c-1aadfa6a7ab1.mp4

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: how to select multi-cell** 

We have already logged the feature request for “Multiple time slot selection in the Flutter Calendar (SfCalendar)”. We will implement this feature in any of our upcoming releases.

 At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:**
https://www.syncfusion.com/feedback/16322/support-for-multiple-time-slot-selection-in-the-flutter-event-calendar-sfcalendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
