### ISSUE TITLE
[calendar] provide selection resize to calendar controller

### ISSUE THREAD

**Issue by darialvznd** [syncfusion/flutter-examples#498]
i know that now in mobile platform you can select only one cell and cannot resize selection, but it would be good if you prodive this feature to calendar controller, so we could make our own buttons to expand selection 
as far as i know now you can only change first selection date, and selection default a hour long

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

We have analyzed and considered your requirement of “**Selection resizing support for calendar cells**” in Flutter Calendar and we have already logged feature request for the same. We will implement this feature in any of our upcoming release. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/28129/create-event-by-resizing-and-dragging-on-empty-slot-of-calendar 
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
