### ISSUE TITLE
Event Calendar possible for Hijri Calender/dates?

### ISSUE THREAD

**Issue by shero1111** [syncfusion/flutter-examples#499]
Is this possible? Or is just the grogrean calendar supported for event calendar?

Thanks in advanced.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked and your requirement is “**Hijri Shamsi or Jalalian Calendar support**”. We have already logged the feature requests for the We will implement this feature any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
**Feedback link:** https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar

Also, we have logged the feature requests for Shamsi and Ghamari calendar. We will implement this feature in any of our upcoming releases.

You can also communicate with us regarding the open features any time using our Feature Report page.  

**Feedback link:** https://www.syncfusion.com/feedback/22657/providing-a-support-for-shamsi-ghamari-calendar-in-the-flutter-event-calendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
