### ISSUE TITLE
tooltip data outside plot

### ISSUE THREAD

**Issue by deedos** [syncfusion/flutter-examples#5]
Hi, thanks for this wonderful project! The best chart library for flutter!
I 'm wondering if it's possible to have the data which is shown inside tooltips, rendered outside the plot, inside another widget for example. Something similar to this https://google.github.io/charts/flutter/example/behaviors/selection_callback_example.html

Thanks in advance

**Comment by JayavigneshwaranG** [comment]
Hi @deedos ,

Thanks for trying our Flutter widgets and providing the feedback.

Yes, your requirement can be achieved using ‘**onTrackballPositionChanging**’ event. In this event, you can get the values displayed in the toolltip on tap and you can assign that to any other widgets. Please find the code snippet for this. Here we have set this to the text widget.

> [Dart]
onTrackballPositionChanging: (TrackballArgs args) {
    final TextWidgetState state = textKey.currentState;
    state.textValue = args.chartPointInfo.label;
}

![image](https://user-images.githubusercontent.com/19405163/62468060-c0e7f700-b7b2-11e9-9300-1ceb52c4cd9c.png)


Attached the example project below for your reference.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample1267654338.zip

Thus I am closing this issue now. Please let us know if you have any concerns.

Thanks,
Jayavigneshwaran
