### ISSUE TITLE
is project opensource ? 

### ISSUE THREAD

**Issue by tbm98** [syncfusion/flutter-examples#50]
is project opensource and anyone can reuse it :D

**Comment by dharanidharandharmasivam** [comment]
Hi @tbm98 ,

Greetings from Syncfusion. Yes, the project is open source. However, if you wish to use our Syncfusion Flutter Widgets in your project, you must have a valid license key. You should have a trial version key or a purchased key or a community license. Please refer to the below links to know more about licensing.

https://github.com/syncfusion/flutter-examples/blob/master/LICENSE 
https://www.syncfusion.com/sales/products/flutter 
https://www.syncfusion.com/products/communitylicense

Kindly get back to us if you have any concerns.

Thanks,
Dharani.

**Comment by tbm98** [comment]
@dharanidharandharmasivam  yep. Thank you for your information
