### ISSUE TITLE
does this package is free

### ISSUE THREAD

**Issue by hdamis** [syncfusion/flutter-examples#500]
Hi,
can I use this package without a commercial license. 
Thanks

**Comment by SriramKiranSenthilkumar** [comment]
Hi @hdamis,

Greetings from Syncfusion. to use our package in your production app, it is mandatory to have a license. It can be either a Syncfusion community license or the Syncfusion commercial license.   
 
To be qualified for the Syncfusion Community License Program you must have gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization and agree to be bound by Syncfusion’s terms and conditions. If you are not qualified for the community license, you can contact sales@syncfusion.com for commercial licensing options.   
 
https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/LICENSE 
https://www.syncfusion.com/sales/products 
https://www.syncfusion.com/products/communitylicense 
 
Regards, 
Sriram Kiran

**Comment by Taymindis** [comment]
> is it free after version 18.3.0.x. ? This [link](https://help.syncfusion.com/flutter/licensing/overview) says that we are no longer required to add a license key.

I still got the community license key, where should I put this key?
