### ISSUE TITLE
Vertical scroll not working when there is sfcalender

### ISSUE THREAD

**Issue by jitheshshetty55** [syncfusion/flutter-examples#501]
Hello,

I have been using syncfusion_flutter_datepicker: ^19.3.56 , and i found the issue as when i wrap the datepicker inside a singlechildscrollview as we have other contents in the page too , so when i try to scroll upon the calender as there are content below to be viewed but it doesnot scroll atall .
Can you please check on the same and let us know a solution for this issue

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked the mentioned issue “**Vertical scroll not working while wrap the picker inside the SingleChildScrollView**”. We have prepared the simple sample to picker with SfDateRangePicker and Text widgets inside the SingleChildScrollView and the vertical scroll working fine as expected from our end. Please find the sample from the following link.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_singlechildscrollview918725590.zip

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with following details,

•	Issue replication video.
•	Code snippet
•	Issue replication scenario

It will be helpful for us to check on it and provide you solution at the earliest.

Regards,
Indumathi R

**Comment by jitheshshetty55** [comment]
Hello,

Thanks for the update. And I ran the sample you had sent

My requirement is as follows : when I fling my finger vertically on the calendar, it interacts with the calendar. But I want it to scroll the SingleChildScrollView when you fling vertically on the calendar, instead of paging through the dates on the calendar.

So then I set the navigationDirection to horizontal and I found that it works fine though 
Then i set the mode of the calender to Range and tried to scroll over the datepicker Inorder scrolldown through the singlechildscrollview it doesnot work

But if the mode is set to single it works

Sample code as follows:

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';

void main() => runApp(const SingleChildScrollViewWidget());

class SingleChildScrollViewWidget extends StatefulWidget {
  const SingleChildScrollViewWidget({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => ScrollView();
}

class ScrollView extends State<SingleChildScrollViewWidget> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: SingleChildScrollView(
            child: Column(
              children: [
                SfDateRangePicker(
                  navigationDirection: DateRangePickerNavigationDirection.horizontal,
                  selectionMode: DateRangePickerSelectionMode.range,
                ),
                const SizedBox(height:500,
                  child: Text("Scrollview"),
                ),
                SfDateRangePicker(
                  navigationDirection: DateRangePickerNavigationDirection.horizontal,
                  selectionMode: DateRangePickerSelectionMode.single,
                ),
                const SizedBox(height:500,
                  child: Text("Scrollview"),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

Based on the code snippet, we have checked the mentioned issue “**Scroll not working when place the SfDateRangePicker inside the SingleChildScrollView with range selection mode**”. By set the [enableSwipeSelection ](https://help.syncfusion.com/flutter/daterangepicker/selections#enable-swipe-selection)value as false, we can scroll the picker inside the SingleChildScrollView. We have modified the sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_singlechildscrollview_(1)-892274283.zip

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with more details.

Regards,
Indumathi R

**Comment by jitheshshetty55** [comment]
Yes thanks this works fine
