### ISSUE TITLE
Can't Change Selected Date Font Color

### ISSUE THREAD

**Issue by bishalimtiaz** [syncfusion/flutter-examples#503]
I am using SfCalendar in my flutter app. I used custom selectionDecoration. But whenever I use color for decoration it hides the selected date text. And also there is no property for changing the selected date font color.

`
SfCalendar(
      initialSelectedDate: DateTime.now(),
      selectionDecoration: const BoxDecoration(
        color: AppColors.timeslotColor,
        shape: BoxShape.circle,
      ),
      view: CalendarView.month,
      showNavigationArrow: true,
      todayHighlightColor: Colors.transparent,
      cellBorderColor: Colors.transparent,
      headerStyle: const CalendarHeaderStyle(
        textAlign: TextAlign.center,
      ),
    )
`
![Screenshot_1640173986](https://user-images.githubusercontent.com/31902309/147089471-041716f9-ed3e-4304-8749-254fa4305134.png)

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: Can't Change Selected Date Font Color**

Based on the shared information, we have checked the issue “**Unable to change the selected date font color in SfCalendar**”. As per the current implementation behavior of the calendar, selection decoration applies for the cell and we are unable to provide the color for the selected date. Also, by using the **SfDateRangePicker** control, you can customize the selected dates. We have UG documentation for the same. Please find the UG from the following link.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/customizations#selection-cell-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
