### ISSUE TITLE
how to add multiple image

### ISSUE THREAD

**Issue by codermonk1** [syncfusion/flutter-examples#504]
how to add multiple image in pdf

and how to add image base64 string to pdf

**Comment by Surya-3013** [comment]
Hi codermonk1,

We created the sample code snippet to add ‘n’-number of images in PDF document with image base64 string. Kindly try with the following code snippet and let us know the result,

```
//Create a new PDF document
PdfDocument document = PdfDocument();

//Add 'n'- no of images in PDF document.
int n = 3;
for (int i = 0; i < n; i++) {
  //Adds a page to the document
  PdfPage page = document.pages.add();
  //Get image base64 string from files and load it.
  String imageString = base64Encode(File(
          "image.png")
      .readAsBytesSync());
  //Add image base64 string to the PDF.
  PdfImage image = PdfBitmap.fromBase64String(imageString);
  page.graphics.drawImage(
      image,
      Rect.fromLTWH(
          0, 0, page.getClientSize().width, page.getClientSize().height));
}

//Saves the document
File('Output.pdf').writeAsBytes(document.save());

//Disposes the document
document.dispose();

```
Note: Based on the bounds(specific image size and location to add at PDF), you can add multiple images in the PDF document. And this KB: https://www.syncfusion.com/kb/11965/how-to-convert-image-to-pdf-in-syncfusion-flutter-pdf-library will explain step by step to add an image in PDF document.

Kindly refer to the following links to get more details,
https://help.syncfusion.com/flutter/pdf/working-with-images

Regards,
Surya V
