### ISSUE TITLE
[calendar] support for swlwction resize like Google Calendar

### ISSUE THREAD

**Issue by darialvznd** [syncfusion/flutter-examples#505]
hello
is there a way to add selection resize like google calendar? to make selection more than minimum range 
![image](https://user-images.githubusercontent.com/62381498/147566553-f06e2b65-a16f-44b3-a06b-776a7f22c2d3.png)

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

We have already considered your requirement of “Selection resizing support for calendar cells” **in** Flutter Calendar as a feature and logged the feature request for the same. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/28129/create-event-by-resizing-and-dragging-on-empty-slot-of-calendar 
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
