### ISSUE TITLE
support Jalali Calendar for agenda

### ISSUE THREAD

**Issue by behinesazan** [syncfusion/flutter-examples#506]
please update and support Jalali Calendar for agenda. 
if yes, can you tell us how long dose it take for you to add this feature?

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

We have already logged the feature request for “**Providing a support for jalali and Hijri calendar in the flutter event calendar**”. We will prioritize the features every release based on the demands, and we don’t have an immediate plan to implement this feature and we will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

You can also communicate with us regarding the open features any time using our Feature Report page.  
  
**Feedback link:** https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
