### ISSUE TITLE
Please Add support in gif images in syncfusion_flutter_pdf  to create document

### ISSUE THREAD

**Issue by alihassan143** [syncfusion/flutter-examples#507]
please add the gif images support to create pdf in flutter

**Comment by Surya-3013** [comment]
Hi @alihassan143 ,

Currently we don’t have support to add gif images in Flutter PDF. We have logged a feature request for this support in the Flutter PDF document. We do not have any immediate plans to implement these features. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.

Please find the feedback link to track the implementation of the feature below.
https://www.syncfusion.com/feedback/31594/add-the-gif-images-support-in-flutter-pdf

Regards,
Surya V

**Comment by alihassan143** [comment]
gif images support is added in the plugin?
