### ISSUE TITLE
[SfDateRangePicker] need change date position

### ISSUE THREAD

**Issue by MinhNguyen1204** [syncfusion/flutter-examples#508]
How can i change date position? I want Monday to appear in the first and Sunday to apppear last. 
Thanks

<img width="325" alt="Screen Shot 2022-01-01 at 11 19 18" src="https://user-images.githubusercontent.com/38999818/147843945-35711eef-af9c-49bf-a02c-097ccbf5d85c.png">

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: How can I change date position?**

Based on the shared information, we have checked and your requirement is “**Need to change the first day of the week in Flutter date range picker (SfDateRangePicker)**”. By using the [firstDayOfWeek ](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthViewSettings/firstDayOfWeek.html)property you can change the position of the first day of the week. We have UG and KB documentations for the same. Please fine the UG and KB document from the following link.

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/getting-started#change-first-day-of-week 

**KB link:**
https://www.syncfusion.com/kb/12221/how-to-change-the-first-day-of-week-in-the-flutter-date-range-picker-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by MinhNguyen1204** [comment]
That works for me, thank you so much
