### ISSUE TITLE
Provide onTap callbacks on Appointments during tests

### ISSUE THREAD

**Issue by S0NN1** [syncfusion/flutter-examples#510]
Hi, I was testing my app which uses SFCalendar to display certain Tasks.

I implemented dialogs when tapping on my Appointments and I wanted to simulate the user's tap, the only problem is that, given a `Key`, the finder used by my tester to tap the widget is not pressing the appointment.

It would be very appreciated to expose a callback to the `onTap` attribute during tests.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query:  onTap callbacks on Appointments during test.**

Based on the shared information, we are unable to understand your requirement clearly. But we have checked with the appointment builder and the onTap callback working fine as expected. If possible, can you please share your issue or requirement details clearly with an illustration image? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by S0NN1** [comment]
Let's say I have a SFCalendar widget in my page like this one
```dart
...
 child: SfCalendar(
        key: const Key('groupCalendar'),
        //tasks filling
        dataSource:
            snapshot.data!.activeTasks.isNotEmpty
                ? TaskDataSource(
                    snapshot.data!.activeTasks)
                : null,
        onTap: (CalendarTapDetails details) {
         // Do something
        },
...
```
If I want to replicate the `onTap` method during my widget integration tests using the key of the SFCalendar, the tester fails to click on the appointments and I can't test the onTap method behavior:

```dart
...
testWidgets('Renders GroupPage with Calendar tap', (tester) async {
        await tester.pumpWidget(MaterialApp(home: MyCalendarpage));
        await tester.pumpAndSettle();
        // I want to tap on an Appointment but this tap is replicated on the calendar instead
        await tester.tap(find.byKey(const Key('groupCalendar')));
});
...
```

**Comment by S0NN1** [comment]
I apologize, I wrongly closed the issue, the last message I wrote describes exactly the main issue when testing your widgets.
I notice there is no reliable method to ensure that appointments displayed in your calendar are tapped, nor it is explained in your docs.

**Comment by S0NN1** [comment]
@Indumathi1195R Did you investigate the issue?

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for the update.

Regarding Query: I notice there is no reliable method to ensure that appointments displayed in your calendar are tapped, nor it is explained in your docs.

We have a method for getting appointments such as visible appointment using getVisibleAppointments, getOccurenceAppointment and getPatternAppointmentDetails. Please refer the UG link for the same.

**Code snippet:**

```
test('Appointments’, () {
      final DateTime startDate = DateTime(2016, 01, 04, 03, 0, 0);
      final _AppointmentDataSource _dataSource =
          _AppointmentDataSource(<Appointment>[appointment3]);
      final List<Appointment> visibleAppointments =
          _dataSource.getVisibleAppointments(startDate, '');
      expect(visibleAppointments.length, 1);
    });
```

**UG link:**
https://help.syncfusion.com/flutter/calendar/appointments#get-visible-appointments 
https://help.syncfusion.com/flutter/calendar/appointments#get-occurrence-appointment 
https://help.syncfusion.com/flutter/calendar/appointments#get-pattern-appointment 

We hope that this helps you. If this is not your requirement, please share more details about your requirement clearly. It would be helpful for us to analyze and provide you with a solution at the earliest.

Regards,
Indumathi R

**Comment by S0NN1** [comment]
> Hi Team,
> 
> Thank you for the update.
> 
> Regarding Query: I notice there is no reliable method to ensure that appointments displayed in your calendar are tapped, nor it is explained in your docs.
> 
> We have a method for getting appointments such as visible appointment using getVisibleAppointments, getOccurenceAppointment and getPatternAppointmentDetails. Please refer the UG link for the same.
> 
> **Code snippet:**
> 
> ```
> test('Appointments’, () {
>       final DateTime startDate = DateTime(2016, 01, 04, 03, 0, 0);
>       final _AppointmentDataSource _dataSource =
>           _AppointmentDataSource(<Appointment>[appointment3]);
>       final List<Appointment> visibleAppointments =
>           _dataSource.getVisibleAppointments(startDate, '');
>       expect(visibleAppointments.length, 1);
>     });
> ```
> 
> **UG link:** https://help.syncfusion.com/flutter/calendar/appointments#get-visible-appointments https://help.syncfusion.com/flutter/calendar/appointments#get-occurrence-appointment https://help.syncfusion.com/flutter/calendar/appointments#get-pattern-appointment
> 
> We hope that this helps you. If this is not your requirement, please share more details about your requirement clearly. It would be helpful for us to analyze and provide you with a solution at the earliest.
> 
> Regards, Indumathi R

@Indumathi1195R this is not helpful, because I'm not doing unit testing but integration testing.
That method is not accessible  while testing an app's behaviour.
```dart
testWidgets('Renders GroupPage with Calendar tap with delete task (IOS)',
        (tester) async {
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('groupCalendar')));
        // tester does not hit any appointments from here and test fails
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('closeDetailsButton')));
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('groupCalendar')));
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('deleteTaskButton')));
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('noDeleteHaskgroup')));
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('groupCalendar')),
            warnIfMissed: false);
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('deleteTaskButton')));
        await tester.pumpAndSettle();
        await tester.tap(find.byKey(const Key('yesDeleteHaskgroup')));
        await tester.pump();
      });
      debugDefaultTargetPlatformOverride = null;
    });
    ```
    As you can see from the code above without providing a key or any sort of identifier to each appointment the method ` await tester.tap(find.byKey(const Key('groupCalendar'))); ` tries to click on the calendar itself and not on a single Appointment.
    
    Each of my appointments opens a dialog to show information about them and I need to test that, without a method to mock this action or any interface to access appointments directly, proper integration testing is not possible using your widgets.

**Comment by Indumathi1195R** [comment]
Hi,

By using the [appointmentBuilder ](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/appointmentBuilder.html)with the **Key** value you can able to tap the appointments in testing. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/getting-event-details-calendar-fluter-master2027187265.zip 

**Code snippet:**
```
widget_test.dart

import 'package:flutter/material.dart';
import 'package:flutter_appointmentdetails/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Calendar Test 3', (WidgetTester tester) async {
    await tester.pumpWidget(CalendarApp());
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('appointment')));
  });
}

main.dart

child: SfCalendar(
  key: const Key('calendar'),
  view: CalendarView.week,
  monthViewSettings: MonthViewSettings(showAgenda: true),
  dataSource: _dataSource,
  appointmentBuilder: appointmentBuilder,
      onTap: calendarTapped,
),

Widget appointmentBuilder(BuildContext context,
    CalendarAppointmentDetails calendarAppointmentDetails) {
  final Meeting meeting = calendarAppointmentDetails.appointments.first;
  return Container(
    color: meeting.background,
    key: const Key('appointment'),
    child: Text(meeting.eventName),
  );
}
```
We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
