### ISSUE TITLE
Resources in CalendarView.day

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [syncfusion/flutter-examples#511]
Hey guys, thx for awesome plugin. Can you please implement this feature, I think it looks a lot cleaner when we have resources at the top like in a screenshot below.
![IMG_1408](https://user-images.githubusercontent.com/36572426/148820211-e6614327-8c10-4fb9-a7a8-8bf74f73a831.PNG)

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Based on the shared information and image, we have checked and your requirement is “**Horizontal Resource grouping support in the Flutter event calendar (SfCalendar)**”. We have already logged the feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/15067/horizontal-resource-grouping-support-in-the-flutter-event-calendar-sfcalendar
 
If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
