### ISSUE TITLE
Allow Special Regions on Month View

### ISSUE THREAD

**Issue by Mabenan** [syncfusion/flutter-examples#512]
At the moment it is only possible to display special regions when the visible day count is below or equal 7.
This restrictions is not very understandable and it would be nice to remove them.
I tested locally by removing the restriction in the timeline_view.dart file in line 184 and it worked for me.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked and your requirement is “**Special time regions support for month and timeline month view in Calendar**”. As per the current implementation of the calendar, we don’t have support for specialTimeRegions in month and timeline month view. Kindly use [blackoutDates](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/blackoutDates.html) for your requirement. Please find the UG documentation for the same.

**UG link:** https://help.syncfusion.com/flutter/calendar/month-view#blackout-dates 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
