### ISSUE TITLE
BUG: When tapping on DatePicker onTap function gets called

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [syncfusion/flutter-examples#513]
There is a bug when clicking on Date Picker, it calls onTap function. When I hold longer instead of just tapping then its working as expected. 
I think that onTap function should be only for events in calendar not for header.

syncfusion_flutter_calendar: ^19.4.41
Flutter version 2.5.3
Tested on real iOS device

https://user-images.githubusercontent.com/36572426/148933580-ce9388e2-b38a-4c64-90a2-4ddffa411fdf.MP4

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: I think that onTap function should be only for events in calendar not for header.**

As per the calendar implementation, we can restrict the **onTap** callback triggering while tapping the header and that element is related to calendar control, not date range picker. But you can prevent this by using the code snippet below.

**Code snippet:**

```
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child:  SfCalendar(
            onTap: calendarTapped,
          )
        ),
      ),
    );
  }
 
void calendarTapped(CalendarTapDetails calendarTapDetails) {
  if (calendarTapDetails.targetElement == CalendarElement.header) {
    return;
  }
}
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by aleksandar-radivojevic** [comment]
Thanks Indumathi, this helped me.
