### ISSUE TITLE
the document don´t show a signature

### ISSUE THREAD

**Issue by duki97** [syncfusion/flutter-examples#514]
I have a document that is already signed and that signature is not shown

**Comment by PraveenGopalsamy** [comment]
Hi duki97,
 
Using the SignaturePad widget, you can save the signatures as images and use the images in documents that need signatures. Please go through the below documentation to know about saving the signature as image.

https://help.syncfusion.com/flutter/signaturepad/getting-started#save-signatures-as-images-in-mobile-and-desktop-platforms

Please refer to the below sample,

Sample : https://flutter.syncfusion.com/#/signature-pad/getting-started
Sample source code: https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/signature_pad/getting_started/signature_pad_getting_started.dart

Please let us know if you need any further assistance in this.
 
Regards,
Praveen G.

**Comment by duki97** [comment]
Hi PraveenGopalsamy, i'm not trying sign the document i'm trying to show the signed pdf, the pdf comes to me signed in base64, all documents display fine, but when one document contain a digital sign don show it

**Comment by dillibabu1802** [comment]
Hi @duki97 

At present we do not have support for "Digital Signature". We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of implementation can be tracked through the below feedback link 

[https://www.syncfusion.com/feedback/26234/support-for-digital-signature](https://www.syncfusion.com/feedback/26234/support-for-digital-signature)

Regards,
Dilli babu.
