### ISSUE TITLE
Schedule view doesn't update when data source is updated with appointment outside currently visible weeks if hideEmptyScheduleWeek = true

### ISSUE THREAD

**Issue by etegan** [syncfusion/flutter-examples#516]
Sorry for the horrible title. 

```
SfCalendar(
        view: CalendarView.schedule,
        allowedViews: const [
          CalendarView.schedule,
          CalendarView.week,
          CalendarView.month,
        ],
        dataSource: _AppointmentDataSource(
          data.map((e) => e.toAppointment()).toList(),
        ),

        scheduleViewSettings: const ScheduleViewSettings(
          hideEmptyScheduleWeek: true,
        ),
        initialDisplayDate: DateTime.now(),
      )

class _AppointmentDataSource extends CalendarDataSource {
  _AppointmentDataSource(List<Appointment> source) {
    appointments = source;
  }
}
```

If I update `data` with an appointment that starts in a week that currently doesn't have any appointments, then the `SfCalendar` won't re-render to reflect these changes. It will however re-render if I update `data` with an event that falls within a week that already has an appointment. This can be worked around by using `key: ValueKey(data)` on `SfCalendar` but this will cause the whole calendar to re-render (causing a flickering effect) instead of just updating the schedule list inside the widget. It also renders correctly if I switch to month view and then back. `data` is being provided trough a Riverpod Provider.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Currently, we are validating the issue “**Appointments doesn’t updated in Schedule view while adding dynamically**”. We will validate and update you the further details on or before January 19, 2022. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We will consider this an issue “**Appointments doesn’t updated in Schedule view while adding dynamically with hideEmptyScheduleWeek property value as true**” in the Flutter Calendar. We will fix the issue and include the issue fix in our upcoming Weekly nuget release, which is expected to be rolled out on February 1, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We will consider this an issue “**Appointments doesn’t updated in Schedule view while adding dynamically with hideEmptyScheduleWeek property value as true**” in Flutter Calendar and we have logged the issue report for the same. We will fix the issue and include the issue fix in our upcoming Weekly nuget release, which is expected to be rolled out on February 1, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

You can also communicate with us regarding this bug report at any time using our Feedback page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/28547/provide-zoom-in-and-zoom-out-support-for-sfcalendar


Regards,
Indumathi R

**Comment by muthulakshmi-123** [comment]
Hi,

Sorry for the inconvenience caused.

Due to the stability concerns, we are unable to include the fix for **“Appointments doesn’t updated in Schedule view while adding dynamically with hideEmptyScheduleWeek property value as true”** in our upcoming 2022, Volume 4 SP release. We are checking the issue fix with different possibilities and scenarios, so we will include the issue fix on before February 10. We appreciate your patience until then.

Regards,
Muthulakshmi K

**Comment by Indumathi1195R** [comment]
Hi,

We have fixed the issue but due to a stability facing problem, we are not including this issue fix in our February 8 Weekly nuget release. But assuredly we will include the issue fix in our upcoming Weekly NuGet release, which is expected to be rolled out by February 15, 2022, and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have included the issue fix for “**Appointments doesn’t updated in Schedule view while adding dynamically with hideEmptyScheduleWeek property value as true**” in our latest weekly nuget package **version 19.4.52**. Kindly update to the latest version to resolve the issue. Please find the latest version from the following link.

**Pub documentation latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
