### ISSUE TITLE
How can I drag & drop events or resource areas?

### ISSUE THREAD

**Issue by DDS-HieuLT** [syncfusion/flutter-examples#517]

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: How can I drag & drop events or resource areas?**

By using the **allowDragAndDrop** property of the calendar, you can drag and drop the appointment to specified timeslots. Also, we have KB documentation for drag drop the appointment based on time interval and getting the dropped resource details. Please find the KB documentation from the following link.

**KB link:**
https://www.syncfusion.com/kb/12950/how-to-drop-the-appointment-based-on-the-time-interval-in-flutter-calendar-sfcalendar
https://www.syncfusion.com/kb/12884/how-to-get-the-dropped-resource-details-in-the-flutter-calendar-sfcalendar
 
Please find the UG documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/drag-drop

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DDS-HieuLT** [comment]
@Indumathi1195R It seems to only be applied with timeline view, I'm working on resource view. Although set allowDragAndDrop = true, nothing changes at all. :(

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for the update.

As per the current implementation of the calendar, drag and drop doesn’t support for month and timeline month views in mobile platform, and it is only applicable for windows platform. We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
