### ISSUE TITLE
Need ability to resize calendar time bar on scale action

### ISSUE THREAD

**Issue by Ne0n11** [syncfusion/flutter-examples#518]
Hello, in our project we need ability to resize calendar time bar on scale user action. Is there possibility you would consider to add such a thing in future? Or maybe there is some workaround to make calendar do that without rebuilding whole calendar widget?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Need ability to resize calendar time bar on scale action.**

Based on the shared information, we suspect your requirement is “**Need to resize the time ruler in Flutter Calendar**”. By using the [timeRulerSize](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/timeRulerSize.html) property of the calendar, you can change the size of the time ruler. We have UG documentation for the same. Please find the UG from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/timeslot-views#change-time-ruler-size 

We hope that this helps you. If this is not your requirement please share more details about your requirement clearly with the illustration image. It would be helpful for us to analyze and provide you with a solution at the earliest. 

Regards,
Indumathi R

**Comment by Ne0n11** [comment]
I was talking about such actions as in video.

https://user-images.githubusercontent.com/28736291/149927786-bc102a5e-5f29-46f8-8826-a8604891dec5.mp4

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared video, we have checked and your requirement is “**Provide a support for zoom in and zoom out in Flutter Calendar**” and we have already logged a feature request for the same. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/28547/provide-zoom-in-and-zoom-out-support-for-sfcalendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by Ne0n11** [comment]
Thanks for answer. Will upvote that feedback :)
