### ISSUE TITLE
I can't set action on resource header widget in Calendar Resource View

### ISSUE THREAD

**Issue by DDS-HieuLT** [syncfusion/flutter-examples#519]
I'm using resourceViewHeaderBuilder to build header. Although I wrap child with GestureDetecter, Inkedwell even ElevatedButton with action press, nothing changes.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked and your requirement is “**Getting the resource header details through the tap action in Flutter Calendar**”. By using the calendar [targetElement ](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarElement.html)of the [onTap](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/onTap.html) callback, you can get the resource details. We have attached the code snippet for the same. Please find the code snippet from the below.

**Code snippet:**
```
void calenarTapped(CalendarTapDetails calendarTapDetails) {
  if (calendarTapDetails.targetElement == CalendarElement.resourceHeader) {
    // To do your requirement here.
  }
}
```

Also, we have prepared the simple sample for the same. Please find the sample from the following link.

Sample link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/resource-in-flutter-event-calendar-main1950120358 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DDS-HieuLT** [comment]
@Indumathi1195R  thanks for helping. You made my day <3
