### ISSUE TITLE
Is All Day TimeSlotView UI Crashed if the appointment goes more than one day

### ISSUE THREAD

**Issue by sarmiladhandapani** [syncfusion/flutter-examples#521]
Is All Day TimeSlotView UI Crashed if the appointment goes more than one day
![Screenshot_1642761453](https://user-images.githubusercontent.com/48172133/150513080-74ea8dd5-ea17-4c60-a6b0-dfef48cb2ee0.png)

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: Is All Day TimeSlotView UI Crashed if the appointment goes more than one day.**

Based on the shared information, we have checked and your requirement is “**Calendar crashes when all day appointment goes more than one day**”. We have prepared the simple sample with all day appointment and time interval height, then UI is working fine as expected from our end. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/scheduleview_appointment1438783386 

We have attached the tested image for the same. Please find the image for the same.

 
![vidma_recorder_24012022_112100](https://user-images.githubusercontent.com/54974849/150729195-8083e26c-5cc5-4a3b-bd59-7a2c5a261878.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
