### ISSUE TITLE
[DatePicker] Allow user to select one day as range in multiRange selection mode

### ISSUE THREAD

**Issue by corentingiraud** [syncfusion/flutter-examples#522]
## Current behaviour

A user can't select one day as a range.

## Step to reproduce

1- Open a date picker with `multiRange` selection mode
2- Listen to `onSelectionChanged` event
3-
  - Click on whatever day => ✅ the `onSelectionChanged` event is triggered with the expected value (a `PickerDateRange` with `startDay` equals to the day clicked and a null `endDate`).
  - Click on the same day a second time => ✅ the `onSelectionChanged` is triggered with the expected value (a `PickerDateRange` with `startDay` AND  `endDate` equals to the day clicked).
  - Click on another day to start a new range => ❌ the `onSelectionChanged` is triggered with only one `PickerDateRange`. Its startDay or endDate is the first day clicked or the second one depending of the chronological order (ie. if the first day clicked is before or after the second one).

## Expected behaviour

The user should be able to select one day as a range.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

As per the current implementation of the date range picker, range does not end with same date, and it is the expected behavior the picker. Please get in touch with us if would require any further assistance.

Regards,
Indumathi R
