### ISSUE TITLE
How to change the todayLabel's text to other language?

### ISSUE THREAD

**Issue by Ssiswent** [syncfusion/flutter-examples#523]
I can see two properties to change the text of cancel and confirm btn, but I didn't see the property like todayText.
Could you please tell me if there is a way to change "TODAY" to Chinese ?
<img width="410" alt="image" src="https://user-images.githubusercontent.com/37449310/150892582-c1dd48d5-c63f-450f-9134-317af0dcca98.png">

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: Could you please tell me if there is a way to change "TODAY" to Chinese ?**

Based on the shared information, we have checked and your requirement is “**Localize the today label text in Flutter DateRangePicker**”. Kindly use the Syncfusion_localization package for custom label texts localization in the SfDateRangePicker. We have prepared the simple sample for the same. Please find the sample from the following link.

Also, we have a UG documentation for the same. Please find the UG from the following link.

**UG link:** https://help.syncfusion.com/flutter/globalization  

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/FL653C~1-2032628100 

We have attached the image for the same.
![vidma_recorder_25012022_143523](https://user-images.githubusercontent.com/54974849/150946221-8cd193d6-d706-498f-9916-e76fe67757ec.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards
Indumathi R

**Comment by Ssiswent** [comment]
Really appreciate for your detailed reply, I solved my problem without a hitch.
Wish you have a good day !
