### ISSUE TITLE
Is there a way to disable drag and drop for a specific Appointment.

### ISSUE THREAD

**Issue by mahmoudatef955** [syncfusion/flutter-examples#524]
Hi,

Is there a way to disable drag and drop for a specific Appointment.

Thanks.

**Comment by muthulakshmi-123** [comment]
Hi, 

Thank you for contacting Syncfusion support. 

Based on the provided information, we have analyzed your requirement **“Disable drag and drop for a specific appointment”**, As of now, there is no direct support to disable drag and drop for a specific appointment.

We have already logged a feature request for the same, we will implement this in any of our upcoming releases, we appreciate your patience until then.

Now you can track the current status of this feature request by using the below mentioned link.
https://www.syncfusion.com/feedback/31761/providing-support-for-read-only-appointments-in-flutter-calendar-sfcalendar

We hope that this helps you. Please let us know if you need further assistance.

Regards, 
Muthulakshmi K
