### ISSUE TITLE
 support language

### ISSUE THREAD

**Issue by Alitaheri1374** [syncfusion/flutter-examples#527]
Does it support Arabic or Persian?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Alitaheri1374,

Greetings from Syncfusion. We are not aware of which widget you want Arabic or Persian language support. So, kindly get back to us with the widget in which you want Arabic or Persian language support, that will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by AnanthaGokulaRaman** [comment]
Hi @Alitaheri1374,

Thank you for your patience.

The Syncfusion Flutter PDF supports drawing both Arabic and Persian languages. Kindly use the following link for reference, https://help.syncfusion.com/flutter/pdf/working-with-text#drawing-right-to-left-text

Regards,
Anantha Gokula Raman J
