### ISSUE TITLE
about Month. i can't see but can pick month in widget

### ISSUE THREAD

**Issue by supaveeK** [syncfusion/flutter-examples#528]
see that issu running ==> https://media.discordapp.net/attachments/709087574328606812/938401470452232242/ezgif.com-gif-maker_1.gif?width=309&height=669

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following LocaleDataException was thrown during paint():
Locale data has not been initialized, call initializeDateFormatting(<locale>).

The relevant error-causing widget was:
  CustomPaint
  CustomPaint:file:///C:/Users/pa254/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-19.4
  .38/lib/src/date_picker/date_picker.dart:8096:20

When the exception was thrown, this was the stack:
#0      UninitializedLocaleData._throwException (package:intl/src/intl_helpers.dart:80:5)
#1      UninitializedLocaleData.containsKey (package:intl/src/intl_helpers.dart:74:7)
#2      DateFormat.localeExists (package:intl/src/intl/date_format.dart:834:28)
#3      verifiedLocale (package:intl/src/intl_helpers.dart:159:19)
#4      new DateFormat (package:intl/src/intl/date_format.dart:266:27)
#5      _getMonthHeaderText (package:syncfusion_flutter_datepicker/src/date_picker/date_picker.dart:13194:10)
#6      _getHeaderText (package:syncfusion_flutter_datepicker/src/date_picker/date_picker.dart:13245:16)
#7      _PickerHeaderPainter.paint (package:syncfusion_flutter_datepicker/src/date_picker/date_picker.dart:8262:27)
#8      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#9      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#14     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#15     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#16     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#21     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#22     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#25     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7530:15)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#37     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#38     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#39     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#42     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7530:15)
#43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#48     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:341:15)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#54     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#57     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#60     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#61     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#64     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#71     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:554:11)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#74     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#75     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:608:11)
#76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#79     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
#80     RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:2028:15)
#81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#83     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#86     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#89     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#91     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#92     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#100    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#101    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#102    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:203:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#104    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#107    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#108    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
#109    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:613:5)
#110    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#111    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#112    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#113    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#114    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#115    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#116    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#117    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:973:29)
#118    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#119    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#120    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#121    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#122    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#123    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#127    _invoke (dart:ui/hooks.dart:150:10)
#128    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#129    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#e8f97
relayoutBoundary=up3:
  creator: CustomPaint ← RepaintBoundary ← _RawMouseRegion ← MouseRegion ← Row ← _PickerHeaderView ←
    ColoredBox ← ConstrainedBox ← Container ← Listener ← _GestureSemantics ← RawGestureDetector ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=40.0)
  semantic boundary
  size: Size(200.0, 40.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: LocaleDataException: Locale data has not been initialized, call
initializeDateFormatting(<locale>).

Another exception was thrown: LocaleDataException: Locale data has not been initialized, call
initializeDateFormatting(<locale>).

Another exception was thrown: LocaleDataException: Locale data has not been initialized, call
initializeDateFormatting(<locale>).

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “**Unable to see the month while using the locale in SfDateRangePicker**” with the const Locale(“th”) language code and month shows properly and there is no exception from our end. We have attached the tested sample for the same. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app_localization116105995.zip

**Screenshot:**
![vidma_recorder_03022022_130602](https://user-images.githubusercontent.com/54974849/152300926-ac7d0df9-5cd3-4446-9c8c-1aa1d5626e07.jpg)

If possible, can you please check the sample once and let us know still if you are facing same issue? If not, please modify the sample based on your scenario and revert us with following details.

•	Code snippet

 It will be helpful for us to check on it and provide you solution at the earliest.

Regards,
Indumathi R
