### ISSUE TITLE
How can I add an icon to a calender card scheduler

### ISSUE THREAD

**Issue by remymumoh** [syncfusion/flutter-examples#529]
Not an issue really but a question. How can I add an icon the cards and only show an open padlock when the card is blue and all others are locked with a locked padlock? and also disable on click on those cards that the event is not due?

![Screenshot 2022-02-03 221425](https://user-images.githubusercontent.com/10322082/152412891-78788749-f0c5-4d52-b6df-cd240e2a3310.png)

Also how can I disable the 12:00 am- 12:00am on the card.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Adding the icon to calendar scheduler.**

By using the [scheduleViewMonthHeaderBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/scheduleViewMonthHeaderBuilder.html) property you can design your own custom builder with required widget and also using the [appointmentBuilder](https://help.syncfusion.com/flutter/calendar/builders#appointment-builder) property of the calendar you can add the icon to the appointments in the schedule view. We have a UG and KB documentation for the same. Please find the documentations from the following link.

**UG links:**
https://help.syncfusion.com/flutter/calendar/builders#appointment-builder
https://help.syncfusion.com/flutter/calendar/builders#schedule-view-month-header-builder

**KB link:**
https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-calendar 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by remymumoh** [comment]
And how to remove the 12am-12am?

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation we can’t remove the appointment timing. By, using the [appointmentBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/appointmentBuilder.html), you can design your own UI for appointments in the Flutter Calendar. We have attached the code snippet for the same. Please find the code snippet from below.

**Code snippet:**
```
appointmentBuilder: appointmentBuilder,

Widget appointmentBuilder(BuildContext context,
    CalendarAppointmentDetails calendarAppointmentDetails) {
  final Appointment appointment =
      calendarAppointmentDetails.appointments.first;
  return Column(
    children: [
      Container(
          width: calendarAppointmentDetails.bounds.width,
          height: calendarAppointmentDetails.bounds.height / 2,
          color: appointment.color,
          child: const Center(
            child: Icon(
              Icons.group,
              color: Colors.black,
            ),
          )),
      Container(
        width: calendarAppointmentDetails.bounds.width,
        height: calendarAppointmentDetails.bounds.height / 2,
        color: appointment.color,
        child: Text(
          appointment.subject,
          textAlign: TextAlign.center,style: TextStyle(fontSize: 10),
        ),
      )
    ],
  );
}
```
**Screenshot:**
![vidma_recorder_07022022_150720](https://user-images.githubusercontent.com/54974849/152763171-6668f65b-2e39-411c-b9e3-a1afbff958ff.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
