### ISSUE TITLE
Intl library version issue

### ISSUE THREAD

**Issue by LugonjaAleksandar** [syncfusion/flutter-examples#53]
I have an error when upgrading to the latest syncfusion library version and this is the reason: 

Because every version of flutter_driver from sdk depends on intl 0.15.8 and ProjectName depends on intl ^0.16.0, flutter_driver from sdk is forbidden.

flutter_driver which is main part of tests in Flutter is dependant on 0.15.8, and because of your mandatory version of 0.16.0 app can't use this library package. Official release branch of flutter doesn't fully support Intl 0.16.0 and your framework must not go above the release veresion and force it. 

We as a company have bought a licence for this chart library, but are unable to utilize it due to a bug you introduce with versioning.

**Comment by JayavigneshwaranG** [comment]
Hi @LugonjaAleksandar ,

We regret for the inconvenience.

As the pub.dev scoring suggests to use the latest version packages, we have specified 0.16.0 for intl package, as it is the latest version. Now we have understood your scenario and modified the charts package to support lower versions of intl. Also, we have published this change to pub.dev. So we suggest you to use the latest version charts package to resolve this issue.

https://pub.dev/packages/syncfusion_flutter_charts/versions/17.3.26

Please let us know if you face any other difficulties.

Thanks,
Jayavigneshwaran

**Comment by LugonjaAleksandar** [comment]
Works now, thanks! "staying up to date" is just a recommendation in order to keep up with all the fixes that libraries provide by their maintainers. But anyways you need to be careful not to go above flutter supported versions and the main product - Flutter and Dart.
