### ISSUE TITLE
Saving the generated QR code as an image

### ISSUE THREAD

**Issue by ramvdixit** [syncfusion/flutter-examples#530]
Hello,

Is there a way to save the generated QR code (using the barcode plugin) to an image (Jpg/Png)? I don't see a method to either return the byte array or a method to save the QR code to an image. Please do let me know.

Thanks,
Mahesh

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ramvdixit ,

Greetings from Syncfusion. We have created a sample that will convert the barcode as a Png image and showed it on another page. We have attached the sample below for your reference.

Sample: [barcode.zip](https://github.com/syncfusion/flutter-examples/files/8074915/barcode.zip)

Regards,
Yuvaraj.
