### ISSUE TITLE
Available and unavailable dates

### ISSUE THREAD

**Issue by Intissaka** [syncfusion/flutter-examples#531]
Hello, I want that when a client selects an appointment, next client couldnt select it. How can I do it?

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

We have already logged the feature request for “**Providing a support to Readonly appointments in the Flutter calendar**”. We will implement this in any of our upcoming release and let you know once the release rolled out.  We appreciate your patience until then.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/31761/providing-support-for-read-only-appointments-in-flutter-calendar-sfcalendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Also we have a support for [speciaRegions](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/specialRegions.html), by using the [enablePointerInteraction](https://help.syncfusion.com/flutter/calendar/timeslot-views#selection-restriction-in-timeslots) property of the time region value as false you can restrict the selection for particular time slots. 

We have a UG documentation for the same. Please find the UG from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/timeslot-views#special-time-regions

Regards,
Indumathi R
