### ISSUE TITLE
Add waterMark

### ISSUE THREAD

**Issue by SaadNewton** [syncfusion/flutter-examples#532]
Hello sir!
I hope you are fine.
Actually I want to add watermark in all pages of pdf file but I cannot find any solution for this. I am working with Syncfussion Flutter Pdf Package. kindly inform me asap I should have to work in this module.
Thanks.
Regard,
Saad

**Comment by Surya-3013** [comment]
Hi @SaadNewton ,

We have created a sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/CreateWatermarkPDFSample715311357 to add watermark in all pages of PDF document. Kindly try it and let us know the result.

Refer to the following articles for more details,
https://www.syncfusion.com/kb/11963/how-to-add-watermark-to-pdf-file-in-syncfusion-flutter-pdf-library
https://help.syncfusion.com/flutter/pdf/working-with-watermarks#adding-image-watermark-to-a-pdf-document

Regards,
Surya V

**Comment by SaadNewton** [comment]
Hi @Surya-3013,

Sorry for late Response.
The code you have delivered to me that I have tested before. But it just add watermark on just 1st page of pdf file.
Sir, I want to add watermark on all pages of pdf but it couldn't work.

Regards,
SaadNewton

**Comment by Surya-3013** [comment]
Hi @SaadNewton ,

We recommend you get the all pages in the PDF document using page collection in the loaded document and with each page graphics you can draw the watermark on all pages in the PDF document. Kindly with the following code snippet and let us know the result,
`Future<void> _addWatermarkToPDF() async {
//Load the PDF document.
PdfDocument documents = PdfDocument(
inputBytes: await _readDocumentData("PDF_Succinctly-doc1.pdf"));

    for (int i = 0; i < documents.pages.count; i++) {
      //Get first page from document
      PdfPage page = documents.pages[i];
      //Get page size
      Size pageSize = page.getClientSize();
      //Set a standard font
      PdfFont font = PdfStandardFont(PdfFontFamily.helvetica, 40);
      //Measure the text
      Size size = font.measureString('Confidential');
      //Create PDF graphics for the page
      PdfGraphics graphics = page.graphics;
      //Calculate the center point.
      double x = pageSize.width / 2;
      double y = pageSize.height / 2;
      //Save the graphics state for the watermark text
      graphics.save();
      //Tranlate the transform with the center point.
      graphics.translateTransform(x, y);
      //Set transparency level for the text
      graphics.setTransparency(0.25);
      //Rotate the text to -40 Degree
      graphics.rotateTransform(-40);
      //Draw the watermark text to the desired position over the PDF page with red color
      graphics.drawString('Confidential', font,
          pen: PdfPen(PdfColor(255, 0, 0)),
          brush: PdfBrushes.red,
          bounds: Rect.fromLTWH(
              -size.width / 2, -size.height / 2, size.width, size.height));
      //Restore the graphics
      graphics.restore();
    }

    //Save the document
    List<int> bytes = documents.save();
    //Dispose the document
    documents.dispose();

    //Save and launch file.
    await FileSaveHelper.saveAndLaunchFile(bytes, 'PDF_Watermark.pdf');
  }`

Regards,
Surya V

**Comment by SaadNewton** [comment]
Hi @Surya-3013 

Now, It's working fine as I required.
Thank you so much for Co-operating with me.

Regards,
SaadNewton

**Comment by SaadNewton** [comment]
Good response..
Very appreciable..
Excellent work..
and nice behaviour to talk and solutions of queries..
Thanks
