### ISSUE TITLE
BlackoutDates

### ISSUE THREAD

**Issue by Ne0n11** [syncfusion/flutter-examples#533]
Hello. So my question is simple. Is there a way to enable selecting blackOut dates?

And second question - is there a way to specify 2 different sets of special dates, with different styles? 

Thanks for answering :)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Q1: Is there a way to enable selecting blackOut dates?**

By using the reverse concept of the blackout dates you can achieve this requirement. We have a KB documentation for this requirement. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12075/how-to-add-active-dates-in-the-flutter-date-range-picker-sfdaterangepicker 

**Regarding Q2: is there a way to specify 2 different sets of special dates, with different styles?**

We have a KB documentation for cell customization using **specialDates**. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12374/how-to-customize-the-special-dates-using-builder-in-the-flutter-date-range-picker 

Also, we have prepared a simple sample for 2 different sets of special dates with different styles. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_specialdate2135411618.zip 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Ne0n11** [comment]
Thanks a lot. :)
