### ISSUE TITLE
[syncfusion_flutter_pdf] Splitting PDF pages into files

### ISSUE THREAD

**Issue by niklasbartsch** [syncfusion/flutter-examples#534]
I am trying to split a pdf file into each pdf page as a file. 

I got it to work with: 

``` dart
Future<List<PdfDocument>> getPagesFromPDF({
    required PdfDocument document,
  }) async {
    final _documents = <PdfDocument>[];
    final count = document.pages.count;

    for (var i = 1; i <= count; i++) {
      final newDocument = await getPageFromPDF(
        pageNumber: i,
        document: document,
        numberOfPages: count,
      );
      _documents.add(newDocument);
    }
    return _documents;
  }
```

``` dart
  Future<PdfDocument> getPageFromPDF({
    required int pageNumber,
    required PdfDocument document,
    int? numberOfPages,
  }) async {
    final index = pageNumber - 1;
    // Seite 1 = index 0

    final _newDocument = PdfDocument(inputBytes: document.save());
    final pdfLen = numberOfPages ?? _newDocument.pages.count;

    // 49 pages
    // index 0-48
    // pageNumber = 5 -> index 4
    // -> remove index 5- 48

    for (var i = pdfLen; i >= pageNumber; i--) {
      _newDocument.pages.removeAt(i);
    }

    for (var i = 0; i < index; i++) {
      _newDocument.pages.removeAt(0);
    }

    final newPdf = _newDocument.save();

    _newDocument.dispose();

    return PdfDocument(inputBytes: newPdf);
  }
```

But this leads to a freezed simulator for a couple of seconds on macOS.

Does anyone know a better way to do this?

**Comment by mirkancal** [comment]
I'm currently trying to do the same 

https://github.com/syncfusion/flutter-widgets/issues/576
https://stackoverflow.com/questions/71065038/how-to-display-pdf-pages-separately-or-make-thumbnail-viewer

**Comment by Surya-3013** [comment]
> I am trying to split a pdf file into each pdf page as a file.
> 
> I got it to work with:
> 
> ```dart
> Future<List<PdfDocument>> getPagesFromPDF({
>     required PdfDocument document,
>   }) async {
>     final _documents = <PdfDocument>[];
>     final count = document.pages.count;
> 
>     for (var i = 1; i <= count; i++) {
>       final newDocument = await getPageFromPDF(
>         pageNumber: i,
>         document: document,
>         numberOfPages: count,
>       );
>       _documents.add(newDocument);
>     }
>     return _documents;
>   }
> ```
> 
> ```dart
>   Future<PdfDocument> getPageFromPDF({
>     required int pageNumber,
>     required PdfDocument document,
>     int? numberOfPages,
>   }) async {
>     final index = pageNumber - 1;
>     // Seite 1 = index 0
> 
>     final _newDocument = PdfDocument(inputBytes: document.save());
>     final pdfLen = numberOfPages ?? _newDocument.pages.count;
> 
>     // 49 pages
>     // index 0-48
>     // pageNumber = 5 -> index 4
>     // -> remove index 5- 48
> 
>     for (var i = pdfLen; i >= pageNumber; i--) {
>       _newDocument.pages.removeAt(i);
>     }
> 
>     for (var i = 0; i < index; i++) {
>       _newDocument.pages.removeAt(0);
>     }
> 
>     final newPdf = _newDocument.save();
> 
>     _newDocument.dispose();
> 
>     return PdfDocument(inputBytes: newPdf);
>   }
> ```
> 
> But this leads to a freezed simulator for a couple of seconds on macOS.
> 
> Does anyone know a better way to do this?

Hi @niklasbartsch ,

Our package is written natively in Dart for supporting all the platforms and its only works on the main thread (synchronously) and we do not have asynchronous support, due to the UI has been stopped animating for doing very large process. So we request you to use the Isolate to overcome issue. Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample_isolate215252369 for more details.

Regards,
Surya V

**Comment by Surya-3013** [comment]
> I'm currently trying to do the same
> 
> [syncfusion/flutter-widgets#576](https://github.com/syncfusion/flutter-widgets/issues/576) https://stackoverflow.com/questions/71065038/how-to-display-pdf-pages-separately-or-make-thumbnail-viewer

Hi @mirkancal ,

We recommend you to follow up: https://github.com/syncfusion/flutter-widgets/issues/576 for further details on this.

Regards,
Surya V
