### ISSUE TITLE
Hello, I would like to ask, how to disable the weekend, do you have a code demo?

### ISSUE THREAD

**Issue by 2530442368** [syncfusion/flutter-examples#535]
Hello, I would like to ask, how to disable the weekend, do you have a code demo?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: I would like to ask, how to disable the weekend, do you have a code demo?**

Based on the shared information, we are unable to understand your requirement is in SfCalendar or SfDateRangePicker control. But your requirement “**Disable the weekends**" can be achieved by using the selectableDayPredicate callback you can disable the selection. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#selectabledaypredicate

**Code snippet:**

```
selectableDayPredicate: (DateTime date) {
  if (date.weekday == DateTime.saturday || date.weekday == DateTime.sunday) {
    return false;
  }
  return true;
},
```
Also, by using the blackoutDates property of the calendar.  We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/active-dates-flutter-date-range-picker-main_(2)1910534668.zip

Also please find the UG links for blackoutDates in date range picker.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates

Also, by using the specialRegions property and blackoutDates you can disable the weekend dates in calendar. Please find the UG documentation for the same.
 
**UG link:**

https://help.syncfusion.com/flutter/calendar/timeslot-views#special-time-regions 
https://help.syncfusion.com/flutter/calendar/month-view#blackout-dates

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
