### ISSUE TITLE
Hello, how to dynamically update the number of monthly rows

### ISSUE THREAD

**Issue by DioboKN** [syncfusion/flutter-examples#536]

**Comment by DioboKN** [comment]
Can the number of rows of the month be automatically updated

**Comment by Indumathi1195R** [comment]
Hi,

By using the **numberOfWeeksInview** property you can show the required weeks in Flutter Calendar and DateRangePicker control. We have a UG and KB documentation for the same. Please find the documentations from the following link.

**UG links:**
https://help.syncfusion.com/flutter/calendar/month-view#customize-number-of-month-rows 
https://help.syncfusion.com/flutter/daterangepicker/views#week-view

**KB links:**
https://www.syncfusion.com/kb/12157/how-to-change-the-number-of-weeks-in-the-flutter-calendar
https://www.syncfusion.com/kb/12167/how-to-change-the-number-of-weeks-in-the-flutter-date-range-picker-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by DioboKN** [comment]
Expect the plug-in to automatically update the number of weeks

**Comment by DioboKN** [comment]
Expect the plug-in to automatically update the number of weeks

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar there is no support to update the week number dynamically. But calculating the height the device in Widget build method using the **MediaQuery** you can change the number of weeks in view as per your requirement. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_customweek-997718325.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
