### ISSUE TITLE
Flutter pdf creation

### ISSUE THREAD

**Issue by sleem2012** [syncfusion/flutter-examples#538]
How to add listvew builder inside pdf 
I want to create sample like invoice but i want to add three or more table inside pdf
Because in my application need to create table for every user inside my application 
I try to add tables inside listview builder but nothing happen

**Comment by sleem2012** [comment]
This what i need 
![Screenshot_2022-02-11-15-18-30-180_com.google.android.apps.docs.jpg](https://user-images.githubusercontent.com/31719188/153598408-5787b32e-6b87-4672-8a40-7a6180b651e8.jpg)

**Comment by Surya-3013** [comment]
Hi @sleem2012 ,

We have support for creating customizable tables like Invoice in a PDF document by using the PdfGrid table model. We recommend you refer to the following UG documentation to create an Invoice in the PDF document, https://help.syncfusion.com/flutter/pdf/getting-started#creating-a-pdf-document-with-table ,Kindly try with the article contains code snippet and let us know the result.

Refer to the following link to get more details about table creation in PDF document,
https://help.syncfusion.com/flutter/pdf/working-with-tables#creating-a-table

Regards,
Surya V
