### ISSUE TITLE
Change month programmatic

### ISSUE THREAD

**Issue by mahdibagjani** [syncfusion/flutter-examples#540]
Hello. Thanks to a useful datepicker. I want to change month programmatic and custom leading (arrow).
How to do it?

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we suspect your requirement is “**Custom header support in the Flutter date range picker**”. By using the **headerHeight** property you can hide the default headers and the required widget for custom header. We have a KB documentation for custom header with navigation arrows. Please find the KB documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/11427/how-to-customize-the-header-view-of-the-flutter-date-range-picker

Also, we have a UG documentation for the same. Please find the Ug from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/headers#customize-view-header-height 

Also, we have UG documentation for programmatic view navigation and date navigation. Please find the UG from the following link.

**UG links:**
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatic-view-navigation 	
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatic-date-navigation

Also, we have a forward and backward method for viewing the next and previous visible dates in the picker. Please find the UG documentation from the following link.

https://help.syncfusion.com/flutter/daterangepicker/date-navigations#forward 
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#backward 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update. Please get in touch with us if you require any further assistance.

Regards,
Indumathi R
