### ISSUE TITLE
Pagination onPlotAreaSwipe animation delay

### ISSUE THREAD

**Issue by kksal55** [syncfusion/flutter-examples#541]
How do I increase the speed of switching pages?

    @override
    Widget build(BuildContext context) {
      return Container(
         child: SfCartesianChart(
            onPlotAreaSwipe:
              (ChartSwipeDirection direction) =>
                  performSwipe(direction),
            series: <ChartSeries<SalesData, num>>[
                 AreaSeries<SalesData, num>(
                     dataSource: chartData,
                 ),
            ],
         )
      );
    }

    Widget performSwipe(ChartSwipeDirection direction) {
        if (direction == ChartSwipeDirection.end) {
            chartData.add(ChartSampleData(
                x: chartData[chartData.length - 1].x + 1,
                y: 10));
            seriesController?.updateDataSource(addedDataIndex: chartData.length - 1);
      }
    }

    class SalesData {
      SalesData(this.x, this.y);
      final num x;
      final double? y;
    }

https://user-images.githubusercontent.com/11652726/153821846-e90e72e8-7128-4176-868a-514dd727afd9.mp4

`

**Comment by LokeshPalani** [comment]
Hi @kksal55,
 
Currently, we don’t have support for **‘Customizing the animation duration for changing the axis range’.** However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.
 
We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.
 
**FR Link,**
https://www.syncfusion.com/feedback/50939/provide-an-option-to-customize-the-axis-range-change-animation-duration
 
Regards,
Lokesh P.
