### ISSUE TITLE
[SfCalendar] How to always show Scrollbar in CalendarView.schedule? 

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-examples#542]
How do I always show the scrollbar in CalendarView.schedule? 

I tried wrapping the SfCalendar widget in a Scrollbar(), but that didn't work

**Comment by Indumathi1195R** [comment]
Hi,

We have considered your requirement “**Providing support to show the Scrollbar in the Schedule view of the Flutter Calendar (SfCalendar)**” as feature and logged the feature request for the same. We will implement this in any of our upcoming releases and let you know once the release rolled out.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/32722/providing-support-to-show-the-scrollbar-in-the-schedule-view-of-the-flutter 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by gajalakshmi-d** [comment]
How  to identify the scroll offset in SfCalendar(TimeSlotViewSettings) ?
