### ISSUE TITLE
Charts: multiLevelLabels

### ISSUE THREAD

**Issue by jpbigmotive** [syncfusion/flutter-examples#545]
Hey, I have been on this for hours and just can't figure this out. Is there a way that I can set the text alignment and max-width of multi-level labels? Not sure if I am missing something or if it is just not possible at the moment.

I am using the multi-level labels on the y-axis and would like them to be left-aligned and for the text to wrap to multiple lines.

This is what I would like to achieve:

<img width="181" alt="Screenshot 2022-02-17 at 00 16 15" src="https://user-images.githubusercontent.com/48809852/154379563-3ddef967-3906-4e14-81d4-d45f9af49bdd.png">

This is what I currently have:

<img width="184" alt="Screenshot 2022-02-17 at 00 17 10" src="https://user-images.githubusercontent.com/48809852/154379598-67429aa5-c879-4924-9722-f4a3b6ed6bcd.png">

Any help would be greatly appreciated.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jpbigmotive,

We suggest using the \n between the characters to move the axis label text or multi-level labels to the next line. We have attached the code snippet below for your reference, we hope it will help you to achieve your requirement.

```dart
// For Multilevel labels
SfCartesianChart(
  primaryYAxis:
    NumericAxis(multiLevelLabels: const <NumericMultiLevelLabel>[
      NumericMultiLevelLabel(start: 0, end: 10, text: 'Exceeded'),
      NumericMultiLevelLabel(
          start: 10, end: 20, text: 'Nearly \n succeeded'),
      NumericMultiLevelLabel(
          start: 20, end: 30, text: 'Not \n attempted'),
  ]),
)
 
// For axis labels
SfCartesianChart( 
  series: <ChartSeries<SalesData, String>>[ 
    ColumnSeries<SalesData, String>( 
      dataSource: <SalesData>[ 
        SalesData('Exceeded', 35), 
        SalesData('Nearly \n succeeded', 28), 
        SalesData('Not \n Attempted', 34), 
       ], 
      // Other required properties 
  ]) 
```
And the can't be aligned to the left as per your requirement, however you can align the labels using the labelAlignment property. Demo sample for this can be found below and this labelAlignment property is applicable for axis label but not for multi-level labels feature.

Axis label alignment: https://flutter.syncfusion.com/#/cartesian-charts/axis-features/positioning-axis-labels

Multilevel labels: https://flutter.syncfusion.com/#/cartesian-charts/axis-features/multi-level-labels

And we have already logged a feature request to use a custom widget for axis labels and this will be available in any of our upcoming releases yet to come and you can track the status of the feature below

https://www.syncfusion.com/feedback/23096

Sample: [chart_sample.zip](https://github.com/syncfusion/flutter-examples/files/8106368/chart_sample.zip)

Regards,
Yuvaraj.

**Comment by jpbigmotive** [comment]
@Yuvaraj-Gajaraj Great, thank you for your detailed response.
