### ISSUE TITLE
PDF adding auth headers

### ISSUE THREAD

**Issue by Mortorff270** [syncfusion/flutter-examples#546]
I'm having issues properly setting up the authorization headers for my application in the network constructor for the PDF viewer. I've looked at the documentation at: https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.network.html
but still can't get the syntax to work properly. I found a similar issue that was closed in regards to header functionality being added:
https://github.com/syncfusion/flutter-examples/issues/306 
but the issue didn't include any examples nor have I been able to find any examples of the header parameter in use. A short example would be greatly appreciated!

**Comment by deepika134** [comment]
Hi Mortorff270,

To include the headers for network constructor in SfPdfViewer.Kindly refer to the following code snippet.

Code Snippet:

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter PDF Viewer'),
        actions: <Widget>[
          IconButton(
            icon: const Icon(
              Icons.bookmark,
              color: Colors.white,
              semanticLabel: 'Bookmark',
            ),
            onPressed: () {
              _pdfViewerKey.currentState?.openBookmarkView();
            },
          ),
        ],
      ),
      body: SfPdfViewer.network(
        'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
        headers: {'key': 'value'},
        key: _pdfViewerKey,
      ),
    );
  }
```

Regards,
Deepika Ravi
