### ISSUE TITLE
how to show each events appointment details on tap of the events i am not getting the recurring events details in the appointment list. 

### ISSUE THREAD

**Issue by pavanZibtek** [syncfusion/flutter-examples#548]

**Comment by pavanZibtek** [comment]
We are developing a calendar app using the flutter syncfusion_flutter_calendar package. In the package, everything is working except only on tap of any event, I need to display the card and show the details of the events (like date of the events, time of the event, and who and all attending the event) this info need to show. But the issue is that on tap of single events I am getting the details of the appointment, but recurring event details of the attendee's list we are not getting in from the package

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, your requirement is “**Getting the tapped recurrence appointment details in the Flutter Calendar**” and we have a KB documentation for the same. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/11529/how-to-add-a-custom-appointments-or-objects-in-the-flutter-calendar 

We hope that this helps you. If this is not your requirement, please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
