### ISSUE TITLE
Is it possible to hide empty months in schedule view?

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-examples#549]
Ex. if I have an event in January and June with nothing in between, there are 4 month headers for empty months, but if I return an empty container with the month header builder, it's still tied to the size from month header settings, so there will be blank space instead of the 4 month headers.

Is there some way to control empty months like hide empty weeks?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is it possible to hide empty months in schedule view?** 

As per the current implementation of the calendar, the [hideEmptyScheduleWeek](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/ScheduleViewSettings/hideEmptyScheduleWeek.html) property hides the month and week without the appointment. We have attached the image for the same. 

![Screen Shot 2022-02-28 at 11 45 43 AM](https://user-images.githubusercontent.com/54974849/155951531-021b4a5c-eb8e-4987-9cee-f0f2f8566988.png)

![Screen Shot 2022-02-28 at 11 46 20 AM](https://user-images.githubusercontent.com/54974849/155951543-dd20a5a8-e3aa-4dfe-9cd8-b5abe40703cb.png)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Thanks for the quick reply.

After further testing I uncovered some strange behavior. This issue seems to occur specifically when there is an event on the 1st of July.

Perhaps it is a bug that only occurs in this case?

Could you recreate the above screenshots with conference1 on July 1 2022

**Comment by Indumathi1195R** [comment]
Hi,

We have checked the mentioned issue with creating an appointment on July 1, 2022 and the appointment date is in June 26, 2022 – July 2, 2022 week. So, it shows the June month also. We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Yes, as mentioned the question is whether it is possible to hide empty
months. In that case June is empty and should not be shown. This will be
confusing for the user.

Is this possible?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: is whether it is possible to hide empty months.**

Yes, it is possible to hide the empty months as per the current implementation of the Flutter Calendar 1st of the July is in last week of the June month and it considers that week has an appointment and this is not issue. So, June month also visible in calendar UI. We hope that information helps you. Please get in touch with us if would you require further assistance.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Hi Indumathi,

Look at the last screenshot you provided above: The February week goes into March but the March header is not showing. This is inconsistent with your explanation for the June header showing for an event on the 1st of July. Do you understand my issue? This is confusing for the user.

**Comment by Justus-M** [comment]
> Hi,
> 
> **Regarding Query: Is it possible to hide empty months in schedule view?**
> 
> As per the current implementation of the calendar, the [hideEmptyScheduleWeek](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/ScheduleViewSettings/hideEmptyScheduleWeek.html) property hides the month and week without the appointment. We have attached the image for the same.
> 
> ![Screen Shot 2022-02-28 at 11 45 43 AM](https://user-images.githubusercontent.com/54974849/155951531-021b4a5c-eb8e-4987-9cee-f0f2f8566988.png)
> 
> ![Screen Shot 2022-02-28 at 11 46 20 AM](https://user-images.githubusercontent.com/54974849/155951543-dd20a5a8-e3aa-4dfe-9cd8-b5abe40703cb.png)
> 
> We hope that this helps you. Please let us know if you need further assistance.
> 
> Regards, Indumathi R

The first and second screenshot display inconsistent behavior.

Why is the march header showing in the first screenshot but not in the second?

Ideally it should also be possible to hide month headers where there are no events, even if the week of an event in the previous or following month overlaps with the empty month. Otherwise app users will be confused, especially if developers want to hide the week headers, since app users will have no idea why only some empty months are showing the headers.

**Comment by Justus-M** [comment]
Hi Indumathi,

Let me clarify, by empty month I mean a month in which there are no events. If you ask an app user if June is an empty month when they have an event on July 1st, they will say yes it is empty. And of course we are developing apps for app users in the end, not developers.

This is especially problematic when hiding the week headers, because then the empty month doesn't show anything at all except for the header, and are confusing clutter.

Is there some way to hide empty months with no events?

**Comment by Indumathi1195R** [comment]
Hi,

We have considered this is an improvement in the Flutter Calendar “**Improve the behavior of schedule view with hideEmptyScheduleWeek in Flutter Calendar**”. We will improve this behavior in our upcoming 2022 Volume 1 release, which is expected to be rolled out by March 31, 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have improved the behavior of Flutter Calendar “**Improve the behavior of schedule view with hideEmptyScheduleWeek in Flutter Calendar**” in our upcoming **2022 Volume 1 release version 20.1.47**. Kindly update to the latest version for this improvement. Please find the latest version from the following link.

**Latest version link:** 
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Thanks!
