### ISSUE TITLE
SfCalendar with CalendarView.timelineDay not trigger RefreshIndicator 

### ISSUE THREAD

**Issue by tuannvm-citigo** [syncfusion/flutter-examples#551]
RefreshIndicator is not working when i use with mode CalendarView.timelineDay
It only trigger when i scroll list resource on the left, but when i scroll the the main calendar view it not trigger RefreshIndicator

**Comment by Indumathi1195R** [comment]
Hi,

We have checked the mentioned issue “**Load more indicator not working in timeline day view of the Flutter Calendar**”. We have checked the simple sample in resource view with load more indicator. The indicators was shown properly while navigating to the next and previous views. We have prepared the simple sample for the same. Please find the sample from the following link.
 
**Sample link:** 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_appschedul-1396381613.zip 

If possible, please check the sample once and let us know still if you are facing the same issue? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by tuannvm-citigo** [comment]
In my case i was trying to wrap SfCalendar inside RefreshIndicator, I want behavior like ListView inside RefreshIndicator that when scroll SfCalendar to reach top and continue pull down, it will trigger RefreshIndicator to reload but the problem is SfCalendar scroll reach top in CalendarView.timelineDay mode doesn't trigger RefreshIndicator
It only work with CalendarView.day but I don't know why not CalendarView.timelineDay

**Comment by Indumathi1195R** [comment]
Hi,

As per the behavior of the day view in Flutter calendar scroll direction is vertical. So, refresh indicator was shown when scroll reaches the top position and in the timelineDay view have a horizontal scroll direction. RefreshIndicator is only applicable for vertical scroll view. We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by tuannvm-citigo** [comment]
Ok thank for @Indumathi1195R comment, I decide to solve this problem by wrap Calendar inside NotificicationListener, for anyone else need:

```
NotificationListener<ScrollEndNotification>(
                  onNotification: (ScrollEndNotification value) {
                    final ScrollMetrics metrics = value.metrics;
                    if (metrics.axisDirection == AxisDirection.down &&
                        metrics.pixels == 0 &&
                        metrics.atEdge &&
                        value.dragDetails is DragEndDetails) {
                     _indicatorKey.currentState?.show();
                      return true;
                    }
                    return false;
                  },
child : SfCalendar()
)
```

**Comment by Indumathi1195R** [comment]
Hi , 

We are glad to know that your issue has been resolved at your end. Please let us know if you need any other assistance. We will be happy to assist you.  

Regards, 
Indumathi R
