### ISSUE TITLE
SFCalendar ScheduleView hideEmptyScheduleWeek Bug:  RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-examples#552]
I get the following exception in schedule view after updating from syncfusion_flutter_calendar:19.4.41 to 19.4.53.

This exception only occurs when - hideEmptyScheduleWeek: true

═══════ Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building Calendar-[<'hi'>](dependencies: [_InheritedProviderScope<Events>, _LocalizationsScope-[GlobalKey#ddfc5], _InheritedTheme], state: _CalendarState#64cd0):
RangeError (index): Invalid value: Valid value range is empty: 0

This is coming from the function void _loadScheduleViewAppointmentDates(List<CalendarAppointment> collection) 

specifically from the line
 final DateTime startDate =
        _previousDates.isEmpty ? _nextDates[0] : _previousDates[0];

i.e. _nextDates is empty.

This also happens in the example at https://pub.dev/packages/syncfusion_flutter_calendar/example when I change to schedule view and turn on hideEmptyScheduleWeek

I didn't have this issue with 19.4.41

Unfortunately when I try to downgrade to 19.4.41 and even run flutter clean, flutter pub get, it still installs 19.4.53

**Comment by Indumathi1195R** [comment]
Hi,

We have fixed the mentioned issue “**Exception occurred while set the hideEmptyScheduleWeekvalue as true with setStaet in onViewChanged callback in Flutter Calendar**”. We will include the issue fix in our upcoming Weekly nuget package, which is expected to be rolled out by March 8, 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Thank you!

**Comment by Justus-M** [comment]
> Hi,
> 
> We have fixed the mentioned issue “**Exception occurred while set the hideEmptyScheduleWeekvalue as true with setState in onViewChanged callback in Flutter Calendar**”. We will include the issue fix in our upcoming Weekly nuget package, which is expected to be rolled out by March 8, 2022 and let you know once the release rolled out. We appreciate your patience until then.
> 
> Regards, Indumathi R

#549 is linked to this as it is a case of hideemptyscheduleweek not working properly in the case of an event on the 1st of july. Would you be able to include that in this fix?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: hideemptyscheduleweek not working properly in the case of an event on the 1st of july. Would you be able to include that in this fix?**

This is not a is, as per the current implementation of the Flutter Calendar 1st of the July is in last week of the June month and it considers that week has an appointment. So, June month also visible in calendar UI. We hope that information helps you. Please get in touch with us if would you require further assistance.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have fixed the mentioned issue “**Exception occurred while set the hideEmptyScheduleWeekvalue as true with setState in onViewChanged callback in Flutter Calendar**” and included the issue fix in our latest weekly nuget package version 19.4 55. Kindly update to the latest version for resolving the issue. Please find the latest version from the following link.

**Pub link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions/19.4.55 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
