### ISSUE TITLE
 After notifyListeners : A Scrollbar cannot be painted without a ScrollPosition.

### ISSUE THREAD

**Issue by Stratj-YannDupuis** [syncfusion/flutter-examples#553]
In web app, when I change language of the app I user notifyListeners for apply new language.  Its work well but if I show sfcalendar widget at this time, the language change and rebuild the widget and error occurs

`═╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be
associated with the ScrollView that the Scrollbar is being applied to. When providing your own
ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/scrollbar.dart 1300:9                            <fn>
packages/flutter/src/widgets/scrollbar.dart 1324:14                           [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1258:14                           <fn>
packages/flutter/src/scheduler/binding.dart 1144:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1089:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 995:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1011:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 159:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 128:45                                 <fn>
dart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1335:19                                          runUnary
dart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded
dart-sdk/lib/async/zone.dart 1281:26                                          <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
`

If I call notifyListeners() without show sfcalendar and after I return on the sfcalendar widget all good !  I can't find the source of the problem and I dont have more data about this issue.  

I Try to disable all ma listerner in the page who use sfcalendar and I got the same error.  (sorry for my English)
Do you have any idea I found nothing on the web about this issue with sfcalendar

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: And call notifiyListeners() from anyware in the web app during sfcalendar are on screen.**

If possible, can you please share the below details to us. It would be helpful for us to analyze and provide you a solution at the earliest.

•	Code snippet of the listener with scenario.

Regards,
Indumathi R
