### ISSUE TITLE
Is there vertical scroll for changing numberOfWeeksInView in month agenda view?

### ISSUE THREAD

**Issue by dmk3141618** [syncfusion/flutter-examples#556]
Is there vertical scroll for changing numberOfWeeksInView in month agenda view?

There is already horizontal scroll to fire forward, backward.
But I want to use vertical scroll to change numberOfWeeksInView.

Can I do that?

And Can I change some UI of month view between calendar and agendas?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is there vertical scroll for changing numberOfWeeksInView in month agenda view?**

Based on the shared information, we are unable to understand your requirement clearly with illustration image. It would be helpful for us to analyze and provide you a solution at the earliest. Also, by using **navigationDirection** property you can change the navigation direction of the calendar.  

**Regarding Query: Can I change some UI of month view between calendar and agendas?**

You can customize the month view UI by suing the **monthCellBuilder** property of the calendar. Also, we have a KB documentation for agenda view Ui customization. Please find the KB documentation for the same.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder

**KB link:**

https://www.syncfusion.com/kb/11016/how-to-show-a-custom-agenda-view-in-the-flutter-calendar 
https://www.syncfusion.com/kb/12210/how-to-customize-the-month-cell-based-on-the-appointment-using-builder-in-the-flutter

We hope that this helps you. If this is not your requirement, can you please share more details about your requirement clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
