### ISSUE TITLE
[Flutter Calendar] Expand calendar view vertically

### ISSUE THREAD

**Issue by kkondarev** [syncfusion/flutter-examples#558]
Hi, I am trying to make the calendar to take the whole vertical space, have tried different options (like wrapping in Expanded widget, wrapping in SingleChildScrollView, etc), but always end up with just using half of the screen (as in the screenshot), code is below:

`Widget getCalendarView() {

    return SliverList(
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return SingleChildScrollView(
            child: SfCalendar(
              firstDayOfWeek: 1,
              view: CalendarView.month,
              dataSource: TasksDataSource(tasks!),
              monthViewSettings: MonthViewSettings(showAgenda: true),
            ),
          );
        },
        childCount: 1,
      ),
    );
  }`

Can you please suggest how I can make the calendar to take the whole vertical space? Especially for the schedule view, or month view with agenda, this would be extremely helpful.
Thanks!

Best regards
Kras

![tasks](https://user-images.githubusercontent.com/5778568/156926188-6ff4ae60-1634-490a-aaad-ed3d091bd829.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Expand calendar view vertically in SliverList**

We have checked with the wrapping the calendar widget inside the Container widget and assign the height for the Container, it was working fine. We have attached the tested sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_schedulecrash1917335900.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by kkondarev** [comment]
Hi,

thank a lot, this works perfectly!

Best
Kras
