### ISSUE TITLE
[Flutter Calendar] Scrollable day view or month view with day view as agenda

### ISSUE THREAD

**Issue by kkondarev** [syncfusion/flutter-examples#559]
Hi, 

is there an option to display continuous CalendarView.day view - scrollable down and going into the next day (similar to CalendarView.schedule view scrolling behavior)?

Or alternatively - to make CalendarView.month to display agenda (monthViewSettings: MonthViewSettings(showAgenda: true)) based on CalendarView.day, not on CalendarView.schedule?

Thanks and best regards
Kras

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we suspect your requirement is “**Scroll controller support to view the next day in the Flutter Calendar**”. We have already logged the feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below feedback link. 

**Link:** https://www.syncfusion.com/feedback/33008/expose-calendar-scroll-controller-so-we-can-supply-our-own

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Also, we have a KB documentation for displaying the vertical calendar in month view. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12091/how-to-display-two-month-view-calendar-in-a-screen-using-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by kkondarev** [comment]
Perfect, thanks a lot, looking forward to it.
