### ISSUE TITLE
Bar Chart - is it possible to have different widths for different bars in the same chart

### ISSUE THREAD

**Issue by atreeon** [syncfusion/flutter-examples#56]
A chart like below but I would like to make the bar for Algeria really big but keep the others the the size they are now if that is at all possible

<img width="305" alt="Screenshot 2019-11-10 at 18 24 33" src="https://user-images.githubusercontent.com/4139336/68548658-5d8be780-03e7-11ea-8200-ba1f581668b5.png">

**Comment by dharanidharandharmasivam** [comment]
Hi @atreeon ,

Thanks for your interest in our Syncfusion Flutter chart widget. Yes, your requirement is possible using the override methods. Here we have extended the bar series and using the calculateSegmentPoints we have modified the size of Algeria and Moldva points. This can be changed based on your scenario. Find the code snippet below to achieve this scenario.

> 
    class CustomPainter extends BarSegment {
        void calculateSegmentPoints() {
          super.calculateSegmentPoints();
          final double currentHeight = 20;
          if(currentSegmentIndex == 6 || currentSegmentIndex == 1)
             segmentRect = RRect.fromLTRBAndCorners(segmentRect.left, segmentRect.top + 
                     currentHeight, segmentRect.right, segmentRect.bottom -currentHeight);
       }
    }

Screenshot:
![bar_chart](https://user-images.githubusercontent.com/19346074/68587054-19164f80-04ac-11ea-95b6-a91a987f35bf.png)

For your convenience, we have attached the sample which can be found below.
Sample: https://www.syncfusion.com/downloads/support/directtrac/254671/ze/sample-2143631710 

Thanks,
Dharani.
