### ISSUE TITLE
Water Mark Image

### ISSUE THREAD

**Issue by SaadNewton** [syncfusion/flutter-examples#560]
Hello Sir,
I hope you are fine.
I want to have watermark image in the center of my pdf pages. I tried too much but this is not working. Kindly guide me if there is a solution to get watermark image in the center.
Thanks,
Reagrds:
 SaadNewton

**Comment by Surya-3013** [comment]
Hi SaadNewton,

We have created a sample code snippet to achieve your requirement of adding a watermark image at the center. Kindly try with the following code snippet and let us know the result.

`Future<void> _addWatermarkToPDF() async {
    //Load the PDF document.
    PdfDocument documents = PdfDocument(
        inputBytes: await _readDocumentData("PDF_Succinctly-doc1.pdf"));

    for (int i = 0; i < documents.pages.count; i++) {
      //Get first page from document
      PdfPage page = documents.pages[i];
      //Get page size
      Size pageSize = page.getClientSize();
      //Create PDF graphics for the page
      PdfGraphics graphics = page.graphics;
      //Load the image.
      final PdfImage image = PdfBitmap(await _readImageData('Logo1.png'));

      //Calculate the center point.
      double x = pageSize.width / 2 - image.width / 2;
      double y = pageSize.height / 2 - image.height / 2;
      //Save the graphics state for the watermark text
      graphics.save();
      //Tranlate the transform with the center point.
      graphics.translateTransform(x, y);
      //Set transparency level for the text
      graphics.setTransparency(0.25);
      //draw image to the first page
      page.graphics.drawImage(image,
          Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()));

      //Restore the graphics
      graphics.restore();
    }

    //Save the document
    List<int> bytes = documents.save();
    //Dispose the document
    documents.dispose();

    //Save and launch file.
    await FileSaveHelper.saveAndLaunchFile(bytes, 'PDF_Watermark.pdf');
  }`

Regards,
Surya V
