### ISSUE TITLE
[syncfusion_flutter_pdf] add a way to generate a Bitmap Image of a PDF page similar to lib PDFium

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-examples#561]
add a way to generate a Bitmap Image of a PDF page similar to lib PDFium

**Comment by Surya-3013** [comment]
Hi @insinfo ,

We recommend you to load image data in [PdfBitmap](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfBitmap-class.html) object to draw the images using the [drawImage](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfGraphics/drawImage.html) method of the [PdfGraphics](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfGraphics-class.html) class. Kindly refer to the following link to get more details with code snippet, https://help.syncfusion.com/flutter/pdf/working-with-images#inserting-an-image-in-pdf-document and also refer the KB: https://www.syncfusion.com/kb/11965/how-to-convert-image-to-pdf-in-syncfusion-flutter-pdf-library

Kindly try with the UG/KB contains code snippet and let us know the result.

Regards,
Surya V

**Comment by insinfo** [comment]
@Surya-3013

you got it wrong. I meant convert a PDF to Bitmap (PNG/JPEG), similar to [pdfium_bindings](https://pub.dev/packages/pdfium_bindings) 
```dart 
void main() {
  PdfiumWrap()
      .loadDocumentFromPath('1417.pdf')
      .loadPage(0)
      .savePageAsPng('out.png')
      .closePage()
      .closeDocument()
      .dispose();
}
```

**Comment by Surya-3013** [comment]
Hi @insinfo ,

Currently, we don’t have support for converting PDF to image in our library. We have logged a feature request for this support in the PDF document library. We do not have any immediate plans to implement these features and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.

Please find the feedback link to track the implementation of the feature below,
https://www.syncfusion.com/feedback/24217/support-for-converting-pdf-to-image

Regards,
Surya V
