### ISSUE TITLE
[syncfusion_flutter_calendar] Option show more when have too many Appointment in same time ?

### ISSUE THREAD

**Issue by tuannvm-citigo** [syncfusion/flutter-examples#562]
I use this library and it work great until i have too many appointments in same time, like maybe 20 Appointments, then it become show like 20 line in same row, i can't see any information about appointment anymore
Is there a way to show like max 2 Appointment, and show something like +18 below for user tap => show other Appointments

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar, there is no support to show the more option for appointments and now it is applicable for all-day appointments only. Kindly use the month view with **showAgendaView**. In month view you can set the appointment display count and based on this you can see the remaining appointments in agenda view. We have UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/month-view
https://help.syncfusion.com/flutter/calendar/month-view#appointment-display-count 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
