### ISSUE TITLE
[syncfusion_flutter_datepicker] Jalali calendar

### ISSUE THREAD

**Issue by ARASHz4** [syncfusion/flutter-examples#563]
Add Jalali calendar to syncfusion_flutter_datepicker

**Comment by Indumathi1195R** [comment]
Hi,

We have already logged the feature request for “**Providing a support for jalali calendar in the Flutter Date Range Picker (SfDateRangePicker)**”. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

You can track the status of this report through the following feedback link, 

**Feedback link:** 
https://www.syncfusion.com/feedback/24246/providing-a-support-for-jalali-calendar-in-the-flutter-date-range-picker

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
