### ISSUE TITLE
SfCalendar. scheduleViewMonthHeaderBuilder seems it has a bug when StartTime is very small value or 2021.12.15 ( DateTime.fromMillisecondsSinceEpoch(1639534372000) ).

### ISSUE THREAD

**Issue by dmk3141618** [syncfusion/flutter-examples#564]
CalendarDataSource's getStartTime may be used to distinguish month.
But 
first source is
DateTime.fromMillisecondsSinceEpoch(122000) So it is 1970.1.1
next source is
DateTime.fromMillisecondsSinceEpoch(1639534372000) So it is 2021.12.15
next ...
Then
**schedule view's month header** is not shown in scheduleViewMonthHeaderBuilder method. 
And at some cases, scheduleViewMonthHeaderBuilder shows 1969.12 
DateFormat.yMMM().format(details.date), << I am using this code to show month header date format.

And when I update the data and re render schedule view, then duplicated element items are shown which has this DateTime.fromMillisecondsSinceEpoch(122000) start time. I don't know the reason. Because of too small value? or the gap of two sources is too big? Also this includes startTime dataSource is 2021.12.15 (  DateTime.fromMillisecondsSinceEpoch(1639534372000)  ) value. I also suspect this may make this error.

2021.12.15 (  DateTime.fromMillisecondsSinceEpoch(1639534372000)  ) Is this value special for scheduleViewMonthHeader? It seems sfCalendar scheduleViewMonthHeaderBuilder can not distinguish this value month.

And I set minDate: DateTime(1970.01.01) But I can see 1969.12.28 ~ 1970.01.03 scheduleViewMonthHeader. 

And I can not see the first scheduleViewMonthHeader 
when the first startTime dataSource is 2021.12.15 (  DateTime.fromMillisecondsSinceEpoch(1639534372000)  )

Why is it happening?

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query:  I also suspect this may make this error.**

We have tested same scenario ( DateTime.fromMillisecondsSinceEpoch(1639534372000) with the Text widget, it show the below output and same output from the calendar. Please find the attached image for the same.

**Screenshots:**
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/54974849/157835008-a19d26f1-2c73-4126-aa0c-47cb2d6bcc05.png)
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/54974849/157835014-382c3571-cbee-4def-b94b-1d833a5a487b.png)

If possible, can you please share error details clearly with illustration image. It would be helpful for us to analyze and provide you a solution at the earliest.

**Regarding Query: And I set minDate: DateTime(1970.01.01) But I can see 1969.12.28 ~ 1970.01.03 scheduleViewMonthHeader.**

We have set the minDate value using the DateTime.fromMillisecondsSinceEpoch(122000), and it shows the DateTime(1970,01,01), it was working fine as expected from our end.

**Regarding Query: And I can not see the first scheduleViewMonthHeader when the first startTime dataSource is 2021.12.15 DateTime.fromMillisecondsSinceEpoch(1639534372000) )
Why is it happening?**

We have modified the header value (first data source- DateTime.fromMillisecondsSinceEpoch(1639534372000) and second data source -DateTime.fromMillisecondsSinceEpoch(1639534372000)) and it shows the corresponding Date value properly in month header. If possible can you please share the issue details clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by dmk3141618** [comment]
Thank you for your quick reply!


Could you test this gist code ?

https://gist.github.com/dmk3141618/c65da05b2cd66546080ab73b6c8dc39c


![image](https://user-images.githubusercontent.com/81060569/158034360-da0ab70d-7b40-4b9d-a5d0-a91636b9cc11.png)


![image](https://user-images.githubusercontent.com/81060569/158034432-274f0e3e-c99a-4924-aab3-82a66794fd5c.png)

Kind Regards,
Jack Kim

**Comment by dmk3141618** [comment]
And...

    eventsDataSource.appointments?.clear();
    eventsDataSource.notifyListeners(
      CalendarDataSourceAction.reset,
      [],
    );
    eventsDataSource.appointments?.addAll(myEvents);
    eventsDataSource.notifyListeners(
      CalendarDataSourceAction.reset,
      myEvents,
    );

After notifyListeners reset, it shows duplicated events in schedule view

**Comment by dmk3141618** [comment]
Future<void> updateEventsDataSource() async {
    eventsDataSource.appointments?.clear();
    eventsDataSource.notifyListeners(
      CalendarDataSourceAction.reset,
      [],
    );
    **// if there isn't delay between clear and addAll, it will show duplicated events.
    await Future.delayed(const Duration(milliseconds: 500));**
    eventsDataSource.appointments?.addAll(myEvents);
    eventsDataSource.notifyListeners(
      CalendarDataSourceAction.reset,
      myEvents,
    );
  }

**Comment by Indumathi1195R** [comment]
Hi,

Currently we are validating the mentioned issue ”Schedule view month header doesn’t shown in the Flutter Calendar ”.  We will validate and update you the further details on or before March 17, 2022. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by dmk3141618** [comment]
Thank you!

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the mentioned issue ”**Schedule view month header doesn’t shown and shows the duplicate value in the Flutter Calendar** ”. We will include the issue fix in our upcoming 2022 Volume 1 release, which is expected to be rolled out by end of March 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have included the mentioned issue fix for ”**Schedule view month header doesn’t shown and shows the duplicate value in the Flutter Calendar** ” in our upcoming 2022 Volume 1 release **version 20.1.47.** Kindly update to the latest version for this issue fix. Please find the latest version from the following link.

Latest version link: 
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
