### ISSUE TITLE
How to toggle between weekdays and weekend

### ISSUE THREAD

**Issue by Ashutosh619-sudo** [syncfusion/flutter-examples#565]
I want to enable and disable both weekdays and weekends in the calendar but there is no way of doing it. I have a checkbox for both weekends and weekdays, so when one is checked it must show the corresponding dates, and when both are selected it must show all the dates for the month. It must disable the dates which are not checked. Is there a way to do this ?.

**Comment by Ashutosh619-sudo** [comment]
Thank you @Indumathi1195R that solution was very useful, but I have another question, what if I want to customize these weekdays and weekends differently than the blackout dates, then adding these to blackout dates won't help, is there another way to do that, I am using blackout dates for another purpose.

**Comment by Indumathi1195R** [comment]
Hi,

By using the [monthCellBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/monthCellBuilder.html) property of the calendar you can customize the weekend dates and weekdays. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_appbuilder1918215748.zip 

Also please find the UG documentation for the same.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder 

We hope that this helps you. If this is not your requirement, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Ashutosh619-sudo** [comment]
Thanks, @Indumathi1195R but we are using SFDateRangePicker, and monthCellBuilder is not useful for us. What we want to achieve is to have a toggle for weekends and weekdays and when we click on it we will **disable** weekday or weekend depending on which one was clicked, currently, we are doing this by adding weekends and weekdays inside blackOutDates list, but the problem is that we are using blackOutDates for another purpose and adding weekends and weekdays into this will have the same styling and we don't want to do that we want different styling for weekdays and weekends(also they must be disabled). We want to disable weekdays and weekends and have different styling from the blackout dates.

**Comment by Indumathi1195R** [comment]
Hi,

You can achieve this requirement by using the [blackouDates](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthViewSettings/blackoutDates.html) property of the SfDateRangePicker. For styling disabled dates, you can use [blackoutDateTextStyle](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDateTextStyle.html) and [blackoutDateDecoration](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDatesDecoration.html) property of the DateRangePickerMonthCellStyle. We have prepared the simple prototype sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_blackdate2054955642.zip 

Please find the UG documentation for the same.

**UG links:**

https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates 

https://help.syncfusion.com/flutter/daterangepicker/customizations#month-cell-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have prepared the sample with [selectableDayPredicate](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/selectableDayPredicate.html) and blackoutDates property for your requirement and styling the selectable day predicate dates using [disableDatesTextStyle](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/disabledDatesTextStyle.html) and [disableDatesDecoration](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/disabledDatesDecoration.html), style the blackout dates using [blackoutDatesTextStyle](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDateTextStyle.html) and [blackoutDatesDecoration](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDatesDecoration.html). Please find the sample from the following link.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_blackdate_(1)2119330476.zip

Also, we have a support for special dates. Please find the KB documentation for the same.

KB link:
https://www.syncfusion.com/kb/12374/how-to-customize-the-special-dates-using-builder-in-the-flutter-date-range-picker

Please find the UG documentation for selectableDayPredicate, blackoutDates, specialDates the same.

UG links:

https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates 

https://help.syncfusion.com/flutter/daterangepicker/customizations#month-cell-customization

https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#selectabledaypredicate 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Ashutosh619-sudo** [comment]
Thanks, @Indumathi1195R your solution works partially for us. Let me give you a bit more context here so that it will be easier for you to provide the solution. 
We are working on a slot booking functionality for which we want to display already booked dates according to month(data comes from backend) and we also want to provide a filter for weekdays and weekends(ability to disable it). Suppose there are already 4 booked dates in the month of March and we are passing those dates to selectablepredicate argument of SFDateRangePicker and this is working fine for this case only, now suppose there are other dates that are already booked in the month of April that we want to disable, now if we change month view from March to April and if we pass those dates to selectablepredicate the dates on the calendar does not get disabled because selectablepredicate argument is being called before onViewChange function(in this function we fetch data from backend for already booked dates and then pass those data to selectablepredicate).
What we basically want is whenever we change our month view the new dates should be disabled according to the passed date argument.
Also, is there any possibility to change the styling for past dates and disabled dates(dates that are being passed to selectablepredicate) because we want to have different styling for past dates, blackoutdates and disabled dates?.

**Comment by Indumathi1195R** [comment]
Hi,

As per the current behavior of the date range picker, we can't update selectable predicate dates based on the onViewChanged callback. Because the selectablePredicate callback was triggered before the onViewCanged callback. You can compare the required dates with the selectable predicate callback itself and add required dates as a selectable predicate dates.  If possible, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Also by using the [disableDatesTextStyle](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/disabledDatesTextStyle.html) and [disableDatesDecoration](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/disabledDatesDecoration.html) properties you can style the selectable predicate dates(disabled dates) and using the [blackoutDatesTextStyle](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDateTextStyle.html) and [blackoutDatesDecoration](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerMonthCellStyle/blackoutDatesDecoration.html)  properties you can style the  blackoutDates. We have UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/customizations#month-cell-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
