### ISSUE TITLE
[SfCalendar] Is it possible to fit whole day view in given space?

### ISSUE THREAD

**Issue by kkondarev** [syncfusion/flutter-examples#566]
Hi,

is there a configuration to fit whole day (CalendarView.day) into given container, so that the whole day is visible without scrolling (with smaller hours cells)?

Thanks and best regards
Kras

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is it possible to fit whole day view in given space?**

Based on the shared information, we suspect your requirement is ”To view the whole day without scrolling in the Flutter Calendar” an your requirement can be achieved by setting the [timeIntervalHeight](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/timeIntervalHeight.html) property value as -1 in the [timeSlotViewSettings](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/TimeSlotViewSettings.html). We have UG and KB documentation for the same. Please find the UG and KB documentation for the same.

**UG link:**
https://help.syncfusion.com/flutter/calendar/timeslot-views#full-screen-calendar

**KB link:**
https://www.syncfusion.com/kb/12231/how-to-autofit-the-calendar-to-screen-height-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by kkondarev** [comment]
This is exactly what I needed!! Thanks a lot!

Best
Kras
