### ISSUE TITLE
[SfDateRangePicker] adding padding inside the DateRangePicker

### ISSUE THREAD

**Issue by hugotiem** [syncfusion/flutter-examples#567]
i would like to add padding inside my SfDateRangePicker widget between dates rows, and also around the calendar without cutting the range selection.

for now it looks like that: 
![IMG_9309](https://user-images.githubusercontent.com/19958081/158264267-94824279-6bb9-4c38-b25e-064381f075c4.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: i would like to add padding inside my SfDateRangePicker widget between dates rows, and also around the calendar without cutting the range selection.**

As per the current implementation, no support to reduce the space between the date rows. By placing the SfDateRangePicker inside the Card widget, you can add the margin for all sides. Please find the code snippet for the same.

**Code snippet:**
```
body: Card(
  margin: const EdgeInsets.fromLTRB(50, 200, 50, 200),
  child: SfDateRangePicker(
        view: DateRangePickerView.month,
        selectionMode: DateRangePickerSelectionMode.range,
        navigationDirection: DateRangePickerNavigationDirection.vertical,
      ),
),
```
**Screenshot:**
 
![vidma_recorder_15032022_123935](https://user-images.githubusercontent.com/54974849/158327577-4708166f-9447-48c6-bb93-c5441a7f6cc0.jpg)


We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
