### ISSUE TITLE
How to set "TrackballBehavior" on left side when it being covered

### ISSUE THREAD

**Issue by internelp** [syncfusion/flutter-examples#568]
My code:

```
child: SfCartesianChart(
                      trackballBehavior: TrackballBehavior(
                        enable: true,
                        activationMode: ActivationMode.singleTap,
                        hideDelay: 2000,
                        lineWidth: 0.5,
                        lineType: TrackballLineType.vertical,
                        markerSettings: const TrackballMarkerSettings(
                            shape: DataMarkerType.circle,
                            markerVisibility: TrackballVisibilityMode.visible),
                        tooltipAlignment: ChartAlignment.near,
                        tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
                        tooltipSettings: const InteractiveTooltip(
                          canShowMarker: false,
                        ),
                      ),
```

![Simulator Screen Shot - iPhone 13 mini - 2022-03-15 at 10 32 55](https://user-images.githubusercontent.com/3395436/158295678-f32e53f9-4a48-4055-8f6d-ff3e9febf22a.png)
![Simulator Screen Shot - iPhone 13 mini - 2022-03-15 at 10 33 00](https://user-images.githubusercontent.com/3395436/158295704-d959e465-ea54-46de-93cd-840c9ee63b8c.png)

![Simulator Screen Shot - iPhone 13 mini - 2022-03-15 at 10 33 06](https://user-images.githubusercontent.com/3395436/158295721-41b61c01-d858-437f-b531-458e0fc74af7.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @internelp,

Greetings from Syncfusion. We have a few improvements in the trackball tooltip display, with that itself the reported issue has been resolved already and will get rolled out in the vol1 main release which is expected on middle of next week. We will update you once the release gets rolled out and we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by dharanidharandharmasivam** [comment]
Hi @internelp ,

Thanks for your patience. The vol 1 main release has been rolled out and to overcome the reported scenario, kindly upgrade the chart widget to the latest version from below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.47+1 

Thanks,

Dharani.

**Comment by internelp** [comment]
> Hi @internelp ,
> 
> Thanks for your patience. The vol 1 main release has been rolled out and to overcome the reported scenario, kindly upgrade the chart widget to the latest version from below.
> 
> https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.47+1
> 
> Thanks,
> 
> Dharani.

That's great, thank you Dharani.
