### ISSUE TITLE
Problems with Hebrew translation

### ISSUE THREAD

**Issue by amirdt** [syncfusion/flutter-examples#569]
Can you please fix the Hebrew (he) translations:

day: יום
week: שבוע
month: חודש

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Problem with Hebrew translation.**

We have ensured the Hebrew translation issue with the allowed views text. Allowed views texts are translated to the corresponding language as per the Google translation and working fine as expected. We have prepared a simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_localize_(1)-2064698978.zip

Screenshot:
![vidma_recorder_16032022_143242](https://user-images.githubusercontent.com/54974849/158780651-c59c3278-5631-4d98-923a-757acd91f08f.jpg)

We hope that this helps you. If possible, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
