### ISSUE TITLE
Graph Area (within some height and width)

### ISSUE THREAD

**Issue by darpan2212** [syncfusion/flutter-examples#57]
When I am using SfCartesianChart() widget to my viewport, It'll cover the random screen area based on the remaining space it has.

Is it possible to give some specific height and width to it?

**Comment by dharanidharandharmasivam** [comment]
Hi @darpan2212 ,

Greetings from Syncfusion and thanks for your interest in our Flutter components. You can specify the size (height and width) to the chart like the below code.

> 
      Container(
          height: 300,
          width: 300,
          child: SfCartesianChart(
              // Other configurations
          )
        )


For your convenience, we have attached the sample which can be found from below.
https://www.syncfusion.com/downloads/support/directtrac/256041/ze/sample-1131461163 

Thanks,
Dharani.

**Comment by darpan2212** [comment]
Thanks a lot @dharanidharandharmasivam
