### ISSUE TITLE
timelineDay view Vertical mode

### ISSUE THREAD

**Issue by mdikcinar** [syncfusion/flutter-examples#570]
Is there a way to show timelineDay in vertical mode?
I want to posisition the resourceViewHeader to top and the timeSlots to left side with a vertical scrollview.
I couldn't see but is there a way to do that?

**Comment by Indumathi1195R** [comment]
Hi,

We have already logged the feature request “**Horizontal resource grouping support in the Flutter Calendar**”. We will implement this feature in any of our upcoming and let you know once the release rolled out. We appreciate your patience until then.

We will prioritize the features every release based on the demands, and we do not have an immediate plan to implement this feature and we will implement this feature in any of our upcoming release.

You can track the status of this report through the following feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/15067/horizontal-resource-grouping-support-in-the-flutter-event-calendar-sfcalendar  

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
