### ISSUE TITLE
[syncfusion_flutter_calendar] schedule view header

### ISSUE THREAD

**Issue by dmk3141618** [syncfusion/flutter-examples#572]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/81060569/158924966-35079726-333c-4252-a4ec-73306acabe76.png">

I have to custom a header. But syncfusion flutter calendar's default header may not be available to custom.
So I made custom element for the header. And hide default syncfusion calendar header using headerHeight: 0.0.
But some icons of the default header are appeared in a release build.
I can not see the default header icons in dev debug mode. But only it appears when release build.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/81060569/158925802-5c970efc-1615-4be8-a80f-d9d558c56710.png">

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue ”**Default calendar icons shown while hiding the default headers in Schedule view of the Flutter Calendar**”. We have prepared the simple sample for hiding the default header and ensured the same with localization. Default header icons are not shown in schedule view and working fine as expected. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_numberofdays1241380117.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
