### ISSUE TITLE
[syncfusion_flutter_calendar] Padding in schedule view event list

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-examples#573]
I set my schedule view to scroll under a transparent/blurred bottombar and appbar for a frosted glass effect, like facebook messenger, imessage and other apps. 

The problem is, since there is no option to add padding to the schedule view event list, the first and last events are stuck under the appbar and schedule view.

I would add it myself, but i don't think the public github is up to date. Are the latest releases no longer public/open source?

If so, would it be possible to add this option? I think it can be done via sliverpadding

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar, there is no support for adding the padding event list. But you can achieve this by adding the appointment with transparent UI at the end date of the appointment list using the [appointmentBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/appointmentBuilder.html). We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Thanks for the suggested workaround.

It wouldn't be possible to achieve proper alignment since the month and appointment heights cannot be set separately for these "padding" events, since these heights can only be set once in "ScheduleViewSettings".

Adding this padding would be quite simple using sliverpadding. Is it possible for me to fork the repo from the latest release? I noticed the syncfusion package repo is out of date.

**Comment by muthulakshmi-123** [comment]
Hi Justus,

Based on the shared information, we have analyzed your requirement “Adding silver padding event list on calendar schedule view”. As per the current implementation of the calendar, there is no support to add padding event lists in the schedule view.

Regards, 
Muthulakshmi K

**Comment by Justus-M** [comment]
Thanks for this info. As mentioned, I would like to do it myself. Is it possible for me to fork the latest repo? I noticed the syncfusion widget repos haven't been updated in 3 months.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query:  Is it possible for me to fork the latest repo? I noticed the syncfusion widget repos haven't been updated in 3 months.**

We will update the source repositories for main releases only not Weekly releases. 2022 Volume 1 release will be rolled out at end of March 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
Ok great, thank you!
