### ISSUE TITLE
[Feature Request] Provide a way of preventing swipping

### ISSUE THREAD

**Issue by mtc-jed** [syncfusion/flutter-examples#574]
I would like to disable the hability to swipe to another month in certains cases.
To take an analogy, with `PageView` this is possible, by providing `physics: NeverScrollablePhysics(),`. I'd like the same thing to be available in `SfCalendar`.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Provide a way of preventing swipping**

By using the [viewNavigationMode](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/viewNavigationMode.html) property value as none, you can disable the ability of swiping in the Flutter Calendar. We have a UG and KB documentations for the same. Please find the documentation from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/date-navigations#view-navigation-mode 

**KB link:** https://www.syncfusion.com/kb/12500/how-to-restrict-the-view-navigation-in-the-flutter-date-range-picker 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
