### ISSUE TITLE
Insert a Qr Code

### ISSUE THREAD

**Issue by mouradkherouf** [syncfusion/flutter-examples#576]
Hey,

I'd like to insert a Qr Code in a defined position of an existing page in a pdf file. 

Is it possible with your library ?

Thanks

**Comment by Surya-3013** [comment]
Hi @mouradkherouf ,

We recommend you draw the QR code image with the specific bounds: Rect.fromLTWH(left, top, width, height) in the PdfDocument. Kindly refer to the following code snippet for more details,
```
//Draw the image 
page.graphics.drawImage( PdfBitmap(File('image.jpg').readAsBytesSync()), Rect.fromLTWH( 0, 0, page.getClientSize().width, page.getClientSize().height));
```

Note: **Rect.fromLTWH(left, top, width, height), Here left represents x-axis position and top represents y-axis position in the PDF document and width, height represents to set the draw image width and height.**

Refer to the following articles for more details,
https://help.syncfusion.com/flutter/pdf/working-with-images
https://www.syncfusion.com/kb/11965/how-to-convert-image-to-pdf-in-syncfusion-flutter-pdf-library

Regards,
Surya V
