### ISSUE TITLE
Header icon issues

### ISSUE THREAD

**Issue by shostakov** [syncfusion/flutter-examples#577]
Using the monthly calendar view, when showNavigationArrow is set to true, a rogue event icon appears in the header.  It's not tappable or anything, it just appears there.  Depending on the header style alignment, it either appears beside the right navigation arrow or beneath it.  When I comment out showNavigationArrow, it goes away, however the left navigation arrow still appears, albeit no longer functional.
<img width="982" alt="Screen Shot 2022-03-20 at 5 22 14 PM" src="https://user-images.githubusercontent.com/99548466/159186664-69d61384-3066-4e46-86ef-8fda04aedf2c.png">
<img width="976" alt="Screen Shot 2022-03-20 at 5 23 06 PM" src="https://user-images.githubusercontent.com/99548466/159186669-96c0692c-f3e1-427e-abe6-3e77b8379be4.png">

**Comment by mfurkanyuceal** [comment]
Hello, I have a problem too. I want to change the size of the arrow icon, but I can't. Is there any solution?
![image](https://user-images.githubusercontent.com/22933926/159232757-0c38db0d-872d-4ea1-ad4f-2a2670dbc856.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Header icon issues**

Currently, we are validating the issue “Unwanted icons appearing after upgrading the Flutter version”. We will validate and update to you the further details on or before March 21, 2022. We appreciate your patience until then.

**Regarding Query:  I want to change the size of the arrow icon, but I can't. Is there any solution?**

As per the current implementation of the calendar, there is no direct support to change the navigation arrow icons. Kindly use the custom header with navigation arrow icons with required size. We have a KB documentation for the same. Please find the KB documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/10997/how-to-add-custom-header-and-view-header-in-the-flutter-calendar 

We hope that this helps you. Please let us know if you need further assistance. 

Regards,
Indumathi R

**Comment by Verzu23** [comment]
I have a similar problem in schedule view 

![fgfgfgfg](https://user-images.githubusercontent.com/23505339/159301167-b2b89b76-1f9f-4294-9d8f-82b2ccf850e8.png)

As you can see on the right, two icons are overlapped

Is there a solution or it's a bug?

Thank you guys.

**Comment by Indumathi1195R** [comment]
Hi,

We have considered this an issue “**Span and recurrence icon overlapping issue in Flutter Calendar**” and logged the issue report for the same. We will fix the issue and include the issue fix in our upcoming Weekly nuget releases, which is expected to be rolled out by April 5, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Now, you can track the current status of this issue report by using the below mentioned link. 

**Link:** https://www.syncfusion.com/feedback/33597/text-cropping-and-icon-overlapping-issue-with-recurrence-appointment-in-the 

Regards,
Indumathi R

**Comment by muthulakshmi-123** [comment]
Hi shostakov,

**Regarding Query: Header icon issues**

We are confirmed the mentioned issue **“Unwanted icons appearing after upgrading the Flutter version”**. We have already fixed the issue and the fix is included on our upcoming Volume1, 2022 which is expected to be released on Mar 29, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Regards, 
Muthulakshmi K

**Comment by Indumathi1195R** [comment]
Hi,

We have included the mentioned issue fix for “**Unwanted icons appearing after upgrading the Flutter version**” in our 2022 Volume 1 release version 20.1.47. Kindly update to the latest version to resolve this issue. Please find the latest version from the following link.

**Latest version link:** 
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Verzu23** [comment]
Hi Indumathi,

> Hi,
> 
> We have included the mentioned issue fix for “**Unwanted icons appearing after upgrading the Flutter version**” in our 2022 Volume 1 release version 20.1.47. Kindly update to the latest version to resolve this issue. Please find the latest version from the following link.
> 
> **Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions
> 
> We hope that this helps you. Please let us know if you need further assistance.
> 
> Regards, Indumathi R

I updated the package but i still get the same error as mentioned in 

> I have a similar problem in schedule view
> 
> ![fgfgfgfg](https://user-images.githubusercontent.com/23505339/159301167-b2b89b76-1f9f-4294-9d8f-82b2ccf850e8.png)
> 
> As you can see on the right, two icons are overlapped
> 
> Is there a solution or it's a bug?
> 
> Thank you guys.

**Comment by Indumathi1195R** [comment]
Hi,

We have considered this an issue “**Span and recurrence icon overlapping issue in Flutter Calendar**” and logged the issue report for the same. We will fix the issue and include the issue fix in our upcoming Weekly nuget releases, which is expected to be rolled out by April 5, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Now, you can track the current status of this issue report by using the below mentioned link.

**Link:** https://www.syncfusion.com/feedback/33597/text-cropping-and-icon-overlapping-issue-with-recurrence-appointment-in-the

Regards,
Indumathi R
