### ISSUE TITLE
Syncfusion PDF has problems with Arabic scripts

### ISSUE THREAD

**Issue by theRealProHacker** [syncfusion/flutter-examples#579]
I am using the syncfusion PDF lib and I have problems printing Arabic letters to the page.
When I try to print the word ahlan (which means hello) to the pdf page
اهلَن
It gives me different results depending on the `PdfTextDirection`

With `PdfTextDirection.rightToLeft` or `PdfTextDirection.leftToRight` I get this result:
![almost_empty](https://user-images.githubusercontent.com/77074862/159949761-27f9d8fd-0249-4ff6-8b99-1905fa077ac5.png)

With `PdfTextDirection.none` (aka the default) I get this result:
![wrong direction](https://user-images.githubusercontent.com/77074862/159949885-946f8bac-8c24-43c8-b0a5-98039a2d36b0.png)

Here is my code:
```dart
text = "اهلَن";
final document = PdfDocument();
final page = document.pages.add();
// create Font (This part works fine)
final fontBytes = await rootBundle.load('fonts/Lateef-Regular.ttf');
final bytesLength = fontBytes.lengthInBytes;
final _protoList = <int>[];
for (int i = 0; i<bytesLength; i++){
  final byte = fontBytes.getUint8(i);
  _protoList.add(byte);
}
final uintlist = Uint8List.fromList(_protoList);
final font = PdfTrueTypeFont(uintlist, 14);
// Write to file
// Here I had tried different things
final textDirection = PdfTextDirection.none;
PdfTextElement(
  text: text,
  font: font,
  brush: PdfSolidBrush(PdfColor(0, 0, 0)),
  format: PdfStringFormat(
    textDirection: textDirection
  )
)
.draw(
  page: page,
  bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, page.getClientSize().height),
  format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate)
)!;

// Save and dispose
await file.writeAsBytes(document.save());
document.dispose();
```

I am using `Flutter version 2.10.3`
and  `syncfusion_flutter_pdf: ^19.4.56-beta`
I tried on Windows 10.

I forgot to mention. The desired version would be that it prints from right to left without mutilating the text.

**Comment by Surya-3013** [comment]
Hi @theRealProHacker ,

We were able to reproduce the reported issue with the provided details. Currently, we are analyzing on this and we will update the further details on March 29th, 2022.

Regards,
Surya V

**Comment by Surya-3013** [comment]
Hi @theRealProHacker ,

Thank you for contacting Syncfusion support.

The provided font “Lateef_Regular.ttf” has open type features. Currently we do not have support to draw complex script language text using font with open type features. We have logged the feature for “Complex script text drawing support in Flutter PDF” and added to our feature request list. We will implement this feature in any of our upcoming release.  

You can track the feature status using the feedback from [https://www.syncfusion.com/feedback/20541/complex-script-text-drawing-support-in-flutter-pdf](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F20541%2Fcomplex-script-text-drawing-support-in-flutter-pdf&data=04%7C01%7Csurya.venkatesan%40syncfusion.com%7C505ced18835640a688d908da11876910%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637841570524998866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pvO2JLpxx50J9G09yPoF4GgwKhqdGiu57eLeMhnzxHk%3D&reserved=0)

However, it is possible to draw complex script text using fonts that supports the character and without any open type features.

Kindly let us know if you need any further assistance in this.

Regards,
Surya V

**Comment by theRealProHacker** [comment]
Do you know what similar fonts without open type features exist? Or do you maybe know how to detect whether a font has open type features?

**Comment by Surya-3013** [comment]
Hi @theRealProHacker ,

We recommend you to use the supported TrueType font like Arial to render the RTL language texts. At present, we do not have a separate API to find the open type feature in the given font. So, kindly check the font details on third-party websites like https://fontdrop.info/ helps to find whether the given font contains open type features or not.

Regards,
Surya V
