### ISSUE TITLE
Spline chart color

### ISSUE THREAD

**Issue by anisalibegic** [syncfusion/flutter-examples#58]
Is it possible to paint the space below the spline? Something like this:

![image](https://user-images.githubusercontent.com/12012869/69544340-cc447580-0f8f-11ea-971e-563cc1b7de16.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @anisalibegic ,

Thanks for your interest in the Syncfusion Flutter chart widget. Your requirement can be achieved using the SplineArea series. As of now, it is not available, but we already have this in our roadmap, and it has been implemented. This is in the testing phase and it will be available in volume 4 main release which is expected to be out in the middle of December 2019. We will update you once the release is rolled and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by anisalibegic** [comment]
I saw you published **17.4.40** version. Does it include this feature?

**Comment by dharanidharandharmasivam** [comment]
Hi @anisalibegic ,

Yes, the spline area series has been implemented and included in the volume 4 main release and thanks for your patience. To use the feature, kindly upgrade your packages from the below link.

https://pub.dev/packages/syncfusion_flutter_charts/versions/17.4.40 

Sample: https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/area_series/spline_area.dart 

User Guide: https://help.syncfusion.com/flutter/chart/cartesian-chart-types#spline-area-chart

Thanks,
Dharani.

**Comment by anisalibegic** [comment]
Thank you very much for your hard work.
