### ISSUE TITLE
I have a problem with icon on header

### ISSUE THREAD

**Issue by AkkiKosmonk** [syncfusion/flutter-examples#580]
![Screenshot_1648190792](https://user-images.githubusercontent.com/98389569/160068990-0eb29652-8b02-4bb5-b49b-aacca46158d5.png)

SfDateRangePicker(
                    maxDate: DateTime.now(),
                    onSelectionChanged: _onSelectionChanged,
                    selectionMode: DateRangePickerSelectionMode.single,
                    initialSelectedRange: PickerDateRange(
                        DateTime.now().subtract(const Duration(days: 4)),
                        DateTime.now().add(const Duration(days: 3))),
                  ),

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the mentioned issue “**Header navigation arrow icon overlaps in Flutter DateRangePicker**”. We will include the issue fix in our upcoming 2022 Volume 1 release, which is expected to be rolled out by end of March 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have included the mentioned issue fix for “**Header navigation arrow icon overlaps in Flutter DateRangePicker**” in our 2022 Volume 1 release version 20.1.47. Kindly update to the latest version to resolve this issue. Please find the latest version from the following link.

**Latest version link:** 
https://pub.dev/packages/syncfusion_flutter_datepicker/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by AkkiKosmonk** [comment]
Done
