### ISSUE TITLE
Add support for html in syncfusion pdf 

### ISSUE THREAD

**Issue by alihassan143** [syncfusion/flutter-examples#583]

**Comment by Surya-3013** [comment]
Hi @alihassan143 ,

At present, We do not have support for converting HTML to PDF in Flutter platform. We have logged a feature request for this support in the PDF document library. We do not have any immediate plans to implement these features and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.

Please find the feedback link to track the implementation of the feature below,
https://www.syncfusion.com/feedback/18068/add-support-for-converting-html-to-pdf-in-flutter-platform  

Regards,
Surya V
