### ISSUE TITLE
Error when generating an image in Flutter web.

### ISSUE THREAD

**Issue by SittiphanSittisak** [syncfusion/flutter-examples#586]
Hi, I use your example project. This works fine on mobile.
But in the flutter web, This error below was shown when I pressed the 'To Image' button.
`
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/scene_builder.dart:94:16 matrix4[0] == window.devicePixelRatio && matrix4[5] == window.devicePixelRatio is not true at Object.throw_ [as throw] (http://localhost:49319/dart_sdk.js:5391:11) at Object.assertFailed (http://localhost:49319/dart_sdk.js:5313:15) at _engine.SurfaceSceneBuilder.new.pushTransform (http://localhost:49319/dart_sdk.js:178150:133) at layer$.OffsetLayer.new.toImage (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:1505:17) at toImage.next (<anonymous>) at runBody (http://localhost:49319/dart_sdk.js:43013:34) at Object._async [as async] (http://localhost:49319/dart_sdk.js:43044:7) at layer$.OffsetLayer.new.toImage (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:1499:20) at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:49319/packages/flutter/src/rendering/proxy_box.dart.lib.js:3674:26) at main._MyHomePageState.new._handleSaveButtonPressed (http://localhost:49319/packages/kt_eclaim/main.dart.lib.js:602:70) at _handleSaveButtonPressed.next (<anonymous>) at runBody (http://localhost:49319/dart_sdk.js:43013:34) at Object._async [as async] (http://localhost:49319/dart_sdk.js:43044:7) at main._MyHomePageState.new.[_handleSaveButtonPressed] (http://localhost:49319/packages/kt_eclaim/main.dart.lib.js:599:20) at ink_well._InkResponseState.new.[_handleTap] (http://localhost:49319/packages/flutter/src/material/icon_button.dart.lib.js:43171:31) at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:49319/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18) at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:427:40) at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:229:12) at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:49319/packages/flutter/src/gestures/tap.dart.lib.js:175:23) at tap.TapGestureRecognizer.new.handleEvent (http://localhost:49319/packages/flutter/src/gestures/recognizer.dart.lib.js:454:16) at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:94:9) at http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:125:26 at LinkedMap.new.forEach (http://localhost:49319/dart_sdk.js:29123:11) at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:122:29) at pointer_router.PointerRouter.new.route (http://localhost:49319/packages/flutter/src/gestures/pointer_router.dart.lib.js:114:37) at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:394:26) at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:380:24) at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49319/packages/flutter/src/rendering/layer.dart.lib.js:5808:13) at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:353:14) at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:326:43) at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:315:14) at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:49319/packages/flutter/src/gestures/binding.dart.lib.js:305:65) at Object.invoke1 (http://localhost:49319/dart_sdk.js:203779:7) at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:49319/dart_sdk.js:182659:15) at _engine.PointerBinding.__.[_onPointerData] (http://localhost:49319/dart_sdk.js:183585:49) at http://localhost:49319/dart_sdk.js:184068:28 at http://localhost:49319/dart_sdk.js:184021:16 at loggedHandler (http://localhost:49319/dart_sdk.js:183695:11)
`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @SittiphanSittisak,

We suspect that you are requesting the exporting functionality of a chart as an image on the web platform. If this is your case, Flutter doesn’t provide support for a few functionalities related to this on the web. Once Flutter has provided the support, we will provide exporting functionality on the web.

If we have misunderstood your query, kindly provide more details on your scenario i.e. When you are receiving this exception, this will be helpful to proceed further.

Regards,
Yuvaraj.

**Comment by SittiphanSittisak** [comment]
Yes, I have already used the latest flutter and this package version.
```
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:syncfusion_flutter_signaturepad/signaturepad.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter SignaturePad Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<SfSignaturePadState> _signaturePadKey = GlobalKey();
  final GlobalKey _repaintBoundaryKey = GlobalKey();

  void _handleClearButtonPressed() {
    _signaturePadKey.currentState!.clear();
  }

  void _handleSaveButtonPressed() async {
    final boundary = _repaintBoundaryKey.currentContext?.findRenderObject()
    as RenderRepaintBoundary?;
    final image = await boundary?.toImage();
    final byteData = await image?.toByteData(format: ImageByteFormat.png);
    final imageBytes = byteData?.buffer.asUint8List();
    if (imageBytes != null) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (BuildContext context) {
            return Scaffold(
              appBar: AppBar(
                title: const Text('Image'),
              ),
              body: Center(
                child: Image.memory(imageBytes),
              ),
            );
          },
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(10),
              child: SizedBox(
                height: 120,
                child: RepaintBoundary(
                  key: _repaintBoundaryKey,
                  child: Stack(
                    children: [
                      RichText(
                        text: const TextSpan(
                          text: 'Name : ....................................\n',
                          style: TextStyle(fontSize: 26, color: Colors.black),
                          children: <TextSpan>[
                            TextSpan(
                                text:
                                '\nSignature : (........................)',
                                style: TextStyle(fontWeight: FontWeight.bold)),
                            TextSpan(
                                text:
                                '\nDate : ............/............../..........'),
                          ],
                        ),
                      ),
                      Container(
                          child: SfSignaturePad(
                              key: _signaturePadKey,
                              backgroundColor: Colors.transparent,
                              strokeColor: Colors.red,
                              minimumStrokeWidth: 1.0,
                              maximumStrokeWidth: 4.0),
                          decoration: BoxDecoration(
                              border: Border.all(color: Colors.grey))),
                    ],
                  ),
                ),
              ),
            ),
            Row(children: <Widget>[
              TextButton(
                  child: const Text('To Image'),
                  onPressed: _handleSaveButtonPressed),
              TextButton(
                  child: const Text('Clear Signature'),
                  onPressed: _handleClearButtonPressed)
            ], mainAxisAlignment: MainAxisAlignment.spaceEvenly)
          ],
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center),
    );
  }
}
```

It works when run by this dropdown below.
![image](https://user-images.githubusercontent.com/59549741/161888250-5687edc1-a931-49a7-b104-c7208ac64a21.png)

But it doesn't work when run by
`flutter run -d chrome --no-sound-null-safety --web-renderer=html`
or deploy this project to the firebase host.
`flutter build web --no-sound-null-safety --web-renderer=html`

**Comment by PraveenGopalsamy** [comment]
Hi SittiphanSittisak,

Thank you for the details. Now we can reproduce the below exception at our end. 

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/scene_builder.dart:94:16
matrix4[0] == window.devicePixelRatio &&
            matrix4[5] == window.devicePixelRatio
is not true
    at Object.throw_ [as throw] (http://localhost:58061/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:58061/dart_sdk.js:4992:15)
    at _engine.SurfaceSceneBuilder.new.pushTransform (http://localhost:58061/dart_sdk.js:166939:135)
    at layer$.OffsetLayer.new.toImage (http://localhost:58061/packages/flutter/src/rendering/layer.dart.lib.js:1424:17)
    at toImage.next (<anonymous>)
    at runBody (http://localhost:58061/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:58061/dart_sdk.js:40621:7)
    at layer$.OffsetLayer.new.toImage (http://localhost:58061/packages/flutter/src/rendering/layer.dart.lib.js:1418:20)
    at proxy_box.RenderRepaintBoundary.new.toImage
    (http://localhost:58061/packages/flutter/src/rendering/proxy_box.dart.lib.js:3351:26)
    at main._MyHomePageState.new._handleSaveButtonPressed
    (http://localhost:58061/packages/flutter_signaturepad/main.dart.lib.js:597:70)
    at _handleSaveButtonPressed.next (<anonymous>)
    at runBody (http://localhost:58061/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:58061/dart_sdk.js:40621:7)
    at main._MyHomePageState.new.[_handleSaveButtonPressed]
    (http://localhost:58061/packages/flutter_signaturepad/main.dart.lib.js:594:20)
    at ink_well._InkResponseState.new.[_handleTap]
    (http://localhost:58061/packages/flutter/src/material/icon_button.dart.lib.js:40468:31)
    at tap.TapGestureRecognizer.new.invokeCallback
    (http://localhost:58061/packages/flutter/src/gestures/recognizer.dart.lib.js:190:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:58061/packages/flutter/src/gestures/tap.dart.lib.js:409:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:58061/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer
    (http://localhost:58061/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
    at tap.TapGestureRecognizer.new.handleEvent
    (http://localhost:58061/packages/flutter/src/gestures/recognizer.dart.lib.js:426:16)
    at pointer_router.PointerRouter.new.[_dispatch]
    (http://localhost:58061/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:58061/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:58061/dart_sdk.js:27679:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes]
    (http://localhost:58061/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
    at pointer_router.PointerRouter.new.route
    (http://localhost:58061/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:364:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:352:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:58061/packages/flutter/src/rendering/layer.dart.lib.js:5427:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:328:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:302:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:292:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:58061/packages/flutter/src/gestures/binding.dart.lib.js:283:54)
    at Object.invoke1 (http://localhost:58061/dart_sdk.js:190405:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:58061/dart_sdk.js:171081:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:58061/dart_sdk.js:171963:49)
    at http://localhost:58061/dart_sdk.js:172401:28
    at http://localhost:58061/dart_sdk.js:172357:16
    at loggedHandler (http://localhost:58061/dart_sdk.js:172062:11)
```
This exception is raised only while using the web renderer as HTML, there is no exception raised when we use the web renderer as CanvasKit.  Also, the issue is not reproduced when we test the same on other platforms. We are currently checking on it and will update you with further details on 07 April 2022.

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi SittiphanSittisak,

This exception is raised from the Flutter web SDK - Assert failure in the scene_builder.dart file. There is already a framework issue report regarding this. You can track the status of this Flutter framework issue from the following link.

**Framework Issue Report:** https://github.com/flutter/flutter/issues/49857#issuecomment-737883223

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by SittiphanSittisak** [comment]
Thank you. I will follow this link.

**Comment by SittiphanSittisak** [comment]
Hi, I build by using Flutter build web. Then it works.
But when I try this on the mobile by using edge, chrome. It will error
`Unsupported operation: toImage is not supported on the Web`
How to fix this?

**Comment by SittiphanSittisak** [comment]
ref https://stackoverflow.com/questions/64583461/how-to-use-skia-canvaskit-in-flutter-web
I can use toImage when building with `flutter build web --web-renderer canvaskit`. But this method has a bug with using the RepaintBoundary widget on the mobile web.
On windows web:
![image](https://user-images.githubusercontent.com/59549741/162871646-84a725f2-74f2-4b0d-a0ba-cb2b233042eb.png)
On the mobile web:
![222377](https://user-images.githubusercontent.com/59549741/162871109-565c4adb-614c-445d-a8c1-275f376cf296.jpg)

How to fix this?

**Comment by SittiphanSittisak** [comment]
Hi, I think that is a bug of Flutter.
So, I create a new issue of Flutter (https://github.com/flutter/flutter/issues/101738).
If you think that your plugin is not about this issue, you can close this issue.
So many thanks.

**Comment by PraveenGopalsamy** [comment]
Hi SittiphanSittisak,

Thank you for the update.

Yes, this is an issue in the Flutter framework. Once the issue is resolved by the Flutter team, there won't be any issues further.

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by SittiphanSittisak** [comment]
Thank you for your response. All are clear, time to close this.
