### ISSUE TITLE
Write on Wrong coordinates 

### ISSUE THREAD

**Issue by OsamaQureshi796** [syncfusion/flutter-examples#587]
Hi
Thanks Syncfusion for such an awesome work and help towards community.
I'm stuck from last 2 weeks to figure out how to write text,image or anything in the pdf. I'm done with writing it on PDF but the text, image is wrote on wrong coordinates even though i'm storing exactly same thing as get from gradding. 

https://user-images.githubusercontent.com/58250220/161530951-e53c8584-90d4-443e-986a-b11169de1a0d.mp4

**Comment by Surya-3013** [comment]
Hi @OsamaQureshi796 , 

We recommend you refer to the following UG documentation will explain with a code snippet, how to write text and draw images on the PDF document.
Write text: https://help.syncfusion.com/flutter/pdf/working-with-text
Draw image: https://help.syncfusion.com/flutter/pdf/working-with-images

If the above details do not help to resolve your issue, Kindly revert us with the below required details. So, it will help us to provide a precise solution. 
•	Syncfusion package details with version.
•	Flutter doctor details.
•	Modified sample or complete code snippet to replicate the issue on our end.

Regards,
Surya V

**Comment by OsamaQureshi796** [comment]
Actually the problem is not regarding how to draw text or images but the problem is it not correctly write content on correct location.

Bellow is the details.

**Package:**
_syncfusion_flutter_pdf: ^19.4.56-beta_

**Flutter doctor Details**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 11.2 20D64
    darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.59.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Code snippet link**

Code is shared through email.

**Comment by OsamaQureshi796** [comment]
Actually the problem is not regarding how to draw text or images but the
problem is it not correctly write content on correct location.

Bellow is the details.

Package:
*syncfusion_flutter_pdf: ^19.4.56-beta*

Flutter doctor Details

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 11.2 20D64
darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK
version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
! Flutter recommends a minimum Xcode version of 13.
Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.59.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by irfanajaffer** [comment]
![image](https://user-images.githubusercontent.com/93319208/210938499-9e5e9b90-884b-4b0e-9346-91b345cd2b7a.png)
