### ISSUE TITLE
Jalali Dates

### ISSUE THREAD

**Issue by AlphaCodeProgrammer** [syncfusion/flutter-examples#588]
please Do something about Jalali Dates to make it perfect

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have already considered your requirement as a feature for “**Providing a support for jalali and Hijri calendar in the Flutter Event Calendar(SfCalendar)**” and we have logged the feature request for the same. We will implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:**
https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by AlphaCodeProgrammer** [comment]
thank you i hope it comes out as soon as possible because we really need that thank you

**Comment by AlphaCodeProgrammer** [comment]
i can give you useful data for add Jalali date to syncfusion calendar you can use this package for convert Gregorian  to Jalali date [https://pub.dev/packages/shamsi_date](url) 
and this package for convert English numbers to Persian numbers [https://pub.dev/packages/shamsi_date](url)
and then make this calendar **AMAZING**!

**Comment by AmandaJralson** [comment]
please add jalali date , we need this!!

**Comment by AmandaJralson** [comment]
> thank you i hope it comes out as soon as possible because we really need that thank you

yes i'm agree

**Comment by AlphaCodeProgrammer** [comment]
> > thank you i hope it comes out as soon as possible because we really need that thank you
> 
> yes i'm agree

yes we need that
