### ISSUE TITLE
Month lowcase on change language for pt-BR

### ISSUE THREAD

**Issue by Mateusvaz89** [syncfusion/flutter-examples#589]
localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('pt'),
      ]
![Simulator Screen Shot - iPhone 11 - 2022-04-05 at 11 25 54](https://user-images.githubusercontent.com/59057718/161776542-59851838-058c-4e07-b644-89db3c844691.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Month lowcase on change language for pt-BR**

In Calendar texts are translated to the corresponding language as per the Google translation and as per the translation it was working fine as expected. We have attached the screenshot image for the same.

**Screenshot:**
![image](https://user-images.githubusercontent.com/54974849/186832770-0b9088bc-2d50-4d77-a551-d8c9e455472b.png)

Also, we have a KB documentation for localize the custom text in the Flutter Calendar. Please find the documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/12836/how-to-localize-the-custom-headers-text-in-the-flutter-calendar-sfcalendar

We hope that this helps you. If possible, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
