### ISSUE TITLE
[Feature request] Split showDatePickerButton in two parameters

### ISSUE THREAD

**Issue by mtc-jed** [syncfusion/flutter-examples#593]
`showDatePickerButton` shows the month navigation when clicking on the month header, and the button positionning the calendar to today.
I'd like to hide the today button but keep the month navigation.

**Comment by mtc-jed** [comment]
I want to hide the Todya button despite `showDatePickerButton` being `true`.

**Comment by Indumathi1195R** [comment]
Hi,

We have already documented about this scenario in our API documentation. Please find the documentation from the following link.

**Link:**
https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/showDatePickerButton.html

Also, we suggest to use the custom header for your requirement. We have a KB documentation for the same. Please find the documentation from the following link.

**KB link:** 
https://www.syncfusion.com/kb/10997/how-to-add-custom-header-and-view-header-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by mtc-jed** [comment]
No, this doesn't help, your documentation explicitly states that what I want is not possible : "It also shows Today navigation button on header view."
I just want to hide the today button _only_. That is all.

**Comment by Indumathi1195R** [comment]
Hi,

We have analyzed and considered your requirement of “**Provide support to hide and show the Today icon button in the Flutter Calendar (SfCalendar)**” and we have logged feature request for the same. We will implement this feature in any of our upcoming release. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/34053/provide-support-to-hide-and-show-the-today-icon-button-in-the-flutter-calendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
