### ISSUE TITLE
jalali Calendar and Persian Numbers !! make this calendar perfect 

### ISSUE THREAD

**Issue by AlphaCodeProgrammer** [syncfusion/flutter-examples#594]

**Comment by AlphaCodeProgrammer** [comment]
i can give you useful data for add Jalali date to syncfusion calendar you can use this package for convert Gregorian  [https://pub.dev/packages/shamsi_date](url) 
and this package for convert English numbers to Persian numbers [https://pub.dev/packages/shamsi_date](url)
and then make this calendar **AMAZING**!

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked and your requirement is “**Providing support for Jalali and hijri calendar in the Flutter event calendar (SfCalendar)**”. We have logged the feature request for the same. We will implement this feature in any of our upcoming releases.  

Thank you for requesting this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then. 

You can also communicate with us regarding the open features any time using our Feature Report page.  

**Feedback link:** https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar  

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count. 

Regards,
Indumathi R
