### ISSUE TITLE
Swiping between date while using loadMoreWidgetBuilder and in view mode day jumps day indication 

### ISSUE THREAD

**Issue by hechmi-dammak-fp** [syncfusion/flutter-examples#595]
while using the sfcalednar with loadMoreWidgetBuilder as a method to fetch data and show loading, 
if you swipe left and right in the day view mode, sometimes the date indicator shows the wrong date but the date when you press the date picker is the correct date .

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the shared information, we have checked issue “**Wrong date indication while swiping left  and right with loadMoreWidgetBuilder in the Flutter Calendar**” with loadMoreWidgetBuilder. We are getting the correct date details while swiping left and right, it was working fine as expected. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_loadmore-1502999533.zip

Tested scenarios:

•	Ensured with loadMoreWidgetBuilder by swiping left and right.
•	Ensured with loadMoreWidgetBuilder by swiping left and right and tapped the picker to ensure the date.

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with more details or if possible share the replication video from your side, it will be helpful for us to check on it and provide you solution at the earliest. 

Regards,
Indumathi R

**Comment by GunesYurdakul** [comment]
I have the same problem and I am using the latest version of the SFCalendar. It doesn't happen very frequently and happens more often in the debug mode. 
You can see it in the screen record as well. The date displayed is not the same with the calendar's controller display date. 
When I swipe just a little bit(not moving to another week), the display is back to normal. As you can see the date header changes as well.

https://user-images.githubusercontent.com/20091789/193081661-460b5e6b-07e8-47c2-80cb-d8ff5687cf53.mov
