### ISSUE TITLE
add the possibility to jump to specific date using the controller 

### ISSUE THREAD

**Issue by hechmi-dammak-fp** [syncfusion/flutter-examples#596]
I couldn't find a way to jump a specific date using the calendar (only using global keys of the appointment), which only works after render the of the calendar

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: add the possibility to jump to specific date using the controller**

Based on the shared information, we have checked and your requirement is “Jump to specific date using CalendarController in the Flutter Calendar”. By using [displayDate](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController/displayDate.html) property of the [CalendarController](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController-class.html) you can programmatically navigate to the specific date. We have a UG and KB documentation for the same. Please find the KB from the following link.

UG link: https://help.syncfusion.com/flutter/calendar/date-navigations#programmatic-date-navigation 

**KB link:** https://www.syncfusion.com/kb/12139/how-to-programmatically-navigate-to-the-date-in-the-flutter-event-calendar-sfcalendar 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
