### ISSUE TITLE
add the possibility to make indicator for empty days or months or weeks ... 

### ISSUE THREAD

**Issue by hechmi-dammak-fp** [syncfusion/flutter-examples#597]
I want the user to know if no appointments exist in that week or day or month without the need to scroll and look for it by just an indicator many as a floating panel at the top or something like that

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the shared information, we have checked and your requirement is “**Getting the empty date details without scroll in the Flutter Calendar**”. We have a KB documentation for getting the visible dates details with and without appointment details through the onPressed() callback of the RaisedButton. Please find the KB documentation from the following link.

**KB link:** https://www.syncfusion.com/kb/12477/how-to-get-the-current-month-appointments-in-the-flutter-calendar

We hope that this helps you. If possible, can you please share your requirement clearly with illustration image? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
