### ISSUE TITLE
How to change weekdays color in CalendarView.timeline Day

### ISSUE THREAD

**Issue by lukiinhas1616** [syncfusion/flutter-examples#600]
How to change weekdays color in CalendarView.timeline Day? Currently it is black, I want to change it to white.
I didn't find anything in the documentation about it.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: How to change weekdays color in CalendarView.timeline Day**

Based on the shared information, we have checked and we suspect your requirement is “Differentiate the weekdays and weekends of the view header in Flutter Calendar” and your requirement can be achieved by using the **viewHeaderStyle** property of the calendar. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_viewheaderstyle-1755214045.zip

Also please find the UG documentation for the same.

**UG link:** 
https://help.syncfusion.com/flutter/calendar/headers#view-header-appearance

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
