### ISSUE TITLE
[syncfusion_flutter_calendar] taking huge time to load 

### ISSUE THREAD

**Issue by Raviteja11122** [syncfusion/flutter-examples#601]
I have 12K(it can go up to 30-50k) agenda records it takes a huge time to load and sometimes the app is freezing.

**Comment by Indumathi1195R** [comment]
Hi,

In the Flutter Calendar, we have added the feature as loadmorewidget. Kindly use this feature for loading the huge amount of data in the calendar. When the calendar view changes the loading indicator will be displayed when it reaches the start or end position to load more appointments. handleLoadMore method in the CalendarDataSource is used to load the appointments on demand. We have a documentation for the sample. Please find the UG documentation for the same. 

**UG link:**
https://help.syncfusion.com/flutter/calendar/load-more

Also, we have a KB documentation for the same. Please find the documentation from the following link.

**KB link:**
https://www.syncfusion.com/kb/12658/how-to-load-appointments-on-demand-in-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
