### ISSUE TITLE
[Sf_Pdf] How to draw an Elements outside the Pages margin?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-examples#602]
I am trying to give my pages a heading, since my Content varies in height, I can't follow the documentation because it adds the pages beforehand. 

```dart
//Add the pages to the document. (not possible for me, I dont know the final pagecount)
for (int i = 1; i <= 5; i++) {. 
  document.pages.add().graphics.drawString(
      'page$i', PdfStandardFont(PdfFontFamily.timesRoman, 11),
      bounds: Rect.fromLTWH(250, 0, 615, 100));
}
```

because of that, I am getting the pagecount after the document has been layed out: 

```dart
    for (var i = 0; i < document.pages.count; i++) {
       final page = document.pages[i];

     //TODO: Add a heading here.
    }
```

However, since the document has been created with the default margins, I am unable to draw the heading to the page.

I tried to add the heading with a negative offset like so :

```dart
    for (var i = 0; i < document.pages.count; i++) {
      PdfTextElement(
              text: 'Heading 1',
              font: PdfStandardFont(PdfFontFamily.helvetica, 16,
                  style: PdfFontStyle.bold),
              brush: PdfSolidBrush(PdfColor(0, 0, 0)))
          .draw(
        page: document.pages[i],
        bounds: Rect.fromLTWH(0, -10, pageWidth, pageHeight), //Trying to place the heading 10 pixels above my content.
      );
    }
```

But the heading then gets cut off by the margin. 

How can I draw the PdfTextElement outside the margin bounds?

**Comment by irfanajaffer** [comment]
The Flutter PDF supports drawing the header and footer in PDF documents using [PdfPageTemplateElement](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPageTemplateElement-class.html) class.
To achieve your requirement, kindly use the following code sample in the link for reference,
https://help.syncfusion.com/flutter/pdf/working-with-headers-and-footers
 
Also, to remove the default margin on a new page, we set the margin as 0 in page settings. Kindly use the following link for reference, https://help.syncfusion.com/flutter/pdf/working-with-pages#adding-margin-to-the-pdf-pages
