### ISSUE TITLE
can't drag

### ISSUE THREAD

**Issue by IvanIIk137** [syncfusion/flutter-examples#604]
Hi,
on mobile platform daragndrop dont work^ on web give error
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
[file:///Users/ivan/development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.48/lib/src/calendar/views/calendar_view.dart:13355:10]()
../…/views/calendar_view.dart:13355
customObject != null
"Implement convertToCalendarAppointment method from CalendarDataSource"
When the exception was thrown, this was the stack:
dart-sdk[/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart]() 251:49         throw_
dart-sdk[/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart]() 29:3           assertFailed
packages[/syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart]() 13355:22  _getCalendarAppointmentToObject
packages[/syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart]() 857:42    [_handleAppointmentDragStart]
packages[/syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart]() 2380:7    [_handleDragStart]
packages[/syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart]() 707:37    <fn>
packages[/flutter/src/gestures/monodrag.dart]() 429:45                                   <fn>
packages[/flutter/src/gestures/recognizer.dart]() 198:24                                 invokeCallback
packages[/flutter/src/gestures/monodrag.dart]() 429:7                                    [_checkStart]
packages[/flutter/src/gestures/monodrag.dart]() 349:7                                    acceptGesture
packages[/flutter/src/gestures/arena.dart]() 264:11                                      [_resolveInFavorOf]
packages[/flutter/src/gestures/arena.dart]() 223:9                                       [_resolve]
packages[/flutter/src/gestures/arena.dart]() 53:12                                       resolve
packages[/flutter/src/gestures/recognizer.dart]() 306:12                                 resolve
packages[/flutter/src/gestures/monodrag.dart]() 317:47                                   handleEvent
packages[/flutter/src/gestures/pointer_router.dart]() 94:12                              [_dispatch]
packages[/flutter/src/gestures/pointer_router.dart]() 139:9                              <fn>
dart-sdk[/lib/_internal/js_dev_runtime/private/linked_hash_map.dart]() 21:13             forEach
packages[/flutter/src/gestures/pointer_router.dart]() 137:17                             [_dispatchEventToRoutes]
packages[/flutter/src/gestures/pointer_router.dart]() 123:7                              route
packages[/flutter/src/gestures/binding.dart]() 439:19                                    handleEvent
packages[/flutter/src/gestures/binding.dart]() 419:14                                    dispatchEvent
packages[/flutter/src/rendering/binding.dart]() 322:11                                   dispatchEvent
packages[/flutter/src/gestures/binding.dart]() 374:7                                     [_handlePointerEventImmediately]
packages[/flutter/src/gestures/binding.dart]() 338:5                                     handlePointerEvent
packages[/flutter/src/gestures/binding.dart]() 296:7                                     [_flushPointerEventQueue]
packages[/flutter/src/gestures/binding.dart]() 279:32                                    [_handlePointerDataPacket]
lib[/_engine/engine/platform_dispatcher.dart]() 1026:13                                  invoke1
lib[/_engine/engine/platform_dispatcher.dart]() 184:5                                    invokeOnPointerDataPacket
lib[/_engine/engine/pointer_binding.dart]() 130:39                                       [_onPointerData]
lib[/_engine/engine/pointer_binding.dart]() 533:16                                       <fn>
lib[/_engine/engine/pointer_binding.dart]() 496:21                                       <fn>
lib[/_engine/engine/pointer_binding.dart]() 210:16                                       loggedHandler
Handler: "onStart"
Recognizer:
  HorizontalDragGestureRecognizer#10c9a
════════════════════════════════════════════════════════════════════════════════════════════════════
129
Another exception was thrown: Assertion failed:

**Comment by osamagamal65** [comment]
The same issue happened to me.
