### ISSUE TITLE
how to expand collapse calender

### ISSUE THREAD

**Issue by qnysyn** [syncfusion/flutter-examples#605]

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked and your requirement is “**Provide support to expand and collapse the month view to a single week (SfCalendar)**”. We have logged the feature request for the same. We will implement this feature in any of our upcoming releases.  

Thank you for requesting this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then. 

You can also communicate with us regarding the open features any time using our Feature Report page.  

**Feedback link:** https://www.syncfusion.com/feedback/34551/provide-support-to-expand-and-collapse-the-month-view-to-a-single-week-sfcalendar 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count. 

Regards,
Indumathi R
