### ISSUE TITLE
[SfCalendar] - Festivity management

### ISSUE THREAD

**Issue by Verzu23** [syncfusion/flutter-examples#606]
Hi All,

I would ask if there's a way to automatically add festivity like Christmas and other festivity (of also other country).

Thanks a lot,

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar, we didn’t add the any festival events by default in the Flutter Calendar. We need to add the required event by manually with the required dates. We hope that this helps you. Please get in touch with us if would you required any further assistance.

Regards,
Indumathi R
