### ISSUE TITLE
How can I manipulate dates in multiple selection mode in SfDateRangePicker?

### ISSUE THREAD

**Issue by swtmply** [syncfusion/flutter-examples#608]
I saw that in the documentation the `selectedDates` only works with range selection, I want to ask if there is a way to select the selected dates and deselect dates using the date picker controller or any suggestion to work around it.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: How can I manipulate dates in multiple selection mode in SfDateRangePicker?**

In the Flutter DateRangePicker, by default it supports multiple selection with deselection operation.
We have a Sample browser sample for multiple selection with deselection operation. Please find the web sample link.

**Link:**
https://flutter.syncfusion.com/#/date-range-picker/getting-started

If possible can you please share your requirement details clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
