### ISSUE TITLE
How to limit the number of selection in date picker ?

### ISSUE THREAD

**Issue by SabarishChungath** [syncfusion/flutter-examples#609]
I want to limit the total number of selection to max 4 dates beyond 4 it shouldn't be selected .

**Comment by muthulakshmi-123** [comment]
Hi SabarishChungath,

Thank you for contacting Syncfusion support.

Based on provided information your requirement is “How to limit the number of selections in SfDateRangePicker”, As of now, there is no direct support to limit the number of selections. But you can achieve your requirement by adding a Selection changed callback, in which you can set the limit number of selected range by using the controller. We have prepared a simple sample for the same.

Kindly find the sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/limit-selection1444279577

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi
