### ISSUE TITLE
Disable drag to scroll on DataGrid

### ISSUE THREAD

**Issue by mattheuspirovani** [syncfusion/flutter-examples#611]
How to disable the drag to scroll behaviour on a datagrid (and keep the mouse wheel scroll)?

**Comment by mattheuspirovani** [comment]
![datagrid](https://user-images.githubusercontent.com/17201784/165408801-edb7cfe3-3a13-4144-a561-3a050c2a56fd.gif)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @mattheuspirovani,

Greetings from Syncfusion.

You can achieve your requirement by using the ScrollConfiguration widget. Wrap the DataGrid as a child of the ScrollConfiguration and set the behavior property. You need to set the ScrollConfiguration’s dragDevices property as PointerDeviceKind.unknown. We have prepared the sample for that. Please check the following sample and code snippet.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('PageNavigation Demo')),
        body: ScrollConfiguration(
            behavior: ScrollConfiguration.of(context)
                .copyWith(dragDevices: {PointerDeviceKind.unknown}),
            child: SfDataGrid(
                source: _employeeDataGridSource, columns: getColumns)));
  }

```

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1875841013 

We hope this helps. Please let us know if you need any further assistance.

Regards,
Tamilarasan

**Comment by mattheuspirovani** [comment]
Worked! Big Thanks!
