### ISSUE TITLE
Calendar Scrolling Animation Causing Crashing on IOS Devices

### ISSUE THREAD

**Issue by Tmarks2** [syncfusion/flutter-examples#613]
When using the calendar widget on IOS Devices by releasing the build:
flutter web build
the calendar will cause IOS device safari and chrome to crash. 
I found that building in: 
flutter build web --web-renderer canvaskit
Fixes the issue? 
Not sure why but would interesting to see if anyone else has similar problem. 
I do not believe that this a widget-specific issue, but posting here to bring awareness to anyone else running into issues.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have check and run the calendar sample using the 	flutter-build-web and there is no scrolling related crash from our end from calendar. It was working fine as expected iOS device and chrome. We have attached the link for the same. Please find the link from below.

**Link:**
flutter-app-cal.surge.sh 

If possible, can you please your issue details clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
