### ISSUE TITLE
Am i only can use 'EEE' and 'EEEE' to set the `dayFormat`, Can i use other language?

### ISSUE THREAD

**Issue by normidar** [syncfusion/flutter-examples#614]
Am I only can use 'EEE' and 'EEEE' to set the `dayFormat`, Can I use other languages?
if I can use other languages, please tell me how, if I can`t I hope you can develop it, thank you !

**Comment by muthulakshmi-123** [comment]
Hi Normidar,

Thank you for contacting Syncfusion support.

Based on provided information your requirement is **“How to set the day format in other languages”**, you can achieve your requirement by adding the localization. We have checked to set the day format in other languages. It is working fine as expected from our end. We have prepared a simple sample for the same. And kindly use the Syncfusion_localization package to localize the custom texts in the SfCalendar.

Kindly find the sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/day_format-1506543938

Please refer to the following UG link for more information.  
https://help.syncfusion.com/flutter/calendar/localization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi

**Comment by normidar** [comment]
yes, thank you very much I found I am used MaterialApp everywhere so the localization can`t deliveried to calendar, thanks!
