### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by Mimzeslami** [syncfusion/flutter-examples#615]
How can I use local notifications for set events in flutter?

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: How can I use local notifications for set events in flutter?**

Based on the shared information, we have checked and  your requirement is “**Providing remainder support for appointments in Flutter Calendar**” and there is no built in support for reminder in calendar. We have already logged the feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/26307/provide-reminder-support-for-appointments-in-the-flutter-calendar  

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
