### ISSUE TITLE
Unhandled Exception: FormatException: Invalid number (at character 1)

### ISSUE THREAD

**Issue by pavanZibtek** [syncfusion/flutter-examples#616]
I am getting this error only for some of the accounts, is there any solution for this bug? Please help me with this issue. Thank You.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi PavanZibtek,

Greetings from Syncfusion. We are not aware of which widget you are getting this exception. So, we request you to provide more information about which widget you have used in your sample and a code snippet to reproduce the exact issue. It will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by pavanZibtek** [comment]
I have sent you the email regarding this. please check and update us, please.

**Comment by pavanZibtek** [comment]
hi, is there any update on this ticket? please resolve this issue as soon as possible. I am stuck on this.

**Comment by LavanyaGowtham2021** [comment]
We have checked your query at our end and as we are not able to understand what your proposing as your requirement, we kindly request you to share us with more information on your requirement in detail along with screenshots/screenrecordings so that it will help us assist you in a better way.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
