### ISSUE TITLE
Flutter 3.0 update showing warning

### ISSUE THREAD

**Issue by adar2378** [syncfusion/flutter-examples#617]
pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_cale
ndar-20.1.55/lib/src/calendar/views/calendar_view.dart:6121:22: Warning: Operand of null-aware
operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../../../../flutter_1.17/flutter_17/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((_) {

**Comment by supratikkoley** [comment]
Same with me.

**Comment by vaidarbhicontractor** [comment]
Did anyone find solution ? I face below issue after upgrading Flutter with 3.0.0

`/C:/Users/Ouranos_PC_2/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.52/lib/src/calendar/sfcalendar.dart:4163:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/Users/Ouranos_PC_2/AppData/Local/Android/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.addPostFrameCallback((_) {`

**Comment by vaidarbhicontractor** [comment]
Update your `syncfusion_flutter_calendar` with latest version `^20.1.56` , with the help of this your run time warning will be gone.

**Comment by Indumathi1195R** [comment]
Hi,

Kindly update the Flutter to 3.0.0 version and syncfusion_flutter_calendar to 20.1.56 for resolving this issue. Please get in touch with us if would you require any further assistance.

Regards,
Indumathi R
