### ISSUE TITLE
 exception will be thrown while using zoom the trackball with multiple series.

### ISSUE THREAD

**Issue by superAndroidMan** [syncfusion/flutter-examples#618]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/26271318/168707847-ca96b1cd-ddc3-4afd-8069-75171a98c90c.png">

**Comment by superAndroidMan** [comment]
multiple series which the one have no data in screen,exception will be thrown

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @superAndroidMan,

We checked by zooming the chart with multiple series and having null values in one of the series and enabled the trackball. It is working fine without any exception. We suspect that you used the old version of the Flutter chart. So, we request you to upgrade the chart package to the latest version below and check. If the issue exists with the latest version, kindly try to replicate it with the sample attached below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.56

Sample: [i379648.zip](https://github.com/syncfusion/flutter-examples/files/8725482/i379648.zip)

Regards,
Yuvaraj.

**Comment by superAndroidMan** [comment]
I used LineSeries and BubbleSeries.but the LineSeries is continue data ,BubbleSeries only a few point.when i zooming,the screnn dont have BubbleSeriesPoint, trackball will be thrown exception

https://user-images.githubusercontent.com/26271318/169262053-c45ecbd4-d1d9-4a85-983c-50dc6160a6f7.mp4

like this video，when red point dismiss to screen and I long press to show trackball,will be thrown exception

**Comment by LavanyaGowtham2021** [comment]
We have done the some architectural changes in Charts widget and rolled out in our Volume 4 Main Release in 2023. Therefore, we kindly request you to upgrade the syncfusion_flutter_charts package to the latest version.

Version Link:
https://pub.dev/packages/syncfusion_flutter_charts/versions/24.2.5
 
If you are still facing issue in the latest version, kindly revert us with more details to proceed further on this.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need any other assistance on this.
