### ISSUE TITLE
Facing issue after upgrading Flutter

### ISSUE THREAD

**Issue by vaidarbhicontractor** [syncfusion/flutter-examples#620]
## How can I resolve this run time warning? It is very annoying

`/C:/Users/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.52/lib/src/calendar/sfcalendar.dart:4163:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/Users/Ouranos_PC_2/AppData/Local/Android/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.addPostFrameCallback((_) {`

**Comment by Indumathi1195R** [comment]
Hi ,

**Regarding Query: Warnings related to latest Flutter version**

We have removed the warnings in the Flutter calendar after upgrading the latest Flutter version. We have included the fix in our latest Weekly nuget package version 20.1.56. Kindly update to the latest version for resolving this warning. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.
  
Regards,
Indumathi R

**Comment by vaidarbhicontractor** [comment]
Hello , 
    Thank you for pay attention and quick response , and yes want to inform you that version `20.1.56` resolving runtime warning and works for me.
    Once again many thanks to you :)
