### ISSUE TITLE
how to monthFormat just month?

### ISSUE THREAD

**Issue by qkrtnfks128** [syncfusion/flutter-examples#623]
I want calendar that show title only month .
how can i do?

**Comment by muthulakshmi-123** [comment]
Hi 

Thank you for contacting Syncfusion support.

Based on provided information your requirement **“How to set the month format in SfCalendar”**, you can achieve your requirement by using [headerDateFormat](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/headerDateFormat.html). Header date format is used to customize the header in the flutter calendar.

Please refer to the following UG link for more information.  
https://help.syncfusion.com/flutter/calendar/headers#header-date-format

Code snippet:
```
@override
Widget build(BuildContext context) {
  return Container(
    child: SfCalendar(
      view: CalendarView.month,
      headerDateFormat: 'MMMM',
    ),
  );
}
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi
