### ISSUE TITLE
Pdf 2 data in a row problem

### ISSUE THREAD

**Issue by andersonbaldissarelli** [syncfusion/flutter-examples#624]
Hello,
i'm trying to use the PDF feature, but i'm didnt found in documentation how to show in a single row with two values in a table.
It's something like that:
![image](https://user-images.githubusercontent.com/51715198/169918412-715ef106-0818-47ee-a95a-78cc3e1c114d.png)

Thanks for help!

**Comment by GowthamrajKumar25** [comment]
Hi andersonbaldissarelli,

We can achieve your requirement by applying the border styles of particular cells of the PDF Grid. We have shared the sample code snippet with output document for your reference, please try the below code snippet and let us know the result.

Code snippet: 

`//Create a new PDF document
PdfDocument document = PdfDocument();
PdfPage pdfPage = document.pages.add();
//Create a PdfGrid class
PdfGrid grid = PdfGrid();
//Add the columns to the grid
grid.columns.add(count: 4);
//Add header to the grid
grid.headers.add(1);
//Add the rows to the grid
PdfGridRow header1 = grid.headers[0];
header1.cells[0].value = 'Test one';
header1.cells[0].columnSpan = 2;
header1.cells[2].value = 'Older person';
header1.cells[2].columnSpan = 2;
//Add rows to grid
PdfGridRow row1 = grid.rows.add();
row1.cells[0].value = 'result:';
row1.cells[1].value = 'X';
row1.cells[2].value = 'John';
row1.cells[3].value = '34 years';
var leftborders = PdfBorders(left: PdfPen(PdfColor(255, 255, 255), width: 0));
var rightborders = PdfBorders(right: PdfPen(PdfColor(255, 255, 255), width: 0));
row1.cells[0].style.borders = rightborders;
row1.cells[1].style.borders = leftborders;
row1.cells[2].style.borders = rightborders;
row1.cells[3].style.borders = leftborders;
grid.draw(page: pdfPage, bounds: const Rect.fromLTWH(0, 0, 0, 0));

//Save and dispose the PDF document
File('E://Flutter/381219/GridOutputcolor.pdf').writeAsBytes(document.save());
document.dispose();`


Output: https://www.syncfusion.com/downloads/support/directtrac/general/pd/GridOutputcolor510443255

Please refer to the below link for more information,
https://help.syncfusion.com/flutter/pdf/working-with-tables#cell-customization-in-pdfgrid

Please try the above solution and let us know the result.

Regards,
Gowthamraj K

**Comment by dalu547** [comment]
**_PdfPage pdfPage = document.pages.add();_** --> This will add new page in pdf document and table will add in that new page but 
i want to add table in existing page. I tried for this as "    **_final PdfPage page = document.pages[0];_**" but it throws an below error , 

E/flutter ( 9380): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value

Looking for an help regarding this scenarios
