### ISSUE TITLE
Syncfusion Calendar - Add padding in the header

### ISSUE THREAD

**Issue by rutaba1** [syncfusion/flutter-examples#626]
Hi, I want to add some padding around the date in the header because right now the it is truncating but I'm not sure how can I do that.

<img width="676" alt="Screenshot 2022-05-25 at 7 32 58 PM" src="https://user-images.githubusercontent.com/71274568/170287706-f6ebbccc-2433-40ff-8b30-916a8f350f67.png">

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the mentioned issue, we will include the issue fix in our upcoming weekly nuget package, which is expected to be rolled out by September 6, 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have included the issue fix for header text cropping while enabling the week number in the Flutter Calendar in our latest weekly nuget release package **version 20.2.48**.  Kindly update to the latest version for resolving the issue. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
