### ISSUE TITLE
Syncfusion Calendar - adjust content in day cells 

### ISSUE THREAD

**Issue by kanagiza** [syncfusion/flutter-examples#627]
![image](https://user-images.githubusercontent.com/70945722/170412967-cc52bd1b-0b02-4a79-a8fe-50eb1855f380.png)
I want to do like this, can you help me ?

**Comment by Indumathi1195R** [comment]
Hi,

By using the [monthCellbuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/monthCellBuilder.html) you can achieve this requirement. We have a UG and KB documentation for the same. Please find the documentations from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder

**KB links:**

https://www.syncfusion.com/kb/12306/how-to-customize-the-month-cell-with-appointment-count-in-the-flutter-calendar
https://www.syncfusion.com/kb/12210/how-to-customize-the-month-cell-based-on-the-appointment-using-builder-in-the-flutter

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
