### ISSUE TITLE
Gradient not supported on Radial Gauge v17.3.26-beta

### ISSUE THREAD

**Issue by simeon9696** [syncfusion/flutter-examples#63]
Following the example on [this page](https://help.syncfusion.com/flutter/radial-gauge/range-pointer). I get the following error on Android Studio.
`The named parameter 'gradient' isn't defined`
Is there a way to implement a gradient on the RangePointer? 

```
@override
Widget build(BuildContext context) {
   return Scaffold(
      body: Center(
        child: SfRadialGauge(
            axes:<RadialAxis>[RadialAxis( 
                axisLineStyle: AxisLineStyle(thickness: 0.1,
                  thicknessUnit: GaugeSizeUnit.factor,),
              pointers: <GaugePointer>[RangePointer(
                value: 40, width: 0.1, sizeUnit: GaugeSizeUnit.factor,
                gradient: const SweepGradient(  //error occurs here
                    colors: <Color>[Color(0xFFCC2B5E), Color(0xFF753A88)],
                    stops: <double>[0.25, 0.75]
                ),
              )]
            ),
          ]
        ),
      ),
    );
  }
```

**Comment by sheiksyedm** [comment]
Hi Simeon, 

We have provided the gradient support for pointer, range and axis from pub version [17.4.40-beta](https://pub.dev/packages/syncfusion_flutter_gauges). Please upgrade your radial gauge pub package version. 

Please check our v17.4.40 what's new items in this [link](https://www.syncfusion.com/products/whatsnew/flutter).

**Comment by simeon9696** [comment]
Upgrading to 17.4.40-beta has solved my issue. Thank you!
