### ISSUE TITLE
Is it possible to only show custom time?

### ISSUE THREAD

**Issue by keanallen** [syncfusion/flutter-examples#630]
Hey, this is a great package and we have been using this in our chat application. Im wondering if I can show only custom time? Like for example, I wanted my time to start at 6AM. By default time starts at 12:30AM.

This would be a great feature.

![image](https://user-images.githubusercontent.com/45480782/170610977-5790579d-977a-4ad8-b544-82daa5653b9e.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is it possible to only show custom time?**

Yes, it is possible to show the required time by using the **startHour** and **endHour** properties of the **timeSlotViewSettings**. We have a UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/timeslot-views#flexible-working-days-and-working-hours

**Code snippet:**

```
child: SfCalendar(
  view: CalendarView.day,
  dataSource: _getCalendarDataSource(),
  todayHighlightColor: Colors.green,
  timeSlotViewSettings: const TimeSlotViewSettings(
      startHour: 6,
      endHour: 18,
      timeInterval: Duration(minutes: 30),
      timeFormat: "h:mm a"),
),
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by keanallen** [comment]
OMG. Thank you! My bad again!
