### ISSUE TITLE
syncfusion_flutter_calendar: ^20.1.58 Build Failed

### ISSUE THREAD

**Issue by Nehal1367** [syncfusion/flutter-examples#634]
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:2867:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:4157:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:4176:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) {
                                    ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:4322:33: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
      SchedulerBinding.instance.addPostFrameCallback((Duration timeStamp) {
                                ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:4618:33: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
      SchedulerBinding.instance.addPostFrameCallback((Duration timeStamp) {
                                ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:4636:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/sfcalendar.dart:8224:23: Error: No named parameter with the name 'thumbVisibility'.
                      thumbVisibility: showScrollbar,
                      ^^^^^^^^^^^^^^^
/D:/Software/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:3293:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:3632:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:3640:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:3789:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:3871:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:6010:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:6107:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:8151:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:8434:15: Error: No named parameter with the name 'thumbVisibility'.
              thumbVisibility: !widget.isMobilePlatform,
              ^^^^^^^^^^^^^^^
/D:/Software/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:8625:29: Error: No named parameter with the name 'thumbVisibility'.
                            thumbVisibility: !widget.isMobilePlatform,
                            ^^^^^^^^^^^^^^^
/D:/Software/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.1.58/lib/src/calendar/views/calendar_view.dart:8613:13: Error: No named parameter with the name 'thumbVisibility'.
            thumbVisibility: !widget.isMobilePlatform,
            ^^^^^^^^^^^^^^^
/D:/Software/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.58/lib/src/date_picker/date_picker.dart:8059:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Software/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.58/lib/src/date_picker/date_picker.dart:9826:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/Software/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked the mentioned issue “Error occurred while using the addPostFrameCallback in the Flutter Calendar”. We have checked the mentioned issue in 20.1.58 version and we are unable to reproduce the mentioned issue from our end.  Also, can you please confirm if you are using the latest flutter version? Otherwise, kindly update to the latest flutter version and check still if you are facing same issue. 

Regards,
Indumathi R

**Comment by bobwiller** [comment]
@Indumathi1195R confirming this error with flutter 3.0.1 and 3.0.2 and syncfusion_flutter_datepicker: ^20.1.60 on Android:

/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.60/lib/src/date_picker/date_picker.dart:8059:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/Users/xxx/fvm/versions/2.10.3/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.60/lib/src/date_picker/date_picker.dart:9826:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/Users/xxx/fvm/versions/2.10.3/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

**Comment by Indumathi1195R** [comment]
Hi,

We have checked with the mentioned error with flutter 3.0.5 and syncfusion_flutter_datepicker: ^20.1.60. We are unable to reproduce the any error from our end. Can you please check with the latest version once and let us know still if you are facing issue? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by daradonn** [comment]
Flutter: 2.8.1
  syncfusion_flutter_calendar: 20.1.47
  syncfusion_flutter_datepicker: 20.1.47
worked for me
