### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by jimmymchau** [syncfusion/flutter-examples#638]
This is happenning when calling reset pad

This is my code

`final GlobalKey<SfSignaturePadState> signatureGlobalKey = GlobalKey();
  void _handleClearButtonPressed() {
    signatureGlobalKey.currentState!.clear();
  }`

`Container(
  child: MaterialButton(
      onPressed: () async {
        _handleClearButtonPressed();
      },
    child: Text('Reset signature',
      style: TextStyle(color: Colors.black87, fontSize: 13.0,),
      textAlign: TextAlign.center,
    ),
  ),
),`

This is the error:

`E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (23721): #0      _SignatureCapturingState._handleClearButtonPressed (package:nbcapp/dashboard/signature_capturing.dart:15:36) //this line is the line of signatureGlobalKey.currentState!.clear();
E/flutter (23721): #1      _SignatureCapturingState.build.<anonymous closure> (package:nbcapp/dashboard/signature_capturing.dart:139:43)
E/flutter (23721): #2      _SignatureCapturingState.build.<anonymous closure> (package:nbcapp/dashboard/signature_capturing.dart:138:52)
E/flutter (23721): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (23721): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (23721): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter (23721): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (23721): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
E/flutter (23721): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (23721): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
E/flutter (23721): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (23721): #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
E/flutter (23721): #12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (23721): #13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (23721): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (23721): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (23721): #16     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (23721): #17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (23721): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (23721): #19     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (23721): #20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (23721): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter (23721): `

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jimmymchau,

Greetings from Syncfusion. We are not aware of which widget and what are properties used in your sample. So, can you please mention the widget type and properties used in the application, and if possible, please provide a sample code to reproduce the issue. That will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by claudiotapiac** [comment]
Could you solve it? Because I have the same problem as you.
