### ISSUE TITLE
Update calendar data and remove calendar data

### ISSUE THREAD

**Issue by yenyichau** [syncfusion/flutter-examples#640]
How can we update and remove data from the load more widget?  Thanks

**Comment by Indumathi1195R** [comment]
Hi,

By using the loadMoreWidgetBuilder you can update the appointments on-demand, when the loading indicator is displaying in the calendar by using the handleLoadMore method in the CalendarDataSource which allows adding the appointments to the data source, update the data source, and notify the listener to update the appointment on view. We have a UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/load-more

Also, we have a KB documentation for the same. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12658/how-to-load-appointments-on-demand-in-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
