### ISSUE TITLE
Calendar: How to change style of selected date text?

### ISSUE THREAD

**Issue by BrianDevOK** [syncfusion/flutter-examples#641]
I can change the selected date container, but I can’t figure out how to change the text of the selected date. For example if I click the 14th on the calendar (month view), I want to change the color of the text of the 14.  If possible, how?  If not possible please add. 

Thanks

**Comment by Indumathi1195R** [comment]
Hi ,

Based on the shared information, we have checked and your requirement is “**Changing the selected date text color in the Flutter Calendar**” and there is no direct support to achieve your requirement. But your requirement can be achieved by sample level by using **monthCellbuilder**. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/selecteddatetextcolor-1350461570.zip

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
