### ISSUE TITLE
Hide Today-Button in SFCalender

### ISSUE THREAD

**Issue by DieGlueckswurst** [syncfusion/flutter-examples#642]
Is there a way to **hide** the Today-Button in the `SFCalender`?

![Bildschirmfoto 2022-06-24 um 19 14 27](https://user-images.githubusercontent.com/40027124/175611513-cd7ca522-5ae3-4d0b-817a-380512f6f1f2.png)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query:  Is there a way to hide the Today-Button in the SfCalendar?**

We have already considered your requirement as a feature “Provide support to hide and show the Today icon button in the Flutter Calendar (SfCalendar)” and logged feature request for the same. We will implement this feature in any of our upcoming releases. 
 
At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
 
Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/34053/provide-support-to-hide-and-show-the-today-icon-button-in-the-flutter-calendar 
   
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.
 
Regards,
Indumathi R
