### ISSUE TITLE
Syncfusion Calendar - scroll calendar sometimes getting empty events

### ISSUE THREAD

**Issue by yenyichau** [syncfusion/flutter-examples#645]
Problem:
- When trying to scroll the calendar to change the month sometimes it return empty events until i press anywhere inside the calendar view and then the events appear again.

Screenshots:
1. Before scrolling (June 2022)
![1656557556043](https://user-images.githubusercontent.com/59037547/176583252-11c502c0-707a-45fe-9a76-5b98a077a550.JPEG)

2. After scrolling from June 2022 to July 2022 and then back to June 2022 again (June > July > June) the events disappear. 
![1656557556035](https://user-images.githubusercontent.com/59037547/176584421-6a509c6a-3c33-490c-b804-1ff08f161c8e.JPEG)

3. After i pressed the events appear again. I press 18th June 2022 but it is actually pressed 18th May 2022.
![1656557556043](https://user-images.githubusercontent.com/59037547/176583252-11c502c0-707a-45fe-9a76-5b98a077a550.JPEG)

4. When i scroll to May 2022 the calendar view show what i pressed previously which is 18th May 2022. (June > May)
![1656557556027](https://user-images.githubusercontent.com/59037547/176584938-c52c5c3c-42cf-4ba3-bd16-32e2728634eb.JPEG)

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query:  Scroll calendar sometimes getting empty events**	

Based on the shared information, we have checked the mentioned issue “**Scroll calendar sometimes getting empty events in the Flutter Calendar**” and we are unable to reproduce the mentioned issue from our end.  If possible, please share more details about your issue clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by ppprakhar** [comment]
Hi,

I am also facing this issue you can check [https://drive.google.com/file/d/1JURDL8GbrweHr_bF-zu3Q_Y4RNxpAo7P/view](https://drive.google.com/file/d/1JURDL8GbrweHr_bF-zu3Q_Y4RNxpAo7P/view) here 

We using latest Flutter version but this issue come since 3.0.0

**Comment by MuniappanSubramanian** [comment]
According to the instructions provided, we followed the steps to check the reported issue but were unable to replicate it on our end. We have prepared a sample, which is attached for your reference.

Please note that the version of **SfCalendar** used for this test is **21.1.41.**

Please check our sample and let us know if you are still facing the same issue. If the issue persists, please provide us with the following details:

•	A video demonstrating the issue you are facing.
•	The code snippets for your calendar implementation.
•	A reproducible sample that demonstrates the issue.

Providing these details would be helpful for us to investigate the issue and provide you with a solution as soon as possible.
[sample.zip](https://github.com/syncfusion/flutter-examples/files/11310736/sample.zip)
[output.zip](https://github.com/syncfusion/flutter-examples/files/11310740/output.zip)
