### ISSUE TITLE
Bug appeared in new released version in sliders/range selector/zooming

### ISSUE THREAD

**Issue by benjamingaudin** [syncfusion/flutter-examples#648]
sliders/range selector/zooming

Hi,

A bug appeared in the new released version.

When modifying the visibility of a line which is zoomed, the new version zooms out and shows the whole series, instead of the selected portion. This was not the case in the previous version.

Below is the example from your samples.

20.2.36 (bug)

https://user-images.githubusercontent.com/57812158/177039992-0ef12285-fefe-4cc6-b121-1f29853042a7.mp4

20.1.47 (no bug)

https://user-images.githubusercontent.com/57812158/177039994-af9736df-9b8f-4f97-aa6e-806cc61a2cb2.mp4

**Comment by benjamingaudin** [comment]
Hi, it is not resolved in 20.2.46; the bug was not present in earlier versions. How can I help here, do you want more details?

**Comment by LokeshPalani** [comment]
Hi @benjamingaudin,

The reported issue has already been fixed and rolled out in our **Volume 4 Main Release** in 2023. Therefore, we kindly request you to upgrade the s**yncfusion_flutter_charts package** to the latest version.

**Version Link:**
https://pub.dev/packages/syncfusion_flutter_charts

Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need any other assistance on this.
