### ISSUE TITLE
moving label text completely left  in y axis rectangular box

### ISSUE THREAD

**Issue by gopibathini** [syncfusion/flutter-examples#650]
i want add space between y axis labels and axis and labels need to move complete left , iam using categoryaxis but no option related to that
![graph](https://user-images.githubusercontent.com/89006280/178433529-fcb29d9c-4cb3-4125-bca7-b6017a380106.PNG)

**Comment by gopibathini** [comment]
@Yuvaraj-Gajaraj  y axis labels are strings not able to use numeric and tried using major ticklines not moving completely left

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @gopibathini,

Currently, we don't have any padding property to move the axis label completely left, we have logged the feature request to replace the axis label with the custom widget. Using this you can be able to add padding to the axis label and move it as per your requirement, it will be available in any of our upcoming releases. We have attached the feedback link below, you can track the status of the feature here.

Feedback: https://www.syncfusion.com/feedback/23096

Regards,
Yuvaraj.
