### ISSUE TITLE
SignaturePad : Inside Bottomsheet dialog scrolling issue

### ISSUE THREAD

**Issue by vishalpatel1327** [syncfusion/flutter-examples#651]
First of all thanks to creating such a great package.

When I am using the Signature pad in bottom sheet having issue to draw sign. check video

https://user-images.githubusercontent.com/14329287/178502215-6ac7c242-1f94-498d-be10-e08a831190a5.mp4

**Comment by vishalpatel1327** [comment]
> showModalBottomSheet(
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(
            top: Radius.circular(20),
          ),
        ),
        context: context,
        builder: (context) => SignatureDialog());
  }

**Comment by vishalpatel1327** [comment]
`
class SignatureDialog extends StatefulWidget {
  const SignatureDialog({Key? key}) : super(key: key);

  @override
  State<SignatureDialog> createState() => _SignatureDialogState();
}

class _SignatureDialogState extends State<SignatureDialog> {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(16),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            "Digital Signature",
            style: TextStyle(
                fontSize: 16, fontWeight: FontWeight.bold, color: primaryColor),
          ),
          const Text(
            "This signature will be displayed on sales invoices.",
            style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w500,
                color: Colors.black54),
          ),
          const SizedBox(
            height: 8,
          ),
          Container(
            decoration: BoxDecoration(
                border: Border.all(color: Colors.black),
                borderRadius: BorderRadius.all(Radius.circular(4))),
            width: MediaQuery.of(context).size.width,
            height: 150,
            child: const SfSignaturePad(
              minimumStrokeWidth: 3,
              maximumStrokeWidth: 6,
              strokeColor: Colors.black,
            ),
          ),
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                    icon: const Icon(
                      Icons.refresh,
                      size: 14,
                    ),
                    onPressed: () {
                      Navigator.of(context).pop();
                      // Validate returns true if the form is valid, or false otherwise.
                    },
                    label: const Text("Reset")),
              ),
              const SizedBox(
                width: 16,
              ),
              Expanded(
                child: ElevatedButton.icon(
                    icon: const Icon(
                      Icons.search_rounded,
                      size: 14,
                    ),
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                    label: const Text("Search")),
              ),
            ],
          )
        ],
      ),
    );
  }
}`

**Comment by beamAkshay** [comment]
getting same problem please tell if you resolved this issue

**Comment by vishalpatel1327** [comment]
@davsyncfusion  can you guys look into it?

**Comment by Policy56** [comment]
I have the same scrolling problem in PageView and ListView ..

**Comment by LavanyaGowtham2021** [comment]
We have resolved the issue already, so we kindly request you to upgrade the latest version.

https://pub.dev/packages/syncfusion_flutter_signaturepad/versions/24.2.5

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need any other assistance on this.
