### ISSUE TITLE
SfCartesianChart Switching the data source when scrolling horizontally will affect the X-axis gap to become larger

### ISSUE THREAD

**Issue by codertiany** [syncfusion/flutter-examples#658]
SfCartesianChart Switching the data source when scrolling horizontally will affect the X-axis gap to become larger
SfCartesianChart 进行水平滚动时切换数据源,会影响X轴间隙变大

https://user-images.githubusercontent.com/11660271/181686360-d59be915-7785-44d3-a2a6-98f1ce67d388.MP4

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @codertiany,

We have validated the reported issue and found that your data points contain some empty values, which causes the gap between the column segments. We took the following image from your video clip, in which the red-colored column series segment point at 6/27 is empty. Please let us know if you need any further assistance in this.

Screenshot:
![rte_image_118](https://user-images.githubusercontent.com/61863686/182192238-437a292c-7bcf-40a5-915e-314e2e111208.png)

Regards,
Yuvaraj.

**Comment by codertiany** [comment]
你好,有空值是正确的需求,现在的问题是月的数据进行了滚动后,再切换到周时,周的X轴数据展示不全.

**Comment by LokeshPalani** [comment]
Hi @codertiany,

We have checked the reported issue and tried to replicate it by changing the axis visible range using [initialVisibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/initialVisibleMinimum.html) and [initialVisibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/initialVisibleMaximum.html) in both the old and new versions of the **syncfusion_flutter_charts** package. However, we were unable to reproduce it on our end. Please check the attached sample, and if you are still experiencing the issue, we kindly request that you replicate it in the attached sample and provide us with more details regarding the specific scenario in which you are encountering this issue. This will enable us to assist you more effectively.

We have checked with below mentioned version:

Old syncfusion_flutter_charts version – 20.2.40
New syncfusion_flutter_charts version – 24.2.6
Flutter SDK version - 3.16.9
Dart version - 3.2.6


Regards,
Lokesh P.

[github_658.zip](https://github.com/syncfusion/flutter-examples/files/14312106/github_658.zip)
[github_658_new_chartversion.zip](https://github.com/syncfusion/flutter-examples/files/14312107/github_658_new_chartversion.zip)

**Comment by codertiany** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by codertiany** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
