### ISSUE TITLE
SfDatepicker | How to remove header angle?

### ISSUE THREAD

**Issue by ziqq** [syncfusion/flutter-examples#659]
### How to remove header angle?

<img src="https://user-images.githubusercontent.com/20646071/182318410-dfa9090b-f544-48a9-a9be-ce401508b146.png" data-canonical-src="https://user-images.githubusercontent.com/20646071/182318410-dfa9090b-f544-48a9-a9be-ce401508b146.png" width="350" />

**Comment by MuniappanSubramanian** [comment]
Hi ziqq, 

**# Regarding SfDatepicker | How to remove header angle?**
As per the instruction we have followed to check the reported issue and we are unable to replicate the issue from our end. We tested the scenario of using the multi-date picker view with vertical navigation and localization. We have prepared the simple sample please find the attached sample for the same. 

**Additional information**
SfDateRangePicker version: **20.2.0.40**

Please check our sample and let us know if you still facing the same issue. if not, please modify our sample and revert us back with the following details which would be helpful for us to check on it and provide you the solution as soon as possible,

- Share the issue reproducible sample
- Share date range picker code snippets
- Share SfDateRangePicker version

[daterangepicker.zip](https://github.com/syncfusion/flutter-examples/files/9258174/daterangepicker.zip)

Regards, 
Muniappan S

**Comment by ziqq** [comment]
Yes fine, in new version this bug fixed.
