### ISSUE TITLE
SfCartesianChart | Critical issue with onTrackballPositionChanging

### ISSUE THREAD

**Issue by Jamesmallon1** [syncfusion/flutter-examples#660]
Hi there,

We use trackball within our charts but also use `onTrackballPositionChanging` to relay the current plot on the graph to the parent view to display the values of the chart as headers. On using `setState` or `notifyListeners` (from provider) within this method (`onTrackballPositionChanging`) the trackball line disappears and never appears again despite the values being relayed correctly.

I have tried to use select from provider to only listen to specific changes but the trackball still disappears. Additionally I am building the chart as part of a separate class but despite trying a huge amount as long as `setState` or `notifyListeners` is called in any parent widget whilst the trackball is displayed it will disappear.

This is obviously less than ideal, is there another solution or a workaround for now?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Jamesmallon1,

We would like to let you know that the behavior of trackball [activationMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/activationMode.html) is that it defines when the trackball comes to visibility, so if you rebuild the widget, it will not remain visible. We request that you share more details about your requirements. Based on your confirmation, we will try other possibilities to achieve your requirement.

Regards,
Yuvaraj.
