### ISSUE TITLE
[syncfusion_flutter_datepicker] SfDateRangePicker Widget onSubmit Parameter Bug

### ISSUE THREAD

**Issue by doch2** [syncfusion/flutter-examples#664]
An attempt was made to use the SfDateRangePickerWidget in the syncfusion_flutter_datepicker library, but an error occurred while entering the code.

An error occurs when using the onSubmit Parameter, and the code below is the code I wrote in the application.
```dart
SfDateRangePicker(
    onSelectionChanged: controller.onSelectionChanged,
    selectionMode: DateRangePickerSelectionMode.range,
    showActionButtons: true,
    confirmText: "Choice",
    cancelText: "Cancel",
    onCancel: () => Get.back(),
    onSubmit: (Object value) {
        print(value);
    },
),
```

The phrase below is an error.
`The argument type 'Null Function(Object)' can't be assigned to the parameter type 'dynamic Function(Object?)?'.`

**Comment by MuniappanSubramanian** [comment]
Hi doch2, 

**Regarding SfDateRangePicker Widget onSubmit Parameter Bug** 

As per the given code snippets we have followed to check the reported issue and we suspect that it is a sample level issue, now it is working fine. By adding the null check in the OnSubmit object parameter you can overcome this issue and an OnSubmit argument type is a non-nullable object. We have prepared a simple sample for the same, please find the attached sample below, 

**Code snippets**
`child: SfDateRangePicker(
controller: _controller,
onSelectionChanged: selectionChanged,
view: DateRangePickerView.month,
selectionMode: DateRangePickerSelectionMode.range,
showActionButtons: true,
cancelText: 'Cancel',
confirmText: 'Choice',
onCancel: ()
  {
    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
      content: Text(
        'Selection Cancelled',
      ),
      duration: Duration(milliseconds: 500),
    ));
},
  onSubmit: (Object ? value) {
    print(value);
},
),`

We hope that this helps you. Please let us know if you need further assistance. 

Regards, 
Muniappan S
[daterange_picker_onsubmit.zip](https://github.com/syncfusion/flutter-examples/files/9349130/daterange_picker_onsubmit.zip)

**Comment by doch2** [comment]
There was no related information in the API Reference, so I couldn't check it and registered it as an issue!
 ㄴ API Reference URL: https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/onSubmit.html

I would appreciate it if you could reflect the comments on this issue in the API reference as well. :)
Thank you for your kind explanation!
