### ISSUE TITLE
Disable mouse drag in syncfusion_flutter_calendar 

### ISSUE THREAD

**Issue by rawquesh** [syncfusion/flutter-examples#667]
Hello there,
I just updated to latest version of syncfusion_flutter_calenda  and now how can I disable Horizontal scroll with mouse drag, and enable it with mouse wheel scroll
(old version was working fine)

**Comment by MuniappanSubramanian** [comment]
Hi Rawquesh, 

**#Regarding Disable mouse drag in syncfusion_flutter_calendar** 
Currently, we are analyzing the mentioned issue in Flutter Calendar. We will validate and update you on the further details on or before (August 30th, 2022). We appreciate your patience until then. 

Regards,
Muniappan S.

**Comment by MuniappanSubramanian** [comment]
Hi Rawquesh,

**#Regarding Disable mouse drag in syncfusion_flutter_calendar**
We have fixed the reported issue, and it will be included in our upcoming weekly NuGet release, which is expected to roll out on September 06th, 2022. We appreciate your patience until then.

Regards,
Muniappan S.

**Comment by LavanyaGowtham2021** [comment]
We have resolved the issue already, so we kindly request you to upgrade the latest version.
