### ISSUE TITLE
how to change order of days in week? 

### ISSUE THREAD

**Issue by nashihu** [syncfusion/flutter-examples#668]
Hello, i would like to change order days of week from SMTWTFS to MTWTFSS

*change first week from sunday to monday

<img width="350" alt="image" src="https://user-images.githubusercontent.com/35857544/187377094-a4d77611-242d-42b1-8a41-166a54f16dc6.png">

how do i do that? thank you

**Comment by MuniappanSubramanian** [comment]
Hi nashihu,

**#Regarding how to change order of days in week?**
You can achieve your requirement by setting the “**firstDayOfWeek**” in the Flutter calendar. Please refer the below code snippets,

![image](https://user-images.githubusercontent.com/46158936/187874477-182c930f-4c5a-493e-8185-aa2b88c46c1c.png)


Please refer to our UG document to know how to set FirstDayOfWeek in the Flutter Calendar,
https://help.syncfusion.com/flutter/calendar/getting-started#change-first-day-of-week

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muniappan S
