### ISSUE TITLE
(minor) europe.json does not contain Norway

### ISSUE THREAD

**Issue by MarcVanDaele90** [syncfusion/flutter-examples#670]
I understand that you are not a map provider 
but the assets/europe.json does not contain Norway 
which makes the map look weird

**Comment by SriramKiranSenthilkumar** [comment]
Hi @MarcVanDaele90,

Greetings from Syncfusion. 
We will look into this issue and will correct the europe.json file in our sample browser repository.

Regards,
Sriram Kiran
