### ISSUE TITLE
How do I merge appointments?

### ISSUE THREAD

**Issue by Andromeda606** [syncfusion/flutter-examples#672]
<img width="354" alt="Ekran Resmi 2022-09-11 23 41 28" src="https://user-images.githubusercontent.com/43077625/189548048-2c4c4a47-929b-4aca-8f64-1469cb300d20.png">
I have added a data using scheduler, but I cannot combine this data when the days are apart. What I want is to merge instead of typing "Day 1/2".

I tried this, but the problem occurs because of margin. What's the solution?
<img width="357" alt="Ekran Resmi 2022-09-11 23 40 40" src="https://user-images.githubusercontent.com/43077625/189548025-ab90b703-a763-4b33-9863-ae719b7a2482.png">

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the shared information, we have checked the issue with “**appointmentbuilder with margin value in the SchdeuleView of the Flutter Event Calendar**” and we are unable to reproduce the any issue from our end. We have attached the tested sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_appschedule-1239876818.zip 

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with more details, it will be helpful for us to check on it and provide you solution at the earliest.

Regards,
Indumathi R

**Comment by Andromeda606** [comment]
what i want is not like in your example. I don't want to add margin, I want to remove margin. I want to combine 2 different days.
<img width="357" alt="189548025-ab90b703-a763-4b33-9863-ae719b7a2482" src="https://user-images.githubusercontent.com/43077625/189626481-9a1454ab-f11d-4652-ba25-727e8928da2b.png">
I want to do something like this
