### ISSUE TITLE
how can i change color of every  range in multi renge Calender?

### ISSUE THREAD

**Issue by mostafamoh176** [syncfusion/flutter-examples#673]
i want to change color of every single range 
![Screenshot 2022-09-12 133855](https://user-images.githubusercontent.com/69174950/189937296-2c263573-edd2-4ce8-a7bb-9d61a233e9c8.png)

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked and your requirement is “**Use the multiple colors for ranges in multi range selection of the Flutter DateRangePicker**”. As per the current implementation there is no direct for this requirement and your requirement can be achieved by sample level using the [cellBuilder](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/cellBuilder.html) property of the DateRangePicker. We have a KB documentation for the same. Please find the KB documentation from the following link.

**KB link:**
https://www.syncfusion.com/kb/12860/how-to-use-multi-colors-for-multi-range-selection-in-the-flutter-date-range-picker

Also, we have a UG documentation for **cellBuilder**. Please find the UG documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
