### ISSUE TITLE
Decade & Century View Suggestion

### ISSUE THREAD

**Issue by didifend** [syncfusion/flutter-examples#675]
Thank you for this very powerful plugin. I just want to give a suggestion (191170616-6caf09cd-f7f1-47e8-88af-33e527f69901.jpeg & 191170619-9f162ebb-47ff-4432-bad0-4948e7f75b3e.jpeg) to the developer.

I think the Yearly View (Decade & Century) should be improved or modified to display the appropriate header and lists. Switching decades or centuries can be through just a swipe of the view.

Currently, to get the look I expect, I modified the code in my local file (picker_helper.dart) like this,

```
static List getVisibleYearDates(dynamic date, DateRangePickerView view, bool isHijri) {
....
      case DateRangePickerView.decade:
        {
          final int year = ((date.year as int) ~/ 10) * 10;

          for (int i = 0; i < 10; i++) {
            currentDate = getDate(year + i, 1, 1, isHijri);
            datesCollection.add(currentDate);
          }
        }
        break;
      case DateRangePickerView.century:
        {
          final int year = ((date.year as int) ~/ 100) * 100;
          for (int i = 0; i < 10; i++) {
            currentDate = getDate(year + (i * 10), 1, 1, isHijri);

            datesCollection.add(currentDate);
          }
        }
....
}
```

I hope the developer provided an options parameter to show 12 lists or 10 lists. Correct Me if I'm Wrong. Thank u.

![Syncfusion Date (Not Match View)](https://user-images.githubusercontent.com/39362311/191170609-350a7808-4239-487c-9193-197b3b694be6.png)
![Syncfusion Date Suggest View 1](https://user-images.githubusercontent.com/39362311/191170616-6caf09cd-f7f1-47e8-88af-33e527f69901.jpeg)
![Syncfusion Date Suggest View 2](https://user-images.githubusercontent.com/39362311/191170619-9f162ebb-47ff-4432-bad0-4948e7f75b3e.jpeg)

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: I think the Yearly View (Decade & Century) should be improved or modified to display the appropriate header and lists. Switching decades or centuries can be through just a swipe of the view.**

SfDateRangePicker header depends on the current view dates or years. Other dates and years in the views are leading or next views dates/years.

Also, we have logged the feature request for “**Provide a support for Hide and show the next view cells in the decade and century views of the SfDateRangePicker**”. We will prioritize the features of every release based on the demands and we do not have an immediate plan to implement this feature and we will implement this feature in any of our upcoming releases.

Now you can track the status of the feature report by using the following link.

**Feature link:**
https://www.syncfusion.com/feedback/37883/provide-a-support-for-hide-and-show-the-next-view-cells-in-the-decade-and-century

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.


We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by didifend** [comment]
> Hi Team,
> 
> **Regarding Query: I think the Yearly View (Decade & Century) should be improved or modified to display the appropriate header and lists. Switching decades or centuries can be through just a swipe of the view.**
> 
> SfDateRangePicker header depends on the current view dates or years. Other dates and years in the views are leading or next views dates/years.
> 
> Also, we have logged the feature request for “**Provide a support for Hide and show the next view cells in the decade and century views of the SfDateRangePicker**”. We will prioritize the features of every release based on the demands and we do not have an immediate plan to implement this feature and we will implement this feature in any of our upcoming releases.
> 
> Now you can track the status of the feature report by using the following link.
> 
> **Feature link:** https://www.syncfusion.com/feedback/37883/provide-a-support-for-hide-and-show-the-next-view-cells-in-the-decade-and-century
> 
> At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.
> 
> We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
> 
> If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.
> 
> Regards, Indumathi R

Thank u Syncfusion Team for your response. 😊🙏🏻
