### ISSUE TITLE
Is there a way to drag and drop in month view in syncfusion_flutter_calendar?

### ISSUE THREAD

**Issue by maulik-benzatine** [syncfusion/flutter-examples#676]

**Comment by zeeshan112233** [comment]
@maulik-benzatine did you find a way ?

**Comment by MuniappanSubramanian** [comment]
@maulik-benzatine 

The current implementation of the Flutter Calendar does not have support for drag and drop appointments in month view on mobile platforms. You can find more details from below UG documentation,

https://help.syncfusion.com/flutter/calendar/drag-drop#allow-drag-and-drop
