### ISSUE TITLE
timezone dependency has a new version now

### ISSUE THREAD

**Issue by hurkanugur** [syncfusion/flutter-examples#677]
Please update the timezone 0.8.0 dependency to timezone 0.9.0

**Comment by Indumathi1195R** [comment]
H,

We have included the version updation of the “**timezone dependency package into 0.9.0 version in the Flutter Calendar**” in our latest Weekly nuget version 20.3.48. Kindly update to the latest version for using Flutter Calendar with latest timezone package. Please find the latest version from the following pub documentation link.

**Pub documentation link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
