### ISSUE TITLE
[SfCalendar] [Resources View] [Time Format] Custom time format builder

### ISSUE THREAD

**Issue by dongnqda** [syncfusion/flutter-examples#679]
Hi guys, thanks for this awesome package. 

Currently, i'm trying to customize the time textFormat but i can't find a way to do that ?  

What i want is to show period with index (Each period is 30 mins)
Ex : Period 1 (8h15 AM - 8h45AM) | Period 2 (8h45 AM - 9h15 AM),........

And having a startTime - endTime below each one of it.

EX : 
Period 1                                |       Period 2
(8h15 AM - 8h45 AM)         |       (8h45 AM - 9h15 AM)      .....

Really appreciate any help. Thanks.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/113326771/192450026-870e9ae4-843d-4a6d-a642-ed1fe6d06cd4.png">

**Comment by Sasikumar3595** [comment]
We are closing this issue. You can track the status of the feature using the provided feedback link.
