### ISSUE TITLE
Is there a way to change the timing of the calendar (resource view)?

### ISSUE THREAD

**Issue by zhpeh** [syncfusion/flutter-examples#680]
Hi there,

I would like to find out if there is a way for me to edit the time intervals of the calendar (resource view)? Currently it is designed to be in fixed time intervals, I would like to change it to be in differing time intervals (e.g. 20 or 30 mins) which may or may not be consistent. 

In addition, how can I edit the labels of the time to display some additional text beside the timing? Ideally, I wish to pass in an array of custom time intervals. 

Could you advise if this is possible? Thanks!

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Is there a way to customise the display of the time intervals in resource view?**

By using the [timeInterval](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/timeInterval.html) property of the [TimeSlotViewSettings](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings-class.html/) you can customize the time intervals of the time slots. If you want the time interval value (in minutes) you need to set the timeformat value to “hh:mm”, by  default value of the timeformat is “h a”. We have a UG and KB documentation for the same. Please find the UG and KB documentation for the same. 

**UG link:**
https://help.syncfusion.com/flutter/calendar/timeslot-views#change-time-interval 

Please find the KB documentation for time label customization.

**KB link:**
https://www.syncfusion.com/kb/11008/how-to-customize-the-time-label-in-the-flutter-calendar

Also, we have logged the feature request for “**Providing a support to different time intervals in the Flutter Calendar (SfCalendar)**”. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   

You can also communicate with us regarding the open features any time using our Feature Report page.       

**Feedback link:**
https://www.syncfusion.com/feedback/35767/providing-a-support-to-different-time-intervals-in-the-flutter-calendar-sfcalendar 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.  


Regards,
Indumathi R
