### ISSUE TITLE
Guage darg stops working at certain point

### ISSUE THREAD

**Issue by ChopraMukul** [syncfusion/flutter-examples#683]
I am working on a project and using this package (version "syncfusion_flutter_gauges: ^20.2.49"). I am facing issue with dragging the gauge from a specific point to another point. I found one problem. 

When I use an image inside the "GaugeAnnotation" widget Row -> Image then I am facing a Guage dragging issue. But when I use Padding->Row-> Image. Then it started working fine. 

I am not sure why "Padding" usage makes it work. Can you please give me an Idea why this is working?

Dragger stopped stopped between this: 
![imageedit_2_3893381022](https://user-images.githubusercontent.com/114716027/193200676-b44f54ac-b114-4216-b8d4-f0e7e880b821.gif)

  ```
    GaugeAnnotation(
      angle: 270,
      horizontalAlignment: GaugeAlignment.center,
      positionFactor: 0.10,
      verticalAlignment: GaugeAlignment.near,
      widget: Column(children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("CURRUNT",
                style:
                    IntexTextStyles.helveticaNeue10pt4),
          ],
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("TEMPERATURE",
                style:
                    IntexTextStyles.helveticaNeue10pt4),
          ],
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const SizedBox(height: 50),
              Container(
                width: 25.00,
                height: 25.00,
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: ExactAssetImage(
                        'assets/images/duration.png'),
                    fit: BoxFit.fill,
                  ),
                ),
              ),
              SizedBox(
                width: 35,
                child: Text.rich(
                  TextSpan(
                    children: <InlineSpan>[
                      TextSpan(
                          text: "Duration",
                          style: IntexTextStyles
                              .helveticaNeue8pt),
                      TextSpan(
                          text: "5HRS",
                          style: IntexTextStyles
                              .helveticaNeue10pt3),
                    ],
                  ),
                  style: IntexTextStyles.helveticaNeue16pt
                      .copyWith(
                          fontSize: 1.7 *
                              SizeConfig.textMultiplier),
                  textWidthBasis:
                      TextWidthBasis.longestLine,
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          ),
        ),
      ]),
    ),
```

**Comment by PraveenGopalsamy** [comment]
Hi ChopraMukul,

We have tried to reproduce the reported scenario in our [SfRadialGauge](https://pub.dev/packages/syncfusion_flutter_gauges) with the given code snippets in the [GaugeAnnotation](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/GaugeAnnotation-class.html) but we are unable to reproduce the mentioned dragging issue at our end. Please check the attached sample and if you are still facing the issue, then please modify the given sample based on your scenario and share it. This will help us to assist you in a better way by reproducing the exact scenario that you are facing.

**Attachment:** [flutter_gauges.zip](https://github.com/syncfusion/flutter-examples/files/9697778/flutter_gauges.zip)

Regards,
Praveen G.

**Comment by ChopraMukul** [comment]
Hi @PraveenGopalsamy, Thanks for the reply.

The code I gave in my comment is working. I mention in my comment when we add "Padding->Row-> Image. Then it started working fine. If we remove the wrapper "Padding" from the code. then It will start giving you the problem. 

Can you please check and try after removing the Padding? and Why Guage is giving errors without padding?

Does "positionFactor" or "Angle" numbers have anything to do with this padding?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ChopraMukul,

We are analyzing the reported issue at our end, and we will update further details in one business day. We appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by PraveenGopalsamy** [comment]
Hi @ChopraMukul ,

We can able to replicate the mentioned scenario now. In our [SfRadialGauge.GaugeAnnotation](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/GaugeAnnotation-class.html), we have only updated the child widget’s parent offset to the given position factor based on the available size. But the actual parent widget is rendered from our widget's top left corner. This is our current behavior. To resolve this issue, wrap your gauge annotation widget into the [IgnorePointer ](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html)widget. We have considered your request as a feature and the status can be tracked from the feedback portal link.

**Feedback Link:** https://www.syncfusion.com/feedback/27881/need-to-layout-the-radial-gauge-based-on-the-start-and-end-angles

We will prioritize the features for every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specifications/suggestions for the feature request, you can add them as a comment in the portal.

Regards,
Praveen G.

**Comment by ChopraMukul** [comment]
Hi @PraveenGopalsamy, Thank you so much. It's working fine for me
