### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt Error on stepDuration of SfRangeSelector

### ISSUE THREAD

**Issue by pradeepo7** [syncfusion/flutter-examples#689]
I'm getting "Infinity or NaN toInt" Error. while assign value like this => stepduration :SliderStepDuration(minutes: 10)

I setted SfRangeSelector as dateselector while both thumbs comes on the same ticks it will create a issue because datevalue is used in splinechart so datecontroll makes startdate and end date same , 
is there any method prevent this on range controller both thumbs don't overlap

here is reference of my graph 

![Screenshot_20221014_133630](https://user-images.githubusercontent.com/43827080/195795726-750f3393-50ad-48bf-88c5-367b9408942d.png)

here is the screenshot of bug

![Screenshot_20221014_133722](https://user-images.githubusercontent.com/43827080/195796110-16eb00ca-de1c-439d-9aaf-732ce8dd0aab.png)

**Comment by PraveenGopalsamy** [comment]
Hi @pradeepo7 ,

We have checked your query on our end. We would like to let you know that, when setting [stepDuration](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/stepDuration.html), the RangeSelector start and end thumbs can be placed on one another. You can avoid the thumb overlapping by adding a listener to the [RangeController](https://pub.dev/documentation/syncfusion_flutter_core/latest/core/RangeController-class.html). This listener gets invoked when the RangeController value changes. When the [RangeController.Start](https://pub.dev/documentation/syncfusion_flutter_core/latest/core/RangeController/start.html) and [RangeController.End](https://pub.dev/documentation/syncfusion_flutter_core/latest/core/RangeController/end.html) values are the same, you can update minimum thumb distance new values respectively. 

We have attached the sample for your reference. Please let us know if you face any issues with it.

**Attachment:** [i413680.zip](https://github.com/syncfusion/flutter-examples/files/9819637/i413680.zip)


Regards,
Praveen G.

**Comment by pradeepo7** [comment]
adding a listener to the [RangeController](https://pub.dev/documentation/syncfusion_flutter_core/latest/core/RangeController-class.html). solved the problem 

thanks @PraveenGopalsamy
