### ISSUE TITLE
Gradient for SplineSeries Line. 

### ISSUE THREAD

**Issue by sujalBandhara** [syncfusion/flutter-examples#69]
Hello is there any way to Gradient for SplineSeries Line of graph.
If it's available in any update then please share demo link.

**Comment by dharanidharandharmasivam** [comment]
Hi @sujalBandhara ,

Greetings from Syncfusion. We have analyzed your query and we suspect that you need to fill the spline series with gradient colors. If so, then your requirement can be achieved using the **SplineArea** series. Find the code snippet below to achieve this.

> 
    SfCartesianChart(series: [
      SplineAreaSeries<SalesData, double>(
        //Apply gradient color here
        gradient: gradientColors,
        //Other Configurations
      )
    ])

**Screenshot:**
<img width="219" alt="Screenshot_20200109-154258" src="https://user-images.githubusercontent.com/19346074/72059233-a2ed6800-32f7-11ea-8e1e-734cb0d225e5.png">


Sample for reference can be found from the below link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1963409312 

For more information on series types, find the user guide below.
https://help.syncfusion.com/flutter/chart/cartesian-chart-types#spline-area-chart

Thanks,
Dharani.
