### ISSUE TITLE
[SfCalendar] Error - Tried to get location before initializing timezone database

### ISSUE THREAD

**Issue by Verzu23** [syncfusion/flutter-examples#691]
Hi everyone,
I just run into this strange error when my flutter app is deployed on a server (in debug it never ever happen).
This is how it looks like.
![image](https://user-images.githubusercontent.com/23505339/196160649-8df26516-d5a5-4c8a-b9fb-1d4ea76f6afe.png)

In console i just have this :

![image](https://user-images.githubusercontent.com/23505339/196161227-1e5bf513-141b-4e34-a475-71a22adec9b8.png)

Can someone help?

**Comment by MuniappanSubramanian** [comment]
Hi Verzu23,

**# Regarding Error: Tried to get location before initializing timezone database**

As per the instruction we have followed to check the reported issue and we are unable to replicate the issue from our end. We have prepared a simple sample based on the shared details, please find the attached sample for the same,

Sample: [calendar_web.zip](https://github.com/syncfusion/flutter-examples/files/9810661/calendar_web.zip)

**Additionnel Information :**
Flutter Calendar Version: 20.3.50

Please check our sample and let us know if you still facing the same issue? if not, please modify our sample and revert us back with the following details which would be helpful for us to check on it and provide you the solution as soon as possible,



- Share the issue replicate video.
- Share the Flutter calendar version
- Share the issue reproducible sample

It will be helpful for us to check on it and provide you a solution at the earliest. Please let us know if you have any concerns. 

Regards,
Muniappan S
