### ISSUE TITLE
Date Range Picker crash my app

### ISSUE THREAD

**Issue by benjdero** [syncfusion/flutter-examples#692]
Hello, I got this weird crash that got reported by Crashlytics a few hundred times for different users on 15th and 16th October. It never happened before.

Not sure why it happen suddenly, my app haven't been updated in the past month. It was built with `syncfusion_flutter_datepicker 20.2.48`

The error I got wasn't really helpful:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError :  type 'Null' is not a subtype of type 'Future<void>'. Error thrown null.
```

Nor the stacktrace I decoded, it doesn't even seems to point to my code:
```
#0      Tween.end= (package:flutter/src/animation/tween.dart:245:6)
#1      _PickerScrollViewState._onHorizontalEnd (package:syncfusion_flutter_datepicker/src/date_picker/date_picker.dart:10748:20)
#2      new ThemeData (package:flutter/src/material/theme_data.dart:520:36)
#3      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:345:26)
#4      _Uri._mayContainDotSegments (dart:core/uri.dart:2579:14)
#5      ListIterator.current (dart:_internal/iterable.dart:330:29)
#6      _Uri._normalizeRelativePath (dart:core/uri.dart:2634:45)
#7      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
#8      Encoding._nameToEncoding (dart:convert/encoding.dart:38:74)
#9      new _Image._ (dart:ui/painting.dart)
#10     new Image._ (dart:ui/painting.dart:1654:21)
#11     Codec.getNextFrame.<anonymous closure> (dart:ui/painting.dart:2002:24)
#12     Isolate._getPortAndCapabilitiesOfCurrentIsolate (dart:isolate-patch/isolate_patch.dart)
#13     _GrowableList.add (dart:core-patch/growable_array.dart:280:7)
#14     _Uri._normalizeRelativePath (dart:core/uri.dart:2646:16)
#15     _Uri.removeFragment (dart:core/uri.dart:2005:17)
#16     AllocationStub_Yea_16227+0x7
#17     _SimpleUri._simpleMerge (dart:core/uri.dart:4792:16)
#18     instantiateImageCodec (dart:ui/painting.dart)
#19     TypeTestingStub_dart_async__Ab__X0_13810+0x9f
#20     instantiateImageCodec (dart:ui/painting.dart)
```

**Comment by MuniappanSubramanian** [comment]
@benjdero 

According to the instructions provided, we followed the steps to check the reported issue but were unable to replicate it on our end. We have prepared a sample based on the shared information, which is attached for your reference.

Please note that the version of **SfDateRangePicker** used for this test is **21.1.41.**

Please check our sample and let us know if you are still facing the same issue. If the issue persists, please provide us with the following details:

•	A video demonstrating the issue you are facing.
•	The code snippets for your Datepicker implementation.
•	A reproducible sample that demonstrates the issue.

Providing these details would be helpful for us to investigate the issue and provide you with a solution as soon as possible.

[Sample.zip](https://github.com/syncfusion/flutter-examples/files/11308844/Sample.zip)
[output.zip](https://github.com/syncfusion/flutter-examples/files/11308845/output.zip)
