### ISSUE TITLE
To customize timeSlotViewSetting

### ISSUE THREAD

**Issue by SMin98** [syncfusion/flutter-examples#693]
Is there a way to customize timeSlotViewSetting as follows?
<img width="271" alt="스크린샷 2022-10-18 오전 9 47 51" src="https://user-images.githubusercontent.com/62275738/196309850-46e92948-5d94-4bee-8df0-cd405cadacb5.png">

**Comment by MuniappanSubramanian** [comment]
Hi SMin98,

**#Regarding To customize timeSlotViewSetting**
We regret to inform you that, as per the current implementation of the Flutter calendar, there is no support to customize the timeslot you mentioned in the screenshot. Please get in touch with us if would you require any further assistance.

Regards,
Muniappan S
