### ISSUE TITLE
[SfCalendar - WeekView] Appointments custom 

### ISSUE THREAD

**Issue by SMin98** [syncfusion/flutter-examples#695]
1. Is there a way to customize Appointments?
Customizing Decorations such as only borders or circular containers
2. Is there a way to delete the cycle icon when setting the recurrence Rule?

**Comment by MuniappanSubramanian** [comment]
Hi SMin98,

**#Regarding Appointment customization and removing the cycle icon**
You can achieve your requirement by customizing the appointment by using the ‘appointmentBuilder’ widget from the Flutter calendar.  You can refer to our following KB documentation to customize the appointment in Calendar,

https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-calendar

Please refer to our UG documentation to know more details about appointment builder support in Calendar,
https://help.syncfusion.com/flutter/calendar/builders#appointment-builder

Please refer to our UG documentation to know more details about appointment customization using ‘appointmentTextStyle’ in Calendar,
https://help.syncfusion.com/flutter/calendar/appointments#appearance-customization

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muniappan S
