### ISSUE TITLE
[SFDatePicker] date range with dotted lines

### ISSUE THREAD

**Issue by 8thgencore** [syncfusion/flutter-examples#696]
How to achieve the same effect as in the image. To display a date range with dotted lines

![image](https://user-images.githubusercontent.com/30128845/197595138-b8ac1b57-3855-4115-acd2-c98edb32d3ea.png)

**Comment by MuniappanSubramanian** [comment]
Hi 8thgencore,

**# Regarding date range with dotted lines**
You can achieve your requirement by setting the “**selectionMode**” as “**extendableRange**” in the DateRange picker. Please refer to our UG documentation to know more details about extendable range selection,

https://help.syncfusion.com/flutter/daterangepicker/selections#extendable-range-selection

If the shared information doesn’t meet your requirement kindly revert us with more information, it will be helpful for us to provide you with a better solution.

Please let us know if you need further assistance.

Regards,
Muniappan S
