### ISSUE TITLE
how to change cell width and size in SfDateRangePicker

### ISSUE THREAD

**Issue by nashihu** [syncfusion/flutter-examples#697]
hello i've tried to follow https://help.syncfusion.com/flutter/daterangepicker/builders by copy-pasting the example,

but the result is not the same as in the link, here's what i got:

![IMG_3C4160956640-1](https://user-images.githubusercontent.com/35857544/199139430-440e5a09-c914-4f8b-afb4-3fde644c439f.jpeg)

<details>
<summary>my code</summary>
<br>

      SfDateRangePicker(
      // headerHeight: 0,
      controller: _controller,
      cellBuilder: (BuildContext context, DateRangePickerCellDetails details) {
        print('h ${details.bounds.height}');
        print('w ${details.bounds.width}');
        final bool isToday = isSameDate(details.date, DateTime.now());
        final bool isBlackOut = isBlackedDate(details.date);
        final bool isSpecialDate = isSpecialDay(details.date);
        return Container(
          margin: EdgeInsets.all(2),
          padding: EdgeInsets.only(top: 10),
          decoration: BoxDecoration(
              color: Colors.blueAccent,
              border:
                  isToday ? Border.all(color: Colors.black, width: 2) : null),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              Text(
                details.date.day.toString(),
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.bold,
                ),
              ),
              isBlackOut
                  ? Icon(
                      Icons.block_sharp,
                      size: 13,
                    )
                  : isSpecialDate
                      ? Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(
                              Icons.cake,
                              size: 13,
                            ),
                            Icon(
                              Icons.celebration,
                              size: 13,
                            ),
                            Icon(
                              Icons.audiotrack,
                              size: 13,
                            )
                          ],
                        )
                      : Container()
            ],
          ),
        );
      },
    );
</details>

anything i missed? thank you

**Comment by MuniappanSubramanian** [comment]
**# Regarding how to change cell width and size in SfDateRangePicker**

This is a sample-level issue. By removing the top padding for the container, the bottom overflow issue has been fixed. Refer to the attached sample based on the given code snippets.

[custom_picker.zip](https://github.com/syncfusion/flutter-examples/files/9909732/custom_picker.zip)

**Comment by nashihu** [comment]
thanks it works. i also added SizedBox as parent of SFDateRangePicker to make cell's height a little bit taller
