### ISSUE TITLE
Is it free? 【question】

### ISSUE THREAD

**Issue by Dhuliang** [syncfusion/flutter-examples#7]
I couldn't find the price on the official website.
Can you tell me if there is a price?

**Comment by JayavigneshwaranG** [comment]
Hi @Dhuliang ,

Thanks for trying our Flutter widgets.
You can refer the Syncfusion licensing terms and conditions from the below link.
https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

And you can get more details about our community license from the below link.
https://www.syncfusion.com/products/communitylicense

If you still have any queries, please create a support incident(https://www.syncfusion.com/support/directtrac/incidents/newincident) for better follow up, we will update our response there.

Thanks,
Jayavigneshwaran
