### ISSUE TITLE
Y-axis interval adaptive

### ISSUE THREAD

**Issue by Cyycl** [syncfusion/flutter-examples#70]
Hi~
- description:
There are multiple polylines, and one of them is selected for display by legend. The interval of the Y axis is not adaptive based on the value of the polyline.

- demo：
![demo](https://s2.ax1x.com/2020/01/09/lWTypq.png)

The value of the polyline named “月结” is too small compared to the other three polylines, which causes this polyline to display unreasonably under the current interval of the Y axis

Thanks ~

**Comment by dharanidharandharmasivam** [comment]
Hi @Cyycl ,

Greetings from Syncfusion. We had gone through the reported scenario, unfortunately, the scenario is not reproduced on our side. The ranges are properly calculating, and the line series is rending properly. The sample used for testing can be found from the below link. 

https://www.syncfusion.com/downloads/support/directtrac/260601/ze/issue_70_y_axis_adaptive135221429 

Since we are unaware of your exact scenario on which you are facing such an issue, kindly try to replicate the reported scenario with the above sample and revert or share your code snippet with your data source. This will be helpful for us to resolve it.
       
Regards,
Dharani.

**Comment by Cyycl** [comment]
> Hi @Cyycl ,
> 
> Greetings from Syncfusion. We had gone through the reported scenario, unfortunately, the scenario is not reproduced on our side. The ranges are properly calculating, and the line series is rending properly. The sample used for testing can be found from the below link.
> 
> https://www.syncfusion.com/downloads/support/directtrac/260601/ze/issue_70_y_axis_adaptive135221429
> 
> Since we are unaware of your exact scenario on which you are facing such an issue, kindly try to replicate the reported scenario with the above sample and revert or share your code snippet with your data source. This will be helpful for us to resolve it.
> 
> Regards,
> Dharani.

Thanks @dharanidharandharmasivam ~

but I do not have permission to access this below link

https://www.syncfusion.com/downloads/support/directtrac/260601/ze/issue_70_y_axis_adaptive135221429

**Comment by dharanidharandharmasivam** [comment]
Hi @Cyycl ,

We regret the inconvenience. The sample is accessible at our end however, we have attached the same sample with the below link. Kindly find the sample,

https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_70_y_axis_adaptive591510604 

Thanks
Dharani.

**Comment by Cyycl** [comment]
> Hi @Cyycl ,
> 
> We regret the inconvenience. The sample is accessible at our end however, we have attached the same sample with the below link. Kindly find the sample,
> 
> https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_70_y_axis_adaptive591510604
> 
> Thanks
> Dharani.


Thanks for fThe reason is that I used the old version of the chart

> Hi @Cyycl ,
> 
> We regret the inconvenience. The sample is accessible at our end however, we have attached the same sample with the below link. Kindly find the sample,
> 
> https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_70_y_axis_adaptive591510604
> 
> Thanks
> Dharani.

Hi @dharanidharandharmasivam 

Thank you very much for the detailed example. The reason is that I used the old version.
