### ISSUE TITLE
Calendar widget test

### ISSUE THREAD

**Issue by BinaryITSolution** [syncfusion/flutter-examples#704]
Can you add the sample code to add a Widget Test for calendar

**Comment by MuniappanSubramanian** [comment]
You can achieve your requirement by using the "**flutter_test**" dependency. Please follow the steps below to meet your needs. 

1. Add the flutter test dependency 

Before writing tests, include the **flutter_test** dependency in the dev_dependencies section of the pubspec.yaml file. 
`dev_dependencies: 
     flutter_test: 
      sdk: flutter`

Refer to the below link for more details about widget testing in the Flutter 
https://docs.flutter.dev/cookbook/testing/widget/introduction

2. Then create a widget to test and create a testWidgets test. By using the testWidgets() from the flutter_test package, you can define a test. Here I have prepared a simple test, in which I have checked whether the next month of the calendar is "December" or not. I got the visible dates collection from the onViewChanged callback of the calendar. Refer to the below code snippets: 

`void main()
{
testWidgets("Flutter Widget Test", (WidgetTester tester) async {
await tester.pumpWidget(const MyApp());
var button = find.text("NextMonth");
expect(button, findsOneWidget);
await tester.tap(button);
await tester.pump();
var visibleDates = getVisibleDates();
final DateTime nextMonth = visibleDates[0];
expect(nextMonth.month, DateTime.december);
expect(nextMonth, DateTime(2022, 12));
});
}`

3. To run the test, use the below command in the terminal.
`flutter test./test/widget_testing.dart`

I have attached a sample of the same. Please find the attached sample. 

[widget_test.zip](https://github.com/syncfusion/flutter-examples/files/10012714/widget_test.zip)
