### ISSUE TITLE
DataGridToPdfConverter:DataGridPdfHeaderFooterExportCallback - Create custom footer

### ISSUE THREAD

**Issue by ChipM0nk** [syncfusion/flutter-examples#706]
How do I create and position a custom footer just below the datatable using `DataGridPdfHeaderFooterExportCallback`?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ChipM0nk,

You can set the document footer using the **DataGridPdfHeaderFooterExportDetails.pdfDocumentTemplate.bottom** property in the **DataGridPdfHeaderFooterExportCallback** callback.  I've attached a simple sample. Please refer to the following code snippet and sample.

```dart
final PdfDocument document =
_key.currentState!.exportToPdfDocument(
headerFooterExport: (details) {
final double width = details.pdfPage.getClientSize().width;
PdfPageTemplateElement footer =
PdfPageTemplateElement(Rect.fromLTWH(0, 0, width, 60));

footer.graphics.drawString(
'PDF Footer',
PdfStandardFont(PdfFontFamily.helvetica, 13,
style: PdfFontStyle.bold),
bounds: const Rect.fromLTWH(220, 25, 200, 60),
);

//Add the footer at the bottom of the document
details.pdfDocumentTemplate.bottom = footer;
},
);
final List<int> bytes = document.saveSync();
await helper.saveAndLaunchFile(bytes, 'DataGrid.pdf');
document.dispose();

```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-190460752

**Comment by ChipM0nk** [comment]
Got it. Thank you for the response!
