### ISSUE TITLE
How can I achive this design

### ISSUE THREAD

**Issue by cgowthamanmca** [syncfusion/flutter-examples#707]
Could you share design coding
![Range](https://user-images.githubusercontent.com/34183706/205612565-5199b0d9-a137-43e9-9574-e16a8eaefe1c.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @cgowthamanmca ,


You can find the code snippet for the requested radial gauge types in the below link.


Multiple range - https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/gauge/pointers/text_pointer.dart
Range width - https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/gauge/ranges/range_thickness.dart
Range label - https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/gauge/ranges/range_datalabels.dart

Regards,
Yuvaraj.
