### ISSUE TITLE
how to disable some days which I need to disable

### ISSUE THREAD

**Issue by mazab99** [syncfusion/flutter-examples#710]

**Comment by mrchuis** [comment]
@mazab99, Have you found a solution?

**Comment by MuniappanSubramanian** [comment]
@mazab99 

You can disable the interaction for a certain date in the month view and timeline month view by using the **blackoutDates** property in the Flutter Calendar. Refer to the below UG documentation to achieve your requirement,

https://help.syncfusion.com/flutter/calendar/month-view#blackout-dates 

You can refer to our KB documentation to know more details about blackout dates and their customization,
https://support.syncfusion.com/kb/article/10759/how-to-update-blackout-dates-using-onviewchanged-callback-in-the-flutter-calendar 
https://support.syncfusion.com/kb/article/10377/how-to-add-active-dates-in-the-flutter-calendar 
https://support.syncfusion.com/kb/article/10346/how-to-customize-the-blackout-dates-in-the-flutter-event-calendar-sfcalendar
