### ISSUE TITLE
Late initialization error

### ISSUE THREAD

**Issue by tauqeerkhattak** [syncfusion/flutter-examples#716]
`LateInitializationError: Field '_useMobilePlatformUI@1082355329' has not been initialized.

The relevant error-causing widget was: 
  AppCalendar AppCalendar:file:///D:/Flutter%20Apps/AppForIOS-main/lib/ui/pages/calendar/calendar_page.dart:595:16
When the exception was thrown, this was the stack: 
#0      _SfCalendarState._useMobilePlatformUI (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart)
#1      _SfCalendarState._removeScheduleViewAppointmentDates (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:4565:13)
#2      _SfCalendarState.didUpdateWidget (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:2956:7)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:5065:57)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)`

**Comment by MuniappanSubramanian** [comment]
Attempting the scenario with SfCalendar version **20.4.41** for adding appointments to the calendar and it’s working fine. I've attached a simple sample based on the shared details. 

[calendar_appointments.zip](https://github.com/syncfusion/flutter-examples/files/10336768/calendar_appointments.zip)

**Comment by tauqeerkhattak** [comment]
Hi,

I have tested with the new version and it seems to be working fine, closing this issue.
