### ISSUE TITLE
Update to timezone 0.9.1

### ISSUE THREAD

**Issue by mauriziopinotti** [syncfusion/flutter-examples#717]
Hi,

The timezone package has been updated, please upgrade your dependency in flutter_calendar:

```
Because syncfusion_flutter_calendar >=20.3.48 depends on timezone 0.9.0 and syncfusion_flutter_calendar >=19.3.43+1 <20.3.48 depends on timezone 0.8.0, syncfusion_flutter_calendar >=19.3.43+1 requires timezone 0.8.0 or 0.9.0.
So, because easyhour_app depends on both timezone ^0.9.1 and syncfusion_flutter_calendar ^20.3.47, version solving failed.
pub finished with exit code 1
```

I think you should allow minor version fixes by using `timezone: ^0.9.1` (with the caret symbol).

**Comment by MuniappanSubramanian** [comment]
We have upgraded the timezone package in the Flutter Calendar and included it in our latest Weekly Nuget release package version **20.4.43.** Kindly update to the latest version for this. Also please find the changelog for the same.

Latest version: https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.
