### ISSUE TITLE
Set selectionShape  is not working when use cellBuilder in SfDateRangePicker

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [syncfusion/flutter-examples#718]
I want to set circle to selectionShape, meanwhile I use cellbuilder to custom the cell.But the selectionShape was not circle, it is still rectangle.What should I do ?

**Comment by andresziemecki** [comment]
I have the same issue. When I add any cellBuilder to the SfDateRangePicker, the selection shape turns rectangle with a corner radius of zero. 
Also, customizing the selected shape with the cell builder doesn't override this blue rectangle. 
Here is a cellBuilder function example and its results below:
```
  Widget cellBuilder(
      BuildContext context, DateRangePickerCellDetails cellDetails) {
    var IsSelected = _controller.selectedDate != null &&
        cellDetails.date.year == _controller.selectedDate?.year &&
        cellDetails.date.month == _controller.selectedDate?.month &&
        cellDetails.date.day == _controller.selectedDate?.day;
    if (IsSelected) {
      return Container(
          decoration: BoxDecoration(
              color: Colors.red,
              borderRadius: BorderRadius.all(Radius.circular(20))),
          child: Column(
            children: [
              Container(
                child: Text(
                  cellDetails.date.day.toString(),
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.white),
                ),
              ),
              Container(
                  child: Text(
                DateFormat('EEE').format((cellDetails.date)),
                style: TextStyle(color: Colors.white),
              )),
            ],
          ));
    }
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Container(
          child: Text(DateFormat('dd').format(cellDetails.date)),
        ),
        Container(
            child: Text(
          "title",
          style: TextStyle(fontSize: 8, color: Colors.black),
        ))
      ],
    );
  }
```
<img width="342" alt="Screenshot 2023-04-23 at 17 42 59" src="https://user-images.githubusercontent.com/30945461/233849724-ec6481e1-a96f-40ad-a42f-95a45ee4a878.png">

**Comment by Indumathi1195R** [comment]
As per the current implementation, the selection shape not working while implementing the cellBuilder and it is an expected behavior of the SfDateRangePicker.By using the **shape** property in the **BoxDecoration** you can achieve your requirement in cell builder. We have prepared the sample for the same. Please find the sample from the following link.

**Sample link:**
[cellbuilder.zip](https://github.com/syncfusion/flutter-examples/files/11321996/cellbuilder.zip)

We hope that this helps you. Please let us know if you need further assistance.

**Comment by IndumathiR-1995** [comment]
We are glad to know that the issue resolved at your end. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
