### ISSUE TITLE
The button "TODAY" not translated to Chinese in the month view of SfDateRangePicker.

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [syncfusion/flutter-examples#720]

**Comment by Indumathi1195R** [comment]
As per the shared information, we have checked the issue of locale translation not working for ‘Today’ text in the SfDateRangePicker and it was working fine as expected. For achieving this we need to add the **syncfusion_localizations** package. Please find the UG documentations for the same.

**UG link:**
https://help.syncfusion.com/flutter/globalization#how-to-localize-the-syncfusion-flutter-widgets

We have attached the screenshot for same. 
<img width="484" alt="Screenshot 2023-04-18 at 3 34 23 PM" src="https://user-images.githubusercontent.com/54974849/232802838-dadfa31d-628d-4364-8151-55999dc5583c.png">

Please let us know if you need further assistance.
