### ISSUE TITLE
The first appoinment duplicate for all day event

### ISSUE THREAD

**Issue by thuydtshop** [syncfusion/flutter-examples#721]
Environment:
- Flutter 3.3.10
- iOS 16.2
- syncfusion_flutter_calendar 20.4.42

If I add some all day events, it always show the first appointment to the last, also just get it if you not expand arrow icon (arrow icon on attached)

Can you check it?

<img width="330" alt="Screenshot 2023-01-05 at 18 55 38" src="https://user-images.githubusercontent.com/82221905/210775375-a9415d0c-021b-4d99-8a9e-d11545fbba9d.png">
<img width="337" alt="Screenshot 2023-01-05 at 18 55 29" src="https://user-images.githubusercontent.com/82221905/210775381-9f30702a-98cb-4e3b-b7de-08ac9e4bffe2.png">

**Comment by Indumathi1195R** [comment]
As per the shared information, we have checked the issue "**First appointment was duplicated in the all day appointment in Flutter Calendar"** and we are unable to reproduce the issue from our end. We have attached the tested sample for the same. Please find the sample from the following link.

**Sample link:**
[allday.zip](https://github.com/syncfusion/flutter-examples/files/11321388/allday.zip)

**Tested details:**
Flutter 3.7.1
iOS 15.2
syncfusion_flutter_calendar 21.1.39

If possible can you please share the following details with us? It would be helpful for us to analyze and provide you a solution at the earliest.

* Code snippet
* Issue replication procedure
