### ISSUE TITLE
Appointment is showing in Week View but not showing in other Views

### ISSUE THREAD

**Issue by freshcodestechnology** [syncfusion/flutter-examples#723]
I scheduled an appointment with 6:30 PM onwards and then it is visible in only week view and in other views like Day, Month, Schedule & TimelineDay is not showing this appointment.

Also if i change its time before 6:30 PM then it will visible in all views.

The data source is same for all.

Please review following code

```
CalendarController calendarController = CalendarController();

Duration interval = Duration(minutes: 15)

double startHour = 0;
double endHour = 24;

var timeSlotSetting = TimeSlotViewSettings(
      timeInterval: interval,
      timeFormat: 'h:mm aa',
      timeRulerSize: 70,
      timelineAppointmentHeight: 60,
      timeIntervalHeight: 60,
      dayFormat: 'EEE',
      dateFormat: 'd MMM',
      startHour: startHour,
      endHour: endHour,
    );

SfCalendar(
   controller: calendarController,
   view: CalendarView.week,
   timeSlotViewSettings: timeSlotSetting,
   monthViewSettings: const MonthViewSettings(
    showAgenda: true,
    appointmentDisplayMode: MonthAppointmentDisplayMode.none,
    agendaItemHeight: 60,
    showTrailingAndLeadingDates: false,
   ),
   resourceViewSettings: ResourceViewSettings(
    showAvatar: false,
    displayNameTextStyle: Get.textTheme.bodyText1!.copyWith(color: Colors.white),
    size: 120,
   ),
   scheduleViewSettings: const ScheduleViewSettings(appointmentItemHeight: 60),
   showDatePickerButton: true,
   allowedViews: const [
     CalendarView.day,
     CalendarView.week,
     CalendarView.month,
     CalendarView.schedule,
     CalendarView.timelineDay,
   ],
   dataSource: MeetingDataSource(
     controller.getAppointmentDataSource(),
     controller.getCalendarResources(),
   ),
  allowAppointmentResize: true,
  cellEndPadding: 0,
  showNavigationArrow: true,
  specialRegions: getTimeRegions(),
  initialDisplayDate: DateTime.now(),
  todayHighlightColor: AppColors.primaryColor,
)
```

**Comment by MuniappanSubramanian** [comment]
As per the instructions provided, we have followed the steps to check the reported issue and were unable to replicate the issue on our end. We tested scenarios where appointments were added at 6:30 PM and confirmed that the issue does not occur in any of the views. We have prepared a sample based on the code snippets provided and have included it in the attachment. We have also included a video of the sample being tested.

Please note that the version of SfCalendar used for this test is **20.4.43.**

If you are still experiencing the issue, please let us know. Additionally, please provide the following details to help us further investigate the issue:

- A video of the issue being replicated
- The calendar code snippets
- A reproducible sample of the issue

This will help us to provide you with a solution as soon as possible.

[calendar-appointments.zip](https://github.com/syncfusion/flutter-examples/files/10411304/calendar-appointments.zip)
