### ISSUE TITLE
The height of the date picker of SfCalendar can't customed .

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [syncfusion/flutter-examples#724]
I checked the source code, the height was 0.5*SfCalendar._minHeight. When the SfCalendar‘s height is half of the screen's height, the height of  date picker dialog was too small. So should you add the feature to custom the height?Thank you.

**Comment by MuniappanSubramanian** [comment]
The current implementation of the Flutter Calendar does not have support to customize the date picker height. If you have any other questions or concerns, please let us know and we'll be happy to assist you.

**Comment by NaarGes** [comment]
is there an plan to add the customization to date picker header?
Like having other actions on it except the today button

**Comment by Indumathi1195R** [comment]
**Regarding Query: is there an plan to add the customization to date picker header?**

Current implementation of the picker have support to customize the header using the **headerHeight** and **headerStyle** properties. We have a UG and KB documentation for the same. Please find the documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/headers#customize-the-header-height
https://help.syncfusion.com/flutter/daterangepicker/headers#header-appearance

**KB links:**
https://www.syncfusion.com/kb/12098/how-to-replace-the-view-header-with-the-custom-widget-in-flutter-date-range-picker 

Please let us know if you need further assistance on this.

**Comment by NaarGes** [comment]
Thanks for reply.
Thanks I did manage to change the current month text style but the caret next to it is not customizable.

I was looking for fully customization of header.
Like the one mentioned above and another purpose is having more action button next to today icon button.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @NaarGes ,

Yes, you can able to customize the header fully, we already have a KB that explains how to replace the header with the custom widget. We have shared the KB documentation below, you can follow the guidelines and achieve your requirements.

KB, https://support.syncfusion.com/kb/article/9606/how-to-add-custom-header-and-view-header-in-the-flutter-calendar

If you have any further queries please get back to us, we are always happy to assist you.

Regards,
Yuvaraj.
