### ISSUE TITLE
How do I tap a button in the Trackball tooltip?

### ISSUE THREAD

**Issue by KoheiKanagu** [syncfusion/flutter-examples#725]
I create a trackball tooltip with a custom widget.

The edit icon is `IconButton`, but it does not receive the `onPressed` event.
Another tooltip is displayed.

https://user-images.githubusercontent.com/6175794/213380683-00585830-f3bb-47a8-8624-74a3d9736e64.mov

```dart
    return SfCartesianChart(
      trackballBehavior: TrackballBehavior(
        enable: true,
        activationMode: ActivationMode.singleTap,
        shouldAlwaysShow: true,
        tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
        tooltipAlignment: ChartAlignment.near,
        builder: (context, trackballDetails) {
          return Card(
            color: Colors.lightBlue,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'x: ${trackballDetails.groupingModeInfo?.points.first.x}',
                ),
                IconButton(
                  onPressed: () {
                    // never called
                    logger.d('onPressed');
                  },
                  icon: const Icon(Icons.edit),
                ),
              ],
            ),
          );
        },
      ),
      series: [
        LineSeries(
          markerSettings: const MarkerSettings(
            isVisible: true,
            shape: DataMarkerType.triangle,
          ),
          dataSource: List.generate(12, (e) => Random().nextDouble() + sin(e)),
          xValueMapper: (datum, index) => index,
          yValueMapper: (datum, index) => datum,
        ),
        LineSeries(
          markerSettings: const MarkerSettings(
            isVisible: true,
            shape: DataMarkerType.rectangle,
          ),
          dataSource: List.generate(12, (e) => Random().nextDouble() + sin(e)),
          xValueMapper: (datum, index) => index,
          yValueMapper: (datum, index) => datum * -1,
        ),
      ],
    );
```

**Comment by KoheiKanagu** [comment]
It seems like a good way to get the tapped position on the `onTrackballPositionChanging` event and draw a `Button` in front of the chart.

https://user-images.githubusercontent.com/6175794/213393711-9689c2e3-4da5-49f8-baf7-27d5897eccac.mov

```dart
    return Stack(
      children: [
        chart,
        Positioned(
          left: xPosition.value,
          child: Card(
            color: Colors.lightBlue,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                IconButton(
                  onPressed: () {
                    logger.d('onPressed');
                  },
                  icon: const Icon(Icons.edit),
                ),
              ],
            ),
          ),
        ),
      ],
    );
```

Are there other solutions?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @KoheiKanagu ,

Currently, we do not have the support to handle the interaction in the trackball tooltip. We have already logged a feature request in our feedback portal. We will prioritize the features of every release based on demand and priority, so this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

https://www.syncfusion.com/feedback/37658

Regards,
Yuvaraj.

**Comment by KoheiKanagu** [comment]
@Yuvaraj-Gajaraj 
Thanks for the information.

However, the Feedback Portal link gave me an access denied error.
I would like to see it if possible.

Anyway, I look forward to seeing it implemented.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @KoheiKanagu ,

We have included your mail in this feedback and granted permission to view it, we have shared it below for your reference.

Feedback, https://www.syncfusion.com/feedback/37658

Regards,
Yuvaraj

**Comment by KoheiKanagu** [comment]
@Yuvaraj-Gajaraj
I was able to see the Feedback.
Thank you!
