### ISSUE TITLE
Flutter Chart not plotting real-time data

### ISSUE THREAD

**Issue by Parthjethwa** [syncfusion/flutter-examples#726]
Hi, we are trying to plot the ECG wave lines from a device to the app directly through bluetooth and in that we are not getting a perfect result from the chart so pls suggest me how i can solve this error.

Here is the code,

 SfCartesianChart(
                        series: <ChartSeries>[
                          LineSeries<DataClass, int>(
                              dataSource: baseData1,
                              xValueMapper: (DataClass graph, _) => graph.xAxis,
                              yValueMapper: (DataClass graph, _) => graph.yAxis,
                              color: Colors.green,
                            onRendererCreated: (ChartSeriesController controller) {
                              seriesController = controller;
                            },
                          )
                        ],
                      ),

**Comment by Yuvaraj-Gajaraj** [comment]
We suspect that you are facing an issue while updating the data using a [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html). So, we have shared the UG and KB documentation below, it will explain how to update the real-time data using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method. 

UG, https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource

KB, https://www.syncfusion.com/kb/12316/how-to-create-flutter-real-time-charts-using-the-cartesian-charts-widget-sfcartesianchart

If this is not your case, then please provide more information regarding how you added the data and how you updated the data using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method. Also, share the output screenshot or screen recordings. It will be more helpful for us to assist you in a better way.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
