### ISSUE TITLE
SfDateRangePicker, minDate not working properly

### ISSUE THREAD

**Issue by HemangSidapara** [syncfusion/flutter-examples#728]
When i set up minDate then date after minDate also disable.

i set minDate is dec,26 and maxDate is feb,5. But dec,27 also disable. it is in the range of maxDate and minDate

![image](https://user-images.githubusercontent.com/61095579/214684858-7f4e8796-0cdb-407b-b0a2-ee935e18182c.png)

**Comment by Indumathi1195R** [comment]
HemangSidapara,

As per the shared information, we have checked the minimum date not working properly. We have checked with the minimum and maximum dates as specified and it was working fine as expected. We have attached the tested details for the same. 

**Tested details:**
Date picker version- 21.1.39
Flutter version- 3.7.11

We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.
