### ISSUE TITLE
Error building for iOS

### ISSUE THREAD

**Issue by gotnull** [syncfusion/flutter-examples#729]
I have cloned [this repository](https://github.com/syncfusion/flutter-examples). I get an issue when I run the following commands:

```
flutter clean
flutter pub get
flutter build ios
```

```
Could not build the precompiled application for the device.
Error (Xcode): No file or variants found for asset: world_map.json.
```

**Comment by fenjuly** [comment]
same error I have faced,
and I solved this error by add prefix `assets/`  to the `world_map.json` at pubspec.yaml file.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/4019015/217744957-7d24fa8e-6809-460d-abca-c7af34921b1a.png">

then works fine

**Comment by LavanyaGowtham2021** [comment]
Hi @gotnull ,

We have resolved the issue already and so we kindly request you to upgrade the latest version.

**Comment by gotnull** [comment]
Terrific, thanks!
