### ISSUE TITLE
Column chart not taking given width when using datetime axis

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [syncfusion/flutter-examples#73]
I have given width as 1 for all the column charts. But all the charts have different widths. I have tried multiple combinations but don't seem to get all the charts to have the same specified width.

`charts.add(ColumnSeries<ChartData, DateTime>(
        dataSource: data,
        yAxisName: 'yAxis1',
        name: 'Steps',
        xAxisName: 'xAxis1',
        color: Colors.green,
        width: 1,
        opacity: 0.7,
        xValueMapper: (ChartData sales, _) => sales.x,
        yValueMapper: (ChartData sales, _) => sales.y));`

![WhatsApp Image 2020-01-15 at 12 25 34 PM](https://user-images.githubusercontent.com/35574146/72412008-4cb67400-3792-11ea-83ba-2ed85723cc45.jpeg)

**Comment by dharanidharandharmasivam** [comment]
Hi @LaxmikanthMadhyastha ,

Thanks for using our Syncfusion Flutter widgets. We have analyzed the reported scenario and we would like to let you know that, the width of each column will be calculated based on the available axis width, number of points and width property specified in series. This is the actual behavior.

We have prepared a sample to depict this scenario in which we have 3 charts, each one having 4, 5 and 2 data points respectively. The column of these 3 charts renders with different in size. 

**Screenshot:**
![Screenshot_20200115_203236_com example line_series - Copy](https://user-images.githubusercontent.com/19346074/72448976-f0794180-37dd-11ea-9699-05880155b405.jpg)

The sample can be found below.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-293318928 

Thanks,
Dharani.

**Comment by madhukar01** [comment]
I had faced the same issue a couple of days back and was never able to get similar width bars (for the same number of points). I spent 2 days breaking my head around it and finally stopped using Syncfusion altogether.

@dharanidharandharmasivam Your comment does not explain why there is a difference between the width of bars in first and 3rd  chart in the screenshot posted by OP. ( I see 4 bars in the first chart and 4 bars in last chart but they are of different width).

**Comment by madhukar01** [comment]
Is there a way we can override this behaviour?
This is too cumbersome when plotting a time series.

For example if I want to plot a single data point in a chart spanning 24 hours, currently I am being forced to provide 24 points so that bar width remains same across all charts.
Most of the libraries handle this by default for a timeseries / Datetime axis.
