### ISSUE TITLE
type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.

### ISSUE THREAD

**Issue by ivangoluuk** [syncfusion/flutter-examples#730]
../../../developer/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7596:37: Error: The argument type 'ScrollableState?' can't be assigned to the parameter type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.

 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../../developer/flutter/packages/flutter/lib/src/widgets/scrollable.dart').

        scrollableState: Scrollable.of(context),

                                    ^

../../../developer/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7611:40: Error: A value of type 'ScrollableState?' can't be assigned to a variable of type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.

 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../../developer/flutter/packages/flutter/lib/src/widgets/scrollable.dart').

        ..scrollableState = Scrollable.of(context)

                                       ^

../../../developer/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7665:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.

 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../../developer/flutter/packages/flutter/lib/src/rendering/viewport.dart').

  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);

**Comment by luilabdev** [comment]
@ivangoluuk did you find a solution? I am having the same problem

**Comment by miguelflores1993** [comment]
I have the same problem.
don't use version:
` syncfusion_flutter_datepicker: ^20.4.48`

Use like this:
` syncfusion_flutter_datepicker: "20.4.44"`

**Comment by ivangoluuk** [comment]
hey thank u so much. its working now

**Comment by kefeh** [comment]
This works for me too. Thank you

**Comment by seborys40** [comment]
What changed for this to happen ? I even got this error in the same version I was using.

**Comment by MuniappanSubramanian** [comment]
@ivangoluuk 

Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.

Please be aware that the version of SfDateRangePicker used in this test is **20.4.48** and **Flutter version is 3.7.0.**

We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.
[datepicker_sample.zip](https://github.com/syncfusion/flutter-examples/files/10577891/datepicker_sample.zip)
[Output.zip](https://github.com/syncfusion/flutter-examples/files/10577892/Output.zip)

**Comment by Dev-Muhammad-Junaid** [comment]
> I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> 
> Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`

This one worked for me.

**Comment by StrixSC** [comment]
> I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> 
> Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`

+1 Thank you for the fix. Also curious as to what caused this to break.

**Comment by Mae623** [comment]
> I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> 
> Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`

hello, I try to use this way, but the pub get give me 20.4.48, even I execute the "flutter clean" command. Is there anything I can do?

**Comment by Dev-Muhammad-Junaid** [comment]
> > I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> > Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`
> 
> hello, I try to use this way, but the pub get give me 20.4.48, even I execute the "flutter clean" command first. Is there anything I can do?

You can remove the library from pubspec.yaml first and paste directly. Also I have added both dependecncies with " "

**Comment by Mae623** [comment]
> > > I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> > > Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`
> > 
> > 
> > hello, I try to use this way, but the pub get give me 20.4.48, even I execute the "flutter clean" command first. Is there anything I can do?
> 
> You can remove the library from pubspec.yaml first and paste directly. Also I have added both dependecncies with " "

Thank you for reply.
These are my step below, hope for your look:
1."flutter clean" command
2.delete pubspec.lock file
3.remove 'syncfusion_flutter_datepicker: ^20.4.44' from pubspec.yaml
4."pub get" command
5.add 'syncfusion_flutter_datepicker: ^20.4.44' into pubspec.yaml
6."pub get" command

However, it turns out to be
`  syncfusion_flutter_datepicker:
    dependency: "direct main"
    description:
      name: syncfusion_flutter_datepicker
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "20.4.48"`
Sigh!

**Comment by Mae623** [comment]
The bug seems linked to dart 3

**Comment by Dev-Muhammad-Junaid** [comment]
> The bug seems linked to dart 3

Yes, Possibly! , Dart and Android studio updates were the only things I did before adding these dependencies..

**Comment by Mae623** [comment]
> > The bug seems linked to dart 3
> 
> Yes, Possibly! , Dart and Android studio updates were the only things I did before adding these dependencies..

I only execute the "pub upgrade" command once 
Maybe upgrade to dart 3 is the only way I can do 
Sigh!

**Comment by unclemeric** [comment]
> 20.4.44

find syncfusion_flutter_datepicker in pubspec.lock, change 20.4.48 to 20.4.44

**Comment by unclemeric** [comment]
> > > > I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> > > > Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`
> > > 
> > > 
> > > hello, I try to use this way, but the pub get give me 20.4.48, even I execute the "flutter clean" command first. Is there anything I can do?
> > 
> > 
> > You can remove the library from pubspec.yaml first and paste directly. Also I have added both dependecncies with " "
> 
> Thank you for reply. These are my step below, hope for your look: 1."flutter clean" command 2.delete pubspec.lock file 3.remove 'syncfusion_flutter_datepicker: ^20.4.44' from pubspec.yaml 4."pub get" command 5.add 'syncfusion_flutter_datepicker: ^20.4.44' into pubspec.yaml 6."pub get" command
> 
> However, it turns out to be ` syncfusion_flutter_datepicker: dependency: "direct main" description: name: syncfusion_flutter_datepicker url: "https://pub.flutter-io.cn" source: hosted version: "20.4.48"` Sigh!

find syncfusion_flutter_datepicker in pubspec.lock, change 20.4.48 to 20.4.44

**Comment by Mae623** [comment]
> > > > > I have the same problem. don't use version: ` syncfusion_flutter_datepicker: ^20.4.48`
> > > > > Use like this: ` syncfusion_flutter_datepicker: "20.4.44"`
> > > > 
> > > > 
> > > > hello, I try to use this way, but the pub get give me 20.4.48, even I execute the "flutter clean" command first. Is there anything I can do?
> > > 
> > > 
> > > You can remove the library from pubspec.yaml first and paste directly. Also I have added both dependecncies with " "
> > 
> > 
> > Thank you for reply. These are my step below, hope for your look: 1."flutter clean" command 2.delete pubspec.lock file 3.remove 'syncfusion_flutter_datepicker: ^20.4.44' from pubspec.yaml 4."pub get" command 5.add 'syncfusion_flutter_datepicker: ^20.4.44' into pubspec.yaml 6."pub get" command
> > However, it turns out to be ` syncfusion_flutter_datepicker: dependency: "direct main" description: name: syncfusion_flutter_datepicker url: "https://pub.flutter-io.cn" source: hosted version: "20.4.48"` Sigh!
> 
> find syncfusion_flutter_datepicker in pubspec.lock, change 20.4.48 to 20.4.44

Execute "pub get" again after this change?

**Comment by nzackoya** [comment]
This date picker package has the most amount of bugs. The controller.forward always returns null. There is no way to remove todaySelection from week. No way to set a style for date items, you should reimplement the builder. But after reimplementing the builder, the selection badge doesn't disappear... Come on guys, do something

**Comment by AfiqMutaz** [comment]
This bug is still present tested on **Flutter 3.3.6**, **Dart 2.18.2**, **SfDateRangePicker 21.1.38**. I understand that my Dart SDK is above the recommended SDK version for this package. Hopefully they'll upgrade soon. Thanks.

**Comment by Mae623** [comment]
> This bug is still present tested on **Flutter 3.3.6**, **Dart 2.18.2**, **SfDateRangePicker 21.1.38**. I understand that my Dart SDK is above the recommended SDK version for this package. Hopefully they'll upgrade soon. Thanks.

maybe you could try Dart3

**Comment by Indumathi1195R** [comment]
Regarding Queries: The controller.forward always returns null. There is no way to remove todaySelection from the week. No way to set a style for date items, you should reimplement the builder. But after reimplementing the builder, the selection badge doesn't disappear... Come on guys, do something

As per the shared information, we have checked the controller.forward() was working fine from our end. Also you can remove the todaySelection from the week by using todayTextStyle property. We have a UG documentation for the same. Also we have prepared the sample for the above queries. Please find the sample from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/customizations#month-cell-customization
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatically-change-to-adjacent-dates
https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder

**Sample link:**
  
[cellbuilder.zip](https://github.com/syncfusion/flutter-examples/files/11329119/cellbuilder.zip)

We hope that this helps you. Please let us know if you need further assistance.
