### ISSUE TITLE
SignaturePad: save signature with different color than the one used on screen

### ISSUE THREAD

**Issue by gabrielbertollo** [syncfusion/flutter-examples#731]
I'm trying to implement the signature pad using the colors from my app, but I need to save the signature in black to later use it in a white document. 

Is it possible to save the signature with a different stroke color from the one used in the `strokeColor` parameter?

**Comment by Yuvaraj-Gajaraj** [comment]
You can change the color of the signature from the app color to black with the help of [Image.memory()](https://api.flutter.dev/flutter/widgets/Image/Image.memory.html). Here we have converted the signature pad data into a Uint8List value and displayed this Uint8List data using the [Image.memory](https://api.flutter.dev/flutter/widgets/Image/Image.memory.html) method and set the color property to black. We have shared the sample below for your reference, you can modify it as per your requirement.

Sample: [i435483.zip](https://github.com/syncfusion/flutter-examples/files/10663531/i435483.zip)

**Comment by gabrielbertollo** [comment]
Hey @Yuvaraj-Gajaraj thanks for the reply.

Showing the signature with `Image.memory()` does change its color on the app (and I already do that), the problem I have is that I need the actual signature file to be black when sending it to the API, but in the signature pad widget I need it to be shown in the app color (say green, for example).

What I ended up doing in the method that returns the signature file is converting it to a `ByteData` and manually changing its pixels to black. I'm pasting the code below.
```dart
late dynamic data;

final ui.Image imageData = await signaturePadKey.currentState!
    .toImage(pixelRatio: 1.0);
final ByteData? bytes = await imageData.toByteData(
    format: ui.ImageByteFormat.rawRgba);

if (bytes != null) {
  for (int i = 0; i < bytes.lengthInBytes; i += 4) {
    if (bytes.getUint8(i + 3) != 0) {
      bytes.setUint8(i, 0);
      bytes.setUint8(i + 1, 0);
      bytes.setUint8(i + 2, 0);
    }
  }

  final Completer<ui.Image> completer = Completer<ui.Image>();
  ui.decodeImageFromPixels(
    bytes.buffer.asUint8List(),
    imageData.width,
    imageData.height,
    ui.PixelFormat.rgba8888,
    (ui.Image image) => completer.complete(image),
  );
  data = await completer.future;
  data =
      await data.toByteData(format: ui.ImageByteFormat.png);
  data = data.buffer.asUint8List();
}

Get.back(result: data); // Returns the file to the previous page
```

With this, I can show the `SfSignaturePad`'s signature in the color of the app.

```dart
SfSignaturePad(
 key: signaturePadKey,
 maximumStrokeWidth: 10.0,
 minimumStrokeWidth: 2.0,
 strokeColor: Get.theme.colorScheme.onSurface,
),
```

I wonder if there is an easier way to show the signature on the `SfSignaturePad` in a different color than the generated file.

**Comment by LavanyaGowtham2021** [comment]
Currently there is no direct way to achieve your requirement, kindly use the above shared codes.
