### ISSUE TITLE
date_picker.dart:7596:37: Error: The argument type 'ScrollableState?'

### ISSUE THREAD

**Issue by bastYYJ** [syncfusion/flutter-examples#732]
`Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7596:37: Error: The argument type 'ScrollableState?' can't be assigned to the parameter type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
        scrollableState: Scrollable.of(context),
                                    ^
/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7611:40: Error: A value of type 'ScrollableState?' can't be assigned to a variable of type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
        ..scrollableState = Scrollable.of(context)
                                       ^
/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_datepicker-20.4.48/lib/src/date_picker/date_picker.dart:7665:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/C:/Program%20Files/flutter_windows_3.3.7-stable/flutter/packages/flutter/lib/src/rendering/viewport.dart').
  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);
                                                                      ^`

**Comment by ahmadhassan7** [comment]
+1

**Comment by rsanjuan87** [comment]
same here

**Comment by saiganesh-sakthivel** [comment]
Hi @bastYYJ,

Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample481972792

Output: https://www.syncfusion.com/downloads/support/directtrac/general/ze/output970198259

Please be aware that the version of SfDateRangePicker and SfCalendar used in this test is 20.4.48 and Flutter version is 3.7.0.

**Comment by rsanjuan87** [comment]
It seems to be an incompatibility bug with previous versions of flutter.

 I have solved with https://github.com/syncfusion/flutter-examples/issues/730#issuecomment-1413788831

> Hi @bastYYJ,
> 
> Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.
> 
> Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample481972792
> 
> Output: https://www.syncfusion.com/downloads/support/directtrac/general/ze/output970198259
> 
> Please be aware that the version of SfDateRangePicker and SfCalendar used in this test is 20.4.48 and Flutter version is 3.7.0.
> 
> We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.

**Comment by bastYYJ** [comment]
> solved here [#730 (comment)](https://github.com/syncfusion/flutter-examples/issues/730#issuecomment-1413788831)

I tried, but it didn't work

**Comment by bastYYJ** [comment]
> Hi @bastYYJ,
> 
> Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.
> 
> Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample481972792
> 
> Output: https://www.syncfusion.com/downloads/support/directtrac/general/ze/output970198259
> 
> Please be aware that the version of SfDateRangePicker and SfCalendar used in this test is 20.4.48 and Flutter version is 3.7.0.
> 
> We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.

I upgraded Flutter version and it is now running normally
