### ISSUE TITLE
Error when the syncfusion flutter calendar plugin is updated to 20.4.48

### ISSUE THREAD

**Issue by usman-ghani-khan** [syncfusion/flutter-examples#736]
When I update SFCalendar to version 20.4.48, I get this error:
`/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.4.48/lib/src/calendar/sfcalendar.dart:10776:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
`

**Comment by saiganesh-sakthivel** [comment]
Hi @usman-ghani-khan,

Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/calendar_sample2038385393

Output: https://www.syncfusion.com/downloads/support/directtrac/general/ze/calendar_output.png1237470043

Please be aware that the version of SfCalendar used in this test is 20.4.48 and Flutter version is 3.7.0.

We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.

**Comment by ekrmh** [comment]
Hi @saiganesh-sakthivel,

This issue is reproducible with the following versions. Currently, I can't upgrade flutter to the latest version due to some bugs. How can I use 20.4.48 with Flutter version 3.3.10?

    • Flutter version 3.3.10 on channel stable 
    • Dart version 2.18.6

**Comment by 17779896606** [comment]
@ekrmh you can try it as follow
  syncfusion_flutter_datepicker: 20.4.44
  syncfusion_flutter_calendar: 20.4.44
because I am try it as previous
• Flutter version 3.3.6 on channel stable 
• Dart version 2.18.2

**Comment by LavanyaGowtham2021** [comment]
We have resolved the issue already and so we kindly request you to upgrade the latest version.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need any other assistance on this.
