### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by Mtharwat95** [syncfusion/flutter-examples#738]
../../../../FlutterSKD/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_calendar-20.4.49/lib/src/calendar/sfcalendar.dart:10776:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../../../FlutterSKD/flutter/packages/flutter/lib/src/rendering/viewport.dart').
  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);
                                                                      ^
../../../../FlutterSKD/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.49/lib/src/date_picker/date_picker.dart:7596:37: Error: The argument type 'ScrollableState?' can't be assigned to the parameter type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../../../FlutterSKD/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
        scrollableState: Scrollable.of(context),
                                    ^
../../../../FlutterSKD/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.49/lib/src/date_picker/date_picker.dart:7611:40: Error: A value of type 'ScrollableState?' can't be assigned to a variable of type 'ScrollableState' because 'ScrollableState?' is nullable and 'ScrollableState' isn't.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('../../../../FlutterSKD/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
        ..scrollableState = Scrollable.of(context)
                                       ^
../../../../FlutterSKD/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.4.49/lib/src/date_picker/date_picker.dart:7665:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../../../FlutterSKD/flutter/packages/flutter/lib/src/rendering/viewport.dart').
  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);

**Comment by MuniappanSubramanian** [comment]
Based on the instructions provided, we attempted to replicate the reported issue but were unable to do so. A sample has been created and is attached, including the output from testing.

Please be aware that the version of **SfDateRangePicker** and **SfCalendar** used in this test is **20.4.49** and **Flutter version is 3.7.0**.

We suggest updating to the latest version of Flutter and re-testing the issue. If the problem persists, please inform us.

[sample.zip](https://github.com/syncfusion/flutter-examples/files/10693734/sample.zip)
[output.zip](https://github.com/syncfusion/flutter-examples/files/10693735/output.zip)

**Comment by jaxnz** [comment]
We have the same issue on Flutter 3.3.10 - last release before 3.7.

As we are waiting for 3.7 issues to be ironed out, can you provide the latest version of `syncfusion_flutter_datepicker` that is supported on v3.3.10

**Comment by heavenlyteam** [comment]
I had the same issue.
`flutter upgrade` solved it

But I can confirm that the bug can be replicated on the 3.3.x flutter version.

**Comment by anilthapa1939** [comment]
> We have the same issue on Flutter 3.3.10 - last release before 3.7.
> 
> As we are waiting for 3.7 issues to be ironed out, can you provide the latest version of `syncfusion_flutter_datepicker` that is supported on v3.3.10

+1

**Comment by komiljonovshohjahon** [comment]
The error occurs when the flutter version on one's computer does not fit the the version of the package.
My flutter version is  3.3.10 and I fixed the issue by adding these lines in pubspec.yaml.
```
dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^20.4.48
  syncfusion_flutter_datepicker: ^20.4.48

dependency_overrides:
  syncfusion_flutter_calendar: "20.2.43"
  syncfusion_flutter_datepicker: "20.2.43"
```

**Comment by Indumathi1195R** [comment]
komiljonovshohjahon,

Thanks for the update. Please get in touch with us if you required further assistance.

**Comment by jokermt235** [comment]
> The error occurs when the flutter version on one's computer does not fit the the version of the package. My flutter version is 3.3.10 and I fixed the issue by adding these lines in pubspec.yaml.
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   syncfusion_flutter_calendar: ^20.4.48
>   syncfusion_flutter_datepicker: ^20.4.48
> 
> dependency_overrides:
>   syncfusion_flutter_calendar: "20.2.43"
>   syncfusion_flutter_datepicker: "20.2.43"
> ```

Yes this is working variant
