### ISSUE TITLE
 syncfusion_flutter_pdf pakage does not genrate certificate

### ISSUE THREAD

**Issue by Omercodiea** [syncfusion/flutter-examples#743]
E/flutter (10148): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method viewPdf on channel launchFile)
E/flutter (10148): #0      MethodChannel._invokeMethod
platform_channel.dart:294
E/flutter (10148): <asynchronous suspension>
E/flutter (10148):

pakage used 

syncfusion_flutter_pdf: ^20.4.51

error genratred on when genratingthe certificate

**Comment by irfanajaffer** [comment]
We've included native code in our Flutter SB sample to enable users to save and view PDF documents. Utilizing this native code can address the issue at hand. Another suggestion would be to utilize the [open_file](https://pub.dev/packages/open_file) package to view any PDF files generated.



For more information on this, please refer to the following UG and KB documents.

https://www.syncfusion.com/kb/11330/how-to-create-a-pdf-file-in-syncfusion-flutter-pdf-library
https://help.syncfusion.com/flutter/pdf/getting-started
