### ISSUE TITLE
not show digital signature in pdfview

### ISSUE THREAD

**Issue by hung-hust-97** [syncfusion/flutter-examples#749]
[CIST_BNT_signed_khong_doc_duoc.pdf](https://github.com/syncfusion/flutter-examples/files/10992646/CIST_BNT_signed_khong_doc_duoc.pdf)
When I use lib, most pdf not show the digital signature. Example above

**Comment by deepika134** [comment]
Hi hung-hust-97,

At present we do not have support for "Digital Signature". We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following link for track the status of the feature,
https://www.syncfusion.com/feedback/26234/support-for-digital-signature 

We have a workaround for show the existing annotation in Flutter PDF Viewer. Kindly refer the following link,
https://www.syncfusion.com/kb/13014/how-to-preserve-the-existing-annotation-in-flutter-pdf-viewer-sfpdfviewer 

Regards,
Deepika R

**Comment by deepika134** [comment]
Hi hung-hust-97,

At present we do not have support for "Digital Signature". We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following link for track the status of the feature,
https://www.syncfusion.com/feedback/26234/support-for-digital-signature

We have a workaround for show the existing annotation in Flutter PDF Viewer. Kindly refer the following link,
https://www.syncfusion.com/kb/13014/how-to-preserve-the-existing-annotation-in-flutter-pdf-viewer-sfpdfviewer

Regards,
Deepika R
