### ISSUE TITLE
Gradient for donut chart

### ISSUE THREAD

**Issue by MobileMon** [syncfusion/flutter-examples#75]
How can I apply a gradient to the donut chart?

**Comment by dharanidharandharmasivam** [comment]
Hi @MobileMon ,

Thanks for your interest Syncfusion chart widget. As of now, we have provided gradient support for cartesian chart types, and already logged a feature request for circular chart types. The feature will be available in any of our upcoming releases and you can track the status of the feature from our feedback portal.

Feedback Portal:  https://www.syncfusion.com/feedback/8229 

Please upvote this. Based on the number of upvotes and the priority of other new features, we will consider and implement it. We will update in the feedback, once it got completed.

Thanks,
Dharani.

**Comment by MobileMon** [comment]
Any update on this?
