### ISSUE TITLE
SfDateRangePicker - Disable animation when changing view

### ISSUE THREAD

**Issue by caiovisk** [syncfusion/flutter-examples#752]
Hi There,

Is there a way to disable the animation when switching the views (months) via Navigation Arrows? or disable the animation all together?

**Comment by MuniappanSubramanian** [comment]
@caiovisk 

The current implementation of the Flutter DateRangePicker does not have support to disable the animation when switching the views.

Please let us know if you need any further assistance. As always, we are happy to help you out.
