### ISSUE TITLE
calculatePointToPixel returns null

### ISSUE THREAD

**Issue by barilki** [syncfusion/flutter-examples#754]
```
          final CartesianChartPoint<dynamic> chartPoint =

                      CartesianChartPoint<dynamic>( 0, double.parse((symbol?.bid ?? 0.0).toStringAsFixed((symbol?.digits ?? 0).toInt())));

                      pointLocation = candleController?.pointToPixel(chartPoint); <--- Return null
```

and then it display the chart.

the problem is with this method inside package:
```

  final ChartAxisRendererDetails xAxisDetails =

      seriesRendererDetails.xAxisDetails!; <---- Return null
```

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked the shared code snippet and found that you have called the [pointToPixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method inside the builder function of the StoreConnector, so we have tried the same and found that the [point](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html)[ToP](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html)[ixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method gets called before the chart rendering gets completed, in this state chart properties are not even initialized. So please try to call the [point](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html)[ToP](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html)[ixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method after the chart rendering gets completed. This will ensure that the necessary chart detail is available for the conversion to be performed accurately.
