### ISSUE TITLE
Custom sort for SfCalendar appointments

### ISSUE THREAD

**Issue by NaarGes** [syncfusion/flutter-examples#755]
Hi,

I need to sort my appointments based on my "view priority" field that exist in my appointment class. Is it supported?

**Comment by MuniappanSubramanian** [comment]
As per the implementation of Flutter Calendar, the appointments in the calendar will be ordered based on their start time and end time in the view. Currently, there is no support to sort appointments to display them using the custom property.

Please let us know if you need any further updates. As always, we are happy to help you out.

**Comment by NaarGes** [comment]
Thanks for reply,
What about the all day event? And is it gonna be implemented eventually or not?

**Comment by Indumathi1195R** [comment]
NaarGes,

As per the last update, there is no support to sort the all-day appointments to display them using the custom property. We hope that this information helps you. Please let us know if you need any further updates.
