### ISSUE TITLE
Feature request : Calendar view - Half hour slot

### ISSUE THREAD

**Issue by QuentinSc** [syncfusion/flutter-examples#757]
Hello,

Could be great to be able to select half hour slot and not only full hour

Thank you

**Comment by MuniappanSubramanian** [comment]
The current implementation of the Flutter Calendar does not have support for selecting half-hour time slots in the timeslot views.

But you can customize the interval of timeslots (30 minutes) in all the timeslots views by using the timeInterval property of TimeSlotViewSettings in the calendar. Refer to our UG documentation to know more details about time interval customization support in the calendar,

https://help.syncfusion.com/flutter/calendar/timeslot-views#change-time-interval
