### ISSUE TITLE
Interactive Annotation

### ISSUE THREAD

**Issue by zahidch052** [syncfusion/flutter-examples#759]
Hi, can annotations be draggable? For example. clickable, draggable, resizeable?

I placed a button inside annotations and its on-click is not working,

**Comment by Yuvaraj-Gajaraj** [comment]
Currently, we do not have interaction support for the annotation in the chart and we have already logged a feature request in our feedback portal it will be implemented and included in any of our upcoming releases. We have also shared the feedback link below you can track the status of the feature implementation here.



Feedback, https://www.syncfusion.com/feedback/42680/provide-gesture-detection-support-for-the-annotation

**Comment by zahidch052** [comment]
Thank you very much for the feedback.
is there any other way to draw some objects on the chart like an arrow, a
line, or a fork as required by forex trading charts?

**Comment by LokeshPalani** [comment]
You can achieve your requirement with the help of [plotBands](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/plotBands.html) property. By using [plotBands](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/plotBands.html) property, you can draw the line in the chart. We have shared the related UG Documentation below for your reference.



UG,
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#plot-bands
