### ISSUE TITLE
Lost X axis marks on zooming

### ISSUE THREAD

**Issue by davidBarbieri** [syncfusion/flutter-examples#76]
Hi, there is a problem while zooming.

in your Pinch Zooming example, when you zoom in at a certain point you lose all the X axis marks, the plot also grows to take up the place left by the missing labels.

Would be nice to be able to have a fixed amount of ticks along the axis and only the values changing, or at least have the rightmost and leftmost marks to stay and have a correct value of the zoomed area.

Thanks a lot

David

**Comment by dharanidharandharmasivam** [comment]
Hi @davidBarbieri ,

Greetings from Syncfusion. The reported scenario is a bug and it has been already fixed and included for the vol 4 sp1 release. To fix the issue, kindly upgrade your chart widget package from below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/17.4.46 

Thanks,
Dharani.
