### ISSUE TITLE
SfCartesianChart selection mode display abnormality.

### ISSUE THREAD

**Issue by ShineYang** [syncfusion/flutter-examples#760]
Hi team,
When I was using SfCartesianChart to implement a single selection function, I found that the style couldn't be maintained in the normal state after selection, and there was also a delay of about 0.5 seconds between tap gesture and triggering.

![alt text](https://i.ibb.co/VSp9WqR/8841680711366-pic.jpg "sample")

**Comment by Yuvaraj-Gajaraj** [comment]
We would like to let you know that currently, we don’t have support for applying gradient color to the selected segment. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.



We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.



Feedback, https://www.syncfusion.com/feedback/42722/provide-a-support-for-gradient-selection-color
