### ISSUE TITLE
SfCalendar: Customer appointment order in same resource

### ISSUE THREAD

**Issue by tony21177** [syncfusion/flutter-examples#761]
Can SfCalendar support custome appointment order in the same resource block?
In my application scenario,the appointmement may span multiple days
for example,I can't arrange the 3 appointment top to down order
![image](https://user-images.githubusercontent.com/38462595/230251731-8e789563-d67c-4765-94ed-e3742d8abb55.png)

**Comment by MuniappanSubramanian** [comment]
As per the implementation of Flutter Calendar, the appointments in the calendar will be ordered based on their start time and end time in the view. Currently, there is no support to sort appointments to display them at the top or bottom

Please let us know if you need any further updates. As always, we are happy to help you out.

**Comment by Exotic308** [comment]
If we could manage order no matter the start time, it would be very useful.
