### ISSUE TITLE
SfCalendar iOS: Calendar view menu closes immediately in dev environment.

### ISSUE THREAD

**Issue by iandppl** [syncfusion/flutter-examples#762]
Hi,

When building the app in iOS developer mode with xCode simulator, I am not able to change the view of the calendar as it closes when the Calendar view menu button is clicked.

Flutter version:
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (7 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1

Syncfusion Calendar version: ^20.2.49

![image](https://user-images.githubusercontent.com/75239750/231088991-2f4f2b20-d037-4d23-b357-db972f5b75a8.png)

**Comment by MuniappanSubramanian** [comment]
According to the instructions provided, we followed the steps to check the reported issue but were unable to replicate it on our end. We conducted tests by tapping the menu button and changing the calendar view and it is working fine from our end. We have prepared a sample, which is attached for your reference.

Please be aware that the version of SfCalendar and SfCalendar used in this test is **21.1.39** and the Flutter version is **3.7.8.**

We suggest updating to the latest version of Flutter and re-testing the issue. If the issue persists, please provide us with the following details:

- A video demonstrating the issue you are facing.
- The code snippets for your calendar implementation.
- A reproducible sample that demonstrates the issue.
- Share the iPhone and iPhone simulator version details


Providing these details would be helpful for us to investigate the issue and provide you with a solution as soon as possible.

[Sample.zip](https://github.com/syncfusion/flutter-examples/files/11208351/Sample.zip)
[output.zip](https://github.com/syncfusion/flutter-examples/files/11208352/output.zip)

**Comment by iandppl** [comment]
Hi @MuniappanSubramanian,

Here is the code snippet and a video showing the error:

`SfCalendar(
      cellEndPadding: 0,
      appointmentBuilder: appointmentBuilder,
      allowedViews: CalendarConstants.ALLOWED_VIEWS,
      showDatePickerButton: true,
      selectionDecoration: BoxDecoration(
        color: Colors.transparent,
        border: Border.all(color: Colors.red, width: 1),
        shape: BoxShape.rectangle,
      ),
      controller: calendarController,
      dataSource: _calendarDataSource,
      showNavigationArrow: true,
      monthViewSettings: const MonthViewSettings(
        appointmentDisplayMode: MonthAppointmentDisplayMode.appointment,
      ),
      onViewChanged: onViewChanged,
      timeSlotViewSettings: const TimeSlotViewSettings(),
)`

https://user-images.githubusercontent.com/75239750/234458655-a6a8d85d-9718-438b-96c6-8ae58ff40b28.mov

**Comment by Indumathi1195R** [comment]
As per the shared information, we have checked the mentioned issue “Calendarview option closed in iOS devices” from our end. It was working fine as expected from our end. We have prepared a simple sample and video for the same. Also please find the tested details below.


- Flutter Calendar version: 21.1.41
-  iPhone 14 pro max with 16.2 
- Flutter version: Stable 3.7.12


If possible can you please check the sample and let us know still if you are facing same issue, please share the below details to us.

- Replicate the issue in the shared sample.
- Code snippet
- Issue replication scenario

[SampleAndVideo.zip](https://github.com/syncfusion/flutter-examples/files/11374072/SampleAndVideo.zip)

It would be helpful for us to analyze and provide you a solution at the earliest.
