### ISSUE TITLE
Sfcalendar is not showing events on the next or previous month while dragging

### ISSUE THREAD

**Issue by NaarGes** [syncfusion/flutter-examples#763]
Hi,

When scrolling between months in month view, we cannot see the events on the coming page while dragging.
It seems that there are no events on the other page while there is data there, but not getting displayed

This is what I mean:

https://user-images.githubusercontent.com/15056339/231451539-84dafea3-e3cd-4314-b4c4-55db966e0e5f.mp4

This is the expected behavior:

https://user-images.githubusercontent.com/15056339/231452748-800beb2e-89f5-426f-9ce2-ee3cf37309e4.mp4

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
