### ISSUE TITLE
In the month view, only the connected month appears as

### ISSUE THREAD

**Issue by SerdarYildiz06** [syncfusion/flutter-examples#764]
![date_picker](https://user-images.githubusercontent.com/72278145/232265296-071cd2b4-1b4a-45c2-82dd-17b4cce18799.png)

I'm sorting the months vertically, but I want it to be in a single month, not 2 in which month it is. How can I do it

**Comment by Indumathi1195R** [comment]
Serdar,

Your requirement can be achieved by using the **navigationMode** property value as **scroll** of the date picker. By using this property, you can show the appropriate month name in the header of vertical picker. Please find the code snippet and screenshot for the same.

**Code snippet:**
```SfDateRangePicker(
navigationMode: DateRangePickerNavigationMode.scroll,
enableMultiView: true,
navigationDirection: DateRangePickerNavigationDirection.vertical,
)),

**Screenshot:**


![Screenshot_20230417-115704](https://user-images.githubusercontent.com/54974849/232413227-3d3db73c-cf45-4d0d-9c20-1b2376646941.jpg)


We hope that this helps you. Please let us know if this is not your requirement. It would be helpful for us to analyze and provide you a solution at the earliest.

**Comment by SerdarYildiz06** [comment]
Thanks
