### ISSUE TITLE
Allow only specified range of views (DateRangePickerView)

### ISSUE THREAD

**Issue by arberzeka1** [syncfusion/flutter-examples#766]
Hi!

Right now the package has the options to set the view to a specific _DateRangePickerView_ and also allow navigation or not.

What we need, if its possible, is to allow navigations but not in all views, just on specific views, example:
allow navigation only on these views:
[ _DateRangePickerView.year_, _DateRangePickerView.decade_ ]

I have been using this package for years and till now i haven't found a configuration that does this, please let me know if there is any solution for this or not?

**Comment by Indumathi1195R** [comment]
As of now, SfDateRangePicker doesn’t have support to Allow only specified picker views. We have logged the feature request for the same. We will implement this feature in any of our upcoming release. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/43045/provide-support-to-allow-specific-picker-views-in-the-flutter-date-range 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.
