### ISSUE TITLE
RangeSlider custom thumbRadius  center not aligned

### ISSUE THREAD

**Issue by jzllovecat** [syncfusion/flutter-examples#767]
![b2aa51cd0f04aa7d232dffda80947a97](https://user-images.githubusercontent.com/19180995/233030194-30b0479a-ac92-4afd-ba07-009f7fd96fba.jpg)
`SfRangeSliderTheme(
      data: SfRangeSliderThemeData(
          inactiveDividerColor: Colors.white,
          activeDividerColor: Colors.white,
          activeDividerStrokeWidth: 1,
          activeDividerStrokeColor: activeColor,
          inactiveDividerStrokeWidth: 1,
          inactiveDividerStrokeColor: inactiveColor,
          activeDividerRadius: 4,
          inactiveDividerRadius: 4,
          activeTrackColor: activeColor,
          activeTrackHeight: 4,
          inactiveTrackColor: Colors.white,
          inactiveTrackHeight: 4,
          thumbStrokeWidth: 1,
          thumbColor: activeColor,
          thumbStrokeColor: activeColor,
          thumbRadius: 6,
          activeLabelStyle:
              const TextStyle(color: Color(0xff333333), fontSize: 10),
          inactiveLabelStyle: TextStyle(color: inactiveColor, fontSize: 10),
          overlayColor: Colors.transparent),
      child: SfRangeSlider(
          min: 1,
          max: 8,
          interval: 1,
          values: widget.teacherTimeOptions.hourRangeSliderValues,
          onChanged: (SfRangeValues values) {
            setState(() {
              widget.teacherTimeOptions.hourRangeSliderValues = values;
            });
          },
          stepSize: 1,
          showLabels: true,
          showDividers: true,
          thumbShape: const _ThumbShape(true),
          labelFormatterCallback: (_, value) {
            return '${value}h';
          }),
    )`

qustion at 'thumbRadius: 6,'   remove this will be ok,but the thumb is so bigger

and how to realization this
![16818972011182](https://user-images.githubusercontent.com/19180995/233035509-3b161508-6861-413e-93e3-8cfca4c6ef9b.png)
thumb bottom always show tips

**Comment by LokeshPalani** [comment]
Hi @jzllovecat,

You can achieve your requirements with the help of the [dividerShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/dividerShape.html) property in the slider. By using the [dividerShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/dividerShape.html) property, you can create a custom divider with a specific shape and size. We have shared a code snippet and User Guide documentation below for your reference. Please get back to us if you need any further assistance.

**Code snippet:**

```
SfRangeSlider(
            min: 1,
            max: 10,
            interval: 1,
            values: _values,
            dividerShape: _DividerShape(),
            onChanged: (SfRangeValues values) {
              setState(() {
                _values = values;
              });
            },
            stepSize: 1,
            showLabels: true,
            showDividers: true,
            labelFormatterCallback: (_, value) {
              return '${value}h';
            },
          ),

class _DividerShape extends SfDividerShape {
  @override
  void paint(PaintingContext context, Offset center, Offset? thumbCenter,
      Offset? startThumbCenter, Offset? endThumbCenter,
      {required RenderBox parentBox,
      required SfSliderThemeData themeData,
      SfRangeValues? currentValues,
      dynamic currentValue,
      required Paint? paint,
      required Animation<double> enableAnimation,
      required TextDirection textDirection}) {
        bool isActive;

    switch (textDirection) {
      case TextDirection.ltr:
        isActive = center.dx <= thumbCenter!.dx;
        break;
      case TextDirection.rtl:
        isActive = center.dx >= thumbCenter!.dx;
        break;
    }
    context.canvas.drawCircle(
        center,
        // Divider radius
        2,
        Paint()
          ..isAntiAlias = true
          ..style = PaintingStyle.fill
          ..color = isActive ? themeData.activeTrackColor! : Colors.grey.shade300);
  }
}
```
UG,
https://help.syncfusion.com/flutter/slider/shapes#divider-shape

Regards,
Lokesh.

**Comment by jzllovecat** [comment]
I solved the problem，thanks！

**Comment by jzllovecat** [comment]
the “currentValue” and “thumbCenter” is null,so i can only use `Offset offset;
    if (center.dx-(startThumbCenter?.dx??0)==4.0) {
      offset = Offset(center.dx-4.0, center.dy);
    }else if (center.dx-(endThumbCenter?.dx??0)==-4.0) {
      offset = Offset(center.dx+4.0, center.dy);
    }else{
      offset = center;
    }`

**Comment by LokeshPalani** [comment]
Most Welcome. Kindly get back to us if you have further queries. We are always happy to assist you.

**Comment by jzllovecat** [comment]
Thank you to your team for providing so many great widgets that will make a lot of developers' jobs easier
