### ISSUE TITLE
[syncfusion_flutter_charts]	X-axis scrolling in infinite_scrolling case when scrolling right to load more? How does the great God solve it?

### ISSUE THREAD

**Issue by wuzeqiang2030** [syncfusion/flutter-examples#769]

**Comment by oxiangyang** [comment]
I get the same question, I hope the author can provide an answer.

**Comment by LavanyaGowtham2021** [comment]
Hi @wuzeqiang2030,

We kindly request to upgrade the latest charts version, if you still face an issue with latest version we request you to share us with more information on your requirement in detail along with screenshots/screenrecordings so that it will help us assist you in a better way.
