### ISSUE TITLE
How to hide Today Button when showDatePickerButton is true

### ISSUE THREAD

**Issue by quocviet1996** [syncfusion/flutter-examples#770]
Hi everyone, my calendar have a header like this, with arrow navigator, dropdown icon next to the header title, and user can click on the title to choose the month year calendar.
But if i'm using showDatePickerButton, everything is perfect except Today Button appear?? And if i don't use showDatePickerButton, i can't have dropdown icon and can't click on the title header to select the Month Year calendar.

I'm using SfCalendar with month calendar

![image](https://user-images.githubusercontent.com/48380821/233428359-152fdef3-1bde-4e45-a9bc-ca3a61c60ccc.png)

**Comment by Indumathi1195R** [comment]
As per the shared information, we have checked and your requirement is “Hide and show the Today button in Flutter calendar” and we are already logged the feature request for the same. We will implement this feature in our 2022 Volume 2 release, which is expecetd to rolled out by end of June 2023 and let you know once feature is implemented. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below mentioned link. 

Feedback link:
https://www.syncfusion.com/feedback/34053/provide-support-to-hide-and-show-the-today-icon-button-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

**Comment by quocviet1996** [comment]
Appreciate it, one more thing, when can we change the appointment size for the dot indicator, thanks
![image](https://user-images.githubusercontent.com/48380821/235044461-b2656fb9-e83f-400e-b46c-a5a8fe4819bd.png)

**Comment by IndumathiR-1995** [comment]
We are glad to announce that our 2023 Volume 2 Main Release **V22.1.34** is rolled out with the “**Hide and show the Today button in Flutter calendar**” feature. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

**Release notes link:**
https://help.syncfusion.com/flutter/release-notes/v22.1.34?type=all#calendar 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Regarding Query: when can we change the appointment size for the dot indicator,**
As per the current implementation, there is no support to change the dot indicator size in the Flutter calendar. By using the  monthCellBuilder you can customize cell with appointment as per your requirement. We have UG and KB documentations for the same. Please find the documentations from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder 

**KB link:**
https://support.syncfusion.com/kb/article/10747/how-to-customize-the-month-cell-with-appointment-count-in-the-flutter-calendar
https://support.syncfusion.com/kb/article/10707/how-to-customize-the-month-cell-based-on-the-appointment-using-builder-in-the-flutter

Regards,
Indumathi R
