### ISSUE TITLE
Custom day format

### ISSUE THREAD

**Issue by mszakacz** [syncfusion/flutter-examples#771]
Hello,
It will be nice to custom a day format in month view.
For example in polish language the default names (shortcuts) of the weekdays are:
` ['PON.', 'WT.', 'ŚR.', 'CZW.', 'PT.', 'SOB.', 'NIEDZ.']`
as you see the name of the last day (which is Sunday) is very long (6 characters).
It will be nice to be able to make it shorter.
Two ideas:
1) Parameter how long the shortcut of the weekday name can be.

2) Method that takes the weekday <int> and returns the String
e.g: 
```
dayFormat: (int day) {
    if(day == 7) return 'S';
}
```

**Comment by ibecerramtz** [comment]
Hello, I currently have the same problem, have you solved it? In my case I want to use the abbreviations of "DateFormat().dateSymbols.NARROWWEEKDAYS" with a single character, but the "dayFormat" parameter only takes a String and not a List<String>.

**Comment by Indumathi1195R** [comment]
As per the shared information, we have checked and your requirement is “**Customize the day format of the view header by the provided language of the Flutter Calendar**”. By hiding default headers (headerHeight and viewHeaderHeight value as 0) and adding the custom headers you can achieve this requirement. We have prepared a simple sample for the same. Please find the sample from the following link. Also, we have KB documentation for custom header localization. Please find the documentation from the following link.

**KB link:**
https://support.syncfusion.com/kb/article/11294/how-to-localize-the-custom-headers-text-in-the-flutter-calendar-sfcalendar
 
[viewheader_locale.zip](https://github.com/syncfusion/flutter-examples/files/11371752/viewheader_locale.zip)

We hope that this helps you. Please let us know if you need further assistance.
