### ISSUE TITLE
Allow changing selected row text color in SfDataGrid

### ISSUE THREAD

**Issue by PabloPadilla5** [syncfusion/flutter-examples#772]
Currently in `SfDataGridThemeData` there's an option to change the background of a selected row with the `selectionColor `parameter, but there doesn't seem to be an option to change the text color of that selected row, which makes the text illegible if you want to use a darker color for the background and the text color of the rest of the rows are dark.

I attach an example:
![image](https://user-images.githubusercontent.com/42223362/235367762-16d8f1e0-add9-4461-8b3f-55fd18211588.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @PabloPadilla5,

As of now, SfDataGrid doesn’t have support to change the text color when selecting the row. However, we have a workaround that you can use to achieve your requirement. You can get the selected rows from the **DataGridController.selectedRows** property, and the **DataGridSource.buildRow** method will be called for the respective row when selecting it. In this method, you can check whether the corresponding row is a selected row or not. If it is a selected row, then you can set the text color directly from the sample code. For more information, please refer to the following code snippet and sample.

```dart
DataGridController dataGridController = DataGridController();

class SfDataGridDemoState extends State<SfDataGridDemo> {
  late EmployeeDataSource _employeeDataSource;
  List<Employee> _employees = <Employee>[];

  @override
  void initState() {
    super.initState();
    _employees = getEmployeeData();
    _employeeDataSource = EmployeeDataSource(_employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter SfDataGrid')),
      body: SfDataGridTheme(
        data: SfDataGridThemeData(selectionColor: Colors.purple),
        child: SfDataGrid(
            controller: dataGridController,
            source: _employeeDataSource,
            selectionMode: SelectionMode.multiple,
            columns: getColumns,
            columnWidthMode: ColumnWidthMode.fill),
      ),
    );
  }
}

```
**In DataGridSource class:**

```dart
class EmployeeDataSource extends DataGridSource {

…

  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    Color selectedRowTextColor = Colors.amber;

    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
          alignment: Alignment.center,
          child: Text(
            dataGridCell.value.toString(),
            style: TextStyle(
                color: dataGridController.selectedRows.contains(row)
                    ? selectedRowTextColor
                    : null),
          ));
    }).toList());
  }
}

```


https://user-images.githubusercontent.com/93904422/235625813-fb44a6d6-6fc3-4563-904b-fa7da5896497.mp4

**Sample Link: [sample.zip](https://github.com/syncfusion/flutter-examples/files/11371541/sample.zip)**

Regards,
Tamilarasan

**Comment by PabloPadilla5** [comment]
Thank you very much, this will do it, i'll close this issue
