### ISSUE TITLE
SfDateRangePicker: how to show the arrow down icon after the year-month string

### ISSUE THREAD

**Issue by rraayy** [syncfusion/flutter-examples#775]
Hi, Thanks for the cool staff about this library. I have a question about the SfDateRangePicker.
I saw the SfCalendar can  have an arrow down icon after "May 2023 " at the top bar, 
but the SfDateRangePicker don't have the arrow down icon. 
Is there anyway to add the arrow down icon?
<img width="367" alt="截圖 2023-05-09 下午11 15 30" src="https://github.com/syncfusion/flutter-examples/assets/4694572/07a1b8ad-d32d-4364-a7d6-bc39a8586c12">

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the calendar implementation, we have integrated the picker control in the calendar control to quickly navigate to the views and dates. So, the down arrow was enabled when the showDatePickerButton property value was true in the Flutter Calendar. But in the date range picker, there is no option to show the down arrow and you can navigate to the other views by tapping the header of the current view. By using the custom header, you can add the required icons in the header. We have KB documentation for the same. 


**KB link:**

https://support.syncfusion.com/kb/article/10373/how-to-customize-the-header-in-the-flutter-multi-date-range-picker-sfdaterangepicker 

https://support.syncfusion.com/kb/article/10526/how-to-replace-the-view-header-with-the-custom-widget-in-flutter-date-range-picker 


We have UG documentation for quick view navigation in Calendar. Please find the documentation for the same.


**UG link:**

https://help.syncfusion.com/flutter/calendar/date-navigations#show-date-picker

https://help.syncfusion.com/flutter/calendar/date-navigations#allow-view-navigation 

https://help.syncfusion.com/flutter/calendar/date-navigations#allowed-views 

**Pub documentation link:**

https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/showDatePickerButton.html

We hope that this information helps you. Please let us know if you need further assistance.


Regards,
Indumathi R

**Comment by rraayy** [comment]
OK!Thanks!
