### ISSUE TITLE
SfCalendar : Horizontal Resource view 

### ISSUE THREAD

**Issue by MohamedAbd0** [syncfusion/flutter-examples#776]
how can group the appointments and time regions arranged in a column-wise order based on the allocated resource in the timeline views.
I want to make the Resource view horizontal, not vertical, Replace the location of the resource with the location of the time

<img width="1437" alt="Screenshot 2023-05-10 at 11 38 14 AM" src="https://github.com/syncfusion/flutter-examples/assets/32939129/70e8a4de-c3e3-454d-8fd2-8c09e594148c">

**Comment by IndumathiR-1995** [comment]
Hi,

We have logged the feature request for the “Horizontal resource view support in the Flutter event calendar (SfCalendar)”. We will implement this feature in any of our upcoming releases.

Now you can track the status of the feature report by using the following link.

**Feature link:**
https://www.syncfusion.com/feedback/15067/horizontal-resource-grouping-support-in-the-flutter-event-calendar-sfcalendar 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.


We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.


If you have any more specifications/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count. 


Regards,
Indumathi R

**Comment by MohamedAbd0** [comment]
Thanks

**Comment by teneon** [comment]
Hi there,

it was the first thing that i have noticed when i started exploring your calendar package, that horizontal resources view is missing. I can see this is also currently the most requested feature on the feature link you have provided. Please add it as soon as possible :-)

Best regards,
Neon
