### ISSUE TITLE
[datepicker] Not compatible with intl v0.17.0

### ISSUE THREAD

**Issue by ARASHz4** [syncfusion/flutter-examples#777]
syncfusion_flutter_datepicker v21.2.4 is not compatible with intl v0.17.0
Because flutter_localizations SDK depends on intl v0.17.0 and i can't update to intl v0.18.0

`
Because syncfusion_flutter_datepicker >=21.2.4 depends on intl ^0.18.0 and app depends on intl ^0.17.0, syncfusion_flutter_datepicker >=21.2.4 is forbidden.
So, because app depends on syncfusion_flutter_datepicker ^21.2.4, version solving failed.
`

My flutter version:  3.7.12

**Comment by IndumathiR-1995** [comment]
Hi Team,

Based on the shared information we have checked the issue “DateRangePicker is not compatible with the into v 0.17.0”. Kindly upgrade the Flutter version to 3.10.0 and also use the package like intl: ">=0.17.0 <0.19.0"  for resolving the issue. We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
