### ISSUE TITLE
Example does not build on Flutter dev for Chrome browser and not even for Android on master

### ISSUE THREAD

**Issue by rydmike** [syncfusion/flutter-examples#78]
I tried to build your charting example app to testing out the charting package and dive into it a bit. 

When trying the build for Android one issue was that the example app files are not AndroidX enabled and that caused build issues for Android even on Flutter stable channel. After fixing the AndroidX issue, the build worked fine on the latest stable Flutter channel when building for an Android device, so that was easily remedied.

```
**OK ON THIS**
(Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (13 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0)
```

After that it also worked fine when building for an Android device when using the Flutter dev channel:

```
**OK ON DEVICE, FAIL ON WEB**
Flutter 1.15.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d94ff4bdbe (3 days ago) • 2020-02-06 13:19:46 -0800
Engine • revision f34bc65bee
Tools • Dart 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)
```

**However**, if it is built for Web using the above Flutter Dev channel with Chrome as the device, then the **build fails** with the following errors:

```
Launching lib\main.dart on Chrome in debug mode...
Error compiling dartdevc module:syncfusion_flutter_charts|lib/charts.ddc.js

packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:22:9: Error: Expected 0 type arguments.
  final Point<double> innerRadiusStartPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:22:47: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> innerRadiusStartPoint = Point<double>(
                                              ^^^^^
packages/syncfusion_flutter_charts/charts.dart:7:1: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
import 'dart:ui';
^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:25:9: Error: Expected 0 type arguments.
  final Point<double> innerRadiusEndPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:25:45: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> innerRadiusEndPoint = Point<double>(
                                            ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:29:9: Error: Expected 0 type arguments.
  final Point<double> radiusStartPoint = Point<double>(
        ^^^^^
packages/syncfusion_flutter_charts/src/circular_chart/utils/helper.dart:29:42: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
  final Point<double> radiusStartPoint = Point<double>(
                                         ^^^^^
AssetNotFoundException: syncfusion_flutter_charts|lib/charts.ddc.js
Failed after 50.3s
Failed to build application for the Web.
```
I also tried upgrading to the packages to the 17.4.46 versions from the 17.4.00 versions used in the latest examples files, the end result was the same.

I realize that the Web support that is available in the Flutter Dev and Master channels, might not be supported yet by your charting package. I just wanted to test and see if it might work and thought I would let you know that it does not. I'm sure you are aware already, but just in case. 

Do you plan to update the package so that it works on Flutter Web in the future?

I did not try to make a desktop build of the examples yet, as that requires using the Flutter master channel when building for Windows. I did notice though that if I try to build on master channel even for Android, I get other build errors:

```
*** FAILED TO BUILD FOR ANDROID ON ***
Flutter 1.15.3-pre.37 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6dc3bfaa98 (2 days ago) • 2020-02-07 18:28:02 -0800
Engine • revision 6158f03ef5
Tools • Dart 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)
```

The example fails when trying to build to an Android device on Flutter master, with the following error:

```
.../syncfusion_flutter_charts-17.4.46/lib/src/common/user_interaction/tooltip.dart:345:52: Error: Constant evaluation error:
  void hide() => _painter._calculateLocation(const Offset(null, null));
                                                   ^
org-dartlang-sdk:///flutter/lib/ui/geometry.dart:15:9: Context: This assertion failed.
  const OffsetBase(double dx, double dy)
        ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
* Where:
Script 'c:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 817
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'c:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 12s
Gradle task assembleDebug failed with exit code 1
```

**Comment by Dharanipalani** [comment]
Hi Rydmike,
 
Thanks for using Syncfusion Flutter widgets. We have analyzed your queries and please find the response below.
 
Query #1 – When trying the build for Android one issue was that the example app files are not AndroidX enabled and that caused build issues for Android even on Flutter stable channel
 
Response – Sorry for the inconvenience. We can able to reproduce the reported issue. This is because we didn’t yet migrate our sample browser project to AndroidX. Now we have migrated our project to AndroidX and moved the changes to the master branch. Now you can check out and run the project and it will work fine.
 
Query #2 – Do you plan to update the package so that it works on Flutter Web in the future
 
Response –  Flutter framework for web and windows support is still in Beta and hence we didn’t provide that support to our Flutter widgets. Once the Flutter moves it to stable, we will also provide support to our widgets.
 
Thanks,
Dharani. P

**Comment by rydmike** [comment]
Thanks Dharani for the quick response. 

Like I mentioned, I managed to migrate the example app to use AndroidX as well and it worked fine after that. Good that your released a version of it as well. Makes it easier for anybody curious about your charting packages to test it out on Flutter stable channel using Android devices without doing the migration themselves.

Just for info, with a few minor tweaks I managed to build the app for both Web on Dev channel and also for Windows using Master channel, with most things working on both builds. So with that in mind, I'm sure you can easily enough release a version of the library that can support them as well, whenever you are ready to do so.

BR
Mike
