### ISSUE TITLE
Date and Year Globalization

### ISSUE THREAD

**Issue by Emon526** [syncfusion/flutter-examples#781]
months is working perfectly but the years and dates are not globalized . i am trying with 'bn' and 'en' local.also the week name breaks then it gets a small screen insted of that if you can shorten the week name it would be great

**Comment by IndumathiR-1995** [comment]
Hi,

**Regarding Query: the week name breaks then it gets a small screen insted of that if you can shorten the week name it would be great**

As per the shared information, we have checked and your requirement is “Customise the day format in the view header provided language of the Flutter Calendar”. By hiding the default headers (headerHeight and viewHeaderHeight value as 0) and adding the custom headers you can localize the headers with required number of strings. We have prepared the simple sample for the same. Please find the sample from the following link.

Sample link:
[viewheader_locale.zip](https://github.com/syncfusion/flutter-examples/files/11496846/viewheader_locale.zip)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
