### ISSUE TITLE
Calendar: mobile platform appointment resize

### ISSUE THREAD

**Issue by Abdulah-butt** [syncfusion/flutter-examples#782]
Still waiting for this feature.

**Comment by sameer8287** [comment]
Me Also facing to resize the allowAppointmentResize but it does not support in mobile platform I want to Know the reason why ...?

**Comment by IndumathiR-1995** [comment]
Hi,

As per the provided information, we have checked and your requirement is “**Provide a support for appointment resizing in mobile platform of Flutter Calendar (SfCalendar)**” and already logged feature request for the same. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know once the feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:**
https://www.syncfusion.com/feedback/30674/provide-a-support-for-appointment-resizing-in-mobile-platform-of-flutter-calendar 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
