### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Gagandeep1408** [syncfusion/flutter-examples#783]
/syncfusion_flutter_datepicker-21.2.6/lib/src/date_picker/date_picker.dart:7665:71: Error: A value of type 'RenderAbstractViewport?' can't be returned from a function with return type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('../../Downloads/flutter/packages/flutter/lib/src/rendering/viewport.dart').
  RenderAbstractViewport get _stackViewPort => RenderAbstractViewport.of(this);

**Comment by IndumathiR-1995** [comment]
Hi,

We have checked the “**Error occurred  in Flutter DateRangePicker”** and we are unable to reproduce the any error from our end. We have checked with the simple sample and picker control was shown properly without any error. 

If possible can you please run the flutter clean command and run it once, still if you are facing the same issue? please share the below details to us.

1. Replicate procedure
2. Replication video

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
