### ISSUE TITLE
Just an in-code comment mistake

### ISSUE THREAD

**Issue by gabrimatic** [syncfusion/flutter-examples#784]
On the file '**/lib/src/date_picker/date_picker_manager.dart**', line '**4151**', there is a missing '**>**' in the:
'**[List<PickerDateRange]**'.

**Comment by IndumathiR-1995** [comment]
Hi,

We have included the mentioned issue fix “**Comment mistake in the date_picker_manager.dart file in the Flutter DateRangePicker**” in our latest Weekly Nuget release packge version 21.2.8. Kindly update to latest version for resolving this issue. Also please find the latest version from the following link.

**Pub link:** https://pub.dev/packages/syncfusion_flutter_datepicker/versions 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
