### ISSUE TITLE
How to show the multiply tooltips at same time for multiply charts?

### ISSUE THREAD

**Issue by GaoXing0608** [syncfusion/flutter-examples#785]
I want to show all of the tooltips for multiply charts when user move the mouse, are there some example code for this function
![image](https://github.com/syncfusion/flutter-examples/assets/47878271/e6666240-d2bc-4c99-99da-fdb952032acc)

**Comment by LokeshPalani** [comment]
Hi,



You can achieve your requirement by using the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property in the [tooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/tooltipBehavior.html). We have stored a group of series information with the help of the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property in the [tooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/tooltipBehavior.html) and displayed the tooltip while clicking on the chart series. We have prepared and attached a sample for your reference. Please modify it based on your requirement.



Regards,
Lokesh.

[chart_468838.zip](https://github.com/syncfusion/flutter-examples/files/11621860/chart_468838.zip)

**Comment by GaoXing0608** [comment]
Thanks a lot, the builder is very powerful
