### ISSUE TITLE
Appointment endTime is being incorrectly parsed / interpreted by the sfCalendar

### ISSUE THREAD

**Issue by nexio-t** [syncfusion/flutter-examples#787]
Hello, 

We believe we have identified a bug where the `endTime` on an Appointment is being incorrectly parsed by the sfCalendar. 

To reproduce, here are our appointments: 

```dart
          Appointment appointment2 = Appointment(
              id: '2',
              startTime: DateTime.parse('2023-05-01T22:00:00+00:00'),
              endTime: DateTime.parse(
                  '2023-05-03T18:00:00+00:00'), // Change to 2023-05-03T22:00:00+00:00 to display on 3
              subject: 'Test',
              color: Colors.red,
              resourceIds: ['23'],
              startTimeZone: 'Pacific Standard Time',
              endTimeZone: 'Pacific Standard Time');
```

Here are our resources: 

```dart
          CalendarResource resource2 = CalendarResource(
            id: '23',
            displayName: 'Resource 2',
            color: Colors.red,
          );
```

```dart 
class _AppointmentDataSource extends syncFusion.CalendarDataSource {
  _AppointmentDataSource(
      List<Appointment> source, List<CalendarResource> resourceColl) {
    this.appointments = source;
    this.resources = resourceColl;
  }
}

 CalendarDataSource calendarResources = _AppointmentDataSource(
      [appointment2],
      [resource2],
    );
```

Here is our calendar: 

```dart
return SfCalendar(
              view: CalendarView.timelineMonth,
              dataSource: calendarResources,
            )
```

For appointment2, when the DateTime endTime is changed from `2023-05-03T18:00:00+00:00` to `2023-05-03T22:00:00+00:00` , it appears to end on May 3, 2023, whereas with the first value it appears to end on May 2, 2023. If the endTime is changed to `2023-05-02T18:00:00+00:00`, it correctly appears to end on May 2.

**Comment by IndumathiR-1995** [comment]
Hi ,

Currently we are validating the mentioned issue. We will validate and update you the further details on or before June 5, 2023. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by IndumathiR-1995** [comment]
Hi ,

We have already found and fixed the mentioned issue “**Appointment endTime is being incorrectly parsed / interpreted by the sfCalendar**” and include the issue fix in our upcoming Weekly nuget release package, which is expected to be rolled out by June 6, 2020 and let you know once release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by IndumathiR-1995** [comment]
Hi,

We have included the issue fix for  “**Appointment endTime is being incorrectly parsed / interpreted by the sfCalendar**”. Kindly update to the latest **version 21.2.9** for resolving the issue. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions 

Regards,
Indumathi R
