### ISSUE TITLE
Could you run it successfully?

### ISSUE THREAD

**Issue by mozartee** [syncfusion/flutter-examples#788]
![image](https://github.com/syncfusion/flutter-examples/assets/5276499/12a9b467-0252-4a79-b183-94f5e80abe45)
I got this error.

**Comment by LokeshPalani** [comment]
Hi @mozartee,

The reported issue "A constant constructor can't call a non-constant super constructor” linter warnings has been raised in the Flutter SDK version 3.10.0. We have resolved the issue in the latest syncfusion_flutter_maps package. To avoid this issue, please use the latest syncfusion_flutter_maps package and the latest Flutter SDK version. Please let us know if you need any further assistance. 

Regards,
Lokesh.
