### ISSUE TITLE
Problem with Horizontal Scrollbar in Schedule Resource view in Flutter Web

### ISSUE THREAD

**Issue by MohamedAbd0** [syncfusion/flutter-examples#789]
horizontal scrollbar not work but victor scrollbar work normally, how to work horizontal scroll as victor scrollbar ?
[
![ezgif com-video-to-gif (2)](https://github.com/syncfusion/flutter-examples/assets/32939129/cc42f9a2-1e3a-4c60-9ff4-1fee309f4150)
](url)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest charts version.
