### ISSUE TITLE
 A constant constructor can't call a non-constant super constructor.

### ISSUE THREAD

**Issue by DeshanKTD** [syncfusion/flutter-examples#791]
A error occurs when importing

`import 'package:syncfusion_flutter_charts/charts.dart'`

`A constant constructor can't call a non-constant super constructor.
      : super(children: children);`

Flutter version  3.3.10 • channel stable

**Comment by mc100p** [comment]
do a flutter upgrade. I upgraded from 3.7.12 to 3.10.3 and it worked perfectly after.

**Comment by daniwaxman** [comment]
I am also facing this issue. The resolution shouldn't be to upgrade to 3.10.3 as this is not indicated to be a breaking change. If it were a breaking change.

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue "A constant constructor can't call a non-constant super constructor” linter warnings has been raised in the Flutter SDK version 3.10.0. We have resolved the issue in the latest syncfusion_flutter_charts package. To avoid this issue, please use the latest syncfusion_flutter_charts package and the latest Flutter SDK version. Please let us know if you need any further assistance.

**Comment by codestronaut** [comment]
Same issue here. I use `syncfusion_flutter_datepicker: ^21.2.3`, causing my CI pipeline to fail. Is there any solution?

```bash
/root/.pub-cache/hosted/pub.dev/syncfusion_flutter_core-21.2.8/lib/src/calendar/custom_looping_widget.dart:50:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(children: children);
        ^
```

**Comment by LokeshPalani** [comment]
Hi @daniwaxman,

This issue will not occur when using below Flutter SDK version 3.7.9 and below syncfusion_flutter_charts package version 21.2.4. The reported issue, "A constant constructor can't call a non-constant super constructor" linter warning, has been raised in Flutter SDK version 3.10.0. We have resolved the issue in the latest syncfusion_flutter_charts package. To avoid this issue, please use the latest syncfusion_flutter_charts package and the latest Flutter SDK version. Please let us know if you need any further assistance.

Regards,
Lokesh.
