### ISSUE TITLE
All day Panel Height

### ISSUE THREAD

**Issue by ObaofNY** [syncfusion/flutter-examples#796]
Hello SyncFusion Community,

I have a suggestion for an enhancement that I believe would be beneficial for many users: the ability to adjust the height of the "All Day Panel" in the Syncfusion Calendar widget.

Currently, the default height of the "All Day Panel" may not always be sufficient to display all the necessary information, especially when there are numerous events or longer event title By allowing users to customize the height of this panel, we can ensure that all relevant information is visible and easily accessible.

Thank you for considering this feature request. I value your expertise and contribution to the package. 

Best regards,

**Comment by IndumathiR-1995** [comment]
Hi,

We have logged the feature request for “**Providing a support to customize the height of the all-day panel in the Flutter Calendar (SfCalendar)**”. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:**
https://www.syncfusion.com/feedback/44895/providing-a-support-to-customize-the-height-of-the-all-day-panel-in-the-flutter 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
