### ISSUE TITLE
Automatic panning is not supported

### ISSUE THREAD

**Issue by MsXam** [syncfusion/flutter-examples#8]
Automatic panning does not work if we set :

zoomPanBehavior: ZoomPanBehavior(
            enablePanning: true,
            enablePinching: false,
          ),

Full Chart :

            /// Used for column 
            SfCartesianChart(
          plotAreaBorderWidth: 0,
          primaryXAxis: CategoryAxis(
            majorGridLines: MajorGridLines(width: 0),
          ),
          primaryYAxis: NumericAxis(
              maximum: 100,
              minimum: 0,
              interval: 25,
              axisLine: AxisLine(width: 0),
              majorTickLines: MajorTickLines(size: 0)),
          series: getColumnSeries(),
              isVisible: true,
              overflowMode: LegendItemOverflowMode.wrap),
          tooltipBehavior: TooltipBehavior(enable: true),
          zoomPanBehavior: ZoomPanBehavior(
            enablePanning: true,
            enablePinching: false,
          ),
        ),

The only way to get panning working is to :

1) zoomPanBehavior: ZoomPanBehavior(
            enablePanning: true,
            enablePinching: true,
          ),

2)  zoomPanBehavior: ZoomPanBehavior(
            enablePanning: true,
            enablePinching: false, enableDoubleTapZooming: true
          ),

 
I just want to view a graph and be able to pan the graph without having to doubletap - is this another bug in syncfusion or is this a limitation ?

**Comment by JayavigneshwaranG** [comment]
Hi @MsXam ,

We have analyzed your query and we wish to let you know that, the panning can be performed only on the zoomed chart. If the chart is not in zoomed state, we could not pan over it. Any one of the below steps can be followed to zoom a chart.
•	Enabling pinch zooming
•	Enabling double tap zooming
•	Enabling selection zooming
•	By setting zoom factor to the x or y axis
•	By specifying visible min and visible max value

We have attached a simple example for setting zoom factor to the axis. Please find it from the below link. Zoom factor value ranges from 0 to 1. Here we have set 0.5 for both x and y axis. Thus the chart will be rendered in zoomed state and you can perform panning on it, without pinching.
https://www.syncfusion.com/downloads/support/directtrac/245143/ze/Zooming1936246516

Please find more details about zooming and panning from the below UG link.
https://help.syncfusion.com/flutter/chart/zoom-pan

Thus I am closing this issue now.
If you still face any concerns, please create a support incident for better follow up, we will update our response there.

Thanks,
Jayavigneshwaran
