### ISSUE TITLE
it shows the date and colors incorrectly, what is the problem? package or us?

### ISSUE THREAD

**Issue by axroromonov** [syncfusion/flutter-examples#800]
<img width="487" alt="Screenshot 2023-07-18 at 20 19 03" src="https://github.com/syncfusion/flutter-examples/assets/76530966/b9a86fc7-959f-4dc8-a138-1dabc526b756">

**Comment by 3rsin3rgul** [comment]
Same here.

**Comment by SourabhKumar11** [comment]
please, explain your problem in details.What exactly do u want and where are u facing the issues?. So that we can help further.
