### ISSUE TITLE
_SfCalendarState._handleScheduleViewScrolled

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-examples#803]
FlutterError - RangeError (length): Invalid value: Valid value range is empty: 0. Error thrown Instance of 'ErrorDescription'.

Platform: apple
Version: 1.1.86 (136)
Issue: 73e0c26bae0c6e98609dd1d2a63f2c25
Session: d7add2f89d5b4697bd655d72e562768a_DNE_0_v2

Fatal Exception: FlutterError
0  ???                            0x0 _SfCalendarState._handleScheduleViewScrolled (sfcalendar.dart)
1  ???                            0x0 ChangeNotifier.notifyListeners + 403 (change_notifier.dart:403)
2  ???                            0x0 ChangeNotifier.notifyListeners + 403 (change_notifier.dart:403)
3  ???                            0x0 ScrollPosition.notifyListeners + 965 (scroll_position.dart:965)
4  ???                            0x0 ScrollPosition.setPixels + 282 (scroll_position.dart:282)
5  ???                            0x0 ScrollPositionWithSingleContext.setPixels + 78 (scroll_position_with_single_context.dart:78)
6  ???                            0x0 BallisticScrollActivity.applyMoveTo + 568 (scroll_activity.dart:568)
7  ???                            0x0 BallisticScrollActivity._tick + 554 (scroll_activity.dart:554)
8  ???                            0x0 AnimationLocalListenersMixin.notifyListeners + 161 (listener_helpers.dart:161)
9  ???                            0x0 AnimationController._tick + 830 (animation_controller.dart:830)
10 ???                            0x0 Ticker._tick + 249 (ticker.dart:249)
11 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1284 (binding.dart:1284)
12 ???                            0x0 SchedulerBinding.handleBeginFrame.<fn> + 1136 (binding.dart:1136)
13 ???                            0x0 _LinkedHashMapMixin.forEach (dart:collection)
14 ???                            0x0 SchedulerBinding.handleBeginFrame + 1134 (binding.dart:1134)
15 ???                            0x0 SchedulerBinding._handleBeginFrame + 1051 (binding.dart:1051)

Crashed: com.apple.main-thread
0  FirebaseCrashlytics            0x1e2cc FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1e6ac FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x15744 FIRCLSHandler + 48
3  FirebaseCrashlytics            0xfbd8 FIRCLSExceptionRecordOnDemand + 1328
4  FirebaseCrashlytics            0xf618 FIRCLSExceptionRecordOnDemandModel + 228
5  FirebaseCrashlytics            0x1da98 -[FIRCLSOnDemandModel recordOnDemandExceptionWithModel:] + 68
6  FirebaseCrashlytics            0x1d4f4 -[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:] + 164
7  FirebaseCrashlytics            0x2b9a8 -[FIRCrashlytics recordOnDemandExceptionModel:] + 140
8  Runner                         0x228284 -[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 177 (FLTFirebaseCrashlyticsPlugin.m:177)
9  Runner                         0x227b40 -[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 101 (FLTFirebaseCrashlyticsPlugin.m:101)
10 Flutter                        0x5d5f98 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
11 Flutter                        0x3736c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
12 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
14 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain + 928
15 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
16 CoreFoundation                 0x4e034 <redacted> + 12
17 CoreFoundation                 0xb538 <redacted> + 2544
18 CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
19 GraphicsServices               0x1988 GSEventRunModal + 160
20 UIKitCore                      0x4e5a88 -[UIApplication _run] + 1080
21 UIKitCore                      0x27efc8 UIApplicationMain + 336
22 Runner                         0x4e90 main + 5 (AppDelegate.swift:5)
23 ???                            0x1028404d0 (Ausente)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  Foundation                     0x17eac <redacted> + 232
6  Foundation                     0x56fd0 <redacted> + 88
7  UIKitCore                      0x464ef4 -[UIEventFetcher threadMain] + 512
8  Foundation                     0x64bdc <redacted> + 792
9  libsystem_pthread.dylib        0x3348 _pthread_start + 116
10 libsystem_pthread.dylib        0x1948 thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
6  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
7  libsystem_pthread.dylib        0x3348 _pthread_start + 116
8  libsystem_pthread.dylib        0x1948 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
6  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
7  libsystem_pthread.dylib        0x3348 _pthread_start + 116
8  libsystem_pthread.dylib        0x1948 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
6  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
7  libsystem_pthread.dylib        0x3348 _pthread_start + 116
8  libsystem_pthread.dylib        0x1948 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bd4 <redacted> + 1240
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x3348 _pthread_start + 116
5  libsystem_pthread.dylib        0x1948 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bd4 <redacted> + 1240
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x3348 _pthread_start + 116
5  libsystem_pthread.dylib        0x1948 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2294 kevent + 8
1  Flutter                        0x4d77e0 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
2  Flutter                        0x506780 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  libsystem_pthread.dylib        0x3348 _pthread_start + 116
4  libsystem_pthread.dylib        0x1948 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  FirebaseCrashlytics            0x17d58 FIRCLSMachExceptionServer + 104
3  libsystem_pthread.dylib        0x3348 _pthread_start + 116
4  libsystem_pthread.dylib        0x1948 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  CFNetwork                      0x247aa8 _CFURLStorageSessionDisableCache + 50420
6  Foundation                     0x64bdc <redacted> + 792
7  libsystem_pthread.dylib        0x3348 _pthread_start + 116
8  libsystem_pthread.dylib        0x1948 thread_start + 8

AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6cc8 <redacted> + 368
3  CoreFoundation                 0xafd0 <redacted> + 1160
4  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
5  AudioSession                   0x6478 CADeprecated::GenericRunLoopThread::Entry(void*) + 156
6  AudioSession                   0xf7c8 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 88
7  libsystem_pthread.dylib        0x3348 _pthread_start + 116
8  libsystem_pthread.dylib        0x1948 thread_start + 8

com.google.firebase.crashlytics.startup
0  CoreFoundation                 0x2482c __CFStringHash + 84
1  CoreFoundation                 0x5ffe0 <redacted> + 96
2  FirebaseCrashlytics            0x25f60 __47-[FIRCLSSymbolResolver loadedBinaryImageForPC:]_block_invoke + 44
3  CoreFoundation                 0x4fde8 <redacted> + 16
4  CoreFoundation                 0xac3a0 <redacted> + 444
5  FirebaseCrashlytics            0x25efc -[FIRCLSSymbolResolver loadedBinaryImageForPC:] + 80
6  FirebaseCrashlytics            0x260c8 -[FIRCLSSymbolResolver updateStackFrame:] + 80
7  FirebaseCrashlytics            0x25a68 __36-[FIRCLSSymbolicationOperation main]_block_invoke + 56
8  FirebaseCrashlytics            0x2637c -[FIRCLSThreadArrayOperation enumerateFramesWithBlock:] + 264
9  FirebaseCrashlytics            0x25a24 -[FIRCLSSymbolicationOperation main] + 68
10 Foundation                     0x39a8c <redacted> + 20
11 Foundation                     0x49fcc <redacted> + 764
12 FirebaseCrashlytics            0x1f5cc -[FIRCLSProcessReportOperation symbolicateFile:withResolver:] + 236
13 FirebaseCrashlytics            0x1f73c __36-[FIRCLSProcessReportOperation main]_block_invoke + 68
14 FirebaseCrashlytics            0x16d90 -[FIRCLSInternalReport enumerateSymbolicatableFilesInContent:] + 200
15 FirebaseCrashlytics            0x1f6dc -[FIRCLSProcessReportOperation main] + 172
16 Foundation                     0x39a8c <redacted> + 20
17 Foundation                     0x49fcc <redacted> + 764
18 FirebaseCrashlytics            0x22a30 __91-[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:]_block_invoke + 460
19 FirebaseCrashlytics            0x5f38 FIRCLSApplicationActivity + 72
20 FirebaseCrashlytics            0x2281c -[FIRCLSReportUploader prepareAndSubmitReport:dataCollectionToken:asUrgent:withProcessing:] + 172
21 FirebaseCrashlytics            0x11654 -[FIRCLSExistingReportManager processExistingActiveReportPath:dataCollectionToken:asUrgent:] + 152
22 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
23 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
24 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
25 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
26 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
27 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
28 libsystem_pthread.dylib        0x193c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1014 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e5c _pthread_wqthread + 360
2  libsystem_pthread.dylib        0x193c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1934 <redacted> + 270

com.google.firebase.crashlytics.on.demand
0  libsystem_kernel.dylib         0xfd0 __semwait_signal + 8
1  libsystem_c.dylib              0x4a40 nanosleep + 216
2  libsystem_c.dylib              0x18710 sleep + 48
3  FirebaseCrashlytics            0x1d790 __107-[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:]_block_invoke + 340
4  Foundation                     0x4e39c <redacted> + 16
5  Foundation                     0x5fa70 <redacted> + 100
6  Foundation                     0x39a8c <redacted> + 20
7  Foundation                     0x49fcc <redacted> + 764
8  Foundation                     0x4d498 <redacted> + 20
9  Foundation                     0x5accc <redacted> + 180
10 libdispatch.dylib              0x11544 _dispatch_block_async_invoke2 + 104
11 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
12 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
13 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
14 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
15 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
16 libsystem_pthread.dylib        0x193c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1934 <redacted> + 270

DartWorker
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9c00 <redacted> + 1284
2  Flutter                        0x68c180 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x6c61cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  Flutter                        0x68bb4c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
5  libsystem_pthread.dylib        0x3348 _pthread_start + 116
6  libsystem_pthread.dylib        0x1948 thread_start + 8

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the shared information, we have checked the issue “**RangeError in the Flutter calendar**” and we are unable to reproduce the mentioned error from our end.

**Tested scenario:**
1.	Checked with all calendar views with appointments
2.	Checked with scrolling the views.

**Tested details:**
1.	Flutter version: Stable channel-3.10.1
2.	Flutter Calendar version: 22.1.39

If possible can you please share the below details with us.

1.	Replication procedure
2.	Issue reproducing video

It would be helpful for us to analyze and provide you a solution at the earliest.


Regards,
Indumathi R

**Comment by mdmota** [comment]
Thanks for the feedback.
Unfortunately I can't reproduce, because I got an error report in firebase crashlytics . This has been happening to some users.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this
