### ISSUE TITLE
Export datagrid to excel, the cell value wrapped with Text

### ISSUE THREAD

**Issue by GaoXing0608** [syncfusion/flutter-examples#807]
Export the datagrid to excel, but the excel wraped the Text, how to fix it.

![image](https://github.com/syncfusion/flutter-examples/assets/47878271/36e06e85-809b-47d7-9029-a7dfe750403d)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi,

We have conducted comprehensive testing on the provided sample using the latest DataGrid-Export package version **22.2.7**. Our findings indicate that the functionality operates seamlessly without encountering any issues. The export to Excel successfully captures the values as expected. We kindly request you to review the enclosed sample from your end.


![image](https://github.com/syncfusion/flutter-examples/assets/93904422/2304892c-dec0-4f09-850c-35d754bb1947)




**Sample Link: [sample](https://github.com/syncfusion/flutter-examples/files/12274978/sample.zip)**


Regards,
Tamilarasan

**Comment by GaoXing0608** [comment]
I solved it. Because of my datagrid with multiply kinds of cell, such as Image, TextButton and Text. So I created the DataGridCell as following

DataGridCell(columnName: "column1", value: TextButton(....)),
DataGridCell(columnName: "column2", value: Text(....))

So it exported with the "Text"

> Hi,
> 
> We have conducted comprehensive testing on the provided sample using the latest DataGrid-Export package version **22.2.7**. Our findings indicate that the functionality operates seamlessly without encountering any issues. The export to Excel successfully captures the values as expected. We kindly request you to review the enclosed sample from your end.
> 
> ![image](https://user-images.githubusercontent.com/93904422/258770796-2304892c-dec0-4f09-850c-35d754bb1947.png)
> 
> **Sample Link: [sample](https://github.com/syncfusion/flutter-examples/files/12274978/sample.zip)**
> 
> Regards, Tamilarasan
