### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by longmengua** [syncfusion/flutter-examples#81]
Error output from Xcode build:
↳
    2020-02-14 14:52:57.725 xcodebuild[94417:14016890]  DTDeviceKit: deviceType from cfea4d0f2a68872fe61c31d3410c6b227a101dc3 was NULL
    2020-02-14 14:52:57.787 xcodebuild[94417:14016890]  DTDeviceKit: deviceType from cfea4d0f2a68872fe61c31d3410c6b227a101dc3 was NULL
    ** BUILD FAILED **

Xcode's output:
↳

    Compiler message:
    /Library/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-17.4.46/lib/src/common/user_interaction/tooltip.dart:345:52: Error: Constant evaluation error:
      void hide() => _painter._calculateLocation(const Offset(null, null));
                                                       ^
    org-dartlang-sdk:///flutter/lib/ui/geometry.dart:15:9: Context: This assertion failed.
      const OffsetBase(double dx, double dy)
            ^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the precompiled application for the device.

Error launching application on TEST.

**Comment by srihariash999** [comment]
What was the solution you found? I am facing the same issue.

**Comment by longmengua** [comment]
It seems like caused by flutter engine, I solved it by updating flutter to the latest stable version.
