### ISSUE TITLE
SfPdfViewer does not display pdfs Blazor Wasm

### ISSUE THREAD

**Issue by JosetoDev** [syncfusion/flutter-examples#813]
I am using the SfPdfViewer control in a Blazor Wasm project and I do it as the examples and the documentation and the file arrives, I convert it to Base-64 and it does not show the file
![image](https://github.com/syncfusion/flutter-examples/assets/22667344/bbd61a48-b9a4-4363-a147-2f05ce575446)
this is the code i use
![image](https://github.com/syncfusion/flutter-examples/assets/22667344/f4ab3f95-8c66-443c-8957-ef8e40c2b881)
![image](https://github.com/syncfusion/flutter-examples/assets/22667344/fbf18266-07df-4bee-a298-2d80855ce432)

**Comment by GokulprasathVenkatachalam** [comment]
<html>
<body>
<p>Hi JosetoDev,<br>&nbsp;</p><p style="margin-bottom:0px;margin-top:0px;">We have already fixed this <strong>"Document not loading with base64 string"</strong> issue in our latest weekly release v24.2.4. Kindly upgrade to that version to get the issue resolved.</p>
<table>
<tr>
<td>Blazor NextGen</td><td><a href="https://www.nuget.org/packages/Syncfusion.Blazor.SfPdfViewer">https://www.nuget.org/packages/Syncfusion.Blazor.SfPdfViewer</a></td>
</tr>
</table><p style="margin-bottom:0px;margin-top:0px;"><strong>CDN Links:</strong></p><p style="margin-bottom:0px;margin-top:0px;"><a href="https://cdn.syncfusion.com/blazor/24.2.4/styles/bootstrap5.css" rel="noreferrer noopener" title="https://cdn.syncfusion.com/blazor/24.2.4/styles/bootstrap5.css" target="_blank">https://cdn.syncfusion.com/blazor/24.2.4/styles/bootstrap5.css</a></p><p style="margin-bottom:0px;margin-top:0px;"><a href="https://cdn.syncfusion.com/blazor/24.2.4/syncfusion-blazor-sfpdfviewer.min.js" rel="noreferrer noopener" title="https://cdn.syncfusion.com/blazor/24.2.4/syncfusion-blazor-sfpdfviewer.min.js" target="_blank">https://cdn.syncfusion.com/blazor/24.2.4/syncfusion-blazor-sfpdfviewer.min.js</a></p><p style="margin-bottom:0px;margin-top:0px;">&nbsp;</p><p style="margin-bottom:0px;margin-top:0px;">Regards,</p><p style="margin-bottom:0px;margin-top:0px;">Gokulprasath</p>
</body>
</html>
