### ISSUE TITLE
Syncfusion Category axis offset

### ISSUE THREAD

**Issue by Samamoah** [syncfusion/flutter-examples#816]
<img width="486" alt="Screenshot 2023-09-11 at 9 50 32 AM" src="https://github.com/syncfusion/flutter-examples/assets/38361238/b8f7c13d-34c9-4e28-ae56-b76e46953522">

There is a gap at the begging and end of x-axis. How can i fix this. I want the S right beneath the 0 on the first axis and last item on last axis

**Comment by sfHariHaraSudhan** [comment]
Hi @Samamoah,

We suspect that you are rendering the x-axis using the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) based on the provided snapshot and the mentioned requirement can be achieved using the [labelPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/labelPlacement.html) property. In both [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html) and [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html), there is an option to render the axislabels between the ticks or on the tick using the [labelPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/labelPlacement.html) property and its default value is [LabelPlacement.betweenTicks](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelPlacement.html). Therefore, we suggest you to set the [labelPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/labelPlacement.html) property as [LabelPlacement.onTicks](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelPlacement.html) to render the axislabel at the beginning and end of the x-axis.

Kindly refer the code snippet below:
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _chartData;

  @override
  void initState() {
    _chartData = [
      ChartSampleData(DateTime(2023, 09, 10), 30),
      ChartSampleData(DateTime(2023, 09, 11), 20),
      ChartSampleData(DateTime(2023, 09, 12), 50),
      ChartSampleData(DateTime(2023, 09, 13), 60),
      ChartSampleData(DateTime(2023, 09, 14), 40),
      ChartSampleData(DateTime(2023, 09, 15), 50),
      ChartSampleData(DateTime(2023, 09, 16), 70),
    ];

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(10.0),
          child: SfCartesianChart(
            primaryXAxis: DateTimeCategoryAxis(
                intervalType: DateTimeIntervalType.days,
                // labelPlacement: LabelPlacement.betweenTicks,
                labelPlacement: LabelPlacement.onTicks,
                dateFormat: DateFormat('E')),
            primaryYAxis: NumericAxis(),
            series: <CartesianSeries<ChartSampleData, DateTime>>[
              SplineSeries<ChartSampleData, DateTime>(
                dataSource: _chartData,
                xValueMapper: (ChartSampleData data, _) => data.x,
                yValueMapper: (ChartSampleData data, _) => data.y,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Snapshot:
Between Ticks :
![image](https://github.com/syncfusion/flutter-examples/assets/105288122/cf5491de-0871-4fa0-92a3-9c04fca5994a)

On Ticks :
![image](https://github.com/syncfusion/flutter-examples/assets/105288122/6fe302dd-ea10-4a8a-a3ab-fefd0241af7d)

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by Samamoah** [comment]
Thank you @sfHariHaraSudhan this worked perfectly. But I am facing 1 more issue that I need help with. Not all the labels are showing on this bar chart, i reduced the font size to like 2 pixels and still the rest were not showing. How can i fix it, its suppused to show from Jan to Dec. Or should i open a different issue and close this ?




<img width="486" alt="Screenshot 2023-09-13 at 12 43 31 PM" src="https://github.com/syncfusion/flutter-examples/assets/38361238/6b3e6f06-98f4-4b90-98fe-c1a29a1eff63">

**Comment by Samamoah** [comment]
I have fixed the issue @sfHariHaraSudhan
