### ISSUE TITLE
debug apk problem

### ISSUE THREAD

**Issue by DFFUa** [syncfusion/flutter-examples#818]
When I run the application in the emulator, everything works, but when I run it on a real device I get the error “The application cannot be installed because it is not supported by the device.”
This error occurs on different phones

please tell me how to solve this problem

**Comment by sfHariHaraSudhan** [comment]
Hi @DFFUa,

We would like to inform you that the Syncfusion Flutter Widgets will be available on both Android and iOS devices. The Android device will be compatible with **API level 19 and later**, while the iOS device will be compatible with version **iOS 8 and later** based on the Flutter Framework update. Shared the User Guide documentation link below regarding the system requirements for Flutter for your reference.

UG : https://help.syncfusion.com/flutter/system-requirements.

If you have the proper versions and still faced the mentioned issue, we recommend you share further details regarding the version and model of your phone used along with a detailed explanation. With that additional information, it will be very useful for us to provide possible solution from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this
