### ISSUE TITLE
Bug when plotting line chart having  String in x-axis

### ISSUE THREAD

**Issue by Sumit258000** [syncfusion/flutter-examples#824]
Thanks for the plugin. Currently, We are developing a graph in which we have a score on the y-axis and date time as a string on the x-axis we have 4 series of data for this. we are formatting the date as "yyyy/MM/dd HH:mm:ss". The output we are getting is individual line charts are coming as independent of their x-axis(Date as string) but the expected result is that it should align with the x-axis kindly see the first image for reference. I am using this JSON for [plotting graph](https://jsonblob.com/1158756531969056768). In the second trial when I formatted the date time as "yyyy/MM/dd" I was getting a little close to the expected result but in that case I am not able to show the exact time also graph looks dirty kindly refer to the second [image](https://user-images.githubusercontent.com/134265081/272276592-ecba39f6-5a42-4947-8c83-c9db37249c73.png).
I tried plotting graphs using dateTime instead of String but that creates
![line_1](https://github.com/syncfusion/flutter-examples/assets/134265081/26d0d929-6927-4b01-80b9-336951a5cfb4)
 
![line_2](https://github.com/syncfusion/flutter-examples/assets/134265081/9a0459ff-5a5a-44e5-b5ad-a682f1d151d0)
a long difference between months see image for reference.

I am expecting this [output's ](https://drive.google.com/file/d/1P-qKFf4TOl9PIXJF__ANE-0qwh4mqKtm/view?usp=sharing)final result

**Comment by LavanyaGowtham2021** [comment]
Addressed this requirement in this ticket https://support.syncfusion.com/agent/tickets/508303, hence closing this now.
