### ISSUE TITLE
ontap in resourceViewHeaderBuilder in SfCalendar

### ISSUE THREAD

**Issue by bybabek** [syncfusion/flutter-examples#827]
I created widget with resourceViewHeaderBuilder . Inkwell and gesturedetectors are not working inside of this widget. I wanted to drag resource widget and drop it to the appointment.
Here is my resourceBuilder code:

```
Widget resourceBuilder(
      BuildContext context, ResourceViewHeaderDetails details) {
return InkWell(
        onTap: () {
          print('test');
        },
        child: Draggable<String>(
          data: "salam",
          dragAnchorStrategy: pointerDragAnchorStrategy,
          feedback: Container(
            key: _draggableKey,
            height: 50,
            width: 50,
            color: Colors.red,
          ),
          child: InkWell(
            onTap: () {
              print('test');
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisSize: MainAxisSize.max,
              children: [
                GestureDetector(
                  onTap: () {
                    print('test');
                  },
                  child: CircleAvatar(
                    backgroundImage: details.resource.image,
                    backgroundColor: details.resource.color,
                  ),
                ),
                Center(
                  child: Text(
                    details.resource.displayName,
                    textAlign: TextAlign.center,
                  ),
                ),
              ],
            ),
          ),
        ),
      );
}
```

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the current implementation, there is no support to gesture detector support for builders. So we can’t detect the gesture inside the builders. We have already logged the feature request for “**Providing a gesture detector support for builders in the Flutter calendar (SfCalendar)**”. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:** https://www.syncfusion.com/feedback/46931/providing-a-gesture-detector-support-for-builders-in-the-flutter-calendar 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by trangdth-mume** [comment]
@bybabek can you use code:
`onTap: (CalendarTapDetails details) {
            if (details.targetElement == CalendarElement.resourceHeader) {
}
}`
