### ISSUE TITLE
[syncfusion_flutter_datepicker 23.1.43] How do I make the size of the calendar smaller?

### ISSUE THREAD

**Issue by ricoricc** [syncfusion/flutter-examples#829]
The calendar takes all the space on the screen, I want it to make it like a showDialog box, is it possible to shrink the box size?
![Phone](https://github.com/syncfusion/flutter-examples/assets/79364775/d687343f-7392-47ec-9d60-a2e92bf38bdc)

**Comment by PmPPolska** [comment]
https://tieba.baidu.com/hottopic/browse/hottopic?topic_id=19295459

**Comment by PmPPolska** [comment]
Regards

**Comment by IndumathiR-1995** [comment]
Hi ,

By using the DatePicker inside the Card widget, you can change the size of the picker with required size.
Please find the code snippet for the same.

**Code snippet:**
```
              Card(
                margin: EdgeInsets.fromLTRB(50, 150, 50, 150),
                child: SfDateRangePicker(
                  view: DateRangePickerView.month,
                ),
              ),
```
**Screenshot:**
![image](https://github.com/syncfusion/flutter-examples/assets/48712435/d56ee799-81f2-4504-b529-c5aa36bb7b95)

Please let us know if  you need further assistance.

Regards,
Indumathi R
