### ISSUE TITLE
Changing intervals on graph axis

### ISSUE THREAD

**Issue by sevekim** [syncfusion/flutter-examples#830]
When using the CandleSeries chart, the zoom in/out functions works fine, however, the intervals on axis can be not ideal to view the graph when zoomed in.

See the image below.

![download](https://github.com/syncfusion/flutter-examples/assets/11042584/09abdd4e-60bd-440a-b561-27d53bbdec5f)

On TradingView, there is an ability to change the axis interval while scrolling the mouse on the axis column, thus making the data bit more readable.

Is there a way to achieve something like this within the flutter package?

Thanks!

**Comment by VijayakumarMariappan** [comment]
Furthermore, our Syncfusion Flutter Chart will calculate the auto interval whenever the axis range is changed, such as when zooming or panning. This can be controlled through the [enableAutoIntervalOnZooming](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/enableAutoIntervalOnZooming.html) property.

If you require additional assistance, please feel free to create a new ticket or reopen this one.
