### ISSUE TITLE
Problem while converting doc file to pdf

### ISSUE THREAD

**Issue by mokaily** [syncfusion/flutter-examples#835]
I am trying to convert docx file to pdf file
code:
```
// data is Uint8List type.
List<int> inputBytes = data.toList();
      PdfDocument document;
      try {
       // error here! 
        document = PdfDocument(inputBytes: inputBytes);
        // Rest of your code
      } catch (e) {
        print('Error creating PdfDocument: $e');
      }
```
output: `PdfDocument: RangeError (end): Invalid value: Not in inclusive range 2048..111303: 1024`

Does this package support only converting small docx files?

**Comment by irfanajaffer** [comment]
As of now, we do not have support to convert docs to PDF documents and we already logged this requirement as a feature request in our library. And we do not have any immediate plans to implement these features and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.
