### ISSUE TITLE
Crash app IOS when build tooltipBehavior >> enable: true

### ISSUE THREAD

**Issue by VuQuangHien** [syncfusion/flutter-examples#846]
Hello Bro
When I add tooltipBehavior: TooltipBehavior(enable: true,header: 'HienVQ'), in SfCartesianChart
1. Android build and using not crash
2.  IOS build crash when touch in tooltop point 
3. I used 
  syncfusion_flutter_charts: ^22.2.12
in file pubspec.yaml

How I can fixed it, thanks ?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest charts version.

**Comment by VuQuangHien** [comment]
@PreethikaSelvam 
Hello Bro, so sorry late rep 
I download file and run but app crash. Pls check with me
[bd547806.zip](https://github.com/syncfusion/flutter-examples/files/14428173/bd547806.zip)

**Comment by VuQuangHien** [comment]
I am using M2, 
<img width="1119" alt="image" src="https://github.com/syncfusion/flutter-examples/assets/11348207/361f5eca-a8c5-48d8-88c4-ba3a4091e63f">

**Comment by VuQuangHien** [comment]
I have viber, skype, facebook, if you have freetime and  maybe contact with me, I can show you that's issue, thanks

**Comment by VuQuangHien** [comment]
@LavanyaGowtham2021 @PreethikaSelvam When I updated lastest version syncfusion_flutter_charts: ^24.2.8 , in IOS not Crash. I think close issue

**Comment by VuQuangHien** [comment]
Thanks
