### ISSUE TITLE
 Error: The getter 'isMetaPressed' isControlPressed isn't defined for the class 'HardwareKeyboard'

### ISSUE THREAD

**Issue by MikePendo** [syncfusion/flutter-examples#849]

**Comment by immankumarsync** [comment]
Hi @MikePendo ,

We have migrated our source, which is compatible with Flutter SDK 3.19.0. In Flutter SDK version 3.19.0, they have made breaking changes to the RawKeyEvent and replaced it with HardWareKeyBoard. So, we kindly request that you upgrade the Flutter SDK version to 3.19.0 or else use the Syncfusion Flutter Packages version below 24.2.7. We have also shared the breaking changes documentation below for your reference.

We hope it will help you resolve the issue. If you have any further queries, please get back to us. We are always happy to assist you.

Flutter 3.19.0 breaking change, https://docs.flutter.dev/release/breaking-changes/key-event-migration#migrating-iskeypressed-and-related-functions
