### ISSUE TITLE
Tooltip in incorrect location on click

### ISSUE THREAD

**Issue by markathomas** [syncfusion/flutter-examples#85]
Added tooltip on a LineSeries chart with a DateTime axis as shown in the example but the tooltip shows up on the wrong value when clicked.  See the attached image fro where I clicked (the grey arrow pointing to it) and the actual location.

![Screenshot from 2020-03-02 07-57-46](https://user-images.githubusercontent.com/488472/75683320-81a45a80-5c5c-11ea-9923-afd5647654b3.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @markathomas ,

We have analyzed your query. For the line type charts, we have stored the marker points as regions and added padding for those regions to detect a smooth touch in case of user interactions like a tooltip, etc. So, in this case, for the huge number of points, the regions are coming so close and this is the behavior of the chart. We have attached a sample screenshot for your reference.

![image](https://user-images.githubusercontent.com/19346074/76011465-a2113500-5f3a-11ea-8a9f-6781ea04b171.png)

In the screenshot, the highlighted regions are tooltip regions and padding enabled for those regions. This is the reason for tooltip positioning in your case.

Thanks,
Dharani.

**Comment by markathomas** [comment]
Regardless of the reason, it's incorrect and not usable.  I've switched to
the trackball for now.

**Comment by dharanidharandharmasivam** [comment]
Hi @markathomas ,

For a huge number of data points, we also prefer to use trackball rather than using the tooltip. Tooltip is good to work with a minimal number of data points. Kindly revert us if you have further queries.

Thanks,
Dharani,
