### ISSUE TITLE
cannot start the project

### ISSUE THREAD

**Issue by chirastefan** [syncfusion/flutter-examples#856]
### Bug description

Cannot start the project due to compile errors.

### Steps to reproduce

1. clone the project
2. run `flutter pub get`
3. can't start the project due to compiling errors

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter pub get
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<img width="1688" alt="Screenshot 2024-05-15 at 15 16 41" src="https://github.com/syncfusion/flutter-examples/assets/16649178/f3fc65cd-af33-4ef8-84a4-ced04a7acce3">

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
Error (Xcode): lib/samples/pdf/import_and_export_annotation_data.dart:29:3: Error: Type 'PdfAnnotationDataFormat' not found.
```

</details>

### On which target platforms have you observed this bug?

macOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.19.6 on channel stable at /Users/me/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA Latest.app
    • Flutter plugin version 79.1.3
    • Dart plugin version 241.15989.9

[✓] VS Code (version 1.89.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0
```

</details>

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @chirastefan , 

We would like to let you know that, we have updated the sample browser GitHub source at every main release once. To resolve the const issue we request you to upgrade the dependent package version to [25.1.35](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.35) it will help you to resolve the error.

We have also published this SB sample in Appstore and shared the link below for your reference, you can install and check the sample.

Google Play store: https://play.google.com/store/apps/details?id=com.syncfusion.flutter.examples&hl=en&gl=US&pli=1

Windows Appstore: https://apps.microsoft.com/detail/9nhnbwcsf85d?amp%3Bgl=US&hl=en-us&gl=IN

Web: https://flutter.syncfusion.com/

If you have any further queries please get back to us, we are always happy to assist you.

Regards,
Yuvaraj.
