### ISSUE TITLE
The examples given are not developer friendly :(

### ISSUE THREAD

**Issue by untillnesss** [syncfusion/flutter-examples#857]
### Bug description

s

### Steps to reproduce

asd

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by LokeshPalani** [comment]
Hi @untillnesss,

We have checked your query and couldn't clearly understand from your shared details. Could you please share the following details to check further on our end?

- In which widget example are you facing the issue?
- What issue are you facing in example samples?

We kindly request you to share more details about your query along with the screenshot or screen recording, it will be more helpful for us to provide a possible solution from our end.

Regards,
Lokesh P.
