### ISSUE TITLE
How to merge some cells for DataGrid?

### ISSUE THREAD

**Issue by GaoXing0608** [syncfusion/flutter-examples#863]
I want to merge some cells, however, I haven't found some documents to implement my function.

**Comment by abineshPalanisamy** [comment]
Hi @GaoXing0608 ,

As of now, DataGrid does not have support for merge the rows and cells. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link - [23230](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F23230%2Fsupport-to-merge-the-rows-and-cells&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C76a3cc2341ea4f4ee4a908dcb2de1351%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638581914074124295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=UlRgChzkPDzJhGKqQhnzDxpFVwPeg5YlBf6FucfpBpo%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @GaoXing0608,

You can follow the provided feedback link for further updates regarding the requested feature. We are closing this issue now. If you need any further assistance, please reopen this issue. We are happy to assist you.

Regards,
Ashok K
