### ISSUE TITLE
Event Calendar could not show the details

### ISSUE THREAD

**Issue by GaoXing0608** [syncfusion/flutter-examples#865]
### Bug description

I built my app into web and publish on Ubuntu server, however, could not show the content details in any chrome browser.
Ubuntu version: 20.04.4 LTS
![image](https://github.com/user-attachments/assets/1d5b67cc-cffb-4b8e-99d7-b95d0ce16f82)

It could show correctly when the web publish on windows server
![image](https://github.com/user-attachments/assets/059835e2-8d47-441b-b8a9-3831afce5007)

### Steps to reproduce

such as the desc

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Web, Linux

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
