### ISSUE TITLE
Cartesian Chart with Labels not Overlapping Gridlines

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#89]
I'd like to make a cartesian chart where the vertical axis labels don't overlap with the horizontal grid lines when the labels are set to be inside the plot area. Is this possible?

Bad:
![image](https://user-images.githubusercontent.com/50309714/77218534-a32d8f00-6b02-11ea-80b9-0db1a41cbfc6.png)

Good:
![image](https://user-images.githubusercontent.com/50309714/77218727-d53ff080-6b04-11ea-8ee2-27b5f43b3c97.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. We have analyzed your query and as of now, we don’t have support for aligning the axis labels which are moved inside. So, we have considered your requirement as a feature request and will be available in any of our upcoming releases. You can track the status of the feature from the below feedback link.

https://www.syncfusion.com/feedback/12910
 
Thanks,
Dharani.
