### ISSUE TITLE
Glow Effect

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#90]
Is it possible to create a glowing effect around plotted values in the cartesian or bar chart, like below?

![image](https://user-images.githubusercontent.com/50309714/77218786-70d16100-6b05-11ea-8905-1c6adf20216c.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Greetings from Syncfusion. As of now, the requested feature is not available and so, we have logged a feature request for your scenario. This will be available in any of our upcoming releases and you can track the status of the feature from the below feedback portal.
https://www.syncfusion.com/feedback/12926 

You can also create incidents using the below link, this will be helpful in better follow up.
https://www.syncfusion.com/support/directtrac/incidents 

Thanks,
Dharani.
