### ISSUE TITLE
Remove Horizontal Line from Tooltip?

### ISSUE THREAD

**Issue by opalr** [syncfusion/flutter-examples#92]
I'd like to not show the horizontal white line between "Transfer" and the round marker. Is this possible?

![image](https://user-images.githubusercontent.com/50309714/77269729-27f1e780-6c80-11ea-81a6-edfda53c064d.png)

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr 

Greeting from Syncfusion. Your requirement can be achieved by specifying the format for the tooltip. Find the code snippet below to achieve this.

> 
    SfCartesianChart(
                      tooltipBehavior: TooltipBehavior(enable: true,
                        format: 'series.name',
                        header: '',
                      ),
                      // Other configurations
                    )

The sample for reference can be found below.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/issue_9232956019 

Thanks,
Dharani.

**Comment by opalr** [comment]
I tried this and it removed the horizontal line but it shows the string 'series.name' instead of the actual category name.

![image](https://user-images.githubusercontent.com/50309714/77370413-30f1c000-6d37-11ea-952b-07d4c6ae1b30.png)

```
SfCartesianChart(
              plotAreaBorderWidth: 0,
              borderWidth: 0,
              margin: EdgeInsets.only(left: 0, right: 0, top: 10, bottom: 5),
              zoomPanBehavior: ZoomPanBehavior(
                enablePanning: true,
              ),
              // margin: EdgeInsets.only(left: 0, right: 0, top: 0, bottom: 5),
              legend: Legend(
                isVisible: true, 
                overflowMode: LegendItemOverflowMode.scroll, 
                position: LegendPosition.bottom,
                textStyle: ChartTextStyle(color: xLabelColor, fontWeight: FontWeight.w500, fontSize: labelSize),
                ),
              primaryXAxis: CategoryAxis(
                // zoomFactor: 0.9,
                visibleMaximum: 6.5,
                plotOffset: 10,
                isInversed: true,
                labelIntersectAction: AxisLabelIntersectAction.wrap,
                majorGridLines: MajorGridLines(width: 0),
                majorTickLines: MajorTickLines(size: 0),
                labelStyle: ChartTextStyle(color: xLabelColor, fontWeight: FontWeight.w500, fontSize: labelSize),
                axisLine: AxisLine(width: 0),
              ),
              primaryYAxis: NumericAxis(
                minimum: 0,
                maximum: 100,
                interval: 25,
                rangePadding: ChartRangePadding.none,
                axisLine: AxisLine(width: 0),
                majorTickLines: MajorTickLines(size: 0),
                labelStyle: ChartTextStyle(color: yLabelColor, fontWeight: FontWeight.w500, fontSize: labelSize),
                labelPosition: ChartDataLabelPosition.outside,
                majorGridLines: MajorGridLines(color: horizGridColor, width: horizGridWidth),
              ),
              series: dataContainer['stackedColumnSeries'],
              tooltipBehavior:
                  TooltipBehavior(enable: true, format: 'series.name', header: ''),
            ) 
```

**Comment by dharanidharandharmasivam** [comment]
Hi @opalr ,

Thanks for the revert. From the reported scenario, we suspect that you are using the lower version of our widgets and the issue might be due to this. So, kindly upgrade the chart widget package to **v18.1.36**. With the latest versions, the reported scenario will not occur. 

Thanks,
Dharani.
