### ISSUE TITLE
for syncfusion_flutter_calendar  i can not find any library for converting calendar to jalali calendar can you guys support jalali calendar as well. and thank your for your awsome projects.

### ISSUE THREAD

**Issue by evangelme** [syncfusion/flutter-examples#95]

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

As of now, we don’t have support for converting the calendar to jalali calendar. We have logged the feature request for the same. We will implement it in any of our upcoming releases. We appreciate your patience until then.

Now, you can track the current status of this feature request by using the below mentioned link.

Feedback link: https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-calendar-in-the-flutter-event-calendar

Also, in flutter event calendar we have support for RTL and Localization. Please find the following KB and UG links.

KB link for Localization: https://help.syncfusion.com/flutter/calendar/localization

UG link for Localization: https://www.syncfusion.com/kb/11246/how-to-localize-the-flutter-event-calendar

UG link for RTL: https://help.syncfusion.com/flutter/calendar/right-to-left

Note: The provided feedback link is private, you need to login to view this feedback.

**Comment by AliEasy** [comment]
any news?!
It's been years
