### ISSUE TITLE
TrackballBehaviour or Crosshair show error.

### ISSUE THREAD

**Issue by harshbarnwal** [syncfusion/flutter-examples#97]
I am implementing flutter charts and trying to show crosshair or trackball (trackball is preffered) at the newly added data (basically live) but,

`.show(x, y, "point")` <- this method is not working but
`.show(x, y, "pixel")` <- this method is working

then i tried .showAtIndex but also
`.showByIndex(list.length - 1)` <-  is not showing crosshair at latest data but
`.showByIndex(list.length - 2)` <-  is showing crosshair at the second latest data but i want to show it to latest data so it looks like live update 

also trackball is not even showing at all it just showing y axis data for candle or HiloClose Series as null but showing in line chart series.

**Comment by dharanidharandharmasivam** [comment]
Hi @harshbarnwal ,

Greetings from Syncfusion. We have analyzed your query, and we are aware of this scenario, the fix for this will be included in the next patch release which is going to be rolled out on April 7, 2020, and we appreciate your patience until then.

Regards,
Dharani.

**Comment by dharanidharandharmasivam** [comment]
Hi @harshbarnwal 

Thanks for being patience. The reported issue with public methods for trackball/crosshair has been fixed. To resolve the issue, kindly upgrade your chart package below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.44 

Thanks,
Dharani.
