### ISSUE TITLE
'point.close' is not parsed.

### ISSUE THREAD

**Issue by onurcanari** [syncfusion/flutter-examples#99]
I am using FinancialSeries. When i using tooltip format it parses

>  point.x point.y point.low point.high point.open. 

So i can get these values. But it is not parsing point.close. I couldn't find any documentation. Any help?

**Comment by dharanidharandharmasivam** [comment]
Hi @onurcanari ,

Greetings from Syncfusion. The reported scenario has been fixed already which is under the testing phase. This will be included in our upcoming patch release which is expected to be rolled out on April 7, 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @onurcanari , 
Thanks for your patience. The reported issue has been fixed. Now, the tooltipBehavior format property can parse point.close value. To overcome the reported issue, kindly upgrade the chart widget package below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.44.

Thanks,
Sriram Kiran.
